Fix all PythonScriptsTest for python3
mantidproject/mantid pull request #17883
Opened 2016-10-25 17:41 UTC by rosswhitfield

This **does not** fix all the files in `scripts` for python 3, just the ones that are needed to get the `PythonScripts` unit tests to pass.

**To test:**
 * Code review
 * Compile with python3, then run `ctest -R PythonScriptsTest`, they should all pass

*Does not need to be in the release notes.*

cc: @peterfpeterson @martyngigg 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-10-27 09:07 UTC, martyngigg requested changes

2016-10-27 09:07 UTC, martyngigg commented on scripts/SANS/isis_reduction_steps.py
> +    Most of this code is a copy-paste from __future__ import (absolute_import, division, print_function)
It looks like the `__future__` imports have not gone to the right place in the file.

2016-10-27 09:07 UTC, martyngigg commented on scripts/CryPowderISIS/cry_focus.py
> +# pylint: disable=too-many-arguments,unused-variable
Should there be a `__future__` import here?

2016-10-27 09:07 UTC, martyngigg commented on scripts/Interface/ui/reflectometer/refl_gui.py
> +# pylint: disable = too-many-lines, invalid-name, line-too-long, too-many-instance-attributes, too-many-branches,too-many-locals, too-many-nested-blocks
Should there be a `__future__` import here

2016-10-27 09:07 UTC, martyngigg commented on scripts/QECoverage.py
>  import sys
Should there be a __future__ import here

2016-10-27 11:49 UTC, rosswhitfield commented on scripts/Inelastic/Direct/RunDescriptor.py
> +            self._ws_cname = part_ind + ''.join(re.findall('\d+', name))
Whoops I missed the `not` and assumed it was the same the other `filter` cases I changed.

2016-10-27 12:05 UTC, rosswhitfield commented
In regards to adding `__future__` imports to the other files, I only wanted to add them to the files I spend time converting to python 3, _i.e._ the ones required for the unit tests to pass, so that it easy to tell which ones still needed working on. After this pull request only 65 out of 410 of the `*.py` files in `scripts` will have the `__future__` imports, there is still a lot of work remaining.

2016-10-31 09:32 UTC, martyngigg approved these changes

2016-10-31 09:33 UTC, martyngigg commented
This looks good to go now.

@mantidproject/gatekeepers let's :shipit: before conflicts start arising.

2016-10-31 09:35 UTC, merged