AppendSpectra now properly sets the values of TextAxis and NumericAxis
mantidproject/mantid pull request #17909
Opened 2016-10-31 10:47 UTC by DimitarTasev

TODO before PR Review:
- [ ] Unit tests to test the unique cases 
- [ ] (Other, Visual Studio debugger, Win7) Check if deleting the giant 9GB workspace created with script's performance test frees the memory 
Description of work.

`AppendSpectra` algorithm used to ignore the values of the TextAxis and NumericAxis labels and just append the spectra number. This is fixed in this PR and the algorithm now properly appends the value of TextAxis and NumericAxis, while keeping the old behaviour unchanged.

**To test:**
- I've made a quite long testing script, that I used to test all cases I could think of, it can be found here: https://gist.github.com/DimitarTasev/1c16fbfe60b95f8dff4845fbb7b02393
- Run unit tests and make sure they pass successfully
- Code review, changes aren't that big, but if you can think of any better way to handle the unique cases, please tell me

Fixes #17902 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-11-02 15:21 UTC, soininen requested changes

2016-11-02 15:21 UTC, soininen commented on Framework/Algorithms/src/AppendSpectra.cpp
> +    }
If I understood the above code right, you could also consider writing this if-else if-else thing the other way around:
```C++
  for (size_t i = 0; i < output->getNumberHistograms(); ++i) {
    if (isTextAxis) {
      const std::string inputLabel = i < ws1len ? yAxisWS1->label(i) : yAxisWS2->label(i - ws1len);
      outputTextAxis->setLabel(i, (inputLabel.size() > 0) ? inputLabel : "");
    }
    else if (isNumericAxis) {
      const double inputVal = i < ws1len ? yAxisWS1->getValue(i) : yAxisWS2->getValue(i - ws1len);
      outputYAxis->setValue(i, inputVal);
    }
    output->getSpectrum(i).setSpectrumNo(specnum_t(i));
  }
```
Less code duplication, no?

2016-11-02 15:21 UTC, soininen commented on Framework/Algorithms/test/AppendSpectraTest.h
> +    TS_ASSERT_THROWS_NOTHING(appendSpectra->execute());
To my understanding, call to execute() never throws, unless you do `appendSpectra->setRethrows(true);`.

2016-11-02 15:24 UTC, soininen commented
Is this also an issue in [`ConjoinWorkspaces`](http://docs.mantidproject.org/nightly/algorithms/ConjoinWorkspaces-v1.html)?

2016-11-03 08:45 UTC, DimitarTasev commented
@soininen Yes this is also an issue in [`ConjoinWorkspaces`](http://docs.mantidproject.org/nightly/algorithms/ConjoinWorkspaces-v1.html), the text axis was dropped

2016-11-07 09:15 UTC, DimitarTasev commented
Restarted [RHEL 10042](http://builds.mantidproject.org/job/pull_requests-rhel6/10042/) due to unrelated failure

2016-11-07 17:07 UTC, soininen approved these changes

2016-11-07 17:08 UTC, soininen commented
Everything seems to be in order. :shipit:

2016-11-08 08:38 UTC, merged