Fix broken unit test on Windows 7
mantidproject/mantid pull request #18028
Opened 2016-11-10 11:34 UTC by tom-perkins

The test `CustomInterfacesTest.ALCLatestFileFinderTest.test_getMostRecentFile` has been broken for the past couple of builds:
http://builds.mantidproject.org/job/master_clean-win7/327/testReport/CustomInterfacesTest/ALCLatestFileFinderTest/test_getMostRecentFile/

Each test creates temporary files that are deleted at the end of the test. This breaks when the tests are run in parallel - fix this by using a separate test directory for each test.

**To test:**

If all the tests pass then this should be OK. (On my Win7 machine these 4 tests all fail on current master.)

No issue number or release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-11-11 11:12 UTC, martyngigg commented
Code changes are good.

I ran all of the tests in parallel on the build machine and I no longer see a problem.

:shipit:

2016-11-14 14:51 UTC, quantumsteve requested changes

2016-11-14 14:51 UTC, quantumsteve commented on MantidQt/CustomInterfaces/test/ALCLatestFileFinderTest.h
> +  virtual ~ScopedDirectory() {
What inherits from this class?

2016-11-14 14:51 UTC, quantumsteve commented on MantidQt/CustomInterfaces/test/ALCLatestFileFinderTest.h
> +  std::string getDirectoryName() const { return m_dirName; }
Should this return a `const std::string &`?

2016-11-14 14:51 UTC, quantumsteve commented on MantidQt/CustomInterfaces/test/ALCLatestFileFinderTest.h
> +    files.emplace_back("2116-03-15T14:00:00", directory, "MUSR", "90002");
Would it make more sense to instead use a single initializer list?

2016-11-14 14:51 UTC, quantumsteve commented on MantidQt/CustomInterfaces/test/ALCLatestFileFinderTest.h
> +  const std::string m_dirName;
Are there downsides to having a const member variable? In particular, I'm concerned about copy and move assignment.

2016-11-14 15:11 UTC, tom-perkins commented on MantidQt/CustomInterfaces/test/ALCLatestFileFinderTest.h
> +  virtual ~ScopedDirectory() {
Nothing, but I made the destructor virtual just in case somebody inherited from it in future. Perhaps it is better to make the class `final`.

2016-11-15 12:00 UTC, quantumsteve approved these changes

2016-11-15 12:02 UTC, merged