Fix coverity warning in PDLoadCharacterizations
mantidproject/mantid pull request #18093
Opened 2016-11-22 16:20 UTC by peterfpeterson

This adds a constructor so default values for member variables can be set.

**To test:**

Just review the code

Fixes coverity issue 1366006.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-11-23 11:26 UTC, DavidFair commented
I think we can completely remove the constructor with some minor changes:
`hasExtras` isn't used within the code at all so this can easily be removed.

`canColumnNames` is a vector of strings which is used in two places - in `exec` and `readCharInfo`. In `readCharInfo` we use the size of the container to determine how much padding to apply so instead we can just hold this size_t as a member variable. If we use C++11 to initialize on declaration to 0 we no longer need the constructor. 

I've added a git patch file with these changes as I didn't want to start pushing to somebody elses branch (has to be a .txt file because of GitHub sigh): [PDLoadChara_changes.txt](https://github.com/mantidproject/mantid/files/608709/PDLoadChara_changes.txt)

2016-11-23 16:00 UTC, DavidFair commented on Framework/DataHandling/src/PDLoadCharacterizations.cpp
> +    for (size_t i = 14; i < num_of_columns; ++i) {
Could we put a comment on where 14 comes from?

2016-11-23 17:39 UTC, DavidFair commented
LGTM :shipit: once the tests finish

2016-11-28 02:18 UTC, quantumsteve requested changes

2016-11-28 02:18 UTC, quantumsteve commented on Framework/DataHandling/src/PDLoadCharacterizations.cpp
> +  for (const auto name : canColumnNames) {
`const auto &`?

2016-11-28 14:16 UTC, quantumsteve approved these changes

2016-11-28 14:17 UTC, quantumsteve commented
@peterfpeterson I'll merge this once the build finish.

2016-11-28 17:04 UTC, merged