Automatically Finding the Centre of Rotation on a Sample, and reconstruction script fixes
mantidproject/mantid pull request #18258
Opened 2016-12-12 15:52 UTC by DimitarTasev

Description of work.

**To test:**

Centre of Rotation Fixes #17995 
Reconstruction script changes Fixes #17914

[Release notes changes here](#did_dimitar_forget_to_add_the_link_again_they_are_in_imaging_rst_though)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-12-12 16:21 UTC, DimitarTasev commented on MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Tomography/TomographyCommandArguments.h
> +#ifndef MANTIDQTCUSTOMINTERFACES_TOMOGRAPHY_TOMOGRAPHYCOMMANDARGUMENTS_H_
File not part of PR. Will be removed

2017-01-09 16:27 UTC, DimitarTasev commented
Unit tests for the GUI and the System tests for the reconstruction scripts are bad and need to be re-designed and rewritten. That will be covered in #18386, the unit and system tests present are just changed so that they pass the build servers, and do not cause any problems to other people.

2017-01-13 08:52 UTC, DimitarTasev commented
A unit test that sometimes crashes locally has been removed in [commit 0797b90] (https://github.com/mantidproject/mantid/pull/18258/commits/0797b905e8d250e914a42d6f5896afe4fa6f5878). This is not a problem as the whole functionality is removed in the next PR: #18134

2017-01-24 12:28 UTC, DavidFair requested changes
Some minor changes and feedback

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyIfacePresenter.cpp
> +  setupAndRunLocalExternalProcess(!cachedExec.empty() ? cachedExec : runnable,
Could we split this operation out: `!cachedExec.empty() ? cachedExec : runnable` as there are several operations running within a function call meaning you have to read it very carefully

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyIfaceViewQtGUI.cpp
> +  m_tabROIW = new TomographyROIViewQtWidget(m_ui.tabMain);
Could we rename this from `m_tabROIW` to `m_tabROIWidget` as initially I thought it was `m_tabROIWindow`?

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyIfaceViewQtGUI.cpp
>    bool enable = 0 != status;
`bool enable (0 != status);` is much nicer to read. Additionally what does 0 represent in this case?

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyROIViewQtWidget.cpp
> +    return;
Should we maybe print a warning to the log as well as I'm guessing this is pretty exceptional?

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyROIViewQtWidget.cpp
> +  std::string output = str.toStdString();
`const`

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyROIViewQtWidget.cpp
> +  // -- to not be on the null character
Could we add a comment saying what the expected output is meant to be so people can see why we parse it like this

2017-01-24 12:28 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Tomography/TomographyROIViewQtWidget.cpp
> +  int cor = 0;
Could we have a more descriptive name than `cor` such as `centreOfRotationValue`?

2017-01-24 12:28 UTC, DavidFair commented on docs/source/release/v3.9.0/imaging.rst
> +- The reconstruction scripts will now run with TomoPy v1.x.x, however the output is not tested with versions newer than 0.10.x.
Is there any way to query TomoPy for its version an provide a warning for users at runtime?

2017-01-24 12:28 UTC, DavidFair commented on scripts/Imaging/IMAT/prep/filters.py
>      for vert_slice in range(len(rescaled_vol)):
Use `xrange` if rescaled_vol is large

2017-01-24 12:28 UTC, DavidFair commented on scripts/Imaging/IMAT/tomo_reconstruct.py
> +sys.path.insert(0, os.path.split(path.dirname(__file__))[0])  # noqa
WRGT sys.path.insert: http://stackoverflow.com/a/10097543

Additionally what are we appending to the system path - personally this line scares me, isn't this what virtual environments are for?

2017-01-24 12:28 UTC, DavidFair commented on scripts/Imaging/IMAT/tomo_reconstruct.py
> +        "rotation counterclocwise")
Typo - "counterclockwise"

2017-01-24 12:28 UTC, DavidFair commented on scripts/Imaging/IMAT/tomo_reconstruct.py
> +        "pixel. The output pixels are calculated as the average of the input pixel blocks."
Does that mean the output resolution is scaled down or is it the same resolution based on the interpolated values?

2017-01-24 12:28 UTC, DavidFair commented on scripts/Imaging/IMAT/tomorec/configs.py
> +            mystr += "Number of algorith iterations: {0}\n".format(
Typo "algorithm"

2017-01-24 12:38 UTC, DimitarTasev commented on MantidQt/CustomInterfaces/src/Tomography/TomographyROIViewQtWidget.cpp
> +    return;
The error will be printed out in the mantid log, and the job will have status `Exit`

2017-01-24 16:23 UTC, DavidFair approved these changes

2017-01-24 16:29 UTC, DavidFair commented
I have tested against Windows and Linux and the GUI works correctly following the testing instructions.

There was an issue running the centre of rotation with an invalid interpreter path then closing the interface crashing Mantid. This is an edge case so shouldn't affect the PR and an issue is opened here: #18532

The remaining comments on the .py scripts (typos mainly) aren't applicable as the scripts are in a completely different state as noted in the original description.

Once the final tests finish :shipit:

2017-01-24 21:25 UTC, merged