Allow Angle argument to FlatPlate dictionary for SetSample
mantidproject/mantid pull request #18251
Opened 2016-12-12 12:18 UTC by martyngigg

A flat plate sample shape can now be rotated about its own center using `SetSample`

**To test:**

Fixes #17194 

[RELEASE NOTES](https://github.com/mantidproject/mantid/commit/a6724b0f17c7d22e17004f701c47db2a10a8dbeb)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-12-22 08:53 UTC, soininen requested changes

2016-12-22 08:53 UTC, soininen commented on Framework/DataHandling/inc/MantidDataHandling/SetSample.h
> +                       const Kernel::PropertyManager_sptr &args);
I'm wondering why pass shared pointers as references? Also, would it be possible to use `PropertyManager_const_sptr` here? Only some getters are used in the method as far as I can see. Same for the `setSampleShape` method and maybe others in this class.

2016-12-22 08:53 UTC, soininen commented on Framework/DataHandling/src/SetSample.cpp
> +    auto refFrame = workspace->getInstrument()->getReferenceFrame();
I think `refFrame` could be delcared `const`.

2016-12-22 08:53 UTC, soininen commented on docs/source/algorithms/SetSample-v1.rst
>  expected along with additional keys specifying the values (all values are assumed to
While at it, you could perhaps fix the typo in the first sentence of the **Environment** subsection as well: 'enviorment' -> 'environment'.

2016-12-22 08:53 UTC, soininen commented on docs/source/algorithms/SetSample-v1.rst
> -                       'Center': [0.,0.,0.], 'Axis':1},
There is a space missing between the colon and '1'.

2016-12-22 09:08 UTC, soininen commented
Are there any plans to extend `SetSample::validateInputs()`? The algorithm seems to happily accept negative sample dimensions.

2016-12-22 09:16 UTC, martyngigg commented on Framework/DataHandling/inc/MantidDataHandling/SetSample.h
> +                       const Kernel::PropertyManager_sptr &args);
Passing the `shared_ptr`'s by const reference here just avoids increasing the reference count: http://stackoverflow.com/a/37610721. I know I have a reference to keep the object alive at the top level as this is all private. I would usually prefer a plain `const PropertyManager&` but it needs to be a `shared_ptr` to be fed into the child algorithm.  

You're right I can probably use `PropertyManager_const_sptr` here.

2016-12-22 09:16 UTC, martyngigg commented on Framework/DataHandling/src/SetSample.cpp
> +    auto refFrame = workspace->getInstrument()->getReferenceFrame();
:+1:

2016-12-22 09:16 UTC, martyngigg commented on docs/source/algorithms/SetSample-v1.rst
>  expected along with additional keys specifying the values (all values are assumed to
:+1:

2016-12-22 09:25 UTC, martyngigg commented
You're right, I should provide better checking for the basic cases such as negative dimensions. I'll update the code.

2016-12-23 07:44 UTC, martyngigg commented
@soininen I've added some changes after your feedback.

2016-12-23 10:57 UTC, soininen requested changes

2016-12-23 10:57 UTC, soininen commented on Framework/DataHandling/src/SetSample.cpp
> +            return true;
Couldn't you just `return !value.empty();`?

2016-12-23 10:57 UTC, soininen commented on Framework/DataHandling/src/SetSample.cpp
> +  //  // Validate as much of the shape information as possible
A bit nit-picking, but perhaps the comment needs some cleanup.

2016-12-23 11:22 UTC, martyngigg commented on Framework/DataHandling/src/SetSample.cpp
> +            return true;
Good point :man_facepalming:

2016-12-23 13:19 UTC, soininen approved these changes

2016-12-23 13:52 UTC, soininen commented
The new angle property seems to work as expected. The test script produces the expected cyclic pattern when the sample is rotated around [-180, 450] degrees. The input properties are validated more rigorously than before, and there are new units tests in place. I think we are done here :shipit:

2016-12-23 14:22 UTC, merged