Improve spherical and ellipsoidal integration
mantidproject/mantid pull request #18270
Opened 2016-12-13 13:55 UTC by VickieLynch

Description of work.
AdaptiveQ option was added to elliptical integration and top 1% of background events was removed from background of spherical integration.

**To test:**
```python
Load(Filename='MANDI_4376_event.nxs', OutputWorkspace='MANDI_4376_event')
ConvertToMD(InputWorkspace='MANDI_4376_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', LorentzCorrection=True, OutputWorkspace='MANDI_4376_md', MinValues='-25,-25,-25', MaxValues='25,25,25', SplitInto='2', SplitThreshold=50, MaxRecursionDepth=13, MinRecursionDepth=7)
FindPeaksMD(InputWorkspace='MANDI_4376_md', PeakDistanceThreshold=0.070650000000000004, MaxPeaks=50, DensityThresholdFactor=100, OutputWorkspace='MANDI_4376_peaks')
FindUBUsingFFT(PeaksWorkspace='MANDI_4376_peaks', MinD=3, MaxD=80, Tolerance=0.12)
CopySample(InputWorkspace='MANDI_4376_peaks', OutputWorkspace='MANDI_4376_event', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
IndexPeaks(PeaksWorkspace='MANDI_4376_peaks', Tolerance=0.12)
FindUBUsingFFT(PeaksWorkspace='MANDI_4376_peaks', MinD=3, MaxD=80, Tolerance=0.12)
CopySample(InputWorkspace='MANDI_4376_peaks', OutputWorkspace='MANDI_4376_event', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
IndexPeaks(PeaksWorkspace='MANDI_4376_peaks', Tolerance=0.12)
PredictPeaks(InputWorkspace='MANDI_4376_peaks', WavelengthMin=2, WavelengthMax=4, MaxDSpacing=15, OutputWorkspace='MANDI_4376_peaks')
FindUBUsingFFT(PeaksWorkspace='MANDI_4376_peaks', MinD=3, MaxD=80, Tolerance=0.12)
CopySample(InputWorkspace='MANDI_4376_peaks', OutputWorkspace='MANDI_4376_event', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
IndexPeaks(PeaksWorkspace='MANDI_4376_peaks', Tolerance=0.12)
PredictPeaks(InputWorkspace='MANDI_4376_peaks', WavelengthMin=2, WavelengthMax=4, MaxDSpacing=80, OutputWorkspace='MANDI_4376_peaks')
ConvertToMD(InputWorkspace='MANDI_4376_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', OutputWorkspace='__MantidEVWorker_sphere_integrate_temp_MD_ws', MinValues='-30,-30,-30', MaxValues='30,30,30', SplitInto='2,2,2', SplitThreshold=200, MaxRecursionDepth=10, MinRecursionDepth=7)
IntegratePeaksMD(InputWorkspace='__MantidEVWorker_sphere_integrate_temp_MD_ws', PeakRadius=0.10000000000000001, BackgroundInnerRadius=0.10000000000000001, BackgroundOuterRadius=0.12, PeaksWorkspace='MANDI_4376_peaks', OutputWorkspace='MANDI_4376_peaks', AdaptiveQBackground=True, AdaptiveQMultiplier=0.10000000000000001)
IntegrateEllipsoids(InputWorkspace='MANDI_4376_event', PeakSize=0.10000000000000001, BackgroundInnerSize=0.10000000000000001, BackgroundOuterSize=0.12, PeaksWorkspace='MANDI_4376_peaks2', OutputWorkspace='MANDI_4376_peaks', AdaptiveQBackground=True, AdaptiveQMultiplier=0.10000000000000001)
```

Fixes #18070

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2016-12-20 11:16 UTC, soininen commented
Is the file needed for the tests available somewhere?

2016-12-20 12:36 UTC, VickieLynch commented
@soininen https://www.dropbox.com/s/40kyog3a38n70en/MANDI_4376_event.nxs?dl=0

2016-12-21 08:49 UTC, soininen requested changes
In addition to responding the comments on the code itself, the html documentation should be updated for both algorithms to reflect the changes.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +	  }
Seems to be that hard tabs are used here for indentation. Please use spaces instead.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +  } else{
Space after `else`.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +	  for (const auto & it :events) {
No space between `&` and `it`, space before `events`.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +	      //errorSquared += static_cast<signal_t>(it.getErrorSquared());
Why the commented-out code?

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +	  std::sort(errsqVec.begin(), errsqVec.end(), MyComparator(eventVec));
Did you consider using a lambda function instead of `MyComparator` here?

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDGridBox.tcc
> +                                      signal_t &errorSquared, const coord_t innerRadiusSquared) const {
While it seems these .tcc files are not handled by clang-format, you could still consider avoiding long lines like this.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/inc/MantidDataObjects/MDGridBox.tcc
> +      if (out[0] < diagonalSquared * 0.72 + radiusSquared || out[0] < diagonalSquared * 0.72 + innerRadiusSquared) {
Long line.

2016-12-21 08:49 UTC, soininen commented on Framework/DataObjects/test/MDBoxBaseTest.h
> +                       const coord_t /*innerRadiusSquared*/) const override{};
There should be a space between `override` and the brackets.

2016-12-21 08:49 UTC, soininen commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +                  "BackgroundInnerRadius + AdaptiveQMultiplier * **|Q|**");
Have you checked how the double asterisks around the `|Q|` appear in the html documentation? At least [here](http://docs.mantidproject.org/nightly/algorithms/IntegratePeaksMD-v2.html) they seem a bit confusing to me.

2016-12-21 08:49 UTC, soininen commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +  declareProperty("AdaptiveQMultiplier", 0.0,
Would it make sense adding a validator here checking *AdaptiveQMultiplier* >= 0?

2016-12-21 08:49 UTC, soininen commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +        lenQpeak = 0.0;
This statement is superfluous.

2016-12-21 08:49 UTC, soininen commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +      double adaptiveRadius = adaptiveQMultiplier * lenQpeak + peak_radius;
`adaptiveRadius` coulde declared `const`, no?

2016-12-21 08:49 UTC, soininen commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +      double adaptiveBack_outer_radius =
Could both the radius above be declared `const`?

2016-12-21 09:32 UTC, soininen commented
How about the unit tests for these changes?

2017-01-03 15:29 UTC, VickieLynch commented on Framework/DataObjects/inc/MantidDataObjects/MDBox.tcc
> +	  std::sort(errsqVec.begin(), errsqVec.end(), MyComparator(eventVec));
Not sure how to use lambda function since I am sorting the errorSquared vector by the values from the signal vector.

2017-01-03 15:41 UTC, VickieLynch commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +  declareProperty("AdaptiveQMultiplier", 0.0,
I recently had to change this so instrument scientist could use negative values.  The intensity is set to zero for negative radius. #17945

2017-01-03 16:42 UTC, VickieLynch commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +                  "BackgroundInnerRadius + AdaptiveQMultiplier * **|Q|**");
The asterisks are to make it bold and they were all fine except for the inner background which I fixed.

2017-01-03 18:39 UTC, VickieLynch commented on Framework/DataObjects/test/MDBoxBaseTest.h
> +                       const coord_t /*innerRadiusSquared*/) const override{};
clang-format removed the space

2017-01-04 08:34 UTC, soininen commented on Framework/DataObjects/test/MDBoxBaseTest.h
> +                       const coord_t /*innerRadiusSquared*/) const override{};
I see. Interesting.

2017-01-04 09:08 UTC, soininen approved these changes

2017-01-04 09:14 UTC, soininen commented
Tested with the script provided in the PR's description and the changes seem to work as expected. Documentation, release notes and unit tests are in place so I think this is good to go :shipit:

2017-01-04 13:21 UTC, merged