Indirect Absorption - Update Sample Geometry
mantidproject/mantid pull request #18282
Opened 2016-12-14 14:50 UTC by louisemccann

The Indirect Absorption Interface has been updated to calculate the absorption corrections using the Monte Carlo method. The algorithms have been refactored to use this method and implemented as version 2 of each respective absorption algorithm.

**To test:**

`\\olympic\babylon5\Public\Louise McCann\Corrections`

Sample: `irs26176_graphite002_red`
Container: `irs26174_graphite002_red`

Interfaces>Indirect>Corrections>Absorption

Use 1cm or 2 cm for sample/container dimensions, given that `container inner < sample inner < sample outer < container outer`

Sample: `H2_O` Mass Density: `1` Number Density: `0.03`
Container: `V` Mass Density: `6` Number Density: `0.07`
Test every possible combination of inputs for container options and FlatPlate/Annulus/Cylinder geometry.
If algorithm runs slowly reduce the number of events.

Fixes #16843 

[Release Notes](https://github.com/mantidproject/mantid/blob/c647a6efe1d4785475b4620d93d9b6669835ea45/docs/source/release/v3.9.0/indirect_inelastic.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-10 13:12 UTC, SpencerHowells commented
Sample angle default should be 0.0. This corresponds to sample perpendicular to beam - the fixed value in the FlatPlateAborption algo.

2017-01-11 14:17 UTC, louisemccann commented
This PR will also close #18214

2017-01-20 09:18 UTC, gvardany requested changes
Could you please update also the GUI tab documentation?
The v2 of the algorithms need their own documentation `-v2.rst` pages.
Could you add a line `Fixes #18214 ` in main PR message, so the second issue will also close itself.

2017-01-20 11:03 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectFlatPlateAbsorption2.py
> +    _sample_angle=None
spaces around `=`

2017-01-20 11:03 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectFlatPlateAbsorption2.py
> +        # Hard-coded because the ISIS parameters weren't being picked up
What is the problem here, that the parameters cannot be retrieved? What about instrument other than IRIS/OSIRIS?

2017-01-25 10:22 UTC, martyngigg commented
Does it make sense to include this in 3.9? I see the "in progress" label has been added but it seems that @gvardany's comments have been addressed?

It would be good to get the `MonteCarloAbsorption` out in the wild.

2017-01-25 12:15 UTC, gvardany commented
Actually I had not reviewed fully yet, but I can do now if this is a priority. Those were just some general remarks.

2017-01-25 12:18 UTC, martyngigg commented
@gvardany If you have time that would be great.

2017-01-25 14:29 UTC, gvardany commented
I have found few issues so far below, I am still testing with various other options though:

1. In this configuration I still get:
![screen shot 2017-01-25 at 15 04 45](https://cloud.githubusercontent.com/assets/16865759/22293392/aac23f64-e30f-11e6-86b5-ee0a20ede349.png)

> Instrument has no default beam size; will use inputs
> MonteCarloAbsorption: Object::generatePointInObject() - Unable to generate point in object after 500 attempts
> Error in execution of algorithm MonteCarloAbsorption:
> MonteCarloAbsorption: error (see log)
> Error in execution of algorithm IndirectFlatPlateAbsorption
> MonteCarloAbsorption: error (see log)
>   at line 165 in '/Users/vardanyan/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectFlatPlateAbsorption2.py'
>   caused by line 926 in 'mantid/simpleapi.py'
> Got error from algorithm "IndirectFlatPlateAbsorption"
> Stopping batch algorithm because of execution error


2. When I increase the sample width to 0.2, the second problem goes away, but this error remains

> Instrument has no default beam size; will use inputs

3. In this configuration, I get error on can radius, even if use can is unchecked. 
![screen shot 2017-01-25 at 15 11 08](https://cloud.githubusercontent.com/assets/16865759/22293627/a2a13e88-e310-11e6-86f8-fbf04989cc98.png)

>Instrument has no default beam size; will use inputs
>Invalid value for CanRadius: Must be greater than SampleRadius
>Unknown error starting next batch algorithm
>Got error from algorithm "IndirectCylinderAbsorption"
>Stopping batch algorithm because of execution error

4. In any case when `NumberOfWavelengthPoints < 4`, I get e.g.:

> MonteCarloAbsorption: interpolate - CSpline requires 4 points but only 3 were found.

I thinks this is more of an issue in MonteCarloAbsorption, that might need to fall back to linear interpolation if Spline is requested but not enough points are given. Note that eventually we want to use this even for `NumberOfWavelengthPoints = 1`.

5. In `validateInputs` of FlatPlate, the can chemical formula is not checked.

6. In `_test_workspaces` in unit tests I would assert also at least the block size and the number of histograms in output and corrections workspaces.

7. `_getEFixed` seems identical across all the 3, maybe it is worth considering to move it to IndirectCommons ? I am not sure however.

8. Ideally the input validation should also be handled in the GUI, to catch the problems before executing the algorithms.

9. In the documentations I would make explicit that these new versions use MonteCarloAbsorption, with a link to it. And optionally for the older versions make a link to the non-MC algorithms used previously. 

10. Finally, the flowcharts should also be adjusted to accommodate the new change.

2017-01-25 14:57 UTC, SpencerHowells commented
4. I've spoken to Martyn and this should be changed in MonteCarloAbsorption.
7. We have been deliberately moving _getEFixed from IndirectCommon to the algo  so that it is properly tested instead of being in a script file.
8. I've checked on this and input validation should always be at the lowest level. Users may also want to use the algo on its own or in a script file.

2017-01-25 15:00 UTC, gvardany commented
Assuming you meant 4, 7, 8
4. OK
7. OK
8. I did not mean that they should be removed from the algorithms. They should be both in the algorithms, and in GUI.

2017-01-25 16:28 UTC, louisemccann commented
@gvardany I agree with you with regards to documentation - however  it could also be done in a new PR for documentation updates as maintenance.
 I think that updating the unit tests to include blocksize etc, although a valid point, is not vital for this release and would also be better suited for a separate PR so that I can update any other Indirect unit tests that don't have this check.

2017-01-25 16:30 UTC, gvardany commented
Yes I agree these are not critical, they can go to a separate ticket.

2017-01-25 17:15 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectAnnulusAbsorption2.py
> +        default = self.getPropertyValue('DefaultBeamSize')
getPropertyValue returns string representation, so both true and false will count as true.
You must use getProperty().value to get the right behaviour, the same in other algorithms.

2017-01-25 17:16 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectAnnulusAbsorption2.py
> +        if default and (has_beam is False):
`if default and not has_beam`

2017-01-25 17:27 UTC, gvardany commented
When I load the `IRS26176.RAW` file, `.getInstrument().hasParameter('Workflow.beam-width')` returns `True`, while for `irs26176_graphite002_red` reduced file it is `False`.  Is there any explanation to this?

2017-01-25 18:14 UTC, SpencerHowells commented
The Reduction routine loads the parameters from the IPF. The raw file does not have this info.

2017-01-25 18:17 UTC, SpencerHowells commented
I've just re-read the comment & the info is the wrong way round! I don't understand it.

2017-01-25 18:20 UTC, SpencerHowells commented
Have you seen Issue 18546 ? Do we have this problem?

2017-01-26 08:41 UTC, gvardany commented
Regarding the parameters, it seems like all the parameters starting from `cm-1-convert-choice` in the master parameter file are absent from the existing reduced file `irs26176_graphite002_red`. However when I reduce the raw file anew, the output has them. Can it be that these test files have been generated before these parameters were added or something alike?

2017-01-26 08:46 UTC, SpencerHowells commented
I think you've found the answer.

2017-01-26 08:49 UTC, gvardany commented
Regarding the issue #18546 ,  I have not encountered it, because on my system the decimal delimiter is `.`. But I am not surprised about it, I think there could be few more places (at least one on my side), e.g. whenever a `,` separated array of doubles are passed from GUI to backend, this may potentially break if the system uses `,` as the decimal point. Maybe it is worth to do a detailed walk-through the interfaces (not only indirect) with both system locale settings.

2017-01-26 08:57 UTC, SpencerHowells commented
It was a coincidence because I noticed on your screenshots of the GUI that it is using ,

2017-01-26 09:13 UTC, gvardany commented
You are right, I was confused about the issue message 😃 . This issue is about `Interfaces -> General -> Sample Transmission Calculator`. The problem there is when the `Rebin` parameter string is formed from the Qt elements.

2017-01-26 09:20 UTC, SpencerHowells commented
That interface was written by one of us! So we may have others with the same problem.

2017-01-26 09:56 UTC, gvardany commented
I have one more suggestion to make the view more intuitive. This can also go to a follow-up ticket.

![screen shot 2017-01-26 at 09 53 05](https://cloud.githubusercontent.com/assets/16865759/22327134/f4a6e6f6-e3b5-11e6-8be6-db0b94cba2ea.png)

2017-01-26 11:26 UTC, gvardany commented
Regarding 1: Indeed, when `x-y` profile of the sample seen by the beam is ~O(100) smaller compared to the lateral beam profile, the MonteCarlo generator often fails to generate a valid track, since it has an inherent limit of `500` attempts. Of course this limit value is arguable, but there has to be one. The only way I see is to catch the error in MonteCarloAbsorption, if possible, and just better formulate the error message. One might also try to compare these profiles beforehand and warn that this might happen. I think this is beyond the scope of this PR anyway.

2017-01-26 11:30 UTC, gvardany commented
One more note on the GUI: Please make explicit that sample angle is in degrees. Also maybe add a tooltip, that it is the angle from x-axis, so 0 means it is perpendicular to the beam.

2017-01-26 15:43 UTC, gvardany commented
I have created the follow up tickets for v3.10 : #18576, #18577, #18579 . This one can be :shipit: once tests pass.

2017-01-26 15:44 UTC, gvardany approved these changes

2017-01-27 08:00 UTC, martyngigg commented
Failing test is some intermittent problem with the matplotlib test in MantidPlot and unrelated.

2017-01-27 08:01 UTC, merged