VSI performance checks
mantidproject/mantid pull request #18348
Opened 2016-12-30 16:25 UTC by quantumsteve

Description of work.

This applies changes suggested by the [clang-tidy performance-* checks](http://clang.llvm.org/extra/clang-tidy/checks/list.html). Reviewing these changes, I found a few more places to reduce the number of unnecessary copies.  

I don't think these changes are in hot loops that would be obvious to end users. 

**To test:**

Review code changes and builds status. If you notice a significant performance improvement, let's add it to the release notes.

There is no GitHub issue associated with this pull request

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-06 10:30 UTC, soininen requested changes

2017-01-06 10:30 UTC, soininen commented on Vates/VatesAPI/inc/MantidVatesAPI/PresenterFactories.h
> +  getWorkspaceName(const Mantid::API::IMDWorkspace & /*workspace*/);
I thought we were trying to remove the comments from argument names in these cases, but I guess there is no project-wide policy on this.

2017-01-06 10:30 UTC, soininen commented on Vates/VatesAPI/inc/MantidVatesAPI/vtkDataSetFactory.h
> +
Usually, there is no empty line here.

2017-01-06 10:30 UTC, soininen commented on Vates/VatesAPI/src/PresenterFactories.cpp
> +  return name;
Why not just `return "__EmptyWorkspaceNamePolicy"`?

2017-01-06 17:21 UTC, quantumsteve commented on Vates/VatesAPI/src/PresenterFactories.cpp
> +  return name;
One can't return a non-static local variable by reference.

2017-01-06 17:30 UTC, quantumsteve commented on Vates/VatesAPI/inc/MantidVatesAPI/PresenterFactories.h
> +  getWorkspaceName(const Mantid::API::IMDWorkspace & /*workspace*/);
@mantidproject/tech-steering How should we mark unused arguments? Do we have or want to set a standard? 

FWIW I prefer commenting out the name vs. using the `UNUSED_ARG` macro or leaving it blank.

2017-01-09 09:32 UTC, soininen commented on Vates/VatesAPI/src/PresenterFactories.cpp
> +  return name;
Yes, indeed one can't.

2017-01-09 09:34 UTC, soininen commented on Vates/VatesAPI/inc/MantidVatesAPI/PresenterFactories.h
> +  getWorkspaceName(const Mantid::API::IMDWorkspace & /*workspace*/);
I have been using `UNUSED_ARG` but I have no strong feelings either way.

2017-01-09 09:35 UTC, soininen approved these changes

2017-01-09 09:40 UTC, soininen commented
Nice tidying here. I don't think the unused function argument discussion above is a blocking issue, so by all means :shipit:

2017-01-09 09:43 UTC, martyngigg commented on Vates/VatesAPI/inc/MantidVatesAPI/PresenterFactories.h
> +  getWorkspaceName(const Mantid::API::IMDWorkspace & /*workspace*/);
@quantumsteve Does Doxygen cope with the commented out names?

My preference would be `UNUSED_ARG` as it's in more active use (I think) but I don't have strong feelings either way.

2017-01-09 09:44 UTC, merged