Change IMDDimension::getName() to name.
mantidproject/mantid pull request #18359
Opened 2017-01-04 13:04 UTC by quantumsteve

Description of work.

**To test:**

Fixes #xxxx.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-10 09:54 UTC, soininen requested changes

2017-01-10 09:54 UTC, soininen commented on docs/source/release/v3.9.0/framework.rst
> +
A C++ illiterate Python user might not understand what this means.

2017-01-10 14:55 UTC, quantumsteve commented
@soininen How would you recommend reformatting the release notes?

2017-01-10 15:06 UTC, soininen commented
@quantumsteve 
Would
```
- The function `IMDDimension.getName()` has been deprecated. Use the attribute `IMDDimension.name` instead.
```
sound more pythonish?

2017-01-11 23:05 UTC, quantumsteve commented
@soininen So that the style is consistent, I also updated my release notes from #18350.

2017-01-12 07:11 UTC, soininen approved these changes

2017-01-12 07:14 UTC, soininen commented
Nice changes. :shipit:

2017-01-12 08:53 UTC, merged