In & out of plane angle tool.
mantidproject/mantid pull request #18374
Opened 2017-01-06 12:02 UTC by samueljackson92

Added a tool to the instrument view that allows the user to select three crystal peaks in detector space and use these to define a plane. A fourth peak can then be selected and the in plane and out of plane angle between the peaks will be calculated.

**To test:**

 - Load some single crystal data and open the instrument view
 - Create at least 4 single crystal peaks (or any points on the instrument)
 - Choose the new alignment tool
 - Select 3 peaks to form a plane
 - Select a 4th peak to show the in-plane (theta) and out-of-plane (phi) angle of that peak

Note: the phi angle should always be calculated relative to the beam direction for the instrument i.e. `phi==0` is the beam direction.

Fixes #18120 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-23 10:11 UTC, soininen commented
@samueljackson92 Please resolve the merge conflicts.

2017-01-23 14:54 UTC, soininen commented
I tried testing this with some MANDI data that is available in Mantid's unit test data, but the 'Add single crystal peak' tool in the Instrument view does not seems to do anything. Any hints what I might be doing wrong here?

2017-01-23 15:04 UTC, samueljackson92 commented
@soininen First click on a detector, then click on the 1D histogram at the bottom left of the screen where you see a peak to choose a position along the x axis.

2017-01-23 16:53 UTC, soininen commented
If I create several peaks and start clicking them with the new tool, the first three peaks get highlighted by a blue circle but afterwards the circles remain there while the phi and theta angles changes. Is this intended behavior? How do I know which peaks actually define the plane and which peak gives the angles?

2017-01-23 16:57 UTC, soininen commented
Another question: If I create a bunch of peaks close to each other so that the square selection(?) region of the angle tool covers several of them, I quickly run into theta: -nan phi: -nan, a state from which the tool does not seem to recover.

2017-01-24 07:38 UTC, samueljackson92 commented
@soininen Yes. The three highlighted peaks are used as points which to define a plane in Q. Clicking a 4th peak should calculate the in plane and out of plane angles to the plane defined by those points. Start again you an right click -> clear plane.

I'll take a look at the second point. Are you seeing this when you're trying to define a plane (1st, 2nd, or 3rd click), or taking angles to it (4th click)?

2017-01-24 08:26 UTC, soininen commented
@samueljackson92 I did a bit more experimenting, and it seems the `-nan` issue is not about the closeness of the peaks. If I hold the mouse button and drag while selecting the either of first two reference plane peaks, the tool seems to get confused and give these `-nan` values.

2017-01-24 08:30 UTC, samueljackson92 commented
@soininen I think you might be correct. I shall try...

2017-01-24 08:41 UTC, soininen requested changes

2017-01-24 08:41 UTC, soininen commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  auto pos3 = planePeaks[2];
Would it make sense to check here if the positions were unique? Otherwise you cannot define a plane.

2017-01-24 08:45 UTC, samueljackson92 commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  auto pos3 = planePeaks[2];
I was actually thinking of doing it earlier on in ProjectionSurface, so that the event does not fire until you have uniquely defined points.

2017-01-24 08:45 UTC, samueljackson92 commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  auto pos3 = planePeaks[2];
But while we're here these could probably be `const`.

2017-01-24 08:48 UTC, soininen commented
By the way, would it make sense to highlight the 4th peak with similar circle as the first three but using a different color?

2017-01-24 14:45 UTC, samueljackson92 commented
@soininen The `nan` issue should be corrected now, I fixed the merge conflicts, and I added a green highlight to the 4th peak.

2017-01-24 23:56 UTC, AndreiSavici requested changes

2017-01-24 23:56 UTC, AndreiSavici commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  const auto proj = beam - n * (beam.scalar_prod(n) / (pow(n.norm(), 2)));
use `n.norm2()`
Also, is it possible that `n` and `beam` are parallel?

2017-01-24 23:56 UTC, AndreiSavici commented on docs/source/release/v3.9.0/ui.rst
> +- New tool for computing in-plane and out-of-plane angles in Qlab space for crystal alignment.
Where is the documentation of what the angles mean? Do you have some formulas to compare to? My guess is that 4 peaks is too much. I would use 2 peaks + sample to define plane, but I am open to be persuaded (that's why I need documentation) that this is the correct approach

2017-01-25 07:39 UTC, samueljackson92 commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  const auto proj = beam - n * (beam.scalar_prod(n) / (pow(n.norm(), 2)));
1) Sure. 2) Good spot. It is but it's unlikely. I can put something in to handle that case.

2017-01-25 07:54 UTC, samueljackson92 commented on docs/source/release/v3.9.0/ui.rst
> +- New tool for computing in-plane and out-of-plane angles in Qlab space for crystal alignment.
No and nothing specific. I was going to add an entry [here](http://www.mantidproject.org/MantidPlot:_Instrument_View) after the PR went through.

theta -> elevation angle from plane defined by the three peaks to the 4th peak
phi -> in plane angle with reference to the beam direction

Actually I think you're correct and you could just use 2 + sample here.

2017-01-25 08:37 UTC, soininen commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  auto R = p.norm();
Both `p` and `R` could be constants, I think.

2017-01-25 09:08 UTC, samueljackson92 commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  auto R = p.norm();
Yes.

2017-01-25 13:10 UTC, soininen approved these changes

2017-01-25 15:11 UTC, AndreiSavici commented on MantidQt/MantidWidgets/src/InstrumentView/InstrumentWidgetPickTab.cpp
> +  const auto pos4 = peak->getQSampleFrame();
Minor thing: you should rename this to pos3

2017-01-25 15:12 UTC, AndreiSavici approved these changes

2017-01-25 15:13 UTC, AndreiSavici commented
The changes are OK. Adding documentation to the instrument view on wiki is OK

2017-01-25 18:25 UTC, AndreiSavici commented
Ubuntu failures are unrelated.

2017-01-26 11:58 UTC, martyngigg commented
@AndreiSavici Is this ready to merge?

2017-01-26 13:03 UTC, soininen commented
@samueljackson92 The mouse dragging issue seems to be still there: if I hold down the mouse button, the same peak get selected twice for the reference plane and then all angles will be 0.

2017-01-26 13:12 UTC, samueljackson92 commented
@soininen I can't reproduce this? For me, if I click & drag the peak is selected as blue. When clicking and dragging on the second peak it goes green. But that kind of makes sense, you selected it as a plane defining peak then also selected it (on the second second click event) to compare to the plane.

2017-01-26 13:21 UTC, soininen commented
@samueljackson92 On my system, if I drag the mouse over the first peak, I think the peak gets selected as the second peak as well. This does not make sense because then you cannot define the alignment plane and whatever peak you select as the third peak give zeros for theta and phi. If you mistakenly drag the mouse while selecting the first peak, you have to clear the alignment plane and start again.

2017-01-26 13:28 UTC, samueljackson92 commented
@soininen Hmm. I agree that is probably what you are seeing, but I still can't reproduce even if I click and drag over the first peak. What instrument are you using? MANDI? Can you maybe send me a copy of the data and the peaks you're using?

2017-01-26 13:36 UTC, soininen commented
@samueljackson92 Can you first try it by just selecting the same peak twice (as the 1st and 2nd peak)? I'm indeed using a Mandi workspace here, and need to find a way to send it to you. I create the peaks quite randomly around the instrument view using the 'Add single crystal peak' tool.

2017-01-26 13:40 UTC, soininen commented
@samueljackson92 Hopefully the file is still available [here in Dropbox](https://www.dropbox.com/s/40kyog3a38n70en/MANDI_4376_event.nxs?dl=0)

2017-01-26 13:41 UTC, samueljackson92 commented
@soininen That is what I'm doing. Both by individually (without holding) clicking on a peak, releasing,  then clicking again on the same peak immediately afterwards, and also separately by clicking, holding & dragging over a single peak. Neither way causes the issue you're seeing for me.

Thanks for the file!

2017-01-26 13:53 UTC, samueljackson92 commented
@soininen Ah ha! Now I can reproduce :) - Seems that when MANDI data and selecting peaks you also don't get any red peak markers displayed either?

2017-01-26 13:56 UTC, soininen commented
@samueljackson92 I just checked that I'm running the correct commit and clean-build all, but the issue is still there. Does the tool accept the 2nd peak only if it differs from the 1st peak? Is there such a check?

2017-01-26 13:57 UTC, soininen commented
@samueljackson92 Red markers? I guess I don't :)

2017-01-26 14:04 UTC, samueljackson92 commented
@soininen I think the issue is when I added the check to see if the peak is already in use I used Qlab instead of sample (doh!). On the dataset I was using these happened to be the same. In your dataset they are different. I will fix that now.

Yes you should see red markers indicating the position of the peak you selected and (if set) the HKL for the peak. But I think that might be a separate issue beyond scope of this work. I will check that also

2017-01-26 14:09 UTC, samueljackson92 commented
@soininen Markers don't appear to show up in 3.8 either, so I assume that is an unrelated issue. I will make a new issue for that.

New commit should hopefully fix the problem you're seeing. Please kindly retest when you have time.

2017-01-26 14:16 UTC, samueljackson92 commented
New issue for peak markers & event data is #18571

2017-01-26 15:01 UTC, soininen commented
The issues seem indeed be gone now. I think this is good to go :shipit:

2017-01-26 15:39 UTC, martyngigg commented
Is this still aiming for `3.9`?

2017-01-26 15:41 UTC, samueljackson92 commented
Ideally.

2017-01-26 15:43 UTC, martyngigg commented
Ok. Can you change the base branch, please?

2017-01-26 17:26 UTC, samueljackson92 commented
@martyngigg Done.

2017-01-27 07:59 UTC, merged