Fix log splitting issue in FilterEvents
mantidproject/mantid pull request #18387
Opened 2017-01-09 17:02 UTC by wdzhou

Description of work.

**To test:**

Fixes #16756.
Fixes #12535.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-10 17:00 UTC, wdzhou commented
** Road Map**

1. Complete all the unit test;
2. Try to replace linear search in splitting by binary search;
3. Speed test on large log (e.g. proton charge) with relatively high frequency splitters;
4. Get data from Garrett for his pulse magnetic data;

2017-03-14 20:19 UTC, peterfpeterson requested changes
Looks good other than changing some log levels

2017-03-15 02:20 UTC, wdzhou commented on Framework/Algorithms/src/FilterEvents.cpp
> +    g_log.warning() << "There are " << split_tsp_vec.size()
Fixed in the last commit.

2017-03-15 02:20 UTC, wdzhou commented on Framework/Algorithms/src/FilterEvents.cpp
> +      g_log.warning() << "Output workspace index: " << miter->first << "\n";
Fixed in the last commit.

2017-03-15 12:07 UTC, peterfpeterson approved these changes

2017-03-16 11:47 UTC, peterfpeterson commented
:shipit:

2017-03-16 16:02 UTC, merged