Fix unintentional modification of container workspace and make rebinning optional in ApplyPaalmanPingsCorrection
mantidproject/mantid pull request #18398
Opened 2017-01-10 14:49 UTC by soininen

[`ApplyPaalmanPingsCorrection`](http://docs.mantidproject.org/nightly/algorithms/ApplyPaalmanPingsCorrection-v1.html) was accidentally applying [`RebinToWorkspace`](http://docs.mantidproject.org/nightly/algorithms/RebinToWorkspace-v1.html) to the input *CanWorkspace*. This PR fixes the behavior and also makes the rebinning optional as it is not always desirable. For example, if both *SampleWorkspace* and *CanWorkspace* have varying bins, `RebinToWorkspace` would rebin the container workspace incorrectly.

**To test:**

Before applying these changes, running
```python
import numpy

xs = numpy.array([0.0, 1.0, 0.0, 1.1])
ys = numpy.array([2.2, 3.3])
sample_1 = CreateWorkspace(DataX=xs, DataY=ys, NSpec=2, UnitX='Wavelength')
ys = numpy.array([0.11, 0.22])
container_1 = CreateWorkspace(DataX=xs, DataY=ys, NSpec=2, UnitX='Wavelength')
corrected = ApplyPaalmanPingsCorrection(SampleWorkspace=sample_1, CanWorkspace=container_1)
print(container_1)
```
would cause `container_1` to get rebinned, and sometimes raise an exception at the last `print` statement. This should not happen anymore.

Further, to test the optional rebinning, one could run the following script:
```python
import numpy

xs = numpy.array([0.0, 1.0, 0.0, 1.1])
ys = numpy.array([2.2, 3.3])
sample_1 = CreateWorkspace(DataX=xs, DataY=ys, NSpec=2, UnitX='Wavelength')
xs = numpy.array([-0.1, 0.5, 1.1, -0.1, 0.5, 1.2])
ys = numpy.array([0.11, 0.22, 0.33, 0.44])
container_1 = CreateWorkspace(DataX=xs, DataY=ys, NSpec=2, UnitX='Wavelength')
corrected = ApplyPaalmanPingsCorrection(SampleWorkspace=sample_1, CanWorkspace=container_1, RebinCanToSample='Rebin Can')
```
In the above, setting *RebinCanToSampe* to 'Do Not Rebin Can' should make the algorithm fail due to incompatible sample and container workspaces.

Fixes #18383.

*The release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-10 14:58 UTC, SpencerHowells commented
The RebinToWorkspace for the container is deliberately there to prevent the User from using different energy ranges and producing a rubbish result. Also, there is an option to shift the energy for the container which again requires a rebin. Making it optional is not what I want for our use.

2017-01-10 15:24 UTC, soininen commented
@SpencerHowells `RebinToWorkspace` does not work for our use cases where we have varying bins in the workspaces. `RebinToWorkspace` will take the binning of the first spectra of the sample workspace and apply it to all the spectra in the container workspace thus destroying the varying bins.

Further, *RebinCanToSample* is optional and its default value is set to enable rebinning so the algorithm works exactly as before, unless *RebinCanToSample* is deliberately set to 'Do Not Rebin Can'.

2017-01-10 16:28 UTC, SpencerHowells commented
I see your problem. You need to Rebin histogram by histogram. I've asked Nick Draper & Martyn Gigg about this.

2017-01-11 07:18 UTC, soininen commented
Good! Lets see if they have good ideas how to proceed or maybe we'll find another satisfactory solution. I can always revert the *RebinCanToSample* change.

2017-01-23 15:13 UTC, soininen commented
@SpencerHowells Any news from Nick or Martyn? Maybe I should also stress the point that we don't necessarily need rebinning at all. To my understanding, it doesn't make sense to measure the empty container using a different incident wavelength in a TOF instrument and thus the TOF axis should always match between the sample and the container workspaces.

2017-01-23 15:22 UTC, SpencerHowells commented
I agree with your comments. As I said I was forced to add it against by advice. historically I've kept it in because other routines would fail due to rounding errors in the x-units between sample & can. Nick was very wary about rebinning of what they call a ragged-workspace - that is, one in which the x-units for the histograms are different. Simple operations might work but many others will not. For your use I think an option would be the best solution.

2017-01-24 08:58 UTC, soininen commented
@SpencerHowells So, you agree that we can proceed with making the rebinning optional? As I said earlier, the change will not affect the current usage or behavior of this algorithm and rebinning has to be explicitly turned off if it is not needed.

2017-01-24 09:01 UTC, SpencerHowells commented
Yes I agree. Further to the ragged-ws problem, according to Nick it was originally thought of only for display/plotting use. If you need to rebin you will have to to do it hist by hist.

2017-01-30 11:27 UTC, soininen commented
@louisemccann I have fixed the flake8 warnings and all the tests seem to pass.

2017-01-30 12:10 UTC, louisemccann requested changes
It looks like the changes to the release notes got removed when you merged with master. 
Also could you add an option for this to the ApplyPaalmanPings interface

2017-01-30 12:10 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +                                  'CanWorkspace.'))
Could this be done with a true/false checkbox instead of a string selector?

2017-01-30 12:10 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +            s_api.mtd[self._sample_ws_name].getAxis(0).getUnit().unitID()
Is there any particular reason for this? Line length is 140, this should all be okay on one line.

2017-01-30 13:06 UTC, soininen commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +                                  'CanWorkspace.'))
Could be, but I rather use string selectors. It forces self-documenting code:
```python
ApplyPaalmanPingsCorrection('samplews', 'corrws', 'canws', 1.0, 0.0, 'outws', 'Rebin Can')
```
is easier to read than
```python
ApplyPaalmanPingsCorrection('samplews', 'corrws', 'canws', 1.0, 0.0, 'outws', True)
```
What is `True` here?

2017-01-30 13:08 UTC, soininen commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +            s_api.mtd[self._sample_ws_name].getAxis(0).getUnit().unitID()
This fails the 80 char limit on my `flake8` tool. Do we have a different standard in Mantid?

2017-01-30 13:19 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +            s_api.mtd[self._sample_ws_name].getAxis(0).getUnit().unitID()
Here is the flake8 config file: https://github.com/mantidproject/mantid/blob/master/.flake8

2017-01-30 13:19 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +                                  'CanWorkspace.'))
what is `1`?

2017-01-30 13:39 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +                                  'CanWorkspace.'))
When calling algorithms there is a tendency to use 
`ApplyPaalmanPingsCorrection(SampleWorkspace=sample_1, CanWorkspace=container_1, RebinCanToSample='True')`
so the code is still self-documented
It also means you can use get rid of:
```
if self.getProperty('RebinCanToSample').value == 'Rebin Can':
    self._rebin_container_ws = True
else:
    self._rebin_container_ws = False
```

2017-01-30 14:12 UTC, soininen commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +                                  'CanWorkspace.'))
Named arguments are not forced by Python so I'd expect there to be users who omit them. Anyway, I don't feel too strongly about this, so I'll make change the property to boolean.

2017-01-30 14:13 UTC, soininen commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
> +            s_api.mtd[self._sample_ws_name].getAxis(0).getUnit().unitID()
I see, thanks! I somehow thought `flake8` would pick up the config file automatically but it doesn't seem to.

2017-01-30 14:38 UTC, soininen commented
There are no release notes for 3.10, yet. Should we push this to 3.9 or add the release notes later, when they become available?

2017-01-30 15:09 UTC, soininen commented
Any hints what to do with the ApplyPaalmanPings interface? I could add a checkbox for container rebinning, but there is an additional check in `ApplyPaalmanPings::run()` if the binning matches, and if not, the user is shown a dialog and rebinning is done by manually running the `RebinToWorkspace` algorithm. 

As `ApplyPaalmanPingsCorrection` applies the rebinning anyway, should I just remove the additional rebinning step from the interface?

2017-01-31 13:28 UTC, louisemccann commented
@soininen wait until the release notes for 3.10. And yes, if the algorithm rebins the workspace anyway, there's no point calling `RebinToWorkspace` in the interface

2017-02-14 11:15 UTC, louisemccann approved these changes

2017-02-14 12:10 UTC, louisemccann commented
LGTM :shipit:

2017-02-14 16:12 UTC, merged