Group workspace masking error in MaskDetectors
mantidproject/mantid pull request #18417
Opened 2017-01-12 09:48 UTC by samueljackson92

See the two scripts in the bug report for examples of how to reproduce the issue.

**To test:**
Two cases to check that didn't work before:
 - Check that a workspace (NOT a masked workspace) where
    - masked workspace has a number of spectra == the number of detectors in the input workspace
    - masked workspace has a number of spectra > the number of spectra in the input workspace
 - Check the above works when specifying a `StartWorkspaceIndex` and `EndWorkspaceIndex`
 - Code review.

Fixes #14793 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-16 12:17 UTC, NickDraper requested changes
#we also need some changes to MaskDetectors.rst to make it explicit what will happen when passing in a MaskedWorkspace, as there are several options.

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +      if (nHist > WS->getNumberHistograms()) {
This if does not fit the comment above it

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +      if (nHist > WS->getNumberHistograms()) {
We also need to consider what should happen if it is <, probably handle it this way

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +            nHist == instrument->getNumberDetectors()) {
I don't think we should have the number of detectors == nhist restriction.

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +                instrument->getNumberDetectors() &&
if the number of detectors in the instruments do not match we should just warn but continue, not refuse.

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +          // We have more spectra in the mask than in the workspace and we also
So we should only refuse if one of the WS's does not have an instrument.

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +      } else {
This else should be more explicit of when it is being called (when workspace indices match)

2017-01-16 12:17 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +      auto id = maskWs->getDetector(i)->getID();
There is a methods that will return a vector of all of the IDs (i think getIDs) that will allow this to work for none 1-1 mapping.

2017-01-19 12:46 UTC, samueljackson92 commented
@NickDraper Please review again when you have time.

2017-01-20 09:07 UTC, NickDraper requested changes

2017-01-20 09:07 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +  } else if (instrument && maskInstrument) {
This should check the instrument->name, not pointer address, but it also should only log as warning if they do not match, still go ahead and apply the masking.

2017-01-20 09:07 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +    appendToDetectorListFromWS(detectorList, WS, maskWs, rangeInfo);
We should log at info that the masking is being applied by detector ids

2017-01-20 09:07 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +    appendToIndexListFromWS(indexList, maskWs, rangeInfo);
We should log at info that the masking is being applied by workspace index

2017-01-20 09:07 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +    appendToIndexListFromMaskWS(indexList, maskWs, rangeInfo);
We should log at info that the masking is being applied by workspace index

2017-01-20 09:07 UTC, NickDraper commented on Framework/DataHandling/src/MaskDetectors.cpp
> +    extractMaskedWSDetIDs(detectorList, maskWs);
We should log at info that the masking is being applied by detector ids

2017-01-20 13:35 UTC, NickDraper approved these changes

2017-01-20 15:27 UTC, NickDraper commented
Tested using the following script 
``` python
wsUnmasked = CreateSampleWorkspace()
wsMasked = CloneWorkspace(wsUnmasked)

def GeneratePattern(ws,noToGroup):
    groupingPattern = []
    for i in range(0,ws.getNumberHistograms(),noToGroup):
         groupingPattern.append(str(i) + '+' + str(i+1))
    groupingPatternString = ", ".join(groupingPattern)
    return groupingPatternString
    
wsGrouped2 = GroupDetectors(wsUnmasked,GroupingPattern = GeneratePattern(wsUnmasked,2))

# Define an infinite cylinder with its axis parallel to the Z-axis
# and the radius of 0.04
shapeXML = \
"""
<infinite-cylinder id="A" >
    <centre x="0" y="0" z="0" />
    <axis x="0" y="0" z="1" />
    <radius val="0.04" />
</infinite-cylinder>
"""
# Mask all detectors inside this cylinder
wsMasked = CloneWorkspace(wsUnmasked)
MaskDetectorsInShape( wsMasked, shapeXML )


wsGrouped2Masked = CloneWorkspace(wsGrouped2)
MaskDetectorsInShape( wsGrouped2Masked, shapeXML )


wsTestGrouped2MaskCopy = CloneWorkspace(wsUnmasked)
MaskDetectors(wsTestGrouped2MaskCopy,MaskedWorkspace=wsGrouped2Masked)

wsTestGroupedMaskCopy = CloneWorkspace(wsGrouped2)
MaskDetectors(wsTestGroupedMaskCopy,MaskedWorkspace=wsMasked)
```

Then the instrument views of the workspaces were compared.

Seems to work well :shipit:

2017-01-23 09:20 UTC, martyngigg commented
@samueljackson92 There was a trivial conflict in the release notes. I've resolved it in the browser and I'll merge this assuming the builds pass.

2017-01-23 13:47 UTC, martyngigg commented
Failing Windows test is unrelated slice viewer failure.

2017-01-23 13:48 UTC, merged