Fixing sphinx warnings
mantidproject/mantid pull request #18428
Opened 2017-01-12 21:25 UTC by AndreiSavici

Fixing some sphinx warnings.
Added figure for release notes from 3.8 branch

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-13 15:44 UTC, peterfpeterson commented
Was 65 warnings, now it is only 64 (squashed a missing img issue).

2017-01-13 15:57 UTC, peterfpeterson requested changes

2017-01-13 15:57 UTC, peterfpeterson commented on docs/source/interfaces/Tomographic_Reconstruction.rst
>    - C:/Anaconda/python.exe for Windows
These should be a sub-list and that still isn't rendering correctly. Also backtick the directories

2017-01-13 15:57 UTC, peterfpeterson commented on docs/source/interfaces/Tomographic_Reconstruction.rst
>    - By default this will be properly setup from the Mantid installation
Should be a sub-list that isn't rendering correctly

2017-01-13 15:57 UTC, peterfpeterson commented on docs/source/release/v3.8.0/framework.rst
> +- :ref:`LoadILL <algm-LoadILLTOF>` was renamed to `LoadILLTOF <algm-LoadILLTOF>` to better reflect what it does. The new algorithm can also handle cases where the monitor IDs are greater than the det
second link needs a `:ref:` to make it work. Same for `ConvertUnitsUsingDetectorTable` on line 78 above.

2017-01-13 20:53 UTC, AndreiSavici commented
I have only one warning, and that is because I am using a newer version of sphinx, where `pngmath` is deprecated
```
Running Sphinx v1.4.8
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
```

2017-01-17 13:57 UTC, peterfpeterson approved these changes

2017-01-17 13:57 UTC, peterfpeterson commented
I'm down to the same warning. :shipit:

2017-01-17 14:36 UTC, merged