Load isaw det cal param change
mantidproject/mantid pull request #18469
Opened 2017-01-18 19:11 UTC by peterfpeterson

Convert from having multiple `Filename` properties to a single property that accepts multiple filenames.

**To test:**

Since there was a modest modernization effort in the changes as well, seeing the parameter change by itself is hiding in the first commit.

Test by loading `.detcal` files onto instruments and seeing that it had an effect. There are some `.detcal` files in the system tests (often with the extension `.DetCal`).

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-20 08:45 UTC, gvardany requested changes
Could you add a unit test for multiple files case?

2017-01-20 13:04 UTC, VickieLynch commented
Works with TOPAZ single file and SNAP with 2 files.  I shifted the first detector in each file and the correct detectors were moved for SNAP.

2017-01-24 08:33 UTC, gvardany reviewed
Tests are a lot better now 👍 , see few more minor points inline.

2017-01-24 08:33 UTC, gvardany commented on Framework/DataHandling/src/LoadIsawDetCal.cpp
> +    result["Filename"] = "Must supply .detcal file";
This message seems copy pasted from above.

2017-01-24 08:33 UTC, gvardany commented on Framework/DataHandling/src/LoadIsawDetCal.cpp
> +  for (auto outer : filenamesFromProperty) {
const auto & ?

2017-01-24 13:46 UTC, gvardany approved these changes

2017-01-24 13:46 UTC, gvardany commented
Happy to :shipit: once tests pass

2017-01-24 19:59 UTC, merged