Histogram Rollout - SaveDetectorGroup to SaveMask
mantidproject/mantid pull request #18633
Opened 2017-01-31 10:54 UTC by DavidFair

HistogramData rollout: algorithms SaveDetectorGroup to SaveMask

## Description of work.
This PR is part of refactoring effort to use the new interface of the HistogramData module.
See https://github.com/mantidproject/mantid/issues/17641 for details.

`SaveFocussedXYETest` was renamed to `SaveFocusedXYETest` to match the algorithm name.

Headers were tided and c4250 warning suppression was removed from some headers - the rest have been completed in this PR with more details: #18632

The following algorithms were refactored to use HistogramData:

```
Framework/DataHandling/src/SaveDetectorsGrouping.cpp
Framework/DataHandling/src/SaveFITS.cpp
Framework/DataHandling/src/SaveFocusedXYE.cpp
Framework/DataHandling/src/SaveGSS.cpp
Framework/DataHandling/src/SaveMask.cpp
```

Performance tests were added for:

`SaveFocusedXYE`

The following algorithms have improved performance:
None - No algorithms copied histogram data so this is expected.
## To test.

Code review.

Fixes #18625 .
Internal change, no release notes (potential performance improvements will be added to release notes as part of the umbrella issue).

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-01-31 11:38 UTC, KarlPalmen commented on Framework/DataHandling/test/SaveFocusedXYETest.h
> -#endif // SAVEFOCUSSEDXYETEST_H_
I note that the new name is already used in the documentation and so that does not also need changing.

2017-01-31 11:43 UTC, KarlPalmen commented on Framework/DataHandling/src/SaveGSS.cpp
>      // Determine whether to skip the spectrum due to being masked
What is a spectrum index?

2017-02-01 16:02 UTC, KarlPalmen commented
:shipit:

2017-02-02 10:17 UTC, martyngigg requested changes

2017-02-02 14:45 UTC, martyngigg approved these changes

2017-02-02 16:19 UTC, merged