HistogramData rollout: algorithms DivideMD to IntegratePeaksMD
mantidproject/mantid pull request #18670
Opened 2017-02-01 17:43 UTC by samueljackson92

## Description of work.
This PR is part of refactoring effort to use the new interface of the HistogramData module.
See https://github.com/mantidproject/mantid/issues/17641 for details.

The following algorithms were refactored to use HistogramData:
```
Framework/MDAlgorithms/src/DivideMD.cpp
Framework/MDAlgorithms/src/EqualToMD.cpp
Framework/MDAlgorithms/src/FindPeaksMD.cpp
Framework/MDAlgorithms/src/GetSpiceDataRawCountsFromMD.cpp
Framework/MDAlgorithms/src/GreaterThanMD.cpp
Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
Framework/MDAlgorithms/src/IntegrateFlux.cpp
Framework/MDAlgorithms/src/IntegratePeaksCWSD.cpp
Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
Framework/MDAlgorithms/src/IntegratePeaksMD.cpp
```

Performance tests were added for: N/a

The following algorithms have improved performance: N/a

## To test.

Code review.

<Add any manual testing not covered by unit tests, especially GUIs>

Fixes #18656 .
Internal change, no release notes (potential performance improvements will be added to release notes as part of the umbrella issue).

2017-02-22 10:05 UTC, LamarMoore requested changes
Hi Sam, 

I took a look at the code and there are a few improvements which could be made to improve readability, compactness and usage of the HistogramData type. Maybe you should review some other changes you made with these tools in mind. I tried to be as thorough as possible but I may have missed something.

2017-02-22 10:05 UTC, LamarMoore commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        setSpectrum(wsProfile2D, i, signal_fit);
Covered in previous comments. Shouldn't need `setSpectrum` unless it returns a histogram.

2017-02-22 10:05 UTC, LamarMoore commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        const auto &x = wsProfile2D->x(i);
sharedX?

2017-02-22 10:05 UTC, LamarMoore commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        fit2DY = funcValues;
Why not use `Histogram` arithmetic? You could do something like 
```
wsFit2D->setSharedY(i, wsDiff2D->y(i));
wsFit2D->mutableY(i) -= yy;
```

or something similar.

2017-02-27 14:38 UTC, samueljackson92 commented
@LamarMoore Sorry for the slow response. Thanks for your comments. I'll hopefully get a chance to work through them individually this week.

2017-02-27 14:45 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/GetSpiceDataRawCountsFromMD.cpp
> +  outws->setCounts(0, vecY);
Agreed about the setting method. But here this is returning `1.0` if the Y value is `< 1.0` are well as performing the square root? So calculating it automatically could change the algorithm's output?

2017-02-27 14:47 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +    const auto &xVals = wksp->x(i);
Agreed.

2017-02-27 14:49 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp
> +        setOutputWorkspaceData(
Agreed. `HistogramData::LinearGenerator` was the droid I was looking for.

2017-02-27 14:50 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegrateFlux.cpp
> -  }
Agreed.

2017-02-27 14:52 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegrateFlux.cpp
>      if (isDistribution) {
Agreed.

2017-02-27 14:54 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegratePeaksMD.cpp
> +            std::accumulate(y.begin() + peakMax, y.end(), background_total);
Will do.

2017-02-27 14:55 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        const auto &x = wsProfile2D->x(i);
👍

2017-02-27 14:55 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        fit2DY = funcValues;
👍

2017-02-28 11:59 UTC, samueljackson92 commented
@LamarMoore I think that has addressed most of your comments. Only remaining thing is your first comment on `GetSpiceDataRawCountsFromMD.cpp`, but perhaps this is incorrect behaviour anyway and we should just compute E automatically as suggested.

2017-03-02 12:23 UTC, LamarMoore commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        std::fill(signal_fit.begin(), signal_fit.end(), 0.0);
Minor comment. If you used `Counts` instead of `std::vector` for signal_fit, you could just use `signal_fit = 0;`

2017-03-02 12:23 UTC, LamarMoore commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        wsFit2D->mutableY(i) = funcValues;
```cpp
wsFit2D->mutableY(i) = std::move(funcValues);
wsDiff2D->setSharedY(i, wsProfile2D->sharedY(i));
wsDiff2D->mutableY(i) -= wsFit2D->y(i);
```
??

Edit:
```cpp
wsFit2D->mutableY(i) = yy.toVector();//don't think you need std::move in this case
```

2017-03-03 10:34 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
> +        wsFit2D->mutableY(i) = funcValues;
I need to get more used to thinking about where I can use `std::move`

2017-03-03 10:35 UTC, samueljackson92 commented on Framework/MDAlgorithms/src/GetSpiceDataRawCountsFromMD.cpp
> +  std::transform(vecY.begin(), vecY.end(), dataE.begin(),
Yes. `remove_if` that the algorithm I was thinking of. And you're right about it breaking the E data anyway with the move. I guess the E value isn't actually covered by a test...

2017-03-06 10:22 UTC, LamarMoore approved these changes

2017-03-06 11:34 UTC, LamarMoore commented
If @SimonHeybrock does not have any further comments :shipit:

2017-03-08 20:50 UTC, merged