HistogramData rollout: algorithms <NexusFileIO to PoldiSpectrumConstantBackground>
mantidproject/mantid pull request #18699
Opened 2017-02-03 12:51 UTC by LamarMoore

## Description of work.
This PR is part of refactoring effort to use the new interface of the HistogramData module.
See https://github.com/mantidproject/mantid/issues/17641 for details.

The following algorithms were refactored to use HistogramData:

Framework/Nexus/src/NexusFileIO.cpp
Framework/SINQ/src/LoadFlexiNexus.cpp
Framework/SINQ/src/MDHistoToWorkspace2D.cpp
Framework/SINQ/src/PoldiAnalyseResiduals.cpp
Framework/SINQ/src/PoldiFitPeaks2D.cpp
Framework/SINQ/src/PoldiPeakSearch.cpp
Framework/SINQ/src/PoldiTruncateData.cpp
Framework/SINQ/src/PoldiUtilities/PoldiAutoCorrelationCore.cpp
Framework/SINQ/src/PoldiUtilities/PoldiResidualCorrelationCore.cpp
Framework/SINQ/src/PoldiUtilities/PoldiSpectrumConstantBackground.cpp

## To test.

Code review.

<Add any manual testing not covered by unit tests, especially GUIs>

Fixes <your issue>.
Internal change, no release notes (potential performance improvements will be added to release notes as part of the umbrella issue).

2017-02-15 14:33 UTC, dtasev requested changes

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
> +PoldiPeakSearch::getNeighborSums(const MantidVec &correlationCounts) const {
Is the work for this class going to be covered in another issue? It seems to have leftover `MantidVec` in places

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
> +  MantidVec summedNeighborCounts = getNeighborSums(correlatedCounts.rawData());
Get result with `const auto &summedNeighborCounts` ?

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
I can't leave comments on unchanged code in a review, but the call to `findPeaks` in the line _below_ should have `.cbegin()`, `.cend()`, the function `findPeaks` takes `MantidVec::const_iterator`

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
>    std::vector<PoldiPeak_sptr> peakCoordinates =
Get result by reference `std::vector<PoldiPeak_sptr> &peakCoordinates`, I think it can also be const? Also could do `const auto &peakCoordinates`

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
>        getPeaks(correlatedCounts.begin(), correlatedCounts.end(),
`.cbegin()`, `.cend()`

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiTruncateData.cpp
> +  auto &xData = workspace->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiUtilities/PoldiAutoCorrelationCore.cpp
> +    auto &timeData = m_countData->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/LoadFlexiNexusTest.h
> +    auto &Y = data->y(0);
const on both?

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/MDHistoToWorkspace2DTest.h
> +    auto &Y = data->y(0);
const on both?

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiAutoCorrelationCoreTest.h
> +    auto &qValues = output->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiAutoCorrelationCoreTest.h
> +    auto &outputIntensities = output->y(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiFitPeaks2DTest.h
> +    std::iota(X.begin(), X.end(), 0);
const iterators? Can't this be rewritten as `ws->setBinEdges(0, ws->x(0).size(), LinearGenerator(0, 1))` although I'm not sure it's worth introducing the includes, and the current code seems clearer

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiTruncateDataTest.h
> +    auto &xData = cropped->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiTruncateDataTest.h
> +    auto &xData = cropped->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiTruncateDataTest.h
> +    auto &x = below->x(0);
const

2017-02-15 14:33 UTC, DimitarTasev commented on Framework/SINQ/test/PoldiTruncateDataTest.h
> +    auto &x = above->x(0);
const

2017-02-15 14:36 UTC, DimitarTasev commented on Framework/SINQ/src/PoldiPeakSearch.cpp
> +PoldiPeakSearch::getNeighborSums(const MantidVec &correlationCounts) const {
Also there's some `MantidVec` in the header

2017-02-16 11:41 UTC, LamarMoore commented on Framework/SINQ/src/PoldiPeakSearch.cpp
> +PoldiPeakSearch::getNeighborSums(const MantidVec &correlationCounts) const {
What's wrong with the MantidVec if they are not being used in conjunction with `HistogramData` types?

2017-02-16 11:44 UTC, LamarMoore commented on Framework/SINQ/src/PoldiPeakSearch.cpp
> +  MantidVec summedNeighborCounts = getNeighborSums(correlatedCounts.rawData());
using `const auto &summedNeighborCounts` doesn't change anything, check the implementation of `getNeighborSums()`.

2017-02-16 11:48 UTC, LamarMoore commented on Framework/SINQ/src/PoldiPeakSearch.cpp
>    std::vector<PoldiPeak_sptr> peakCoordinates =
Why would I do that for objects created within the scope of the method?

2017-02-16 11:50 UTC, LamarMoore commented on Framework/SINQ/src/PoldiTruncateData.cpp
> +  auto &xData = workspace->x(0);
`const` is not required. `auto` already provides `const HistogramData::HistogramX`.

2017-02-20 09:43 UTC, dtasev approved these changes

2017-02-20 10:10 UTC, DimitarTasev commented
If @SimonHeybrock doesn't have any comments, I'm happy to :shipit:

2017-02-24 15:41 UTC, martyngigg commented on Framework/SINQ/src/PoldiTruncateData.cpp
> +  auto &xData = workspace->x(0);
@LamarMoore While `auto &` is perfectly correct we did a quick poll on slack and an overwhelming consensus was that `const auto &` was better for readability as you don't have to check function definition. Most other code I have seen has used `const auto &`, can we be consistent here?

2017-02-27 14:50 UTC, SimonHeybrock reviewed
Looks good, I don't have significant comments.

2017-02-27 14:50 UTC, SimonHeybrock commented on Framework/SINQ/src/MDHistoToWorkspace2D.cpp
>      std::transform(Y.begin(), Y.end(), E.begin(),
Could make use of `setHistogram` to compute `E` automatically.

2017-02-28 08:17 UTC, merged