Add concepts documentation.
mantidproject/mantid pull request #18705
Opened 2017-02-03 16:22 UTC by dymkowsk

Description of work.

**To test:**

Fixes #xxxx.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-06 08:50 UTC, martyngigg commented
As this is just new documentation I think this can go in to `release-v3.9` so I've updated the base branch accordingly.

2017-02-06 22:29 UTC, AndreiSavici requested changes
This is just the form. I will review the content tomorrow

2017-02-06 22:29 UTC, AndreiSavici commented on docs/source/concepts/TheoreticalS.rst
> +[4] P. C H Mitchell, S. F. Parker, A. J. Ramirez-Cuesta, J. Tomkinson, * Vibrational Spectroscopy with Neutrons With Applications in Chemistry, Biology, Materials Science and Catalysis *, ISBN: 978-9
Remove space right after the first `*` and right before the second one

2017-02-06 22:29 UTC, AndreiSavici commented on docs/source/algorithms/Abins-v1.rst
> +A description about the implemented working equations can be found :ref:`here <concepts contents>`
This should link directly to the page. For now, I could not find `TheoreticalS` in the concepts page. I will try a clean build for that. I would rename that page anyway

2017-02-06 22:29 UTC, AndreiSavici commented on docs/source/concepts/TheoreticalS.rst
> +.. categories:: Concepts
I figured out why it does not work. Add an extra line before categories, that way it will show up in the concepts page

2017-02-07 15:50 UTC, AndreiSavici approved these changes

2017-02-07 16:28 UTC, AndreiSavici requested changes
Make sure all indices are consistent, not one superscript, one subscript. Everywhere you use the same variables in the text, they should be in the math mode, otherwise they look different.

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/algorithms/Abins-v1.rst
> +A description about the implemented working equations can be found :ref:`here <concepts contents>`
Use :ref:`here <DynamicalStructureFactorFromAbInitio>`

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
> +:math:`j` -- indicates j-th atoms
use math mode for `j` in the description. Same for `i` in the next line, and so on

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
> +:math:`\sigma_j` -- cross-section for j-th atom
Be consistent: `sigma_j` in the description, `\sigma^j` in the formula, same for `M_j`

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
> +consider transitions 0 -> 2, but also simultaneous transitions 0 -> 1, 0 -> 1' for different phonons. Within harmonic approximation all second
use math mode for `0->1` and so on

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
> +C -- is a constant,  C=2 if i=j and C=1 otherwise
use math mode

2017-02-07 16:28 UTC, AndreiSavici commented on docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
> +:math:`Q(\omega)=k2_i(\omega) + k2_f - 2  \sqrt{k2_i(\omega)  k2_f} angle`
Formula is wrong. it should be `Q^2(\omega)=k^2_i(\omega) + k^2_f - 2  k_i(\omega)  k_f \cos \theta`. Then in the next lines replace `k2` with `k^2`. And you should never name the cosine as `angle`. `\theta` is the scattering angle

2017-02-07 16:33 UTC, dymkowsk commented
@AndreiSavici  thank you for your feedback. I will correct it asap.

2017-02-07 17:17 UTC, dymkowsk commented
@AndreiSavici  I have applied changes you requested. Let me know If I it looks OK now.

2017-02-07 18:12 UTC, AndreiSavici approved these changes

2017-02-07 18:18 UTC, AndreiSavici commented
There might still be a couple of minor things (on line 48 you have `M^j` while on line 70 it is `M_j`), but it looks OK. Leave those for a future issue. In that you should have a link to the file formats for CASTEP and phonon. Your Abins algorithm should also be able to compare simulations directly to workspaces, instead of having to save to a file. :shipit:

2017-02-07 21:53 UTC, merged