HistogramData Rollout LessThanMD to PlusMD
mantidproject/mantid pull request #18718
Opened 2017-02-06 13:52 UTC by DimitarTasev

Description of work.

 Framework/MDAlgorithms/src/LessThanMD.cpp
 Framework/MDAlgorithms/src/LoadILLAscii.cpp
 Framework/MDAlgorithms/src/LoadSQW.cpp
 Framework/MDAlgorithms/src/MDNormDirectSC.cpp
 Framework/MDAlgorithms/src/MDNormSCD.cpp
 Framework/MDAlgorithms/src/MinusMD.cpp
 Framework/MDAlgorithms/src/MultiplyMD.cpp
 Framework/MDAlgorithms/src/PlusMD.cpp

**To test:**
- [ ] Run DataHandling tests
- [ ] Code inspection

Fixes #18661 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-07 09:20 UTC, LamarMoore requested changes
Looks good. I noticed in a few places you missed some of the legacy implementation. Make sure you check the files thoroughly. A simple search and find on the files might reveal something you have missed.

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MDAlgorithms/src/MultiplyMD.cpp
> +  float scalar = float(m_rhs_scalar->mutableY(0)[0]);
`auto scale = static_cast<float>(m_rhs_scalar->y(0)[0]);`?

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MPIAlgorithms/src/BroadcastWorkspace.cpp
>        broadcast(world, const_cast<MantidVec &>(inputWorkspace->readX(i)), root);
`readX`?

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MPIAlgorithms/src/GatherWorkspaces.cpp
>          std::vector<boost::mpi::request> reqs(numReqs);
There are some `dataX` calls below this.

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MPIAlgorithms/test/BroadcastWorkspaceTest.h
> +    const auto &inX = inWS->x(0);
You didn't really need to do this. `inWS->x(0)[i]` would have been sufficient. You do not have to change it but it seems like a lot of unecessary extra code. Actually if you include `#include <MantidTestHelpers/HistogramDataTestHelpers.h`, header file name might not be correct, you can directly compare the two using `TS_ASSERT_EQUALS(inWS->x(0), outWS->x(0));`

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MPIAlgorithms/test/GatherWorkspacesTest.h
> +      TS_ASSERT_EQUALS(inWS->e(0)[i], outWS->e(0)[i]);
See above comment.

2017-02-07 09:20 UTC, LamarMoore commented on Framework/MPIAlgorithms/test/GatherWorkspacesTest.h
> +      TS_ASSERT_EQUALS(inWS->e(0)[i], outWS->e(0)[i]);
See above.

2017-02-07 09:49 UTC, DimitarTasev commented on Framework/MPIAlgorithms/src/BroadcastWorkspace.cpp
>        broadcast(world, const_cast<MantidVec &>(inputWorkspace->readX(i)), root);
Sorry, I didn't copy it from the issue description, BroadcastWorkspace and GatherWorkspaces need more work, as the `boost::mpi::broadcast(...)` function does not work with HistogramData types, and serialisation needs to be implemented. I've created an issue for that #18717, which will also cover the HistogramData refactoring

2017-02-07 09:49 UTC, DimitarTasev commented on Framework/MPIAlgorithms/src/GatherWorkspaces.cpp
>          std::vector<boost::mpi::request> reqs(numReqs);
Same comment as `BroadcastWorkspaces`

2017-02-07 17:15 UTC, DimitarTasev commented
I've reverted any changes to `BroadcastWorkspace` and `GatherWorkspaces`, because I cannot build it locally, and I do not think that the build servers run the tests for MPIAlgorithms, so I cannot be sure that my changes do not break the scripts.

2017-02-08 08:40 UTC, LamarMoore commented
@DimitarTasev can you make an issue for those to be refactored away from the legacy implementation?

2017-02-08 09:33 UTC, DimitarTasev commented
@LamarMoore Issue is #18717 for both conversion and implementing the serialising

2017-02-09 15:52 UTC, LamarMoore approved these changes

2017-02-10 09:02 UTC, LamarMoore commented
:shipit:

2017-02-13 07:16 UTC, merged