Ikeda-Carpenter parameters non-negative
mantidproject/mantid pull request #18835
Opened 2017-02-13 14:54 UTC by VickieLynch

Description of work. Add constraints that all parameters are non-negative

**To test:**
Load file and use Fit Peak from Toolbar with Ikeda-Carpenter fit of this peak:
https://www.dropbox.com/s/uc3hkmh91ow7wre/peak.nxs?dl=0
Fixes #18769 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-22 07:25 UTC, soininen requested changes

2017-02-24 07:52 UTC, soininen approved these changes

2017-02-24 07:57 UTC, soininen commented
Sorry for not bringing this up earlier, but while checking the reviewer boxes in the PR description, I realized that I forgot to request for a unit test, and perhaps the sphinx documentation could be updated to mention that the parameters are bound to be non-negative.

2017-02-24 14:11 UTC, VickieLynch commented
There are already unit tests in FitTest and IkedaCarpenterPVTest.  Do you want me to test that the parameters are non-negative?

2017-02-27 07:42 UTC, soininen commented
Nice work! The changes look good to me. :shipit:

2017-02-27 14:58 UTC, merged