Indirect QuickRun - add diffusion option
mantidproject/mantid pull request #18845
Opened 2017-02-14 13:39 UTC by louisemccann

EnergyWindowScan has been extended to include diffraction reduction and renamed to IndirectReductionAndAnalysis to better represent what the algorithm does.

**To test:**
InputFiles: [Diff_inputs.zip](https://github.com/mantidproject/mantid/files/774174/Diff_inputs.zip)

1
Interfaces>Indirect>Diffraction
Input: `26181` 
(this should find the appropriate run in the data archive otherwise browse to `IRS26181` in files provided)
Ensure Instrument = `ISIS` and mode = `diffspec`
Press `Run`

2
```Python
IndirectReductionAndAnalysis(InputFiles='26176',
                             Instrument='IRIS',
                             Analyser='graphite',Reflection='002',
                             SpectraRange='3, 50',
                             ElasticRange='-0.5, 0',
                             InelasticRange='0, 0.5',
                             GroupingMethod='All',
                             MSDFit=False,
                             Diffraction=True,
                             DiffractionSpectraRange=[105,112])
```
Ensure irs26176_diffspec_red is the same for both methods

Fixes #18223 #12270

[Release Notes](https://github.com/mantidproject/mantid/blob/be1b1486734488150de3569407f561772a855007/docs/source/release/v3.10.0/indirect_inelastic.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-16 15:25 UTC, samueljackson92 commented
@louisemccann Question: `ElasticWindowScan` is already an algorithm in 3.9 right? So by renaming the algorithm to `IndirectReductionAndAnalysis` does this break the Python API? `ElasticWindowScan` is pretty niche, but shouldn't we deprecate for a version then remove?

One option would be to just point the deprecated `ElasticWindowScan` at the new algorithm.

2017-02-16 15:26 UTC, samueljackson92 commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectReductionAndAnalysis.py
> +            self.setProperty("DiffractionWorkspace", diff_red_alg.getProperty("OutputWorkspace").value)
All of the stuff under the if statement could be refactored into a method.

2017-02-16 15:29 UTC, samueljackson92 commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectReductionAndAnalysis.py
> +            self.setProperty("DiffractionWorkspace", diff_red_alg.getProperty("OutputWorkspace").value)
In fact I'd go for one method per algorithm i.e. something like `self.run_diffraction_reduction()`, `self.run_msg()` ...

2017-02-16 15:31 UTC, samueljackson92 requested changes
See suggested changes above, or come talk to me if you disagree.

2017-02-20 11:38 UTC, SpencerHowells commented
We need EnergyWindowScan for use by the Interface in #18216

2017-02-20 11:47 UTC, samueljackson92 commented
@SpencerHowells I agree the algorithm needs to exist. My problem is with renaming. Renaming would potentially break any user scripts that we have no control over that use the current name. Hence we should really deprecate the name `EnergyWindowScan` name for one version of Mantid, then remove any reference of the algorithm called `EnergyWindowScan` in favour of `IndirectReductionAndAnalysis`.

2017-03-14 16:32 UTC, louisemccann commented
It has been decided that EnergyWindowScan and the DiffractionScan should be 2 different algs so I am going to close this.

2017-03-14 16:32 UTC, closed without merging