Fix an issue in `TimeSeriesProperty`
mantidproject/mantid pull request #18952
Opened 2017-02-21 16:19 UTC by raquelalvarezbanos

Description of work.

**To test:**

Fixes #xxxx.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-23 18:26 UTC, peterfpeterson requested changes

2017-02-23 18:26 UTC, peterfpeterson commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +    if (lhsTimes.size() != rhsTimes.size()) {
Shouldn't you use  `TimeSeriesProperty::size()` or `TimeSeriesProperty::realSize()` and copy the vectors if they aren't equal?

2017-02-23 21:29 UTC, DimitarTasev commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +    if (lhsTimes.size() != rhsTimes.size()) {
:+1: maybe extend the `if (this->m_size != right.m_size) ` above with an ` || this->realSize() != right.realSize()`, then the check will be applied for both below

2017-02-23 22:09 UTC, peterfpeterson commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +    if (lhsTimes.size() != rhsTimes.size()) {
The greatest effect would be had by putting this as an `if` on line 176.

2017-02-24 09:51 UTC, DimitarTasev commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +    if (lhsTimes.size() != rhsTimes.size()) {
@peterfpeterson Could you tell me why an additional `if` is preferred to extending an existing one?

2017-02-24 11:39 UTC, DimitarTasev commented
I've tested without the fix works and mantid longer crashes. After applying the fix there is no crash.
I've ran the unit tests without the fix and the new test fails. After applying the fix it passes successfully.
If @peterfpeterson doesn't have any comments I'm happy to :shipit:

2017-02-24 12:15 UTC, raquelalvarezbanos commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +    if (lhsTimes.size() != rhsTimes.size()) {
Shouldn't they be the same?

2017-02-24 13:21 UTC, peterfpeterson commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +
add the word `else` here and I'm happy

2017-02-24 13:41 UTC, peterfpeterson commented
I think a clearer version of the code (with added `const` below) is:
```c
if (this->realSize() != right.realSize()) {
     return false;
} else {
     const std::vector<DateAndTime> lhsTimes = this->timesAsVector();
      const std::vector<DateAndTime> rhsTimes = right.timesAsVector();
     if (!std::equal(lhsTimes.begin(), lhsTimes.end(), rhsTimes.begin())) {
       return false;
     }

     const std::vector<TYPE> lhsValues = this->valuesAsVector();
     const std::vector<TYPE> rhsValues = right.valuesAsVector();
     if (!std::equal(lhsValues.begin(), lhsValues.end(), rhsValues.begin())) {
       return false;
     }
}

return true;
```
I don't think the `const` buys anything since those functions return copies of the vectors. Without checking against a compiler, you can probably declare the various variables as `const auto` as well, but I don't think it really adds.

2017-02-27 13:22 UTC, peterfpeterson approved these changes

2017-02-27 14:19 UTC, martyngigg commented
Tests are the usual unrelated failures.

2017-02-27 14:19 UTC, merged