Enable peakviewer for NonOrthogonal view in sliceviewer
mantidproject/mantid pull request #19008
Opened 2017-02-27 14:39 UTC by lottiegreenwood

Fixes #18299 

To test go to \olympic\Babylon5\Scratch\Lottie\18911_peakviewer
load SEQ_11499_md_enp.nxs in the sliceviewer, and test with the peak file testPeak.nxs.
See that the skewed peak view looks sensible.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-02-28 10:23 UTC, AntonPiccardoSelg requested changes

2017-02-28 10:23 UTC, AntonPiccardoSelg commented on MantidQt/SliceViewer/src/CompositePeaksPresenter.cpp
> +  }
Avoid the iterator and go directly to the range-based for loop

2017-10-13 14:37 UTC, mantid-builder commented
@@mantidproject/gatekeepers this PR is now without a developer.
<!-- {"problem_type": "no_dev"} -->

2017-10-13 15:08 UTC, martyngigg commented
@NickDraper Who can work on this now?

2017-10-18 13:42 UTC, NickDraper commented
@Mantid-Matthew Could you take on the developer role for this PR please

2017-11-24 11:30 UTC, mantid-builder commented
@mantidproject/gatekeepers this PR is now without a developer.
<!-- {"problem_type": "no_dev"} -->

2018-02-27 11:57 UTC, ElliotAOram commented
@samueljackson92 is this ready to test and if so have you got the file around?

2018-02-27 12:55 UTC, samueljackson92 commented
I don't have that file, but I can probably find you *a* file somewhere

2018-04-16 14:54 UTC, mantid-builder commented
@samueljackson92 have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-04-30 14:03 UTC, mantid-builder commented
@samueljackson92 could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2018-05-14 14:03 UTC, mantid-builder commented
@samueljackson92 could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2018-05-29 14:03 UTC, mantid-builder commented
@samueljackson92 have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-06-28 09:06 UTC, martyngigg commented
@samueljackson92 As this is quite old I'm going to rebase the branch with master and get some fresh builds on it.

2018-06-28 10:31 UTC, martyngigg approved these changes
This seems to work as expected. The peaks are plotted in the correct places in the non-orthogonal view.

2018-06-28 10:34 UTC, NickDraper commented
We seem to be short of release notes here

2018-06-28 10:35 UTC, NickDraper commented
A nice screenshot would not go amiss either

2018-07-02 12:17 UTC, merged