Deprecate algorihtm BASISReduction311
mantidproject/mantid pull request #19047
Opened 2017-03-02 20:59 UTC by jmborr

Python algorithms cannot inherit from class `DeprecatedAlgorihtm` because it is not exported. I included a warning in the Algorithm summary and one error in the log upon execution.

**To test:**

Fixes #19046.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-02 21:23 UTC, peterfpeterson requested changes
The deprecation warning is put in the correct place. However, it could be done as a static string at the top of the file rather than copy-and-paste. Also, the standard format should be
```
BASISReduction311 is deprecated (on 2017-03-11). Use BASISReduction instead.
```

2017-03-03 13:37 UTC, peterfpeterson approved these changes

2017-03-03 13:38 UTC, peterfpeterson commented
LGTM :shipit:

2017-03-03 14:23 UTC, jmborr commented
@peterfpeterson You made me google for LGTM...LOL

2017-03-03 15:45 UTC, jmborr commented
@quantumsteve Steve, can you ship this pull request to the netherworld?

2017-03-03 15:51 UTC, merged

2017-03-03 16:03 UTC, jmborr commented
@quantumsteve @peterfpeterson 
 :checkered_flag: thanks :checkered_flag: