DPDFReduction: calibrate with white-beam vanadium
mantidproject/mantid pull request #19101
Opened 2017-03-08 22:13 UTC by jmborr

Check for white vanadium.

**To test:**
Run the following script:
```
DPDFreduction(RunNumbers="56416-56420", CleanWorkspaces=False,
    Vanadium="/SNS/ARCS/shared/autoreduce/vanadium_files/van56293.nxs",
    EmptyCanRunNumbers="34665-34674",
    EnergyBins="1.5",
    MomentumTransferBins="0.1",
    OutputWorkspace="slices_QE")
```
Make sure that the intensity gaps in workspace S(E,\theta)=`` are fixed in the interpolated workspace ``. Final workspace is S(Q,E)=`slices_QE`.

Fixes #19086.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-09 16:42 UTC, AndreiSavici requested changes

2017-03-09 16:42 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DPDFreduction.py
> +            api.Load(Filename=files, LoadMonitors=True, OutputWorkspace=data_name)
You can use `LoadEventNexus` from here on, if you only want this to work on ARCS. Leave `Load` if you want this to work at other facilities

2017-03-09 16:42 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DPDFreduction.py
> +            if mtd[wn_van].run().getProperty('vChTrans').value[0] != 2:
This works only on ARCS and SEQ. At some point in the code you MUST check if the instrument is ARCS. I would do it as part of the `_load` function. Just raise a `RuntimeError` or a `ValueError` or a `NotImplementedError`

2017-03-09 16:42 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DPDFreduction.py
>          if datasearch != "On":
don't need an `if`. And move the other config options (instrument and facility) here, so they are grouped and just next to the code that uses those

2017-03-09 22:35 UTC, jmborr commented
@AndreiSavici I just reduced with empty array for input property `MomentumTransferBins` and it went through OK.

2017-03-10 04:10 UTC, AndreiSavici approved these changes

2017-03-10 04:12 UTC, AndreiSavici commented
Looks fine. :shipit:

2017-03-10 14:06 UTC, merged

2017-03-10 14:10 UTC, jmborr commented
@AndreiSavici @peterfpeterson Thanks!!