ISIS Powder - Migration of GEM
mantidproject/mantid pull request #19112
Opened 2017-03-10 15:36 UTC by DavidFair

Description of work.
This PR adds the GEM instrument into the ISIS Powder scripts. 

**To test:**

Fixes #18643 .

*Does not need to be in the release notes. - ISIS Powder scripts are still in development*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-23 16:13 UTC, samueljackson92 requested changes
A few minor comments. I'm guessing unit/system tests are added in the next PR.

2017-03-23 16:30 UTC, samueljackson92 commented
As discussed gave it a good test with variety of parameter combinations. Seems to work ok. Output data appears to match the example given above.

2017-03-24 10:45 UTC, DavidFair commented on scripts/Diffraction/isis_powder/routines/common.py
> +    return out_name
Typically 40-60 characters at the most. These are used internally for the script. Basically we generate a unique fingerprint for a splined vanadium containing the offset name, tt_mode (on Pearl) and vanadium numbers. 
This also means users can see something of the format
`VanSplined_12345-12350_offsets_16_5.cal.nxs`

2017-03-24 10:46 UTC, DavidFair commented on scripts/Diffraction/isis_powder/routines/common.py
> +    return run_numbers
It should always return a list - this is a leftover from when it didn't. 👍

2017-03-24 11:08 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/common.py
> +    return out_name
That's probably ok. I've seen longer. I just wary sometimes of have workspace names that are too long, but this is fine.

2017-03-31 07:27 UTC, samueljackson92 requested changes
One more minor thing:

2017-03-31 07:27 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/common.py
> +    if isinstance(run_number_string, int):
This does not make sense anymore. You're checking it's an `int` then casting it to an `int`. So I'm guess this fails when it's a `str`.

Is this function still expected to take strings? If so I think we still need another case here? 
1) is string run number
2) is int run number
3) is a list of run numbers

If not then we should update the docstring, which also needs a `:param:` entry anyway and the variable name.

2017-04-03 10:35 UTC, samueljackson92 approved these changes

2017-04-03 10:35 UTC, samueljackson92 commented
Changes now LGTM. :shipit:

2017-04-03 11:10 UTC, merged