Add unit tests for ISIS_Powder common routines
mantidproject/mantid pull request #19163
Opened 2017-03-16 14:59 UTC by DavidFair

**Must not be merged before #19112** - I would recommend waiting for that PR before taking this one so you can get an accurate diff

**Description of work.**
This PR adds unit tests for the common functions in the ISIS_Powder scripts

**To test:**
Check that unit tests pass
Code review

Fixes #19113 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-24 09:39 UTC, DimitarTasev commented on scripts/Diffraction/isis_powder/routines/InstrumentSettings.py
> +                                   suppress_warnings=(not bool(basic_config) or suppress_warnings))
More of a query than a note, do we have to cast implicitly to `bool`? I think it's done automatically when you put the `not` in front, i.e. there shouldn't be a difference between `not bool(basic_config)` and just `not basic_config`

2017-03-24 09:52 UTC, DimitarTasev commented
From a brief look changes look good, all the unit tests pass, I'll have a look again after #19112 is merged and mark for ship then

2017-03-24 09:52 UTC, DimitarTasev commented
From a brief look changes look good, all the unit tests pass, I'll have a look again after #19112 is merged and mark for ship then

2017-04-03 16:02 UTC, DavidFair commented on scripts/Diffraction/isis_powder/routines/InstrumentSettings.py
> +                                   suppress_warnings=(not bool(basic_config) or suppress_warnings))
Good point Python does this implicitly I'll change that in the current branch I'm working on (to reduce the number of merge conflict in the future)

2017-04-05 12:39 UTC, dtasev requested changes

2017-04-05 12:39 UTC, DimitarTasev commented on scripts/Diffraction/isis_powder/routines/yaml_parser.py
> +                                 " Please check your indentation if the syntax looks correct.")
`Please check your indentation if the syntax looks correct.` consider rephrasing to something like
`Please check your indentation and make sure that the syntax is correct.`

2017-04-05 12:39 UTC, DimitarTasev commented on scripts/Diffraction/isis_powder/routines/common.py
> +    if isinstance(run_numbers, list):
It seems like `generate_run_numbers` _always_ returns a list, with single run number, or a range

2017-04-05 12:40 UTC, DimitarTasev commented on scripts/Diffraction/isis_powder/routines/common.py
> +    if isinstance(run_numbers, list):
also in `get_monitor_ws` [here](https://github.com/mantidproject/mantid/pull/19163/files#diff-3e56862968e7fc4f56f839cc920d48baL174), I think you could use get_first_run_number

2017-04-05 12:44 UTC, DimitarTasev commented
Use `get_first_run_number` in `yaml_parser.py` [here](https://github.com/mantidproject/mantid/blob/ac05bc1459672ae164348155091688aed2209027/scripts/Diffraction/isis_powder/routines/yaml_parser.py#L11) ?

2017-04-07 08:49 UTC, DavidFair commented on scripts/Diffraction/isis_powder/routines/common.py
> +    if isinstance(run_numbers, list):
Thats correct - it means the caller doesn't have to figure out types on their end (e.g. can just use a for in loop or [0])

Good spot 👍

2017-04-07 16:04 UTC, dtasev approved these changes

2017-04-19 12:59 UTC, DimitarTasev commented
:shipit: when OSX build lands on an ISIS node which has yaml installed

2017-04-21 12:46 UTC, merged