GEM Intial Feedback fixes
mantidproject/mantid pull request #19193
Opened 2017-03-20 18:29 UTC by DavidFair

**Note cannot be merged before #19163**

**Description of work.**
TODO
**To test:**
Code review
Ensure unit tests pass

(Self: Get someone to try out some broken functionality)

Fixes #19156 .

*Does not need to be in the release notes as currently in development*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-26 17:18 UTC, dtasev requested changes

2017-04-26 17:18 UTC, DimitarTasev commented on scripts/test/ISISPowderRunDetailsTest.py
> +        expected_splined_out_str = ''.join('_' + val for val in splined_name_list)
Adding `[ ]` to make it a list -> **[**"_" + val for val in splined_name_list **]** is about 2x faster
```
In [62]: timeit('"".join(["_" + val for val in splined_name_list])',setup='splined_name_list = ["name","2","fff"]')
Out[62]: 0.4237639904022217
```
```
In [63]: timeit('"".join("_" + val for val in splined_name_list)',setup='splined_name_list = ["name","2","fff"]')
Out[63]: 0.9818799495697021
```

2017-04-26 17:18 UTC, DimitarTasev commented on scripts/test/ISISPowderRunDetailsTest.py
> +        return ''.join(random.choice(string.ascii_lowercase) for _ in range(10))
Can save another 0.5s per call here by making the code inside `join(...)` a list:

```
In [66]: timeit("''.join(random.choice(string.ascii_lowercase) for _ in range(10))",setup='import random, string; splined_name_list = ["name","2","fff"]')
Out[66]: 6.115681886672974
```
```
In [67]: timeit("''.join([random.choice(string.ascii_lowercase) for _ in range(10)])",setup='import random, string; splined_name_list = ["name","2","fff"]')
Out[67]: 5.514591932296753
```

2017-04-27 10:43 UTC, dtasev approved these changes

2017-04-27 10:43 UTC, DimitarTasev commented
Everything looks good, unit tests pass, when the build servers pass :shipit:

2017-04-28 17:11 UTC, DTasev commented
changes look good :shipit:

2017-05-01 13:12 UTC, merged