Harmonise plotting of workspaces from right-button click
mantidproject/mantid pull request #19237
Opened 2017-03-23 14:59 UTC by KarlPalmen

Until this, surface and contour plotting was done in quite a different way to the plotting of spectra with or without errors in simple 1D, waterfall or tiled plot. Now they should all be accessible from a `Plot Spectrum Advanced` right-click menu option and basic plot spectrum functionality should be available as before.

The issue #18159 shows this in more detail.

**To test:**

The issue shows a python script and file to load that would be useful in testing also use your own file or scripts as you see fit.

Test the right click menu for `Plot Spectrum`, `Plot Spectrum with Errors` and `Plot Spectrum Advanced` in the various options available. It has been noted that the legend may not always appear for a waterfall plot #19208 and when 1D or waterfall plots are done with log values instead of workspace index, the items may not be shown in numerical order in the legend.

Fixes #18159.

TO DO

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-27 07:43 UTC, AntonPiccardoSelg requested changes

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidGroupPlotGenerator.cpp
> +    bool accepted, int plotIndex, const QString &axisName,
The class is not only used for groups any longer, so we should consider changing the name of the class.

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidGroupPlotGenerator.cpp
> +  // const auto &logName = logName; // Log to read for axis of XYZ plot
If the commented out code is not being used, then it should be removed.

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidGroupPlotGenerator.cpp
> +  if (workspaces.size() <= 0) {
`workspaces.empty()` is a better option here

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    if (auto ei = boost::dynamic_pointer_cast<const ExperimentInfo>(matrixWS)) {
`MatrixWorkspace` inherits from `ExperimentInfo`, hence you don't have to perform a `dynamic_pointer_cast` here. You should be able to get the run via `matrixWS->run()`.

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +          return std::stod(log->value());
Good use of  `C++11` feature

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +  if (wsIndex < static_cast<int>(logValues.size())) {
Why do you `static_cast` here? `size` returns a `size_t` and `wsIndex` is a `size_t`.

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    std::advance(it, wsIndex);
:+1:

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidUI.cpp
> +          logVal = getSingleWorkspaceLogValue(i++, customLogValues);
Why are we incrementing the iterator here?

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidUI.h
> +#include "MantidAPI/WorkspaceGroup_fwd.h"
Do we need to the forward declaration of the `WorkspaceGroup` any longer?

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/MantidWSIndexDialog.cpp
> +  for (auto wsName : m_wsNames) {
take this by reference, ie `auto& wsName : m_wsNames`. This avoids the copy of each element

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/MantidWSIndexDialog.cpp
> +      for (auto log : logData) {
See above

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/MantidWSIndexDialog.cpp
> +  for (auto logCount : logCounts) {
See above

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/MantidWSIndexDialog.cpp
>                                           QList<QString> wsNames,
This is not your change, but we should check if taking this via `const &` is the right thing to do here.

2017-03-27 07:43 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/test/WorkspacePresenter/WorkspacePresenterTest.h
> +  }
:+1:

2017-03-27 09:59 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidGroupPlotGenerator.cpp
> +    bool accepted, int plotIndex, const QString &axisName,
Renamed MantidSurfaceContourPlotGenerator as implied by opening comment in .h file.

2017-03-27 10:20 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    std::advance(it, wsIndex);
The code in MantidplotUtilities was moved by me from MantidGroupPlotGenerator to make it available elsewhere. I'm happy to make simple improvements in its code.

2017-03-27 11:49 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    std::advance(it, wsIndex);
That was just a thumbs up for good use of `std::advance`

2017-03-27 11:53 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    std::advance(it, wsIndex);
I was referring to all comments about `MantidPlotUtilities`.

2017-03-27 12:52 UTC, KarlPalmen commented on MantidQt/MantidWidgets/src/MantidWSIndexDialog.cpp
>                                           QList<QString> wsNames,
The `wsnames` is set by the user and so `const` is not appropriate, but perhaps `&` is. This is also the same for the `MantidWSIndexWidget`.

2017-03-27 12:53 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidUI.cpp
> +          logVal = getSingleWorkspaceLogValue(i++, customLogValues);
Why not?

2017-03-27 14:39 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidUI.cpp
> +          logVal = getSingleWorkspaceLogValue(i++, customLogValues);
Hmm, I read it wrong. I read `i` as `it`. It is only a counter, that is fine.  This makes more sense now to me.

2017-03-28 14:56 UTC, KarlPalmen commented
I've added issue #19259 for the Release Notes.

2017-03-29 07:41 UTC, AntonPiccardoSelg commented
Issues found while testing:

### Single workspace with single spectrum does not open when clicking `Plot Spectrum` (or `Plot Spectrum with Errors`
 You can create the workspace with 
```python
CreateSampleWorkspace(OutputWorkspace='ws3', Function='Flat background', NumBanks=1, BankPixelWidth=1, XUnit='MomentumTransfer', XMax=10, BinWidth=1)
```

2017-03-29 08:47 UTC, KarlPalmen commented
I had noticed that if one put in too few custom log values, the remaining log values are shown as 0 in a waterfall or 1D plot. I didn't consider this an important issue, because the user should input as many custom log values as workspaces.

2017-03-29 08:53 UTC, AntonPiccardoSelg commented
Yes, the user should provide one log value per workspace. Should we warn the user if this is not being provided or should we just default to 0?

2017-03-30 07:08 UTC, AntonPiccardoSelg commented
Some more issues:

1. Run the temp script where the workspaces have multiple spectra
2. Select spectrum 1-2
3. Select waterfall plot and plot
  * Confirm that the labels are duplicates. I recall that we clarified with Nick that the label should be something like *templable*-spX.

2017-03-30 08:08 UTC, KarlPalmen commented
When I tried this I got `temp10-sp-1`, `temp10-sp-2`, `temp100-sp-1`, `temp100-sp2`, `temp20-sp-1`, `temp20-sp2` etc. Each label is unique.

2017-03-30 08:13 UTC, KarlPalmen commented
I then realised I did this for 1D-plot, when I tried waterfall plot I found the legend had been moved up so only the bottom part was showing. I could move it down and see the same labels as for 1D-plot.

2017-03-30 08:50 UTC, AntonPiccardoSelg commented
I get: 

![image](https://cloud.githubusercontent.com/assets/8955784/24495807/3da93936-152e-11e7-82db-2b184abe5e6e.png)

2017-03-30 08:56 UTC, KarlPalmen commented
You didn't mention selecting `temp` as the log.

2017-03-30 09:16 UTC, AntonPiccardoSelg commented
You are right, the instructions have been updated.

2017-03-30 15:39 UTC, NickDraper commented
If you use this script
``` python
base = CreateSampleWorkspace(Function='Powder Diffraction', NumBanks=1, BankPixelWidth=1)

wsNames = []
for t in range (10,110,10):
    wsName = "temp" + str(t)
    wsNames.append(wsName)
    MultiplyRange(base,75,99,t/100.0,OutputWorkspace=wsName)
    AddSampleLog(wsName,"Temp",str(t),"Number","Kelvin")
TestGroup = GroupWorkspaces(wsNames)
```

You get workspaces with only one spectrum, in this case you do not get the plot Advanced gui, and I think you should.

2017-03-30 15:45 UTC, NickDraper commented
Log values are being sorted in text order rather than numeric order
![image](https://cloud.githubusercontent.com/assets/1017173/24513116/54cbfaa6-1568-11e7-9d92-60da8a776fbb.png)

2017-03-30 16:30 UTC, AntonPiccardoSelg commented
Hi, 

Nick just tested the PR and there is a set of requirements and changes that we should consider. All of this refers to `Plot Spectrum Advanced`

1. `Plot Spectrum Advanced` should be renamed to `Plot Advanced`
2. When the user forgets to enter a spectrum number or a workspace index in the two line edit fields in the top, a warning box should appear
3. The custom input field is not disabled when opening the `Plot Spectrum Advanced` the first time.
4. The GUI itself needs to be reorder slightly. We should place the `Show Error Bars` checkbox underneath the combo box which contains `1D Plot`, etc. Next to this combobox we should add a lable with the name `Plot Type`
5. The elements concerning labels, ie everything below the `Show Error Bars`  should be grouped.
6. When the user tries to open `Plot Advanced` with workspaces that have only one spectrum, the values are plotting immediately without prompting a GUI. This is correct for `Plot Spectrum` and `Plot Spectrum With Errors` but in the case of `Plot Advanced` we should get the GUI.
7. The last settings for anything but the workspace index line edit field and the spectrum number line edit field should be persisted via QSettings.
8. WSIndex for labelling does not make much sense for the `Plot1D` family. In fact we need to check if it makes sense at all
9. When dealing with log values (or custom values) we need to order the labels in an ascending order. This means we would have an order of, for example, `10-sp1, 10-sp2, 20-sp1, 20-sp2, 100-sp1, 100-sp2` instead of `10-sp1, 10-sp2, 100-sp1, 100-sp2, 20-sp1, 20-sp2` which is currently being used.

2017-03-31 15:24 UTC, KarlPalmen commented
I've found out that the surface plot graph depends on how the workspaces in the group are named. This situation does not apply before this issue. The following script demonstrates it
```python
base = CreateSampleWorkspace(Function='Powder Diffraction', NumBanks=4, BankPixelWidth=1)

wsNames = []

for t in range (10,110,10):
    wsName = "temp" + str(t)
    wsNames.append(wsName)
    MultiplyRange(base,75,99,t/100.0,OutputWorkspace=wsName)
    AddSampleLog(wsName,"Temp",str(t),"Number","Kelvin")

TestGroup = GroupWorkspaces(wsNames)

# Now the same again, but the numbers in the names have 100 added
wsNames100 = []

for t in range (10,110,10):
    wsName = "temp" + str(t+100)
    wsNames100.append(wsName)
    MultiplyRange(base,75,99,t/100.0,OutputWorkspace=wsName)
    AddSampleLog(wsName,"Temp",str(t),"Number","Kelvin")

TestGroup100 = GroupWorkspaces(wsNames100)
```

2017-04-10 08:57 UTC, AntonPiccardoSelg commented
### Retesting the change requests from above:

1. `Plot Spectrum Advanced` should be renamed to `Plot Advanced` -> Open
2. When the user forgets to enter a spectrum number or a workspace index in the two line edit fields at the top, a warning box should appear. -> Open
3. The custom input field is not disabled when opening the `Plot Spectrum Advanced` for the first time. -> Open
4. The GUI itself needs to be reordered slightly. We should place the `Show Error Bars` check box underneath the combo box which contains `1D Plot`, etc. Next to this combo box we should add a label with the name `Plot Type`. -> Open
5. The elements concerning labels, ie everything below the `Show Error Bars`  should be grouped. -> Open
6. ~~When the user tries to open `Plot Advanced` with workspaces that have only one spectrum, the values are plotted immediately without prompting a GUI. This is correct for `Plot Spectrum` and `Plot Spectrum With Errors` but in the case of `Plot Advanced` we should get the GUI.~~ -> Done
7. The last settings for anything but the workspace index line edit field and the spectrum number line edit field should be persisted via QSettings. -> Open
8. WSIndex for labelling does not make much sense for the `Plot1D`, `Waterfall Plot` and `Tiled Plot`. In fact we need to check if it makes sense at all. -> Open
9. When dealing with log values (or custom values) we need to order the labels in an ascending order. This means we would have an order of, for example, `10-sp1, 10-sp2, 20-sp1, 20-sp2, 100-sp1, 100-sp2` instead of `10-sp1, 10-sp2, 100-sp1, 100-sp2, 20-sp1, 20-sp2` which is currently being used. -> Cannot check since I don't see the legend

2017-04-12 09:41 UTC, AntonPiccardoSelg commented
Going through the remaining points:

- [x] Plot Spectrum Advanced should be renamed to Plot Advanced
- [x] When the user forgets to enter a spectrum number or a workspace index in the two line edit fields at the top, a warning box should appear. **Comment** the input field shows now a red star which is better than a pop ip.
- [x] The custom input field is not disabled when opening the Plot Spectrum Advanced for the first time.
- [x] The GUI itself needs to be reordered slightly. We should place the Show Error Bars check box underneath the combo box which contains 1D Plot, etc. Next to this combo box we should add a label with the name Plot Type.
- [x] The elements concerning labels, ie everything below the Show Error Bars should be grouped.
- [x] When the user tries to open Plot Advanced with workspaces that have only one spectrum, the values are plotted immediately without prompting a GUI. This is correct for Plot Spectrum and Plot Spectrum With Errors but in the case of Plot Advanced we should get the GUI.
- [ ]  The last settings for anything but the workspace index line edit field and the spectrum number line edit field should be persisted via QSettings. **Comment** This will addressed in a separate issue. This does not break any old functionality
- [ ] WSIndex for labelling does not make much sense for the Plot1D, Waterfall Plot and Tiled Plot. In fact we need to check if it makes sense at all. **Comment** Name is changed to `Worspace name` for the standard plots. There is still a small inconsistency to be addressed when switching between the plot options. I will show you on my machine.
- [x] When dealing with log values (or custom values) we need to order the labels in an ascending order. This means we would have an order of, for example, 10-sp1, 10-sp2, 20-sp1, 20-sp2, 100-sp1, 100-sp2 instead of 10-sp1, 10-sp2, 100-sp1, 100-sp2, 20-sp1, 20-sp2 which is currently being used. :+1: 
![image](https://cloud.githubusercontent.com/assets/8955784/24951494/80d7e64c-1f6c-11e7-91b8-e2045fefa8cf.png)

Some minor points to address, before we send it to other people to test.

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidPlotUtilities.h
> +} CurveSpec;
You should be able to use `C++`-style here, ie `struct CurveSpect {...`

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidSurfaceContourPlotGenerator.cpp
> +  if (workspaces.size() == 0) {
better to use `workspaces.empty()`

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidSurfaceContourPlotGenerator.h
> +  enum class Type { Surface, Contour };
:+1: good use of `enum classs`

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidUI.cpp
> +        if (customLogValues.size() > 0) {
why not `!customLogValues.empty()` ?

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidPlot/src/Mantid/MantidUI.cpp
> +MantidUI::createWorkspaceIndexDialog(int flags, QStringList wsNames,
Should we pass the `wsNames` as `const &` here?

2017-04-12 15:12 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/MantidTreeWidget.cpp
> +        if (selectedWsNameSet.find(QString::fromStdString(childWsName)) ==
We should iterate over the names via `const &` then we avoid copying the whole container.

2017-04-12 15:15 UTC, AntonPiccardoSelg commented
- [x]`Ubuntu 16.04`. Comparing the behaviour of this PR and the latest release seems to be ok.
- [ ] OSX
- [ ] Windows

2017-04-19 14:48 UTC, NickDraper commented
When adding custom values that are not numeric you get en error message, so "a,b,c,d" fails

2017-04-19 15:02 UTC, KarlPalmen commented
On testing an old version of Mantid, I found that non-numeric custom log values were never accepted.

2017-04-20 08:59 UTC, AntonPiccardoSelg approved these changes

2017-04-20 09:26 UTC, KarlPalmen commented
Nick's third item of feedback from testing was easy to fix and has been done. The other two would be harder to fix, because log values are currently conveyed as double and not strings and the correct number of custom values is not readily available as the dialog box.

2017-04-28 12:41 UTC, KarlPalmen commented
This PR is ready for testing again.

2017-05-04 14:55 UTC, KarlPalmen commented
Pull Request #19485 is for the release notes of this issue.

2017-05-04 15:54 UTC, NickDraper commented
Custom value handling is much better now

2017-05-08 13:12 UTC, peterfpeterson commented
@quantumsteve Please try this out on osx.

2017-05-08 13:27 UTC, samueljackson92 submitted a review, later dismissed
A few minor code comments added below. I also noticed a couple of issues when testing on OSX.

1. The plot legend is missing on waterfall plots
![screen shot 2017-05-08 at 14 24 52](https://cloud.githubusercontent.com/assets/2487781/25806122/20627fe6-33fa-11e7-8a36-468534b2d885.png)
2. The "Show Error Bars" text appears squished on OSX.
![screen shot 2017-05-08 at 14 25 28](https://cloud.githubusercontent.com/assets/2487781/25806151/349ef71e-33fa-11e7-8374-af8c31bb1f02.png)

3. Custom log values seem to work a little inconsistently. For example if I put in `1,2,1,2` I get back labels `0, 0, 1, 2`

4. It appears I cannot edit the label for the plot axis. Even when the log value is set to custom

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    return (double)wsIndex; // cast for plotting
Don't use a C style cast. Use `static_cast<double>`

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +    return (double)wsIndex; // cast for plotting
We also `return` here, so we can use an [early exit](http://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code) to remove the else statement and reduce code complexity

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidPlotUtilities.cpp
> +  if (wsIndex < logValues.size()) {
Could also use an early exit here.

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidPlotUtilities.h
> +bool byLogValue(const CurveSpec &lhs, const CurveSpec &rhs);
Three slashes (`///`) needed for doxygen comment.

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidUI.cpp
> +
Could we split this block for adding curves into a new method?

2017-05-08 13:27 UTC, samueljackson92 commented on MantidPlot/src/Mantid/MantidUI.cpp
> +
Code is quite long and complex. Perhaps we could split it into a new method?

2017-05-08 13:27 UTC, samueljackson92 commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/WorkspacePresenter/QWorkspaceDockView.h
> +  void plotSpectrum(std::string type) override;
`const std::string&`

2017-05-08 13:39 UTC, KarlPalmen commented
Thank you @samueljackson92 for reviewing this. The point about the waterfall plot legend not always being shown is addressed in issue #19208 and applies already. The axis name only has effect in surface and contour plots and should be enabled for such plots. I'll address other issues later on.

2017-05-08 14:29 UTC, samueljackson92 commented
@KarlPalmen Ahhh I misunderstood the purpose of the axis name.

2017-05-10 08:50 UTC, KarlPalmen commented
I looked into the issues arising from duplicate custom log values. In doing so, I checked the behaviour of Mantid without this PR and found that the validation of the custom logs was done against the number of _distinct_ log values.  This suggests that the validation is not correct for duplicate custom log values and Samuel's case should be rejected, because there are only 2 log values. However with waterfall and 1D plots different considerations may apply.

2017-05-10 12:49 UTC, KarlPalmen commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/WorkspacePresenter/QWorkspaceDockView.h
> +  void plotSpectrum(std::string type) override;
Function is called like this ``  view->plotSpectrum("Simple");`` so can't use`` string&``.

2017-05-11 13:22 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidUI.cpp
> +
I've put this one into a new method (with a little help from you).

2017-05-11 13:24 UTC, KarlPalmen commented on MantidPlot/src/Mantid/MantidUI.cpp
> +
It would require 6 arguments for just 20 lines.

2017-05-17 15:57 UTC, AntonPiccardoSelg commented
Please :shipit:

2017-05-17 19:47 UTC, merged