better the the system test for global fit of water
mantidproject/mantid pull request #19261
Opened 2017-03-28 18:56 UTC by jmborr

Added a check for output fitted workspace.

**To test:**
Just [run the test locally](http://www.mantidproject.org/System_Tests#Running_Tests_Locally)

Fixes #19249.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-03-31 15:17 UTC, rosswhitfield requested changes

2017-03-31 15:17 UTC, rosswhitfield commented on Testing/SystemTests/tests/analysis/QENSGlobalFitTeixeiraWaterSQE.py
> +            print otherChi2, chi2, abs(otherChi2-chi2)/chi2
Can you fix the print statement for python 3, this systemtest previously passed with python 3 and we don't want to go backwards.

And add `from __future__ import (absolute_import, division, print_function)` to the top.

2017-03-31 16:40 UTC, jmborr commented on Testing/SystemTests/tests/analysis/QENSGlobalFitTeixeiraWaterSQE.py
> +            print otherChi2, chi2, abs(otherChi2-chi2)/chi2
Ouch, this I did for debugging purposes and forgot to remove it.

2017-03-31 18:51 UTC, rosswhitfield approved these changes

2017-03-31 18:51 UTC, rosswhitfield commented
LGTM :shipit:

2017-03-31 23:47 UTC, quantumsteve commented on Testing/SystemTests/tests/analysis/QENSGlobalFitTeixeiraWaterSQE.py
> +            print otherChi2, chi2, abs(otherChi2-chi2)/chi2
@jmborr Did you forget to add `from __future__ import (absolute_import, division, print_function)` to the top of the file?

2017-04-01 02:31 UTC, jmborr commented on Testing/SystemTests/tests/analysis/QENSGlobalFitTeixeiraWaterSQE.py
> +            print otherChi2, chi2, abs(otherChi2-chi2)/chi2
Just fixed. Thanks for pointing it out

2017-04-03 10:28 UTC, merged

2017-04-03 13:39 UTC, jmborr commented
Thank y'all