Reformat and add cross-references
mantidproject/mantid pull request #19290
Opened 2017-04-03 13:28 UTC by peterfpeterson

I'm kicking off builds and will fill in the details soon enough. Description of work.

**To test:**

Fixes #xxxx.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-04 13:07 UTC, soininen requested changes

2017-04-04 13:07 UTC, soininen commented on docs/source/algorithms/CreateCacheFilename-v1.rst
> +* ``property_manager``: an instance of
Are the items in this list the properties of the algorithm? In that case, the underscores could be changed to CamelCase, i.e. `property_manager` could be `PropertyManager` and so on.

2017-04-04 13:56 UTC, soininen approved these changes

2017-04-05 06:31 UTC, soininen commented
What's with the 'new' sphinx warnings in Ubuntu + Doc Tests? They don't seem to be connected to this PR in any way.

2017-04-05 13:08 UTC, peterfpeterson commented
They are in `master` and "somebody" is working on them.

2017-04-06 08:53 UTC, soininen commented
Everything seems to be OK :shipit:

2017-04-06 14:20 UTC, merged