Implement slicing by log value
mantidproject/mantid pull request #19301
Opened 2017-04-04 16:16 UTC by PranavBahuguna

This PR adds a fourth slicing option to the event handling tab in the ISIS Reflectometry interface - log value slicing. This new slicing option allows the user to provide a selection of values (in a manner identical to custom slicing) and the name of a log. This allows a run to be filtered by the log values for each start/stop value, creating several slices.

**To test:**

This should be tested on `Release` mode. Alternatively if using `Debug` mode, go to `LoadEventNexus.cpp` and replace the following lines at lines 289-292 with this:

```
if (temp < 0) {
    if (temp < m_min_id)
        m_min_id = temp;
    if (temp > m_max_id)
        m_max_id = temp;
}
```

- Code review
- Access the interface from Interfaces->Reflectometry->ISIS Reflectometry
- Enter run `38415` with transmission run `38393` in the `Runs` tab
- In the `Event Handling` tab, ensure that omitting either slicing values or log name and processing causes the run to be processed as a non-event workspace (it will be processed via `GenericDataProcessorPresenter.cpp`).
- Enter values `0,100,1000,2000,3000,4000` and log name `raw_frames` and process. This should produce 5 sliced workspaces of each kind. As there are no raw_frames

Fixes #19012.

*Release notes have been updated.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-09 07:44 UTC, PranavBahuguna commented
@AntonPiccardoSelg Merge conflicts are resolved and this issue is no longer in progress, can you review this please?

2017-05-09 18:07 UTC, AntonPiccardoSelg commented on MantidQt/CustomInterfaces/src/Reflectometry/ReflDataProcessorPresenter.cpp
> +                                                  std::string logFilter) {
`const &`?

2017-05-16 08:06 UTC, AntonPiccardoSelg commented
@PranavBahuguna This is stuck at `ClangFormat`

2017-05-17 15:47 UTC, AntonPiccardoSelg commented
Works as described. Please :shipit:

2017-05-17 20:10 UTC, quantumsteve requested changes
A few things which I think should be considered before merging

2017-05-19 19:38 UTC, quantumsteve commented on MantidQt/CustomInterfaces/src/Reflectometry/QtReflEventView.cpp
> +  return m_sliceTypeStrMap.at(m_sliceType);
Why did you switch to `std::map::at`? It's a relatively expensive check that in this case serves no purpose.

2017-05-22 08:02 UTC, PranavBahuguna commented on MantidQt/CustomInterfaces/src/Reflectometry/QtReflEventView.cpp
> +  return m_sliceTypeStrMap.at(m_sliceType);
As m_sliceTypeStrMap is now defined in the header file, it is essentially `const` after initialisation. We cannot use `[]` as that can also be used to insert new elements into the map.

I feel it is also worth mentioning that the code in question is only called once in reduction and is not performance-critical at all.

2017-05-22 15:00 UTC, quantumsteve approved these changes

2017-05-22 15:00 UTC, merged