Changing the font on the script window causes crash
mantidproject/mantid pull request #19346
Opened 2017-04-11 14:16 UTC by samueljackson92

Fixed a bug which could cause Mantid to crash when choosing the font for the script window.

**To test:**
 - Check you can reproduce by opening the script window, then choosing window -> select font
 - Check these changes fix the issue.
 - Code review.

Fixes #19345 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-19 14:12 UTC, AntonPiccardoSelg commented
I don't seem to be able to reproduce the crash on `Ubuntu` and `Windows` (even when no entry for `ScriptFontFamily` in `.config` or the `registry` is set). Having only briefly glanced over the code, it appears that QScintilla's lexer provides default fonts for the various operating system. 

Since I cannot reproduce the issue it might be better if someone with OSX tests this.

2017-05-05 15:23 UTC, soininen requested changes

2017-05-05 15:23 UTC, soininen commented on MantidPlot/src/MultiTabScriptInterpreter.cpp
> +  if (results.size() > 0) {
Wouldn't
```
if (!results.empty()) {
```
convey the intention better?

2017-05-10 13:24 UTC, soininen requested changes

2017-05-10 13:24 UTC, soininen commented on MantidPlot/src/MultiTabScriptInterpreter.cpp
> +  if (results.empty()) {
This seems to be missing `!`:
```
if (!results.empty()) {
```

2017-05-11 06:36 UTC, soininen approved these changes

2017-05-11 06:39 UTC, soininen commented
On my Ubuntu 14.04 system I can finally use Comic sans in the Python window. Nice work! :shipit:

2017-05-12 15:15 UTC, merged