Version passing in python test helper
mantidproject/mantid pull request #19352
Opened 2017-04-12 07:03 UTC by gvardany

This is a small fix in the way python test helper handles the algorithm version. See the issue description.

**To test:**
1. Pick a python algorithm test, that uses `run_algorithm` helper, e.g. FindEPPTest
2. Add `Version=1` to the argument list to `run_algorithm` call
3. Test should still pass with no error

Fixes #19344 .

Does not need to be in the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-12 14:18 UTC, peterfpeterson requested changes

2017-04-12 14:18 UTC, peterfpeterson commented on Framework/PythonInterface/test/testhelpers/__init__.py
> +    if 'Version' in kwargs:
Slightly more pythonic, and using knowledge of `AlgorithmManager` is to change this to
```python
alg = mantid.api.AlgorithmManager.createUnmanaged(name, kwargs.get('Version', -1))
if 'Version' in kwargs:
    del kwargs['Version']

2017-04-13 07:33 UTC, gvardany commented on Framework/PythonInterface/test/testhelpers/__init__.py
> +    if 'Version' in kwargs:
True, but from the other hand you are repeating here the default value, which might change theoretically, and if this ever happens, one should take care to change here as well. In principle, this code should not know what is the default value of version in the algorithm manager, so I am not entirely sure it is worth it.

2017-04-13 12:31 UTC, peterfpeterson approved these changes
Explanation is good with me.

2017-04-13 12:31 UTC, peterfpeterson commented
:shipit:

2017-04-17 15:34 UTC, merged