Check parameters as they are passed into ProgressBase
mantidproject/mantid pull request #19378
Opened 2017-04-13 13:03 UTC by peterfpeterson

Let people know they are giving in bad values.

**To test:**

Find someplace that uses a progress bar and change the `start` or `end` to be outside of `0 <=x<=1`.

*There is no associated issue.*

*Does not need to be in the release notes* because it is an internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-13 13:30 UTC, peterfpeterson commented
Binary operations on MD workspaces apparently set the progress bar up incorrectly.

2017-05-05 07:58 UTC, martyngigg requested changes
The changes themselves look fine.

I think we should add a unit test for the throw behaviour in [ProgressBaseTest](/mantidproject/mantid/blob/master/Framework/Kernel/test/ProgressBaseTest.h)

2017-05-08 07:06 UTC, martyngigg approved these changes

2017-05-08 07:07 UTC, martyngigg commented
Python 3 test failure is a known failure and unrelated to these changes.

:shipit:

2017-05-12 18:30 UTC, merged