New 3D-deltaPDF algorithm
mantidproject/mantid pull request #19384
Opened 2017-04-13 21:59 UTC by rosswhitfield

This add a new algorithm DeltaPDF3D that will calculate the 3D-deltaPDF from a HKL MDHistoWorkspace

**To test:**
Here are some example MDHisto you can use for testing: `/SNS/users/rwp/corelli/IPTS-16617-PMN/PMN_normdata_48sym_300K.nxs`, `/SNS/users/rwp/corelli/IPTS-18149-Dy2Ti2O7/DTO_normdata_48sym_680mK_H0.8T.nxs`, `/SNS/users/rwp/benzil/benzil_300K_bkg_subtract_sym_All_noCC_flat2.nxs`

Run the DeltaPDF3D algorithm on these (read the docs) and see that something comes out the other side.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-17 19:47 UTC, rosswhitfield commented
I just found a problem with the indexing order of `CreateMDHistoWorkspace` being different to how the signalArray is exposed, so I will need to fix that first.

2017-04-25 15:07 UTC, AndreiSavici requested changes

2017-04-25 15:07 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
> +                                x_min=np.searchsorted(X,h-width[0])
Is `searchsorted` faster than calculating the index by hand? You know that MDHistoWorkspaces have a regular grid?

2017-04-25 15:07 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
> +        signal=np.fft.fftshift(np.fft.fftn(np.fft.ifftshift(signal))).real
Have you looked at pyFFTW? That might be faster

2017-04-25 15:07 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
> +        if inWS.getNumExperimentInfo() > 0:
In principle you can copy all experiment infos.

2017-04-25 15:52 UTC, rosswhitfield commented on Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
> +            for h in range(int(np.ceil(dimX.getMinimum())), int(np.floor(dimX.getMaximum()))+1):
No it's not.

2017-04-25 15:54 UTC, rosswhitfield commented on Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
> +        signal=np.fft.fftshift(np.fft.fftn(np.fft.ifftshift(signal))).real
I will try that out later but I don't really want to add a new dependency to Mantid just for this.

If it is faster I might optionally use pyFFTW over numpy.fft if it's available.

2017-04-28 20:06 UTC, AndreiSavici approved these changes
:shipit:

2017-04-28 20:14 UTC, merged