Add exed
mantidproject/mantid pull request #19393
Opened 2017-04-17 21:47 UTC by granrothge

Description of work.

**To test:**

Open DGSPlanner from MantidPlot.
Pick Exed, 
Select plot
 

Fixes #19383.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-04-18 23:06 UTC, AndreiSavici requested changes
Pretty important milestone to add a new facility. I think it should be added to release notes as well. Maybe even a picture for the release notes

2017-04-18 23:08 UTC, AndreiSavici commented
When testing this PR, I found a bug introduced since last release: I cannot do the fast plotting (masking detectors). I get 
```
MaskDetectors-[Notice] MaskDetectors started
MaskDetectors-[Error] Error in execution of algorithm MaskDetectors:
MaskDetectors-[Error] _Map_base::at
```

2017-04-20 16:07 UTC, granrothge commented on scripts/DGSPlanner/InstrumentSetupWidget.py
> +        self.instrumentList=['ARCS','CNCS','DNS','FOCUS','HET','HYSPEC','LET','MAPS','MARI','MERLIN','SEQUOIA','EXED']
I'll Fix these.

2017-04-20 16:08 UTC, granrothge commented on instrument/EXED_Definition.xml
> +<instrument name="EXED" date="6th Mar 2017"
I will probably pull the date field.  I'll look at the instrument definition and make sure it is more in line with standards.

2017-04-20 16:16 UTC, granrothge commented
I am working on a load routine.  Once that is ready for a pull request,  I will add the instrument to the release notes.

2017-04-20 18:11 UTC, granrothge commented on instrument/EXED_Definition.xml
> +<instrument name="EXED" date="6th Mar 2017"
I matched the date format to other instrument definition files and updated the pixel sizes appropriately

2017-04-20 18:52 UTC, AndreiSavici approved these changes

2017-04-20 18:52 UTC, AndreiSavici commented
Looks good. :shipit:

2017-04-21 15:33 UTC, AndreiSavici commented
The `ValidateInstrumentDefinitionFiles` systemtest failed
```
22:17:40 Validating '/opt/mantidunstable/instrument/EXED_Definition.xml'
22:17:40 VALIDATION OF '/opt/mantidunstable/instrument/EXED_Definition.xml' FAILED WITH ERROR:
22:17:40 ERROR: EXED_Definition.xml: line 2: Used root tag (None, u'instrument') not found in schema file(s)!
```

2017-04-22 02:04 UTC, granrothge commented
I think I fixed the schema problem.  We'll see.

2017-04-25 13:20 UTC, granrothge commented
Finally passed.  Can someone merge this?

2017-04-25 14:17 UTC, merged