Publish system tests for ISIS SANS
mantidproject/mantid pull request #19394
Opened 2017-04-18 08:11 UTC by AntonPiccardoSelg

Fixes #19364

## **Important**
The changes here rely on #19333,  #19351,  #19360,  #19372 and #19373; do **not review** before this has been merged. Once they have been merged the code size will have gone down dramatically.

This PR exposes a new set of system tests for the new ISIS SANS reduction backend.

**To test:**
Please code review. These changes are part of larger set of complete changes which are currently being tested by the ISIS SANS team.

*Does not need to be in the release notes.*
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-22 14:14 UTC, dtasev requested changes

2017-05-22 14:14 UTC, DTasev commented on Testing/SystemTests/tests/analysis/SANSMergedDetectorsTest_V2.py
> +        from mantid.simpleapi import SaveNexus
Can this be moved to be part of the import at the start of the file?

2017-05-22 14:15 UTC, DTasev commented
Looks good, I've just added a minor comment.

2017-05-22 14:16 UTC, AntonPiccardoSelg commented on Testing/SystemTests/tests/analysis/SANSMergedDetectorsTest_V2.py
> +        from mantid.simpleapi import SaveNexus
Actually, this can be removed :+1:

2017-05-24 08:48 UTC, AntonPiccardoSelg commented
There is an issue with `SpectrumNumberTranslator` which I think has changed recently. I could use @SimonHeybrock for this.

2017-05-24 10:41 UTC, dtasev approved these changes

2017-05-24 10:43 UTC, DTasev commented
If it's going to be a significant change maybe you could do it in a separate PR? Or I can wait until it's ready before shipping it, your call

2017-05-24 10:46 UTC, AntonPiccardoSelg commented
@Dtasev It is not clear what the change will have to be. It might uncover a logical flaw in the core. The fix would be in a separate PR. At this point we cannot ship this PR yet, I will let you know if there is any news on this. Worst case we have to bump this back to 3.11.

2017-05-24 11:12 UTC, SimonHeybrock commented
@AntonPiccardoSelg Could you clarify, I am not sure which issue you are referring to.

2017-05-24 12:55 UTC, AntonPiccardoSelg commented
@SimonHeybrock I think I have figured it out. Some updates to the `SpectrumNumberTranslator` and surrounding code, have pointed out an inconsistency in the SANS code.

2017-05-26 10:27 UTC, AntonPiccardoSelg commented
@DTasev Your change request has been applied, the underlying bug has been resolved in #19686

2017-05-26 16:02 UTC, AndreiSavici commented
Is this ready to be merged?

2017-05-28 06:33 UTC, DTasev commented
Yes, the changes look good, the related bug has been resolved in another issue. Looks good, happy to :shipit:

2017-05-28 19:38 UTC, merged