Export data processor widget
mantidproject/mantid pull request #19430
Opened 2017-04-24 15:18 UTC by AntonPiccardoSelg

Description of work.

**To test:**

No issue number here

No release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-07 21:34 UTC, AntonPiccardoSelg commented
@PranavBahuguna  The issues on the `DataProcessorWidget` PR have finally been resolved and it is ready for final testing The python 3 tests are failing because of the general PowderDiffraction issue). To build it locally you might have to clean the `CustomInterfaces` target. `sip` apparently does not play well with incremental builds.

2017-05-23 08:52 UTC, AntonPiccardoSelg commented
Given the timeline and since this is a non-user facing change that will only be used in features in `3.11`. I makes sense to push this to `3.11`.

2017-06-26 15:45 UTC, PranavBahuguna commented on scripts/Interface/ui/dataprocessorinterface/data_processor_gui.py
> +        # Metdho 'addElement' adds a column to the widget
Typo - "Method"

2017-06-26 15:45 UTC, PranavBahuguna commented on MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp
> +      // No pre-processing needed
Can get rid of this comment.

2017-06-26 15:45 UTC, PranavBahuguna commented on MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp
> +      // alg->setPropertyValue(propertyName, globalOptions);
Do we need this if it is commented out?

2017-06-26 15:45 UTC, PranavBahuguna commented on docs/source/interfaces/DataProcessorWidget.rst
> +The only effect of the blaklist is on the *Options* column, not in the reduction. This column uses a *HintingLineEdit* (a MantidWidget)
Typo - 'blacklist'

2017-06-26 15:45 UTC, PranavBahuguna commented on docs/source/interfaces/DataProcessorWidget.rst
> ++-------------------------------------+----------------------------------------------------------+
There are no descriptions of these classes. Should there be descriptions or has it been left blank on purpose?

2017-06-27 07:40 UTC, PranavBahuguna requested changes
A major problem I found is when attempting to process any rows, the interface concatenates all property values set as a single string and attempts to use it as a value for the `Filename` property, throwing an error. I suspect this is related to your changes since this was not an error that existed when I had previously reviewed this with Raquel.

There are also a few minor issues in documentation and some typos that need addressing.

2017-06-27 07:55 UTC, AntonPiccardoSelg commented
Once the async stuff is in master I will address these issues

2017-06-30 09:14 UTC, PranavBahuguna commented
New code seems good, probably best to just remove the class descriptions for now. Good to go once that is done and checks pass.

2017-06-30 10:59 UTC, PranavBahuguna commented
:shipit: once checks pass

2017-06-30 11:00 UTC, PranavBahuguna commented
:shipit:

2017-06-30 11:08 UTC, PranavBahuguna approved these changes

2017-07-03 09:52 UTC, ianbush commented
I assume the inclusion of `MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp.orig` is a mistake?

2017-07-03 11:33 UTC, merged