Update kafka event listener to new schema
mantidproject/mantid pull request #19489
Opened 2017-05-05 09:01 UTC by matthew-d-jones

Updated the `KafkaEventListener` to use new schema for neutron event data which is designed for use by PSI, ESS and ISIS.
As part of this change the event data topic can consist of multiple partitions, allowing streaming through multiple brokers in a Kafka cluster to achieve higher throughput.

Removed mention of the Kafka listener from the release notes as it is still undergoing major changes, including to the interface. This was agreed on at the IBEX-Kafka-Mantid meeting 3 Mar 2017.

**To test:**

Fixes #19358.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-18 14:01 UTC, martyngigg commented
@matthew-d-jones If this is marked for 3.11 then the release note change won't get in. Was that intended?

2017-05-18 14:43 UTC, matthew-d-jones commented
@martyngigg That wasn't intended, I forgot about the release note change. It would be best to get this into 3.10.

2017-05-18 14:46 UTC, martyngigg commented
@matthew-d-jones Thanks for the clarification. I'll get on and review it.

2017-05-18 15:38 UTC, matthew-d-jones commented on Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp
> +                                              1e-9, // nanoseconds to seconds
This should be `1e-3, // nanoseconds to microseconds`

2017-05-19 08:11 UTC, martyngigg requested changes
Code generally looks good.

Just a few minor style points suggested. I'll do some functional testing now.

2017-05-19 08:50 UTC, martyngigg commented
I'm just running through some tests and I don't quite see the expected behaviour.

After a while I get a workspace with only `9496266` events. Also when I try to cancel `MonitorLiveData` it gets stuck and won't stop. `gdb` indicates that it's stuck in `rdkafka`:

```
(gdb) thread 12
[Switching to thread 12 (Thread 0x7f4d337fe700 (LWP 6386))]
#0  0x00007f4d9ffaf98d in pthread_join (threadid=139969393833728, thread_return=0x7f4d337fd200) at pthread_join.c:90
90      pthread_join.c: No such file or directory.
(gdb) bt
#0  0x00007f4d9ffaf98d in pthread_join (threadid=139969393833728, thread_return=0x7f4d337fd200) at pthread_join.c:90
#1  0x00007f4d6ca3a700 in ?? () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#2  0x00007f4d6c9e5f94 in rd_kafka_destroy () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#3  0x00007f4d6cc8259e in RdKafka::KafkaConsumerImpl::close() () from /usr/lib/x86_64-linux-gnu/librdkafka++.so.1
#4  0x00007f4d6cfca560 in Mantid::LiveData::KafkaTopicSubscriber::~KafkaTopicSubscriber (this=0x7f4d680057c0, __in_chrg=<optimised out>) at ../../Framework/LiveData/src/Kafka/KafkaTopicSubscriber.cpp:81
#5  0x00007f4d6cfca5da in Mantid::LiveData::KafkaTopicSubscriber::~KafkaTopicSubscriber (this=0x7f4d680057c0, __in_chrg=<optimised out>) at ../../Framework/LiveData/src/Kafka/KafkaTopicSubscriber.cpp:91
#6  0x00007f4d6cfc0744 in std::default_delete<Mantid::LiveData::IKafkaStreamSubscriber>::operator() (this=0x7f4d68002a88, __ptr=0x7f4d680057c0) at /usr/include/c++/5/bits/unique_ptr.h:76
#7  0x00007f4d6cfbee5d in std::unique_ptr<Mantid::LiveData::IKafkaStreamSubscriber, std::default_delete<Mantid::LiveData::IKafkaStreamSubscriber> >::~unique_ptr (this=0x7f4d68002a88, __in_chrg=<optimised out>)
    at /usr/include/c++/5/bits/unique_ptr.h:236
#8  0x00007f4d6cfb7fb8 in Mantid::LiveData::KafkaEventStreamDecoder::~KafkaEventStreamDecoder (this=0x7f4d68002a10, __in_chrg=<optimised out>)
    at ../../Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp:71
#9  0x00007f4d6cfb6616 in std::default_delete<Mantid::LiveData::KafkaEventStreamDecoder>::operator() (this=0x7f4d68004128, __ptr=0x7f4d68002a10) at /usr/include/c++/5/bits/unique_ptr.h:76
#10 0x00007f4d6cfb5da1 in std::unique_ptr<Mantid::LiveData::KafkaEventStreamDecoder, std::default_delete<Mantid::LiveData::KafkaEventStreamDecoder> >::~unique_ptr (this=0x7f4d68004128, 
    __in_chrg=<optimised out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#11 0x00007f4d6cfb74e4 in Mantid::LiveData::KafkaEventListener::~KafkaEventListener (this=0x7f4d680040d0, __in_chrg=<optimised out>, __vtt_parm=<optimised out>)
    at ../../Framework/LiveData/inc/MantidLiveData/Kafka/KafkaEventListener.h:43
#12 0x00007f4d6cfb7554 in Mantid::LiveData::KafkaEventListener::~KafkaEventListener (this=0x7f4d680040d0, __in_chrg=<optimised out>, __vtt_parm=<optimised out>)
    at ../../Framework/LiveData/inc/MantidLiveData/Kafka/KafkaEventListener.h:43
#13 0x00007f4d6cfb7a1f in boost::checked_delete<Mantid::LiveData::KafkaEventListener> (x=0x7f4d680040d0) at /usr/include/boost/core/checked_delete.hpp:34
#14 0x00007f4d6cfb7aac in boost::detail::sp_counted_impl_p<Mantid::LiveData::KafkaEventListener>::dispose (this=0x7f4d68001710) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:78
#15 0x00007f4d6cf519d2 in boost::detail::sp_counted_base::release (this=0x7f4d68001710) at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#16 0x00007f4d6cf51a65 in boost::detail::shared_count::~shared_count (this=0x7f4d337fd508, __in_chrg=<optimised out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#17 0x00007f4d6cf89ad4 in boost::shared_ptr<Mantid::API::ILiveListener>::~shared_ptr (this=0x7f4d337fd500, __in_chrg=<optimised out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#18 0x00007f4d6cf9da1b in Mantid::LiveData::MonitorLiveData::exec (this=0x7f4d683f4230) at ../../Framework/LiveData/src/MonitorLiveData.cpp:110
#19 0x00007f4da6f584b4 in Mantid::API::Algorithm::execute (this=0x7f4d683f4230) at ../../Framework/API/src/Algorithm.cpp:548
#20 0x00007f4da6f5df8d in Mantid::API::Algorithm::executeAsyncImpl (this=0x7f4d683f4230) at ../../Framework/API/src/Algorithm.cpp:1491
#21 0x00007f4da6f71e82 in Poco::ActiveRunnable<bool, Poco::Void, Mantid::API::Algorithm>::run (this=0x7f4d683f8080) at /usr/include/Poco/ActiveRunnable.h:65
#22 0x00007f4da5352d82 in Poco::PooledThread::run() () from /usr/lib/libPocoFoundationd.so.31
#23 0x00007f4da534fd8d in ?? () from /usr/lib/libPocoFoundationd.so.31
#24 0x00007f4da534fa34 in Poco::ThreadImpl::runnableEntry(void*) () from /usr/lib/libPocoFoundationd.so.31
#25 0x00007f4d9ffae6ba in start_thread (arg=0x7f4d337fe700) at pthread_create.c:333
#26 0x00007f4d9fce482d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) thread 13
[Switching to thread 13 (Thread 0x7f4d29ffb700 (LWP 6393))]
#0  0x00007f4d9ffaf98d in pthread_join (threadid=139968815032064, thread_return=0x7f4d29ffac80) at pthread_join.c:90
90      in pthread_join.c
(gdb) bt
#0  0x00007f4d9ffaf98d in pthread_join (threadid=139968815032064, thread_return=0x7f4d29ffac80) at pthread_join.c:90
#1  0x00007f4d6ca3a700 in ?? () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#2  0x00007f4d6c9e1705 in ?? () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#3  0x00007f4d6c9e2591 in ?? () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#4  0x00007f4d6ca3a237 in ?? () from /usr/lib/x86_64-linux-gnu/librdkafka.so.1
#5  0x00007f4d9ffae6ba in start_thread (arg=0x7f4d29ffb700) at pthread_create.c:333
#6  0x00007f4d9fce482d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```
Have you observed this?

2017-05-19 09:12 UTC, matthew-d-jones commented
The changes in this PR require a bug fix which will be in the next release of `librdkafka` (v0.9.6).

2017-06-16 09:29 UTC, peterfpeterson submitted a review, later dismissed
This is a test

2017-10-13 14:38 UTC, mantid-builder commented
@matthew-d-jones have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2017-10-16 09:10 UTC, matthew-d-jones commented
@mantid-builder I've got conferences for the next two weeks, after that I'll look into updating `librdkafka` and sorting out this PR.

2017-11-24 11:30 UTC, mantid-builder commented
@matthew-d-jones have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2017-12-08 13:13 UTC, closed without merging