Fixed bin edges as vertical axis in CreateWorkspace
mantidproject/mantid pull request #19526
Opened 2017-05-10 13:00 UTC by soininen

This PR fixes a check in [`CreateWorkspace`](http://docs.mantidproject.org/nightly/algorithms/CreateWorkspace-v1.html) which would reject bin edges as vertical axis.

**To test:**

The following script should fail before these changes are applied:
```python
import numpy

ys = numpy.array([1.0])
xs = numpy.array([0.0])
vertAxis = "0.1, 0.2"
ws = CreateWorkspace(DataX=xs, DataY=ys, VerticalAxisUnit='MomentumTransfer', VerticalAxisValues=vertAxis)
```

Fixes #19525.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-12 12:48 UTC, dtasev requested changes

2017-05-12 12:48 UTC, DTasev commented on Framework/Algorithms/src/CreateWorkspace.cpp
> +  if (vUnit != "SpectraNumber" &&
A comment here explaining what it does would be nice, from a brief look it's very hard to interpret what the many nested conditions do. Maybe a refactoring of the condition would be better

2017-05-12 12:48 UTC, DTasev commented
I've tested it locally and had a play with adding different number of spectra, bins, increasing x and y, and found no issues. Apart from a minor comment it looks good

2017-05-16 12:19 UTC, dtasev approved these changes

2017-05-16 12:19 UTC, DTasev commented
Tested locally with example, everything worked as described. Had a play and I think everything looks alright, I'm happy to :shipit:

2017-05-17 07:07 UTC, merged