Set DetID before Q to prevent ray tracing when loading a peaks workspace
mantidproject/mantid pull request #19524
Opened 2017-05-10 09:05 UTC by samueljackson92

This changes how LoadNexusProcessed creates a `Peak` object to set the detector ID before Q. This means that the peaks workspace will not perform ray tracing and will just use the data loaded from file.

**To test:**
There is a peaks workspace attached to the issue that you can use for testing. This is now also in the unit test data.

 - Try opening the file before applying changes. 
 - Go get a coffee. On my machine this took ~5 mins.
 - Try opening the file with the changes applied. It should take significantly less time.

Fixes #19522 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-10 11:10 UTC, quantumsteve requested changes

2017-05-10 11:10 UTC, quantumsteve commented on Framework/DataHandling/src/LoadNexusProcessed.cpp
> +    peakWS->addPeak(*peak);
Should we add something like `void PeaksWorkspace::addPeak(Geometry::Peak &&peak)` to move, rather than copy, each `Peak`?

2017-05-10 19:36 UTC, quantumsteve commented on Framework/DataObjects/inc/MantidDataObjects/PeaksWorkspace.h
> +  void addPeak(Peak &&ipeak);
If you make other changes, change the variable name here and in Peaksworkspace.cpp to `peak`.

Beyond that, I'll defer to the other reviews.

2017-05-10 19:36 UTC, quantumsteve approved these changes

2017-05-12 10:10 UTC, KarlPalmen commented
Noting that two reviewers have been invited, but have not responded :shipit: .

2017-05-12 12:51 UTC, merged

2017-05-12 12:51 UTC, KarlPalmen commented
Without the change, the file attached to the issue, took between 3 or 4 minutes to load. With the change it took a small number of seconds. (Windows 7)