Indirect ILL: Background subtraction from vanadium run
mantidproject/mantid pull request #19543
Opened 2017-05-12 14:23 UTC by gvardany

To be written...

**Do not merge before PR #19227**

**To test:**

Fixes #19448 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-23 14:43 UTC, DavidFair commented
I've downloaded the attached zip however run 091515 is missing?

2017-05-23 14:51 UTC, DavidFair requested changes

2017-05-23 14:51 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Indirect/ILLEnergyTransfer.cpp
> +          "Scale factor for calibration background is invalid.");
Can we inform the user that the scale factor must be a number and > 0

2017-05-23 14:51 UTC, DavidFair commented on Testing/SystemTests/tests/analysis/ILLIndirectReductionFWS.py
> +        self.assertEquals(mtd['efws_calib_bg_red'].getItem(0).getNumberHistograms(), 18)
Can we assert some Y data values so future developers are sure their changes don't affect the results.

2017-05-23 14:51 UTC, DavidFair commented on Testing/SystemTests/tests/analysis/ILLIndirectReductionQENS.py
> +        self.assertEquals(mtd['out_calib_bg_red'].getItem(0).getNumberHistograms(), 18)
^ Assert on Y Data values

2017-05-23 14:52 UTC, gvardany commented
I have corrected the run numbers.

2017-05-23 14:56 UTC, DavidFair commented
Testing verifies that the background for the calibration is being applied correctly. I also checked the validation and that  also handles bad values correctly.
Its just the a few minor points picked up in the code review otherwise everything looks good.

2017-05-23 16:21 UTC, gvardany commented
I have addressed the comments.

2017-05-24 08:46 UTC, DavidFair commented
Everything looks good to me. Once the builds finish :shipit:

2017-05-24 08:48 UTC, DavidFair approved these changes

2017-05-24 15:50 UTC, AndreiSavici commented
Unrelated failure on `SliceViewerPythonInterfaceTest`

2017-05-26 10:13 UTC, merged