Muon multiple fitfing gui
mantidproject/mantid pull request #19545
Opened 2017-05-12 15:31 UTC by AnthonyLim23

This is the first phase of an upgrade to the multiple fitting GUI in muon analysis to make it more user friendly. 

**To test:**

There are multiple tests. I recommend using HIFI data (never use the current run) as it has both multiple periods and groups. 

0. The input parameters change after a simultaneous fit if a different data set is selected for display (assuming it is not global). 

1. Changing the Groups/Pairs to fit option updates the GUI correctly. So the relevant data should be listed in the Display parameters for drop down menu. A fit should use the relevant data (can check by doing a tiled plot of the output workspace). 

2. Changing the periods to fit option updates the GUI correctly. The response should be similar to the above. 

3. If custom is selected from the drop down menus (in 1 and 2) then the relevant pop up is produced and data is passed to the GUI correctly. If you press the Reselect Groups/Pairs or Periods buttons (will only be enabled if the relevant drop down menu is set to custom) the pop up menu should reappear. 

4. If the data has multiple periods, the Combine Periods button will produce a pop up that allows users to create combinations of periods. This should be added to the period drop down and pop ups. Check that the data is passed to the GUI correctly. 

5. Changing the start and end alters the fit. 

Fixes #19149 and is to be merged after #19454 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-15 12:38 UTC, AnthonyLim23 commented
I have updated the comparison branch, to remove the files from the other PR

2017-05-16 12:09 UTC, AnthonyLim23 commented
Just found a bug, which I am going to fix now

2017-05-18 11:32 UTC, DTasev commented
Issues found from testing:
- `Combine Periods`, `Periods` and `Groups/Pair` buttons in multiple fitting stop Mantid from closing, if you try closing Mantid while one of them is open
  - You can also open multiple instances of each, maybe the view wasn't set as the parent? (I haven't looked at the code yet)
- The Global checkboxes in the `Fit Function` section of multiple fitting are grayed out and look like inactive, yet they seem to be active and clickable, I think they should be reverted to look like normal enabled checkboxes (different issue ?)

Apart from that, after following the testing instructions and with some help from @AnthonyLim23 I went through the testing directions and found no other issues, everything seemed to be working as described.

2017-05-18 11:57 UTC, AnthonyLim23 commented
I can add a check for if the pop-ups are open. I'm not sure about the closing. 

The global checkboxes are unchanged from the current release.

2017-05-18 14:04 UTC, dtasev requested changes
Just a few minor comments

2017-05-18 14:04 UTC, DTasev commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  // m_uiForm.
unfinished comment?

2017-05-18 14:04 UTC, DTasev commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
Is there a reason for these to be `mutable`? They're never changed inside a `const` function

2017-05-18 14:07 UTC, AnthonyLim23 commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
for which one to be mutable?

m_normalizationValue is overwritten

2017-05-18 14:08 UTC, AnthonyLim23 commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  // m_uiForm.
thought I had caught all of them. Its an old bit of code, not needed anymore (as you have seen). 

Thank you for spotting it

2017-05-18 14:11 UTC, DTasev commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
`m_normalizationValue` and a few of the other variables below it are set to mutable

2017-05-18 14:14 UTC, AnthonyLim23 commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
these are all overwritten at other points in the code. 

m_normalization -> in TFAsymmfit
m_groupsToFitOptions -> in addGroupCheckbox
m_ShowGroupValues -> in updateGroupDisplay

similarly for periods.

2017-05-18 14:17 UTC, DTasev commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
They're not changed inside `const` functions, the `mutable` keyword does not do anything here, it's only confusing

2017-05-18 14:21 UTC, AnthonyLim23 commented on MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/MuonFitPropertyBrowser.h
>    mutable QStringList m_normalizationValue;
I will try removing it. I have a vague recollection of it not working.

2017-05-18 15:54 UTC, AnthonyLim23 commented
fixed them

2017-05-19 08:26 UTC, dtasev approved these changes

2017-05-19 08:39 UTC, DTasev commented
Everything looks good, I did the testing after the review comments and other fixes have been added, and found no further issues. I'm happy to :shipit:

2017-05-19 18:25 UTC, merged