New unit for TOF powder diffraction
mantidproject/mantid pull request #19556
Opened 2017-05-16 07:21 UTC by mganeva

Implemented new unit for the TOF powder diffraction. 

**To test:**

Can be tested on sample workspaces, for example:
```python
ws = CreateSampleWorkspace(WorkspaceType="Histogram", Function="Powder Diffraction", NumBanks=1, XUnit="TOF")
ws_dp = ConvertUnits(ws, Target="dSpacingOrth", EMode="Direct")
```

The calculations are tested with Unittests, but can also be tested with a Python script, for example:
```python
from scipy.constants import m_n, h
import numpy as np

ssd = 10.0   # source-sample distance, default for CreateSampleWorkspace
sdd = 5.0     # source-detector distance

def d_perp (t, theta):
    tmp = h*1e+10/(m_n*(ssd + sdd)*1e+6)*t
    return np.sqrt(tmp*tmp - 2.0*np.log(np.cos(theta)))
    
ws = CreateSampleWorkspace(WorkspaceType="Histogram", Function="Powder Diffraction", NumBanks=1, XUnit="TOF")
ws_dp = ConvertUnits(ws, Target="dSpacingOrth", EMode="Direct")

ws_index = 0
x_tof = ws.readX(ws_index)
x_dp = ws_dp.readX(ws_index)
det = ws.getDetector(ws_index)
two_theta = ws.detectorTwoTheta(det)

x_dp_test = d_perp(x_tof, 0.5*two_theta)
print np.allclose(x_dp, x_dp_test, atol=1e-07)
```

Fixes #19532

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-18 15:06 UTC, louisemccann commented
The examples above work fine. I tried converting back to TOF:
`ws_tof = ConvertUnits(ws_dp, Target="TOF", EMode='Direct')`
and the zero values are a bit off. Everything else is fine
![image](https://cloud.githubusercontent.com/assets/12883435/26209131/e5b92754-3be3-11e7-9d82-0500b074d013.png)

2017-05-19 08:04 UTC, mganeva commented
@louisemccann Very nice point! Thank you for reviewing. I think, I've found the reason, I will fix it today.

2017-05-19 10:45 UTC, louisemccann commented
looks good to me :shipit:

2017-05-19 17:31 UTC, AndreiSavici requested changes
I asked several instrument scientists and programmers for powder diffraction and no one knows what `dSpacingOrth` is. We need some documentation why we need this unit, and where it is used. Also, the name is not nice. Should it be `perpendiculardSpacing` or `dSpacingPerpendicular` instead?

2017-05-19 17:31 UTC, AndreiSavici commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
This comment is incompatible with the rest of the ticket. Should there be `cos` instead?

2017-05-19 17:50 UTC, mganeva commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
you are right, it should be cos. The implementation is correct, error is in the comment.

2017-05-19 17:51 UTC, mganeva commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
I will change the name to dSpacingPerpendicular and write some additional documentation about unit. Where to put it?

2017-05-19 18:22 UTC, AndreiSavici commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
Just add it to `UnitFactory.rst` concept page

2017-05-19 18:39 UTC, mganeva commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
For me it is also unusual. The idea was to create a unit which is orthogonal to dSpacing(theta, lambda). This is needed for 2D Rietveld refinement of TOF powder diffraction data from POWTEX@MLZ and DREAM@ESS due to specific detector construction. We plan to test the approach at POWGEN soon.

2017-05-19 18:47 UTC, AndreiSavici commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
Just add a detailed description (with formula) or a paper reference, to show what this unit is all about. What I mean is that I want to be able to check that the formula that you implement makes sense or not

2017-05-19 18:48 UTC, mganeva commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
Some more information may be found here, in the talk of A. Houben: https://indico.esss.lu.se/event/785/session/5/material/0/3.pdf

2017-05-19 19:06 UTC, mganeva commented on Framework/Kernel/src/Unit.cpp
> + * Conversion uses equation: d^2 = lambda^2 - 2[Angstrom^2]*ln(sin(theta))
I will do it by Monday.

2017-05-22 14:54 UTC, AndreiSavici approved these changes

2017-05-22 14:56 UTC, merged