New loader for ILL diffractometers
mantidproject/mantid pull request #19560
Opened 2017-05-16 13:37 UTC by gvardany

TBW

**To test:**

Fixes #18868 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-22 09:46 UTC, dtasev requested changes

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +    m_scanVar.emplace_back(ScannedVariables(names[i], properties[i], units[i]));
`push_back`

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +      m_outWorkspace->mutableY(i)[j] = y;
move `m_outWorkspace->mutableY(i)` to a variable outside the inner most for loop

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +      m_outWorkspace->mutableE(i)[j] = sqrt(y);
move `m_outWorkspace->mutableE(i)` to a variable outside the inner most for loop

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +    times.emplace_back(time);
`push_back`

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +  times.emplace_back(time);
push_back

2017-05-22 09:46 UTC, DTasev commented on Framework/Nexus/inc/MantidNexus/NexusClasses.h
> +  NXUInt openUIntData() { return openData<unsigned int>(); }
Why add `unsigned int`? Shouldn't `size_t` be used instead?

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +  NXUInt data = dataGroup.openUIntData();
Why not use `NXSize` with `dataGroup.OpenSizeData()`?

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +    fillMovingInstrumentScan(data, scan);
Empty function definition in header?

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
> +  void fillMovingInstrumentScan(const NeXus::NXUInt &,
As comment below, why add `NXUInt` instead of using `NXSize`?

2017-05-22 09:46 UTC, DTasev commented on Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
> +  void fillStaticInstrumentScan(const NeXus::NXUInt &, const NeXus::NXDouble &,
See above

2017-05-22 09:46 UTC, DTasev commented on Framework/Nexus/inc/MantidNexus/NexusClasses.h
> +typedef NXDataSetTyped<unsigned int> NXUInt;
See comment below

2017-05-23 16:33 UTC, gvardany commented on Framework/DataHandling/CMakeLists.txt
> +        src/LoadILLSANS.cpp
I think this is a github diff artefact. In reality it is aligned.

2017-05-23 16:34 UTC, gvardany commented on Framework/DataHandling/CMakeLists.txt
> +        LoadILLTOF2Test.h
same here

2017-05-23 16:38 UTC, gvardany commented on Framework/DataHandling/src/LoadILLDiffraction.cpp
> +    fillMovingInstrumentScan(data, scan);
This is a place holder that will be filled later on in a separate PR when the scanning workspace functionality is ready. I can remove it for now, but this part must be refactored later anyways.

2017-05-24 08:55 UTC, NickDraper commented
@gvardany Could you have a look at this stuck PR, it needs attention son if it is going to make it into this release.

2017-05-24 09:41 UTC, gvardany commented
@NickDraper I am working on it right now, it will be finalised in a few hours, I hope it is not too late.

2017-05-24 09:45 UTC, gvardany commented on Framework/Nexus/inc/MantidNexus/NexusClasses.h
> +  NXUInt openUIntData() { return openData<unsigned int>(); }
The entries in the nexus files are specifically unsigned int (and not unsigned long) type, so when I try to read with openSizeData I get spurious numbers wrongly read from memory.

2017-05-24 10:40 UTC, dtasev approved these changes

2017-05-24 10:41 UTC, DTasev commented
I'm happy with the changes, there's some merge conflicts that need to be resolved, and then I'd be happy to mark for ship

2017-05-24 11:26 UTC, gvardany commented
@DTasev I have now addressed all of your comments. Except the documentation, which I will push in a bit.

2017-05-24 12:00 UTC, gvardany commented
@DTasev I have completed the documentation also.

2017-05-25 10:42 UTC, DTasev commented
Tested after the changes, everything still works the same. I'm happy to :shipit:

2017-05-28 20:44 UTC, merged