Make the Reflectometry GUI process runs asynchronously
mantidproject/mantid pull request #19581
Opened 2017-05-18 15:30 UTC by PranavBahuguna

Previously the algorithm execution in the GenericDataProcessorPresenter was not executed asynchronously, which causes Mantid to freeze. This PR allows execution to be performed asynchronously as well as introduce a pause button for halting processing.

**To test:**

- Code review
- Currently no additional unit tests have been written yet and existing ones may fail. This will be amended in the future.
- For now, perform functional testing e.g.:
  - Check that you can operate other parts of the interface while processing runs.
  - Check that window cannot be closed without pausing processing first.
  - Check that only exclusively are the `Process` and `Pause` buttons enabled/disabled, not both.
  - Ensure when pausing processing that the last row/group are processed before fully stopping.
  - Ensure that there is no change in the actual output workspaces after processing from the old interface.

There are probably many ways I haven't thought of to break the interface or do things that have unexpected side effects. Notify me of anything that feels strange to you and I will look into it.

A simple way of obtaining runs to reduce with is to login to the ICAT catalog, set current instrument to `POLREF`, enter id `1520249` and transfer them over.

Fixes #19480.

*Release notes will be updated later.*

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-19 09:06 UTC, AntonPiccardoSelg requested changes

2017-05-19 09:06 UTC, AntonPiccardoSelg commented on MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp
> +    auto *worker = new GenericDataProcessorPresenterRowReducerWorker(
See above

2017-05-19 09:28 UTC, PranavBahuguna commented on MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/IReflPresenter.h
> +    PauseFlag
It can be resumed, so `pause` seems appropriate here.

2017-06-27 09:09 UTC, AntonPiccardoSelg approved these changes

2017-06-27 09:10 UTC, AntonPiccardoSelg commented
Tested with all of the instructions. The functionality works as expected. The GUI does not freeze any longer and the reduction can be paused and restarted. The outputs are still the same as in the old reduction. Please :shipit:

2017-06-27 12:18 UTC, AntonPiccardoSelg commented
@mantidproject/gatekeepers I just wanted to bump this PR, since other pieces of work rely on it.

2017-06-28 10:12 UTC, merged