Add exed loader
mantidproject/mantid pull request #19670
Opened 2017-05-23 16:15 UTC by granrothge

Adds a python Algorithm to load files from the Exed Beamline at HZB.

use the system test to test.

Fixes 19416.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-05-23 22:57 UTC, AndreiSavici commented
Changing from `CreateWorkspace` to `WorkspaceFactory.create` reduced execution time from 20s to 1 s

2017-05-23 23:08 UTC, AndreiSavici requested changes
I would remove all print statements as well

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +
I would add a `OutputMonitorWorkspace` property. This would allow an easier use of handles, something like `dataWS,monitorWS=LoadEXED(filename)`

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        from mantid.simpleapi import LoadInstrument
Move all imports at the beginning

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +def read_file(fn):
Is there a reason not to move these functions to be part of the `LoadEXED` class?

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +    __doc__ = """This is the EXED data loader written in Python.
Merge the `__doc__` and the output of summary, and move some of it to the rst file

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        if (self.fxml == ""):
Don't need the if statement, just pass both `InstrumentName` and `Filename`. If the filename is specified, it will load that

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        ws = WorkspaceFactory.create("Workspace2D", NVectors=nr,
I would create the monitor workspace here

2017-05-23 23:08 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        SetGoniometer(Workspace=wsn, Goniometers='Universal', Axis0='phi,0,1,0,1')
`Axis0` has no effect if `Goniometers='Universal'`

2017-05-25 15:56 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +def read_file(fn):
For testing outside of Mantid.  I will move them inside. the class

2017-05-25 16:05 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        from mantid.simpleapi import LoadInstrument
I'll move the imports to the beginning.

2017-05-25 16:17 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +    __doc__ = """This is the EXED data loader written in Python.
I will do this.

2017-05-25 17:49 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +
I don't want to break user scripts at this time.  I will make this an issue for the next release.

2017-05-25 17:57 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        if (self.fxml == ""):
This is clearer and I don't want to rely on undocumented  features.

2017-05-25 18:01 UTC, granrothge commented on Framework/PythonInterface/plugins/algorithms/LoadEXED.py
> +        ws = WorkspaceFactory.create("Workspace2D", NVectors=nr,
I will do this in the next release.  Once I have a more robust test suite.

2017-05-25 19:27 UTC, AndreiSavici approved these changes

2017-05-26 09:10 UTC, merged