AsynchronousTest.testCancelGroupWS randomly fails
mantidproject/mantid pull request #19765
Opened 2017-06-01 10:05 UTC by mantid-roman

Added synchronisation using Poco::Condition.

Fixes #19764.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-01 10:23 UTC, martyngigg reviewed
Any reason we can't use `std::condition_variable` & `std::mutex` here?

2017-06-01 10:25 UTC, mantid-roman commented
Will it work with Poco threading?

2017-06-01 10:27 UTC, martyngigg commented
Yep. The Poco thread classes are just wrappers around the native threading libraries the same as the `std` variants - I don't think it should be a problem.

2017-06-01 10:29 UTC, mantid-roman commented
OK. I'll change.

2017-06-01 10:30 UTC, martyngigg commented
Thanks. I think it's good to use `std` stuff where we can. We should probably think about switching the main algorithm threading to `std::thread` too but that's a different question.

2017-06-01 11:00 UTC, mantid-roman commented
@martyngigg I was wrong, the times are the same.

2017-06-01 13:53 UTC, AntonPiccardoSelg commented
Does this not lead to a potential condition variable deadlock? 
If the test thread acquires the mutex first, it can go all the way down to the point where it waits on cond2. Then the AsyncAlgorithm thread can get the mutex and waits on cond1. But since the test thread is already past the point where it notifies the threads waiting on cond1, AsyncAlgorithm will keep waiting on cond1, which in turn will leave the test thread waiting on cond2. Am I missing something?

2017-06-05 08:33 UTC, martyngigg requested changes
I agree with Anton here. If the threads were slow to start up then the main thread will block indefinitely on the second condition.

2017-06-05 08:33 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
> +    alg.synchronise = true;
Is this correct? `synchronise` is set to true on the parent object but not on the child algorithms so I don't think the `if` statement above will ever fire?

2017-06-06 07:55 UTC, martyngigg reviewed
This looks fine to me now from a functional perspective.

I'm not too fond of the global variables though, even though they are in an an anonymous namespace. Having them here could encourage others to use condition variables in this manner. Can we move them to private variables of the test along with the whole class definition of  `AsyncAlgorithm`?

2017-06-06 07:55 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
Can remove `using namespace std`? We shouldn't encourage its use in headers, even in tests.

2017-06-06 08:22 UTC, mantid-roman commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
But the variables will be static members?

2017-06-06 08:25 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
Do they need to be static?

2017-06-06 08:26 UTC, mantid-roman commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
They have to be passed to the algorithms

2017-06-06 08:30 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
Oh yes, of course. :man_facepalming:

That's okay. At least they are taken out of the global scope and won't clash with other variables in other test headers (The final test binary includes all of the headers in a single file).

2017-06-06 08:34 UTC, mantid-roman commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
We cannot use `DECLARE_ALGORITHM` with a nested class

2017-06-06 08:38 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
Why do we need to use `DECLARE_ALGORITHM` at all if we are instantiating the object directly?

2017-06-06 08:40 UTC, mantid-roman commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
`AlgorithmFactory` is used to clone algorithms to process groups.

2017-06-06 09:15 UTC, martyngigg commented on Framework/API/test/AsynchronousTest.h
>  using namespace std;
Okay. Let's leave it as it is but can we capitalise the names to follow the standard for static variables and still remove the `using namespace std`.

2017-06-06 10:01 UTC, martyngigg approved these changes
I'm happy with these changes now.

2017-06-06 10:15 UTC, martyngigg commented
:shipit:

2017-06-06 16:15 UTC, merged