19747 group 10 python2 to 3 conversion
mantidproject/mantid pull request #19781
Opened 2017-06-01 18:26 UTC by granrothge

updating code to be python 3 compliant.

**To test:**

Fixes #19747

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-06 17:54 UTC, peterfpeterson requested changes

2017-06-06 17:54 UTC, peterfpeterson commented on Testing/SystemTests/tests/analysis/DirectInelasticDiagnostic.py
> +        handle = open(self.saved_diag_file, 'w')
Instead this should be
```python
with open(self.saved_diag_file, 'w') as handle:
```
then indent the code below and remove the explicit `close`

2017-06-06 17:54 UTC, peterfpeterson commented on Testing/SystemTests/tests/analysis/DirectInelasticDiagnostic2.py
> +#python 2 to 3 changes
remove these comments

2017-06-06 17:54 UTC, peterfpeterson commented on Testing/SystemTests/tests/analysis/DirectInelasticDiagnostic2.py
> +        handle = open(self.saved_diag_file, 'w')
Same comment as `Testing/SystemTests/tests/analysis/DirectInelasticDiagnostic.py`

2017-06-19 21:14 UTC, granrothge commented on Testing/SystemTests/tests/analysis/DirectInelasticDiagnostic2.py
> +        handle = open(self.saved_diag_file, 'w')
Updates have been made as requested.

2017-06-20 12:50 UTC, peterfpeterson approved these changes
Looks good once the builds pass

2017-06-23 07:32 UTC, martyngigg commented
Sorry for stepping in here. I resolved what I thought was a trivial merge conflict and then `flake8` moaned again on a different file.

2017-06-23 15:28 UTC, merged