replace nxs with h5py in SANSUtility
mantidproject/mantid pull request #19801
Opened 2017-06-04 21:35 UTC by yxqd

Fixes #19796 

**To test:**

Make sure following tests pass
* systemtest SANSFileChecking
* unittest SANSUtility

No release notes required.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-05 08:04 UTC, AntonPiccardoSelg requested changes

2017-06-05 08:04 UTC, AntonPiccardoSelg commented on scripts/SANS/SANSUtility.py
> +        print("value=", value)
Why do you print here?

2017-06-05 08:04 UTC, AntonPiccardoSelg commented on scripts/SANS/SANSUtility.py
> +        print("end_time=", end_time)
Same as above

2017-06-05 08:04 UTC, AntonPiccardoSelg commented on scripts/SANS/SANSUtility.py
> +        print("mantid_definition=", mantid_definition)
Same as above

2017-06-05 08:16 UTC, AntonPiccardoSelg commented on scripts/SANS/SANSUtility.py
> +    # Original code test it with nexus python. why?
What is the question?

2017-06-05 08:21 UTC, AntonPiccardoSelg commented
@yxqd Is this PR essential for M3.10?

2017-06-05 09:47 UTC, AntonPiccardoSelg commented
I ran `SANSFileChecking` on a Python3 build and it seems to fail for me:
```
Traceback (most recent call last):
File "/home/anton/sources/Mantid3/mantid/Testing/SystemTests/tests/analysis/SANSFileChecking.py", li
ne 180, in test_that_reducer_for_LARMOR_switches_to_correct_IDF_when_outdated_V2
self.assertNotEqual(os.path.normpath(idf_workspace), os.path.normpath(idf_reducer_before))
AssertionError: '/home/anton/sources/Mantid3/mantid/instrument/LARMOR_Definition.xml' == '/home/anton/
sources/Mantid3/mantid/instrument/LARMOR_Definition.xml'
```

I think the might be an issue with `utf-8` encoding.

2017-06-05 18:54 UTC, yxqd commented
Thanks @AntonPiccardoSelg. The bugs are fixed. Please check

2017-06-06 09:11 UTC, AntonPiccardoSelg approved these changes

2017-06-06 09:14 UTC, AntonPiccardoSelg commented
* Code changes look fine
* Tests pass on Python3
* I ran reductions with SANS2D and LARMOR with event-mode data and multi-period event-mode data. This touches parts of the code changes and it seemed fine.
* I ran reductions with LOQ and can confirm that switching of the IDF works fine (this is anyway thoroughly covered by the `SANSFileChecking` tests)

The change is still risky, but at this point there is not more we can do. Hence, please :shipit:

2017-06-06 12:22 UTC, merged