Indirect - QuickRun - Use instrument from algorithm
mantidproject/mantid pull request #19804
Opened 2017-06-05 09:55 UTC by louisemccann

IndirectDiffScan and SofQWMomentsScan now use the instrument selected in the algorithm to search for runs.

**To test:**

Requires access to the ISIS data archive.

IndirectDiffScan:
Search in algorithms for IndirectDiffScan
Runs: `50017 - 50020`
Instrument: `IRIS`
SpectraRange: `105,112`
Leave other fields as default or blank.
Press `Run`
Ensure all runs used are IRIS runs

Repeat for OSIRIS:
Runs: `120223-120227`
Instrument: `OSIRIS`
SpectraRange: `3,962`
Leave other fields as default or blank.
Press `Run`

Also check SofQWMomentsScan
Runs: `50017 - 50020`
Instrument: `IRIS`
SpectraRange: `3,50`
QRange: `0,0.1,2`
EnergyRange: `-0.4,0.01,0.4`
Leave other fields as default or blank.
Press `Run`

Runs: `120223-120227`
Instrument: `OSIRIS`
SpectraRange: `963,1004`
QRange: `0,0.1,2`
EnergyRange: `-0.4,0.01,0.4`
Leave other fields as default or blank.
Press `Run`

Fixes #19803.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-05 19:31 UTC, AndreiSavici commented
`SliceViewer` test failure on OSX

2017-06-06 07:35 UTC, martyngigg requested changes
Can we move this repeated code somewhere common such as `IndirectCommon.py`?

2017-06-06 10:40 UTC, martyngigg approved these changes

2017-06-06 10:49 UTC, martyngigg commented
Good to go.
:shipit:

2017-06-06 16:01 UTC, merged