Group20 to python 3
mantidproject/mantid pull request #19828
Opened 2017-06-08 08:06 UTC by AnthonyLim23

This is the conversion of group 20 into python 3. This is a simple refactoring of the code. It should be compatible with both python 2 and 3. 

Fixes #19821 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-28 13:21 UTC, wdzhou requested changes
There are conflicts in 'scripts/HFIRPowderReduction/HfirPDReductionControl.py'.

I am going to resolve this.

2017-08-29 17:16 UTC, wdzhou approved these changes

2017-08-29 17:17 UTC, wdzhou commented
All changes look good!  :shipit:

2017-08-29 17:31 UTC, rosswhitfield requested changes

2017-08-29 17:31 UTC, rosswhitfield commented on scripts/HFIRPowderReduction/HfirPDReductionGUI.py
> +        for attname in list(self.__dict__.keys()):
You don't need to convert to list if you are iterating over it.

2017-08-29 17:31 UTC, rosswhitfield commented on scripts/HFIRPowderReduction/HfirPDReductionGUI.py
> +                intlist.extend(list(range(templist[0], templist[1]+1)))
Don't need list here either

2017-08-29 17:31 UTC, rosswhitfield commented on scripts/HFIRPowderReduction/MplFigureCanvas.py
> +        for ikey in list(self._lineDict.keys()):
and here

2017-08-29 17:47 UTC, rosswhitfield approved these changes

2017-08-29 20:25 UTC, rosswhitfield approved these changes

2017-08-29 20:25 UTC, rosswhitfield approved these changes

2017-08-29 20:25 UTC, rosswhitfield approved these changes

2017-08-29 21:46 UTC, merged