15414 sum spectra max index
mantidproject/mantid pull request #19830
Opened 2017-06-08 09:13 UTC by ThomasLohnert

Fixes #15414.

Fixed the one-off errors in SumSpectra's min/max index checks as described in the ticket, and added input validation for the max index and index list properties.

**To test:**
1. Create sample workspace
1. Run SumSpectra on it 
1. Try entering invalid values (i.e. negative, or greater than maximum spectrum index) for StartWorkspaceIndex, EndWorkspaceIndex or ListOfWorkspaceIndices properties
1. Confirm an error appears when trying to run the algorithm, and the tooltip for the invalid input is understandable
1. Confirm functionality of the algorithm is unchanged for valid inputs

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-20 07:01 UTC, soininen requested changes
Tested this as instructed. There are few issues with the code but overall these are nice improvements. This PR does fix an actual bug, so why not add a line to the release notes?

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +  if (indices_list.size() > 0) {
Please check `!indices_list.emtpy()` instead of comparison to `0`. It conveys the intention better.

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +    auto listMinIndex = this->m_indices.begin();
How about `m_indices->front()` and `m_indices->back()`? No need for the iterator stuff here. Also, please use `const auto`.

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +  int maxIndex = getProperty("EndWorkspaceIndex");
Can't this variable be declared `const`?

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +  if (maxIndex != EMPTY_INT() && maxIndex > m_numberOfSpectra) {
I believe you need to test here for `maxIndex >= m_numberOfSpectra`.

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +  if (m_minWsInd >= m_numberOfSpectra) {
How about testing *StartWorkspaceIndex* in `validateInputs` as well? You would need to ensure that `m_minWsInd < m_maxWsInd` and `m_minWsInd < m_numberOfSpectra`.

2017-06-20 07:01 UTC, soininen commented on Framework/Algorithms/src/SumSpectra.cpp
> +    if ((i >= this->m_numberOfSpectra) || (i < 0)) {
The `this->` thing is used inconsistently throughout this file anyhow. Personally, I'd remove them as my IDE color-codes member variables automatically but your mileage my vary...

2017-06-27 09:16 UTC, ThomasLohnert commented on Framework/Algorithms/src/SumSpectra.cpp
> +    if ((i >= this->m_numberOfSpectra) || (i < 0)) {
You're right, there really is not much point to using `this->` - while my IDE does not highlight it, the `m_` naming convention for member variables implies the same anyway. I have removed it throughout the file in the interest of consistency

2017-06-27 12:31 UTC, soininen approved these changes

2017-07-06 06:19 UTC, merged