Add input instrument approximation to MonteCarloAbsorption
mantidproject/mantid pull request #19842
Opened 2017-06-09 15:38 UTC by soininen

This PR extends [`MonteCarloAbsorption`](http://docs.mantidproject.org/nightly/algorithms/MonteCarloAbsorption-v1.html) by adding an option to approximate the instrument of the input workspace by a 'sparse' instrument. The sparse instrument consists of a grid of detectors spawning the opening angles of the full instrument thus enabling simulation with smaller number of detectors than in the full input instrument. The simulated absorption corrections are then interpolated to the full instrument in a two step process.

This PR shouldn't introduce changes to existing functionality.

**To test:**

Run the algorithm by enabling and disabling *SparseInstrument* to see if the results more-or-less match. If possible, check that when *SparseInstrument* is disabled, the results are unchanged compared to master.

Fixes #19757.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-30 08:22 UTC, gvardany requested changes
The new option is very useful indeed for speeding up the simulation for large instruments. Changes look fine in general, except few minor oversights inline. Probably the major thing is to move the new helper methods in `MonteCarloAbsorption.cpp` file to a `SparseWorkspaceCreation.cpp` or something, since they are too many. Also like this they can be tested in isolation. I will proceed to functional testing shortly.

2017-06-30 08:22 UTC, gvardany commented on Framework/Algorithms/src/InterpolationOption.cpp
> +void InterpolationOption::applyInPlace(const HistogramData::Histogram &in,
missing doxygen

2017-06-30 08:22 UTC, gvardany commented on Framework/Algorithms/src/SampleCorrections/DetectorGridDefinition.cpp
> +                   static_cast<double>(m_latitudePoints - 1);
what if `m_latitudePoints = 1`?

2017-06-30 08:22 UTC, gvardany commented on Framework/HistogramData/src/Interpolate.cpp
> +void sanityCheck(const Histogram &input, const Histogram &output) {
missing doxygen

2017-06-30 08:22 UTC, gvardany commented on Framework/HistogramData/src/Interpolate.cpp
> +template <typename XData, typename YData, typename XInterp, typename YInterp>
same here

2017-06-30 08:22 UTC, gvardany commented on Framework/HistogramData/src/Interpolate.cpp
> +void interpolateLinearInplace(const Histogram &input, Histogram &output) {
and here

2017-06-30 08:22 UTC, gvardany commented on Framework/HistogramData/src/Interpolate.cpp
> +void interpolateCSplineInplace(const Histogram &input, Histogram &output) {
here

2017-06-30 08:22 UTC, gvardany commented on Framework/Algorithms/src/MonteCarloAbsorption.cpp
> +  twoOrMore->setLower(2);
As we have tested once, I think it is better to set an odd default value (so 3) for the latitude points. Supposedly most of the instruments will be more or less symmetric around the equatorial, where with 2 points only one would simulate the upper and lower bands, and get a systematic shift after interpolating to the equator.

2017-06-30 08:22 UTC, gvardany commented on Framework/Algorithms/src/MonteCarloAbsorption.cpp
> + *  @param wavelengthPoints Number of points in the output workspace.
missing @throw

2017-06-30 08:51 UTC, gvardany commented on Framework/Algorithms/src/MonteCarloAbsorption.cpp
> +  const V3D samplePos{0.0, 0.0, 0.0};
One more comment, here you set sample at the centre, and then the source along the negative ray of z. 
I wonder if these should also be copied from the actual instrument?

2017-06-30 14:29 UTC, gvardany commented
Results look good as well. Obtained identical results with master in case of no approximation.

2017-07-04 08:24 UTC, soininen commented on Framework/Algorithms/src/SampleCorrections/DetectorGridDefinition.cpp
> +                   static_cast<double>(m_latitudePoints - 1);
In principle, the validators in `MonteCarloAbsorption::init()` prevent this, but I guess it doesn't hurt to be extra careful here.

2017-07-04 08:30 UTC, soininen commented on Framework/Algorithms/src/MonteCarloAbsorption.cpp
> +  twoOrMore->setLower(2);
Good point. The bound can be changed later to 2 if needed without breaking the API. I'll change the default to an odd number as well.

2017-07-04 09:30 UTC, soininen commented on Framework/Algorithms/src/MonteCarloAbsorption.cpp
> +  const V3D samplePos{0.0, 0.0, 0.0};
The original reference frame can be (and should be) taken into account, but I'd rather move the sparse instrument such that the sample position is in the origin as the beam profile stuff kind of expects it.

2017-07-19 09:09 UTC, gvardany approved these changes

2017-07-19 09:10 UTC, gvardany commented
Changes look good, the separated tests as well.

2017-07-20 06:27 UTC, martyngigg commented
Agreed. The images for the docs are very nice too.

2017-07-20 06:27 UTC, merged