Dev2017 flag and skip slow tests
mantidproject/mantid pull request #19910
Opened 2017-06-21 14:21 UTC by louisemccann

A function `excludeInPullRequests` has been added to the base class for system tests, allowing for especially slow or unnecessary tests to be skipped for every PR build and only run nightly. Tests will be excluded if this function returns true.

When calling `systemtest` from the command line, all tests will be run by default. A flag `--exclude-in-pull-requests` has been added to exclude any systems test with the above function returning true.

A few of the slowest system tests have been updated to be skipped, see https://docs.google.com/spreadsheets/d/1uzAhnFM9Q8jMmrOzaZ32oBx_SDIdojKUgps9-EXpslo/edit#gid=0

**To test:**

Run a system test of your choice. 
Add the function
```
def excludeInPullRequests(self):
    return True
```
to the class of your system test.

run `systemtest -R yourtest` and it should be run.

run `systemtest -R yourtest --exclude-in-pull-requests` and it should be skipped.

Fixes #19864

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-21 14:42 UTC, peterfpeterson requested changes
Code looks good other than a few small changes.

2017-06-21 14:42 UTC, peterfpeterson commented on Testing/SystemTests/lib/systemtests/stresstesting.py
> +    def __init__(self, test_dir, module_name, test_cls_name, exinpr):
This is a horrible variable name. How about `exclude_in_pr_builds` or `excludeInPullRequests`?

2017-06-21 14:42 UTC, peterfpeterson commented on Testing/SystemTests/lib/systemtests/stresstesting.py
> +def returnFalse():
This is a great case for using a [lambda function](http://www.diveintopython.net/power_of_introspection/lambda_functions.html).
```python
if {5}:
    systest.excludeInPullRequests = lambda : False
```

2017-06-21 15:02 UTC, peterfpeterson requested changes

2017-06-21 15:02 UTC, peterfpeterson commented on Testing/SystemTests/scripts/runSystemTests.py
> +parser.add_option("", "--exclude-in-pull-requests", dest="exinpr",action="store_true",
Better name here too

2017-06-21 15:02 UTC, peterfpeterson commented on Testing/SystemTests/scripts/runSystemTests.py
> +                                testsInclude=options.testsInclude, testsExclude=options.testsExclude, exinpr=options.exinpr)
Better name

2017-06-21 15:24 UTC, peterfpeterson approved these changes
This works as advertised. Once the builds pass it can be merged.

2017-06-22 06:59 UTC, martyngigg commented
Good stuff. I assume we need to add the flag to the `pull_requests-rhel7` configuration?

2017-06-22 07:01 UTC, merged

2017-06-22 12:44 UTC, peterfpeterson commented
The change to the build script is done in #19913