Improve FindPeaksMD
mantidproject/mantid pull request #19916
Opened 2017-06-22 14:38 UTC by AntonPiccardoSelg

Fixes #19914

**To test:**
TODO

**Release Notes** 
TODO

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-06-29 10:02 UTC, NickDraper requested changes
I think that having a combobox of peak finding (and normalization strategies) would make more sense than adding a Boolean option for this special case.

It is fairly likely that there will be more in the future.  Of course the current default should be the new default for the drop down list.

2017-07-19 12:50 UTC, AntonPiccardoSelg commented
@NickDraper The peak finding strategy has been changed to a combobox. 
Scientific validation is complete: Pascal seems to think that the results are better than previously ( but not great for all data sets, especially if they have weak peaks and strong backgrounds)

2017-07-26 11:03 UTC, ThomasLohnert requested changes
The changes are a big improvement, functionality looks good. Some nitpicking in the comments

2017-07-26 11:03 UTC, ThomasLohnert commented on docs/source/algorithms/FindPeaksMD-v1.rst
> +the events are weighted this will result in boxes with signal counts larger than one for peaks and for the majority of background counts this will 1. Hence it is possible to discrimiate between peaks
> and for the majority of background counts this will 1.

will _be_ 1?

2017-07-26 13:49 UTC, AntonPiccardoSelg commented on Framework/MDAlgorithms/src/FindPeaksMD.cpp
> +      double binCount = box->getSignalByNEvents() * m_densityScaleFactor;
Good spot :+1:. Using `getSignalNormalized` makes much more sense here. At this point in the code we have already found our peaks.

2017-07-26 15:31 UTC, ThomasLohnert approved these changes

2017-07-27 10:53 UTC, AntonPiccardoSelg commented
@NickDraper Your requested changes have been implemented.

2017-07-28 09:59 UTC, NickDraper approved these changes

2017-07-31 12:48 UTC, SimonHeybrock commented on docs/source/algorithms/FindPeaksMD-v1.rst
> +quanity the signal count (total weighted event sum divided by the number of events) is used. If
Typo `quanity`.

2017-07-31 12:48 UTC, SimonHeybrock commented on docs/source/algorithms/FindPeaksMD-v1.rst
> +the events are weighted this will result in boxes with signal counts larger than one for peaks and for the majority of background counts the signal count will be 1. Hence it is possible to discrimiat
Typo `discrimiate`

2017-08-02 07:00 UTC, merged