TF asymmetry and multiple fitting
mantidproject/mantid pull request #19935
Opened 2017-06-27 14:43 UTC by AnthonyLim23

The TF asymmetry fit has been added to the multiple fitting GUI in muon analysis. The user can now do a TF asymmetry fit in any mode. 

TF asymmetry mode allows the user to calculate a better normalization by fitting a function to the data. 

**To test:**

Add test instructions....

Fixes #19835 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-06 11:56 UTC, soininen commented
I tried to follow the instructions for testing, but got 'Fit Algorithm failed. Unknown property search object InputWorkspace_1' while doing the following:
1. Change facility to ISIS, default instrument to MUSR
2. Open the Muon Analysis interface
3. Click Manage Directiories and dd Mantid training course data to Data Search Directories
4. Browse... and open MUSR00015189.nxs from the training course data
5. Switch between the three options in Group/Group Pair combo box.
6. Go to Settings tab, make sure multiple fitting is disabled and TF Asymmetry enabled
7. Go to Data Analysis tab
8. There is thee options in Data/Workspace combo box. Switch between them and the number of options increases...
9. When you have all six options in the Data/Workspace combo box, add GausOsc fitting function
10. Fit. An error dialog with the aforementioned message appears

2017-07-06 12:03 UTC, soininen commented
Found another issue while trying Part 2 of the testing procedure:
1. Set facility to ISIS, instrument to MUSR
2. Open the Muon Analysis interface
3. Make sure Mantid training course data directory is in the Data Search Directories
4. Select MUSR00015189.nxs from the training course data
5. Go to Settings tab, make sure multiple fitting and TFAsymmetry are enabled
6. Go to Data Analysis tab, add CompositeFunction and GausOsc within the Composite function.
7. Observe MantidPlot catching an unexpected: 'Unknown function parameter A'

2017-07-06 12:13 UTC, AnthonyLim23 commented
I will look into these today. 

For the second error: "Unkown function parameter A", that should allow you to select continue and it will then be ok  (its bad wording of the warning message). See #19735.

The other issue sounds more serious. I will try to reproduce it. What were the extra groups/pairs that you added (complete with detector ID's)?

2017-07-06 14:20 UTC, AnthonyLim23 commented
@soininen I have had a look into this and I think that I understand the error. It have made an issue for it (#19975 ), as it already exists in the release version. 

The adding of workspaces as you choose groups in data analysis is because after you have selected a group it load both the first and second period of data. 

The error message occurs with TFAsymm turned off. However, it will only happens if multiple periods are available.

2017-07-07 10:17 UTC, soininen commented
Now I get a segmentation fault. Steps to reproduce:
1. Set Facility to ISIS, default instrument to MUSR
2. Open Muon Analysis
3. Check that the directory of the file in the next step is in Data Search Directories
4. Browse and open  MUSR00015189.nxs in Mantid training course data
5. Go to Settings tab, check 'Enable multiple fitting' and 'TF Asymmetry'
6. Go to Data Analysis tab, add GausOsc function
7. Fit
8. TF Asymmetry Fit. This will segfault.

2017-07-07 11:11 UTC, AnthonyLim23 commented
@soininen when you get the seg fault was there any text in the drop down box just below the table? If thats not clear I will send a picture to you. 

I have seen this happen if the data did not load correctly. So there was no data to fit

2017-07-07 12:20 UTC, soininen commented
I cannot say if there was no data to fit. This muon analysis and multifit stuff is quite an unexplored sea for me. Anyway, the interface looks like this just after step 6:
![muon-analysis-data-analysis](https://user-images.githubusercontent.com/19147159/27957029-b4a77520-631c-11e7-8fc5-affe79f4436c.png)
If there is something wrong with the MUSR dataset included in the Mantid training course dataset I'm using here, would it be possible to provide a more suitable input file to test this ticket?

2017-07-07 12:22 UTC, AnthonyLim23 commented
That should work. I will look into it. I am going to add an in progress label. I am also going to try and fix the fit being temperamental.

2017-07-11 11:47 UTC, AnthonyLim23 commented
I think that should work now. For the fitting with no shared parameters use a good starting guess (frequency of about 2 and an amplitude of 0.2) for all of the groups.

2017-08-01 12:50 UTC, dtasev requested changes

2017-08-03 09:34 UTC, dtasev requested changes
Just a minor spelling query, apart from that in the functional testing I found no problems and the results were as expected

2017-08-03 09:34 UTC, DTasev commented on MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Muon/MuonAnalysis.h
> +  void updateNormalisation(QString name);
You have mixed spelling of Normalisation, in some functions it's Normali**z**ation, this might confuse IDEs and developers

2017-08-03 12:47 UTC, dtasev approved these changes

2017-08-07 05:18 UTC, merged