Muon analysis Group/pair selection
mantidproject/mantid pull request #19953
Opened 2017-07-03 14:19 UTC by AnthonyLim23

In muon analysis the "all groups" selection in the multiple fitting did not select all of the groups when it initially loaded. Furthermore, the groups and pairs were found not to be passed correctly to the data analysis tab. This PR solves both problems. 

1. Load some data into muon analysis. Make sure that a group is plotted.
2. Go to the Grouping Options tab
3. Add a group (including the detector numbers) and some pairs. 
4. Go to the settings tab and make sure multiple fitting is selected. 
5. Go to the data analysis tab. The selected groups should include all of the groups (and the ones added from step 3). 
6. Change the selection in Groups/Pairs to fit to all pairs. It should list all of the pairs (including the ones added in 3). 
7. Go back to the Grouping Options tab and add another pair. 
8. In the data analysis tab the new pair should show up when all pairs is selected. 

Fixes #19938 

**Release Notes** 
Not in the release notes as it was not reported by a user. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-06 16:08 UTC, DavidFair requested changes

2017-07-06 16:08 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
Since we don't reuse `tmp` can we move the elements instead of copying them: [link](https://stackoverflow.com/a/10720242)

2017-07-06 16:08 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  for (auto name : names) {
`const auto &name` to avoid temporary copies

2017-07-06 16:08 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +    m_uiForm.fitBrowser->setAvailableGroups(GroupsAndPairsNames);
This block of code is duplicated from above - can we move it into a separate function and call it twice instead?

2017-07-07 08:16 UTC, AnthonyLim23 commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
changing it to 

```
auto names = m_groupingHelper.parseGroupingTable().pairNames;
	names.insert(std::end(names), std::make_move_iterator(m_groupingHelper.parseGroupingTable().groupNames.begin()), std::make_move_iterator(m_groupingHelper.parseGroupingTable().groupNames.end()));
	QStringList GroupsAndPairsNames;
```

causes an error. I think we do want a copy, as the group names should still contain the names.

2017-07-07 08:28 UTC, AnthonyLim23 commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
I have added a tmp to store the vector in, this stops it from crashing

2017-07-07 09:00 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
I was thinking of something along the lines of:
``` c++
auto tmp = m_groupingHelper.parseGroupingTable().groupNames;
auto names = ....;
names.insert(std::end(names), std::make_move_iterator(tmp.begin()), std::make_move_iterator(tmp.end()));
```

2017-07-07 09:01 UTC, DavidFair commented on MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp
> +  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
Oh you've already done it - sigh Github....

2017-07-07 09:08 UTC, DavidFair commented
Noticed a bug during testing:
Select `All Groups` under data analysis
Go to grouping options add a new group
Go back to data analysis
Notice how `All Pairs` is now selected instead of `All Groups`

2017-07-07 09:10 UTC, AnthonyLim23 commented
Thats a feature. I have assumed that adding a group or pair does not mean that a user wants to change the selection in the fitting

2017-07-07 09:11 UTC, DavidFair commented
Yes but thats the problem - it is changing the selection in the fitting window

2017-07-11 13:09 UTC, DavidFair commented
We have determined the pair / group selection changing is an existing issue not related to the changes in this PR. Issue #19986 has been created and I'm happy to :shipit: this.

2017-07-11 13:09 UTC, DavidFair approved these changes

2017-07-18 09:43 UTC, merged