OS X support for high DPI screens
mantidproject/mantid pull request #19974
Opened 2017-07-06 13:01 UTC by gvardany

MantidPlot showed up blur on 4K screens with OS X. This fixes the scaling.

**To test:**
You have to be on 4K screen with OS X.

Install OS X packages built with and without this change. 
Open MantidPlot and compare the graphics and especially the texts.
Optionally go through several interfaces/viewers and see if there is nothing dramatically off.

No issue.

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-28 07:09 UTC, gvardany commented
@quantumsteve Did you manage to have a look into this?

2017-09-07 20:34 UTC, quantumsteve requested changes
Last year @martyngigg and I looked into enabling this on OS X and Windows. Just enabling the flags generates very small icons in menus (see below). [Qt 5](http://doc.qt.io/qt-5/highdpi.html) has more options for High DPI displays, but modifying MantidPlot is a much larger task than shown here. 
![image](https://user-images.githubusercontent.com/5920552/30183751-8fbe84e4-93e9-11e7-8688-b1a0ae89a8bc.png)

I'd recommend we instead enable high DPI display support in the new workbench on day 1 and focus our efforts there.

2017-09-08 07:52 UTC, gvardany commented
True that the icons are tiny, but I think especially mac users would generally prefer small and sharp over large and fuzzy. Moreover, without the flag, also the texts and the plots are fuzzy, which are lot more important to get sharp. So somehow I thought getting just the icons small is a good compromise, and more preferable until we do it properly. I would agree to put this off for the moment but aiming to enable it for the new workbench from the very beginning should be considered.

2017-09-08 15:35 UTC, quantumsteve commented
@martyngigg pointed out that Mantid is explicitly set to be DPI unaware on Windows (see https://github.com/mantidproject/mantid/pull/19081), which is identical to the current behavior on MacOS. I'm sympathetic to your desire for Retina support, but this half-solution will disappoint many users, such as those with poorer eye sight that need larger icons. Doing so properly requires at least Qt5, new icons, and more exhaustive testing and refinement. Let's leave Retina support as a benefit of the new workbench.

Does this PR change the *saved* figures or just the MantidPlot window? 

The `Info.plist` may be edited after Mantid is installed and I don't see harm if you want to document this change for motivated users.

2017-09-13 06:49 UTC, gvardany commented
I have probably missed #19081. I am not actually sure about the saved figures, I have not tested it.
If it is possible to patch the file after installation, I agree that could be a good compromise.
So where do you suggest to document it? in wiki?

2017-09-13 21:21 UTC, quantumsteve commented
The wiki is fine, though not terribly visible and hard to keep updated. I think you'd be better off putting it in the sphinx documentation and adding a link in the release notes.

2017-09-14 14:32 UTC, gvardany commented
I just tried to amend the .plist after installation and it did not work. This should be done before installation, but the issue there is that the .dmg is mounted read-only, so it did not allow me to modify the package content before installation. Any idea one could make and checkbox in the installation step to ask for the preference or something like that?

2017-09-14 14:38 UTC, gvardany commented
Also it is as blurry in the saved plot, as it is inside MantidPlot.

2017-09-14 20:46 UTC, quantumsteve commented
I'd suggest doublechecking your changes to the Info.plist. I tested this PR by updating it after installing nightly and made the figure above.

I haven't tried making an install option like you describe above and suspect it won't be trivial. Given the small number of people we expect will make this change, I'd recommend focusing your efforts elsewhere.

2017-09-17 12:13 UTC, gvardany commented
You are absolutely right, this problem affects probably <1% of the users. I see what I can do for my client setup, and we can put this off until it is more relevant.

2017-09-17 12:13 UTC, closed without merging