Inconsistent use of number density
mantidproject/mantid pull request #19978
Opened 2017-07-07 11:21 UTC by ianbush

The main change is to ensure `MaterialBuilder` uses atoms per cubic Angstrom for the number density, instead of formula units per cubic Angstrom.

There are some documentation changes to ensure that it is clear that `atoms / Angstrom^3` are used for number density and not anything else.

**To test:**

Check unit tests pass. Is there anywhere else the documentation should be clarified? Is there any knock-on effect on user scripts we should worry about, or is this just a bug fix?

Fixes #19962

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-08 21:06 UTC, AndreiSavici commented
Did we decide atoms/volume or formula units/volume? I don't recall a final answer on this

2017-07-10 06:33 UTC, ianbush commented
I went for atoms / volume as it was the original intention in `Material`. Switching to formula units / volume I think would be a bigger breaking change.

2017-07-10 08:21 UTC, martyngigg commented on Framework/Kernel/src/MaterialBuilder.cpp
> +    return (m_massDensity.get() * totalNumAtoms / rmm) *
:+1:

2017-07-10 09:58 UTC, martyngigg commented on Framework/PythonInterface/test/python/plugins/algorithms/IndirectTransmissionTest.py
>          # mass density 1.0 = number density 0.033424 for water
The comment and code here are now inconsistent. I would suggest getting rid of the comment, it doesn't seem that useful.

2017-07-10 10:18 UTC, martyngigg commented
Code-wise I think this is fine now. `MassDensity` was introduced much more recently so we may be saved that most scripts are still using `NumberDensity` as input and shouldn't need to change.

On the documentation side is it worth updating `SetSampleMaterial` with an explicit calculation of how the number density is derived from the mass density?

2017-07-10 15:21 UTC, ianbush commented
@martyngigg A good point, I have added the mass density calculation to `SetSampleMaterial`.

2017-07-10 15:56 UTC, SpencerHowells commented
Let's get this straight! I have been calculating absorption for 45 years! The equation contains the product of number density & cross-section so these 2 variables MUST be consistent. In the amorphous/liquid community we have used number density in atoms/volume so the cross-sections are average per atom. I don't mind which we use provided SetSampleMatrial is consistent.

2017-07-10 16:03 UTC, SpencerHowells commented
Regarding the Indirect routines I decided to give users the option of inputting Mass Density so that they don't need to calculate the number density and risk having it in the wrong units. This has happened often in the past.

2017-07-13 16:04 UTC, ianbush commented
I have pushed some extra changes to hopefully improve the validation in `MaterialBuilder`, meaning a number density should always be set, or an error thrown.

2017-07-18 11:42 UTC, ianbush commented
@martyngigg @peterfpeterson This should be ready for review now.

2017-07-20 06:49 UTC, martyngigg requested changes
I think this is nearly there - I just have a few comments.

2017-07-20 06:49 UTC, martyngigg commented on Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
>              mat = builder.setFormula(chemical_formula).setMassDensity(density).build()
I think we can simplify this a bit now can't we? The `builder` variable is no longer needed as the number density will be calculated on the fly? So basically the `if` just needs 1 line each for whether the property is `SampleMassDensity` or `SampleNumberDensity`?

2017-07-20 06:49 UTC, martyngigg commented on Framework/PythonInterface/plugins/algorithms/IndirectTransmission.py
> +        SetSampleMaterial(InputWorkspace=workspace, ChemicalFormula=formula, SampleNumberDensity=density)
Should we do something similar here and get rid of the `MaterialBuilder` in here too and just switch on the property name? This also avoids doing the calculation twice?

2017-07-20 06:49 UTC, martyngigg commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/FlatPlatePaalmanPingsCorrection.py
> +            set_material_alg.setProperty('SampleNumberDensity', density)
Same comment as for `CylinderPaalmanPingsCorrection` above.

2017-07-20 06:49 UTC, martyngigg commented on Framework/PythonInterface/test/python/plugins/algorithms/CalculateSampleTransmissionTest.py
> +        density = 0.100272
What's the reason for changing the value here? Should this test case not stay the same?

2017-07-20 06:49 UTC, martyngigg commented on Framework/PythonInterface/test/python/plugins/algorithms/IndirectTransmissionTest.py
> +        density = 0.100272
Same question here. I don't quite understand if we are still using the `Number Density` below why that needs to change as the `MaterialBuilder` was only corrected for the mass density setting wasn't it?

2017-07-20 08:54 UTC, ianbush commented on Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
>              mat = builder.setFormula(chemical_formula).setMassDensity(density).build()
I agree `builder` is no longer required, but I think the extra lines are still needed as the algo returns the number density.

2017-07-20 09:09 UTC, ianbush commented on Framework/PythonInterface/test/python/plugins/algorithms/CalculateSampleTransmissionTest.py
> +        density = 0.100272
The docs for the algorithm say that number density is in `Atoms / Angstrom^3`, so `1 g /cc` (standard water density) in `test_mass_density` should correspond to `0.100272 Atoms / Angstrom^3` (`3 x 0.033424 molecules / Angstrom^3`) here.

I think the point of this test was to show that mass density and number density, at standard density, give the same results. Hence why I thought changing this made more sense than changing the mass density.

2017-07-20 09:10 UTC, ianbush commented on Framework/PythonInterface/test/python/plugins/algorithms/IndirectTransmissionTest.py
> +        density = 0.100272
Same answer as above.

2017-07-20 09:11 UTC, ianbush commented on Framework/PythonInterface/test/python/plugins/algorithms/CalculateSampleTransmissionTest.py
> +        density = 0.100272
As an additional point when Miguel was testing this these were the numbers he used. I assume this is be cause `0.1 mm` of water at `1 g/cc` is a number most instrument scientists will know.

2017-07-20 09:18 UTC, ianbush commented on Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
>              mat = builder.setFormula(chemical_formula).setMassDensity(density).build()
Ah, perhaps it is better to do `density = ws.experimentInfo().sample().getMaterial().numberDensity`? This should ensure the calculation is done once.

2017-07-20 15:28 UTC, martyngigg commented on Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
>              mat = builder.setFormula(chemical_formula).setMassDensity(density).build()
Good point. Yes I think your option is the best way forward now.

2017-07-20 15:29 UTC, martyngigg commented on Framework/PythonInterface/test/python/plugins/algorithms/CalculateSampleTransmissionTest.py
> +        density = 0.100272
Fair point, that does make sense.

2017-07-20 15:29 UTC, martyngigg approved these changes

2017-07-20 15:29 UTC, martyngigg commented
I'm happy with these changes now. @peterfpeterson @louisemccann Please provide any comments if you have any.

2017-07-20 15:40 UTC, louisemccann approved these changes
See comment about the error message. Aside from that looks good to me

2017-07-20 15:40 UTC, louisemccann commented on Framework/Kernel/src/MaterialBuilder.cpp
> +                             "cell volume or mass density.");
Should this be `The number density couldn't be determined`?

2017-07-20 15:43 UTC, ianbush commented on Framework/Kernel/src/MaterialBuilder.cpp
> +                             "cell volume or mass density.");
:+1: Whoops, good spot!

2017-08-03 19:22 UTC, peterfpeterson approved these changes
I think everything has been sorted out and is consistent.

2017-08-04 07:52 UTC, merged