InfoComponentVisitor makes DetectorInfo and ComponentInfo
mantidproject/mantid pull request #20010
Opened 2017-07-14 16:19 UTC by OwenArnold

Fixes #20002. Make `ComponentInfo` and `DetectorInfo` via visitor double dispatch mechanism.

WIP

Check key performance areas such as `CalibrateSXDPanels` and common Load/Save algorithms. Should be at least as good as base branch `instrument_2_0_1` 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-31 08:26 UTC, SimonHeybrock requested changes
Looks pretty good already. My main comment is regarding the copy/ownership mechanism in `Beamline::Beamline` that you already mentioned on Skype. I do not really understand the mechanism. It seems to be made for handling cases where one of `ComponentInfo` and `DetectorInfo` can be `nullptr`? What is that used for?

2017-07-31 08:26 UTC, SimonHeybrock commented on Framework/Beamline/inc/MantidBeamline/Beamline.h
> +class MANTID_BEAMLINE_DLL Beamline {
I think we will be running into trouble with this name -- there will be clashes with the namespace of the same name (I had this issue with `Histogram`, this is why the module is names `HistogramData`.

2017-07-31 08:26 UTC, SimonHeybrock commented on Framework/Beamline/inc/MantidBeamline/Beamline.h
> +  boost::shared_ptr<DetectorInfo> m_detectorInfo;
Why do we need to store these as `shared_ptr`? The data inside `ComponentInfo` and `DetectorInfo` is shared, so it is not clear why we would want another level of sharing.

2017-07-31 08:26 UTC, SimonHeybrock commented on Framework/Geometry/inc/MantidGeometry/Instrument.h
> +#include "MantidBeamline/Beamline.h"
Consider avoiding this include and instead use a forward declaration (and store `Beamline` as `unique_ptr`).

2017-07-31 08:26 UTC, SimonHeybrock commented on Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h
> +#include "MantidBeamline/Beamline.h"
Maybe also avoid this include?

2017-07-31 08:26 UTC, SimonHeybrock commented on Framework/Geometry/src/Instrument.cpp
> +  auto componentCache = m_instrVisitor->componentIds();
`auto &`?

2017-07-31 12:23 UTC, OwenArnold commented on Framework/Beamline/inc/MantidBeamline/Beamline.h
> +class MANTID_BEAMLINE_DLL Beamline {
There was a previous chat on the general slack thread, and I think Duc suggested "Beamline" a name. Instrument 2.0 doesn't seem to cut, it and `Instrument` is too easily confused with existing `Instrument 1.0` IMHO. I do agree that `Beamline` itself might not be descriptive enough. Open for suggestions... maybe

* `Geometry`  - as in `Beamline::Geometry`, too easily confused with namespace `Geometry`?
* `BeamlineInstrument`?

2017-07-31 12:25 UTC, OwenArnold commented on Framework/Beamline/inc/MantidBeamline/Beamline.h
> +  boost::shared_ptr<DetectorInfo> m_detectorInfo;
I had to change it from a `unique_ptr` to this. I think i'm going to write down the various object/ownership issues I encountered. I did add a regression tests for each of these as I came across and fixed these. I think some of your questions will relate to these so I'll write it properly once.

2017-07-31 12:26 UTC, OwenArnold commented on Framework/Geometry/inc/MantidGeometry/Instrument.h
> +#include "MantidBeamline/Beamline.h"
Considered that, and sat of the fence for a while - eventually decided that ownership and copying semantics issues were complex enough that I wanted to shield from the client. will define further below.

2017-07-31 12:29 UTC, SimonHeybrock commented on Framework/Beamline/inc/MantidBeamline/Beamline.h
> +class MANTID_BEAMLINE_DLL Beamline {
The discussion in slack was when I looked for a module name, and indeed I then used Duc's suggestion `Beamline`.

- `Geometry` has nothing to do with neutron instruments.
- `BeamlineInstrument` does not make a lot of sense?
- `Instrument` does not seem too bad for me. The existing `Geometry::Instrument` is being removed after all.

Personally I would, I think, also prefer `Beamline::Beamline`, but I think that implies that we can never use `using namespace Beamline`? Is that an issue?

2017-07-31 12:51 UTC, OwenArnold commented on Framework/Geometry/src/Instrument.cpp
> +  auto componentCache = m_instrVisitor->componentIds();
👍

2017-07-31 12:51 UTC, OwenArnold commented
1. **Deep Copy**

Ensuring correct COW of held requires invoking the copy constructor of DetectorInfo and ComponentInfo. For example, when an `ExperimentInfo` is copied, if the COW ptr holding the vector of positions is not reference count incremented, then modifying positions of the first `Workspace`/`ExperiementInfo` will result in positions on the second incorrectly being changed.

```cpp
ExperimentInfo a;
...
ExperimentInfo b = a; // Deep copy in beamline required here!
a.beamline().detectorInfo().setPosition(V3D{1,1,1}); // Otherwise sharing in b not broken.
```

Current solution: Copy constructors of held pointers (`DetectorInfo` and `ComponentInfo`) in `Beamline` must be invoked on a `Beamline` copy

2. **Shallow Copy**

The original design had `ExperimentInfo` as the owner of `Beamline`. References loaned out to `ParameterMap` as part of `ExperimentInfo::setInstrument`. However, th there are cases where the Instrument is used after the ExperimentInfo has goine out of scope. While we do NOT want a deep copy, we need to ensure that the ParameterMap can have shared ownership of the beamline. See https://github.com/mantidproject/mantid/blob/8c85f9a168ef352e6dc9cbebdb03cc58fee69b15/Framework/API/test/ExperimentInfoTest.h#L974-L999

Current solution: `Beamline` provides an `alias` member function which calls a private constructor, which copies the held pointers but elides their copy constructors. Ownership of member pointers is shared so that use cases such as: `ParameterMap` can remain valid after creating `ExperimentInfo` goes out of scope.

3. **Move construction and assignment**

For convenience we might want to move an existing named beamline object, or reuse a temporary. 

Current solution: A default move constructor and move assignment operator are declared on `Beamline`.

2017-10-09 06:07 UTC, SimonHeybrock commented
I think this has been dealt with in another PR, closing?

2017-10-09 06:07 UTC, closed without merging