SplineInterpolation to support linear
mantidproject/mantid pull request #20028
Opened 2017-07-18 11:56 UTC by gvardany

This PR extends the `SplineInterpolation` algorithm to support linear interpolation if only 2 points are present in the input. 

**To test:**
```
iws = CreateSampleWorkspace(NumBanks = 1, XMin = 7, XMax = 29, BinWidth = 11)
mws = CreateSampleWorkspace(NumBanks = 1, XMin = 6, XMax = 30, BinWidth = 3)

ows = SplineInterpolation(WorkspaceToMatch = mws, WorkspaceToInterpolate = iws, Linear2Points = True, DerivOrder = 0)
```

Then overlay the 1st spectrum of the `iws`, `mws` and `ows`.  Disable normalisation by bin width in the plot. Inside the interpolation region the points should be on the line, outside, they should be equal to the last point of `iws`.

Fixes #18097. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-09 13:30 UTC, AntonPiccardoSelg requested changes
Looks good. There are just a few very minor points to look at.

2017-08-09 13:30 UTC, AntonPiccardoSelg commented on Framework/CurveFitting/src/Algorithms/SplineInterpolation.cpp
> +      << " to " << lastIndex << "\n";
You can avoid `stringstream` by using [`std::to_string`](http://en.cppreference.com/w/cpp/string/basic_string/to_string)

2017-08-28 09:04 UTC, gvardany commented on Framework/CurveFitting/src/Algorithms/SplineInterpolation.cpp
> +      for (size_t j = 0; j < order; ++j) {
The thing is that setValue wants the first argument as size, and the second as int, so it will not help.

2017-08-28 09:05 UTC, gvardany commented on Framework/CurveFitting/src/Algorithms/SplineInterpolation.cpp
> +SplineInterpolation::convertBinnedData(MatrixWorkspace_sptr workspace) {
Now I use `createChildAlgorithm` inside, which is not const.

2017-08-28 09:07 UTC, gvardany commented
I have addressed your comments, please have another look.

2017-08-29 07:39 UTC, gvardany commented on Framework/CurveFitting/src/Algorithms/SplineInterpolation.cpp
> +  const int derivOrder = getProperty("DerivOrder");
Apparently not, I tried but execution fails like that.

2017-08-30 08:25 UTC, AntonPiccardoSelg approved these changes

2017-08-31 08:06 UTC, merged