Absorption Corrections - Add SimpleShapeMonteCarloAbsorption
mantidproject/mantid pull request #20050
Opened 2017-07-19 16:08 UTC by louisemccann

Adds a new algorithm that calls MonteCarloAbsorption.

The MonteCarloAbsorption algorithm has several inputs which must be set before the algorithm can be run. This includes setting the beam geometry, sample geometry, and sample material. This algorithm sets these inputs for 3 different sample geometries:
Flat Plate
Cylinder
Annulus
The algorithm has been written in such a way that it should be easy to add additional shapes.
The algorithm can only run with data that has its x-axis units in wavelength.

**To test:**

Create a workspace eg
``` python
ws=CreateSampleWorkspace(Function="Quasielastic",
                         XUnit="Wavelength",
                         XMin=-0.5,
                         XMax=0.5,
                         BinWidth=0.01)
```
Run `SimpleShapeMonteCarloAbsorption`
Try with differnent shapes and options.
Use Chemical Formals: `H2-O` and mass density `1.0`

Fixes #19907. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-21 11:44 UTC, gvardany requested changes
The new wrapper does what it is supposed to. Only minor comments about clarifications of the units of the inputs and the tests (see inline).

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Height of the sample environment')
in `cm`?

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Width of the FlatPlate sample environment')
`cm`

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Thickness of the FlatPlate sample environment')
`cm`

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +        self.setPropertySettings('Center', flatPlateCondition)
`cm`?

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Angle of the FlatPlate sample environment')
degree? Also would be nice to be more specific about the definition of the angle. Is it with respect to the beam or beam normal? Clockwise or anti-clockwise? `-PI` to `PI`, or `0` to `2PI` ?

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Radius of the Cylinder sample environment')
cm

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Outer radius of the Annulus sample environment')
cm

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Inner radius of the Annulus sample environment')
cm

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +from mantid.api import *
you don't need the full api and kernel, I would prefer to be specific here

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorption.py
> +                             doc='Angle of the FlatPlate sample environment')
One could also have a float bounded validator for the angle

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py
> +        num_hists = corr_ws.getNumberHistograms()
I would assert on the block size as well

2017-07-21 11:44 UTC, gvardany commented on Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py
> +        red_ws = Load('irs26176_graphite002_red.nxs')
Should we have one more test with ILL reduced data? Just to make sure everything is and stays consistent.

2017-07-21 12:25 UTC, gvardany commented
One more thing I forgot to mention, the `MonteCarloAbsorption` now has an option to approximate the instrument. I was wondering if these properties should also be propagated? This might be needed for some of our direct geometry instruments, but from the other hand the new algorithm you have added is targeted only on indirect ones.

2017-07-21 12:42 UTC, gvardany commented on docs/source/algorithms/SimpleShapeMonteCarloAbsorption-v1.rst
> +* Flat Plate
This did not look right, maybe use `-` instead of `*`

2017-07-21 12:46 UTC, SpencerHowells commented
@gvardany we are now doing a Calculate.... algo to do sample & container from non-wavelength input ws. It converts to wavelength for calculating the corrections & then converts back to the input x-unit. I also have a scheme for Elastic S(Q,0) input. The output ws is in the Paalman-Pings format & will be used in the Apply... algo.

2017-07-21 15:51 UTC, louisemccann commented
@gvardany It's meant to be a general algorithm rather than a specific indirect one, so long is as the workspace is in units of wavelength this algorithm should work. If it will definitely be used for direct I will put in the instrument interpolation options

2017-07-26 11:22 UTC, gvardany commented
Regarding the instrument approximation in MC, I am not sure if they will be definitely needed. So I think  we can ship this as is, and then later if the need arises, we can add the 3 pass-through properties as well.

2017-07-26 11:22 UTC, gvardany approved these changes

2017-08-02 07:05 UTC, merged