Indirect - Use supplied drange when it is manually overridden
mantidproject/mantid pull request #20066
Opened 2017-07-21 14:26 UTC by brandonhewer

When the default d-range is overridden in the OSIRISDiffractionReduction algorithm, it had not impact on the used d-range, which continued to be the default.

Fixed this by passing the given d-range as an argument in the relevant function calls.

**To test:**
1. Navigate to `Interfaces > Indirect > Diffraction`.
2. Ensure `OSIRIS` is selected in the Instrument drop-down menu.
3. Ensure `diffonly` is selected in the Reflection drop-down menu.
4. Enter `119977` into the run number field.
5. Ensure the Use Container checkbox is checked and enter `71987` into the field.
6. Supply a calibration file in the cal file field (calibration file included below).
7. Enter `119963` into the vanadium runs field.
8. Ensure the Manul dRange checkbox is checked and use the spinner to select a range.
9. Run the algorithm and check the *_dRange file, ensuring the entered d-range was used.

Fixes #18858. 

**Release Notes** 

Added change to the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-15 16:32 UTC, louisemccann requested changes

2017-08-15 16:32 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
> +    return [RebinToWorkspace(
Could you change this to a for loop? Also maybe change Rebin to a child algorith.

2017-08-15 16:32 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
> +        self.declareProperty('DRange', defaultValue="", doc='Dranges to use when DetectDRange is disabled')
update the doc string to describe what kind of input you need, ie a list of numbers

2017-08-15 16:37 UTC, louisemccann commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
> +    temperatures = map(lambda index: mtd[ws_list[index]], range(1, num_workspaces))
List comprehension

2017-08-15 16:46 UTC, louisemccann commented
could you also add the drange used to the sample logs

2017-09-12 16:36 UTC, NickDraper requested changes
Code is fine, but it doesn't come out with data in the d-rage specified (I used 2-6).

We need to understand this better.

2017-09-13 16:02 UTC, brandonhewer commented
@NickDraper 
These numbers correspond to the Standard Diffraction Settings for drange on OSIRIS as laid out in the manual. Not sure how much this clears up:
https://www.isis.stfc.ac.uk/Pages/osiris-user-guide.pdf

2017-09-14 08:51 UTC, NickDraper commented
Can you add that as a tooltip on the input text box

2017-09-14 09:17 UTC, brandonhewer commented
@NickDraper Yes, I'll add that now.

2017-09-14 10:19 UTC, brandonhewer commented
@NickDraper Note that there are changes to files which aren't specifically related to this PR -> these are ClangFormat changes.

2017-09-14 13:24 UTC, NickDraper approved these changes

2017-09-14 13:25 UTC, NickDraper commented
Good to go once the build servers are happy

2017-09-15 07:13 UTC, merged