Remove ILL indirect deprecated code
mantidproject/mantid pull request #20085
Opened 2017-07-25 09:29 UTC by gvardany

This PR removes the old version of the loader, 2 deprecated algorithms, and one GUI tab for indirect ILL.

**To test:**
1. Set at ISIS, go to `Interfaces>Indirect>Data Reduction`
2. You should see 7 tabs, from which first 3 specific to ISIS
3. Set at ILL, go to `Interfaces>Indirect>Data Reduction`
4. Now you should see 5 tabs, only first of which specific to ILL (Energy Transfer).
5. [Optional] If you are familiar with Indirect, check if there is something else that needs to be removed and I missed?

Fixes #20083 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-18 12:48 UTC, KarlPalmen commented
You need to merge master into your branch and resolve the conflicts.

To ensure it, builds properly, you may need to follow the advice recently given by @martyngigg .

2017-08-18 12:49 UTC, KarlPalmen requested changes

2017-08-18 12:49 UTC, KarlPalmen commented on MantidQt/CustomInterfaces/CMakeLists.txt
> +        src/Indirect/Elwin.cpp
indented?

2017-08-28 08:13 UTC, gvardany commented
I have merged the master and solved the conflicts, can you please have another look?

2017-08-31 09:15 UTC, KarlPalmen commented
Another conflict needs resolving in the ``ui.rst`` file.

2017-08-31 14:41 UTC, KarlPalmen approved these changes

2017-08-31 18:46 UTC, merged