Refactor and add ALT format to SaveGSS
mantidproject/mantid pull request #20100
Opened 2017-07-26 10:45 UTC by DavidFair

Description of work.
As part of discussions with ENGINX we have been asked to implement the GSAS ALT format. This allows them to continue using existing Python scripts for analysis of textured banks whilst migrating over to using Mantid.

This PR:
- Updates the unit tests for `SaveGSS` to use the `FileComparisonHelper` - that way we check the entire file instead of just looking at snippets (as GSAS can be white space sensitive)
- Refactors the existing code :- TODO
- Adds the option to select ALT format in addition to FXYE when using RALF headers

**To test:**

TODO

Fixes #19413 

**Release Notes** 
TODO

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-07-27 09:23 UTC, dtasev requested changes

2017-07-27 09:23 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +  if (format.compare(SLOG) == 0) {
Isn't this the same as to `format != SLOG` or `!format.compare(SLOG)`?

2017-07-27 09:23 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +      if (algo->name().compare("NormaliseByCurrent") == 0)
Same comment as above

> Isn't this the same as to format != SLOG or !format.compare(SLOG)?

2017-07-27 09:23 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +    // None time series
Might be a typo, was `No time series` intended?

2017-07-27 09:23 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +void SaveGSS::validateUserInput() const {
Function is not used anywhere, consider removing if it's not going to be used.

2017-07-27 09:23 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +  const int nHist = static_cast<int>(m_inputWS->getNumberHistograms());
clang-tidy warning: `Use auto when initializing with a cast to avoid duplicating the type name`

2017-07-27 09:24 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +  for (const auto &filename : m_outFileNames) {
clang-tidy warning: `Local variable 'filename' hides previous declaration in the upper scope`

2017-07-27 09:42 UTC, dtasev requested changes

2017-07-27 09:42 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +          static_cast<int>(fixErrorValue(eVals[dataPosition] * 1000));
Same as the other clang-tidy warning about `const auto`

2017-07-27 09:42 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +    if (allValid == false) {
`!allValid` ?

2017-07-27 09:42 UTC, DTasev commented on Framework/DataHandling/src/SaveGSS.cpp
> +  if (value <= 0. || !std::isfinite(value))
No brackets, and the `else` is unnecessary because we are returning

2017-07-27 09:49 UTC, DTasev commented on Framework/DataHandling/inc/MantidDataHandling/SaveGSS.h
> +#include "MantidAPI/SpectrumInfo.h"
Imports below are unused 
```
#include "MantidAPI/Run.h"
#include "MantidAPI/SpectrumInfo.h"

#include "MantidHistogramData/Histogram.h"
#include <cmath>
```

2017-07-27 09:54 UTC, DavidFair commented on Framework/DataHandling/src/SaveGSS.cpp
> +  if (format.compare(SLOG) == 0) {
https://stackoverflow.com/a/9158971
Huh yep - I guess I misread that we should use `compare` instead of `==`

2017-07-27 14:05 UTC, DavidFair commented on Framework/DataHandling/src/SaveGSS.cpp
> +  for (int64_t fileIndex = 0; fileIndex < static_cast<int64_t>(numOutFiles);
PARALLEL_FOR only works with signed integer types i.e. `int64_t`

2017-07-27 14:09 UTC, DavidFair commented on Framework/DataHandling/src/SaveGSS.cpp
> +  outLines.resize(numberOfOutLines);
This is due to a limitation with PARALLEL - see above

2017-08-02 13:17 UTC, DavidFair commented on Framework/DataHandling/src/SaveGSS.cpp
> +void SaveGSS::validateUserInput() const {
I had called the base class `ValidateInputs` rather than this function - good catch

2017-08-08 10:12 UTC, DTasev commented on Framework/DataHandling/test/SaveGSSTest.h
> +    alg->setProperty("Data Format", "ALT");
`SaveGSS(v1) property (Data Format) violates conventions` according to RHEL7, might be worth updating the wiki at https://www.mantidproject.org/Mantid_Standards#Properties to mention that spaces in the name are not allowed

2017-08-09 08:50 UTC, dtasev requested changes
Just a question, changes look good and function correctly, unit tests are present and pass. 

There's also a TODO on the release notes that needs to be finished

2017-08-10 07:52 UTC, dtasev approved these changes

2017-08-10 07:53 UTC, DTasev commented
There's a merge conflict in the release notes, after that is done I think it's ready to be merged

2017-08-11 07:06 UTC, martyngigg commented
@DavidFair The branch has developed some merge conflicts.

2017-08-11 14:38 UTC, DavidFair commented
@martyngigg Thanks, the merge conflicts were Pete fixing up some incorrect string concatenation which I had also previously tidied during the refactor. Because of this there won't be any code changes following the merge.

2017-08-16 08:20 UTC, martyngigg commented on Framework/TestHelpers/inc/MantidTestHelpers/FileComparisonHelper.h
> +#include <iterator>
As there were no other changes in this file is it necessary to add this to the header?

2017-08-16 09:50 UTC, DavidFair commented on Framework/TestHelpers/inc/MantidTestHelpers/FileComparisonHelper.h
> +#include <iterator>
Yes, it uses `std::istreambuf_iterator` so it should have originally been included.

I'll also fix the merge conflict with release notes again

2017-08-16 10:37 UTC, martyngigg commented
@peterfpeterson @wdzhou Will the fact that `SaveGSS` now doesn't append `-0` in the `SplitFiles=False` case cause any problems?

2017-08-17 15:48 UTC, peterfpeterson commented
@martyngigg This does not appear to be the case. I just tried it out and the filenames (for `SplitFiles=False`) are unchanged.

2017-08-17 16:13 UTC, merged