Indirect - Corrections - Add Plot Current Preview
mantidproject/mantid pull request #20134
Opened 2017-08-01 11:12 UTC by brandonhewer

Currently in the Indirect Corrections interface, the ContainerSubtraction and ApplyPaalmanPings tabs do not have the functionality for plotting the current preview (mini-plot).

Added functionality for plotting current preview in the ContainerSubtraction and ApplyPaalmanPings interfaces.

**To test:**
1. Navigate to Interfaces > Indirect > Corrections.
2. To test each of the interfaces:
    1. 

Fixes #19094. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-03 09:45 UTC, mantid-roman requested changes
There is a small bug:
1. Add the sample.
2. Change spectrum with the spinner.
3. Add container. Now the preview shows sample's n-th spectrum and 1st containers's spectrum.
4. 'Plot Current Preview' plots the n-th spectra form both workspaces which is not what we see in the preview.

2017-08-03 13:22 UTC, brandonhewer commented
@mantid-roman This appears to be an issue with the preview (first spectrum of container is always loaded - regardless of what is in the 'Spectrum' field. Changing this to plot the n-th spectrum of the container when it is first loaded is a simple change, however, this brings up the issue of a container file which has a different number of spectrum than the sample file. In this scenario, a value may be entered in the 'Spectrum' field, which is out of range in the container file - of course this is invalid input and the Subtraction/Paalman Pings algorithms will deal with this situation respectively - however, it is unclear what might be expected to be seen in the preview/interface and how the issue may be conveyed to the user.

2017-08-03 13:29 UTC, mantid-roman commented
I think the preview should try to display the n-th spectrum for both workspaces. If n is out of range for any of them then change it to a valid value and update the 'spectrum' field.

2017-08-03 13:33 UTC, brandonhewer commented
@mantid-roman This certainly seems like a reasonable thing to do - perhaps just the minimax of the two files would work fine for this.

2017-08-04 12:35 UTC, mantid-roman commented on MantidQt/CustomInterfaces/src/Indirect/ContainerSubtraction.cpp
> +                             m_csSampleWS->getNumberHistograms()) -
If one of the pointers is null shouldn't this code crash?

2017-08-04 12:35 UTC, mantid-roman commented on MantidQt/CustomInterfaces/src/Indirect/ContainerSubtraction.cpp
> +                    1;
Can this be moved to the previous line? I don't think clang-format will mind.

2017-08-04 12:37 UTC, mantid-roman commented
If I have only Sample loaded and change Spectrum I get this message:

`Cannot plot with empty workspace name`.

2017-08-04 15:07 UTC, brandonhewer commented on MantidQt/CustomInterfaces/src/Indirect/ContainerSubtraction.cpp
> +                             m_csSampleWS->getNumberHistograms()) -
Yes that's completely right, this is a mistake.

2017-08-08 15:52 UTC, brandonhewer commented
@mantid-roman For some reason, ClangFormat appears intent on moving the '- 1' to the next line.

2017-08-09 09:04 UTC, mantid-roman commented
Message `Cannot plot with empty workspace name` is still there.

2017-08-09 16:21 UTC, brandonhewer commented
@mantid-roman This was occurring, as the container workspace spectrum was set to be added to the plot preview when it did not exist. The most recent update should fix this.

2017-08-10 08:59 UTC, mantid-roman approved these changes

2017-08-10 09:38 UTC, merged