Fix conda build
mantidproject/mantid pull request #20173
Opened 2017-08-04 14:14 UTC by yxqd

Description of work.

**To test:**

Run docker

    $ docker run -it condaforge/linux-anvil

In docker,

    $ git clone https://github.com/mantidproject/conda-recipes
    $ cd conda-recipes/frameworks

Modify meta.yaml, so that 

    version = "3.10.debug"
    git_rev = "fix-conda-build"

Build:

    export OPENGL_gl_LIBRARY=/usr/lib64/libGL.so 
    export OPENGL_glu_LIBRARY=/usr/lib64/libGLU.so 
    yum install -y mesa-libGLU-devel 
    conda build --python 2.7 --numpy 1.13 &>log.build &
    tail -f log.build

Fixes #20172 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-04 19:03 UTC, quantumsteve requested changes
Please move the new include to Cylinder.cpp

2017-08-04 19:03 UTC, quantumsteve commented on Framework/Kernel/inc/MantidKernel/V3D.h
> +#include <cfloat>
Why are you adding this to `V3D.h` when the undefined macro is in `Cylinder.cpp`?

2017-08-04 20:58 UTC, peterfpeterson commented
You should change to [`std::numeric_limits<double>::max()`](https://stackoverflow.com/questions/23278930/what-is-dbl-max-in-c#23279161) since we're a C++ project.

2017-08-07 20:57 UTC, yxqd commented on Framework/Kernel/inc/MantidKernel/V3D.h
> +#include <cfloat>
Rolled back

2017-08-08 12:36 UTC, yxqd commented
@quantumsteve @peterfpeterson please check

2017-08-08 13:02 UTC, peterfpeterson approved these changes
Looks good to me.

2017-08-08 13:10 UTC, quantumsteve approved these changes
:+1:

2017-08-08 13:10 UTC, merged