Add sphere support to SetSample
mantidproject/mantid pull request #20237
Opened 2017-08-11 17:02 UTC by DavidFair

Description of work.
This PR adds support for Spheres to set sample. This is used by PEARL currently but it also allows other people to use a sphere with relative ease.

Additionally I've made the shape field case insensitive as it was slightly confusing why a `sphere` wouldn't work but a `Sphere` is OK from a user perspective. 

**To test:**
Run the following
```
ws = CreateSampleWorkspace()

SetSample(InputWorkspace=ws, Geometry={'Shape' : 'Sphere', 'Center': [0., 0., 0.], 'Radius' : 1.0}, Material={'ChemicalFormula': 'V'})
```

On the workspace view the "Sample Details". If this has entries (for a Vanadium) SetSample completed successfully. 

Fixes #20207 . 

**Release Notes** 
Added to the release notes here

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-18 10:48 UTC, AnthonyLim23 commented on Framework/DataHandling/src/SetSample.cpp
> +      static_cast<double>(args.getProperty(ShapeArgs::RADIUS)) * 0.01;
add a comment somewhere saying that it expects an input of untis (cm?)

2017-08-18 10:51 UTC, AnthonyLim23 commented on Framework/DataHandling/test/SetSampleTest.h
> +  void test_Setting_Uppercase_Geometry_As_Sphere() {
could we add a test for mixed case (e.g. sPhERe)?

2017-08-18 10:52 UTC, AnthonyLim23 reviewed
Need to test it but looks good so far. Just a couple of minor things

2017-08-21 09:13 UTC, AnthonyLim23 approved these changes
worked as described, except the command was sample material.

2017-08-22 07:19 UTC, martyngigg requested changes

2017-08-22 07:19 UTC, martyngigg commented on Framework/DataHandling/src/SetSample.cpp
> +  xmlShapeStream << "<" << tag << " id=\"sample-shape\"> "
This doesn't make sense to me. This is not the correct XML to define a sphere: http://docs.mantidproject.org/nightly/concepts/HowToDefineGeometricShape.html#sphere. A sphere doesn't have an axis and only requires a centre and a radius to configure it. I am surprised the test works.

2017-08-25 10:01 UTC, closed without merging