WIP: ISIS Reflectometry: Prevent external table modification while processing
mantidproject/mantid pull request #20255
Opened 2017-08-16 13:35 UTC by edwardb96

- Disables actions which modify the contents of the DataProcessorWidget runs table whilst the widget is processing and not paused.
- Refactors elements of the `QDataProcessorWidget`, `QtReflRunsTabView`, `ReflRunsTabPresenter` and `GenericDataProcessor` as well as the tests `ReflRunsTabPresenterTest`.

**To test:**

Fixes #19951. 

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-23 10:26 UTC, AntonPiccardoSelg requested changes
Nice refactoring work . Clear improvement of the code quality  :+1:.

There are only some minor point and a fairly important point regarding reduction scenarios which might not use post-processing.

2017-08-23 10:26 UTC, AntonPiccardoSelg commented on qt/scientific_interfaces/ISISReflectometry/ReflectometryAction.h
> +  EXPORT_TBL
I think we should either call everything `TABLE` or everything `TBL`

2017-08-23 10:26 UTC, AntonPiccardoSelg commented on qt/widgets/common/src/DataProcessorUI/QDataProcessorWidget.cpp
> +  switch (action) {
Will this be an issue when you are dealing with non-grouped reduction scenarios?

2017-09-18 08:41 UTC, AntonPiccardoSelg commented
@edwardb96 There seem to be merge conflicts on here

2017-09-18 08:51 UTC, edwardb96 commented
There's a lot more than merge conflicts wrong with this PR, #19951 its no longer scheduled for 3.11.
I'll be continuing work on this issue in a new branch `19951_prevent_external_table_modification_2`.

2017-09-18 08:51 UTC, closed without merging