Enable ProductFunction to behave as a CompositeFunction in Python
mantidproject/mantid pull request #20304
Opened 2017-08-22 08:20 UTC by KarlPalmen

Before this change ``ProductFunction`` would behave as a ``CompositeFunction`` in Python, because it is in ``CurveFitting``, which is not exported to Python. The work was to achieve this export and in particular enable ``ProductFunction`` to behave as a ``CompositeFunction``.

**To test:**

Try out a python script that uses ``ProductFunction`` and methods it inherits from ``CompositeFunction``, such as ``len(p)``, ``p.add(f)``, p.getFunction(i)``

Fixes #20279. 

**Release Notes** 
This is being done to enable improvement of the workability 
of fitting functions in python #19010 and so
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-08-22 13:03 UTC, martyngigg requested changes
This looks like it is mostly there. I've just got a few comments for clean up.

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/mantid/_plugins/__init__.py
> +Defines Python objects that wrap the C++ DataObjects namespace. These are exported
This isn't quite the right documentation for this subpackage as it's a little different to the others: Can we have something like:

"Defines Python objects that wrap classes from the framework defined as plugins. The classes defined here simply export the class types to Python but not any additional functionality. This allows Boost Python to automatically downcast a type to the actual leaf type, making it easier to work with these objects in Python."

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/mantid/_plugins/src/Exports/ProductFunction.cpp
> +namespace {
These functions are not needed so we should be able to delete the whole anonymous namespace.

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/mantid/_plugins/src/curvefitting.cpp.in
> +// See http://docs.scipy.org/doc/numpy/reference/c-api.array.html#PY_ARRAY_UNIQUE_SYMBOL
On second thoughts we don't use `numpy` here so we can delete these 3 lines.

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/mantid/_plugins/src/curvefitting.cpp.in
> +  // Import numpy
We can delete these 2 lines as well.

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/_plugins/ProductFunctionTest.py
> +from mantid.kernel import DateAndTime
We don't need these 2 import lines from `mantid.kernel`

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/_plugins/ProductFunctionTest.py
> +# from mantid._plugins import ProductFunction
Can we remove this comment line too, please?

2017-08-22 13:03 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/_plugins/ProductFunctionTest.py
> +
I think it would be a good idea to have an additional check that verifies `isinstance(p, CompositeFunction)` is true.

2017-08-23 09:00 UTC, KarlPalmen commented on Framework/PythonInterface/mantid/_plugins/src/curvefitting.cpp.in
> +// See http://docs.scipy.org/doc/numpy/reference/c-api.array.html#PY_ARRAY_UNIQUE_SYMBOL
Remove these 3 lines (starting with last line shown) causes a build failure concerning ``_import_array`` in the generated file.

2017-08-23 09:06 UTC, KarlPalmen commented on Framework/PythonInterface/mantid/_plugins/src/curvefitting.cpp.in
> +// See http://docs.scipy.org/doc/numpy/reference/c-api.array.html#PY_ARRAY_UNIQUE_SYMBOL
It does work, after deleting the two lines you suggested next.

2017-08-23 10:32 UTC, martyngigg commented on Framework/PythonInterface/mantid/_plugins/src/curvefitting.cpp.in
> +// See http://docs.scipy.org/doc/numpy/reference/c-api.array.html#PY_ARRAY_UNIQUE_SYMBOL
:+1:

2017-08-23 10:40 UTC, martyngigg commented
@KarlPalmen This looks good now I think. There were some clang-format changes on `master` too so could you merge master to your branch as well, please?

2017-08-23 10:41 UTC, martyngigg approved these changes

2017-08-23 10:44 UTC, KarlPalmen commented
That would explain why my most recent clang patch was for files I not modified.

2017-08-23 10:47 UTC, mantid-roman approved these changes
Looks fine to me.

2017-08-23 12:23 UTC, KarlPalmen commented
It tried merging master into the branch and got the reply ``Already up-to-date``.

2017-08-23 12:33 UTC, KarlPalmen commented
I forgot to fetch.

2017-08-25 09:07 UTC, KarlPalmen commented
I need to get this merged into master, before I can continue work on #19010 with PR #19971 .

2017-08-25 12:30 UTC, merged