Adding maximum entropy method to Frequency Domain Analysis GUI
mantidproject/mantid pull request #20310
Opened 2017-08-22 13:48 UTC by AnthonyLim23

**Do not merge before #20205** 

The MaxEnt algorithm has been added to the new Muon GUI (Frequency Domain Analysis, see #20205). This involved adding a menu bar that can be used to select the method (FFT or MaxEnt) along with an implementation of the MaxEnt GUI. These changes required some minor restructuring of the code. 

**To test:**
0. Open muon analysis (custom interface) and load some data (the current run will do). Go to the settings tab and bin the data (10) 

1. Open the Frequency Domain analysis GUI. 
2. Use the drop down menu to switch between the two interfaces. 
3. In the MaxEnt interface the data selection should automatically be loaded in the workspace dropdown menu.
4. Try various settings and run MaxEnt. The MaxEnt algorithm is expensive so if you use the Raw data (tick box) then it will take a long time.

Fixes #20233 
**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-15 15:38 UTC, AnthonyLim23 commented
This is important to stay in this release

2017-09-19 09:31 UTC, mantid-roman commented
Cannot run Frequency Domain Analysis:
```
KeyError: "'MuonAnalysis' does not exist."
  at line 35 in '<Interface>'
  caused by line 20 in '<Interface>'
  caused by line 13 in 'D:/Work/mantid-1/scripts\Muon\transform_presenter.py'
  caused by line 11 in 'D:/Work/mantid-1/scripts\Muon\load_utils.py'
```

2017-09-19 10:58 UTC, AnthonyLim23 commented
Ah sorry, I forgot to update the instructions. You need to load some data into muon analysis first. It then only considers that data.

2017-09-20 10:45 UTC, mantid-roman commented
Could you add a warning to the user with instructions how to make it work if the workspace doesn't exist?

2017-09-20 10:46 UTC, mantid-roman commented
What is the output of MaxEnt? I couldn't see any.

2017-09-20 10:48 UTC, AnthonyLim23 commented
The output is under the group workspace for that run e.g. MUSR00023456 and will have a _maxEnt on the end of the name. 

I will update the documentation later today

2017-09-20 13:03 UTC, mantid-roman commented
I merged master. Now I have this error when I start Muon Analysis:
```
Traceback (most recent call last):
  File "D:\Work\mantid\build\bin\Release\pymantidplot\proxies.py", line 73, in _do_dispatch
    raise self.__exception # Ensures this happens in the right thread
TypeError: MantidUI.plot1D(list-of-QString, list-of-int, bool, MantidQt.DistributionFlag distr=MantidQt.DistributionDefault, bool errs=True, GraphOptions.CurveType style=GraphOptions.Unspecified, Graph plotWindow=None, bool clearWindow=False, bool waterfallPlot=False): argument 1 has unexpected type 'list'
TypeError: MantidUI.plot1D(list-of-QString, list-of-int, bool, MantidQt.DistributionFlag distr=MantidQt.DistributionDefault, bool errs=True, GraphOptions.CurveType style=GraphOptions.Unspecified, Graph plotWindow=None, bool clearWindow=False, bool waterfallPlot=False): argument 1 has unexpected type 'list'
  at line 60 in '<Interface>'
  caused by line 30 in '<Interface>'
  caused by line 274 in 'D:\Work\mantid\build\bin\Release\pymantidplot\__init__.py'
  caused by line 99 in 'D:\Work\mantid\build\bin\Release\pymantidplot\proxies.py'
  caused by line 51 in 'D:\Work\mantid\build\bin\Release\pymantidplot\proxies.py'
  caused by line 73 in 'D:\Work\mantid\build\bin\Release\pymantidplot\proxies.py'
```

2017-09-20 13:05 UTC, AnthonyLim23 commented
I had that this morning,. The solution is to delete everything in the build directory and rebuild it.

2017-09-20 13:06 UTC, mantid-roman commented
OK, I'll try.

2017-09-21 11:09 UTC, mantid-roman requested changes

2017-09-21 11:09 UTC, mantid-roman commented on scripts/Muon/transform_selection_presenter.py
> +class transformSelectionPresenter(object):
Name should begin with capital T

2017-09-21 11:09 UTC, mantid-roman commented on scripts/Muon/transform_view.py
> +class transformView(QtGui.QWidget):
Name should begin with capital T

2017-09-21 11:09 UTC, mantid-roman commented on scripts/Muon/view_constructor.py
> +class viewConstructor(object):
Class name should start with capital V.

2017-09-21 11:09 UTC, mantid-roman commented on scripts/Muon/view_constructor.py
> +"""
The docstring should be moved to the line below `class ViewConstructor(object):`

2017-09-21 11:09 UTC, mantid-roman commented on scripts/test/Muon/MaxEntPresenter_test.py
> + #       self.alg.started.connect=mock.Mock()
Delete the line?

2017-09-21 12:01 UTC, AnthonyLim23 commented on scripts/Muon/load_utils.py
> +        self.options = mantid.AnalysisDataService.getObjectNames()
A few lines done it throws out anything that is not relevant. I will add comments

2017-09-25 09:55 UTC, mantid-roman approved these changes

2017-09-25 13:33 UTC, merged