Output string representation of optimal fit function after completion of fitting
mantidproject/mantid pull request #20328
Opened 2017-08-23 17:57 UTC by jmborr

**To test:**

Download and unzip under `/tmp` and run the script:

```
hello dolly
```
The printed function should be
```
(composite=Convolution,FixResolution=false,NumDeriv=true;name=TabulatedFunction,Workspace=resolution,WorkspaceIndex=0,X=(),Y=(),Scaling=1.09281,Shift=1.47731e-10,XScaling=1,ties=(XScaling=1);(name=DeltaFunction,Height=0.87475,Centre=0,constraints=(0<Height<1),ties=(Centre=0);name=Lorentzian,Amplitude=0.12525,PeakCentre=0,FWHM=0.00874458,constraints=(0.001<FWHM),ties=(PeakCentre=0);ties=(f1.Amplitude=1-f0.Height)));name=LinearBackground,A0=3.41084e-05,A1=6.46268e-05
```
Fixes #20326
**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-06 08:17 UTC, soininen requested changes
There were a few minor formatting issues in the usage example. Otherwise this looks like a nice addition to Fit. A small concern I have is the new API which breaks scripts that unzip the returned tuple:
```python
a, b, c, d = Fit(...)
```
However, I think we have to encourage the users to use the named tuples instead. The improvements in the usage examples are in the right direction in this regard.

2017-09-06 08:17 UTC, soininen commented on docs/source/algorithms/Fit-v1.rst
> +   print( "The fit was: " + fit_output.OutputStatus)
A leftover space.

2017-09-06 08:17 UTC, soininen commented on docs/source/algorithms/LoadSassena-v1.rst
> +    print( "Number of spectra in fitWorkspace is: " +  str(fitWorkspace.getNumberHistograms()))
Leftover space.

2017-09-06 08:17 UTC, soininen commented on docs/source/concepts/Fitting.rst
> +            CloneWorkspace(InputWorkspace='fit_Workspace',OutputWorkspace='fitBest')
Missing space before `OutputWorkspace`.

2017-09-06 13:54 UTC, jmborr commented
@soininen yes, `a, b, c, d = Fit(...)` will unfortunately break but it can't be helped. I will point out that `Fit` returns something like 7 different quantities and I think we can convince users of the futility of defining seven variables in the unpacking statement when they're planning to use, say, just one. The named tuple is definitely the way to go.

2017-09-07 06:02 UTC, soininen approved these changes

2017-09-07 07:37 UTC, mantid-roman commented
I think this new property is unnecessary as it duplicates the in-out Function property and we want to get away from function strings. I would prefer if the python Fit function returned a function wrapper from Karl's PR https://github.com/mantidproject/mantid/pull/19971 instead.

2017-09-07 13:26 UTC, martyngigg commented
@mantid-roman How would the function be retrieved after the Fit call or should it be created differently. Can you provide an example?

2017-09-07 13:40 UTC, mantid-roman commented
I would do it similarly to how I did it for crystal field: `function = alg.getProperty('Function').value`.

2017-09-07 13:55 UTC, martyngigg commented
@mantid-roman This is a bit harder to do in Python though isn't it?

2017-09-07 14:01 UTC, mantid-roman commented
My example was from the crystal field python interface. `alg` is an instance of Fit algorithm. simpleapi has a wrapper for fitting algorithms. This can be done inside it.

2017-09-07 14:21 UTC, jmborr commented
@mantid-roman I would also prefer to return a function object instead of a function string, but pull #19971 is not closed and I need this now. Also, [the returned properties by algorithms](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/simpleapi.py#L773) are only those marked as `Output`, so properties marked as  `InOut` are ignored.

2017-09-07 14:26 UTC, jmborr commented
@mantid-roman If I understand, you're suggesting to modify wrapper [fitting_algorithm(f)](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/simpleapi.py#L299) to include returning a function object in the named tuple. Is this correct?

2017-09-07 14:28 UTC, mantid-roman commented
@jmborr Yes

2017-09-07 14:33 UTC, jmborr commented
OK, I'll get down to it :runner:

2017-09-08 14:13 UTC, jmborr commented
@mantid-roman @martyngigg @soininen I'm planing of adding optional argument `inout=False` to [_gather_returns](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/simpleapi.py#L810) in order to retrieve not just the `Direction::Output` properties but also `Direction::InOut`, like property `Function` of the Fit algorithm. Please let me know if you have any objections.

2017-09-14 18:39 UTC, jmborr commented
@soininen Well, this finally passed all the test. Can you please redo the manual test now that I'm returning the function object?

2017-09-15 08:46 UTC, soininen commented
The changes look OK to me, and the test script runs just fine. However, I'm not too familiar with the fitting stuff, and how this particular PR fits the bigger picture. @mantid-roman How's your opinion?

2017-09-15 09:08 UTC, mantid-roman commented
It fits very well. I just want to test how it works with the new `FunctionWrapper`s.

2017-09-15 09:52 UTC, mantid-roman requested changes
Can `Fit` return a `FunctionWrapper` instead of a C++ pointer?

2017-09-15 23:06 UTC, jmborr commented
@mantid-roman I tried to return a `FunctionWrapper` by [invoking its initializer from the string representation of the fit function](https://github.com/mantidproject/mantid/pull/20328/files#diff-21e1642a0ce7da9cc69e0c7542489c39R887). However, I get an error from the DynamicFactory when running the test:
```
  File "/home/jbq/repositories/mantidproject/mantid2/cmake-build-debug/bin/mantid/fitfunctions.py", line 16, in __init__
    self.fun = FunctionFactory.createFunction(name)
RuntimeError: DynamicFactory: (composite=Convolution,FixResolution=false,NumDeriv=true;name=TabulatedFunction,Workspace=resolution,WorkspaceIndex=0,X=(),Y=(),Scaling=1.09281,Shift=1.47731e-10,XScaling=1,ties=(XScaling=1);(name=DeltaFunction,Height=0.87475,Centre=0,constraints=(0<Height<1),ties=(Centre=0);name=Lorentzian,Amplitude=0.12525,PeakCentre=0,FWHM=0.00874458,constraints=(0.001<FWHM),ties=(PeakCentre=0);ties=(f1.Amplitude=1-f0.Height)));name=LinearBackground,A0=3.41084e-05,A1=6.46268e-05 is not registered.
 search object (composite=Convolution,FixResolution=false,NumDeriv=true;name=TabulatedFunction,Workspace=resolution,WorkspaceIndex=0,X=(),Y=(),Scaling=1.09281,Shift=1.47731e-10,XScaling=1,ties=(XScaling=1);(name=DeltaFunction,Height=0.87475,Centre=0,constraints=(0<Height<1),ties=(Centre=0);name=Lorentzian,Amplitude=0.12525,PeakCentre=0,FWHM=0.00874458,constraints=(0.001<FWHM),ties=(PeakCentre=0);ties=(f1.Amplitude=1-f0.Height)));name=LinearBackground,A0=3.41084e-05,A1=6.46268e-05
```
I'm a bit at a loss because the new function API is, well, new to me.

2017-09-18 08:19 UTC, mantid-roman commented on Framework/PythonInterface/mantid/simpleapi.py
> +            retvals[name] = FunctionWrapper(value_str)
Just pass `prop.value` to `FunctionWrapper`:

```
retvals[name] = FunctionWrapper(prop.value)
```

2017-09-18 14:30 UTC, jmborr commented
@mantid-roman Thanks Roman, now I see your suggestion makes sense in view of [`FunctionWrapper.__init__`](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/fitfunctions.py#L6)

2017-09-18 14:38 UTC, jmborr commented
@mantid-roman So as of today, is the way to create a `FunctionWrapper` object from a string representation like this?
```
ifun_obj = FunctionFactory.createInitialized("name=UserFunction,Formula=a*erf(x),a=0")
f = FunctionWrapper(ifun_obj)
```
Shouldn't `FunctionWrapper.__init__` use `FunctionFactory.createInitialized` instead of `FunctionFactory.createFunction`?

2017-09-18 14:42 UTC, mantid-roman commented
The idea behind `FunctionWrapper` is to be able to do this:
```
f = UserFunction(Formula='a*erf(x)',a=0)
```

2017-09-20 13:46 UTC, jmborr commented
@mantid-roman Can you please give the OK if I addressed all your concerns?

2017-09-20 13:50 UTC, mantid-roman approved these changes

2017-09-20 13:52 UTC, jmborr commented
thanks! :sunflower:

2017-09-21 09:09 UTC, merged