Bring support for HRPD into ISISPowder scripts
mantidproject/mantid pull request #20449
Opened 2017-09-12 15:51 UTC by josephframsay

A collection of routines and classes have been written to replace the CRI scripts previously used by HRPD in Mantid.

**To test:**

Scientific validation has taken place with HRPD, so as long as the unit and system tests for `ISIS_PowderHRPD` pass without issues, the changes should be good to go.

Fixes #20152 

**Release Notes** 
[here](https://github.com/mantidproject/mantid/commit/88890ea0d064688f8c400b4e769276260e785597)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-14 09:16 UTC, samueljackson92 requested changes
Generally good. I have a couple of comments that should be addressed.

2017-09-14 09:16 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/sample_details.py
> +        if self.shape_type == "cylinder":
`shape_type` and `shape` should be called `_shape_type` and `_shape` to match the [python conventions](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles).

2017-09-14 09:16 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/sample_details.py
> +            raise KeyError("Shape type \"" + self.shape_type + "\" not supported: current supported shape types are "
Don't use string concatenation with `+`, use [.format](https://docs.python.org/2/library/string.html#formatstrings) instead.

2017-09-14 10:25 UTC, josephframsay commented on scripts/Diffraction/isis_powder/routines/sample_details.py
> +        print("Sample Details")
I think David's thinking behind this is that (as far as I can tell) the logger doesn't show up in the script window, only in the results log

2017-09-14 11:09 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/sample_details.py
> +        print("Sample Details")
Ah I see. This is probably better then.

2017-09-14 11:54 UTC, samueljackson92 requested changes

2017-09-14 11:54 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/sample_details.py
> +            logger.warning(warning)
Could we make this so that it also makes a `print` call here as well? Just so you get a message both in the scrit window and the log window?

2017-09-19 09:35 UTC, samueljackson92 approved these changes

2017-09-19 09:35 UTC, samueljackson92 commented
I think this is good to go now. 👍

2017-09-19 10:59 UTC, merged