Simple evaluation of FunctionWrapper functions in python
mantidproject/mantid pull request #20456
Opened 2017-09-13 08:42 UTC by KarlPalmen

Fixes #20420 
== To test ==
Try python scripts such as
```
p = Polynomial(n=2, A0=0, A1=0.5, A2=0.5)

print p(1)
print p(2)
print p(3)
print p([0,1,2,3])

ws = CreateWorkspace(DataX=[0,1,2,3,4,5,6,7], DataY=[5,5,5,5,5,5,5])

print p(ws).readY(1)
```
Also try with numpy arrays.

**Release Notes** 

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-14 08:15 UTC, KarlPalmen commented
I've realised I need to add something to the user documentation about this. I'll do this after getting Roman's change on my local copy of the branch.

2017-09-14 08:18 UTC, mantid-roman requested changes

2017-09-14 08:18 UTC, mantid-roman commented on Framework/PythonInterface/test/python/mantid/FitFunctionsTest.py
> +        self.assertAlmostEqual(result[1][1],121.0)
A test is needed that `*params` arguments set the parameters correctly

2017-09-14 08:18 UTC, mantid-roman commented on Framework/PythonInterface/mantid/fitfunctions.py
> +      from mantid.simpleapi import CreateWorkspace, EvaluateFunction
There is no need for these imports any more. I forgot to delete the line after my changes.

2017-09-14 08:21 UTC, mantid-roman commented
@KarlPalmen I made some changes to make it possible to pass function objects to fitting algorithms. Now mantid functions can be used with the `scipy` optimisation library.

2017-09-14 13:21 UTC, KarlPalmen commented
@mantid-roman I've tried SimpleAPIRenameWorkspaceTest on my PC and it crashes.

2017-09-14 15:30 UTC, KarlPalmen commented
Thank you @mantid-roman . That fixed it.

2017-09-18 13:33 UTC, KarlPalmen commented
I'm un-assigning @mantid-roman from the PR because he has been doing work on this issue. Thank you. Someone else needs to test & review it.

2017-09-18 14:49 UTC, josephframsay requested changes
Changes look good, but there's a few places where, I might be wrong, they don't appear to quite meet the design document:

- **"A call without passing in any initialisation arguments should create a function with default parameters and attributes"** - this is true of most of the functions, but if I make a `Polynomial` with no parameters and then try and call it, I get `IndexError: ParamFunction parameter index 0 out of range 0`. If it's not valid to have a `Polynomial` with no parameters, maybe there should be a check for this (though maybe that's a problem with `Polynomial` and not your new stuff)?
- **"The output type is the same as that of the input"** - This is not the case if I call functions with a list, as I always get back an array. Is this deliberate?

2017-09-18 14:49 UTC, josephframsay commented on Framework/PythonInterface/mantid/fitfunctions.py
> +      list_input = False
These two flags might read more intuitively if they were written something like `list_input = isinstance(x, list)`

2017-09-18 14:59 UTC, mantid-roman commented
@josephframsay 
* It is a problem with `Polynomial`
* I think returning a numpy array for a list is fine.

2017-09-18 15:46 UTC, mantid-roman approved these changes

2017-09-19 08:05 UTC, KarlPalmen commented
@josephframsay  have you any outstanding concerns about this pull request?

2017-09-19 08:18 UTC, josephframsay commented
Only a superficial thing - I think the lines associated with `list_input` and `numpy_input` could be made a bit more readable by changing them to something like:
```
list_input = isinstance(x, list)
numpy_input = isinstance(x, np.ndarray)
if numpy_input:
    ....
elif list_input:
    ....
```
It means the variables only get assigned to once, and it might save someone a bit of a headache in future. Other than that, everything looks grand to me

2017-09-19 14:35 UTC, josephframsay approved these changes

2017-09-20 16:42 UTC, merged