Indirect - Diffraction Reduction - Correctly implement Use Manual Grouping
mantidproject/mantid pull request #20478
Opened 2017-09-14 17:31 UTC by brandonhewer

Description of work.

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-21 12:47 UTC, edwardb96 requested changes
Now working 👍. Just a couple of potential method extractions...

2017-09-21 12:47 UTC, edwardb96 commented on scripts/Inelastic/IndirectReductionCommon.py
> +            mask_detectors.execute()
Could this be moved to it's own function?

2017-09-21 12:47 UTC, edwardb96 commented on scripts/Inelastic/IndirectReductionCommon.py
> +            save_ascii_alg.execute()
Same again, could this be its own function?

2017-09-21 13:19 UTC, brandonhewer commented
@edwardb96 Good spots, I've moved the highlighted code to separate functions. Should help in slowly cleaning up IndirectReductionCommon.

2017-09-21 15:24 UTC, edwardb96 approved these changes

2017-09-21 15:25 UTC, edwardb96 commented
Ok to merge when tests pass. 😄

2017-09-21 18:38 UTC, AndreiSavici commented
Is this supposed to be documented somewhere? Release notes?

2017-09-22 05:33 UTC, martyngigg commented
I'm going to me this so it can be tested by scientists
@brandonhewer Please add something to the inelastic release notes in a separate PR.

2017-09-22 05:33 UTC, merged