BASISReduction: save data in NXSPE format
mantidproject/mantid pull request #20522
Opened 2017-09-19 22:31 UTC by jmborr

[Release Notes*]()

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-20 00:12 UTC, AndreiSavici requested changes
Also add in the help file a requirement that some log must exist for the angle

2017-09-20 00:12 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/BASISReduction.py
> +                error_message = 'Runs have no log entry named {}'.format(self._reflection)
Wrong error message

2017-09-22 13:51 UTC, jmborr commented
@AndreiSavici Is there anything else you would like done for this pull request?

2017-09-22 18:29 UTC, AndreiSavici approved these changes

2017-09-26 07:07 UTC, merged