Number of bin boundaries
mantidproject/mantid pull request #20541
Opened 2017-09-20 15:58 UTC by AndreiSavici

New function to get number of bin boundaries

Fixes #20497

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-20 16:16 UTC, quantumsteve requested changes
This looks good, just be careful with virtual functions inside tight loops.

2017-09-20 16:16 UTC, quantumsteve commented on Framework/MDAlgorithms/src/SaveMD2.cpp
> +    for (size_t n = 0; n < dim->getNBoundaries(); n++)
Move `dim->getNBoundaries()` out of the for loop. Compilers have a hard time seeing through virtual functions.

2017-09-20 16:16 UTC, quantumsteve commented on qt/paraview_ext/VatesAPI/src/vtkMDHistoLineFactory.cpp
> +    coord_t incrementX = m_workspace->getXDimension()->getBinWidth();
:+1:

2017-09-20 17:12 UTC, quantumsteve approved these changes

2017-09-21 05:31 UTC, SimonHeybrock commented
How does this interact with @peterfpeterson's PR introducing variable length histograms?

2017-09-21 09:18 UTC, martyngigg commented
I think this should also go into `3.12` and not `3.11`

2017-09-21 14:06 UTC, AndreiSavici commented
This should definitely be in 3.11. It fixes a bug that is causing problems for both diffuse elastic and direct geometry inelastic single crystal scattering. The extra stuff is just because @quantumsteve wanted more than a temporary fix. See issue #20495  and PR #20496

2017-09-21 14:16 UTC, quantumsteve commented
@SimonHeybrock This adds a member function to `IMDDimension` to avoid off-by-one errors in existing code. If there is any overlap with variable length histograms, it should have already been addressed when earlier when creating this object.

2017-09-21 20:22 UTC, merged