Miscellaneous Flake8 warnings fixed
mantidproject/mantid pull request #20637
Opened 2017-09-25 14:33 UTC by josephframsay

**IN PROGRESS**

As part of #20508, several Python scripts have been refactored to reduce cyclomatic complexity

**To test:**
Make sure all unit and system tests pass, and code review. In addition, if this is your area, feel free to throw some data at me to test the affected scripts with, to make sure I haven't broken anything

Note: it was deemed acceptable to just bury the warnings associated with SANS under the rug with a noqa flag, as these scripts are soon to be deprecated, and a lack of unit tests makes refactoring them needlessly risky

Address part of #20508 . 

**Release Notes** 
*Does not need to be in the release notes as the change is internal*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-05 14:45 UTC, peterfpeterson approved these changes
These files no longer have `python3-flake8` warnings in them.

2017-10-05 16:13 UTC, AndreiSavici requested changes

2017-10-05 16:13 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
> +        if self._background == 'Sloping':
All these if statements should be `return ['Zero','Flat','Sloping'].index(self._background)`

2017-10-06 17:55 UTC, AndreiSavici commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
> -        setup_prog.report('Encoding input options')
Is this line supposed to be gone?

2017-10-09 08:12 UTC, josephframsay commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
> -        setup_prog.report('Encoding input options')
Nope - replaced now!

2017-10-09 14:01 UTC, AndreiSavici approved these changes

2017-10-10 07:22 UTC, SimonHeybrock commented
The PR message still says "in progress", should this be merged or are there more changes coming?

2017-10-10 07:30 UTC, josephframsay commented
Nope, just forgot to remove that. Everything's done on this one

2017-10-10 07:30 UTC, merged