Data Processor Refactoring Part 1
mantidproject/mantid pull request #20666
Opened 2017-09-27 11:08 UTC by edwardb96

This PR begins the refactoring the `DataProcessor` classes as described by the issue #20665 .

To summarise this PR
- Adds a `const_iterator` to the `WhiteList` class.
- Groups postprocessing and preprocessing attributes of `GenericDataProcessorPresenter` into their own classes, `PreprocessingAttributes` and `PostprocessingStep`.
- Moves the postprocessGroup routine out of `GenericDataProcessorPresenter` and into `PostprocessingStep`.
- Replaces the postprocessing related member variables with a `optional<PostprocessingStep>` member variable`
- Removes the `m_columns` and `m_postprocess` member variables.

**To test:**
- Ensure that the SANS v2 and Reflectometry GUIs open and continue to operate without errors.
- Ensure the unit tests pass.
- Code Review

No Issue

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-10 14:44 UTC, gemmaguest requested changes
The changes look good to me :+1: Just some minor queries inline, and I think most of the new files are missing doxygen comments.

2017-10-10 14:44 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/PostprocessingStep.cpp
> +                                       std::map<QString, QString> map)
Should these pass by reference?

2017-10-10 14:44 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/PostprocessingStep.cpp
> +  for (auto kvp : optionsMap) {
`auto const &` ?

2017-10-10 14:44 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/PostprocessingStep.cpp
> +    auto const propValueStr =
Do these create copies?

2017-10-10 14:44 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/TwoLevelTreeManager.cpp
> +      for (auto columnName : whitelist.names())
`auto const&` ?

2017-10-13 14:38 UTC, mantid-builder commented
@edwardb96 have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2017-10-23 11:29 UTC, gemmaguest approved these changes

2017-10-23 11:33 UTC, gemmaguest commented
Thanks for the changes. All looks good now and the GUIs operate as normal :+1:

2017-10-24 08:00 UTC, martyngigg commented on qt/widgets/common/src/DataProcessorUI/PostprocessingStep.cpp
> +    auto column = *columnIt;
@edwardb96 This does create a copy doesn't it?

2017-10-24 08:02 UTC, martyngigg commented on qt/widgets/common/src/DataProcessorUI/GenericDataProcessorPresenter.cpp
> +  if (m_manager->isValidModel(workspace, static_cast<int>(m_whitelist.size())))
@edwardb96 As Gemma has pointed out, `isValidModel` is used with and without (above) the `static_cast` Can we be consistent, please?

2017-10-24 08:04 UTC, martyngigg commented on qt/widgets/common/src/DataProcessorUI/GenerateNotebook.cpp
> +#include <iostream>
Is `iostream` necessary? It's a heavy include and I see that `<sstream>` & `<fstream>` are already included.

2017-10-24 08:05 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/WhiteList.h
>  #include <map>
Unused include.

2017-10-24 08:22 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/WhiteList.h
>    virtual ~WhiteList(){};
Is this necessary? It will suppress the default move constructor/assignment operator.

2017-10-24 11:01 UTC, merged