Indirect - MSDFit - Display and update properties in property table
mantidproject/mantid pull request #20671
Opened 2017-09-27 14:37 UTC by brandonhewer

In the MSDFit Indirect Data Analysis interface, when the model is updated, the property table does not display the properties for the current model (e.g. Intensity and MSD for a Gaussian model).
These properties should be displayed and updated and the plot preview should properly display the results of a fit.

**To test:**

Fixes #20642. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-02 16:48 UTC, LamarMoore requested changes
Functionality as described in the PR test instructions. However, I noticed there are many irrelevant clang -format changes to documentation which should be reverted. It makes the diffs huge and difficult to read. Please revert the documentation changes.

2017-10-02 16:48 UTC, LamarMoore commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> + */
Please undo clang formatting of documentation where relevant.

2017-10-02 16:48 UTC, LamarMoore commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> + */
revert doc changes

2017-10-02 16:48 UTC, LamarMoore commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> + * Reads in settings files
And again

2017-10-02 17:05 UTC, brandonhewer commented
@LamarMoore You're right about the Doc Changes (this is likely due to formatting in Visual Studio). Currently there are number of important bug fixes to be made within Indirect by Wednesday. Martyn has let me know he would be willing to Merge this PR if everyone works as expected. Would it be possible to avoid reverting these changes this time and use the `?w=1` suffix when viewing the changes?

2017-10-03 07:00 UTC, LamarMoore approved these changes

2017-10-03 07:16 UTC, merged