Expose fitting penalties to python
mantidproject/mantid pull request #20682
Opened 2017-09-27 20:39 UTC by VickieLynch

Description of work.
Python fitting function needs higher penalty for violating constraints (Brendan's IC)

**To test:**

        self.addConstraints("A>0");
        self.addConstraints("B>0");
        self.addConstraints("R>0");
        self.addConstraints("T0>0");
        self.setConstraintPenaltyFactor("A", 1.0e3)
        self.setConstraintPenaltyFactor("B", 1.0e3)
        self.setConstraintPenaltyFactor("R", 1.0e3)
        self.setConstraintPenaltyFactor("T0", 1.0e3)

Fixes #20634 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-27 23:45 UTC, jmborr commented
@VickieLynch what object is `self` in the test?

2017-10-16 18:09 UTC, jmborr commented
@VickieLynch let me know when all the build servers pass and you're done. Also, add the `in progress` label.

2017-10-16 20:56 UTC, VickieLynch commented
@jmborr All builds have passed

2017-10-16 23:54 UTC, jmborr commented
@VickieLynch I ran the script without penalty by setting
`myFunc.setConstraintPenaltyFactor("PeakCentre",0.0)`
and still got `PeakCentre=3`. Do you know the reason?

2017-10-17 12:07 UTC, VickieLynch commented
@jmborr I agree the penalty=0 shows this is not working correctly, but I do not see the exception

2017-10-17 14:02 UTC, jmborr commented
@VickieLynch I ran the script in the scrip* window of mantidplot. The exception was shown in the **log** window, not in the script window

2017-10-18 15:10 UTC, peterfpeterson submitted a review, later dismissed

2017-10-18 17:13 UTC, jmborr requested changes

2017-10-18 17:13 UTC, jmborr commented on Framework/PythonInterface/mantid/api/src/Exports/IFunction.cpp
> +
Can you travel back the test to find why the example is not working?

2017-10-31 12:01 UTC, NickDraper commented
So after talking to @mantid-roman , this will currently not work.  The Function object in Python  (so the Gaussian in this case) is translated to a string and back as it passes into the Fit algorithm, and the methods for writing to the string and reading back do not do anything with the constraint penalty value.

The places you need to look are IFunction.cpp::writeToString and FunctionFactory.cpp

2017-10-31 12:03 UTC, NickDraper requested changes
See my comment the penalty value is lost during string serialization.  
Also the unit tests only test setting the penalty to a high value (which is just like the default), you need a test where the penalty is reduced so a constraint can be shown to be ignored.

2017-10-31 15:56 UTC, VickieLynch commented
Explains why I could not see difference with test.  I will close since this did not work.

2017-10-31 15:56 UTC, closed without merging

2017-10-31 16:32 UTC, mantid-roman commented
I can take a look at the issue.

2017-11-01 14:44 UTC, jmborr commented
@mantid-roman What if instead of [passing the string representation](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/simpleapi.py#L340), we pass the underlying unwrapped function object?
```
function = function.fun
```

2017-11-01 15:14 UTC, mantid-roman commented
@martyngigg We need your opinion on this. Passing the function means it will be modified by Fit.

2017-11-01 17:10 UTC, martyngigg commented
As discussed on Slack. Cloning could be expensive and cause a lot of unnecessary work so we'll accept the modification of the function by Fit and explain in the documentation how to preserve the old copy if required.

2017-11-02 08:46 UTC, mantid-roman commented
@VickieLynch How urgently do you need this fixed?

2017-11-02 17:28 UTC, VickieLynch commented
@mantid-roman We have a postdoc working on single crystal integration who requested this.  It is not urgent and he can probably find another way to get the fits he wants.

2017-11-03 08:48 UTC, mantid-roman commented
@VickieLynch Why does he feel a need to change the penalty factor? Will changing the default help? At the moment it is arbitrary set to 1000

2017-11-03 13:40 UTC, VickieLynch commented
@mantid-roman Postdoc, Brendan, says my branch with this change does work for him.  He sets to penalties to 1e10 here:
https://github.com/neutrons/fit_peak_intensities/blob/master/ICCFitTools.py  line 579 is where I set the penalty which calls line 25 in https://github.com/neutrons/fit_peak_intensities/blob/master/ICConvoluted.py