Errors for unsorted data in mean algorithm
mantidproject/mantid pull request #20691
Opened 2017-09-28 10:52 UTC by AnthonyLim23

The mean algorithm calculates the average y value for each x value in the workspaces. If the workspaces did not have the same order for the data then this would produce the wrong result. This is because it simply iterated over the x values.

**To test:**
With the script below you can test:
1. It works if the data is good
2. If throws an error if one workspace has more spectra than the other
3. It throws an error if the x values are different between the two spectra 

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-28 10:56 UTC, AnthonyLim23 commented
need to add a test

2017-10-02 15:32 UTC, gemmaguest requested changes
The changes look good :+1:. I get the correct results if the data are ok, or sensible error messages if the workspaces need to be sorted or are not the same shape.

Just one minor point about a misleading comment.

2017-10-02 15:32 UTC, gemmaguest commented on Framework/PythonInterface/test/python/plugins/algorithms/MeanTest.py
> +            c = Mean(Workspaces='a,b') # 'a' and 'b' are different sizes.
I think the comment here is incorrect (copy-paste error?)

2017-10-03 08:46 UTC, gemmaguest approved these changes

2017-10-03 08:47 UTC, gemmaguest commented
All looks good now :+1:. The tests probably don't need to be re-run because the last commit was just a comment change.

2017-10-03 12:19 UTC, merged