Muon crash
mantidproject/mantid pull request #20694
Opened 2017-09-28 12:10 UTC by AnthonyLim23

Just added an error message if the user deletes all of the files while using muon analysis. 

Fixes #20693. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-09-28 14:11 UTC, samueljackson92 commented
@AnthonyLim23 This stops the crash but now I get:
```
No Data available. Please load Some data.
```

Printed 5 times when I open the interface.

2017-09-28 16:28 UTC, AnthonyLim23 commented
ah. That will be because it sets up the interface at start up and there will be no data. The message is relevant but if we want to remove it we will need to be a bit more clever.

2017-10-02 12:47 UTC, samueljackson92 requested changes

2017-10-02 12:47 UTC, samueljackson92 commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +  }
This is still not quite right. I think we always want to return when `m_workspaceNames` is empty but we only want to print the error if the `this` is visible AND `m_workspaceNames` is empty. 

i.e.
```cpp
if(m_workspaceNames.empty()) {
    if (this->visible()))
        g_log.error("...");
    return;
}
```

2017-10-03 08:09 UTC, samueljackson92 approved these changes
This no longer crashes and now only shows an error on the tab that causes the crash.

2017-10-03 12:19 UTC, merged