CalMuonDetectorPhases
mantidproject/mantid pull request #20743
Opened 2017-10-02 10:23 UTC by AnthonyLim23

There was a bug in the code that meant it was fitting using a sin instead of a cosine. So all of the phases were out by pi/2. 

**To test:**

If you load some data into muon analysis (Musr 62642)

Then run CalMuonDetectorPhases on the MuonAnalysis workspace (frequency = 5.6)

The run PaddingandApodization (with padding =1, negative padding true, apodization function = Lorentz and decay constant 2.4) on the output.

Then take the result and put it into FFT (set the output to be the real and imaginary ws, set real to 0 and Im to 1). Run. The plot should have a peak at -5.6 MHz (see #20742 will fix the minus sign)

Fixes #20727 
**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-02 13:49 UTC, NickDraper commented
My commit was a tiny correction to the doctest expected results

2017-10-02 14:06 UTC, AnthonyLim23 commented
Thanks @NickDraper  I thought that I had pushed that change

2017-10-03 09:09 UTC, NickDraper commented
@AnthonyLim23 How accurately are you expecting the peak to be at 5.6 (from your testing notes)?

I'm getting the peak at 5.45, and another at -5,45.
![image](https://user-images.githubusercontent.com/1017173/31117767-e8cf64e8-a822-11e7-9b63-8cfad799604c.png)

History of test:
```python
Load(Filename=r'\\isis\inst$\ndxmusr\instrument\data\cycle_16_5\MUSR00062642.nxs', OutputWorkspace='MUSR00062642')
CalMuonDetectorPhases(InputWorkspace='MUSR00062642', Frequency=5.5999999999999996, DetectorTable='det', DataFitted='data', ForwardSpectra='33-64', BackwardSpectra='1-32')
PaddingAndApodization(InputWorkspace='data_8', OutputWorkspace='pad_8', ApodizationFunction='Lorentz', DecayConstant=2.3999999999999999, Padding=1, NegativePadding=True)
FFT(InputWorkspace='pad_8', OutputWorkspace='fft_8', InputImagWorkspace='pad_8', Imaginary=1)
```

2017-10-03 09:11 UTC, NickDraper requested changes
Some discrepency between results and expected results.  Need some response on this from Anthony.

2017-10-03 10:20 UTC, NickDraper commented
James Lord checked the numbers on this yesterday and was happy, that's good enough for me.

2017-10-03 10:20 UTC, NickDraper approved these changes

2017-10-03 14:49 UTC, merged