20674 py3 doctests basisreduction calcmuondetector phases
mantidproject/mantid pull request #20758
Opened 2017-10-03 10:19 UTC by samueljackson92

Python3 doctest compatibility: algorithms BASISReduction to CalcMuonDetectorPhases

## Description of work.
This PR is part of refactoring effort to bring Python3 compatibility into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :

## To test.

Code review.

Fixes #20674.
Internal change, no release notes

2017-10-04 14:18 UTC, josephframsay approved these changes
Everything looks good to me, nice change on the `reduce` thing as well

2017-10-04 20:37 UTC, rosswhitfield commented
The `reduce` was addressed in #20778 in a different way, only one fix should be used.

2017-10-05 07:08 UTC, martyngigg requested changes

2017-10-05 07:08 UTC, martyngigg commented on docs/sphinxext/mantiddoc/doctest.py
> +from functools import reduce
I already merged #20778 before seeing this so can we just remove this line now?

2017-10-05 09:15 UTC, martyngigg approved these changes

2017-10-05 09:15 UTC, merged