Python3 doctest compatibility: PoldiCreatePeaksFromFile to PredictFractionalPeaks
mantidproject/mantid pull request #20817
Opened 2017-10-05 14:02 UTC by brandonhewer

Python3 doctest compatibility: algorithms <PoldiCreatePeaksFromFile to PredictFractionalPeaks>

This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
PoldiCreatePeaksFromFile-v1
PoldiDataAnalysis-v1
PoldiFitPeaks1D-v1
PoldiFitPeaks1D-v2
PoldiFitPeaks2D-v1
PoldiIndexKnownCompounds-v1
PoldiLoadRuns-v1
PoldiMerge-v1
PoldiPeakSearch-v1
PoldiPeakSummary-v1
PoldiTruncateData-v1
PolynomialCorrection-v1
Power-v1
PowerLawCorrection-v1
PredictFractionalPeaks-v1
```

Code review.

Fixes #20185.
Internal change, no release notes

2017-10-05 17:54 UTC, rosswhitfield requested changes

2017-10-05 17:54 UTC, rosswhitfield commented on docs/source/algorithms/PoldiFitPeaks2D-v1.rst
> +    print("Refined lattice parameter a = {:.5} +/- {}".format(cell_a, cell_a_error))
This should be `{:.6}`

2017-10-06 09:23 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:05 UTC, rosswhitfield approved these changes

2017-10-06 14:44 UTC, merged