Python3 doctest compatibility: RemoveBackground to ResizeRectangularDetector
mantidproject/mantid pull request #20819
Opened 2017-10-05 14:22 UTC by brandonhewer

Python3 doctest compatibility: algorithms <RemoveBackground  to ResizeRectangularDetector>

## Description of work.
This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
RemoveBackground-v1
RemoveBins-v1
RemoveExpDecay-v1
RemoveLogs-v1
RemoveMaskedSpectra-v1
RemovePromptPulse-v1
RemoveWorkspaceHistory-v1
RenameLog-v1
RenameWorkspace-v1
RenameWorkspaces-v1
ReplaceSpecialValues-v1
ReplicateMD-v1
ResNorm-v1
ResNorm-v2
ResizeRectangularDetector-v1
``

Code review.

Fixes #20818.
Internal change, no release notes

2017-10-05 17:59 UTC, rosswhitfield requested changes

2017-10-05 17:59 UTC, rosswhitfield commented on docs/source/algorithms/RemoveBackground-v1.rst
>     for i in xrange(0,20):
Should be `range` not `xrange`

2017-10-05 17:59 UTC, rosswhitfield commented on docs/source/algorithms/RenameWorkspace-v1.rst
>     print "*********************************************************************"
You missed some `print` statements

2017-10-05 17:59 UTC, rosswhitfield commented on docs/source/algorithms/ReplaceSpecialValues-v1.rst
> +    print("{0}\t{1:.1f}".format(wsYArray[0], ws.readY(0)[0]))
I get different precision here for python 3
```
Expected:
    Before                After
    9.99999993923e-09   0.0
Got:
    Before		 After
    9.99999993922529e-09	0.0
```

2017-10-06 09:24 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:08 UTC, rosswhitfield approved these changes

2017-10-06 14:58 UTC, merged