Python3 doctest compatibility: PaddingAndApodization to PoldiCreatePeaksFromCell
mantidproject/mantid pull request #20812
Opened 2017-10-05 13:34 UTC by brandonhewer

Python3 doctest compatibility: algorithms <PaddingAndApodization  to PoldiCreatePeaksFromCell>

## Description of work.
This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
PaddingAndApodization-v1
Pause-v1
PawleyFit-v1
PeakIntensityVsRadius-v1
PeaksInRegion-v1
PeaksOnSurface-v1
PerformIndexOperations-v1
PhaseQuad-v1
PlotAsymmetryByLogValue-v1
PlotPeakByLogValue-v1
Plus-v1
PoissonErrors-v1
PoldiAnalyseResiduals-v1
PoldiAutoCorrelation-v5
PoldiCreatePeaksFromCell-v1
```

Code review.

Fixes #20811.
Internal change, no release notes

2017-10-05 17:18 UTC, rosswhitfield requested changes

2017-10-05 17:18 UTC, rosswhitfield commented on docs/source/algorithms/Plus-v1.rst
> +    print("The updated Error values are: " + str(ws.readE(0)))
There are more `print` statements in this file that need to be fixed.

2017-10-05 17:18 UTC, rosswhitfield commented on docs/source/algorithms/PlotAsymmetryByLogValue-v1.rst
> +   print("X values (sample magn. field): {}".format(ws.readX(0)))
There are more `print` statements in this file that need to be fixed.

2017-10-05 17:18 UTC, rosswhitfield commented on docs/source/algorithms/PeaksInRegion-v1.rst
> +   print(just_intesecting_box_table.row(0))
These are printing a `dict` and the order is not guaranteed for python 3

2017-10-05 17:18 UTC, rosswhitfield commented on docs/source/algorithms/PeaksOnSurface-v1.rst
> +   print(tbl.row(0))
Again these are printing a `dict` and the order is not guaranteed for python 3

2017-10-06 09:50 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:03 UTC, rosswhitfield approved these changes

2017-10-06 14:43 UTC, merged