Python3 doctest compatibility: SaveIsawPeaks to SavePAR
mantidproject/mantid pull request #20826
Opened 2017-10-05 15:32 UTC by brandonhewer

Python3 doctest compatibility: algorithms <SaveIsawPeaks to SavePAR>

## Description of work.
This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
SaveIsawPeaks-v1
SaveIsawUB-v1
SaveLauenorm-v1
SaveMD-v1
SaveMD-v2
SaveMDWorkspaceToVTK-v1
SaveMask-v1
SaveNISTDAT-v1
SaveNXSPE-v1
SaveNXTomo-v1
SaveNXcanSAS-v1
SaveNexus-v1
SaveNexusProcessed-v1
SaveOpenGenieAscii-v1
SavePAR-v1
```

Code review.

Fixes #20825 .
Internal change, no release notes

2017-10-05 18:21 UTC, rosswhitfield requested changes
Need to use `range` not `xrange` in `SaveNXSPE`

There are some `print` statements that need to be changed in `SaveOpenGenieAscii,SaveNexusProcessed`

2017-10-06 08:19 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 08:51 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:14 UTC, rosswhitfield approved these changes

2017-10-06 14:48 UTC, merged