Python3 doctest compatibility: SavePDFGui to ScaleX
mantidproject/mantid pull request #20828
Opened 2017-10-05 15:52 UTC by brandonhewer

Python3 doctest compatibility: algorithms <SavePDFGui to ScaleX>

## Description of work.
This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
SavePDFGui-v1
SavePHX-v1
SaveParameterFile-v1
SavePlot1D-v1
SavePlot1DAsJson-v1
SaveRKH-v1
SaveSESANS-v1
SaveSPE-v1
SaveTBL-v1
SaveToSNSHistogramNexus-v1
SaveVulcanGSS-v1
SaveYDA-v1
SaveZODS-v1
Scale-v1
ScaleX-v1
```

Code review.

Fixes #20827 .
Internal change, no release notes

2017-10-05 18:29 UTC, rosswhitfield requested changes

2017-10-05 18:29 UTC, rosswhitfield commented on docs/source/algorithms/SaveVulcanGSS-v1.rst
>    for i in xrange(11):
Should be `range` not `xrange`

2017-10-05 18:29 UTC, rosswhitfield commented on docs/source/algorithms/SaveYDA-v1.rst
> +            print(f.readline())
This change leads to additional new line being printed.

2017-10-06 07:54 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:16 UTC, rosswhitfield approved these changes

2017-10-06 14:23 UTC, merged