Python3 doctest compatibility: RetrieveRunInfo to SaveAscii-v2
mantidproject/mantid pull request #20821
Opened 2017-10-05 14:45 UTC by brandonhewer

Python3 doctest compatibility: algorithms <RetrieveRunInfo  to SaveAscii-v2>

## Description of work.
This PR is part of refactoring effort to bring Python3 compatiblity into the doctests.
See https://github.com/mantidproject/mantid/issues/20672 for details.

The following tests were refactored to be compatible :
```
RetrieveRunInfo-v1
RingProfile-v1
RotateInstrumentComponent-v1
RotateSource-v1
RunPythonScript-v1
SANSBeamFluxCorrection-v1
SANSConvertToWavelengthAndRebin-v1
SANSDarkRunBackgroundCorrection-v1
SANSFitShiftScale-v1
SANSStitch-v1
SANSWideAngleCorrection-v1
SCDCalibratePanels-v1
SassenaFFT-v1
SaveANSTOAscii-v1
SaveAscii-v2
```

Code review.

Fixes #20820 .
Internal change, no release notes

2017-10-05 18:09 UTC, rosswhitfield requested changes
There are also some `print` statements in `SANSBeamFluxCorrection, SCDCalibratePanels` that need to be fixed.

2017-10-05 18:09 UTC, rosswhitfield commented on docs/source/algorithms/RotateInstrumentComponent-v1.rst
> +  print('The non-zero difference {} is due to detector {}'.format(diff[32], ws.getDetector(32).getID()))
I get different precision for python 3
```
Expected:
    The non-zero difference -0.0464531276188 is due to detector 33
Got:
    The non-zero difference -0.046453127618849614 is due to detector 33
```

2017-10-05 18:09 UTC, rosswhitfield commented on docs/source/algorithms/SassenaFFT-v1.rst
> +    print('workspaces instantiated:  {}.format(', '.join(ws.getNames()))
You're missing a `'`

2017-10-06 08:52 UTC, josephframsay commented
Brandon asked me to take over these PRs as he's not here until 16th

2017-10-06 13:12 UTC, rosswhitfield approved these changes

2017-10-06 14:49 UTC, merged