Indirect - Elwin - Add check in case of invalid value within IPF file
mantidproject/mantid pull request #20922
Opened 2017-10-16 10:36 UTC by brandonhewer

In the Elwin interface (Elwin.cpp), it is possible to crash Mantid, when there is an attempt to load an IPF file which contains an invalid value.

This PR adds a check for when this condition occurs and provides a warning message to the user.

**To test:**

Fixes #20858. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-18 11:55 UTC, soininen requested changes

2017-10-18 11:55 UTC, soininen commented on qt/scientific_interfaces/Indirect/Elwin.cpp
> +      if (params.size() > 0) {
Please use `if (!params.empty())` instead. It conveys the intention better.

2017-10-18 12:01 UTC, soininen commented
Could there be a test file attached to this pull request so it could be tested?

2017-10-30 10:50 UTC, soininen commented
@brandonhewer I couldn't make vanilla Mantid 'master' to crash with the test files provided. The interface seems to work just fine. What am I supposed to see when these changes are not applied?

2017-11-24 11:30 UTC, mantid-builder commented
have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-02-27 16:48 UTC, NickDraper commented
@brandonhewer This appears to be stuck with you

2018-03-01 17:22 UTC, brandonhewer commented
This PR adds a simple check, currently I've been unable to reproduce the issue with the file I supplied.
This PR shouldn't break any existing code (please see the diff) and it may be best to check it works with the supplied test.

2018-03-01 17:27 UTC, Anders-Markvardsen approved these changes
The code adds an extra null pointer check. Bug can't been reproduced from this branch and previous test suggest can't easily do this with older version, but this extra change provides an extra safety and therefore approve

2018-03-02 09:01 UTC, soininen approved these changes

2018-03-02 18:44 UTC, merged