Adjust MonitorEfficiencyCorUser for other instruments
mantidproject/mantid pull request #20930
Opened 2017-10-16 16:59 UTC by mganeva

This PR removes restriction to TOFTOF instrument and modifies algorithm to read the name of the 'monitor counts' sample log from the instrument parameter file.

This makes possible to use `MonitorEfficiencyCorUser` for other instruments.

**To test:**

Fixes #20924. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-26 10:05 UTC, soininen requested changes

2017-10-26 10:05 UTC, soininen commented on Framework/Algorithms/src/MonitorEfficiencyCorUser.cpp
> +  Strings::convert(m_inputWS->run().getProperty(mon_counts_log)->value(),
This looks awfully complicated. Have you tried using
```c++
m_monitorCounts = m_inputWS->run().getPropertyValueAsType<double>(mon_counts_log);
```
If the above works, you could make similar changes to the other similar cases within this algorithm.

2017-10-26 10:05 UTC, soininen commented on docs/source/algorithms/MonitorEfficiencyCorUser-v1.rst
> +- A formula named "formula\_eff" must be defined in the instrument parameters file. For TOFTOF and DNS instruments it is defined as :math:`M*\sqrt{\frac{E_i}{25.3}}`. The incident energy :math:`E_i`
May I suggest removing the '*' from the efficiency formula? Or try something like '\cdot' if you really want to show a multiplication operator there.

2017-10-30 09:35 UTC, soininen commented
@mganeva The test script provided with the PR doesn't run with the latest changes anymore. I think you should switch back to `int` type as the monitor counts log. With the changes in this diff:
[MonitorEfficiencyCorUser-int-monitor-log.diff.zip](https://github.com/mantidproject/mantid/files/1426671/MonitorEfficiencyCorUser-int-monitor-log.diff.zip) things seems to be working. Maybe you could have a look?

2017-11-16 15:24 UTC, mganeva commented
@soininen Sorry for delay. If I will get back to int, `MonitorEfficiencyCorUser` will get in trouble with workspaces processed by `MergeRuns`. I decided to make monitor counts float also for DNS. 

Now the example script should work.

2017-11-17 14:54 UTC, soininen approved these changes

2017-11-17 15:33 UTC, soininen commented
The test script seems to run now without problems.

2017-11-20 08:17 UTC, merged