Fix Cppcheck warnings
mantidproject/mantid pull request #20947
Opened 2017-10-17 17:27 UTC by AndreiSavici

**To test:**
Code review and builds should pass

Fixes #20946. 

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-18 14:42 UTC, quantumsteve approved these changes

2017-10-18 14:43 UTC, peterfpeterson requested changes

2017-10-18 14:43 UTC, peterfpeterson commented on Framework/Algorithms/src/RemovePromptPulse.cpp
> -  DataObjects::EventWorkspace_const_sptr eventWksp =
The old implementation has a mistake in it, but the new one ignores the fact that `EventWorkspace` can have events outside of the binned range. That is what this was supposed to handle. I think changing line 69 to
```
const bool isEvent = bool(eventWksp);
```
would fix it.

2017-10-18 14:43 UTC, peterfpeterson commented on Framework/DataHandling/src/LoadRawHelper.cpp
> -  bool bExclude;
New code is much better

2017-10-18 16:14 UTC, peterfpeterson requested changes

2017-10-18 16:14 UTC, peterfpeterson commented on Framework/Algorithms/src/RemovePromptPulse.cpp
> +  if (eventWksp == nullptr) {
You want to switch the body of the `if`/`else`

2017-10-18 17:06 UTC, peterfpeterson approved these changes

2017-10-19 12:43 UTC, peterfpeterson approved these changes

2017-10-20 05:27 UTC, merged