Indirect - MSDFit Interface - Add Plot Guess feature
mantidproject/mantid pull request #20981
Opened 2017-10-20 11:03 UTC by brandonhewer

Currently in the MSDFit interface, there is no Plot Guess feature (as seen in the other Indirect Data Analysis Fit Interfaces).

This PR adds the plot guess feature to the MSDFit interface.

**To test:**
1. Navigate to Interfaces > Indirect > Data Analysis > MSDFit
2. Supply the provided file in the Input field.
3. For each model in the Model Input drop-down menu:
    1. Select the model in the Model Input drop-down menu.
    2. Check the Plot Guess checkbox.
    3. Ensure the guess is plotted (green plot) in the top preview plot.
    4. Move the blue fit selectors in the top preview plot and ensure the guess plot is updated.

Fixes #20975 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-11-03 10:34 UTC, gvardany requested changes
Tested with MSDFit, plot guess appears on the preview. Few minor oversights in the code, made some inline comments on some lines, but there are not exhaustive, so please look over:
- `const` consistency is not preserved
- doxygen documentation is missing for some methods

Also, these interfaces have a documentation page: http://docs.mantidproject.org/nightly/interfaces/Indirect%20Data%20Analysis.html#msd-fit 
One could add a statement about the new feature.

The main problem appears when adjusting the fitting range (the blue lines), when I brought them too close, I got the error attached, and there is no way out, even if I click continue. Maybe this can be handled in a more friendly manner?

![screen shot 2017-11-03 at 10 46 33](https://user-images.githubusercontent.com/16865759/32369717-8ee41d68-c08a-11e7-890c-e37e0b50edbf.png)

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> +  std::string paramWsName = outputPrefix + "_Parameters";
const?

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> +  bool specOutOfBounds =
const?

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/ConvFit.cpp
> +    bool tieCentres = (m_uiForm.cbFitType->currentIndex() == 2);
const?

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.cpp
> + * analysis tab.
@param ?

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.cpp
> +void IndirectDataAnalysisTab::updatePlot(
missing oxygen for the methods hereafter

2017-11-03 10:34 UTC, gvardany commented on qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.cpp
> +  std::vector<double> dataY = computeOutput(func, dataX);
const

2017-11-03 16:37 UTC, brandonhewer commented
@gvardany Added a check for if the guess has enough data points before plotting - there is no reason to throw an error here - for a small region the guess just won't appear on the plot until you move the range selectors.

2017-11-06 10:36 UTC, gvardany commented
That error is fixed, but when I try to bring the blue lines close after the guess is plotted, I get a similar one, how about this?

![screen shot 2017-11-06 at 11 29 16](https://user-images.githubusercontent.com/16865759/32437113-9879f812-c2e6-11e7-93e9-d7a62a1f396b.png)

2017-11-13 14:36 UTC, brandonhewer commented
@gvardany This error message should no longer appear.

2017-11-13 16:05 UTC, gvardany approved these changes

2017-11-13 17:00 UTC, merged