Re #20991: Updated Reflectometry IDFs.
mantidproject/mantid pull request #20997
Opened 2017-10-23 11:06 UTC by edwardb96

Updated the IDFs for INTER, OFFSPEC, POLREF and SURF.
This also fixes #20991.

**To test:**
TODO

Fixes #20991. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-25 16:34 UTC, gemmaguest commented
Since the INTER IDF contains a breaking change (a change in the log name used for slit gaps) I think we need to version this file in a similar manner to PR #17476, i.e. add it as a new file with a different name and an appropirate `valid-from` date, and revert the original `INTER_Definition.xml` but change its `valid-to` date to the appropriate date. I'm not sure whether we can find out the date the log name changed or whether Max could tell us.

2017-10-27 11:36 UTC, gemmaguest commented
I've added the Science Validation label because we should check with Max that your fixes are ok with him, i.e. the fixes for `ystart` and `TransRunEndOverlap`, and the version dates for the INTER IDF (was there anything else?).

2017-10-30 09:57 UTC, gemmaguest commented
When we test this, we should test reducing INTER runs both before and after the version date, e.g. on the ISIS Reflectometry interface, enter investigation 1620384 (16 Feb 2017) and click Autoreduce - this currently fails due to the changed log name, whereas investigation 1620396 (Dec-2016) works. Both should work after this PR.

2017-10-30 14:24 UTC, NickDraper commented
Note: When this is merged these will be downloaded to users immediately, they will not wait for the next release.

2017-10-30 15:35 UTC, gemmaguest commented
Max said he is fine for these to go live whenever we are ready.

2017-11-10 12:31 UTC, gemmaguest commented
This PR also adds slits for offspec which is part of issue #16218

Scientists are happy with the INTER IDF now but not with the bench rotation for OFFSPEC, so we should hold off merging this for now.

2018-02-16 13:18 UTC, gemmaguest requested changes
Just one minor comment

2018-02-16 13:18 UTC, gemmaguest commented on instrument/INTER_Definition_2017.xml
> +			last-modified="2010-11-04 00:00:00">
We should put a more sensible last-modified date in here. I think this is just for reference so doesn't need to be accurate. Maybe 26 October as that was the last commit date?

2018-02-16 14:26 UTC, gemmaguest commented
I think I made a mistake when I said the old version of the INTER IDF should not be changed. We're making two sets of changes here - the positions, and the log names. The log names need to remain the same to match the older runs, but the other changes should be included in the old IDF, otherwise we'll get different behaviour when using old vs new runs. I therefore think we should change the old IDF to be the same as the new one for everything apart from the slit log names (S1_VG etc), and of course the valid dates. I'll email Max and Becky to check this is what they expect.

2018-03-15 18:14 UTC, gemmaguest commented
@edwardb96 We had some more minor changes to the INTER and SURF IDFs requested today, so I've pushed those changes. Also the doctest was failing again so I'm not sure the last fix was correct. I've reverted it for now and will check it on Monday.

2018-03-21 12:58 UTC, gemmaguest approved these changes
The changes look good and behave as expected :+1:

There are a lot of changes in tests etc. and removal of old versions of our algorithms which no longer work due to the significant changes in the IDFs. Scientists have confirmed that the old algorithms are not in use and have verified the new IDFs.

It might be worth looking at creating replacement system tests for the OFFSPEC tests that have been removed. I think this should be done as a separate PR though because we don't want to hold up these IDF changes any more.

2018-03-21 15:26 UTC, merged