Re #20903 Output both workspaces for both reduction
mantidproject/mantid pull request #21016
Opened 2017-10-24 13:04 UTC by Mantid-Matthew

Description of work.
An error was being thrown when a reduction was performed in reduction mode both from the python script window. 
**To test:**
Run this script
from sans.command_interface.ISISCommandInterface import *
Clean()
UseCompatibilityMode()
LOQ()
MASKFILE = FileFinder.getFullPath('MaskFile.txt')
MaskFile(MASKFILE)
AssignSample('LOQ74044.nxs')
WavRangeReduction(combineDet = 'both')

Fixes #20903. 

**Release Notes** 
Does not need to be in the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-31 12:00 UTC, edwardb96 approved these changes
This is working fine for me. 👍

2017-11-03 10:18 UTC, ianbush requested changes
Just a minor suggestion for tidying up.

2017-11-03 10:18 UTC, ianbush commented on scripts/SANS/sans/command_interface/ISISCommandInterface.py
> +        is_group = is_part_of_reduced_output_workspace_group(state)
This seems to be the same in both branches of the if/else, so why not leave it outside?

2017-11-22 08:29 UTC, ianbush approved these changes

2017-11-22 08:30 UTC, merged