Hyspec si polarization
mantidproject/mantid pull request #21069
Opened 2017-10-27 21:53 UTC by AndreiSavici

New algorithm as part of the workflow for polarized analysis on HYSPEC

**To test:**

Code review. See that the formula implemented is the same as in the documentation

Fixes #21020. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-27 21:58 UTC, AndreiSavici commented
Still needs some release notes

2017-11-09 11:06 UTC, soininen requested changes
In addition to the few style issues, I think the algorithm could be made agnostic of the instrument's reference frame. Also, the common calculations for both histogram and event data could be refactored to separate function(s) to avoid code duplication.

2017-11-14 22:20 UTC, AndreiSavici commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +        "No Ei value has been set or stored within the run information.");
It is already at the beginning of exec() function

2017-11-14 22:21 UTC, AndreiSavici commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +    // get detector info and calculate the in plane angle
what typo? I am missing that

2017-11-14 22:22 UTC, AndreiSavici commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +        std::atan2((detPos - samplePos).X(), (detPos - samplePos).Z());
I like this :)

2017-11-14 22:27 UTC, AndreiSavici commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +      it = wevector.erase(it);
The answer is that I have no idea. The event list might or might not be sorted

2017-11-15 00:20 UTC, AndreiSavici commented on docs/source/algorithms/HyspecScharpfCorrection-v1.rst
> +    \gamma=\arctan2\left(-\frac{k_f}{k_i}\sin\theta, 1-\frac{k_f}{k_i}\cos\theta\right)
It's important that it's arctan2. The `arctan` function is only between plus and minus Pi/2

2017-11-15 09:27 UTC, soininen commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +        "No Ei value has been set or stored within the run information.");
`validateInputs` is called by the automatically generated algorithm dialogs to check if the inputs are OK before permitting the actual execution of the algorithm.

2017-11-15 09:28 UTC, soininen commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +    // get detector info and calculate the in plane angle
I misinterpreted the comment. Sorry for the noise!

2017-11-15 09:31 UTC, soininen commented on docs/source/algorithms/HyspecScharpfCorrection-v1.rst
> +    \gamma=\arctan2\left(-\frac{k_f}{k_i}\sin\theta, 1-\frac{k_f}{k_i}\cos\theta\right)
If you think the users will understand the difference, then I think the current formula is OK.

2017-11-15 09:33 UTC, soininen commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +      it = wevector.erase(it);
Then I guess it's better to leave it like that and optimize it only if it proves to be a performance bottleneck.

2017-11-15 22:24 UTC, AndreiSavici commented on Framework/Algorithms/src/HyspecScharpfCorrection.cpp
> +  if (eventW != nullptr) {
I still keep nullptr for type safety

2017-11-15 22:29 UTC, AndreiSavici commented on docs/source/algorithms/HyspecScharpfCorrection-v1.rst
> +along the momentum transfer  :math:`Q`, perpendicular to it in the horizontal
This looks fine to me

2017-11-16 08:51 UTC, soininen commented on docs/source/algorithms/HyspecScharpfCorrection-v1.rst
> +along the momentum transfer  :math:`Q`, perpendicular to it in the horizontal
I meant to say there is two spaces before :math:. I think it is a typo.

2017-11-16 15:44 UTC, soininen approved these changes

2017-11-16 15:52 UTC, AndreiSavici commented
Minor documentation rendering issues will be fixed separately.

2017-11-16 16:56 UTC, merged