Fix workspace operator when workspaces are not in the ADS
mantidproject/mantid pull request #21080
Opened 2017-10-30 14:15 UTC by soininen

The binary operators (`+`, `-`, `*=`, etc.) did not work if one or both of the operands was not stored in the Analysis data service. This PR fixes the issue.

**To test:**

Play with workspaces both in and out of the ADS and binary operators. The following Python script tests some cases and the single unary operator available in Mantid:
```python
ws = CreateSampleWorkspace(StoreInADS=False)
initialY = ws.readY(0)[0]
ws_ads = CreateSampleWorkspace(StoreInADS=True)
result1 = ws + ws
result2 = ws + ws_ads
result3 = ws_ads + ws
result4 = ws_ads + ws_ads
result5 = ws + 1
result6 = 1 + ws
result7 = ws_ads + 1
result8 = 1 + ws_ads
ws += 1
ws_ads += 1
if ws.readY(0)[0] != initialY + 1 or ws_ads.readY(0)[0] != initialY + 1:
    raise RuntimeError('Operator += did not work.')
mdws = CreateMDHistoWorkspace(SignalInput=[0], ErrorInput=[0], Dimensionality=1, Extents=[0, 1], NumberOfBins=1, Names=['a'], Units=['TOF'], StoreInADS=False)
mdws_ads = CreateMDHistoWorkspace(SignalInput=[0], ErrorInput=[0], Dimensionality=1, Extents=[0, 1], NumberOfBins=1, Names=['a'], Units=['TOF'], StoreInADS=True)
result9 = ~mdws
result10 = ~mdws_ads
```

Fixes #21064.

**Release Notes** 

The Framework's release notes were updated accordingly.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-11-02 06:50 UTC, SimonHeybrock reviewed
Question: Instead of clearing the name in the `clone()` method, would it make (more?) sense to clear it in the copy constructor?

2017-11-02 07:00 UTC, SimonHeybrock requested changes
Are there missing changes to a series `clone()` methods? For example, `EventWorkspace::clone()` does not seem to be refactored for the new behavior? I suspect running the test with, e.g.,` and `EventWorkspace` would fail?

Given that there are many workspace types with `clone()` that would need to be refactored, maybe clearing the name in the `Workspace` copy constructor is the easiest way to go (unless this is breaking something else?)?

Edit: Given that the copy constructor is not public and is used (I think) only for cloning, I think such a change would not break anything.

2017-11-02 07:00 UTC, SimonHeybrock commented on Framework/TestHelpers/inc/MantidTestHelpers/FakeObjects.h
> -  std::unique_ptr<WorkspaceTester> clone() const {
Why are these gone?

2017-11-02 07:00 UTC, SimonHeybrock commented on Framework/PythonInterface/test/python/mantid/api/WorkspaceBinaryOpsTest.py
> +        self.assertTrue(mtd.doesExist('ws_ads'))
Good testing :+1:

2017-11-06 14:10 UTC, soininen commented
@SimonHeybrock The changes to workspace cloning here are only half done, indeed. In addition to changing the cloning behavior of all workspaces, the Python documentation of `clone()` should be updated as well. As the changes to cloning are largish but independent of what this PR is (or should be) about, I think I'll open another issue and PR to handle `clone()`.

2017-11-06 14:12 UTC, SimonHeybrock commented
@soininen My point was rather that I think you can avoid all those changes to `clone()`.

2017-11-06 14:18 UTC, soininen commented
@SimonHeybrock Yes, I'll have a look if I can get away with just changing the copy constructors, as you suggested.

2017-11-06 14:19 UTC, SimonHeybrock commented
@soininen I think you only need to change it for `Workspace`, all derived classes should be unchanged, I think.

2017-11-07 06:13 UTC, SimonHeybrock commented
Changes look good now. Also verified that `CloneWorkspace` still puts a workspace with the requested name into the ADS (it is using `clone()` internally).

2017-11-07 06:13 UTC, SimonHeybrock approved these changes

2017-11-10 16:15 UTC, merged