Use IArchiveSearch more selectively
mantidproject/mantid pull request #21089
Opened 2017-10-31 19:11 UTC by peterfpeterson

Copied and rephrased from the issue:

The value of `datasearch.searcharchive` (case insensitive) will be interpreted differently in `FileFinder`:

* empty string or `off` means don't do archive search
* `on` means search your default facility only
* `all` means search in all facilities
* list of names means search facilities in the list (example is `hfir,sns` will search those and skip `isis`)

**To test:**

Turn logging up to `debug`, set your default facility to `isis` or `sns`, set your `datasearch.searcharchive` to various values, then search for `OSI12345` and `NOM12345`. I don't know if both exist, but you'll see from the logging whether or not it used archive search for the files.

Fixes #20352.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-10-31 19:23 UTC, rosswhitfield requested changes
All this appears to be working correctly!

But can you add the new options to the [ManageUserDirectories](https://www.mantidproject.org/ManageUserDirectories) UI?

At the moment it [will appear to be off while it may still be searching](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/ManageUserDirectories.cpp#L73-L76) and [then be overridden when you close the ManageUserDirectories](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/ManageUserDirectories.cpp#L90-L93)

2017-11-01 14:00 UTC, peterfpeterson commented
I'll change the setting to a drop-down list of "default facility", "all", "off", or the list of facilities (if the user has set it). I'll also fix that populating that bit of the dialog is case sensitive.

2017-11-02 18:42 UTC, rosswhitfield requested changes

2017-11-02 18:42 UTC, rosswhitfield commented on qt/widgets/common/src/ManageUserDirectories.cpp
> +  } else if (newSearchArchive == "none") {
Wouldn't it be easier if the options matched between the ManageUserDirectories UI and the Mantid properties file?

2017-11-02 18:42 UTC, rosswhitfield commented on qt/widgets/common/src/ManageUserDirectories.cpp
> +                               "datasearch.searcharchive"))
You are prepending `"custom - "` to the custom option above which is getting saved, after opening ManageUserDirectories a few time my properties file looks like
```
datasearch.searcharchive=custom - custom - custom - custom - custom - sns
```
😀

2017-11-02 19:15 UTC, rosswhitfield approved these changes

2017-11-03 10:44 UTC, merged