Bug in MultidomainFunction python wrapper
mantidproject/mantid pull request #21105
Opened 2017-11-02 12:36 UTC by mantid-roman

Generic function that creates fit function wrappers for composite functions uses correct arguments now.

**To test:**

Use the script form the issue description. Print out the created fit function to see that the global parameters are tied to each other.

Fixes #21102

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-11-02 15:10 UTC, KarlPalmen commented on Framework/PythonInterface/test/python/mantid/FitFunctionsTest.py
> +
I'd use a more informative test name suffix than ``..._1``, such as ``..._by_name``. There is one more example of this.

2017-11-02 15:29 UTC, AnthonyLim23 commented
the code looks fine and it doesn't crash. However, the ties do not seem to work correctly in MultiDomainFunction (and the wrapper). The following is based on the last example http://docs.mantidproject.org/nightly/algorithms/Fit-v1.html

```
import math
import numpy as np

# create data
xData=np.linspace(start=0,stop=10,num=22)
yData=[]
for x in xData:
    yData.append(2.0*x+10.)
yData2=[]
for x in xData:
    yData2.append(5.0*x+7.)
# create workspaces
input = CreateWorkspace(xData,yData)
input2 = CreateWorkspace(xData,yData2)
# create function
myFunc = LinearBackground()
myFunc2 = LinearBackground()
multiFunc=MultiDomainFunction(myFunc,myFunc2,NumDeriv=1,Global=["A1"])
#multiFunc.tie({'f0.A1' : 'f1.A1'})
# do fit
fit_output = Fit(Function=multiFunc, InputWorkspace=input, WorkspaceIndex=0, \
                 InputWorkspace_1=input2, WorkspaceIndex_1=0, \
                 StartX = 0.1, EndX=9.5, StartX_1 = 0.1, EndX_1=9.5,Output='fit') 
paramTable = fit_output.OutputParameters  # table containing the optimal fit parameters # print results print('Gradients (shared):') print("Gradient 1: {0:.2f}".format(paramTable.column(1)[3]))
print("Gradient 1: {0:.2f}".format(paramTable.column(1)[3]))
print("Gradient 2: {0:.2f}".format(paramTable.column(1)[1]))
print('offsets:')
print("Constant 1: {0:.2f}".format(paramTable.column(1)[0]))
print("Constant 2: {0:.2f}".format(paramTable.column(1)[2]))
```

2017-11-02 16:05 UTC, KarlPalmen requested changes
Change fixes the problem and the result function looks OK.  I'm not happy with the names of the new unit tests and want something more informative, such as the suggestion I made.

If ties don't work in MultiDomainFunction rather than just the wrapper, then this is a different issue, which needs to be found or created.

2017-11-03 15:21 UTC, KarlPalmen approved these changes

2017-11-03 15:48 UTC, AnthonyLim23 requested changes
the code looks good and it all works now. However, the doc should be updated (it currently has global instead of Global)

2017-11-03 16:02 UTC, mantid-roman commented
I would prefer `global`. I'll better change the code.

2017-11-03 16:03 UTC, AnthonyLim23 commented
as long as it is consistent I do not mind

2017-11-03 16:08 UTC, mantid-roman commented
Oops. `global` is a reserved word. :(

2017-11-03 16:12 UTC, AnthonyLim23 approved these changes

2017-11-03 16:16 UTC, KarlPalmen commented
I recall that is the reason chose ``Global`` rather than ``global`` (reserved word in Python).

2017-11-06 09:07 UTC, merged

2017-11-07 14:26 UTC, jmborr commented on Framework/PythonInterface/mantid/fitfunctions.py
> +    def init_paramgeters_and_attributes(self, **kwargs):
is `paramgeters` the intended word in method `init_paramgeters_and_attributes` ?