Update developer package specs for workbench requirements
mantidproject/mantid pull request #21239
Opened 2017-11-22 14:30 UTC by martyngigg

Description of work.

Adds Qt5 plus other workbench requirements to the developer spec file and debian control files.

**To test:**

* Code review

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-11-22 17:33 UTC, peterfpeterson requested changes

2017-11-22 17:33 UTC, peterfpeterson commented on buildconfig/dev-packages/rpm/mantid-developer/mantid-developer.spec
> +Requires: python-QtPy
Missing the python3 version below

2017-11-24 13:36 UTC, peterfpeterson approved these changes

2017-11-27 16:22 UTC, rosswhitfield commented
`qscintilla-qt5-devel`

2017-11-27 17:09 UTC, peterfpeterson commented
I must have had that installed already. This is approved to merge.

2017-11-27 17:09 UTC, rosswhitfield commented
Do we also need `libqt5scintilla2-dev` for Ubuntu?

2017-11-29 08:58 UTC, martyngigg commented
Build failures are unrelated to this changes.

2017-11-30 16:09 UTC, merged