Enabling and disabling reflectometry GUI components
mantidproject/mantid pull request #21254
Opened 2017-11-23 12:58 UTC by gemmaguest

This PR improves functionality to enable/disable GUI components on the `ISIS Reflectometry` interface and `DataProcessorWidget`.

**To test:**

- Check that the following GUIs still operate correctly:
    - `ISIS Reflectometry`
    - `ISIS SANS v2 experimental`
    - `DataProcessorInterface` (can be enabled by adding `Utilities/DataProcessorInterface.py` to `mantidqt.python_interfaces` in `Framework/Properties/Mantid.properties.template`
- Menu items in the toolbar, context menu and main menus are disabled/enabled according to whether processing is in progress. Try processing some runs and check that:
  - The pause button is disabled while idle and enabled while processing. Check that hitting Pause stops reduction.
  - Buttons that do not change reduction settings are always enabled: plotting, group selection, expand/collapse rows (for all interfaces using the DataProcessorWidget). Check that these still work while processing is in progress
  - For  `ISIS Reflectometry`, the save/export options and slit calculator in the Reflectometry menu should always be enabled
  - Other buttons are enabled while idle and disabled while processing
  - The toolbar buttons have the same enabled/disabled state as their counterparts in the context menu (and also the Edit menu for reflectometry - note that this PR doesn't cover enabling/disabling main menu items in the SANS GUI).
  - Double-clicking on a cell in the DataProcessorWidget normally allows you to edit its contents but this should be disabled during processing.

Fixes #21215 

Note that this also adds most of the functionality for #19951 but the problem from that issue of enabling the pause button too soon is not yet fixed.

**Release Notes** 
*To follow*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-11-30 16:47 UTC, edwardb96 requested changes
This seems to be working fine for me. A few code style points to consider.

2017-12-07 12:23 UTC, gemmaguest commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/QtCommandAdapter.h
> +    if (!m_action)
The important thing is whether it's an action or not, so perhaps the comment is not necessary, but I added it to be clear that it's valid for the action to be null

2017-12-07 12:29 UTC, gemmaguest commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/QtCommandAdapter.h
> +    else if (m_adaptee->modifiesRunningProcesses())
Yes, if a command modifies settings it must be disabled during processing, so it wouldn't make sense for it to also modify running processes

2017-12-07 13:11 UTC, gemmaguest commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/QtCommandAdapter.h
> +    }
I didn't, but I think that would actually be less concise/readable than the current code?

2017-12-07 13:30 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/QDataProcessorWidget.cpp
> +  static const auto editTriggers = ui.viewTable->editTriggers();
Yes, it's because we need to revert back to the original value when re-enabling. I'll add a comment to clarify this.

2017-12-08 12:20 UTC, gemmaguest commented on qt/widgets/common/test/DataProcessorUI/GenericDataProcessorPresenterTest.h
> +    // Expect the views' widgets to be set in the paused state
I've done this along with a lot more tidying to reduce duplication in the tests

2017-12-14 10:18 UTC, edwardb96 approved these changes

2017-12-15 12:14 UTC, merged