ISIS Powder improvements for using non-standard grouping files
mantidproject/mantid pull request #21261
Opened 2017-11-24 13:57 UTC by josephframsay

HRPD have a number of non-standard grouping files that they like to use. Doing this makes it reasonably easy to run into errors where there is a mismatch between the numbers of banks in the various inputs. This PR improves the readability of these errors and also enables and also enables dividing by a vanadium spline with only one bank.

**To test:**

As with all `isis_powder` PRs, if you've not set up your directories and config files, give me a poke and I'll give you a hand. Sample data is [here](https://github.com/mantidproject/mantid/files/1501831/HRPD.zip).

Create your HRPD instrument using the attached config file (you'll need to set the paths in it to suit your setup)

```
from isis_powder import HRPD
hrpd = HRPD(config_file=r"path/to/hrpd_config.yaml")
```
First, create your vanadium and do a focus normally. This should give you no errors, the output workspaces should have nice sharp peaks
```
hrpd.create_vanadium(first_cycle_run_no=68236, window="10-110")
hrpd.focus(run_number=68245, window="10-110")
```
Put `hrpd_new_072_01_corr_simm_left3_test.cal` (attached) in your calibration directory, and then try and do a focus using it:
```
hrpd.focus(run_number=68245, window="10-110",
           grouping_file_name="hrpd_new_072_01_corr_simm_left3_test.cal")
```
You should get:
```
RuntimeError: Mismatch between number of banks in vanadium and number of banks in workspace to focus
There are 3 banks for vanadium but 1 for the run
```
Now try creating your vanadium with the new grouping file and focusing with the correct number of cropping values and bin widths:
```
hrpd.create_vanadium(first_cycle_run_no=68236, window="10-110",
               grouping_file_name="hrpd_new_072_01_corr_simm_left3_test.cal")
hrpd.focus(run_number=68245, window="10-110", focused_cropping_values=[(0, 1e6)], focused_bin_widths=[-0.005]
```
This should not throw any errors, and you should again get nicely defined peaks

Fixes #21259 

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/commit/7c5cec855bbf9d5aa71ea32e02da31a22ac64f34)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-01-15 13:49 UTC, samueljackson92 requested changes

2018-01-15 13:49 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/common.py
> +                                                                                   ))
We're calling `len` 4 times here but we could do in in 2 if we cached the length.

2018-01-15 13:49 UTC, samueljackson92 commented on docs/source/release/v3.12.0/diffraction.rst
> +- Some usability improvements for using non-standard grouping files in ISIS_Powder
What usability improvements?

2018-01-15 13:49 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/focus.py
> +    common.remove_intermediate_workspace(rebinned_spline)
Can we use `StoreInADS=False` instead?

2018-01-15 13:49 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/focus.py
> +        for data_ws, van_ws in zip(spectra_list, vanadium_splines):
Perhaps:

```python
output_list = map(_divide_one_spectrum_by_spline, zip(spectra_list, vanadium_splines))
```

2018-01-15 13:49 UTC, samueljackson92 commented on scripts/Diffraction/isis_powder/routines/focus.py
> +                                                                                             len(spectra_list)))
`len` used twice here as well.

2018-01-15 17:19 UTC, samueljackson92 approved these changes

2018-01-16 08:43 UTC, martyngigg commented
@josephframsay There are some failing system tests.

2018-01-17 08:35 UTC, merged