WIP: Notify GDPP on Settings Change
mantidproject/mantid pull request #21299
Opened 2017-11-30 15:19 UTC by edwardb96

Description of work.

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-01-16 10:08 UTC, gemmaguest requested changes
The changes look good, but I think there is an error in setting the processed state of rows in the two level tree - see inline comments

2018-01-16 10:08 UTC, gemmaguest commented on qt/widgets/common/src/DataProcessorUI/TwoLevelTreeManager.cpp
> +  }
I think this needs to loop through the group/row hierarchy in a similar way to [here](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/DataProcessorUI/QTwoLevelTreeModel.cpp#L221)

2018-01-16 13:26 UTC, gemmaguest commented
The changes look good now and the reflectometry GUI works as expected. Rows are reprocessed when settings/data change but not otherwise.

There seems to be a problem on the SANS GUI - if you load the maskfile and batch file from the sample data and tick `PlotResults`, then the workspaces are created ok but the plot window does not show any graphs.

2018-01-16 16:05 UTC, gemmaguest commented
The SANS GUI seems to be working fine now. Changes to the settings on the runs tab or the settings tab seem to be picked up ok. Therefore all looks good to me :+1:

2018-01-16 16:05 UTC, gemmaguest approved these changes

2018-01-17 08:33 UTC, martyngigg commented
@edwardb96 It looks like there are some conflicts after #21343 was merged.

2018-01-17 13:58 UTC, merged