Refs # Added condition and little test
mantidproject/mantid pull request #21332
Opened 2017-12-04 16:49 UTC by jmborr

- Included a condition to check if property is enabled
- unit test

**To test:**
Run the following:
```
print(BASISReduction)
```

Fixes #21321

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-12-04 21:20 UTC, peterfpeterson approved these changes
It works as advertised.

2017-12-04 22:15 UTC, quantumsteve requested changes
Needs a little cleanup before being merged.

2017-12-04 22:15 UTC, quantumsteve commented on Framework/Kernel/src/PropertyManager.cpp
>      Property *p = getPointerToPropertyOrdinal(static_cast<int>(i));
(linting issue) Given that `getPointerToPropertyOrdinal` accepts an `int`, shouldn't the loop variable type be `int` and `count` be cast outside of the loop?

2017-12-05 20:21 UTC, quantumsteve approved these changes

2017-12-05 20:21 UTC, merged

2017-12-05 20:23 UTC, jmborr commented
@peterfpeterson @quantumsteve :zap: thanks! :zap: