Engineering Diffraction GUI allow runs to be removed from the fitting list
mantidproject/mantid pull request #21376
Opened 2017-12-07 10:48 UTC by josephframsay

The ability to remove runs from the list widget (and the model) was added to the ED GUI. Users can now discard runs they're not interested in before doing **Fit All**.

**To test:**

Make sure `EnggDiffFittingModelTest` and `EnggDiffFittingPresenterTest` pass locally.

Some sample data is [here](https://github.com/mantidproject/mantid/files/1460806/ENGINX_focused_runs.zip).

Load up the ED GUI and go to the **Fitting** tab.

Load at least 2 of the runs from the attached zip file. Select one, and click **Remove run**. The run should disappear from the list widget, and the corresponding workspace should no longer appear in the workspaces area.

Fixes #21365 

**Release Notes** 
Doesn't need to be in the release notes, as is quite a minor (and obviously necessary) part of the larger work to enable multirun fitting

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-12-08 15:19 UTC, brandonhewer requested changes
Only a few small changes to the code quality, everything else appears very well written.

2017-12-08 15:19 UTC, brandonhewer commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingViewQtWidget.cpp
> +  });
What is the reason for using for_each here?

Would it be more clear to use -
```
for(const auto &rowLabel : rows)
  this->addRunNoItem(rowLabel)
```

2017-12-08 15:34 UTC, josephframsay commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingModel.cpp
> +    const auto name = getFromRunMap(runNumber, bank, map)->getName();
I'm not sure gmock will let you mock methods that return a reference - do you know if this is the case?

2017-12-08 15:59 UTC, brandonhewer commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingModel.cpp
> +    const auto name = getFromRunMap(runNumber, bank, map)->getName();
Why would there be an issue with mocking methods which return a reference?

2017-12-11 10:46 UTC, josephframsay commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingModel.cpp
> +    const auto name = getFromRunMap(runNumber, bank, map)->getName();
Oh no, it does let you do it. However I'm still not a big fan of this change.

It seems confusing to have `getWorkspaceFilename` but not any of the other methods which use `getFromRunMap` return a const reference, and I think having the ones which return workspaces return a const reference to a shared pointer is too much indirection. I seem to remember "don't return references" being the first thing anyone tells you about C++.

I also don't really see the need for it - the methods aren't used often enough to have a significant effect on performance, and the values in RunMaps can't be changed from outside `EnggDiffFittingModel` anyway.

2017-12-12 11:41 UTC, brandonhewer approved these changes

2017-12-12 11:42 UTC, brandonhewer commented
Manual test produced the expected output and unit tests ran successfully.

2017-12-13 08:00 UTC, merged