Add Python 3 packages debian developer package
mantidproject/mantid pull request #21433
Opened 2017-12-14 09:26 UTC by martyngigg

Description of work.

Tidies up the control file and adds required Python 3 packages.

**To test:**

* Check the list
* On a Debian/Ubuntu machine switch to the  `buildconfig/dev-packages/deb/mantid-developer` directory and run `equivs-build ns-control` (you may need to install `equivs`).
* You can simulate installing the new package with `gdebi --apt-line mantid-developer_1.3.2_all.deb`

*No issue*

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2017-12-14 15:01 UTC, rosswhitfield approved these changes
LGTM I checked the package on Ubuntu 14.04 and 16.04

2017-12-15 19:15 UTC, AndreiSavici commented on buildconfig/dev-packages/deb/mantid-developer/ns-control
> +  python3-numpy,
Add `python3-mock`

2017-12-15 19:15 UTC, AndreiSavici requested changes
need python3-mock

2017-12-18 08:09 UTC, martyngigg commented
Thanks, @AndreiSavici I've added that now.

2017-12-18 15:06 UTC, AndreiSavici approved these changes

2017-12-19 07:16 UTC, SimonHeybrock commented
Build failure is unrelated, merging.

2017-12-19 07:17 UTC, merged