Add diagnostics tab to sans gui
mantidproject/mantid pull request #21478
Opened 2017-12-20 17:53 UTC by Mantid-Matthew

Description of work.
This is currently blocked by the need to update the back-end algorithm to support more instruments. 
**To test:**

Fixes #21404 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-05 15:34 UTC, soininen requested changes
Tested the new tab in the interface by following the provided instructions. Seemed to work fine, expect I couldn't compare the resulting plot to anything. Anyhow, the code changes look good to me, as well. I found just a few minor issues here and there.

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/common/general_functions.py
> +                             "value {1}. Make sure that this is not the case.")
Formatting is missing the actual call to `.format()`.

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/common/general_functions.py
> +                             "value {1}. Make sure that this is not the case.")
Missing `format()`?

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/common/general_functions.py
> +                             "value {1}. Make sure that this is not the case.")
Missing `format()`?

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/gui_logic/models/diagnostics_page_model.py
> +    for range in ranges:
`range` is a built-in function and being shadowed here. Actually, it seems to be shadowed in a lot of places below.

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/gui_logic/presenter/diagnostic_presenter.py
> +        range = self._view.horizontal_range
`range` is a built-in.

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/gui_logic/presenter/diagnostic_presenter.py
> +        file = self._view.run_input
`file` is a built-in function.

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
> +            #self._setup_instrument_specific_settings()
Commented-out code?

2018-02-05 15:34 UTC, soininen commented on scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
> +        # self._setup_instrument_specific_settings()
Commented out code?

2018-02-05 15:34 UTC, soininen commented on scripts/test/SANS/gui_logic/diagnostics_page_model_test.py
> +if sys.version_info.major == 3:
Would `sys.version_info.major > 2` be more forward compatible?

2018-02-05 15:34 UTC, soininen commented on scripts/test/SANS/gui_logic/diagnostics_page_presenter_test.py
> +if sys.version_info.major == 3:
Test `sys.version_info.major > 2`?

2018-02-13 10:34 UTC, soininen commented
@Mantid-Matthew The failing RHEL7 system test might be connected to these changes. Could you have a look?

2018-02-14 08:18 UTC, soininen commented
@Mantid-Matthew The issue of commented-out line of code in `run_tab_presenter.py` still remains unresolved. Is there a reason to keep the line?

2018-02-14 09:49 UTC, Mantid-Matthew commented
No I just managed to overlook the second of both the commented code and system comments. Thanks for spotting that.

2018-02-14 15:13 UTC, soininen commented
@Mantid-Matthew Sorry for not noting this before, but how about release notes? Is there any other user facing documentation that needs to be updated?

2018-02-14 15:40 UTC, Mantid-Matthew commented
No worries yes there should be some release notes and probably some sphinx documentation as well. Now you have reminded me this https://github.com/mantidproject/mantid/blob/master/docs/source/interfaces/ISIS%20SANS%20v2.rst needs updating to reflect the changes.

2018-02-27 10:11 UTC, Mantid-Matthew commented
@soininen Documentation now added.

2018-02-28 14:26 UTC, soininen approved these changes

2018-03-01 10:49 UTC, merged

2018-03-01 10:50 UTC, martyngigg commented
The failing Vesuvio tests are a known issue and they are unrelated to this issue.