Refactor QWorkspaceDockView
mantidproject/mantid pull request #21491
Opened 2018-01-02 11:03 UTC by ElliotAOram

This PR covers the refactoring of the `QWorkspaceDockView` to a `QWorkspaceWidget`. This is now a self contained Widget which is not stored within a DockWidget. It no longer has reliance on it's parent class.

Additionally, `MantidUI` and has been updated to hold a QDockWidget container for the QWorkspaceWidget.

Finally the class name has been changed (as have references to this class elsewhere in the code base).

**To test:**

* Code review 

* Open `MantidPlot`
* Observe that the WorkspaceWindow is the same as it was before.
  * Check that it can still be docked and undocked
  * Check the buttons still work as expected
  * Check size limits

Fixes #21461 

**Release Notes** 
*Internal change not required in release notes*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-01-02 14:13 UTC, martyngigg requested changes

2018-01-02 14:13 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/MantidTreeWidget.h
> +  MantidTreeWidget(QWorkspaceWidget *w, MantidDisplayBase *mui);
This should follow the more standard pattern for a widget constructor as

```
MantidTreeWidget(MantidDisplayBase *mui, QWidget *parent=nullptr);
```

2018-01-02 14:13 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/MantidTreeWidget.h
> +  QWorkspaceWidget *m_dockWidget;
It looks as if this is not used anywhere and can be removed, which is good as this dependency shouldn't need to exist.

2018-01-02 14:13 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/QWorkspaceDockView.h
> +    : public QWidget,
It looks like this has been left behind by accident after the rename.

2018-01-02 14:13 UTC, martyngigg commented on qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/QWorkspaceDockView.h
> +                              QWidget *parent = 0);
Please use `= nullptr` rather than `= 0`

2018-01-02 14:13 UTC, martyngigg commented on MantidPlot/src/Mantid/MantidUI.cpp
> +  m_exploreMantid = boost::make_shared<QWorkspaceWidget>(this);
I don't think we need to manage this with a `shared_ptr`. None of the other widgets here do that. The Qt parent/child relationship should handle the clean up.

2018-01-03 09:45 UTC, martyngigg commented on qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
> +             dynamic_cast<QWidget *>(this->parent()),
You could use [`parentWidget`](http://doc.qt.io/archives/qt-4.8/qwidget.html#parentWidget) instead here to avoid the `dynamic_cast`.

2018-01-03 09:54 UTC, martyngigg commented on qt/widgets/common/src/MantidTreeWidget.cpp
> +    : m_mantidUI(mui),
I think this line should now read: ` QTreeWidget(parent), m_mantidUI(mui),` as I'm getting a compiler warning about not using `parent`.

2018-01-03 11:30 UTC, ElliotAOram commented
@martyngigg that should fix the drop down menu and `Ctrl+Shift+M` issue now. Still at a bit of a loss on the name currently though. Might be worth coming back to this in a maintenance period? possible others I've considered are `WorkspaceStorageWidget`, `ADSInterfaceWidget`, or maybe even simply `WorkspaceWidget`?

2018-01-03 13:06 UTC, martyngigg approved these changes
I'm happy with this now. The functionality is unchanged in MantidPlot but the widget can now be reused elsewhere.

2018-01-04 04:35 UTC, merged