Modify SliceViewer to add support for sorting by I/sigma
mantidproject/mantid pull request #21511
Opened 2018-01-08 11:10 UTC by samueljackson92

These changes allow the user to sort by the  I/sigma column in the SliceViewer and any other column that was previously disabled.

**To test:**

Some data for testing can be found under Scratch/Sam. The MD workspace is md.nxs, the peaks workspace is satellite_refined.nxs.

 - Load an MD workspace
 - Load a peaks workspace
 - Right click -> Open the slice viewer on the MD workspace
 - Overlay peaks workspace on the slice viewer
 - Sort by the I/sigma column.

Also check that you can add/erase peaks and click rows to zoom to a peak and that this a) does not crash mantid and b) does the correct thing (i.e. the sort order does not break these features).

Fixes #20441

**Release Notes** 
(See here)[]

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-01-09 21:39 UTC, quantumsteve requested changes
Loaded a MDWorkspace and PeaksWorkspace in the Slice Viewer without issues. Sorting mostly worked as expected and removing a column didn't crash Mantid.

Does the current sorting of Qsample or Qlab make sense? Sorting by the norm of vector may be more useful.

See inline comments from code review.

2018-01-09 22:18 UTC, quantumsteve commented on Framework/DataObjects/src/Peak.cpp
> +  if (m_sigmaIntensity == 0)
Checking for division by zero makes sense, but is the check sufficient? Would we be better off using [std::isinf](http://en.cppreference.com/w/cpp/numeric/math/isinf) on the result?

2018-01-10 12:59 UTC, samueljackson92 commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +      },
But `v3dAsString` would have a different type signature because `&IPeak::get*` is a member function and `v3dAsString` isn't?

2018-01-10 16:50 UTC, quantumsteve commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +      },
Oops, looks like lambdas don't capture functions by default. I did verify that one could write a free function that uses another free function and append that function pointer, but that is almost certainly hurts clarity.

2018-01-10 16:54 UTC, samueljackson92 commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +      },
>I did verify that one could write a free function that uses another free function and append that function pointer, but that is almost certainly hurts clarity.

Would you care to share the code anyway? 😄  Just to help better my C++ knowledge?

2018-01-10 17:01 UTC, quantumsteve commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +      },
[patch.txt](https://github.com/mantidproject/mantid/files/1619738/patch.txt)

2018-01-10 17:10 UTC, samueljackson92 commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +      },
Oh I see. I thought you meant make the creation of `m_dataLookup` something along the lines of the following:
```c++
m_dataLookup = {
    &IPeak::getTOF,
    &IPeak::getRow,
...
    &qLabAsVariant
}
```

Hence my confusion. My bad.

2018-01-10 21:09 UTC, quantumsteve commented
I'm now getting a `std::bad_alloc` exception when overlaying the peaks workspace.

2018-01-10 21:16 UTC, quantumsteve commented on qt/widgets/sliceviewer/inc/MantidQtWidgets/SliceViewer/QPeaksTableModel.h
> +  std::vector<std::function<QVariant(const Mantid::Geometry::IPeak &)>>
Does changing this to `std::vector<QVariant(*)(const MantidGeometry::IPeak &)>` work?

2018-01-10 22:01 UTC, quantumsteve commented on qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
> +        return QString::number(peak.getL(), 'f', hklPrec);
Don't capture a temporary by reference! Capture `hklPrec` or `m_hklPrec` by value.

2018-01-12 15:21 UTC, quantumsteve approved these changes

2018-01-15 08:03 UTC, merged