New polarization correction algorithm for reflectometers
mantidproject/mantid pull request #21579
Opened 2018-01-18 09:40 UTC by soininen

This PR introduces new `PolarizationEfficiencyCor` algorithm for reflectometrer polarization analysis. The polarization corrections are based on [A. R. Wildes (2006), Neutron News, 17:2, 17-25].

**To test:**

Scientific validation will be done by scientists at ILL. For the purpose of this PR, try to break the algorithm. The following script could serve as a basis for testing:
```python
# The unit test data dir has to be in Mantid's data search directories.
ws00 = CreateSampleWorkspace(
    Function='Quasielastic',
    NumBanks=1,
    BankPixelWidth=1,
    XUnit='Wavelength',
    XMin=0.1,
    XMax=10.,
    BinWidth=0.1
)
ws01 = CloneWorkspace(ws00)
ws10 = CloneWorkspace(ws00)
ws11 = CloneWorkspace(ws00)

factors = LoadILLPolarizationFactors(
    Filename='ILL/D17/PolarizationFactors.txt',
    WavelengthReference=ws00
)

PolarizationEfficiencyCor(
    Inputworkspaces='ws00, ws01, ws10, ws11',
    OutputWorkspace='corr',
    Efficiencies=factors,
    Flippers='00, 01, 10, 11'
)
```

Fixes #20962.

**Release Notes** 

A note was added to the reflectometry release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-06 12:42 UTC, gemmaguest requested changes
The changes look good and behave as described. I haven't managed to break the algorithm. Gives sensible errors with:
- missing/invalid workspaces
- mismatched sizes or X values for the input workspaces 
- mismatched X values or missing labels in the factors workspace
- an invalid flippers string
- mismatch between number of flippers and input workspaces
:+1:

Just a few minor in-line queries.

2018-02-06 12:42 UTC, gemmaguest commented on Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
> +  // TODO check if history is retained with create().
Is this `TODO` left in intentionally?

2018-02-06 12:42 UTC, gemmaguest commented on Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
> +PolarizationEfficiencyCor::fullCorrections(const WorkspaceMap &inputs,
Could this function be split up to reduce the length/nesting?

2018-02-06 12:42 UTC, gemmaguest commented on Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
> +PolarizationEfficiencyCor::twoInputCorrections(
Could this function be split up to reduce the length/nesting?

2018-02-14 08:32 UTC, soininen commented
@gemmaguest I've refactored the methods as requested.

2018-02-16 17:59 UTC, gemmaguest approved these changes

2018-02-16 17:59 UTC, gemmaguest commented
Looks good to me now :+1:

2018-02-19 09:50 UTC, merged