Add toDict example to TableWorkspace concept page
mantidproject/mantid pull request #21635
Opened 2018-01-23 16:01 UTC by samueljackson92

Add an example to the TableWorkspace concepts page. This should have been part of #21558.

*No associated issue*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-02 14:22 UTC, peterfpeterson requested changes
I thought you were going to also add examples for converting to a `pandas.DataFrame`. From the other PR
```python
import pandas as pd
df = pd.DataFrame(table.toDict())
```
It should be marked up as a code block so we don't have to install pandas on the build servers, but people can still see the example. Also, an example that assembles a `pandas.DataFrame` from looping over the columns would be helpful. For example (this likely won't work as is)
```python
df = pandas.DataFrame()
for col in tableWS.columnNames():
    df[col] = tableWS[col]
```

2018-02-02 14:51 UTC, samueljackson92 commented
@peterfpeterson Sure. I think I misunderstood. I'll add that as well.

2018-02-12 16:46 UTC, peterfpeterson requested changes
I know it isn't part of this PR, but please fix up the formatting of the C++ section of the document as well. L172, L176-179, L223-231, and L235-239 should be `code-block:: c` to make the document look nicer.

2018-02-12 16:46 UTC, peterfpeterson commented on docs/source/concepts/TableWorkspaces.rst
> +    df = pd.DataFrame()
This should be
```python
df = pd.DataFrame()
for col in tableWS.getColumnNames():
    df[col] = tableWS.column(col)
```

2018-02-13 16:37 UTC, peterfpeterson requested changes

2018-02-13 16:37 UTC, peterfpeterson commented on docs/source/concepts/TableWorkspaces.rst
> +        df[col] = tableWS[col]
Still a bug. This line should be `df[col] = tableWS.column(col)`

2018-02-13 16:43 UTC, peterfpeterson commented
Other than the one error in the example, everything else is ready. Good additions.

2018-02-14 20:07 UTC, peterfpeterson approved these changes

2018-02-15 08:23 UTC, merged