Add ability to pickle table workspaces
mantidproject/mantid pull request #21633
Opened 2018-01-23 15:03 UTC by samueljackson92

Add the ability to pickle table workspaces.

**To test:**

Try pickling/unpickling!

Fixes #21590.

**Release Notes** 
[See here](https://github.com/mantidproject/mantid/commit/4092918be8982e8cc9b159fcb64a21fadcce7b7b)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-01-31 10:27 UTC, OwenArnold requested changes
I think there is a problem that needs fixing here. It is not possible to add the deserialized workspaces to the ADS. Maybe these aren't being returned as shared_ptr wrapped? Maybe @martyngigg would be able to comment.

2018-02-08 14:31 UTC, samueljackson92 commented
@OwenArnold This should be ready for retesting.

2018-02-08 15:37 UTC, OwenArnold commented on Framework/PythonInterface/mantid/api/src/Exports/ITableWorkspace.cpp
> +  const auto ws = WorkspaceFactory::Instance().createTable();
This makes sense.

2018-02-08 15:38 UTC, OwenArnold approved these changes

2018-02-09 08:15 UTC, merged