Reflectometry Help improvement
mantidproject/mantid pull request #21668
Opened 2018-01-31 14:53 UTC by edwardb96

Description of work.

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-12 12:16 UTC, josephframsay submitted a review, later dismissed
Changes look mostly good, but unfortunately the runs are still highlights in a rather attractive green on Linux.

2018-02-12 12:17 UTC, josephframsay requested changes
Changes look mostly good, but unfortunately the rows are still highlighted in green on both Linux and Windows (see screenshot)

![screenshot from 2018-02-12 12-14-56](https://user-images.githubusercontent.com/29916298/36096554-c9206ab4-0fee-11e8-8afb-440c55462b72.png)

2018-02-16 11:40 UTC, edwardb96 commented on MantidPlot/src/ApplicationWindow.cpp
> +  @returns A pallete with contrasting tooltip and background colours.
Good catch

2018-02-16 11:46 UTC, josephframsay approved these changes

2018-02-16 11:47 UTC, josephframsay commented
My bad, misread the instructions. Tests work as expected - all good to go!

2018-02-16 15:37 UTC, merged