FindPeaksMD calculate Goniometer rotation for CW
mantidproject/mantid pull request #21726
Opened 2018-02-09 14:29 UTC by rosswhitfield

Add option to calculate the Goniometer rotation (around y-axis only) for a constant wavelength source. This will allow only one instrument definition to be held while peaks can be found for multiple sample rotations.

**To test:**
The following should find 18 peaks, without this option it only finds 2:
```
LoadMD(Filename='/SNS/users/rwp/tmp/NaCl_data_MDH3.nxs', LoadHistory=False, OutputWorkspace='md')
FindPeaksMD(InputWorkspace='md', PeakDistanceThreshold=0.5, DensityThresholdFactor=500, OutputWorkspace='peaks',
            CalculateGoniometerForCW=True, Wavelength=1.488)
```

Added to release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-09 15:26 UTC, AndreiSavici requested changes
There is no description in the help about what the algorithm is doing with the new parameters.

2018-02-09 15:26 UTC, AndreiSavici commented on Framework/MDAlgorithms/src/FindPeaksMD.cpp
> +  declareProperty(make_unique<PropertyWithValue<double>>("Wavelength", DBL_MAX,
Add a validator. There is no point in allowing negative wavelengths

2018-02-12 13:58 UTC, VickieLynch approved these changes
Works for TOPAZ data without this option and WAND data with it.  Should the goniometer rotations be in the notice or debug logs?

2018-02-12 15:15 UTC, rosswhitfield commented
@VickieLynch I think most of the time people don't care what the rotations are but I will move it up a level to `information`.

2018-02-12 22:30 UTC, AndreiSavici approved these changes

2018-02-13 16:44 UTC, merged