Set matplotlib figure background to white by default in new workbench
mantidproject/mantid pull request #21769
Opened 2018-02-16 16:25 UTC by martyngigg

Description of work.

In matplotlib `< v2.0` the default figure facecolor is gray but in `>= v2.0` it changed to white. White looks cleaner so we set the default figure facecolor to white across the board. Users are of course free to change it with 'matplotlib.rcParams'

**To test:**

* build the branch on a system with matplotlib < v2.0
* start the workbench
* make a plot an observe the figure facecolor is white

Refs #21649 

**Release Notes** 

*Does not need to be in the release notes as the workbench is not ready to announce yet.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-16 22:38 UTC, AndreiSavici requested changes
Can you fix the segfault when I right click on workspaces? Or is there a PR for that?

2018-02-20 16:09 UTC, martyngigg commented
@AndreiSavici I'm not going to have time to look into this before the code freeze so I'll get back to it next week.

2018-04-16 14:54 UTC, mantid-builder commented
@martyngigg the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-04-30 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-05-25 16:02 UTC, martyngigg commented
@AndreiSavici Pete's going to look into the crash on RedHat now that he has a machine locally. Would you be willing to merge this without that fix?

2018-05-31 07:27 UTC, martyngigg commented
@AndreiSavici Would you be willing to accept this now #22503 is merged?

2018-05-31 14:27 UTC, AndreiSavici approved these changes

2018-05-31 14:27 UTC, AndreiSavici commented
Unrelated build server failures

2018-05-31 19:54 UTC, merged