Set transmission runs based on run angle
mantidproject/mantid pull request #21762
Opened 2018-02-16 12:41 UTC by gemmaguest

This PR adds a table to the Settings tab of the ISIS Reflectometry GUI which allows default transmission runs to be specified on a per-angle basis, so that the transmission runs can be looked up based on the angle of each run. This replaces the existing text entry box which just allowed for one default set of transmission runs to be specified. Overall defaults can still be specified by leaving the angle column blank.

Due to the issues with providing the lookup angle described in the linked issue, for now, to avoid confusion, there is a restriction that per-angle OR overall defaults can be specified, but not both.

This PR also includes the following changes, which were fixed in the process of making the underlying code more consistent:
- Significant refactoring to cache row metadata, such as properties used in the reduction, the processed state, the reduced workspace names etc. This 
- The `Output Notebook` option now works for all groups that are processed as non-event workspaces. Previously, if event handling was enabled but a group contained non-event workspaces, generating the notebook was disabled.

Fixes #20088

**To test:**

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-26 10:09 UTC, edwardb96 requested changes
Broadly this is working. There are a few UX glitches and which could do with tidying up further along the line. There are a few code style issues outlined below, some which are easier to deal with than others...

2018-02-27 09:43 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/QtReflSettingsView.cpp
> +      m_ui.transmissionRunsTable->horizontalHeader()->height() + 2;
There seems to be some extra padding or something in the table so this was required to make it the correct height. I don't know if there's a better way to find out what this is.

2018-02-27 10:02 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/QtReflSettingsView.cpp
> +    auto runs = runsItem ? runsItem->text() : "";
Apparently so - they are null when the GUI is first opened. I'm not sure why.

2018-03-01 16:25 UTC, edwardb96 approved these changes

2018-03-01 17:11 UTC, martyngigg commented
Windows test failure is unrelated.

2018-03-02 13:26 UTC, gemmaguest commented
I've just found a bug related to these changes so please hold off merging for now.

2018-03-02 18:02 UTC, gemmaguest commented
To test the fix for transferring new rows: 
- Do a search in the ISIS Reflectometry GUI e.g. POLREF investigation 1520249
- Transfer several runs e.g. the first 10
- Process some rows and check you can plot them from the GUI
- Expand some groups
- Transfer some more rows to the table
- Check that:
  - the new rows get added to the correct existing group, or to a new group at the bottom of the table if their group doesn't exist yet.
  - you can still plot rows/groups that were previously reduced.
  - rows/groups that were previously highlighted green are still green (this didn't used to work so is an added benefit of this fix).
  - groups' expanded/collapsed state has not changed (again this didn't used to work)
  - if you deselect everything and hit process, rows/groups that were already reduced should not be re-processed (again this didn't used to work).

Also check that the ISIS SANS v2 experimental GUI still operates correctly

2018-03-02 18:30 UTC, gemmaguest commented
@edwardb96 This is ready to look at again but I've left the In Progress label so it doesn't get merged yet.

2018-03-02 18:50 UTC, gemmaguest commented
@edwardb96 Actually I have some more improvements to make so don't review yet

2018-03-05 09:48 UTC, gemmaguest commented
@edwardb96 This is ready to look at again

2018-03-06 09:25 UTC, NickDraper commented
Should this still have the in progress label?

2018-03-06 09:29 UTC, gemmaguest commented
@NickDraper I left the In Progress label because I found a bug after it had been approved. Edward is going to check the latest fix and I'll remove the label when he's happy with it.

2018-03-06 09:36 UTC, martyngigg commented
Just want to double check. Is this okay to merge now?

2018-03-06 09:36 UTC, edwardb96 commented
Not yet.

2018-03-06 09:48 UTC, edwardb96 commented
@martyngigg, @gemmaguest I have finished testing this now and it looks good to merge :+1:

2018-03-06 09:51 UTC, martyngigg commented
Thanks.

2018-03-06 09:52 UTC, merged