Add SpectrumInfo and twoTheta python exports
mantidproject/mantid pull request #21820
Opened 2018-02-22 14:02 UTC by MatthewBowles

[Mslice](https://github.com/mantidproject/mslice) recently required access to scattering angle information through `SpectrumInfo` (due to using a non-matrix workspace). This PR adds the required exports.

**To test:**
Test `SpectrumInfo` and `twoTheta` can be used in python e.g. `workspace.spectrumInfo().twoTheta(x)`

Fixes #21817

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-22 19:25 UTC, quantumsteve commented
Have you considered discussions in https://github.com/mantidproject/mantid/pull/18962 and https://github.com/mantidproject/mantid/pull/19019?

2018-02-23 09:31 UTC, MatthewBowles commented
Yes. `getDetector` cannot be used in mslice's use case since I am not operating on a `MatrixWorkspace`. `SpectrumInfo` seems to be in a more stable state now, so I see no reason not to add exports (since it was planned to do this eventually anyway). I have discussed with @SimonHeybrock about this.

2018-02-23 09:35 UTC, SimonHeybrock requested changes
One comment:

2018-02-23 09:35 UTC, SimonHeybrock commented on Framework/PythonInterface/mantid/api/src/Exports/ExperimentInfo.cpp
> +      .def("spectrumInfo", &ExperimentInfo::spectrumInfo,
I think this is currently in the child class export `MatrixWorkspace`, so if we add it here in the base, remove it in the child.

2018-02-23 09:52 UTC, SimonHeybrock commented on Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp
> -      .def("spectrumInfo", &MatrixWorkspace::spectrumInfo,
Also remove the include.

2018-02-23 09:57 UTC, SimonHeybrock approved these changes

2018-02-23 15:17 UTC, merged