Minor fix to default in calibration script
mantidproject/mantid pull request #21825
Opened 2018-02-22 15:21 UTC by NickDraper

The calibration script was not working if the range_list was using the default.
This was the error
```
<tube_spec.TubeSpec instance at 0x0000000022776448>
Looking for MAPS/B2_window
Number of tubes = 52
TypeError: 'int' object is not iterable
  at line 21 in 'New script'
  caused by line 432 in 'C:/MantidInstall/scripts/Calibration\tube.py'
  caused by line 498 in 'C:/MantidInstall/scripts/Calibration\tube_calib.py'
```

This PR sets the default for range_list to be a range
not a single int as it was before, which would fail in the calibration routine

**To test:**

Run this script if it runs all is well.
``` python
from tube_calib_fit_params import TubeCalibFitParams
import tube
from tube_spec import TubeSpec

#Load the calibration workspace
wsIn=Load('MAP26840.raw')
#remove the previous calibration
empty_instr = LoadEmptyInstrument("c:/mantidinstall/instrument/MAPS_definition.xml")
CopyInstrumentParameters(empty_instr,wsIn)
#integrate the data
ws=Integration("wsIn", RangeLower=2000,RangeUpper=10000)

#Set the Tube specfication
tubeSet = TubeSpec(ws)
tubeSet.setTubeSpecByString("MAPS/B2_window")
#Starting positions for fits
ExpectedPositions = [15.0, 50.0, 90.0, 126.0, 200.0, 240.0]
fitPar = TubeCalibFitParams(ExpectedPositions)

#position in metres along the tube where the bands should be
knownPositions = [-0.5, -0.30, -0.15, 0.0, 0.30, 0.5] 
# the shape of these points: edge, gaussian, gaussian, gaussian, edge
funcForm = [2, 1, 1, 1,1, 2]

calibTable = tube.calibrate(ws, 'MAPS/B2_window', knownPositions, funcForm, margin=30, plotTube=range(0,52), fitPar=fitPar, outputPeak=True)
ApplyCalibration(ws, calibTable)
```

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-02-23 13:10 UTC, KarlPalmen approved these changes

2018-02-23 13:10 UTC, KarlPalmen commented on scripts/Calibration/tube.py
> -    range_list = param_helper.get_parameter(RANGELIST, kwargs, default_range_list=tubeSet.getNumTubes())
The tube calibration now works, but the script produces another error concerning workspace pointer when applying the calibration, which I take to be another issue.

2018-02-23 16:06 UTC, peterfpeterson requested changes
This isn't getting you want you want in python3. It should be changed to `list(range(tubeSet.getNumTubes()))` otherwise you are setting the keyword to an iterator.

2018-02-26 13:58 UTC, peterfpeterson approved these changes

2018-02-26 13:58 UTC, merged