Engineering Diffraction GUI - run GSASIIRefineFitPeaks in a separate thread
mantidproject/mantid pull request #21916
Opened 2018-03-01 15:13 UTC by josephframsay

**Work in progress**

Running GSASIIRefineFitPeaks synchronously from the GSAS tab of the ED GUI locks the GUI. This PR Takes care of moving the algorithm to run in a separate thread, and hence stop locking the GUI.

**Things left to do:**
- [ ] Improve the error message when we cancel the algorithm
- [ ] Fix up `EnggDiffGSASFittingModelTest` (may be fiddly - it would be nick to mock `EnggDiffGSASFittingObserver` in there if possible)

**To test:**

Fixes #21843 

**Release Notes** 
Doesn't need to go in, as it's a fix for a feature which is new this release

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-06 10:46 UTC, ElliotAOram commented
@Mantid-Matthew you can follow the test instructions on this [Pull Request](https://github.com/mantidproject/mantid/pull/21804). I believe this is left in a state where the problem with the GUI freezing has been resolved, just the tests and error handling need a fix up. Let me know if you have any questions and I can try to answer them!

2018-03-06 17:06 UTC, NickDraper commented
@ElliotAOram @Mantid-Matthew  has got an urgent issue in from one of the SANS instruments, so I've removed him from this PR.  We will need to find someone else.

2018-03-07 11:07 UTC, NickDraper commented
Moving out of this release as more work is needed here by the original author than we have time for in this release.

2018-03-20 10:34 UTC, josephframsay commented
Accidentally closed with deletion of `release-v3.12` branch

2018-03-22 15:55 UTC, josephframsay commented
@NickDraper Would this be considered too high-risk for the patch release?

2018-04-11 10:00 UTC, soininen requested changes
I had some problems saying that GSASII could not be imported but these got solved after I set up correct proxies for subversion. Nothing that could be solved in Mantid, I suppose. Anyway, the refinement seems to run nicely in the background and nothing crashes in unrecoverable way if I delete workspaces or close the interface in the middle of the refinement process. There are a few concerns regarding the code but nothing major, see below.

2018-04-11 10:00 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingModel.cpp
> +    return "Unknown refinement method: contact development team";
Would it make sense to throw here?

2018-04-11 10:00 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingObserver.h
> +public:
This class has `virtual` methods. How about a `virtual` destructor as well? Could be declared `default`.

2018-04-11 10:00 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingPresenter.h
>    virtual ~IEnggDiffGSASFittingPresenter() = default;
The destructor could be declared `virtual` in the new parent class and removed here.

2018-04-11 14:17 UTC, soininen approved these changes

2018-04-12 16:01 UTC, merged