Removed temperature filtering from Muon Analysis
mantidproject/mantid pull request #21953
Opened 2018-03-05 18:10 UTC by Mantid-Matthew

The muon Analysis interface was filtering the temperature sample logs for some data and not for others. This removes the temperature filtering from all cases.

**To test:**

- Open muon analysis
- Load MUSR 67909
- Look at the Temp_sample of the sample logs (has data for t<0)
- go to the settings tab and make sure multi fitting is ticked
- Go to data analysis and some new groups will be added to the ADS - these will have sample logs with values for t<0

Fixes #21827. 

**Release Notes** 
ToDo

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-06 10:06 UTC, AnthonyLim23 requested changes
code looks good and works as expected. Just needs to be added to the release notes

2018-03-06 10:12 UTC, AnthonyLim23 approved these changes
all works

2018-03-06 10:45 UTC, NickDraper requested changes

2018-03-06 10:45 UTC, NickDraper commented on qt/scientific_interfaces/Muon/MuonAnalysisHelper.cpp
> +    runTemp.getProperty("Temp_Sample")->filterByTime(start, end);
Can we copy just that property rather than the whole run object?

2018-03-06 14:56 UTC, NickDraper approved these changes

2018-03-06 19:55 UTC, martyngigg requested changes

2018-03-06 19:55 UTC, martyngigg commented on qt/scientific_interfaces/Muon/MuonAnalysisHelper.cpp
> +    const auto *Temp_Sample_TimeSeries =
A couple of things:
  - variables names should be camelCase
  - we should check the result of the `dynamic_cast` for safety or we'll hit a segfault

2018-03-07 11:22 UTC, martyngigg approved these changes
Confirmed that the latest set of changes preserves the expected behaviour.

2018-03-07 11:23 UTC, merged