Tie/fix/constrain in multi fitting
mantidproject/mantid pull request #21974
Opened 2018-03-07 10:09 UTC by mantid-roman

Corrected update of the gui for local parameters. Added constraints to the local parameters.

**To test:**

* Start the multi fit interface. Add some data, function.
* Set ties, fixes, constraints to parameters of functions of different data sets.
* Switch between data sets. Check that the gui updates correctly.
* Run a few fits selecting different current data set each time. Results must be the same regardless of the selected data set.

Fixes #21829

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-07 10:50 UTC, keeeto commented
I'm happy to have a go at testing this too. Can anyone direct me to the multi fitting documentation?

2018-03-07 10:57 UTC, mantid-roman commented
@keeeto I am not sure if we have it

2018-03-07 11:00 UTC, keeeto commented
Ah, okay. No problem; I guess this is a job I cannot do then :). Maybe after the release is over I will have a go at learning the interface and writing some documentation. @mantid-roman would I be best to talk to you about this?

2018-03-07 11:03 UTC, mantid-roman commented
@keeeto Yes

2018-03-07 11:14 UTC, soininen commented
I found a problem when using CompositeFunction.
1. Get some data. I used `084446.nxs` from `ExternalData/Testing/Data/UnitTest/ILL/IN4`.
2. Open the Multi dataset fitting interface.
3. Add data. I used ws indices 10-14 from the IN4 workspace.
4. Add composite function.
5. Add FlatBackground to the composite function.
6. Constrain the A0 parameter to 10%.
7. Click Fit. Mantid crashes.

There is even a crash if I just try to change the value of A0...

2018-03-08 07:32 UTC, soininen commented
The problem with CompositeFunction seems to be gone now. However, there are some problems with ties: when I write some garbage, like `0.8*` in the tie input field, Mantid crashes.

Also, the tie field sometimes becomes disabled (grayed out) and I cannot modify the value anymore. This seems to happen when I try to write `0.` in the field.

2018-03-08 10:08 UTC, soininen commented
I should have been more precise: there is a crash when I right click a parameter, select `Add tie`, and write some garbage like `**` in the `Add a tie` dialog.

2018-03-08 14:16 UTC, soininen commented
The problems with the ties are now gone.

However, if I
1. Use the same dataset as above
2. Create a CompositeFunction
3. Add a FlatBackground
4. Add a Gaussian
5. Set the tie of the Sigma parameter to `f1.PeakCentre/25`
6. Click 'Fit'

```
Fit failed:

Unknown function parameter Height

This may happen if there is a CompositeFunction containing only one function
```

2018-03-08 14:26 UTC, mantid-roman commented
I am afraid this is unfixable, in this release at least. The message tells the user that using a composite function with one member is an error and they should either add more functions of do without the CompositeFunction.

2018-03-08 15:49 UTC, soininen commented
@mantid-roman There was two functions there in this case, FlatBackground and Gaussian, so I was a bit surprised with the error message.

2018-03-08 15:53 UTC, mantid-roman commented
That's not good :(

2018-03-09 08:19 UTC, soininen requested changes
Tested the changes with some data, and for simple functions, ties, fixes and constraints work fine. I get some error message with ties when CompositeFunction is involved but this is a known problem to my understanding.

The code changes look good, as well. I spotted just a few minor issues.

2018-03-09 08:19 UTC, soininen commented on qt/widgets/common/src/FunctionBrowser.cpp
> +    bool isUpper = it.value().upper == prop;
`const bool`?

2018-03-09 08:19 UTC, soininen commented on qt/widgets/common/src/FunctionBrowser.cpp
> +        auto parName = getParameterName(paramProp);
`const auto`?

2018-03-09 08:19 UTC, soininen commented on qt/widgets/common/src/FunctionBrowser.cpp
> +      QString parName = QString::fromStdString(parameterName);
Could both strings be `const`? It looks a bit strange that the same string is duplicated as C-string and `QString` here, but I guess it cannot be helped.

2018-03-09 08:19 UTC, soininen commented on qt/widgets/common/src/FunctionBrowser.cpp
> +        auto tie = localParam.tie;
`const auto &`?

2018-03-09 08:19 UTC, soininen commented on qt/widgets/common/src/FunctionBrowser.cpp
> +  for (auto it = m_constraints.begin(); it != m_constraints.end(); ++it) {
Perhaps C++11 style `for` loop could be considered here:
```
for (const auto &constraint : m_constraints) {
```

2018-03-09 14:54 UTC, soininen commented
The ties seem to work now with multiple functions in CompositeFunction. Good work!

2018-03-09 14:56 UTC, soininen approved these changes

2018-03-09 16:56 UTC, merged