Period algebra in Muon multiFitting
mantidproject/mantid pull request #21999
Opened 2018-03-08 09:25 UTC by AnthonyLim23

In the multiple fitting of muon analysis any period algebra (e.g. periods 1+2) where not available for fits. This PR fixes that. 
**To test:**
Open Muon analysis

**check algebra is picked up in multi fit**
Make sure multi fitting is enabled in the settings tab
On the home tab load HIFI 84447 (it should have 4 periods)
Got to data analysis and 'All periods' should be selected and the periods should be listed. 
Click combine button (bottom of page) then enter the following:

- 1,2 in the top box, then press apply
- 1 in the top box and 2 in the bottom box, press apply
- 1 in the top box and 2,3 in the bottom box, press apply

The above should all be added to the list of selected periods (, will be replaced by +)
In the combine box enter:
- 1.2 in the top box press apply
- 1,5 in the top box, then press apply
-1 in the top box and 2.3 in the bottom box, press apply
-1 in the top box and 2,5 in the bottom box, press apply
None these should be added to the selected periods as they all have errors (wither the decimals or a non-existent period)

Do a fit (flat background is good)
It should work.

**Check changing data resets the periods**
Change the selected periods to something else
Then go to the home tab and click the next button (the right arrow)
Go back to data analysis and the periods selected should just be 1,2,3,4
Go back to the home page and enter a 2 in the box after the '-' and press enter (creates the 1-2 data)
Go to the data analysis tab and check that the 1-2 period has been added to the selected periods list

On the home tab enter 84442 into the run number box and press enter
Go back to data analysis and the periods selected should just be 1,2,3,4
Go back to the home page and enter a 2 in the box after the '-' and press enter (creates the 1-2 data)
Go to the data analysis tab and check that the 1-2 period has been added to the selected periods list

Then go to the home tab and click the previous button (the left arrow)
Go back to data analysis and the periods selected should just be 1,2,3,4
Go back to the home page and enter a 2 in the box after the '-' and press enter (creates the 1-2 data)
Go to the data analysis tab and check that the 1-2 period has been added to the selected periods list

**Check changing to a single period data set from multi period works**
Load run 128247 and go to the data analysis tab (this has no periods)
Do a fit

**Check changing from single period to multiperiod data works**
Load 84447 on the home tab and then do a fit in data analysis 

**Check single fit works**
Go to the settings tab and make sure the multi fitting box is unticked
On the home tab enter a 2 in the box after the '-'
Go to data analysis (it will be the single fit interface)
Do a fit (it will be to the 1-2 data)
Change the data to period 1 by using the workspace drop down and do another fit

Fixes #21961. 

**Release Notes** 

In release notes
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-09 13:24 UTC, MatthewBowles requested changes
Completed the tests without any problems, but in the combine box if I enter -1 in the top box and then 2,3 in the second it gives an error when trying to fit.

2018-03-09 13:24 UTC, MatthewBowles commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +    m_enumManager->setValue(m_periodsToFit, j);
It looks like these two lines are always executed regardless of the if/else statements so shouldn't they be moved outside instead of duplicated?

2018-03-09 13:24 UTC, MatthewBowles commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +    }
I think you can use use `boost::split` here.

2018-03-09 13:24 UTC, MatthewBowles commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +    return;
I'd prefer `if(!x)` over `if(x) return`.

2018-03-09 13:24 UTC, MatthewBowles commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +
I think it would be better to move all this validation into a separate method that returns a boolean.

2018-03-13 09:12 UTC, NickDraper commented
@MatthewBowles This PR needs retesting now, please.

2018-03-13 09:41 UTC, MatthewBowles approved these changes
Looks good to me. Everything works as expected :+1:

2018-03-13 09:43 UTC, merged