Check if executed and is interactive for successful script execution
mantidproject/mantid pull request #22011
Opened 2018-03-08 15:41 UTC by reimundILL

Fixes a bug. See issue(s) for information.

**To test:**

**Try to provoke a crash using the Python script window.**

Fixes #22009 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-09 09:27 UTC, martyngigg requested changes
I'm happy that we only update the auto-complete information on successful execution of a script.

2018-03-09 09:27 UTC, martyngigg commented on MantidPlot/src/PythonScript.cpp
> +    if (isInteractive() && !isExecuting()) {
I think the `isExecuting` check here means that the code inside the `if` here will never run. I think `isExecuting` will only return false after `executeString()` has completed.

To demonstrate this first type `ws = CreateSampleWorkspace()` in to the script window and execute the code. Now on a new line start typing `ws.` and nothing happens. In the current version of Mantid the selection box of methods pops up, which is created by a call to `generateAutoCompleteList()`

2018-03-09 09:35 UTC, martyngigg commented
I think our main problem here is that we are hitting a real problem under the hood with how `getRun().getProperty` works. `getProperty` returns a bare pointer to a log value and when `A` is overwritten the pointer stored in `B` is no longer valid so any further accesses of this pointer will likely cause a segmentation fault.

I think your fix, without the `isExecuting` check, is still valid as it at least allows an error message to be populated.

The issue with `getProperty` is rather harder to solve and the workaround at the moment would be:
```
A = CreateSampleWorkspace()
a_title = A.getRun().getProperty('run_title').value
A = CreateSampleWorkspace()
A.setTitle(a_title)
```
so that `a_title` becomes a copy of the value in the property and having a dangling pointer in the script at all.

I suggest we try and tackle the *real* problem with `getPointer` in the next release as it is to big to put in now.

2018-03-09 12:47 UTC, reimundILL commented
Thank you for your careful considerations, I did not check that auto-completion still works throughout.

I will follow your advice to allow auto-completion and open an issue for the remaining bug.  I hope you follow this further since I will likely not have time to do some further investigations.

Some points that stay important for me are:
- this solution does (I was really happy) not produce any crashes in no multiple ways for me.

- the script
```Python
A = CreateSampleWorkspace()
B = A.getRun().getProperty('run_title')
A = CreateSampleWorkspace()
A.setTitle(B.value)
```
in the script interpreter does not produce crashes at all (on master)
- but this script will still crash Mantid in the future when run in the script window.

The script interpreter and the script window should behave the same way, the script window should be fixed first from my point of view.

2018-03-10 10:59 UTC, martyngigg commented
@reimundILL Thanks for re-enabling the auto completion. I agree that it's important we fix the underlying issue so that the program does not crash in any instance when accessing the log data in that way.

2018-03-10 11:24 UTC, martyngigg approved these changes

2018-03-12 09:17 UTC, merged