Indirect - Corrections - Ensure Plot Current Preview plots transformed container in Container Subtraction and Apply Paalman Pings
mantidproject/mantid pull request #22018
Opened 2018-03-08 17:57 UTC by brandonhewer

In ```Interfaces > Indirect > Corrections```, the ```Container Subtraction``` and ```Apply Paalman Pings``` interfaces do not plot the transformed container or the result when clicking ```Plot Current Preview```.

This PR ensures the transformed container and the result are plot, when appropriate, by the ```Plot Current Preview``` feature.

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-09 11:12 UTC, MatthewBowles commented
I get different results in the interface and plot:
![image](https://user-images.githubusercontent.com/29917114/37204894-8b0e0df8-238a-11e8-9cd4-61a777d262d9.png)
![image](https://user-images.githubusercontent.com/29917114/37204902-905fff96-238a-11e8-832d-255494a03d1d.png)

2018-03-09 11:19 UTC, MatthewBowles requested changes
The absorption corrections is fine, just fix the inconsistency in the container subtraction plots.

2018-03-09 13:16 UTC, brandonhewer commented
@MatthewBowles The issue in the Container Subtraction interface should now be fixed.

2018-03-09 13:34 UTC, MatthewBowles approved these changes
Yep, works fine now.

2018-03-09 15:57 UTC, NickDraper requested changes

2018-03-09 15:57 UTC, NickDraper commented on qt/scientific_interfaces/Indirect/ContainerSubtraction.cpp
> +      "LogText", boost::lexical_cast<std::string>(m_uiForm.spShift->value()));
You are passing in a value into the function, but are not using it and setting the value from the ui form, why?

2018-03-09 15:58 UTC, NickDraper commented on qt/scientific_interfaces/Indirect/ContainerSubtraction.cpp
> +      "LogText", boost::lexical_cast<std::string>(m_uiForm.spShift->value()));
This is also the cause of the compiler warning

2018-03-09 16:21 UTC, brandonhewer commented
@NickDraper This was a mistake, the value passed into the function should have been used here. I have now updated this.

2018-03-12 09:44 UTC, NickDraper approved these changes

2018-03-12 11:47 UTC, merged