Hb3a 1pt intensity 21837
mantidproject/mantid pull request #22032
Opened 2018-03-09 15:58 UTC by wdzhou

Implement a functionality in HB3A interface to calculate peak intensities of weak peaks which are only measured by single point.

**To test:**

Fixes #21837. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-28 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-06-11 14:03 UTC, mantid-builder commented
@wdzhou have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-08-30 14:03 UTC, mantid-builder commented
@wdzhou have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-09-14 14:03 UTC, mantid-builder commented
@VickieLynch do you have any comments on this PR?
<!-- {"problem_type": "review_requested"} -->

2018-10-02 14:03 UTC, mantid-builder commented
@wdzhou have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-10-18 21:13 UTC, peterfpeterson requested changes
Lots of little fixes. I haven't gone through everything yet.

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/hfctables.py
> +from PyQt4 import QtCore
Still has direct dependence on PyQt4

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/message_dialog.py
> -class MessageDialog(QtGui.QDialog):
Does this need to be a separate class? It looks like a free function kicking off `QMessageBox` would cover it.

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/mpl2dgraphicsview.py
> +from qtpy.QtWidgets import (QWidget, QVBoxLayout, QSizePolicy)
There is an abstraction in the root of `scripts` to make matplotlib qt4/qt5 compatible. Use that.

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/mplgraphicsview.py
> +            # data_line = r[0]
Don't add commented out code

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/mplgraphicsview.py
> +                # plot[0].remove()
Don't add commented out code

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/peak_integration_utility.py
> +    #
Move to debug logging or remove the commented out code

2018-10-18 21:13 UTC, peterfpeterson commented on scripts/HFIR_4Circle_Reduction/plot3dwindow.py
>  from . import ui_View3DWidget
`load_ui` again

2018-10-19 12:56 UTC, wdzhou commented on scripts/HFIR_4Circle_Reduction/guiutility.py
> +# TODO - 20180815 - Clean!
Done

2018-10-19 12:58 UTC, wdzhou commented on scripts/HFIR_4Circle_Reduction/hfctables.py
> +from PyQt4 import QtCore
Corrected

2018-10-19 13:01 UTC, wdzhou commented on scripts/HFIR_4Circle_Reduction/mplgraphicsview.py
> +            # data_line = r[0]
Done

2018-10-19 13:01 UTC, wdzhou commented on scripts/HFIR_4Circle_Reduction/mplgraphicsview.py
> +                # plot[0].remove()
Done

2018-10-19 13:19 UTC, VickieLynch approved these changes
Works well using instructions in pull request

2018-10-19 13:58 UTC, peterfpeterson approved these changes
The rest of the Qt4/Qt5 changes will be done in a later PR. This is good to merge.

2018-10-19 14:32 UTC, merged