Improvements to per angle options
mantidproject/mantid pull request #22040
Opened 2018-03-09 18:20 UTC by gemmaguest

This PR adds the following changes to the ISIS Reflectometry GUI:

- Add additional options that can be set on a per-angle basis on the Settings tab: Q min, Q max, dQ/Q and Scale.
- Fix a bug where the Get Defaults button on the Settings tab clears values for which a default doesn't exist
- If duplicate angles are given, the first one takes precedence

**To test:**
To follow

Fixes #22039 

**Release Notes** 
*to follow*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-12 16:06 UTC, edwardb96 requested changes
Working with the exception of the bug I described to you. Some code-style suggestions...

2018-03-12 16:33 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/ReflSettingsPresenter.cpp
> +    for (auto iter = defaultOptions.begin(); iter != defaultOptions.end();
Yes, but I need keys as well as values and a range-based for loop with a QMap just seems to give the values

2018-03-12 16:33 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/QtReflSettingsView.cpp
> +  registerSettingWidget(*m_ui.optionsTable, "FirstTransmissionRun", alg);
Doh, yes!

2018-03-13 11:12 UTC, edwardb96 approved these changes

2018-03-13 11:12 UTC, edwardb96 commented
Ok to merge when builds pass. :+1:

2018-03-13 14:36 UTC, merged