22031 phase quad gui
mantidproject/mantid pull request #22052
Opened 2018-03-12 15:04 UTC by AnthonyLim23

The frequency domain analysis would use incorrect workspaces in its calculations if the data in muon analysis changed

**To test:**
Open muon analysis
Load some data
Open frequency domain analysis
Change workspace to PhaseQuad and run it (you may have to change the endX)
Change the method to maxent and run that

Change the data in Muon analysis (without closing the frequency GUI)
Go back to the frequency GUI
Run maxEnt - it should give an error
Go back to FFT and try another phaseQuad - it should give an error

Fixes #22031. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-12 15:48 UTC, NickDraper approved these changes
Overall I would have preferred a more visible error message than just a log entry, And a refresh option would have been better than having to reopen the interface.

However, given where we are in the release this is acceptable for now.

2018-03-12 15:52 UTC, AnthonyLim23 commented
I'm thinking that in future instead of just throwing a log warning we then reload the data automatically. And then resubmit the calculation (but to do this well will take some thought)

2018-03-12 16:03 UTC, NickDraper commented
@AnthonyLim23 You have a few flake8 warnings to sort out

2018-03-13 08:29 UTC, AnthonyLim23 commented
I have thought of a few improvements. Most have now been implemented and I am just waiting to check that it passes the tests. 

I have moved the checking to the thread model and have a method that can be called by the presenters at a later data for reloading the data (#22059). I have also improved the naming convention for the maxent

2018-03-13 09:04 UTC, AnthonyLim23 commented
I have also improved the naming of the PhaseQuad outputs and the checks. The previous version only compared the run numbers (so if two runs had the same number but different instruments it would have not failed) and now we also look at the instrument.

2018-03-13 09:45 UTC, martyngigg requested changes

2018-03-13 09:45 UTC, martyngigg commented on scripts/Muon/thread_model.py
> +    def hasDataChanged(self):
I'm not sure the `TheadModel` is the correct place for this check. `ThreadModel` has the responsibility  for starting threads and it shouldn't have other responsibilities that are not related to this.

As discussed offline the `load_utils.py` might make more sense for this as that already knows about the workspace names etc.

2018-03-13 10:20 UTC, AnthonyLim23 commented
moved the error check and it now reloads the data if it has changed

2018-03-13 12:21 UTC, martyngigg commented
I seem to get the name+instrument combination duplicated in the names (see below). Is that intended?

![screenshot from 2018-03-13 12-19-04](https://user-images.githubusercontent.com/733773/37341355-03e6f9f2-26b9-11e8-898a-897c2ea74146.png)

2018-03-13 12:43 UTC, AnthonyLim23 commented
yes that is intended. As it is useful if you use one of the grouped workspaces as you then get

run;grouped ws...

2018-03-13 12:57 UTC, martyngigg commented
@AnthonyLim23 Thanks for the explanation - I just wanted to check.

2018-03-13 12:57 UTC, martyngigg approved these changes

2018-03-13 12:58 UTC, AnthonyLim23 commented
no worries, it does look strange

2018-03-13 15:05 UTC, AnthonyLim23 commented
I have fixed the merge conflict and the previous build passed so we can cancel the builds

2018-03-13 15:16 UTC, merged