Dev-docs: Testing
mantidproject/mantid pull request #22150
Opened 2018-03-20 13:40 UTC by brandonhewer

This is the dev-docs move of the following Testing pages:
* [Unit Test Good Practice](http://www.mantidproject.org/Unit%20Test%20Good%20Practice)
* [Data and Helpers for unit tests](http://www.mantidproject.org/Data%20and%20Helpers%20for%20unit%20tests) - Renamed to "Testing Utilities"
* [Data Files in Mantid](http://www.mantidproject.org/Data%20Files%20in%20Mantid) - Renamed to "Data Files for Testing"
* [Running the unit tests](http://www.mantidproject.org/Running%20the%20unit%20tests)
* [Writing Performance Tests](http://www.mantidproject.org/Writing%20Performance%20Tests)
* [System Tests](http://www.mantidproject.org/System%20Tests) - Brandon

**To test:**
Build dev-docs and make sure the new page reads and renders clearly.
Ensure the changes in #22082 have been implemented

Refs #22082. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-23 10:47 UTC, DanNixon requested changes
See comments.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/UnitTestGoodPractice.rst
> +   testCreateAlgorithmNoAlgorithmException). THE AIM IS THAT FROM THE
Use inline code formatting for function name.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/UnitTestGoodPractice.rst
> +-  Be cautious in use of the setUp() and tearDown() methods. Be aware
More code formatting.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/UnitTestGoodPractice.rst
> +    More details of this will be provided at `Testing Utilities <TestingUtilities>`__.
This link does not work for me.

Is this a result of the pages not yet being in the doctree or is there a `.html` missing?

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/UnitTestGoodPractice.rst
> +.. figure:: Mocking.png
This image doesn't render for me.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/DataFilesForTesting.rst
> +**ApplyCalibrationTest**. In its first test, testSimple, it creates a
Use code formatting.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/DataFilesForTesting.rst
> +```http://HOSTNAME:PORT`` <http://HOSTNAME:PORT>`__.
This should just be `http://HOSTNAME:PORT` (i.e. no link).

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/SystemTests.rst
> +Target Platform Based on Free Memory
Duplicate heading

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/SystemTests.rst
> +marked as the development build, and the subversion tag
Out of date information (SVN tags).

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/TestingUtilities.rst
> +-  **ComponentCreationHelper**
Extra bold text not needed here.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/TestingUtilities.rst
> +be found in the **testhelpers**-package.
Use code formatting for "testhelpers"

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/WritingPerformanceTests.rst
> +cmake -DCXXTEST_ADD_PERFORMANCE=TRUE
Indentation is needed on the examples here, currently they render as empty code blocks.

2018-03-23 10:47 UTC, DanNixon commented on dev-docs/source/WritingPerformanceTests.rst
> +Mantid <http://builds.mantidproject.org/view/Tests/job/performance_tests_master/Master_branch_performance_tests/>`__.
http://builds.mantidproject.org/job/master_performancetests2/ is probably a more relevant link to go here (obviously the text also needs updated to reflect this is a machine at the ESS).

2018-03-28 13:51 UTC, martyngigg commented
@brandonhewer @DanNixon Is there more work to do here or is this ready to go?

2018-03-28 15:04 UTC, DanNixon commented
There are two comments that still need addressing:
- https://github.com/mantidproject/mantid/pull/22150/files#r176696370
- https://github.com/mantidproject/mantid/pull/22150/files#r176696121

2018-03-28 15:32 UTC, brandonhewer commented
@martyngigg @DanNixon Duplicate heading and outdated section has been removed.

2018-03-28 16:34 UTC, DanNixon commented
I think mentioning the nightly master pipeline is still worthwhile, it should just be updated to reflect the current workflow, or at very least link to the master pipeline view in Jenkins (http://builds.mantidproject.org/view/Master%20Pipeline/) and explain how the nightly build copy works.

2018-03-29 10:01 UTC, DanNixon commented
Actually do we have any pages that are specifically about Jenkins? I think what I was suggesting to include would be more appropriate there as it was not particularly specific to the system tests.

2018-03-29 10:01 UTC, DanNixon approved these changes

2018-03-29 10:37 UTC, martyngigg commented
[AutomatedBuildProcess](/mantidproject/mantid/blob/master/dev-docs/source/AutomatedBuildProcess.rst) looks like the best place.

2018-03-29 10:38 UTC, merged