D2B detector efficiency calculation
mantidproject/mantid pull request #22164
Opened 2018-03-21 15:06 UTC by gvardany

This PR extends the `PowderDiffILLDetEffCorr` algorithm to support the efficiency calculation for D2B instrument, which is a scanning powder diffractometer at the ILL. 

Some satellite algorithms are also fixed/adjusted correspondingly; there were minor bugs and extensions.

**To test:**
Use the files 532008 and 532009 from system test data under ILL/D2B directory (set facility to ILL) : 
```
PowderDiffILLDetEffCorr(CalibrationRun='532008,532009', DerivationMethod='GlobalSummedReference2D', OutputWorkspace='calib')
```
The output should be a 2D map of detector efficiencies, similar to the plot in the documentation.

Play around with the input properties of the algorithm, make sure the behaviour is reasonable. Also try to break it.

Make sure the documentation reads clear and the testing is adequate.

The method and the results are preliminarily agreed upon with the instrument scientist.

Fixes #21550 . 
Fixes #22093 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-04-11 14:15 UTC, soininen requested changes
Tested this using the instructions provided as well as with some data on ILL's network. `PowderDiffILLDetEffCorr` worked without problems and gave comprehensive error messages when suspicious input was given. There are a few comments I made on the code; additionally:
- *OutputWorkspace* could have X and Y axis labels if somebody wants to plot 2D.
- There is an extra dot in the doc string of the *PixelRange* property preventing the tooltip to show correctly.

2018-04-11 14:15 UTC, soininen commented on docs/source/algorithms/PowderDiffILLDetEffCorr-v1.rst
> +.. figure:: /images/D20_calib.png
Could the `.. plot:` directive be used here or does it take too long to produce the documentation?

2018-04-11 14:15 UTC, soininen commented on docs/source/algorithms/PowderDiffILLDetEffCorr-v1.rst
> +**Example - D20**
Is the example data available in Mantid's usage example data package? If so, it should be mentioned here as well. There is some sphinx directive to add a standard phrase and link here.

2018-04-16 07:05 UTC, gvardany commented
I think I have addressed all your comments now.

2018-04-16 12:29 UTC, soininen approved these changes

2018-04-17 07:37 UTC, merged