Add GSAS tab to Engineering GUI documentation
mantidproject/mantid pull request #22184
Opened 2018-03-22 15:35 UTC by josephframsay

Sections on the new GSAS tab were added to the docs for the ED GUI

**To test:**

Build the docs and make sure they look good. Have a read and make sure everything in there sounds sensible/lucid

Fixes #22044 

**Release Notes** 
Doesn't need to be in the release notes, as Engineering scientists aren't using the GUI yet anyway

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-23 10:26 UTC, DanNixon requested changes
Just a few comments.

2018-03-23 10:26 UTC, DanNixon commented on docs/source/interfaces/Engineering Diffraction.rst
> +- **GSAS-II Installation Directory** - you must have a version of
Some clarification of what the "installation directory" is may be good. i.e. is it the root of the install, the binary directory, etc.

2018-03-23 10:26 UTC, DanNixon commented on docs/source/interfaces/Engineering Diffraction Test Guide.rst
> +    :width: 500px
Does RST support percentage specifiers here? For me I have to open the full image to actually read any of the text on it.

2018-03-23 10:26 UTC, DanNixon commented on docs/source/interfaces/Engineering Diffraction Test Guide.rst
> +GSAS Fitting
Is it worth matching the heading with the name of the tab in the GUI (as per the other sections/tabs)?

2018-03-27 13:03 UTC, DanNixon approved these changes

2018-03-27 14:30 UTC, martyngigg commented
The Ubuntu and Windows jobs both passed but leeroy failed to notify back.

2018-03-27 14:31 UTC, merged