Dev-docs: instrument view and logging
mantidproject/mantid pull request #22199
Opened 2018-03-26 09:46 UTC by gvardany

This is the dev-docs move of 
[Rendering the Instrument View](http://www.mantidproject.org/Rendering_the_Instrument_View)
and [Logging](http://www.mantidproject.org/Logging) combined with [Logging Good Practice](http://www.mantidproject.org/Logging_Good_Practice)

**To test:**
Build the dev-docs check the pages read and render fine.

Refs #22082 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-26 14:03 UTC, DanNixon requested changes
Looks good. Documentation is clear and reads well.

Only issue is lack of formatting for inline code and filenames which should be as `raw text`.

2018-03-26 14:03 UTC, DanNixon commented on dev-docs/source/InstrumentViewer.rst
> +An instrument is always shown in a context of a workspace of data recorded on this instrument.
`in the context of a workspace of data` seems to read better to me.

2018-03-26 14:03 UTC, DanNixon commented on dev-docs/source/InstrumentViewer.rst
> +MantidPlot uses OpenGL to plot the geometry. Instrument3DWidget represents the view window and controls the viewport and the scene.
Class names should be `inline code formatted`.

2018-03-26 14:03 UTC, DanNixon commented on dev-docs/source/Logging.rst
> +  - Call *FrameworkManager.initialise()*
Use `code/raw text` formatting

2018-03-26 14:03 UTC, DanNixon commented on dev-docs/source/Logging.rst
> +For example, in python:
"Python"

2018-03-27 10:44 UTC, DanNixon approved these changes

2018-03-27 11:01 UTC, martyngigg commented
The failing build is unrelated.

2018-03-27 11:01 UTC, merged