Dev-docs: Git and coding standards-related pages
mantidproject/mantid pull request #22211
Opened 2018-03-27 12:03 UTC by josephframsay

Pages associated with Git, GitHub and coding standards were moved to the new `dev-docs` target

**To test:**

Build the docs and have a quick read through them to make sure everything looks correct and sounds sensible

Refs #22082 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-03-27 14:10 UTC, DanNixon requested changes
All looks good, just a few comments.

2018-03-27 14:10 UTC, DanNixon commented on dev-docs/source/GitWorkflow.rst
> +<https://help.github.com/articles/using-pull-requests/>`__
Full stop at end of line.

2018-03-27 14:10 UTC, DanNixon commented on dev-docs/source/GitWorkflow.rst
> +A good example is `here <https://github.com/mantidproject/mantid/pull/18713>`__
`.`

2018-03-27 14:10 UTC, DanNixon commented on dev-docs/source/GitWorkflow.rst
> +synchronized with GitHub, please follow the convention of
`synchronized with` -> `pushed to`

Synchronization is not a thing it Git.

2018-03-27 14:10 UTC, DanNixon commented on dev-docs/source/IssueTracking.rst
> +  - This is a duplicate of #1234
May as well add umbrella issues to this list as they often are not closed by a single PR

2018-03-27 14:10 UTC, DanNixon commented on dev-docs/source/IssueTracking.rst
> +Labels fall into several groups: (*please note that 'ticket' is used
This asterisk needs escaping, it is being rendered as a link.

2018-03-27 14:37 UTC, josephframsay commented on dev-docs/source/CodingStandards/UnitTestStandards.rst
> +  example WorkspaceTest, LoggerTest.
@DanNixon could you explain what you mean here? I didn't realise you could have class names that aren't raw strings?

2018-03-27 14:41 UTC, DanNixon commented on dev-docs/source/CodingStandards/UnitTestStandards.rst
> +  example WorkspaceTest, LoggerTest.
Sorry I mean the inline monospace style (I usually refer to it as "raw text").

2018-03-27 14:49 UTC, josephframsay commented on dev-docs/source/CodingStandards/UnitTestStandards.rst
> +  example WorkspaceTest, LoggerTest.
Oh yep, sorry - that makes sense!

2018-03-28 07:27 UTC, DanNixon approved these changes

2018-03-28 13:35 UTC, merged