Replace boost::random with std::random
mantidproject/mantid pull request #22252
Opened 2018-04-05 08:53 UTC by martyngigg

Description of work.

While upgrading boost as part of #22088 it was observed that the output of `boost::random::normal_distribution` has been slightly tweaked again producing some test failures. This work migrates everything to use classes from `std` `<random>` in the hope that we can standardize on this implementation and have fewer tests which need to check versions of boost etc.

As part of this work it was noticed that `std::normal_distribution` produces matching output on MSVC and clang but not [gcc](https://stackoverflow.com/questions/38532927/why-gcc-and-msvc-stdnormal-distribution-are-different). I have decided that to decrease the overhead in maintaining tests that the `normal_distribution` implementation that is part of clang would be brought into `Kernel` and used in place of the `std` version.

Many tests relied on sample from a uniform or normal distribution and this done slightly differently in the `std` versions but our tests don't perform enough iterations for the differences to be unobservable. The tests have been updated accordingly.

**To test:**

* Code review and tests should pass.

*No issue*

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-04-20 06:15 UTC, SimonHeybrock requested changes
Code looks good and I think this is a sensible way to solve the described consistency issues 👍.
Changes also include some cleanup and re-enabled tests. 👍 

Only a couple of minor questions/comments:

2018-04-20 06:15 UTC, SimonHeybrock commented on Framework/Kernel/inc/MantidKernel/uniform_int_distribution.h
> +// results yeild problems consistency of our tests across platorms.
yield

2018-04-20 08:08 UTC, martyngigg commented on Framework/Kernel/inc/MantidKernel/normal_distribution.h
> +#include <ios>
Good question. As I was pulling the the header from `llvm` I wanted to keep it as similar as possible. Although after looking over it again we're going to get it included anyway due to the inclusion of `<random>` so I should probably remove here.

2018-04-20 08:09 UTC, martyngigg commented on Framework/Kernel/inc/MantidKernel/normal_distribution.h
> +#include <ios>
I think we currently only use it from a few places in the code base.

2018-04-20 08:29 UTC, martyngigg commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
I'm afraid I don't. The algorithm is quite a complex method for Bayesian fitting as far as I understand it. @mantid-roman Could you offer any insight here?

2018-04-20 08:44 UTC, mantid-roman commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
I think that the use of `mt` is wrong here. The effective random number generator here is the seed expression.

2018-04-20 08:59 UTC, martyngigg commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
@mantid-roman Due you mean essentially that the return value should just be the seed expression?

2018-04-20 09:25 UTC, mantid-roman commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
No. `mt` should be instantiated outside the function and passed to it as a parameter (or a global variable). `mt` generates uniform random numbers using some sophisticated algorithm and those are used to pick values from the normal distribution. But what happens currently is that this sophisticated algorithm is effectively replaced by the expression `123 * (int(m_counter) + 45 * int(jump))  + 14 * int(time_t())`. Sorry I wasn't clear in my first comment.

2018-04-20 09:34 UTC, martyngigg commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
No problem. Thanks for clarifying.

2018-04-20 11:43 UTC, martyngigg commented on Framework/Crystal/test/NormaliseVanadiumTest.h
> +    TS_ASSERT_DELTA(ws->y(5050)[5], 17, 0.0001);
It seems to be entirely down to the way the random numbers are sampled from the flat distribution. If I make a one line change and use `boost::random::uniform_real_distribution` and leave the other changes alone then I recover the original number. I assume using a much higher number of events would eventually yield a converging result for both implementations.

2018-04-20 11:51 UTC, martyngigg commented on Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
>  double FABADAMinimizer::gaussianStep(const double &jump) {
I think I would prefer to have a separate issue for replacing this. It's going to require changes to allow a seed to be passed in and then we'll need to make sure we test it well. I've created #22317 to look at this.

2018-04-20 12:16 UTC, SimonHeybrock approved these changes

2018-04-20 12:52 UTC, rosswhitfield commented
Can you check the VesuvioCorrectionsTest systemtest? I'm guessing it's related. #19782

2018-04-20 13:10 UTC, martyngigg commented
@rosswhitfield Will do. I suspect it is the same problem too. It'll be nice for this not to be an issue in the future!

2018-04-23 07:39 UTC, martyngigg commented
@rosswhitfield I've checked and updated the Vesuvio tests and they now seem to pass for on RHEL7, Ubuntu and Windows. Hopefully this means we have one less source of discrepancy between the OSs.

2018-04-23 07:52 UTC, SimonHeybrock approved these changes

2018-04-23 08:24 UTC, martyngigg commented
@mantidproject/gatekeepers Could we get this merged pretty soon? It updates a fair few files across the framework directory.

2018-04-23 12:45 UTC, rosswhitfield commented
Thanks @martyngigg

2018-04-23 12:45 UTC, merged