Re #21734 Updated reduction packaging
mantidproject/mantid pull request #22253
Opened 2018-04-05 09:25 UTC by Mantid-Matthew

Description of work.

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-22 14:03 UTC, mantid-builder commented
@Mantid-Matthew it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2018-05-23 09:48 UTC, soininen commented
I spotted some layout problems in the settings tab:
![sans-settings-glitches](https://user-images.githubusercontent.com/19147159/40417066-2dd65e62-5e7f-11e8-864b-b7e386b10f72.png)

2018-05-23 10:16 UTC, soininen requested changes
The test procedure described in the description worked flawlessly after I got the data search directories set up correctly. If the reduction fails due to no files found the GUI still seems to go full steam ahead. The only indication of issues is in the logs. Might be worth considering in the future to color the problematic rows with red or orange. Anyway, the code changes look good and clean. Just a few minor comments below.

2018-05-23 10:16 UTC, soininen commented on scripts/SANS/sans/common/general_functions.py
> +    if multi_reduction_type and multi_reduction_type["wavelength_range"] and user_specified_output_name:
Could these three `if` statements be simplified to something like:
```python
if multi_reduction_type and user_specified_output_name:
    if multi_reduction_type["period"]:
        pass
    if multi_reduction_type["event_slice"]:
        pass
    if multi_reduction_type["wavelength_range"]:
        pass
```

2018-05-23 10:16 UTC, soininen commented on scripts/SANS/sans/gui_logic/models/state_gui_model.py
> +    def _update_wavelength(self, min_value=None, max_value=None, step=None, step_type=None, range=None):
`range` is a reserved keyword in Python, might be a good idea to consider something else here.

2018-05-23 10:16 UTC, soininen commented on scripts/SANS/sans/state/state_base.py
> +                                                                               str(value), type(value)))
Are the `str()` conversions needed here? Wouldn't `format()` do this automatically?

2018-05-23 10:45 UTC, Mantid-Matthew commented on scripts/SANS/sans/algorithm_detail/batch_execution.py
> +            group_alg.setChild(False)
Thanks thats good to know. Am I right in thinking that setChild controls the ADS and whether workspace history is stored ? What happens if I setChild to true and setAlwaysStoreInADS to true ?

2018-05-23 10:48 UTC, Mantid-Matthew commented on scripts/SANS/sans/algorithm_detail/batch_execution.py
> +        :param reduction_packages: a list of reduction packages.
is the normal syntax not :param name: ?

2018-05-23 11:07 UTC, soininen commented on scripts/SANS/sans/algorithm_detail/batch_execution.py
> +            group_alg.setChild(False)
`setChild()` indeed controls the ADS and history, `setAlwaysStoreInADS()` gives a bit more fine-grained control. In the background they control the same flag so setting `setAlwaysStoreInADS(True)` after calling `setChild(True)` will put all workspaces to the ADS.

2018-05-23 11:09 UTC, soininen commented on scripts/SANS/sans/algorithm_detail/batch_execution.py
> +        :param reduction_packages: a list of reduction packages.
Yes, of course, my mistake. Sorry for the noise!

2018-05-23 13:58 UTC, soininen commented
I wonder if something went wrong when fixing the glitches since the Wavelength box in the settings view now looks quite differrent; the Ranges field is gone, replaced by Min and Max:
![sans-settings-wavelength-missing-ranges](https://user-images.githubusercontent.com/19147159/40429090-18b1f456-5ea2-11e8-85ed-1099eed12101.png)

2018-05-23 14:22 UTC, Mantid-Matthew commented
The wavelength box should change its appearance depending on which step type you select. For step type Lin and Log what you are seeing is correct however it should change to display a single range box when RangeLin or RangeLog are selected. 

I notice that the Q resolution box is still being cut of for you at the bottom so I'll have another look at that.

2018-05-24 13:42 UTC, soininen approved these changes

2018-05-24 13:42 UTC, soininen commented
The missing range field was indeed a problem on my side. The layout is now fixed. I think is good to go. Great work!

2018-05-25 14:06 UTC, merged