Engineering GUI implement new model for EnggVanadiumCorrections
mantidproject/mantid pull request #22367
Opened 2018-05-02 11:44 UTC by josephframsay

A model for generating and caching the vanadium corrections workspaces (calculated by EnggVanadiumCorrections and used for calibration and focusing) was implemented and integrated into the main presenter of the ED GUI. The intended behaviour was always to cache the workspaces so that we don't need to run EnggVanadiumCorrections (which is slow) for every calibration or focus, but the caching didn't actually appear to happen. The new model takes care if the algorithm and the cache, and also gets unit tests on the behaviour.

**To test:**

There's some sample data [here](https://github.com/mantidproject/mantid/files/1967047/EnggCalibrateAndFocus.zip)

Open up the GUI and go to the Calibration tab. Under **Make new calibration**, select the 280329 run for Vanadium and 280336 for Calibration sample. Click **Calibrate**, and go and make a coffee for a few minutes. Once this is complete, make sure that the two workspaces were saved out (you can see where they were saved in the Calibration field in the Settings tab).

Now go to the Focus tab and select the 281188 run and click **Focus**. Make sure that EnggVanadiumCorrections isn't run by looking in the Algorithm Progress window.

Repeat any of the above steps, and EnggVanadiumCorrections still shouldn't be run

Fixes #17424

**Release Notes** 

Doesn't need to go in the release notes, as it's mostly a refactoring change, and I don't think the scientists were aware that the cache didn't work in the first place

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-28 08:59 UTC, soininen commented
Testing this with the provided test data. `EnggVanadiumCorrections` indeed gets omitted when running the steps the second time. However, the forced recalculation doesn't seems to work: after checking the box in the Settings tab, `EnggVanadiumCorrections` still won't run and the two files `ENGINX00280329_precalculated_vanadium_run_bank_curves.nxs` and `ENGINX00280329_precalculated_vanadium_run_integration.nxs` don't get updated. In fact, if I delete these files I get
```
EnggDiffraction GUI: starting new focusing. This may take some seconds... 
Generating new focusing workspace(s) and file(s) into this directory: 
Generating new focused file (bank 1) for run 281188 into: ENGINX_281188_focused_bank_1.nxs
The focusing failed. Some input properties were not valid. See log messages for details. Error: Invalid value for property Filename (list of str lists) "/users/soininen/ENGINX00280329_precalculated_vanadium_run_bank_curves.nxs": File "/users/soininen/ENGINX00280329_precalculated_vanadium_run_bank_curves.nxs" not found
Generating new focused file (bank 2) for run 281188 into: ENGINX_281188_focused_bank_2.nxs
The focusing failed. Some input properties were not valid. See log messages for details. Error: Invalid value for property Filename (list of str lists) "/users/soininen/ENGINX00280329_precalculated_vanadium_run_bank_curves.nxs": File "/users/soininen/ENGINX00280329_precalculated_vanadium_run_bank_curves.nxs" not found
The focusing did not finish correctly. Check previous log messages for details
```

when running Focus and
```
EnggDiffraction GUI: starting new calibration. This may take a few seconds... 
Generating new calibration file: ENGINX_280329_280336_all_banks.prm
The calibration calculations failed. Some input properties were not valid. See log messages for details. 
The calibration did not finish correctly. Please check previous log messages for details.
```

when calibrating.

Here is how the interface looks for me:
![engg-calibration](https://user-images.githubusercontent.com/19147159/40606584-1fce1982-6266-11e8-8d19-997d056b35c3.png)

![engg-focus](https://user-images.githubusercontent.com/19147159/40606588-23686098-6266-11e8-8131-7dfc27c997e7.png)

![engg-settings](https://user-images.githubusercontent.com/19147159/40606594-2612840e-6266-11e8-93e4-a2bbce4081e9.png)

Am I doing something wrong here?

2018-05-29 09:35 UTC, josephframsay commented
@soininen nope, I missed both of those - nice one! This should be ready for test again

2018-05-29 15:03 UTC, soininen requested changes
The interface works now as promised: `EnggVanadiumCorrections` is only run when needed or specifically requested. The code changes look good and are covered by some unit tests. A few minor comments below.

I did notice, though, that MantidPlot crashes due to unhandled expection if the processing of the interface's algorithms is canceled from the Algorithm process dialog. This should perhaps be investigated and fixed under another issue.

2018-05-29 15:03 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.cpp
> +  const auto vanCurvesWS = vanadiumCorrectionWorkspaces.second;
Not that it matters much performance-wise, but as far as I can see, `vanIntegWS` and `vanCurvesWS` could be references avoiding copying the shared pointers.

2018-05-29 15:03 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.cpp
> +  const auto vanCurvesWS = vanadiumCorrectionWorkspaces.second;
See the above comment about references, maybe it applies here as well?

2018-05-29 15:03 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/EnggVanadiumCorrectionsModel.cpp
> +  return boost::none;
Why not just return a `nullptr`?

2018-05-29 15:03 UTC, soininen commented on qt/scientific_interfaces/EnggDiffraction/EnggVanadiumCorrectionsModel.cpp
> +  const static size_t normalisedRunNumberLength = 8;
How about `constexpr size_t`? Or is this something that could be read from the facility info?

2018-05-29 15:49 UTC, josephframsay commented
Ah, I always forget my `constexpr`s. The problem with MantidPlot crashing is present across the whole GUI except for the GSAS tab - fixing it is way way way out of scope of this PR. I've put in an issue at #22492

2018-05-30 08:32 UTC, soininen approved these changes

2018-05-31 07:49 UTC, merged