Add JobTreeView widget
mantidproject/mantid pull request #22380
Opened 2018-05-04 07:50 UTC by edwardb96

**Description of work**
Adds `JobTreeView` a spreadsheet like adaptation of QTreeView with an MVP style interface.
Part of the work for #22263.

**TODO**
- [ ] Tidy up remaining TODO comments.
- [ ] Fix failing unit tests.
- [ ] Assess the need for and implement remaining unit tests.
- [ ] Add documentation.

**To test:**
1. Ensure passing builds
2. JobTreeView tests via Batch Widget (Experimental) interface.

Refs #22263 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-08 09:38 UTC, martyngigg commented on Framework/Properties/Mantid.properties.template
> +mantidqt.python_interfaces = Direct/DGS_Reduction.py Direct/DGSPlanner.py Direct/PyChop.py Direct/MSlice.py SANS/ORNL_SANS.py Utility/TofConverter.py Reflectometry/ISIS_Reflectometry_Old.py Diffracti
Was it intentional to add this to the interfaces menu?

2018-05-21 17:23 UTC, gemmaguest requested changes
Very nice code and design and works well :+1: :+1:
- The clear code means that for the most part comments are not needed, but a few would be helpful - I've noted places I think they would be most useful
- The new header files should have a comment with a description of the class and the author, date, copyright etc.
- Other than that, just a few minor queries/suggestions

2018-05-23 13:30 UTC, edwardb96 commented on qt/widgets/common/src/Batch/JobTreeView.cpp
> +JobTreeView::applyNavigationResult(QtTreeCursorNavigationResult const &result) {
Added in b9c46e20

2018-05-24 16:01 UTC, gemmaguest approved these changes

2018-05-25 07:13 UTC, merged