Add background scale to WANDPowderReduction
mantidproject/mantid pull request #22388
Opened 2018-05-04 17:10 UTC by rosswhitfield

**To test:**
Look at [usage examples](http://docs.mantidproject.org/nightly/algorithms/WANDPowderReduction-v1.html#usage) and in lieu of background try subtracting silicon from itself with different background scales.
_e.g._
```python
silicon =LoadWAND('/HFIR/HB2C/IPTS-7776/nexus/HB2C_26506.nxs.h5')
vanadium=LoadWAND('/HFIR/HB2C/IPTS-7776/nexus/HB2C_26509.nxs.h5')

WANDPowderReduction(InputWorkspace=silicon,
                    CalibrationWorkspace=vanadium,
                    Target='Theta',
                    NumberBins=1000,
                    OutputWorkspace='silicon_powder')

WANDPowderReduction(InputWorkspace=silicon,
                    BackgroundWorkspace=silicon,
                    BackgroundScale=0.5,
                    CalibrationWorkspace=vanadium,
                    Target='Theta',
                    NumberBins=1000,
                    OutputWorkspace='silicon_powder_bkg')
```
You see that half the intensity has been subtracted as background.
![silicon_background_scaled](https://user-images.githubusercontent.com/5595210/39641387-f7ed02ac-4f9b-11e8-97cc-baf32863bfdf.png)

**Release Notes** 
*Does not need to be in the release notes and the algorithm was only added in this release*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-07 19:28 UTC, AndreiSavici approved these changes

2018-05-08 18:20 UTC, peterfpeterson requested changes
I believe that you missed a validator on the new property. Also, do you want to change the usage example to take advantage of the new property?

2018-05-08 18:20 UTC, peterfpeterson commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/WANDPowderReduction.py
> +        self.declareProperty("BackgroundScale", 1.0,
You probably want to require that this is greater than 0.

2018-05-14 14:43 UTC, peterfpeterson approved these changes

2018-05-14 14:43 UTC, merged