22293 error report refactor
mantidproject/mantid pull request #22449
Opened 2018-05-21 11:54 UTC by Mantid-Matthew

**Description of work**

**To test:**

Fixes #xxxx. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-05-24 08:19 UTC, Mantid-Matthew commented on buildconfig/CMake/DarwinSetup.cmake
> +configure_file ( ${CMAKE_MODULE_PATH}/Packaging/osx/error_dialog_app.py.in
@keeeto do we still need error_dialog_app.py.in ?

2018-06-01 10:20 UTC, martyngigg requested changes
This looks really good now. I think we just need to fix up the exit code situation from the app and then it's good to go.

2018-06-01 10:20 UTC, martyngigg commented on scripts/ErrorReporter/error_dialog_app.py
> +    if not UsageService.isEnabled():
There's a minor issue here that if you have usage reports disabled and the crash happens the exit code of the process is `0`. I think we need to make sure main always returns an integer and then main gets called as `sys.exit(main())` from below.

2018-06-01 10:20 UTC, martyngigg commented on scripts/ErrorReporter/error_dialog_app.py
> +    app.exec_()
I think `return app.exec_()` is then what we want here also.

2018-06-01 15:42 UTC, martyngigg approved these changes
This looks good - let's get it merged and out in the wild.

2018-06-06 05:36 UTC, merged