Improve user error message when GSAS-II installation scripts because SSL is out of date
mantidproject/mantid pull request #22547
Opened 2018-06-06 16:06 UTC by josephframsay

Previously, if a user's version of openssl was pre-1.0, the GSAS-II installation scripts would fail with an unhelpful error message. The user is now advised to make sure that their computer is connected to the internet and that their openssl version is recent enough.

Note, I've not added any documentation for how to upgrade openssl, as there is plenty of help on StackOverflow that will be more valuable than anything I can come up with, but feel free to object if you think that more detail would be better.

The latest vetted GSAS-II revision number was also change to 3392, as several features have been added since the old one (3216) which we use.

**To test:**

From a computer with a pre-1.0 version of openssl (possibly most macs?) try running `python scripts/GSAS-II/install_gsas_proxy.py`. You should see a useful error message. (Run on master first to make sure the message `urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>`)

Fixes #22357

Does this update require release notes?
No, as the change is minor and no users use the installation script anyway

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-06-06 16:07 UTC, josephframsay commented
@samueljackson92 I know you've already assigned yourself to loads of my PRs but I'd appreciate a review on this if you've got time, since I'm not sure who else the script would fail for

2018-06-07 09:43 UTC, samueljackson92 requested changes
Nice message. I have two requests:
 - Can you change the file permissions so it's executable (on osx I had to `chmod +x` before I could run it)
 - Add `#!/usr/bin/env python` to the top of the file.

2018-06-07 10:12 UTC, samueljackson92 approved these changes

2018-06-08 08:35 UTC, merged

2018-06-08 08:43 UTC, SimonHeybrock commented
@josephframsay This seems to have a broken issue link (it closed https://github.com/mantidproject/mantid/pull/22357 accidentially). Which is the correct issue to close?

2018-06-08 11:00 UTC, josephframsay commented
@SimonHeybrock apologies, looks like I got confused. The issue was #22537 - I've now closed it