Fix an issue with zero entry in split TimeSeriesProperty
mantidproject/mantid pull request #22546
Opened 2018-06-06 15:55 UTC by wdzhou

Method splitByTimeVector may generate split TimeSeriesProperty with zero entry.  The behaviour shall be changed such that there shall be at least one entry in each split TimeSeriesProperty instance.

**Report to:** [mdoucet ]. 

**To test:**

```
LoadEventNexus(Filename='/SNS/REF_M/shared/ADARA.Test.Data.2018/REF_M_28131.nxs.h5',
               OutputWorkspace='test31')
               
GenerateEventsFilter(InputWorkspace='test31', OutputWorkspace='filter', InformationWorkspace='filter_info', LogName='SF1',
                     MinimumLogValue=0.9, MaximumLogValue=1.1, LogBoundary='Left')
FilterEvents(InputWorkspace='test31', SplitterWorkspace='filter', OutputWorkspaceBaseName='testtest',
             OutputWorkspaceNames='testtest_unfiltered,testtest_0')
```
In output workspace testtest_0, sample log CurrentSP shall have 1 entry.

Fixes #21836 . 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-06-12 17:54 UTC, mdoucet approved these changes
I tested it with a data set that previously failed and it worked as expected.

2018-06-13 17:28 UTC, quantumsteve commented
Please remove old, commented out code.

2018-06-14 05:38 UTC, SimonHeybrock requested changes
A couple of small comments:

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Algorithms/inc/MantidAlgorithms/FilterEvents.h
> +  //      const int max_target_index);
Leftover commented code?

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Algorithms/test/FilterEventsTest.h
> +    // std::cout << "Add splitters: " << t0 << ", " << t1 << ", " << 0 << "\n";
More commented code.

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Algorithms/test/FilterEventsTest.h
> +    // std::cout << "Add splitters: " << t0 << ", " << t1 << ", " << 1 << "\n";
.

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +  // tps_time is start time of time series property
`tsp_time`

Also, it does not show up until 20 lines further down. Move the comment there?

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +  //
Empty comment line.

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Kernel/src/TimeSeriesProperty.cpp
> +  // splitters.
What is "It"? I do not understand the comment.

2018-06-14 05:38 UTC, SimonHeybrock commented on Framework/Kernel/test/TimeSeriesPropertyTest.h
> +  void Throw_test_splitByTimeVectorEarlySplitter() {
Is this test disabled? Why?

2018-06-15 06:22 UTC, SimonHeybrock approved these changes

2018-06-15 12:39 UTC, merged