Indirect - ISISEnergyTransfer - Custom Detector Grouping Option
mantidproject/mantid pull request #22565
Opened 2018-06-12 12:47 UTC by MatthewBowles

Replaces default option for detector grouping in the `ISISEnergyTransfer' interface with a 'Custom' option that allows specific spectra or ranges to be entered.

**Report to:**  @brandonhewer
 
**To test:**
- Navigate to Interfaces -> Indirect -> Data Reduction
- Enter a file to load e.g. `IRS26176`
- In Detector Grouping, check 'Custom' is selected by default
- Check the line edit box next to 'Custom' is only present when 'Custom' is selected
- Enter spectra and/or a range in this box: `1, 2, 4-7`
- The resulting workspace should contain only the spectra specified (+ spectra min): `55, 56, 58-61`

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-06-13 15:54 UTC, KarlPalmen commented on qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
>        createMapFile(m_uiForm.cbGroupingOptions->currentText());
I get a compilation error here concerning type conversion between QString and const std::string.

2018-06-13 15:55 UTC, KarlPalmen commented on qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
>      return qMakePair(groupType, QString());
I get a compilation error here about conversion between QPair and std::pair here.

2018-06-13 16:15 UTC, KarlPalmen commented
I don't see any "custom" in the Detector Grouping. I see "default" selected by default.

2018-06-13 16:20 UTC, KarlPalmen commented
I had my default facility set to ILL for previous test. Setting it back to ISIS and instrument to IRIS made custom appear as described.

2018-06-13 16:21 UTC, MatthewBowles commented
That's weird. It's clearly changed [here](https://github.com/mantidproject/mantid/pull/22565/files#diff-48cd8b084a7a38294e273ca24e745a01R218).

2018-06-13 16:31 UTC, KarlPalmen commented
The crash occurred again on retry. I used `irs26176_graphite002_red.nxs` .

2018-06-13 16:36 UTC, KarlPalmen commented
Looks like you may be assigning an incorrect type as a `minimum spectrum` property in this case and this exception is not caught.

2018-06-13 17:10 UTC, SpencerHowells commented
Data reduction uses a RAW file NOT a *_red.nxs file. Typing the run number is the method of entry.

2018-06-13 17:13 UTC, SpencerHowells commented
Also, this interface is not used by ILL - they have their own version.

2018-06-14 07:57 UTC, SpencerHowells commented
Further to the ILL version, if the default Facility is set to ILL then launching Data Reduction will give a GUI specific to ILL. The aim is to do this for all Facilities which want to use this GUI.

2018-06-14 07:58 UTC, KarlPalmen commented
If typing a run number is the only method of entry, I would not expect a file browser to be available. If one does want to support file selection, then the set of file types needs to be limited appropeiately (e.g to .raw). This may be beyond the scope of thjis issue.

2018-06-14 08:48 UTC, KarlPalmen commented
I got the desired functionality after selecting the raw file for run 57093, but the workspace only had 'nan' in it, which might not be related to this issue. If I just type a number, I get invalid runs.

2018-06-14 08:50 UTC, KarlPalmen commented
I got numeric data in the workspace from run 57907 (selected as raw file).

2018-06-14 08:52 UTC, KarlPalmen commented
If you can easily change the default file type in the file browser to "*.raw", please do so (assuming only 'raw' file are valid).

2018-06-14 08:53 UTC, KarlPalmen commented
I don't see any update of the documentation for the Indirect interface.

2018-06-14 09:16 UTC, KarlPalmen commented
I'll approve this change, when I see a good documentation update.

2018-06-14 09:46 UTC, SpencerHowells commented
When Browsing you can select a RAW file - we usually test on iris26176.raw.

2018-06-14 09:50 UTC, SpencerHowells commented
Browse filters on *.nxs, *.raw & *.sav which are all raw files. The nxs file would be eg iris26176.nxs.

2018-06-14 12:32 UTC, KarlPalmen requested changes

2018-06-14 12:32 UTC, KarlPalmen commented on docs/source/release/v3.13.0/indirect_inelastic.rst
Should it not be `Added` instead of `Add` as in previous item?

2018-06-14 12:40 UTC, KarlPalmen approved these changes

2018-06-21 12:05 UTC, merged

2018-06-21 12:05 UTC, SimonHeybrock commented
@brandonhewer Merged.