Add summation in Q to ILL's reflectometry reduction
mantidproject/mantid pull request #22650
Opened 2018-06-22 13:27 UTC by soininen

This PR adds a previously missing 'SumInQ' option to `ReflectometryILLSumForeground`. The option enables summation in Q, also know as coherent summation.

There were a few modifications to the overal reduction workflow. Most importantly cropping in wavelength was moved to the end of `ReflectometryILLSumForeground` from `ReflectometryILLPreprocess`.

The wavelength ranges were removed from `ReflectometrySumInQ` and an option to exclude partial bins following #22541 was added.

The changes to algorithm properties and thus the API should not affect any users since none of the algorithms touched here have seen any use outside the development team and test user at ILL.

**Report to:** nobody.

**To test:**

The following script could be used as a starting point for testing. Note that the default facility should be set to ILL and the unit test data directories should be included in Mantid's data search directories before running the script.

```python
ReflectometryILLPreprocess(
    Run='ILL/D17/317369.nxs',
    OutputWorkspace='direct-raw',
    ForegroundHalfWidth=[3],
    OutputBeamPositionWorkspace='direct-beamPos')
ReflectometryILLPreprocess(
    Run='ILL/D17/317370.nxs',
    OutputWorkspace='reflected-raw',
    ForegroundHalfWidth=[3, 4],
    BeamPositionWorkspace='direct-beamPos')
ReflectometryILLSumForeground(
    InputWorkspace='direct-raw',
    OutputWorkspace='direct-fgd')
ReflectometryILLSumForeground(
    InputWorkspace='reflected-raw',
    OutputWorkspace='reflectivity',
    WavelengthRange=[2., 14.],
    SummationType='SumInQ',
    DirectForegroundWorkspace='direct-fgd')
```

Fixes #22315.

Does this update require release notes?
- [x] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-06-28 13:34 UTC, vreimund approved these changes
Tested reduction work-flow for reflectometry data and it works fine.

2018-06-28 14:42 UTC, peterfpeterson commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometrySumInQ.h
> +    double horizon{std::nan("")};
Please change this to [`std::numeric_limits<double>::quiet_NaN()`](https://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN).

2018-06-28 14:43 UTC, peterfpeterson commented on Framework/Algorithms/src/ReflectometrySumInQ.cpp
> +  if (a > max) {
Isn't this just `max = std::max(a,max)`?

2018-06-28 14:43 UTC, peterfpeterson commented on Framework/Algorithms/src/ReflectometrySumInQ.cpp
> +  if (a < min) {
Isn't this just `min = std::min(a,min)`?

2018-06-28 14:57 UTC, peterfpeterson requested changes
A couple of super-small changes and I'll merge it.

2018-06-29 12:10 UTC, peterfpeterson approved these changes

2018-06-29 12:11 UTC, merged