Live data monitoring on reflectometry GUI
mantidproject/mantid pull request #22692
Opened 2018-06-27 17:01 UTC by gemmaguest

This PR adds a button to start live data monitoring on the `ISIS Reflectometry` GUI. 

**Report to:** Max at ISIS

**To test:**

To follow

Fixes #18828 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-01 14:03 UTC, mantid-builder commented
@gemmaguest the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-09-04 14:03 UTC, mantid-builder commented
@gemmaguest it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2018-09-18 09:05 UTC, Mantid-Matthew commented on Framework/PythonInterface/plugins/algorithms/GetLiveInstrumentValue.py
> +        from epics import caget
Could we surround this import statement by a try/catch block to provide a more useful error message?

2018-09-18 10:37 UTC, Matthew-Andrew requested changes
Looks good to me, the testing worked as expected and code changes good and well tested. One minor picky point but should then be good to go.

2018-09-18 10:37 UTC, Mantid-Matthew commented on Framework/PythonInterface/plugins/algorithms/GetLiveInstrumentValue.py
> +        except:
Could I be picky here and ask that we use a more specific exception type? Minor point but I think it is better to state the specific exception you are expecting where possible. For example in this case I think `except ImportError:` should work. 

Would it also be worth pointing them towards the relevant documentation here?

2018-09-18 14:53 UTC, Matthew-Andrew approved these changes
All looks good to me

2018-09-19 08:29 UTC, merged