RROA takes polarization correction parameters from parameters file
mantidproject/mantid pull request #22701
Opened 2018-06-28 14:48 UTC by mantid-roman

**Description of work.**

Added an algorithm that extracts polarization correction parameters from the instrument parameters file and use it to set the correction properties.

**Report to:** [user name]/[nobody]. 

**To test:**

?

Fixes #22500

Does this update require release notes?
- [X] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-03 09:58 UTC, martyngigg commented
@mantid-roman Can you provide some test instructions please.

@gemmaguest @edwardb96 Would either of you have time to review this?

2018-07-04 16:16 UTC, gemmaguest requested changes
Looks good to me :+1: I'm still testing but so far it works as expected. Just some minor typos to fix.

2018-07-05 09:32 UTC, gemmaguest approved these changes

2018-07-05 09:45 UTC, gemmaguest commented
This all looks good now and works as expected :+1:

I tested the new algorithm directly and also via the GUI. It handles incorrect inputs to the algorithm well, as well as handling incorrect settings in the parameters file. Existing GUI functionality also still works as expected. The ability to specify coefficients for the efficiencies has been kept on the GUI and still functions as before, with the exception that the coefficients can no longer be specified in the parameters file, which is as agreed with scientists.

2018-07-05 10:40 UTC, merged