MSlice Fixes for 3.13
mantidproject/mantid pull request #22830
Opened 2018-07-09 10:25 UTC by martyngigg

**Description of work.**

Bring in minor fixes for mslice.

**To test:**

* Start mslice from the `Interfaces/Direct` menu
* Play with slices/cuts

*No associated issue*

Does this update require release notes?
- [ ] Yes
- [X] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-10 08:52 UTC, NickDraper commented
@MatthewBowles You are the best person to test this, do you have some time today?

2018-07-13 14:18 UTC, samueljackson92 commented
Another issue found from unscripted testing. https://github.com/mantidproject/mslice/issues/342

2018-07-13 16:09 UTC, mducle commented
The release notes should also say that now MSlice workspaces are not stored in the `ADS` so they are invisible from MantidPlot. As some people may want to fit 1D cuts produce by MSlice using the MantidPlot algorithm, there should be a way to export an MSlice workspace to the `ADS` - which can be addressed as part of https://github.com/mantidproject/mslice/issues/341

2018-07-13 16:54 UTC, AndreiSavici requested changes

2018-07-13 16:54 UTC, AndreiSavici commented on scripts/ExternalInterfaces/CMakeLists.txt
> +  GIT_TAG a1c96d5d325b30e2537c5784a133c5284a936468
Should be ce0a3647d111bc31fafd00addb64913760828352

2018-07-13 21:59 UTC, AndreiSavici commented on scripts/ExternalInterfaces/CMakeLists.txt
> +  GIT_TAG a1c96d5d325b30e2537c5784a133c5284a936468
Or later, if more PRs are merged in

2018-07-16 22:45 UTC, AndreiSavici approved these changes

2018-07-16 22:47 UTC, AndreiSavici commented
I've approved the changes. It might need to be modified again, if https://github.com/mantidproject/mslice/issues/347 is addressed.

2018-07-17 06:52 UTC, martyngigg commented
@MatthewBowles Would you be able to add some release notes to this branch?

2018-07-17 08:52 UTC, merged