TOFTOF GUI added testing automation
mantidproject/mantid pull request #22836
Opened 2018-07-09 13:52 UTC by JoachimCoenen

**Description of work.**
added `TOFTOFGUITest.py` and `TOFTOFScriptElementTest.py` under `scripts/test/TOFTOF/`

**To test:**

`TOFTOFGUITest.py` and `TOFTOFScriptElementTest.py` tests get executed and pass without failure.

Fixes #22791. 

Does this update require release notes?
- [ ] Yes
- [ ] No

Milestone: 3.14

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-10 13:47 UTC, mganeva commented
Label: In Progress. I need some time to test it.

2018-08-22 13:40 UTC, soininen requested changes
Good to have some unit tests for the TOFTOF interface. The tests pass and the changes look generally good. Below are a few minor comments.

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFGUITest.py
> +        self.settingsMock.facility_name = facility_name
Why not `self.settingsMock.facility_name = "name of facility"`? Ditto for instrument name below.

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFGUITest.py
> +        #done
Commented-out code?

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFGUITest.py
> +    #def test_that_init_works_correctly(self):
Commented-out code?

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFGUITest.py
> +import mantid
Please, run `flake8` on the test files: it says, for example, that `mantid` is an unused import.

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFGUITest.py
> +            [u'TOFTOFTestdata.nxs', u'H2O 34C', OptionalFloat(34.0)]
Just a note: my understanding is that the `u` prefix for strings is a syntax error in early Python 3 versions (3.0, 3.2?). I hope when Mantid finally moves to Python 3 everyone will be running a later version...

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFScriptElementTest.py
> +        exec('from mantid.simpleapi import *\n' + self.scriptElement.to_script(), dict(), dict())
There don't seem to be any asserts in this test. What is it testing then?

2018-08-22 13:40 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFScriptElementTest.py
> +        def executeSubTest(inputs, shoudThrow):
`shoudThrow` -> `shouldThrow`?

2018-08-24 08:49 UTC, soininen commented
We have moved to `clang-format 5.0`, please merge master to this branch. And a small note for the future: please explain the changes in the commit messages, 'fixing requested changes' does not really tell what the commit is about.

2018-08-24 10:54 UTC, JoachimCoenen commented
ok.

2018-08-28 14:21 UTC, soininen requested changes

2018-09-04 09:59 UTC, soininen commented on scripts/test/TOFTOF/TOFTOFScriptElementTest.py
> +        #    exec('from mantid.simpleapi import *\n' + self.scriptElement.to_script(), dict(), dict())
Commented-out code?

2018-09-06 13:10 UTC, soininen approved these changes

2018-09-06 14:20 UTC, merged