Allow user to specify max iterations and make partial spectra fitting more flexible.
mantidproject/mantid pull request #22865
Opened 2018-07-11 02:49 UTC by wdzhou

**Description of work.**

This fixes #22860.

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #xxxx. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-01 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-08-15 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-08-29 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-09-12 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-09-26 14:03 UTC, mantid-builder commented
@wdzhou the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-10-10 14:03 UTC, mantid-builder commented
@wdzhou do you want to request a review on this PR?
<!-- {"problem_type": "unreviewed"} -->

2018-11-01 14:03 UTC, mantid-builder commented
@wdzhou it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2018-11-28 15:55 UTC, peterfpeterson requested changes
Lots of minor changes. One suggestion (for a separate PR) is to change the tests to use [CreateSampleWorkspace](http://docs.mantidproject.org/nightly/algorithms/CreateSampleWorkspace-v1.html) with `Function='Powder Diffraction'` which could simplify the tests.

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/src/FitPeaks.cpp
> + * @brief PeakFitResult::getParameterError
remove empty docs

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/src/FitPeaks.cpp
> + * @brief PeakFitResult::getParameterValue
remove empty docs

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/src/FitPeaks.cpp
> +          "is chosen to be output.";
remove `.` at the end of the sentence

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/src/FitPeaks.cpp
> +  fit->setProperty("MaxIterations", m_fitIterations); // magic number
I like that this is being exposed as a parameter to the user

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/src/FitPeaks.cpp
> + * @brief FitPeaks::reduceByBackground
remove empty parameter docs

2018-11-28 15:55 UTC, peterfpeterson commented on Framework/Algorithms/test/FitPeaksTest.h
> +   * @brief genFitWindowWorkspace
remove empty docstring

2018-11-29 02:49 UTC, wdzhou commented on Framework/Algorithms/src/FitPeaks.cpp
> +  double chi2(DBL_MAX);
double chi2(DBL_MAX) is C++ standard; 
double chi2{DB_MAX} is introduced in C++ 11.

2018-11-29 15:50 UTC, peterfpeterson submitted a review, later dismissed
Looks good now

2018-11-30 10:56 UTC, soininen requested changes

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +  std::string error_table_name =
```suggestion
  const std::string error_table_name =
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +    bool use_raw_params = getProperty("RawPeakParameters");
```suggestion
    const bool use_raw_params = getProperty("RawPeakParameters");
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +  if (error_table_name != "") {
```suggestion
  if (!error_table_name.empty()) {
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +      std::string msg =
```suggestion
      `const` std::string msg =
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +                    << m_inputMatrixWS->getNumberHistograms() << " spectra;"
```suggestion
                    << m_inputMatrixWS->getNumberHistograms() << " spectra; "
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +  double chi2{DBL_MAX};
```suggestion
  double chi2{std::numeric_limits<double>::max()};
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +    param_vec.push_back("intensity");
All `push_back`s could be replaced by `emplace_back`

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +    param_vec.push_back(m_bkgdFunction->parameterName(iparam));
```suggestion
    param_vec.emplace_back(m_bkgdFunction->parameterName(iparam));
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +  std::string fiterror_table_name =
```suggestion
  const std::string fiterror_table_name =
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/src/FitPeaks.cpp
> +  if (fiterror_table_name == "") {
```suggestion
  if (fiterror_table_name.empty()) {
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +    std::string data_ws_name("Test1Data");
`const`?

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +    std::string fit_window_ws_name =
The above `string`s could be declared `const`.

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +          peak_center = 10.0;
This if-else could be replaced by
```c++
const double peak_centre = peak_index == 0 ? 5.0 : 10.0;
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +        int peak_index = peak_index_vec[j];
```suggestion
        const int peak_index = peak_index_vec[j];
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +    size_t num_peaks = peak_index_vec.size();
```suggestion
    const size_t num_peaks = peak_index_vec.size();
```

2018-11-30 10:56 UTC, soininen commented on Framework/Algorithms/test/FitPeaksTest.h
> +          peak_center = 10.0;
See the above comments about the if-else and `const`.

2018-12-03 14:44 UTC, soininen approved these changes

2018-12-03 15:31 UTC, martyngigg commented
There seem to be some compiler warnings on clang: http://builds.mantidproject.org/job/pull_requests-osx/25459/warnings14Result/

2018-12-03 16:25 UTC, merged