D2B : add new IPF for the latest cycle
mantidproject/mantid pull request #22899
Opened 2018-07-12 14:58 UTC by gvardany

**Description of work.**

This commits new IPF and IDF for D2B valid from 2018 May 1st containing a recent tube alignment measurement from the latest cycle.

**Report to:** ILL/Cuello. 

**To test:**

Check the valid-from dates to match. 

No issue.

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-13 14:47 UTC, KarlPalmen commented on instrument/D2B_Definition_2018-05-01.xml
> +valid-to="2100-01-31 23:59:59" last-modified="2018-03-20 14:05:02">
Do you really mean `valid-from="2018-05-01 23:59:59`?

2018-07-13 14:48 UTC, KarlPalmen commented on instrument/D2B_Parameters_2018-05-01.xml
> +	<component-link name="D2B">
Matches valid from date in IDF

2018-07-13 14:53 UTC, KarlPalmen requested changes
The dates are consistent, but suspicious to me. Do you want the files to be valid from one second before the start of 2 May?

2018-07-16 06:32 UTC, gvardany commented
The cycle started mid May, and the previous one ended 26 April, so it just has to be something in between.

2018-07-16 08:45 UTC, KarlPalmen approved these changes

2018-07-16 19:52 UTC, merged