Fix RPATH issues on Ubuntu 18.04
mantidproject/mantid pull request #23003
Opened 2018-07-18 17:51 UTC by quantumsteve

**Description of work.**

This changes the `LINUX_INSTALL_RPATH` to match the library's location. For reasons I don't understand, the location of the executable isn't being used on Ubuntu 18.04.

**Report to:** [user name]/[nobody]. 

**To test:**

1. Build or obtain a .deb package with these changes.
1. Install .deb package on an Ubuntu 18.04 machine
1. Start up MantidPlot and verify there are no warnings about missing libraries
1. Use `ldd` to verify that all shared libraries are found. 

There is no GitHub issue associated with this pull request.

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-18 18:15 UTC, rosswhitfield approved these changes

2018-07-18 18:45 UTC, peterfpeterson submitted a review, later dismissed
Running `bin/MantidPlot` directly on a clean RHEL7 build works.

2018-07-18 19:51 UTC, quantumsteve commented
Issues finding ParaView libraries remain.
```
      3486:	find library=libvtkPVServerManagerCore-pv5.4.so.1 [0]; searching
      3486:	 search path=/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/haswell:/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/x86_64:/usr/lib/x86_64-linux-gnu/hdf5/serial/tls:/usr/lib/x86_64-linux-gnu/hdf5/serial/haswell/x86_64:/usr/lib/x86_64-linux-gnu/hdf5/serial/haswell:/usr/lib/x86_64-linux-gnu/hdf5/serial/x86_64:/usr/lib/x86_64-linux-gnu/hdf5/serial		(RUNPATH from file /opt/mantidunstable/bin/../lib/paraview-5.4/libvtkPVServerManagerRendering-pv5.4.so.1)
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/tls/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/hdf5/serial/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	 search cache=/etc/ld.so.cache
      3486:	 search path=/lib/x86_64-linux-gnu/tls/haswell/x86_64:/lib/x86_64-linux-gnu/tls/haswell:/lib/x86_64-linux-gnu/tls/x86_64:/lib/x86_64-linux-gnu/tls:/lib/x86_64-linux-gnu/haswell/x86_64:/lib/x86_64-linux-gnu/haswell:/lib/x86_64-linux-gnu/x86_64:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/haswell/x86_64:/usr/lib/x86_64-linux-gnu/haswell:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu:/lib/tls/haswell/x86_64:/lib/tls/haswell:/lib/tls/x86_64:/lib/tls:/lib/haswell/x86_64:/lib/haswell:/lib/x86_64:/lib:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib		(system search path)
      3486:	  trying file=/lib/x86_64-linux-gnu/tls/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/tls/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/tls/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/tls/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64-linux-gnu/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/tls/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/tls/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/tls/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64-linux-gnu/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/tls/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/tls/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/tls/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/tls/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/lib/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/tls/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/tls/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/tls/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/tls/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/haswell/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/haswell/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/x86_64/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	  trying file=/usr/lib/libvtkPVServerManagerCore-pv5.4.so.1
      3486:	
./MantidPlot_exe: error while loading shared libraries: libvtkPVServerManagerCore-pv5.4.so.1: cannot open shared object file: No such file or directory
```

2018-07-18 20:29 UTC, quantumsteve commented
I imagine we could do something like this, but hoping there is a better way.
https://public.kitware.com/pipermail/paraview/2011-November/023233.html

2018-07-18 20:49 UTC, rosswhitfield requested changes
Yep. I tried this time with paraview and it gives me the same errors.

2018-07-19 11:08 UTC, martyngigg commented
https://blog.qt.io/blog/2011/10/28/rpath-and-runpath/ is an interesting read. At the end it basically says don't use `RUNPATH` use `RPATH`. So is it cmake that is setting the `RUNPATH`?

2018-07-19 12:39 UTC, peterfpeterson commented
We're configuring cmake's `LINUX_INSTALL_RPATH` which looks like the right thing according to [the docs](https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_RPATH.html).

2018-07-19 13:05 UTC, martyngigg commented
Agreed. Presumable CMake are doing something different?

2018-07-19 14:33 UTC, martyngigg commented
The `ld` change would explain why `18.04` only specifies `-rpath-link` and not `rpath` when linking. Can we override pass `--disable-new-dtags`?

2018-07-19 14:58 UTC, NickDraper commented
Moved to r3.14, or at least a nightly as soon as it is available.  I'll update the supported environments page to state that we will support 18.04 as soon as we have a working deb package.

2018-07-19 15:48 UTC, rosswhitfield commented
Setting
```
CMAKE_EXE_LINKER_FLAGS=-Wl,--disable-new-dtags
CMAKE_MODULE_LINKER_FLAGS=-Wl,--disable-new-dtags
CMAKE_SHARED_LINKER_FLAGS=-Wl,--disable-new-dtags
```

works without paraview but with it fails with the same problem

```
/opt/mantidunstable/bin/MantidPlot_exe: error while loading shared libraries: libvtkPVServerManagerCore-pv5.4.so.1: cannot open shared object file: No such file or directory
FrameworkManager-[Notice] Welcome to Mantid 3.13.20180719.1516
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
DllOpen-[Error] Could not open library /opt/mantidunstable/plugins/libMantidVatesAlgorithms.so: libvtkIOLegacy-pv5.4.so.1: cannot open shared object file: No such file or directory
DllOpen-[Error] Could not open library /opt/mantidunstable/plugins/libMantidVatesAlgorithms.so: libvtkIOLegacy-pv5.4.so.1: cannot open shared object file: No such file or directory
```

I think we will need to rebuild paraview with `--disable-new-dtags` also?

2018-07-19 15:52 UTC, quantumsteve commented
Works after also rebuilding ParaView with `--disable-new-dtags`

2018-07-19 21:57 UTC, quantumsteve commented
I believe that the changes in this branch and those in `paraview-build` are sufficient to generate a working .deb package for Ubuntu 18.04.

2018-07-20 06:57 UTC, martyngigg commented
Awesome!

2018-07-20 13:07 UTC, AndreiSavici reviewed
Works on a18.04. I've tested it on my laptop, without paraview

2018-07-20 13:08 UTC, rosswhitfield approved these changes
I rebuilt paraview and it all works now. Tested both python 2 and 3 on Ubuntu 18.04.

2018-07-23 12:06 UTC, merged