Caught exception in ICat
mantidproject/mantid pull request #23007
Opened 2018-07-19 09:24 UTC by SamJenkins1

Caught unhandled exception in ICat caused by passing an invalid date.

Fixes #18529

**Description of work.**

**To test:**

See Linked Issue

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-26 08:16 UTC, martyngigg requested changes
This indeed captures the exception correctly and we get the red validation makers as expected.

I seem to have an issue on my Ubuntu version though where the tooltip text colour/background are not set correctly so you then can't read the message:

![icatsearchtooltip](https://user-images.githubusercontent.com/733773/43250092-6cba2f52-90b4-11e8-96f5-7dbf69e0835f.png)

I believe @Mantid-Matthew has some experience of this. Could you see if this might be a simple fix here?

2018-07-26 08:43 UTC, SamJenkins1 commented
I don't seem to be able to reproduce the error on my Lubuntu VM, but I've asked @Mantid-Matthew about it. If it isn't a simple fix, should I create a new issue for it?

2018-07-26 09:38 UTC, SamJenkins1 commented
are you using gnome or unity?

2018-07-26 09:40 UTC, martyngigg commented
Gnome.

2018-07-26 12:07 UTC, SamJenkins1 commented
Made some changed, but I can't test if it worked to fix the tooltips since lubuntu runs in LXDE not gnome or Unity.

2018-07-26 12:13 UTC, SamJenkins1 commented
can you find out what this `QString::fromLocal8Bit(qgetenv("XDG_CURRENT_DESKTOP"))` and this `QString::fromLocal8Bit(Qgetenv("XDG_SESSION_DESKTOP"))`return on your computer? if they return gnome then the other issue that was similar might also need updating as it currently checks whether it needs to act by checking if either of those return "Unity"

2018-07-26 12:16 UTC, Mantid-Matthew commented
On my Ubuntu 16.04 Unity machine, XDG_SESSION_DESKTOP returns Ubuntu whilst XDG_CURRENT_DESKTOP returns Unity

2018-07-26 12:51 UTC, SamJenkins1 commented
From looking into the following comment, it looks like this probably deserves to be its own issue
```
  On Linux Fedora 26+ and Ubuntu 14.4+ the palette colour for
  ToolTipBase has no effect on the colour of tooltips, but does change
  the colour of 'What's This' boxes and and Line Edit hints. The palette
  colour for ToolTipText on the other hand affects all three of
  these.

  The default pallete shows light text on a pale background which, although not
  affecting tooltips, makes LineEdit hints and 'What's This' boxes difficuilt
  if not impossible to read.

  Changing the tooltip text to a darker colour fixes the problem for 'LineEdit'
  hints and 'What's This' boxes but creates one for ordinary tooltips.

  Setting the tooltip background colour to a darker colour works fine on
  Fedora 26-7+ and Ubuntu 14.04 but not for RHEL7 where the tooltip text
  colour is also dark.

  One option is to simply hardcode the values to a dark-on-light colour
  scheme which works consistently on Fedora, Ubuntu and RHEL7.
  However, RHEL7 users were not happy with this solution.

  Further investigation revealed that the issue may be related to
  https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/877236 and the
  fact that in the qt source gui/styles/qgtkstyle.cpp ~line 299 only loads
  the ToolTipText colour, leaving ToolTibBase to the default from
  CleanLooksStyle.

  This problem can be worked around on fedora by switching to the
  Adwaita theme in Mantid Preferences. However, the adwaita-qt
  theme is not available on certain versions of Ubuntu.

  Any easy solution for now is to detect unity clients and apply the
  fix only to them.
```
Since the problem is occurring for you on gnome, not unity, it looks like this is a different issue, as the other example of this being fixed was done on unity, and actually broke it on gnome until a check was added to prevent it from happening on gnome, as such solving this problem appears to be non-trivial and should probably be its own issue.

2018-07-26 13:03 UTC, SamJenkins1 commented
for now I've reverted this back to just fixing the exception, since my attempt at fixing the tooltips only confused things

2018-07-30 07:38 UTC, martyngigg approved these changes

2018-07-30 07:38 UTC, merged