23031 tf crash
mantidproject/mantid pull request #23054
Opened 2018-07-23 11:42 UTC by AnthonyLim23

Fixes the bugs found in Muon Analysis due to TF asymmetry mode. 

**To test:**

Muon Analysis with 1 workspace in multi fit
1. Open muon analysis
2. Make sure multiple fitting is on in the settings tab
3. On the home tab load MUSR 62260
4. Go to data analysis
5. Change the group selection to custom -> make sure only one is selected in the pop up (e.g. fwd)
6. Add a fitting function
7. Turn on TFAsymm mode
8. It should now work (not crash)

No function in Muon Analysis
1. Open muon analysis
2. Make sure multiple fitting is off in the settings tab
3. On the home tab load MUSR 62260
4. Go to data analysis
5. Turn on TFAsymm mode
6. It should now work (not crash)
7. Clicking somewhere else will update the tick box

Zeros in calculateMuonAsymmetry
1. Open muon analysis
2. Make sure multiple fitting is off in the settings tab
3. On the home tab load MUSR 62260
4. Go to data analysis
5. Add a fitting function
6. Do a few fits to get good parameters
7. Turn on TFAsymm mode
8. Set the first flat background to 0 and fix it
9. Do a fit
10. It should have a useful error message at the top of the fitting menu

Fixes #23031. 

Does this update require release notes?
- [ ] Yes
- [ x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-07-23 13:41 UTC, NickDraper commented
Crash still present on following the first testing example

MantidQtWidgetsCommonQt4.dll!MantidQt::MantidWidgets::MuonFitPropertyBrowser::ConvertFitFunctionForMuonTFAsymmetry(bool enabled) Line 1194

2018-07-23 13:42 UTC, NickDraper submitted a review, later dismissed
Crash on 1st example

2018-07-23 13:44 UTC, AnthonyLim23 commented
is the crash the first of my examples or from the issue?

2018-07-23 13:46 UTC, NickDraper commented
Anthony Ignore that crash comment, the brach had not merged cleanly so I was testing the previous state.

2018-07-23 14:04 UTC, NickDraper requested changes

2018-07-23 14:04 UTC, NickDraper commented on qt/widgets/common/src/MuonFitPropertyBrowser.cpp
> +    g_log.warning("No fitting function provided. Please add a function");
This is too invisible, and does not mention what it is in relation to, or that TF asymmetry mode has been turned off.

I suggest, you use a messagebox with a message like
"No fitting function provided. ~TF Asymmetry mode needs a function added before enabling, Add a function and enable TF Asymmetry Mode again."

2018-07-23 14:20 UTC, NickDraper commented
Another crash:

1. Run example 1
1. Go to the settings tab
1. Disable multiple fitting
1. Return to the data analysis tab
1. Bang.  	Null pointer exception MantidMuon.dll!Mantid::Muon::ConvertFitFunctionForMuonTFAsymmetry::extractUserFunction(const boost::shared_ptr<Mantid::API::IFunction> & TFFuncIn) Line 254

2018-07-23 15:07 UTC, NickDraper commented
Example 3 - Is this the error message you were expecting?
![image](https://user-images.githubusercontent.com/1017173/43085236-5f924e0a-8e92-11e8-83a3-9ef9cfa8cbb0.png)

Deviations from testing notes:

1. It isn't at the top of the fitting menu
1. Calling this a useful error message is quite a stretch

2018-07-23 15:15 UTC, NickDraper approved these changes

2018-07-23 15:15 UTC, NickDraper commented
Good to go, some areas for future improvement, but this is good enough for the release

2018-07-24 07:58 UTC, martyngigg requested changes
There is a documentation build warning in the muon.rst

2018-07-24 13:55 UTC, martyngigg approved these changes

2018-07-24 13:55 UTC, merged