Updateing table model and view Re #23022
mantidproject/mantid pull request #23139
Opened 2018-07-31 09:19 UTC by Mantid-Matthew

**Description of work.**

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #xxxx. 

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-07 07:18 UTC, gemmaguest commented
I get this on trying to open the GUI:
```
AttributeError: 'MainPresenter' object has no attribute 'get_gui_algorithm_name'
  at line 19 in '<Interface>'
  caused by line 131 in '/opt/mantidnightly/scripts/Interface/ui/sans_isis/sans_data_processor_gui.py'
```

2018-08-07 12:26 UTC, Mantid-Matthew commented
Hmm


It looks like it is trying to use a file from a nightly build which will still be looking for a load of old stuff.

I've had something similar previously and found I had to clear out the directories I was searching for python files in the properties.user file. This is the one in .mantid on linux or in %appdata% on windows.


Does that do anything ?

________________________________
From: Gemma Guest <notifications@github.com>
Sent: 07 August 2018 08:18:38
To: mantidproject/mantid
Cc: Andrew, Matthew (Tessella,RAL,ISIS); Author
Subject: Re: [mantidproject/mantid] Updating sans GUI table (#23139)


I get this on trying to open the GUI:

AttributeError: 'MainPresenter' object has no attribute 'get_gui_algorithm_name'
  at line 19 in '<Interface>'
  caused by line 131 in '/opt/mantidnightly/scripts/Interface/ui/sans_isis/sans_data_processor_gui.py'


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mantidproject/mantid/pull/23139#issuecomment-410958986>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AekuVql1-NXGMbscmE2tJMVAIkXoMMdVks5uOT9NgaJpZM4Vn5Hl>.

2018-08-08 10:31 UTC, gemmaguest requested changes
Looks good to me :+1:

Just one file which looks like it's been changed accidentally which would be good to revert to avoid confusion.

Also just to note, the HintingLineEdit is not implemented so the Options column does not show tooltips. It also doesn't reject invalid input. (However, valid input is used correctly.) As this is merging to a feature branch it's fine to add the missing behaviour in a future PR.

2018-08-08 10:31 UTC, gemmaguest commented on MantidPlot/src/ProjectRecovery.cpp
> +
Was this file supposed to be changed?

2018-08-08 13:02 UTC, gemmaguest approved these changes

2018-08-08 13:02 UTC, gemmaguest commented
Happy to merge when tests pass :+1:

2018-08-08 15:43 UTC, martyngigg commented
@Mantid-Matthew Was this branch started from `release-next`? It looks like there are some fixes that are on master that are necessary for the RHEL7 builds that are now using gcc 7. I would suggest moving the `sans_table_change_feature_branch` forward to master and then merging that to this branch.

2018-08-14 16:03 UTC, Mantid-Matthew commented
@martyngigg Yes that was the problem they were running an old version of gcc on RHEL7 all seems to be good now.

2018-08-14 20:20 UTC, merged