Set store in ADS false - AbsorptionCorrections.cpp
mantidproject/mantid pull request #23163
Opened 2018-08-02 08:45 UTC by robertapplin

**Description of work.**
The indirect inelastic GUIs can be unstable. To help minimize the problems this causes we want the GUI's to work with project recovery.
To do this the algorithms are not set to child, and store to ADS is turned off. 

**To test:**
Check that history is saved for an ex-child algorithm after a crash/unexpected shut-down.

Fixes  #23144

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-10 10:29 UTC, keeeto commented
An example of a typical QENS workflow that currently fails is:

* Open Indirect > Data Analysis
* Load the file below in the MDS tab
[irs26176_graphite002_elwin_eq.nxs.zip](https://github.com/mantidproject/mantid/files/2277575/irs26176_graphite002_elwin_eq.nxs.zip)
* Set `Fit type` to Gaussian
* `Run` the fit
* After project recovery has saved files, use `Segfault` to kill Mantid
* Restart and attempt a recovery, it will fail

2018-08-10 10:35 UTC, keeeto commented
The workflow described above still fails for the same reasons as previously. i.e. the following lines:
```
QENSFitSequential(Input='irs26176_graphite002_elwin_eq,i0;', OutputWorkspace='irs26176_graphite002_elwin_eq_MSDFit_Gaussian_s0_Result', OutputParameterWorkspace='irs26176_graphite002_elwin_eq_MSDFit_Gaussian_s0_Parameters', OutputWorkspaceGroup='irs26176_graphite002_elwin_eq_MSDFit_Gaussian_s0_Workspaces', Function='name=MsdGauss,Height=1,MSD=0.05', StartX=0.52531275787596388, EndX=1.8250942715026275, PassWSIndexToFunction=True, MaxIterations=100, IgnoreInvalidData=True)  # 2018-08-10 10:30:42.038615 
Fit(Function='name=MsdGauss,Height=0.170185,MSD=0.146884', InputWorkspace='__QENSFitSequential_ws1', IgnoreInvalidData=True, MaxIterations=100, CreateOutput=True, Output='__QENSFitSequential_ws1_0', CalcErrors=True, OutputCompositeMembers=True, StartX=0.52531275787596388, EndX=1.8250942715026275)  # 2018-08-10 10:30:42.041708 
```

The workspace `__QENSFitSequential_ws1` is hidden from the ADS, therefore doesn't exist in recovery.

To make project recovery work with Indirect workflows we need to fix this issue.

2018-08-10 10:37 UTC, keeeto submitted a review, later dismissed
See my comments in the conversation. While this PR may help with some parts of recovering the indirect data analysis workflow it does not mean that a typical workflow is recovered.

On the plus side, it does not seem to make the interface any more unstable!

2018-08-27 14:03 UTC, mantid-builder commented
@robertapplin could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2018-09-24 12:29 UTC, robertapplin commented
Note: The PlotPeaksByLogValueTest failed because the Fit algorithm is now recorded as a child algorithm and hence it's outputs are no longer stored in the ADS. This meant that the test that failed couldn't find the output from the Fit part of PlotPeaksByLogValue.

2018-11-05 14:03 UTC, Pasarus commented
I spoke to @robertapplin and we believe the issue #23265 should be fixed by this PR as well.

2018-11-05 14:18 UTC, robertapplin commented
@Pasarus It will be fixed in this specific instance within QENSFitSequential, however there may be other instances elsewhere where the behavior described in #23265 is still happening. Those instances may needed to be fixed individually as and when found

2018-11-05 14:36 UTC, Pasarus commented
@robertapplin That is on the algorithm maintainers opposed to the people working on project recovery due to the fact that whoever wrote the algorithms in the first place making incomplete/incorrect workspace history

2018-11-05 14:46 UTC, robertapplin commented
@Pasarus I agree that it is an issue with algorithms rather than project recovery. It's worth keeping this issue in mind however because it could cause something to not work with project recovery in the future

2018-11-19 15:23 UTC, keeeto submitted a review, later dismissed
A lot has improved in this PR. However, I am having trouble getting this to work with ConvFit. 

* Load Mantid and got to Interfaces > Indirect > Data Analysis
* Go to the Conv Fit tab
* Load the following files into Sample and Resolution
[Archive.zip](https://github.com/mantidproject/mantid/files/2595871/Archive.zip)
* Run a fit to the data
* Wait for project saving to complete
* Crash Mantid with Segfault
* Reload Mantid and choose yes for recovery
* I see the following error:
```
RuntimeError: ['Workspace'] argument(s) not supplied to LoadParameterFile
  at line 2 in '/Users/keithbutler/.mantid/ordered_recovery.py'
```

2018-11-26 15:50 UTC, keeeto commented
The interface now works with project recovery! Also, this passes all the stability tests for the Indirect interfaces.

2018-11-30 11:18 UTC, keeeto submitted a review, later dismissed
This is good to go. It will be very much appreciated by the user community.

2018-11-30 14:11 UTC, soininen requested changes

2018-11-30 14:11 UTC, soininen commented on Framework/CurveFitting/src/Algorithms/PlotPeakByLogValue.cpp
> +    for (auto workspace : fitWorkspaces)
`auto &workspace`?

2018-11-30 14:11 UTC, soininen commented on Framework/CurveFitting/src/Algorithms/QENSFitSequential.cpp
> +  for (const auto resultWorkspace : *resultWorkspaces)
`const auto &resultWorkspace`?

2018-11-30 14:11 UTC, soininen commented on Framework/CurveFitting/src/Algorithms/QENSFitSequential.cpp
> +  for (const auto workspace : *resultGroup)
`&workspace`?

2018-11-30 14:11 UTC, soininen commented on qt/scientific_interfaces/Indirect/JumpFitModel.cpp
> +  for (auto const name : workspaceNames) {
`&name`?

2018-12-03 14:41 UTC, soininen approved these changes

2018-12-03 14:41 UTC, merged