Enable appending multiple times for event workspaces
mantidproject/mantid pull request #23176
Opened 2018-08-02 23:38 UTC by jmborr

**Description of work.**

**To test:**

Fixes #23175

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-16 08:10 UTC, DanNixon requested changes
Functionality all looks good, just a couple of small points.

2018-08-16 08:10 UTC, DanNixon commented on Framework/Algorithms/src/AppendSpectra.cpp
> +    output = boost::dynamic_pointer_cast<MatrixWorkspace>(e_output);
Given that the result of the cast will be successful this may as well be a `static_pointer_cast`.

2018-08-16 08:10 UTC, DanNixon commented on Framework/Algorithms/src/WorkspaceJoiners.cpp
> +  fixSpectrumNumbers(event_ws1, event_ws2, *output);
While this is being modified it is probably worth replacing all the `snake_case` variable names with `lowerCamalCase`.

2018-08-16 23:02 UTC, jmborr commented
@DanNixon all test passed, please let me know if anything else is needed

2018-08-17 07:04 UTC, DanNixon approved these changes
Looks good to me now.

2018-08-17 07:58 UTC, martyngigg commented
I noticed that the `Number` property documentation was not slightly incorrect so it seemed easier that I just fix such a trivial thing myself.

2018-08-17 12:48 UTC, merged

2018-08-17 15:10 UTC, jmborr commented
@DanNixon @martyngigg Thank you! :dancing_women: