New introduction documentation
mantidproject/mantid pull request #23185
Opened 2018-08-03 15:08 UTC by keeeto

**Description of work.**

This PR adds a new introduction section to the Sphinx documentation. The introduction is intended to be a very minimal guide to get a user up and running quickly

**Report to:** [user name]/[nobody]. 

**To test:**

* Build the `docs-html` target of Mantid. I found that on OSX I had to build a regular target first then build the `docs-html` target
* Check the front index page of documentation 
* Follow the links to `Mantid Basics`
* Check the content - there should be four sub-headings
* Check that each of the four pages has working figures and hyperlinks (including email link)
* Check that the text makes sense

Does this update require release notes?
- [ ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-18 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-08-22 15:06 UTC, peterfpeterson requested changes
Lots of changes requested. This feels like a PR that should be marked "in progress."

2018-08-22 15:06 UTC, peterfpeterson commented on docs/source/basics/introduction.rst
> +    * A users help forum: `Here <http://forum.mantidproject.org/>`_.
Change this line to
```
* A `forum <http://forum.mantidproject.org/>`_.
```

2018-08-22 15:06 UTC, peterfpeterson commented on docs/source/basics/introduction.rst
> +    * A Mantid help email address: mantid-help@mantidproject.org.
```
* An email address: `mantid-help@mantidproject.org <mailto:mantid-help@mantidproject.org>`__.
```

2018-08-22 15:06 UTC, peterfpeterson commented on docs/source/basics/loading_and_displaying_data.rst
> +* <name>, <name> : load a list
escape these

2018-08-22 15:06 UTC, peterfpeterson commented on docs/source/basics/loading_and_displaying_data.rst
> +You can load multiple files into mantid with a single Load command, either keeping each workspace separate,
link to http://docs.mantidproject.org/nightly/api/python/mantid/api/MultipleFileProperty.html

2018-08-22 15:06 UTC, peterfpeterson commented on docs/source/basics/loading_and_displaying_data.rst
> +* ISIS, SNS, ILL, PSI .nexus data files.
escape file extensions

2018-08-23 15:32 UTC, keeeto commented on docs/source/basics/algorithms_workspaces_and_history.rst
> +Understanding algorithms, workspaces and history
@peterfpeterson agree on the non-necessity of history here. The reason for not folding into the concepts page is that this is intended as a very basic intro, just giving a brand new user what they need to get going. I think that it is pretty impossible to use Mantid without knowing what a workspace/algorithm is. The way I see it concepts pages provide deeper level understanding for the interested user. The basics docs just tell you what you need to know to get going.

2018-08-23 15:38 UTC, keeeto commented
@peterfpeterson - thanks for the detailed review. I think that documentation is an area that should be somewhat developed collaboratively, so I appreciate the feedback and any criticisms are welcome (within reason :)).

2018-08-23 15:47 UTC, keeeto commented on docs/source/algorithms/Load-v1.rst
> +.. _load algorithm:
`Load-v1.rst` previously had no label for linking as far as I can see. This is linked to in the 'loading and displaying data' guide. The link seems to work fine when I build it. Should I put the label elsewhere in the `.rst` file?

2018-08-23 15:56 UTC, peterfpeterson commented on docs/source/algorithms/Load-v1.rst
> +.. _load algorithm:
All of the algorithm links are done automagically in the `.. algorithm::` directive. The link for `Load` is `:ref:`Load <algm-Load>` if you want to control the text.

2018-09-06 13:55 UTC, NickDraper submitted a review, later dismissed

2018-09-06 13:55 UTC, NickDraper commented on docs/source/index.rst
> +   basics/index
This renders as "Mantid Basics"

A few lines later you have "Mantid Basics Course" referring to the training course.  These titles are too similar for two separate but related things.

2018-09-06 13:55 UTC, NickDraper commented on docs/source/index.rst
> +   basics/index
Perhaps "Introduction to Mantid"?

2018-09-06 13:55 UTC, NickDraper commented on docs/source/basics/introduction.rst
> +============
This whole page has similar links to the top level index page, and might be better as a replacement of the top level index page.

2018-09-06 13:55 UTC, NickDraper commented on docs/source/index.rst
> +   basics/index
Also the index page itself is not a usefull index, it would be better to link to the Introduction page itself.

2018-10-01 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2018-10-04 17:09 UTC, peterfpeterson commented on docs/source/basics/loading_and_displaying_data.rst
> +You can load multiple files into mantid with a single Load command, either keeping each workspace separate,
```
:py:obj:`MultipleFileProperty <mantid.api.MultipleFileProperty>`
```

2018-11-01 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-11-15 14:03 UTC, mantid-builder commented
@keeeto could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2018-11-30 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-12-15 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-12-30 14:03 UTC, mantid-builder commented
@keeeto could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-01-14 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-01-28 14:03 UTC, mantid-builder commented
@keeeto could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-02-12 14:03 UTC, mantid-builder commented
@keeeto could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-02-18 11:50 UTC, NickDraper commented
@peterfpeterson, or any other tester.

The only changes now are to the first into page to the documentation, all of the others were pointless copies of sections from the mantid basics course and have been removed.

Please check you are happy to have a link to monitor.sns.gov in the page, this can easily be removed if you are not happy.

2019-02-18 15:56 UTC, peterfpeterson approved these changes
Builds without warning and adds context to what the various sub-pages actually are.

2019-02-19 15:18 UTC, merged