ConfigService document more properties
mantidproject/mantid pull request #23194
Opened 2018-08-06 18:48 UTC by peterfpeterson

This adds a unit test to prevent the addition of properties without documentation in `PropertiesFile.rst`.

**Do not merge before**  #23191 because it includes those changes.

**To test:**

Build the docs and declare that they are better than before this work was done.

*There is no associated issue.*

*This does not require release notes* because it is an improvement on user documentation rather than a functional change.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-07 11:59 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
> +                           'filefinder.casesensitive',
This may be worth documenting as users might want to fiddle with that

2018-08-07 12:00 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
> +                           'pythonalgorithms.refresh.allowed',
I don't think we use this key any more so we could remove it? I wonder if any others are dead?

2018-08-23 13:27 UTC, soininen commented
When running `ctest --output-on-failure -R ConfigServiceTest`, I get the following failure:
```
FAIL [0.003s]: test_properties_documented (ConfigServiceTest.ConfigServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cs/soininen/Sources/mantid/Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py", line 160, in test_properties_documented
    raise AssertionError('{} undocumented properties: {}'.format(len(undocumented), undocumented))
AssertionError: 1 undocumented properties: ['MantidOptions.ReusePlotInstances']

Stdout:
Parsing /home/cs/soininen/Sources/mantid/docs/source/concepts/PropertiesFile.rst
```

Looks like `MantidOptions.ReusePlotInstances` is somehow missing in the list of undocumented properties. If this is the case, I wonder how all the checks are passing?

2018-08-23 13:29 UTC, peterfpeterson commented
If the property was introduced after this PR was last updated would explain it.

2018-08-23 18:19 UTC, peterfpeterson commented
It is more interesting than that. You apparently have set `MantidOptions.ReusePlotInstances` in your properties file, where it isn't set in mine. I'll add it to the list to skip, but this can only test for properties that are defined in a properties file that `ConfigService` has read.

2018-08-24 08:16 UTC, soininen requested changes
The new test looks good and it passes on my system as well. I have one question, though: would it make sense to sort the property tables in the documentation alphabetically (case-insensitive)? Most of them are sorted already.

2018-08-24 12:40 UTC, soininen approved these changes

2018-08-24 16:10 UTC, merged