Indirect - F(Q) Fit - Only display EISF/Width in drop-down menu if found in workspace
mantidproject/mantid pull request #23221
Opened 2018-08-09 09:33 UTC by brandonhewer

This PR ensures that the EISF and Width options only appear in the parameter type drop-down menu (both in single and multiple input modes) when they are available within the selected input workspace.

If neither are available, the user is presented with a meaningful error message.

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #23204. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-10 10:40 UTC, keeeto commented
@brandonhewer , can you provide some more details for testing this PR. An example of a workspace where the options *do* appear and one where they *don't* appear would be useful.

2018-08-11 16:01 UTC, SpencerHowells commented
@brandonhewer @robertapplin Run iris26176 in ConvFit with TeixieraWater and it will generate a ws that crashes.

2018-11-01 14:03 UTC, mantid-builder commented
@keeeto do you have any comments on this PR?
<!-- {"problem_type": "review_requested"} -->

2018-11-16 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to complete your review yet?
<!-- {"problem_type": "review_requested"} -->

2018-12-06 10:41 UTC, keeeto commented
Hi @robertapplin should have time tomorrow morning to get through this. Please send me a reminder if I don't message you about it.

2018-12-07 11:18 UTC, keeeto requested changes
This seems almost there. But gets kind of stuck after I load the invalid data. 

* I load the good data - all is fine.

* After I load the wrong data I get the error. Then switch to a new tab and the error pops up again. No big problem.

* I go back to `F(Q)` tab and try to browse for a new file, the error message continuously pops up and does not allow me to select a new file.

2018-12-07 12:43 UTC, robertapplin commented
@keeeto I am struggling to reproduce this problem. Did you use the files in the description, or could you send me the files you used?

2018-12-07 12:46 UTC, keeeto commented
Hi @robertapplin - I used the files in the description.

* Loaded the correct file
* Loaded incorrect file
* Switched to `I(Q, T)` tab
* Loaded some data and did a fit there
* Switched back to `F(Q)` tab
* Tried to load the correct data

Sorry - I have a new build on my machine at the moment, so it would take a while for me to rebuild.

2018-12-10 13:02 UTC, keeeto approved these changes
* This all works as described except a small OSX specific problem (#24297)
* The functionality is still improved even on OSX
* The OSX issue is searate and it would be best to merge this fix for the stable nightly

2018-12-10 14:03 UTC, merged