ISIS Powder Prevent division by zero in Vanadium
mantidproject/mantid pull request #23239
Opened 2018-08-10 10:46 UTC by SamJenkins1

**Description of work.**
Prevented division by zero when applying the vanadium by replacing zeros in the vanadium with ones.

**To test:**
Download:
[Test.zip](https://github.com/mantidproject/mantid/files/2277619/Test.zip)

unzip it, update the paths in the calibration file, then run
```
from isis_powder import Gem

config_file_path = r"Path\to\Gem_config_example.yaml"
Gem_example = Gem(config_file=config_file_path,user_name="test")
Gem_example.create_vanadium(input_mode="Individual",first_cycle_run_no=85105,texture_mode=True)
append = False
for i in range(1,161):
    input = 'spline_bank_'+str(i)
    ws = mtd[input]
    ws = ws -ws
    mtd[input]=ws
    
    SaveNexus(Filename=r'Path\To\Calibration\cycle_18_1\VanSplined_85105_offsets_2011_cycle111b.cal.nxs',
                    InputWorkspace=ws, Append=append)
    append = True

Gem_example.focus(input_mode="Individual",run_number="85105",texture_mode=True)
```
and check the ResultsD and ResultsTOF, neither should contain infs

Fixes #23214 
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-31 14:03 UTC, mantid-builder commented
@SamJenkins1 the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-09-14 14:18 UTC, soininen requested changes
The data files (GEM85105...) seem to be missing in the test data zip, so I will do testing later. Below are some comments on the code.

2018-09-14 14:18 UTC, soininen commented on scripts/test/isis_powder/ISISPowderFocusCropTest.py
> +        e = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Is the `e` array needed here? The `DataE` property of `CreateWorkspace` is optional and the errors are not tested. Same applies to the other tests below.

2018-09-14 15:33 UTC, SamJenkins1 commented on scripts/Diffraction/isis_powder/routines/focus.py
> +    for i in range(spline.blocksize()):
looks like it actually needs to be 
```
small_spline_indices = numpy.nonzero(spline_spectrum > y_val)
x_max = x_list[small_spline_indecies[-1]]
x_min = x_list[small_spline_indecies[0]]
```
to give the same output as the loop, but it is much nicer to read, thanks

2018-09-18 08:19 UTC, soininen commented
I got some data files to test this. Below is shown a plot where the result data (red) ends when the vanadium splines (black) reach values close to zero.
![result_vs_spline](https://user-images.githubusercontent.com/19147159/45673744-cf420b80-bb2b-11e8-89e9-c447e496c8fe.png)
I think this is what this PR was after. The code looks good to me, some unit tests were added (:+1:  for those) and all-in-all I think this is good to go.

2018-09-18 08:19 UTC, soininen approved these changes

2018-09-18 09:11 UTC, merged