Add free text box to error reporter
mantidproject/mantid pull request #23293
Opened 2018-08-20 10:40 UTC by keeeto

**Description of work.**

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-28 15:57 UTC, Matthew-Andrew requested changes
Looks good just a few comments/clarifications below :)

2018-08-28 15:57 UTC, Mantid-Matthew commented on Framework/Kernel/src/ErrorReporter.cpp
> +  message["textBox"] = m_textbox;
We probably want this inside the m_share check below so that it is shared under the same conditions as name and email address

2018-08-28 15:57 UTC, Mantid-Matthew commented on scripts/ErrorReporter/errorreport.ui
> +          <string>Please enter any additional information about your problems. (Max 3200 characters)
Can you/have you put a code limit on this 3200? I think you have put limits of 128 on the email/name boxes below?

2018-08-28 15:58 UTC, Mantid-Matthew commented on scripts/ErrorReporter/errorreport.py
> +        #self.icon.setPixmap(QtGui.QPixmap(":/crying_mantid.png"))
Does this want to be uncommented ?

2018-08-28 16:19 UTC, Mantid-Matthew commented
When testing I came across the following:
* If you enter nothing in the email or name boxes and click share non identifiable information nothing is sent. Not sure whether this is a new issue or not. A server error seems to be returned.
* If you enter a name and email and click share you end up with the hint text being sent in the textBox. The textbox hint text also has to be manually deleted can we set it as the hint autoclears and is not sent by default.
* If you do not enter a name and email address and click share identifiable information you also get a server error. It seems that the server cannot currently cope with an empty string for the email/name.
* I seem to get the contents of the textbox printed out at notice level is this deliberate.

2018-08-31 12:10 UTC, keeeto commented
The issues around empty email and name causing errors is server related, so we will address this in a server-based fix, not this PR.

2018-09-03 12:50 UTC, keeeto commented on scripts/ErrorReporter/errorreport.py
> +        #self.icon.setPixmap(QtGui.QPixmap(":/crying_mantid.png"))
The bug is back in :)

2018-09-05 09:54 UTC, Mantid-Matthew commented
Code all looks good now and works when I tested it. I have some nitpicky things to do with how the window looks however apologies.
 * Could we make all the text the same size and font currently the text above is much large and therefore looks slightly odd. This also leads at least on my system to having to scroll down to get the entire message about the error.

2018-09-06 13:03 UTC, keeeto commented
@Mantid-Matthew quite right, thanks for picking this up. I think that this is, unfortunately, one of those cases where display properties vary by OS. Also, there is no easy way to set the font style in the plainText box, so I have done my best to make sure they look the same on my system. If you can check again that would be great.

2018-09-07 14:46 UTC, Matthew-Andrew approved these changes
This looks good to me. I think all the builds are failing due to a merge conflict though.

2018-09-10 16:56 UTC, peterfpeterson commented
It is a broken unit test
```
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:67:47: error: no matching function for call to ‘TestableErrorReporter::TestableErrorReporter(std::__cxx11::string&, Mantid::Types::Core::time_duration&, const char [2], bool, const char [5], const char [6])’
11:35:27                                         "email");
11:35:27                                                ^
11:35:27 In file included from Framework/Kernel/test/ErrorReporterTest.cpp:16:0:
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:14:24: note: candidate: TestableErrorReporter::TestableErrorReporter(std::__cxx11::string, Mantid::Types::Core::time_duration, std::__cxx11::string, bool)
11:35:27    using ErrorReporter::ErrorReporter;
11:35:27                         ^
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:14:24: note:   candidate expects 4 arguments, 6 provided
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:14:24: note: candidate: TestableErrorReporter::TestableErrorReporter(std::__cxx11::string, Mantid::Types::Core::time_duration, std::__cxx11::string, bool, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:14:24: note:   candidate expects 7 arguments, 6 provided
11:35:27 /home/builder/Jenkins/workspace/pull_requests-ubuntu-python3/Framework/Kernel/test/ErrorReporterTest.h:12:7: note: candidate: TestableErrorReporter::TestableErrorReporter(const TestableErrorReporter&)
```

2018-09-17 08:19 UTC, merged