Add progress bar
mantidproject/mantid pull request #23338
Opened 2018-08-24 10:29 UTC by Mantid-Matthew

**Description of work.**
This adds a progress bar and row coloring to the table in order to track progress through a batch reduction. In order to enable this a new work handler called batch_process_runner was created.

**To test:**
In the new sans GUI try a reduction on several rows. Verify that after being reduced the rows are colored correctly and that the progress bar updates. 

Fixes #xxxx. 

This does not require release notes as only going into a feature branch

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-17 09:49 UTC, gemmaguest requested changes
Looks good. Just a couple of suggestions when dealing with errors:
- Could we make the background colour for failed rows consistent with the reflectometry GUI? We currently use green/blue for success/failure as it's more colour-blind friendly than green/red.
- Could we avoid pop-ups for errors? If a lot of rows failed you could end up with a lot of dialogs. In the reflectometry GUI we set a tooltip on the row with the error message.

2018-09-18 12:57 UTC, gemmaguest approved these changes

2018-09-18 12:57 UTC, gemmaguest commented
Thanks for the changes. Looks good to me so happy to merge when tests pass :+1:

2018-09-18 18:45 UTC, merged

2018-09-18 18:46 UTC, peterfpeterson commented
I think it does deserve release notes even into a long running feature branch to make creating the final release notes easier.