Throw ParseError instead of bad_lexical_cast
mantidproject/mantid pull request #23348
Opened 2018-08-27 17:04 UTC by peterfpeterson

Users reported it difficult to find where errors were in files. This
should greatly improve their ability to figure out what is going on.

**Report to:** Huq

**To test:**

A bad error file is below. Load it and see that the error message now gives line numbers and filename.

```
Instrument parameter file:
1 3.17 90.0000
2 3.17 90.0000
3 3.17 90.0000
4 3.17 90.0000
5 3.17 90.0000
6 3.17 90.0000
7 3.17 90.0000
8 3.17 90.0000
9 3.17 90.0000
10 3.17 90.0000
11 3.17 90.0000
12 3.17 90.0000
13 3.17 90.0000
14 3.17 90.0000
15 3.17 90.0000
16 3.17 90.0000
17 3.17 90.0000
18 3.17 90.0000
19 3.17 90.0000
20 3.17 90.0000
21 3.17 90.0000
22 3.17 90.0000
23 3.17 90.0000
24 3.17 90.0000
25 3.17 90.0000
26 3.17 90.0000
27 3.17 90.0000
28 3.17 90.0000
29 3.17 90.0000
30 3.17 90.0000
31 3.17 90.0000
32 3.17 90.0000
33 3.17 90.0000
34 3.17 90.0000
35 3.17 90.0000
36 3.17 90.0000
37 3.17 90.0000
38 3.17 90.0000
39 3.17 90.0000
40 3.17 90.0000
L1 60.0
#S 1 characterization runs
#L frequency(Hz) center_wavelength(angstrom) bank_num vanadium_run empty_run vanadium_back d_min(angstrom) d_max(angstrom) t_min(microsec) t_min(microsec) lamda_min(angstrom) lambda_max(angstrom)
60 0.8 1 0 0 0 0.18,0.18,0.18,0.18,0.18,0.18,0.18,0.18,0.18,0.19,0.19,0.19,0.21,0.21,0.21,0.24,0.24,0.24,0.27,0.27,0.27,0.32,0.32,0.40,0.40,0.51,0.72,1.20,0.18,0.18,0.18,0.19,0.21,0.24,0.27,0.32,0.40,0.51,0.72,1.20  0.66,0.66,0.66,0.69,0.69,0.69,0.74,0.74,0.74,0.81,0.81,0.81,0.92,0.92,0.92,1.05,1.05,1.05,1.21,1.21,1.21,1.53,1.53,2.00,2.00,2.00,4.32,5.40,0.66,0.69,0.74,0.81,0.92,1.05,1.21,1.53,2.00,2.84,4.32,5.40 4500.00  21000.00 0.267 1.333
60 1.5 1 0 0 0 0.65,0.65,0.65,0.65,0.65,0.65,0.65,0.65,0.65,0.69,0.69,0.69,0.76,0.76,0.76,0.87,0.87,0.87,0.98,0.98,0.98,1.16,1.16,1.45,1.45,1.85,2.61,4.35,0.65,0.65,0.65,0.69,0.76,0.87,0.98,1.16,1.45,1.85,2.61,4.35 1.01,1.01,1.01,1.05,1.05,1.05,1.13,1.13,1.13,1.24,1.24,1.24,1.40,1.40,1.40,1.60,1.60,1.60,1.85,1.85,1.85,2.33,2.33,3.05,3.05,4.33,6.59,8.24,1.01,1.05,1.13,1.24,1.40,1.60,1.85,2.33,3.05,4.33,6.59,8.24
15400.00  32500.00 0.967 2.033
60 2.665 1 0 0 0
1.09,1.09,1.09,1.12,1.12,1.12,1.19,1.19,1.19,1.29,1.29,1.29,1.42,1.42,1.42,1.60,1.60,1.60,1.86,1.86,1.86,2.20,2.20,2.72,2.72,3.53,4.79,8.2,1.09,1.12,1.19,1,1.29,.42,1.60,1.86,2.20,2.72,3.53,4.79,8.2
1.64,1.64,1.64,1.73,1.73,1.73,1.88,1.88,1.88,2.07,2.07,2.07,2.33,2.33,2.33,2.70,2.70,2.70,3.20,3.20,3.20,3.90,3.90,5.01,5.01,7.17,11.75,29.6,1.64,1.73,1.88,2.07,2.33,2.70,3.20,3.90,5.01,7.17,11.75,29.6
33500.33  51500.00 2.132 3.198
```
The error arose from a text editor automatically inserting newlines in the file to break up long lines.

*There is no associated issue.*

*This does not require release notes* because it is a small change in error reporting.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-28 13:50 UTC, AndreiSavici requested changes
It shows error on line 45, but in the editor is line 47. 1 is from the algorithm logic, 1 is from starting at 0.

2018-08-28 17:09 UTC, AndreiSavici approved these changes

2018-08-29 14:38 UTC, merged

2018-08-29 14:38 UTC, martyngigg commented
The failing system test was unrelated to these changes.

2018-08-29 14:39 UTC, martyngigg commented
It was requested that this be reported to Huq when merged.