Expose the TSVSerialiser to python
mantidproject/mantid pull request #23353
Opened 2018-08-28 09:49 UTC by AnthonyLim23

**Description of work.**
This work exposes some of the basic functionality of the TSVSerialiser to python so it can save python interfaces.

**Report to:** nobody. 

**To test:**
The following script can be used to test it:

```
from mantidqtpython import MantidQt

def makeStuff():
    tmp = MantidQt.API.TSVSerialiser()
    tmp.writeLine("test")
    tmp.storeDouble(1.1)
    tmp.storeInt(2)
    tmp.writeLine("bob")

    tmp.storeString("hello world")
    tmp.storeBool(True)
    return tmp.outputLines()

#create first section
tmp = MantidQt.API.TSVSerialiser()
string= makeStuff()
tmp.writeSection("FDA", string)
string = tmp.outputLines()

#create a top level section
tmp = MantidQt.API.TSVSerialiser()
tmp.writeSection("muon", string)
string = tmp.outputLines()
# check output
print string

# lets read some data
load = MantidQt.API.TSVSerialiser(string)

# select top section
secs = load.sections("muon")
load = MantidQt.API.TSVSerialiser(secs[0])

#select sub section
secs = load.sections("FDA")
load = MantidQt.API.TSVSerialiser(secs[0])

#check line
print(load.values("test")[0])

load.selectLine("test")
print load.readDouble()
print load.readInt()

#check line 2
load.selectLine("bob")
print load.readString()
print load.readBool()
```

Fixes #23233. 

Should this be in the release notes? I am in 2 minds about it. 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-28 10:22 UTC, martyngigg requested changes

2018-08-28 12:05 UTC, martyngigg commented on qt/widgets/common/src/TSVSerialiser.cpp
> +void TSVSerialiser::storeDouble(const double val) { m_output << "\t" << val; }
:+1:

2018-09-11 14:04 UTC, mantid-builder commented
@AnthonyLim23 the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2018-09-20 07:44 UTC, AnthonyLim23 commented
unrelated failure

2018-09-20 08:06 UTC, martyngigg approved these changes
This looks good to go now :+1:

2018-09-20 14:22 UTC, merged