Updating Job Tree View
mantidproject/mantid pull request #23362
Opened 2018-08-28 14:25 UTC by Matthew-Andrew

**Description of work.**

This PR takes the changes to JobTreeView from #22590 and pulls them out into a separate PR. Changes included here are 
* Added cut functionality to JobTreeView
* Updates to hinting line edit classes to make them exportable through SIP to python
* Updates to the existing Reflectometry GUI to work with the new hinting line edit classes
* The adding of an interface IJobTreeView as well as some tests
* The correction of a bug with SubTrees

**To test:**
The most important test is to check that the existing Reflectometry and SANS Gui's still work. To test the JobTreeView changes requires a GUI updated to use them.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-08-31 15:28 UTC, gemmaguest requested changes
I still need to do a bit more testing but looks good so far, apart from the one potential issue highlighted inline.

2018-08-31 16:11 UTC, Mantid-Matthew commented
Good spot I think it should hopefully corrected now.

2018-09-03 11:05 UTC, gemmaguest commented
Looks good now. Both existing interfaces still function correctly and the hints still work in both. Happy to approve when tests pass :+1:

2018-09-03 12:54 UTC, gemmaguest approved these changes

2018-09-03 14:21 UTC, merged