Migrate MBC Training to Sphinx
mantidproject/mantid pull request #23363
Opened 2018-08-28 15:46 UTC by keeeto

**Description of work.**

This PR moves the documentation for the basic training course across to Sphinx. This is part of an ongoing move to consolidate the documentation in one place.

**Report to:** [user name]/[nobody]. 
**To test:**

* Build the `docs-html` target of Mantid. I found that on OSX I had to build a regular target first then build the `docs-html` target
* Check the front index page of documentation 
* Follow the links to `Training/Mantid Basic Course`
* Check the content 
* Check that each of the pages has working figures and hyperlinks (including email link)
* Check that the text makes sense

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-03 08:39 UTC, soininen requested changes
The documentation builds fine and the migration looks successful. The links seem to be working. I think I clicked most of them. Hopefully. I didn't spot any missing figures, either. I didn't read through everything but I'd guess the training course needs a major overhaul when the GUI gets upgraded anyway. Most of the content is more-or-less up-to-date. There was only two small but obvious glitches I noticed, see the comments below.

2018-09-03 10:26 UTC, keeeto commented
Thanks @soininen nice proof-reading :)

2018-09-04 09:57 UTC, soininen commented
Looks like the removal of the ILL training stuff left some leftovers.

2018-09-04 13:40 UTC, soininen approved these changes

2018-09-04 20:30 UTC, merged