Get selected spectrum number not combobox index
mantidproject/mantid pull request #23397
Opened 2018-08-31 11:01 UTC by robertapplin

**Description of work.**
This PR fixes an issue where the parameter values are not updated for a selected spectrum when you use the  `Fit String` option in ConvFit.
The problem was that the selected spectrum number was wrong and so an update of the parameter values did not occur. Instead of retrieving the selected spectrum number, the currently selected Combobox index was returned instead.

**To test:**
- Go to Interfaces > Indirect > Data Analysis
- Go to the Conv Fit tab
- Load the reduced and resolution files below
- Set `Fit spectra` to String 3
- Set `Fit type` to Two Lorentzian's
- Set `Max iterations` to 100
- Expand the function f0-Lorentzian - note the parameters
- Click `Run`
- Check the parameters of f0-Lorentzian are updated

- `Run` the fit for other `Fit spectra` Strings, and change between each fitted spectra to ensure that the parameter values are updating

**Test Files**
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2339793/irs26173_graphite002_res.zip)
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2339794/irs26176_graphite002_red.zip)

Fixes ##23225

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-03 09:28 UTC, Pasarus requested changes
Your tests work as described. Just a change to be made. No need for tests here.

2018-09-03 09:28 UTC, Pasarus commented on qt/scientific_interfaces/Indirect/IndirectFitPlotView.cpp
> +#include <string>
This include is not necessary

2018-09-03 16:04 UTC, Pasarus approved these changes

2018-09-03 16:05 UTC, Pasarus requested changes
Actually you need to make release notes! This is a user facing feature

2018-09-03 16:09 UTC, robertapplin commented
This PR doesn't need release notes because no new features have been added, and no improvements have been made - it's just a behind-the-scenes fix that users would expect to have been implemented already. I think that because it's such a small fix (and for the above reason), adding release notes isn't justified.

2018-09-04 15:29 UTC, Pasarus approved these changes
Looking Good!

2018-09-04 20:28 UTC, merged