Fix reflectivity calculation and error propagation in Q grouping in ILL reflectometry reduction
mantidproject/mantid pull request #23404
Opened 2018-08-31 15:44 UTC by soininen

**Description of work.**

This PR reorganizes the `ReflectometryILL*` algorithms such that in the `SumInLambda` mode, the reflected data gets divided by the direct beam only after conversion to *Q* and grouping in *Q*. 

**Report to:** [nobody].

**To test:**

The script below exercises the workflow algorithms both in `SumInLambda` and `SumInQ` modes. Check that the script runs and the two final workspaces, `reflectivity_sumInLambda` and `reflectivity_sumInQ` look about right; you should see something like this:

![reflectivity](https://user-images.githubusercontent.com/19147159/44922237-26cb3380-ad45-11e8-9afb-f8f0be9dc809.png)

```python
# Direct beam first
ReflectometryILLPreprocess('ILL/D17/317369.nxs',
    OutputWorkspace='direct',
    OutputBeamPositionWorkspace='direct_beampos')
ReflectometryILLSumForeground('direct',
    OutputWorkspace='direct_fgd',
    WavelengthRange=[2, 20.])
    
# SumInQ
ReflectometryILLPreprocess('ILL/D17/317370.nxs',
    OutputWorkspace='reflected',
    DirectBeamPositionWorkspace='direct_beampos')
ReflectometryILLSumForeground('reflected',
    OutputWorkspace='reflected_fgd_inQ',
    DirectForegroundWorkspace='direct_fgd',
    SummationType='SumInQ')
ReflectometryILLConvertToQ('reflected_fgd_inQ',
    OutputWorkspace='reflectivity_sumInQ',
    ReflectedBeamWorkspace='reflected',
    DirectBeamWorkspace='direct',
    GroupingQFraction=0.2)

# SumInLambda; same data as above
ReflectometryILLPreprocess('ILL/D17/317370.nxs',
    OutputWorkspace='reflected',
    DirectBeamPositionWorkspace='direct_beampos')
ReflectometryILLSumForeground('reflected',
    OutputWorkspace='reflected_fgd_inLambda',
    DirectForegroundWorkspace='direct_fgd')
ReflectometryILLConvertToQ('reflected_fgd_inLambda',
    OutputWorkspace='reflectivity_sumInLambda',
    ReflectedBeamWorkspace='reflected',
    DirectBeamWorkspace='direct',
    DirectForegroundWorkspace='direct_fgd',
    GroupingQFraction=0.2)
```

Fixes #22674.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-06 14:48 UTC, reimundILL commented
- A `DirectForegroundWorkspace` was added to the *`ConvertToQ` algorithm but the diagram does not seem to be updated accordingly
- The `DirectBeamPositionWorkspace` in *`Preprocess` seems to be missing in the diagram of the corresponding documentation

2018-09-07 07:53 UTC, vreimund requested changes
I verified these changes by comparing an updated reduction script with the already realized preliminary reduction:
Previous
![previous](https://user-images.githubusercontent.com/19187274/45205810-967c7980-b283-11e8-82b8-5e6427fff1b3.png)
Now:
![pr](https://user-images.githubusercontent.com/19187274/45205829-a6945900-b283-11e8-9096-07b5ea179a3d.png)
This looks good!

But we need to still update the documentation + diagram, see comment above.

2018-09-07 13:19 UTC, vreimund requested changes
When running the example given, I expect `XErrors` for the output workspace. This is true for the `SumInQ` option but not for the `SumInLambda` option (`XError` tab missing):
![suminlambdamissingresolution](https://user-images.githubusercontent.com/19187274/45221271-41575c80-b2b1-11e8-96f7-58a2ddb3810b.png)

This may require a unit test as well.

My guess: `Divide` does not propagate `Dx`

2018-09-07 14:03 UTC, reimundILL commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLConvertToQ.py
> +        reflectivityWS.setYUnitLabel('Reflectivity')
```
dxs = ws.readDx(0)
reflectivityWS.setDx(0, dxs)
self._cleanup.cleanup(ws)
```
Seem to solve the problem for me

2018-09-10 14:01 UTC, vreimund approved these changes

2018-09-11 08:10 UTC, reimundILL commented
:+1:

2018-09-14 12:17 UTC, merged