Project Recovery runs when not selected yes
mantidproject/mantid pull request #23439
Opened 2018-09-05 12:32 UTC by Pasarus

**Description of work.**
Project recovery will now run normally when you select no or the recovery fails when recovering from a ungraceful exit.

**To test:**
- Load up Mantid
- Load a workspace
- Wait for the project recovery to save (make sure logging is at debug level)
- Run Segfault
- Restart Mantid
- Select "no" on project recovery popup GUI
- Load a workspace
- Wait for it to save and if it does attempt a save it is working!

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-05 17:11 UTC, robertapplin requested changes
Apart from the typo, all the tests work as described. I can approve this once this change is made

2018-09-05 17:11 UTC, robertapplin commented on docs/source/release/v3.14.0/ui.rst
> +- Project recovery will now run normally when you select no or the recovery fails when recvoering from a ungraceful exit.
There is a typo in this line

2018-09-06 07:25 UTC, robertapplin approved these changes

2018-09-07 07:44 UTC, martyngigg requested changes
Can we handle much of this by the high level `checkForProjectRecovery` function. We've now got quite a few scattered calls to `startProjectSaving` in functions that probably shouldn't be calling that.

2018-09-07 08:10 UTC, Pasarus commented
As far as I can tell the design was to decide inside the ProjectRecovery Class whether or not to start project saving, I didn't want to take away this ability.

2018-09-07 09:28 UTC, martyngigg commented
To me it looks like the opposite as the current calls in `master` are in `ApplicationWindow.cpp`, i.e. the client of the class decides this, which in my mind makes for sense.

2018-09-07 11:54 UTC, Pasarus commented
I agree however ProjectRecovery originally handled whether it wanted to start the saving thread should it finish, and there was no project recovery checkpoints.

2018-09-07 16:21 UTC, martyngigg approved these changes

2018-09-07 16:22 UTC, merged