Speeding up the system tests further
mantidproject/mantid pull request #23444
Opened 2018-09-05 18:04 UTC by nvaytet

**Description of work.**

The scheduling of the system tests is now done in the following way.:

A master test list is first cerated by scanning the `Testing/SystemTests/tests/analysis` directory.
Then, N processes are spawned, where N is the number requested by the user via the `-j N` option.
Each thread runs a function that stays in a loop as long as there are tests that still have not been run.

Each thread starts a loop and gathers a first test module from the master test list which is stored in a shared dictionary, starting with the number in the module list equal to the process id.
Once it has completed the work in the current module, it checks if the number of modules that remains to be executed is greater than 0. If there is some work left to do, the thread finds the next module that still has not been executed (searches through the `tests_lock` array and finds the next element that has a 0 value). This aims to have all threads end calculation approximately at the same time, even though in practise some test modules take a long time to complete.

The `*V2` tests (mainly SANS2D tests) were merged into their parent file to avoid the use of the same data by competing trheads.

**To test:**

`./systemtests -j 8 -q --output-on-failure` should run even faster than before.

Fixes #23373 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-06 08:54 UTC, martyngigg commented on Testing/SystemTests/lib/systemtests/stresstesting.py
> +        config['defaultsave.directory'] = "%s/core-%i" % (saveDir,core_id)
Are we going to need to warn developers now that `config['defaultsave.directory']` is now only fixed at runtime so it shouldn't be cached in the test?

2018-09-07 12:48 UTC, nvaytet commented
Hi @martyngigg I've now changed things around again, in a way which is much better in my opinion.

As the description of work says above, I am now creating a list of data files that each test module requires at runtime.

The threads pick the next module in a global test list that has not yet been run and checks if any of the data files required by that module have not been locked by another threads.

If all files are unlocked, it locks them and proceeds with running the tests in that module. If any one of the files is locked, then it moved on to the next module in the list to see if that one can be run. This no longer required any messing around with default save directories etc...

This is of course as long as I have correctly identified what is a data file in the python scripts. For now I am checking for anything that has a '.nxs' extension and any sequence of 4 or 5 digits inside a string (e.g. "54431" or "TOPAZ_3132"). Maybe I also need to add the ".raw" extension?

It works pretty well on my machine. Down to 18min on 12 cores.

2018-09-07 13:16 UTC, peterfpeterson commented
FYI #23458 is likely going to get merged before this and resolving the conflicts will be fun.

2018-09-07 13:27 UTC, nvaytet commented
@peterfpeterson aaaarrgh! :-)

2018-09-10 12:37 UTC, peterfpeterson commented
If you are going to clean up the file stuff [use the `with` keyword](http://effbot.org/zone/python-with-statement.htm) which will close the file even in the case of exceptions.
```python
with open("x.txt") as f:
    data = f.read()
    do something with data
```
It works for writing too.

2018-09-10 12:45 UTC, nvaytet commented
I think I used the `with open(...) as f` syntax as much as possible now.

2018-09-10 17:05 UTC, peterfpeterson commented
You missed one in L970 of `Testing/SystemTests/lib/systemtests/stresstesting.py`

2018-09-10 18:27 UTC, nvaytet commented
Yes, but since you hadn't modified it in your PR, I left it alone. I thought you decided it was better that way (https://github.com/mantidproject/mantid/pull/23458/files#diff-5247c1f456dfe545c21d1a44924ad807R923)

2018-09-11 18:28 UTC, nvaytet commented
@peterfpeterson  I fixed them all now

2018-09-12 14:39 UTC, peterfpeterson requested changes
Small regular expression change then it can be merged. Good improvement to the code in general. I'm still surprised there isn't a standard python implementation of a thread pool.

2018-09-12 14:39 UTC, peterfpeterson commented on Testing/SystemTests/lib/systemtests/stresstesting.py
> +                        p = re.compile(so+r"\d\d\d\d")
Can be `p = re.compile(so+r"\d{4}")`

2018-09-12 14:39 UTC, peterfpeterson commented on Testing/SystemTests/lib/systemtests/stresstesting.py
> +                        p = re.compile(r"\d\d\d\d"+so)
Can be `p = re.compile(r"\d{4}"+so)`

2018-09-12 16:41 UTC, peterfpeterson approved these changes

2018-09-13 09:30 UTC, merged