Project Recovery: Handle algorithms that require a string list of workspace names
mantidproject/mantid pull request #23464
Opened 2018-09-07 09:29 UTC by Pasarus

**Description of work.**
Removed the previous way of handling GroupWorkspaces as it will no longer after required pull requests be required as it is handled properly now.

**To test:**
- Group two workspaces
- Wait for project recovery to save
- Run Segfault
- Load up mantid
- Attempt recovery
- The group should be there with it's respective workspaces

Fixes #23452 and #23450 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-07 11:03 UTC, keeeto commented
The functional tests related to this PR work fine.

2018-09-07 11:04 UTC, keeeto approved these changes
This passes the functional tests and also the unscripted testing for project recovery.

2018-09-11 13:29 UTC, soininen requested changes

2018-09-11 13:29 UTC, soininen commented on Framework/API/inc/MantidAPI/ScriptBuilder.h
> +                std::vector<std::string> ignoreTheseAlgs = {""});
Why add an empty string? Why not use an empty `vector` as the default?

2018-09-11 13:29 UTC, soininen commented on Framework/API/src/Algorithm.cpp
> +          currentWS.push_back(propPropValue[i]);
`emplace_back` should be used over `push_back`.

2018-09-11 13:29 UTC, soininen commented on Framework/API/src/Algorithm.cpp
> +    std::string errorMsg(error.what());
`const`

2018-09-11 13:29 UTC, soininen commented on Framework/API/src/Algorithm.cpp
> +      outputWorkspaces.push_back(ADS.retrieveWS<Workspace>(currentWS));
`emplace_back`

2018-09-11 13:29 UTC, soininen commented on Framework/API/src/Algorithm.cpp
> +    std::string errorMsg(error.what());
`const`

2018-09-11 13:29 UTC, soininen commented on Framework/Algorithms/src/GeneratePythonScript.cpp
> +  declareProperty("IgnoreTheseAlgs", std::vector<std::string>({""}),
Why `std::vector<std::string>()` would not work as the default value?

2018-09-11 14:03 UTC, soininen commented on Framework/API/src/Algorithm.cpp
> +          currentWS.push_back(propPropValue[i]);
Okay, sorry for the noise, then!

2018-09-11 14:04 UTC, soininen approved these changes

2018-09-12 14:54 UTC, merged