Indirect - Iqt Monte Carlo Progress bar and option to skip error calculation
mantidproject/mantid pull request #23484
Opened 2018-09-11 12:36 UTC by robertapplin

**Description of work.**
This PR adds an checkbox in the Iqt Tab of `Indirect Data Analysis` which allows the user to skip the calculation of Monte Carlo errors.
This PR also adds a progress bar which lets the user know how far through the error calculation it is.

**To test:**

Fixes #23474

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-11 13:55 UTC, Pasarus commented on Framework/Algorithms/src/CalculateIqt.cpp
> +  PARALLEL_FOR_IF(Mantid::Kernel::threadSafe(*outputWorkspace))
I don't believe you end this parrellized for loop here

2018-09-12 13:45 UTC, LowriJenkins requested changes
Code all looks fine and runs as stated, I'll mark this as approve once it passes doc-tests

2018-09-12 13:58 UTC, ewancook commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
> +        for key, value in args.items():
As a side note - `args.items()` (Python 2.X) returns a copy of the items, whereas using `from six import iteritems` and `iteritems(args)` returns an iterator (lower memory usage). This is a small dict so shouldn't make too much difference, but worth remembering.

2018-09-13 07:12 UTC, LowriJenkins approved these changes

2018-09-13 10:22 UTC, gvardany requested changes
Handy feature is added, few comments inline.

2018-09-13 15:39 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
> +        calculateiqt_alg = self.createChildAlgorithm(name='CalculateIqt', startProgress=0.3,
I had to change it to this in order to get the progress bar for the errors to work properly - I'm not too sure why it wouldn't work when using the previous function-like call.

2018-09-14 07:40 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
> +        calculateiqt_alg = self.createChildAlgorithm(name='CalculateIqt', startProgress=0.3,
That's strange, but that's a separate issue. If you can make a minimum reproducible example and open an issue, would be great.

2018-09-14 07:43 UTC, gvardany approved these changes

2018-09-14 07:44 UTC, merged

2018-09-14 07:51 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
> +        calculateiqt_alg = self.createChildAlgorithm(name='CalculateIqt', startProgress=0.3,
Absolutely, I shall try find an example later