macOS bundle h5py
mantidproject/mantid pull request #23561
Opened 2018-09-19 14:43 UTC by gvardany

**Description of work.**

This PR makes packaging of `h5py` a bit more flexible; now it can in brew site packages or system python site packages.

**To test:**
- [x] Believe that packaging works on my machine
- [ ] Make package, install and make sure it works on your macOS machine
- [ ] Rebuild the macOS build on the server with make package ON, download and install the artefact, make sure it works as well. (Note that `ill-mac` will fail the packaging (for different reasons), so might need to rebuild until it is picked up by another mac server).

Fixes #23552 . 

*This does not require release notes, internal issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-19 19:08 UTC, quantumsteve requested changes
We build our own version of h5py to avoid bundling a second copy of hdf5. Therefore I am hesitant to support this change.

Do you need this change? May we protect it with an optional flag?

2018-09-20 07:16 UTC, gvardany commented
I see. Is this why we install h5py with brew rather than pip? I wonder how large hdf5 is.
It seems I need this, since I have h5py in `brew list`, but I don't have this directory `/usr/local/lib/python2.7/site-packages/h5py`. So packaging as is does not work for me, at least in the recent months. Should I try to reinstall h5py?

2018-10-04 14:03 UTC, mantid-builder commented
@gvardany have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-11-01 14:03 UTC, mantid-builder commented
@gvardany have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-11-16 14:03 UTC, mantid-builder commented
@gvardany have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2018-12-01 14:03 UTC, mantid-builder commented
@gvardany could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2018-12-21 14:03 UTC, mantid-builder commented
@gvardany have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2019-01-05 14:03 UTC, mantid-builder commented
@gvardany could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-01-20 14:03 UTC, mantid-builder commented
@gvardany have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2019-01-20 14:03 UTC, mantid-builder commented
@gvardany there are conflicts here, can you resolve them.
<!-- {"problem_type": "conflicting"} -->

2019-02-04 14:03 UTC, mantid-builder commented
@gvardany the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-02-04 14:03 UTC, mantid-builder commented
@gvardany there are conflicts here, can you resolve them.
<!-- {"problem_type": "conflicting"} -->

2019-02-11 11:12 UTC, closed without merging

2019-02-11 11:12 UTC, gvardany commented
Not relevant.