New algorithm to slice event workspaces for ISIS reflectometry
mantidproject/mantid pull request #23578
Opened 2018-09-20 17:29 UTC by gemmaguest

**Description of work.**
This PR adds a new algorithm to perform slicing of event workspaces, producing output suitable for use with ReflectometryReductionOneAuto.
- Uses GenerateEventsFilter and FilterEvents to do the filtering
- Rebins to histogram data
- Adds monitors to each resulting slice, scaled by the relative proton_charge for the slice

The aim of this algorithm will eventually be to replace functionality currently implemented in the ISIS Reflectometry GUI, which should simplify the restructuring work in #23051.

**Report to:** nobody

**To test:**

To follow

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-25 09:19 UTC, Mantid-Matthew commented
Code and tests look good. 

I have one minor issue to do with C++ types which I'm not even sure is an error. When I run the following script
```
Load('OFFSPEC48276', OutputWorkspace='OFFSPEC48276',LoadMonitors=True)
ReflectometrySliceEventWorkspace(InputWorkspace='OFFSPEC48276', MonitorWorkspace='OFFSPEC48276_monitors',OutputWorkspace='TOF_48276',
    TimeInterval=400, StartTime=5, StopTime=500)
```

I get the following error 

```
TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > from this Python object of type int
  at line 3 in 'New script'
  caused by line 1094 in '/home/matthew/Documents/Mantid/mantidBuild/bin/mantid/simpleapi.py'
  caused by line 1032 in '/home/matthew/Documents/Mantid/mantidBuild/bin/mantid/simpleapi.py'
  caused by line 1016 in '/home/matthew/Documents/Mantid/mantidBuild/bin/mantid/simpleapi.py'
``` 

This seems to be because GenerateEventsFilter expects a string for StartTime and StopTime passing these numbers as strings works but I was wondering if it would be better to sanatise this input into a string inside the python algorithm?

2018-09-25 10:46 UTC, gemmaguest commented
I think I'd rather leave the inputs the same as GenerateEventsFilter for now, although I may change this in the future depending on user feedback.

2018-09-25 10:48 UTC, Matthew-Andrew approved these changes
OK looks good to go to me then.

2018-09-25 21:41 UTC, AndreiSavici requested changes

2018-09-25 21:41 UTC, AndreiSavici commented on docs/source/algorithms/ReflectometrySliceEventWorkspace-v1.rst
> +.. seealso :: Algorithm :ref:`algm-GenerateEventsFilter`, :ref:`algm-FilterEvents` and :ref:`algm-ReflectometryReductionOneAuto`
There is a function in algorithm that should be overwritten instead. Add the following to the algorithm code
```
def seeAlso(self):
    return [ "GenerateEventsFilter","FilterEvents" ,"ReflectometryReductionOneAuto"]
```

2018-09-25 21:41 UTC, AndreiSavici commented on docs/source/algorithms/ReflectometrySliceEventWorkspace-v1.rst
> +Usage
Add a correct (testable) documentation usage.

2018-09-26 15:59 UTC, AndreiSavici approved these changes

2018-09-26 16:49 UTC, AndreiSavici commented
Unrelated systemtest error

2018-09-28 07:26 UTC, merged