Refs #23510 Fix bug with saving WISH data to Isaw format
mantidproject/mantid pull request #23599
Opened 2018-09-24 07:00 UTC by samueljackson92

**Description of work.**
Fix bug where WISH peak workspaces are not saved to the Isaw `.peaks` file format.

**Report to:** Fabio Orlandi

**To test:**
 - Check that saving a peaks workspace with the WISH instrument attached.
 - Code review.

Fixes #23510 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-10-02 09:17 UTC, LowriJenkins requested changes
Saving the file out appears to work, but attempting to load the file back in using `LoadISawPeaks` appears to get stuck and fail, this may be a problem in `LoadISawPeaks`, but perhaps the file is not being saved out correctly?

2018-10-02 09:18 UTC, samueljackson92 commented
@SamJenkins1 what is the error output when running LoadIsawPeaks?

2018-10-02 09:27 UTC, SamJenkins1 commented
I didn't receive one, the algorithm started running, then mantid stopped responding, the debug terminal produced this output before it stopped responding though
 ```
MaskBTP-[Debug] MaskBTP finished with isChild = 1
MantidPlot: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const Mantid::Geometry::IComponent; typename boost::detail::sp_member_access<T>::type = const Mantid::Geometry::IComponent*]: Assertion `px != 0' failed.
```

2018-10-02 09:28 UTC, samueljackson92 commented
@SamJenkins1 Ok I shall investigate further.

2018-10-02 09:33 UTC, SamJenkins1 commented
I got this to happen by loading a wish file 41845 using `CreatePeaksWorkspace` on it then saving that out using `SaveISawPeaks` when I tried to load it back in is when the problem occurred

2018-10-08 13:06 UTC, samueljackson92 commented
@SamJenkins1 The issue you saw was because the algorithm generates a dummy peak which is not attached to a valid detector. `LoadIsawPeaks` wasn't handling that very well. Now it will give a error & not crash.

2018-10-08 13:07 UTC, samueljackson92 commented
@SamJenkins1 The issue you saw was because the algorithm generates a dummy peak which is not attached to a valid detector. LoadIsawPeaks wasn't handling that very well. Now it will give a error & not crash.

2018-10-08 15:08 UTC, SamJenkins1 commented
Loading the file back in no longer crashes mantid, but the following outputs to the logger 
```
Error reading peak SEQN 0 : Instrument: Detector with ID -1 not found. search object 
Error in execution of algorithm LoadIsawPeaks:
Corrupted input file. 
```
and attempteing to open the loaded workspace fails with `Error, cannot create empty table` whereas the workspace that the save was called on can be open fine.

2018-10-08 15:13 UTC, samueljackson92 commented
@SamJenkins1 That is the behaviour I was expecting. You're saving a file with peaks that are not attached to any detector. When loading the file back in there is no way for the algorithm to find a detector because it never had one associated with it.

There's probably more we could do here it make this nicer, but that is not really related to this issue.

2018-10-08 15:15 UTC, LowriJenkins approved these changes

2018-10-09 07:20 UTC, martyngigg commented on Framework/Crystal/src/SaveIsawPeaks.cpp
> +  if (bankPart != "bank" && bankPart != "WISHpanel" && bankPart != "?") {
I'm not suggesting we change it here but would is possible to make this more general in some way and not have to update the code for each instrument that we want to support?

2018-10-09 07:21 UTC, merged