Create a separate Python/C helper library to remove code duplication
mantidproject/mantid pull request #23594
Opened 2018-09-21 18:17 UTC by martyngigg

**Description of work.**

Parts of the code base had duplicated the GIL class and error handling code from the Framework PythonInterface code. The new library required for supporting the matplotlib-based instrument view plotter will requires these features too so it's time to make them easily accessible.

Over time this library should grow with most code moving out of PythonInterface kernel.

**Report to:** [nobody]. 

**To test:**

* Code review

*This does not require release notes* because **it is an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-09-22 10:56 UTC, martyngigg commented
The failing system tests are currently being fixed in #23579.

2018-09-24 15:38 UTC, peterfpeterson requested changes
Overall good reduction in duplication of code. One minor change.

2018-09-24 15:38 UTC, peterfpeterson commented on Framework/PythonInterface/core/src/GlobalInterpreterLock.cpp
> +#if PY_VERSION_HEX < 0x03000000
shouldn't this use `IS_PY3K`?

2018-09-24 15:42 UTC, martyngigg commented on Framework/PythonInterface/core/src/GlobalInterpreterLock.cpp
> +#if PY_VERSION_HEX < 0x03000000
Nice catch. Yes it should.

2018-09-24 17:26 UTC, peterfpeterson approved these changes

2018-09-24 19:09 UTC, merged