scripts: typo fixes
mantidproject/mantid pull request #23602
Opened 2018-09-24 14:28 UTC by luzpaz

Found via `codespell -q 3 -I ../mantid-word-whitelist.txt -L mye,amin scripts/`

2018-09-24 14:37 UTC, luzpaz reviewed
I've added some comments where I wasn't sure about the validity of some of the fixes. Please also know that I will revert the ones mentioned above when I get the green light on all the other questions.

2018-09-24 14:37 UTC, luzpaz commented on scripts/Calibration/tube.py
> +    points, where there are one gaussian peak and two edges, the calibrate
please review this fix

2018-09-24 14:37 UTC, luzpaz commented on scripts/HFIR_4Circle_Reduction/peakprocesshelper.py
> +            raise RuntimeError('PeaksWorkspace %s does not exist.' % self._myPeakWorkspaceName)
please review

2018-09-24 14:37 UTC, luzpaz commented on scripts/HFIR_4Circle_Reduction/reduce4circleControl.py
> +            'Center column number {0} of type {1} must be either None or non-negative integer.' \
please review

2018-09-24 14:37 UTC, luzpaz commented on scripts/Inelastic/Direct/DirectEnergyConversion.py
> +    except Exception:
please review source change

2018-09-24 14:37 UTC, luzpaz commented on scripts/Interface/ui/sans_isis/sans_data_processor_window.ui
> +                        <string>Memory&amp;y</string>
I will revert this commit.

2018-09-24 14:37 UTC, luzpaz commented on scripts/PyChop/ISISDisk.py
> +        Returns the focused incident energy in meV
will revert this commit

2018-09-24 14:37 UTC, luzpaz commented on scripts/PyChop/MulpyRep.py
> +    efocus: The incident enrgy that all choppers are focused on
will be reverted

2018-09-24 14:37 UTC, luzpaz commented on scripts/SCD_Reduction/ReduceSCD.config
> +# Specify the slurm partition, or None to use local processes.  The parameter
is this partition or portion?

2018-09-24 14:37 UTC, luzpaz commented on scripts/SCD_Reduction/TOPAZ.config
> +# Specify the slurm partition, or None to use local processes.  The parameter
partition or portion ?

2018-09-24 14:37 UTC, luzpaz commented on scripts/test/SANS/user_file/state_director_test.py
> +    def test_stat_can_be_created_from_valid_user_file_and_later_on_reset(self):
please review

2018-09-24 17:14 UTC, AndreiSavici requested changes
Awesome PR. Revert the changes for "focused" instead of "focussed" and "Memory&amp;y"

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/PyChop/Instruments.py
> +        """Sets the (focused) incident energy"""
British spelling

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/PyChop/MulpyRep.py
> +    efocus: The incident enrgy that all choppers are focused on
British spelling

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/SCD_Reduction/TOPAZ.config
> +# Specify the slurm partition, or None to use local processes.  The parameter
"partition" is the correct choice

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/SCD_Reduction/ReduceSCD.config
> +# Specify the slurm partition, or None to use local processes.  The parameter
"partition" is the correct choice

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/PyChop/ISISDisk.py
> +        Returns the focused incident energy in meV
British spelling

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/Inelastic/Direct/DirectEnergyConversion.py
> +    except Exception:
Changes are OK

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/HFIR_4Circle_Reduction/reduce4circleControl.py
> +            'Center column number {0} of type {1} must be either None or non-negative integer.' \
Changes are OK

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/HFIR_4Circle_Reduction/peakprocesshelper.py
> +            raise RuntimeError('PeaksWorkspace %s does not exist.' % self._myPeakWorkspaceName)
Changes are OK

2018-09-24 17:14 UTC, AndreiSavici commented on scripts/Calibration/tube.py
> +    points, where there are one gaussian peak and two edges, the calibrate
"two" is correct

2018-09-24 22:39 UTC, luzpaz commented
All incorrectly fixed commits have been reverted.

2018-09-25 21:15 UTC, AndreiSavici approved these changes

2018-09-26 06:53 UTC, merged