Muon - Algorithm; MuonGroupingCounts
mantidproject/mantid pull request #23679
Opened 2018-10-02 09:04 UTC by TWJubb

Refs #23642

Requires #23677, #23678 to be merged.

This PR introduces a new algorithm `MuonGroupingCounts` which is one of a set of four algorithms intended to break up the large `MuonProcess` algorithm which is not fit for purpose with the user requirements of the new muon interface (it is too large and does not allow easy or intuitive scripting of the user workflows).

This algorithm captures the idea of a "grouping counts" operation on a workspace; which is essentially a summation of selected spectra. The input to this algorithm is intended to come from the output of `MuonPreProcess` (#23678).

The reason for this is to treat multi-period data in a consistent way; by default a single period workspace will be converted to a workspace group with a single workspace by `MuonPreProcess`; and this is what `MuonGroupingCounts` expects.

Creating this algorithm creates a logically distinct operation which is well understood by users familiar with muon workflows; rather than having the grouping counts as a subset of the behaviour of one gigantic algorithm whose >10 inputs are not intuitive. The reason to have it this way is to fulfil the user requirement of being able to replicate the muon interface workflow in the python scripting window, if required.

Unit Tests
As per instruction; unit tests have not been written yet, to focus on the functionality.

-----------------------------------------

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-10-30 15:45 UTC, Mantid-Matthew commented
The failing doctests here are due to the fact that #23678 needs to be merged first

2018-11-13 07:35 UTC, AnthonyLim23 commented on Framework/Muon/inc/MantidMuon/MuonGroupingCounts.h
> +    return {"MuonProcess"};
should include child algs and muonPreProcess and other new muon algs (later)

2018-11-13 07:37 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingCounts.cpp
> +bool is_alnum_underscore(char c) {
what is alnum?

2018-11-13 07:38 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingCounts.cpp
> +bool is_alnum_underscore(char c) {
also could we have a longer variable name (single character variables are prone to typos)

2018-11-13 10:16 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingCounts.cpp
> +    throw std::invalid_argument("Some of the detector IDs were not found");
can we change this error message to something like: "Requested a detector outside of range ( wsIndicies.size() > detectorIDs.size)"?

2018-11-13 14:00 UTC, Mantid-Matthew commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
It does throw an error on line 44 which is modified above. Algorithms by default don't rethrow errors however they instead print out the message to the dialog window.

2018-11-13 14:03 UTC, AnthonyLim23 commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
we would like them to throw in the GUI so we can then catch the error and put it into a warning

2018-11-13 14:04 UTC, Mantid-Matthew commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
I will check what ASSERT_THROWS does though as slightly uncertain here.

2018-11-13 14:33 UTC, Mantid-Matthew commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
We could easily add it here? https://github.com/mantidproject/mantid/blob/master/Framework/Muon/src/MuonAlgorithmHelper.cpp#L582

2018-11-13 14:35 UTC, AnthonyLim23 commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
Lets give it a go

2018-11-13 14:35 UTC, AnthonyLim23 commented on Framework/Muon/test/MuonGroupingCountsTest.h
> +    TS_ASSERT(!alg->isExecuted());
dont need to do it now, just later

2018-11-14 13:00 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingCounts.cpp
> +                                "(wsIndicies.size() > detectorIDs.size)");
sorry, but could we have the numbers displayed instead of detectorIDs.size?

2018-11-19 08:48 UTC, AnthonyLim23 commented
needs a clang otherwise looks good

2018-11-19 12:41 UTC, AnthonyLim23 submitted a review, later dismissed

2018-11-20 12:40 UTC, gvardany requested changes
Please see few minor comments inline.

2018-11-20 12:40 UTC, gvardany commented on Framework/Muon/CMakeLists.txt
>          src/MuonAlgorithmHelper.cpp
It seems the indentation gone wrong in the cmake file.

2018-11-20 12:40 UTC, gvardany commented on Framework/Muon/inc/MantidMuon/MuonAlgorithmHelper.h
> +DLLExport bool is_alphanumeric_or_underscore(char character);
The method names must be in camelCase instead of using `_`.

2018-11-26 10:41 UTC, gvardany approved these changes

2018-11-27 08:21 UTC, merged