Muon - Algorithm; MuonGroupingAsymmetry
mantidproject/mantid pull request #23680
Opened 2018-10-02 09:10 UTC by TWJubb

Refs #23642

Requires #23677, #23678 to be merged.

This PR introduces a new algorithm `MuonGroupingAsymmetry` which is one of a set of four algorithms intended to break up the large `MuonProcess` algorithm which is not fit for purpose with the user requirements of the new muon interface (it is too large and does not allow easy or intuitive scripting of the user workflows).

This algorithm captures the idea of a "grouping asymmetry" operation on a workspace. The input to this algorithm is intended to come from the output of `MuonPreProcess` (#23678).

The reason for this is to treat multi-period data in a consistent way; by default a single period workspace will be converted to a workspace group with a single workspace by `MuonPreProcess`; and this is what `MuonGroupingAsymmetry` expects.

Creating this algorithm creates a logically distinct operation which is well understood by users familiar with muon workflows; rather than having the grouping asymmetry as a subset of the behaviour of one gigantic algorithm whose >10 inputs are not intuitive. The reason to have it this way is to fulfil the user requirement of being able to replicate the muon interface workflow in the python scripting window, if required.

###Unit Tests

As per instruction; unit tests have not been written yet, to focus on the functionality.

----------------------

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-11-13 11:06 UTC, AnthonyLim23 commented on Framework/Muon/inc/MantidMuon/MuonGroupingAsymmetry.h
> +    return {"MuonProcess"};
we should include child algs and the other new muon algs

2018-11-13 11:07 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +bool is_alnum_underscore(char c) {
I have seen this a few times so probably should be common code.

2018-11-13 11:13 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  asym->setProperty("NormalizationIn", 0.0);
some times we will want to pick the normalizationIn so we should make this an argument of the alg

2018-11-13 11:17 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +calculateMuonAsymmetry(WorkspaceGroup_sptr inputWS,
this is not actually a calculation and is an estimate, so we should change the name of the method

2018-11-13 11:19 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +                  "Start time for the asymmetry calculation (in micro "
estimate

2018-11-13 11:19 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +                  "End time for the asymmetry calculation (in micro seconds). "
estimate

2018-11-13 11:32 UTC, AnthonyLim23 commented on docs/source/algorithms/MuonGroupingAsymmetry-v1.rst
> +After the grouping is performed, the analysis described in :ref:`algm-EstimateMuonAsymmetryFromCounts` will be run; effectively estimating the muon decay curve and subtracting it from the grouped dat
it removes the exp decay and then estimates the asymmetry on the grouped data

2018-11-13 11:33 UTC, AnthonyLim23 commented on docs/source/algorithms/MuonGroupingAsymmetry-v1.rst
> +    AddSampleLog(workspace=workspace, LogName="goodfram", LogText ="10")
just change it to 1 instead of 10. It is a sensible arbitery number

2018-11-14 13:02 UTC, AnthonyLim23 commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +
should also assert that the norm is 15, we can get the value from the sample logs of the output

2018-11-19 08:49 UTC, AnthonyLim23 commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::string norm = wsOut->getLog("analysis_asymmetry_norm")->value();
would it not be better to get it as a double?

2018-11-19 08:50 UTC, AnthonyLim23 commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +bool is_alnum_underscore(char c) {
we can use the one in the helper class now

2018-11-27 13:40 UTC, AnthonyLim23 submitted a review, later dismissed

2018-11-29 09:30 UTC, AnthonyLim23 submitted a review, later dismissed
test had to change as the first bin was excluded in the calculations

2018-11-30 10:41 UTC, soininen requested changes

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +                                 WorkspaceGroup_sptr workspace) {
`workspace` could be passed as a reference avoiding a shared pointer copy.

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +    std::vector<int> spec(1, index);
```suggestion
    const std::vector<int> spec(1, index);
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::vector<size_t> wsIndices =
```suggestion
  const std::vector<size_t> wsIndices =
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::vector<int> defaultPeriods = {1};
These could be declared `const` if I understood this correctly.

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::string groupName = this->getProperty("GroupName");
```suggestion
  const std::string groupName = this->getProperty("GroupName");
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  WorkspaceGroup_sptr inputWS = getProperty("InputWorkspace");
```suggestion
  WorkspaceGroup_const_sptr inputWS = getProperty("InputWorkspace");
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::vector<int> subtractedPeriods = getProperty("SubtractedPeriods");
`const` qualify both `vector`s

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +      boost::dynamic_pointer_cast<WorkspaceGroup>(inputWS);
`inputWS` is already declared as `WorkspaceGroup_sptr` above, so why this cast? Am I missing something here?

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::vector<int> group = this->getProperty("Grouping");
```suggestion
  cosnt std::vector<int> group = this->getProperty("Grouping");
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/src/MuonGroupingAsymmetry.cpp
> +  std::vector<int> subtractedPeriods = getProperty("SubtractedPeriods");
`const` for both `vector`s?

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> group = {1};
```suggestion
    const std::vector<int> group = {1};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> group = {1};
```suggestion
    const std::vector<int> group = {1};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<std::string> validNames = {"fwd", "fwd2", "bwd_2"};
```suggestion
    const std::vector<std::string> validNames = {"fwd", "fwd2", "bwd_2"};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> group = {1};
`const`

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<std::string> invalidNames = {"@", "fwd!", "#1", "fwd @", "   "};
```suggestion
    const std::vector<std::string> invalidNames = {"@", "fwd!", "#1", "fwd @", "   "};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> detectors = {6, 7, 8, 9, 10};
```suggestion
    const std::vector<int> detectors = {6, 7, 8, 9, 10};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {};
`const` all three vectors here.

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> summedPeriods = {3};
`const` the `vector`s

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {3};
ditto

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> summedPeriods = {-1};
ditto

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {-1};
ditto

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> detectors = {1};
```suggestion
    const std::vector<int> detectors = {1};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> detectors = {1, 2};
```suggestion
    const std::vector<int> detectors = {1, 2};
```

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {2, 3};
`const` the `vector`s.

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {1};
ditto

2018-11-30 10:41 UTC, soininen commented on Framework/Muon/test/MuonGroupingAsymmetryTest.h
> +    std::vector<int> subtractedPeriods = {1};
ditto

2018-12-03 09:33 UTC, soininen approved these changes

2018-12-03 09:33 UTC, merged