Load an ANSTO EMU datafile (no ticket)
mantidproject/mantid pull request #23713
Opened 2018-10-03 23:54 UTC by geishm-ansto

Loads an ASNTO EMU datafile as a TOF EventWorkspace.

No issue number allocated - I am an external contributor working for ANSTO.

Contains a unit test LoadEMUauTest.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-10-08 22:06 UTC, geishm-ansto commented
Applied the clang-format patch to the master and pushed back up.

2018-10-09 02:16 UTC, geishm-ansto commented
Don't understand why cppcheck is failing still - the errors were fixed with the update eg _cancel is still flagged as an unused variable but it was removed in the update.

2018-10-09 08:09 UTC, martyngigg commented
@geishm-ansto It looks like the failures are due to similar fields in the`.cpp` file and your fixes above only changed things in the `.h` file.

2018-10-09 22:49 UTC, geishm-ansto commented
Apologies, there was a remnant LoadANSTOEventFile.cpp file that was removed from the repository. The clang-format check is using the latest revision 'b7bd301..' but  the cpp-check refers to rev '364f1..' and is failing on the file that was deleted.

2018-10-11 06:39 UTC, geishm-ansto commented
@martyngigg I can't determine the segmentation fault on the Linux platforms from the error messages. I think my only option is to clone the code on a local Linux machine to solve the problem. Unless you have a suggestion, I should close this pull request and come back later. Thanks for your patience.

2018-10-11 08:09 UTC, martyngigg commented
@geishm-ansto The segfault appears to occur when [retrieving instrument parameters](https://github.com/mantidproject/mantid/pull/23713/files#diff-dd771b9d041331dca8b354c9fe55fadbR594). It looks like the instrument parameter file has failed to be found on Linux because we extract the instrument name from the filename of the `_Definition.xml` file and then force it to be upper case. As the filesystem is case sensitive on Linux it fails to find `EMUau_Paramters.xml` as it is looking for `EMUAU_Parameters.xml`. Windows/Mac are not case sensitive so they don't see the same issue.

I have a feeling that this prefix transformation is a hangover from the past as I don't see why it is necessary. I'll check and if others agree then we can just remove [this line](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadInstrument.cpp#L290) and the test should be good.

2018-10-11 12:16 UTC, martyngigg commented
@geishm-ansto I have agreed with others that the current behaviour is odd and we should fix it. Would you be able to remove [this line](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadInstrument.cpp#L290) to stop the prefix being changed? This should fix your issue.

2018-10-11 23:35 UTC, geishm-ansto commented
@martyngigg Thanks, that was the issue - all the checks pass now.

2018-10-16 21:51 UTC, geishm-ansto commented
@martyngigg Is there any more I need to do on my end with this pull request?

2018-10-17 09:22 UTC, soininen requested changes
The code quality of the new loader looks superb, although I couldn't test this myself as no test instructions nor data was provided. Hopefully the unit test is sufficient. I couldn't find any changes to the release notes, so please consider adding a line to `docs/sources/release/v3.14.0/indirect_inelastic.rst` or whatever is suitable.

That said there were a few minor issues in the code, please see the comments below. Additionally, I would've hoped to see more `const` keywords peppered around the function parameters and local variables.

2018-10-17 23:43 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +// Types of OOB events, and 'NEUTRON' event.  Not all are used for all
Cleaned up the comment formatting.

2018-10-17 23:46 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +  // headers, hence a command line option -c is provided to allow it to be
Changed to function argument.

2018-10-17 23:46 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +    ;
Removed.

2018-10-17 23:48 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +           .clock_scale) { // old eventfile format did not have clock_scale...
Done.

2018-10-18 00:06 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +void ReadEventFile(IReader &loader, IEventHandler &handler, IProgress &progress,
I am not the original author of this code but appreciate the complexity of decoding of an existing intricate binary packing format.  I agree the state machine could be cleaned up but the intent was to re-use a working decoder with a wrapper to make it useable. I would be reluctant to make structural changes now.

2018-10-18 01:03 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
> +Loads an Emu data file. Implements API::IFileLoader and its file check methods
I couldn't find the reference to copyright on the mantid documentation nor the python update script. I updated the header based on the LoadISISNexus2.h format and added the required and optional parameters.

2018-10-18 01:09 UTC, geishm-ansto commented on Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
> +  DataObjects::EventWorkspace_sptr m_localWorkspace;
Done.

2018-10-18 02:03 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +#include <stdio.h>
Moved and dropped <stdio.h>

2018-10-18 02:16 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +static const size_t DETECTORS = 51;
Agreed and changed.

2018-10-18 02:31 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +void mapRangeToIndex(const std::string &line, std::vector<T> &result,
Moved the local functions to the anonymous namespace but kept EMU to capture the changes from the existing class definitions.

2018-10-18 02:31 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +// - the loader returns returns the doppler and auxillary time along with the
Fixed.

2018-10-18 03:12 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +      Kernel::make_unique<Kernel::PropertyWithValue<std::string>>(
Done.

2018-10-18 03:46 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +    API::AnalysisDataService::Instance().remove(outName);
I am still not fluent in the framework and copied existing code. Have removed the calls.

2018-10-18 06:03 UTC, geishm-ansto commented on Framework/DataHandling/src/LoadEMU.cpp
> +void LoadEMU::exec() {
Extracted several smaller functions to improve the readability.

2018-10-18 06:03 UTC, geishm-ansto commented on docs/source/algorithms/LoadEMU-v1.rst
> +.. categories::
Moved to the end.

2018-10-18 06:49 UTC, soininen commented on Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
> +void ReadEventFile(IReader &loader, IEventHandler &handler, IProgress &progress,
I understand and agree. Better leave it as-is.

2018-10-18 06:51 UTC, soininen commented
@geishm-ansto Looks like you have to `#include<exception>` or something similar.

2018-10-18 10:21 UTC, soininen commented on Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
> +Loads an Emu data file. Implements API::IFileLoader and its file check methods
I think the copyright changed after you branched out from master. Please, merge master, or check how the copyright looks there.

2018-10-18 10:21 UTC, soininen commented on Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
> +Loads an Emu data file. Implements API::IFileLoader and its file check methods
Also the script mentioned above is available in the latest master.

2018-10-18 23:45 UTC, geishm-ansto commented
@soininen I've fixed those exceptions. My development is on Windows but I can't find any options on Visual Studio that ignore Windows deviations from the standards. It would make my life easier. :-)

2018-10-19 08:55 UTC, soininen commented
@geishm-ansto Every compiler seems to have its own little quirks. I'm on gcc and have to occasionally fix stuff that Visual Studio's better diagnostics finds. Anyway, this looks good to me now. Thanks a lot for the high quality contribution!

2018-10-19 08:56 UTC, soininen approved these changes

2018-10-19 14:03 UTC, merged