Modernize event filter gui
mantidproject/mantid pull request #23778
Opened 2018-10-12 11:40 UTC by peterfpeterson

The main task was to make the gui qt4/qt5 compatible so something could be included in the new workbench. Part of what was done was to refactor a some associated code into an abstraction of the matplotlib backends to access widgets in `MPLwidgets` and add `gui_helper.py` to assist in setting the correct matplotlib backend and launch custom guis with less boilerplate code.

**To test:**

From mantidplot: Interfaces -> Utilities -> FilterEvents

From the commandline: `mantidpython .../scripts/FilterEvents.py` and `mantidpython --classic .../scripts/FilterEvents.py`.

Launching the GUI from inside mantidworkbench needs further work to sort out the threading and setting the parent correctly.

This is associated with #23762.

*This does not require release notes* because workbench.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-10-12 13:59 UTC, rosswhitfield requested changes
Starting FilterEvents in the workbench with python2 I get
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 155, in __draw_idle_agg
    self.draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 128, in draw
    self.update()
RuntimeError: wrapped C/C++ object of type MplFigureCanvas has been deleted
```

with python3 I get
```
Traceback (most recent call last):
  File "/home/rwp/mantid/qt/applications/workbench/workbench/app/mainwindow.py", line 291, in <lambda>
    action.triggered.connect(lambda checked, script=script: self.launchCustomGUI(script))
  File "/home/rwp/mantid/qt/applications/workbench/workbench/app/mainwindow.py", line 254, in launchCustomGUI
    execfile(script)
NameError: name 'execfile' is not define
```

2018-10-12 14:09 UTC, martyngigg commented on scripts/FilterEvents.py
> +app, within_mantid = get_qapplication()
Nice!

2018-10-12 14:11 UTC, martyngigg commented
I'm also seeing an error when trying to start it in MantidPlot:
```
ImportError: cannot import name load_ui
  at line 12 in '<Interface>'
  caused by line 30 in '/media/data1/source/github/mantidproject/mantid/scripts/FilterEvents/eventFilterGUI.py'
```

2018-10-16 13:34 UTC, rosswhitfield approved these changes

2018-10-16 16:14 UTC, merged