23827 indirect bayes move run button for disabling
mantidproject/mantid pull request #23846
Opened 2018-10-18 09:52 UTC by robertapplin

**Description of work.**
This PR moves the run button above the output options on the Indirect Bayes interface.
This PR ensures the run, plot and save options are disabled while running and plotting is taking place.

**To test:**
1. `Interfaces`->`Indirect`->`Bayes`
2. Load the data below
3. Click `Run` and ensure the run, plot and save options are disabled
4. Click `Plot` and ensure the run, plot and save options are disabled

- For the third interface `Stretch`, clicking `Plot` should result in an error message. This is a good way of checking that all the buttons are re-enabled even after an error.

**Data Files**

**ResNorm**
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491289/irs26173_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491290/irs26173_graphite002_res.zip)

**Quasi**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

**Stretch**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

Fixes #23827 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-10-19 08:02 UTC, LowriJenkins reviewed
I've Reviewed as much of this as I can, The code is fine and ResNorm works fine, however the other tabs use algorithms that don't run on linux so I am unable to review them.

2018-10-19 08:52 UTC, SpencerHowells commented
@robertapplin @SamJenkins1 Forgot to remind you that the other tabs use Fortran code which is only distributed for Windows.

2018-11-01 11:08 UTC, mantid-roman requested changes
If a default save directory is set Run doesn't work in Quasi and Stretch.

2018-11-02 08:54 UTC, robertapplin commented
@mantid-roman Thanks for spotting this. It should work fine now.

2018-11-02 11:07 UTC, mantid-roman commented
@robertapplin It works now. One last question: the plot on Stretch page doesn't show the fit or diff lines after a fit, is it by design or a bug?

2018-11-02 11:21 UTC, robertapplin commented
@mantid-roman  That is strange, I believe this is a bug - I will create a new issue for this. Seeing as the Bayes interface tends to be unmanaged, this problem may have been around for a while.

2018-11-02 11:23 UTC, mantid-roman submitted a review, later dismissed

2018-11-02 15:35 UTC, soininen requested changes

2018-11-02 15:35 UTC, soininen commented on qt/scientific_interfaces/Indirect/Quasi.cpp
> +  for (std::string const paramName : paramNames) {
```suggestion
  for (std::string const &paramName : paramNames) {
```

2018-11-05 08:36 UTC, soininen approved these changes

2018-11-05 08:36 UTC, merged