Package Mantid Workbench for OSX
mantidproject/mantid pull request #24082
Opened 2018-11-22 16:31 UTC by samueljackson92

**Description of work.**

This adds an application bundle for the workbench for OSX.

**To test:**

This needs to be tested on all supported platforms incase we have broken the packaging process for another system as we've added these changes.

 - [ ] Tested on Linux
 - [ ] Tested on OSX
 - [ ] Tested on Window

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-11-27 13:18 UTC, samueljackson92 commented
@keeeto The time has come. Would you kindly give this a test drive on your mac?

2018-12-07 13:56 UTC, keeeto commented
* Add `"libboost_python27-mt.dylib"` to the `make_package.rb`
* Allow warnings when importing `PyQt5`
* Ensure that `mantid-scripts.pth` is in the Workbench package

2018-12-12 15:38 UTC, samueljackson92 commented
@keeeto Should be ready for another test when you can.

2018-12-28 14:03 UTC, mantid-builder commented
@samueljackson92 the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-01-08 09:58 UTC, martyngigg requested changes
Unfortunately we have broken something with the workbench packaging on Linux:
```
$ ls /opt/mantidnightly/bin                    
ipython_widget        mantidplot      mantidplot.py    mantidplotrc.pyc   mantidqtpython.so              mantid_reset_settings.sh  paraview-config  pvpython        pymantidplot
launch_mantidplot.sh  MantidPlot      mantidplot.pyc   Mantid.properties  mantid_qt_settings_editor.py   mantid-scripts.pth        pvbatch          pvrenderserver  workbench
mantid                MantidPlot_exe  mantidplotrc.py  mantidpython       mantid_qt_settings_editor.pyc  mantidworkbench           pvdataserver     pvserver
$ ls /opt/mantidunstable/bin
ipython_widget        lib         MantidPlot      mantidplot.pyc    Mantid.properties  mantid_qt_settings_editor.py   mantid-scripts.pth  pvbatch       pvrenderserver
launch_mantidplot.sh  mantid      MantidPlot_exe  mantidplotrc.py   mantidpython       mantid_qt_settings_editor.pyc  mantidworkbench     pvdataserver  pvserver
launch_workbench      mantidplot  mantidplot.py   mantidplotrc.pyc  mantidqtpython.so  mantid_reset_settings.sh       paraview-config     pvpython      pymantidplot
$ ls /opt/mantidunstable/lib    
libMantidAPI.so          libMantidHistogramData.so  libMantidParallel.so             libMantidQtWidgetsInstrumentViewQt4.so   libMantidQtWidgetsSliceViewerQt4.so     mantidqt-3.13.20190108.908.egg-info
libMantidBeamline.so     libMantidIndexing.so       libMantidPythonInterfaceCore.so  libMantidQtWidgetsInstrumentViewQt5.so   libMantidQtWidgetsSpectrumViewerQt4.so  MantidWorkbench-3.13.20190108.908.egg-info
libMantidCatalog.so      libMantidKernel.so         libMantidQtWidgetsCommonQt4.so   libMantidQtWidgetsLegacyQwtQt4.so        libMantidTypes.so                       paraview-5.4
libMantidDataObjects.so  libMantidNexusGeometry.so  libMantidQtWidgetsCommonQt5.so   libMantidQtWidgetsMplCppQt5.so           libMantidVatesAPI.so                    workbench
libMantidGeometry.so     libMantidNexus.so          libMantidQtWidgetsFactoryQt4.so  libMantidQtWidgetsRefDetectorViewQt4.so  mantidqt
```

It seems that we have put the `lib` folder in `bin` but this shouldn't be there.

2019-01-08 10:19 UTC, martyngigg commented on buildconfig/CMake/PythonPackageTargetFunctions.cmake
> +    # register the "installed" components with cmake so it will carry them over
I think this is the cause of the duplicate `lib` directory installation. Is this not a duplicate of line `87`?

2019-01-08 10:20 UTC, martyngigg commented on buildconfig/CMake/PythonPackageTargetFunctions.cmake
> +    # register the "installed" components with cmake so it will carry them over
I think line `87` is the one we need to keep.

2019-01-11 08:00 UTC, samueljackson92 commented
@keeeto When you have time could you retest this on OSX. I made some changes to the DMG installer that it would be worth just checking on someone else's machine.

@martyngigg When you have time I think this is good to be retested on Linux and tested on Windows.

2019-01-11 12:35 UTC, martyngigg requested changes

2019-01-11 12:35 UTC, martyngigg commented on scripts/ErrorReporter/error_dialog_app.py
> +print(sys.path)
We left a print statement in...

2019-01-11 12:35 UTC, martyngigg commented on buildconfig/CMake/PythonPackageTargetFunctions.cmake
> +    # install the generated executable - only tested with "workbench"
I think we've duplicated these lines so lines 102-107 can be removed.

2019-01-11 12:35 UTC, martyngigg commented on buildconfig/CMake/PythonPackageTargetFunctions.cmake
> +                RENAME launch_workbench)
The renaming here has broken the Linux packaging.  Let's remove the `RENAME launch_workbench` and leave it as workbench. We'll then need to update [MantidWorkbench_osx_launcher](https://github.com/samueljackson92/mantid/blob/workbench-package-osx/buildconfig/CMake/Packaging/osx/MantidWorkbench_osx_launcher#L6) to change `./launch_workbench` to just `./workbench`.

2019-01-11 17:58 UTC, martyngigg submitted a review, later dismissed
Works for me now!

2019-01-11 17:59 UTC, martyngigg commented
Gatekeepers: Please wait for confirmation from tests on the other OSs

2019-01-14 15:05 UTC, DTasev commented
I will try this change on Windows

2019-01-14 19:04 UTC, DTasev commented
Package built, installed and ran MantidPlot and Workbench successfully. No issues found

2019-01-14 19:11 UTC, dtasev submitted a review, later dismissed

2019-01-15 07:57 UTC, samueljackson92 commented
Just waiting on a retest of OSX now. One last time @keeeto?

2019-01-21 11:38 UTC, martyngigg requested changes
The `MantidWorkbench` bundle is missing `sip.so` and `skimage` from the `Contents/MacOS` directory

2019-01-21 16:36 UTC, martyngigg approved these changes
It works!

2019-01-22 10:45 UTC, merged