Vates testing docs
mantidproject/mantid pull request #24104
Opened 2018-11-27 10:02 UTC by keeeto

**Description of work.**

This PR adds testing for the VATES interface. This testing will be done in each release cycle to ensure that the interface is in minimal required working condition. This means that all features that are regularly/routinely required by users should be tested and verified.

**Report to:** nobody. 

**To test:**

* Build the `dev-docs-html`
* Open `dev-docs/index.html` and navigate to `Testing` > `VATES Testing`
* Check that the tests make sense and cover all required features

*There is no associated issue.*

*This does not require release notes* because it is not a user-facing feature.
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-11-27 10:08 UTC, OwenArnold commented on dev-docs/source/Testing/VATES/VATESTEsting.rst
> +.. _vates_testing:
I will do a more thorough review when I'm back, but all references to "VATES" should be VSI. Vates was the original project name, which included visualisation and workspace extensions for multidimensional processing. VSI is vates-simple-interface, which we already refer to in all existing documentation. Personally I would prefer that this was called "n-d viewer" or something similar, but VSI is the best choice for now.

2018-11-27 19:46 UTC, OwenArnold requested changes
Apart from that minor correction looks very good. Would be even better as a squish test ;)

2018-11-27 19:46 UTC, OwenArnold commented on dev-docs/source/Testing/VSI/VSITesting.rst
> +#. This should load a workspace called QLab. Right-click this workspace and choose 'Show VSI simple interface'.
Sorry to be pedantic, but the menu option is actually "Show VATES simple interface"

2018-11-27 19:48 UTC, OwenArnold commented on dev-docs/source/Testing/index.rst
> +   VATES/VATESTEsting
VSITesting?

2018-12-17 14:03 UTC, mantid-builder commented
@keeeto could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-01-01 14:03 UTC, mantid-builder commented
@keeeto have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2019-01-02 08:33 UTC, keeeto commented
@OwenArnold - I think that all the changes you requested are made. Just requires a final ok from your end. Cheers.

2019-01-02 11:21 UTC, OwenArnold approved these changes

2019-01-03 12:55 UTC, merged