Indirect - Chi squared in Result workspace and plot combobox
mantidproject/mantid pull request #24113
Opened 2018-11-27 14:18 UTC by robertapplin

**Description of work.**
This PR ensures that Chi_squared is added to the bottom row of the Results workspaces for Indirect Data Analysis (MSDFit, IqtFit, ConvFit and F(Q) Fit).
This PR also allows the plotting of Chi_squared in the output options.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`
2. In turn, run a fit on MSDFit, IqtFit, ConvFit and F(Q) Fit using the data below
3. The result workspaces last row should be Chi-Squared
4. An option to plot chi-squared should be given in the output options in the `Plot` Combobox
5. This should plot the values that can be found in the result workspace

**Data**

Fixes #24111 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-02 14:03 UTC, mantid-builder commented
@robertapplin it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2019-02-12 14:03 UTC, mantid-builder commented
@robertapplin do you want to request a review on this PR?
<!-- {"problem_type": "unreviewed"} -->

2019-03-05 07:35 UTC, soininen requested changes
Chi squared is added to the result workspaces and can be plotted as described. The code changes look good too. However, I propose to use `std::fill_n` as explained in the comments below. Two issues I encountered which are not in the scope of this PR but perhaps could be tackled later:

- The result workspace when choosing the 'Fit' option from the 'Fit' combo box-button does not have the chi squared row. I don't know if this is desired but it is inconsistent.
- When setting the plot panel as floating, there is no way of moving the panel on my system (Ubuntu 16.04). I can only resize it in the floating state.

2019-03-05 07:35 UTC, soininen commented on Framework/WorkflowAlgorithms/src/ProcessIndirectFitParameters.cpp
> +    e.emplace_back(0.0);
`std::fill` or `std::fill_n` should do the job as well. I am unsure if you need this entire function just for this purpose.

2019-03-05 07:35 UTC, soininen commented on Framework/WorkflowAlgorithms/src/ProcessIndirectFitParameters.cpp
> +      populateChiSquaredErrorsWithZeros(e, y.size() - e.size());
`std::fill_n`

2019-03-05 08:32 UTC, SpencerHowells commented
@soininen @robertapplin Regarding the floating panel. Marina discovered that problem during testing. It is a bug in Qt that affects linux only.

2019-03-05 09:19 UTC, robertapplin commented
@soininen Thank you for finding these bugs. As @SpencerHowells said the floating panel not moving on linux is a qt bug. Regarding the Fit ComboBox, this combobox will be removed when Simultaneous fitting has been implemented and so it is probably not worth looking into this

2019-03-25 14:03 UTC, mantid-builder commented
@robertapplin have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-03-27 07:46 UTC, soininen commented
There seems to be a merge conflict now.

2019-03-27 08:25 UTC, robertapplin commented
Thanks @soininen , the conflict should be fixed now.

2019-03-27 14:50 UTC, soininen approved these changes

2019-03-28 06:50 UTC, merged