Fix GuiStartupTest on Windows
mantidproject/mantid pull request #24152
Opened 2018-11-30 12:55 UTC by martyngigg

**Description of work.**

The test was always being skipped as `wscript.exe ...` is not a valid path. We were also missing the `launch_mantidplot` script for the development builds so this has been added so the test can work on a development copy. 

**Report to:** [nobody]. 

**To test:**

Checkout and build the code. Run the `GuiStartup` system test and check it passes. 

*There is no associated issue.*

*This does not require release notes* because **it's an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-11-30 13:57 UTC, dtasev requested changes

2018-11-30 13:57 UTC, DTasev commented on Testing/SystemTests/tests/analysis/GUIStartupTest.py
> +            mantid_exe = os.path.join(mantid_init_dirname, "..", "launch_mantidplot.bat"))
There's a syntax error here - an extra `)` at the end

2018-11-30 13:57 UTC, DTasev commented on Testing/SystemTests/tests/analysis/GUIStartupTest.py
> +        self.assertTrue(b'Hello Mantid' in out)
This assertion fails for me - `out` is empty and `err` contains: `'python: can\\'t open file \\'\\scripts\\ErrorReporter\\error_dialog_app.py\\': [Errno 2] No such file or directory'`

2018-11-30 14:10 UTC, DTasev commented
This [check](https://github.com/mantidproject/mantid/pull/24152/files#diff-9825ce855804677914e0bb75a1a4eeb3R43) if the mantid launch script exists can silently hide cases where it _doesn't_ because it skips the test - I think that would be better raised as a test fail or a runtime error, now that the test will be executed every time

2018-11-30 15:12 UTC, martyngigg commented
The one complication is that there are cases where they legitimately don't exist so we'd need a way to flag whether we should require it or not.

2018-12-03 15:49 UTC, martyngigg commented
Maybe need a flag that is passed in by the job starting the tests to indicate if any GUI tests should be run?

2018-12-18 14:03 UTC, mantid-builder commented
@martyngigg could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-01-02 14:03 UTC, mantid-builder commented
@martyngigg could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2019-01-30 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to look at the review comments yet?
<!-- {"problem_type": "ignored_review"} -->

2019-02-14 14:03 UTC, mantid-builder commented
@martyngigg the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-03-01 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-03-21 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-04-04 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-04-18 14:03 UTC, mantid-builder commented
@martyngigg the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-04-29 08:39 UTC, martyngigg commented
I'm closing this as I'd like to rethink it in next maintenance.

2019-04-29 08:39 UTC, closed without merging