Indirect - Crash when loading F(Q) Fit data
mantidproject/mantid pull request #24219
Opened 2018-12-04 11:54 UTC by robertapplin

**Description of work.**
This PR fixes a bug which causes a crash when loading data across multiple Data Analysis interfaces.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` Tab
2. Load the data below
3. Go to the F(Q)Fit tab and load the data below
crash!

**Data Files**
**ConvFit**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2640133/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2640134/irs26173_graphite002_res.zip)
**F(Q)Fit**
[iris26174_graphite002_s0-17_Result.zip](https://github.com/mantidproject/mantid/files/2640135/iris26174_graphite002_s0-17_Result.zip)

Fixes #24199 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-12-06 17:53 UTC, dtasev requested changes
I managed to replicate the crash in the nightly, and after building this it was gone.

--------------------------------

I found some other errors (likely unrelated), this first one leaves Mantid unusable:
Go to Indirect > Data Analysis > ConvFit
Load `irs26176_graphite002_red` and res file `irs26173_graphite002_res`
Delete the workspaces from the ADS
Click Run

I guess the expected behaviour would be to reload the workspaces

Second one:
Go to Indirect > Data Analysis > ConvFit
Load `irs26176_graphite002_red` and res file `irs26173_graphite002_res`
Click Run
Go to `F(Q) Fit` tab
Change Sample `File` to `Workspace`, unhandled exception error should pop up.

If you think these 2 errors should be fixed in different PRs, I am happy to approve this one when new issues have been opened

2018-12-07 08:33 UTC, robertapplin commented
@DTasev Thank you for finding these problems. Yes I think it would be best to fix these in different PRs. I have created an issue for the first problem you found #24273. The second issue should be fixed in the PR #23221

2018-12-07 08:43 UTC, dtasev approved these changes

2018-12-07 08:46 UTC, DTasev commented
👍 :shipit:

2018-12-07 09:06 UTC, merged