Print sample log's units, if present
mantidproject/mantid pull request #24321
Opened 2018-12-13 09:45 UTC by reimundILL

**Description of work.**

The algorithm  `SaveReflectometryAscii` saves as well SampleLog information to file. Now, units will be printed, if present.

**To test:**

- Consult the usage example of the documentation
- Create a workspace and SampleLogs with units
- Run the algorithm
- Check that the resulting file contains the units of log values

or
- Make sure that you trust the unit test
- Observe that the tests do not fail

Fixes #24312.

*This does not require release notes* : deprecated reflectometry save algorithms do not print units and nobody seem to care about it. I do not believe that we need to update the documentation since I believe this behavior is simply expected.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-12-13 14:19 UTC, peterfpeterson requested changes
Only one small change is needed.

2018-12-13 14:19 UTC, peterfpeterson commented on Framework/DataHandling/src/SaveReflectometryAscii.cpp
> +  return "";
Very minor point: I prefer you put the return for failure inside the catch block

2018-12-13 14:19 UTC, peterfpeterson commented on Framework/DataHandling/src/SaveReflectometryAscii.cpp
> +    m_file << logName << " : " << sampleInfo(logValue) << sampleUnit(logValue)
shouldn't the second part be `sampleUnit(logName)`? An improvement is to declare a constant at the top of the function `const std::string logUnit = sampleUnit(logName);` and use that everywhere below.

2018-12-13 14:30 UTC, peterfpeterson commented on Framework/DataHandling/src/SaveReflectometryAscii.cpp
> +    m_file << logName << " : " << sampleInfo(logValue) << sampleUnit(logValue)
Shouldn't the line be
```c++
m_file << logName << " : " << sampleInfo(logValue) << sampleUnit(logName)
```

2018-12-14 10:30 UTC, reimundILL commented
Some finding:

![logs](https://user-images.githubusercontent.com/19187274/49998113-aea31980-ff93-11e8-9171-09ecfb8fb086.png)

2018-12-14 13:22 UTC, peterfpeterson approved these changes
This highlights the importance of good variable names.

2018-12-14 19:56 UTC, merged