Add SetCrystalLocation
mantidproject/mantid pull request #24331
Opened 2018-12-13 18:28 UTC by sullivanbt

New algorithm `SetCrystalLocation` to set the sample position of an events workspace.  This provides a nice, simple interface to adjust sample position when recreating MD workspaces with samples not at the origin.

No tests have been added since it changes the sample position the same way that `OptimizeCrystalPlacement` does, which already has tests.  

**To test:**
```python
events = Load('TOPAZ_3007_bank_37_20_sec.nxs')
sample = mtd['events'].getInstrument().getSample()
print('Sample position before SetCrystalLocation: {}'.format(sample.getPos()))
SetCrystalLocation(InputWorkspace=events, OutputWorkspace=events, NewX=0.1, NewY=0.1, NewZ=0.1)
print('Sample position after SetCrystalLocation: {}'.format(sample.getPos()))
```
You can also verify that MDWorkspaces created from these are different.  Note that if you test that, you must delete the preprocessed detectors workspace or name a new preprocessing workspace when calling `ConvertToMD`.

Fixes #24329 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-12-18 13:32 UTC, VickieLynch submitted a review, later dismissed
Not sure why the doc tests are failing since the file is found by doc tests on my machine.

2018-12-18 13:47 UTC, VickieLynch commented
Ubuntu build servers do not have systemtest data.  Change doc test to read this file:  events = Load('BSS_11841_event.nxs')

2018-12-18 14:06 UTC, VickieLynch submitted a review, later dismissed

2018-12-20 07:21 UTC, soininen requested changes
A few minor comments below. Why no unit tests? Release notes should be added, as well.

2018-12-20 07:21 UTC, soininen commented on Framework/Crystal/inc/MantidCrystal/SetCrystalLocation.h
> +// Copyright &copy; 2012 ISIS Rutherford Appleton Laboratory UKRI,
The year should probably be 2018 already.

2018-12-20 07:21 UTC, soininen commented on Framework/Crystal/inc/MantidCrystal/SetCrystalLocation.h
> +  const std::string category() const override {
Would it make sense to have a `seeAlso()` method? `OptimizeCrystalPlacement` for example was mentioned in the PR's description.

2018-12-20 07:21 UTC, soininen commented on Framework/Crystal/src/SetCrystalLocation.cpp
> +  V3D newSamplePos = V3D(newX, newY, newZ);
The variables above could be declared `const`, I believe.

2018-12-20 20:05 UTC, sullivanbt commented
All good suggestions - the newest version takes them all into account.

2018-12-21 08:10 UTC, soininen approved these changes

2018-12-21 08:11 UTC, soininen commented
Looks good to me. The failing Windows build looks unrelated.

2018-12-21 09:30 UTC, merged