Restructure reflectometry GUI save tab
mantidproject/mantid pull request #24345
Opened 2018-12-17 09:40 UTC by gemmaguest

**Description of work.**
PR #23630 should be merged first

This PR restructures the Save Tab view/presenter for the GUI to follow the same structure as the other tabs which have already been restructured as part of #23630.

**Report to:** nobody

**To test:**

To follow

Refs #23051

*This does not require release notes* because it involves under-the-hood changes only.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-03 12:42 UTC, TTitcombe requested changes
Code changes largely moving and renaming. New code looks clean.
Test coverage is good.
I have a couple of comments about the output from saving - it is possible that these issues were not caused by this PR:
1. Repeated comments for `ISaveView` class
2. The only difference between "Custom" and "3-column" formats seems to be that checking Q resolution has no effect for 3-columns. Is there a reason both formats are explicitly needed? otherwise 3-column seems redundant
3. Saving as a custom .dat without Title checked results in an empty comment line at the top. This is not the case for 3-column .dat
4. Q res column is added for .mft files regardless of whether Q resolution is checked
5. In .mft files, subtitle is included even if Title is not checked. Will users want subtitle information without title?

2019-01-07 17:43 UTC, gemmaguest commented
Thanks for the comments @TTitcombe. I've removed the duplicated class comment.

The save output is "correct" in that it's the same as the existing behaviour, but it does need an overhaul. I've raised #24429 to deal with the problems. They're not related to this PR.

2. The "3-column" ("drydoc") format is a rigid format so this option is still required to give the user an easy way to create output for drydoc programs, even though the output can easily be produced with the "custom" option. We should grey out inputs that are not applicable when it's selected.
3. This is historical, but the `#` comment lines are no longer required. We'll replace them with an option to include the MFT header lines, as I've described in the linked issue.
4. Q res column should always be included in .mft files, so this option should be greyed out when that format is selected.
5. Good question. I think this may be fixed in the new algorithm we want to use. I've added a comment on the linked issue to check this.

2019-01-08 09:51 UTC, TTitcombe approved these changes

2019-01-17 08:15 UTC, martyngigg commented
After #23630 has been merged it looks like there are some non-trivial conflicts to resolve

2019-01-17 13:01 UTC, merged