DownloadInstrument segfault in docker and conda
mantidproject/mantid pull request #24352
Opened 2018-12-17 19:34 UTC by peterfpeterson

This changeset is to improve logging around the issue so we can better determine what is actually going on. There is an additional `nullptr` check, but it is uncertain if that will help with what was reported.

**To test:**

`DownloadInstrument(ForceUpdate=True)` should continue to work. With logging at `information`, you'll also see how many requests are left against the github REST api.

Refs #24339. This may actually fix the issue, but it needs to be merged into `master` so the docker/conda builds can have improved logging.

*This does not require release notes* because it is only an improvement in logging.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-01 14:03 UTC, mantid-builder commented
@peterfpeterson do you want to request a review on this PR?
<!-- {"problem_type": "unreviewed"} -->

2019-01-10 08:15 UTC, soininen requested changes
Clean code, just a small typo fix below. The `DownloadInstrument` seems to work as before, and just gives an error message when I run it with wrong proxy settings. Hopefully the additional logging will help with the other issues. However, workbench segfaults if I close the application while the algorithm is running. Can this be reproduced on other systems? MantidPlot waits for the algorithm to finish before closing, so no segfault in the legacy interface.

2019-01-10 08:15 UTC, soininen commented on Framework/Kernel/inc/MantidKernel/GitHubApiHelper.h.in
> +   * will never cout against your REST API limit.
```suggestion
   * will never count against your REST API limit.
```

2019-01-10 19:40 UTC, peterfpeterson commented
Your comment about proxy settings should be a proper issue on workbench.

2019-01-11 09:18 UTC, soininen commented
Reported the segfault issue in #24467.

2019-01-11 09:19 UTC, soininen approved these changes

2019-01-11 09:20 UTC, soininen commented
I think the behavior with wrong proxy settings (log an error message) is correct.

2019-01-11 16:00 UTC, merged