Indirect Data Analysis - Elwin plot spectrum options
mantidproject/mantid pull request #24356
Opened 2018-12-18 11:46 UTC by robertapplin

**Description of work.**
This PR introduces options to allow the user to select which workspaceIndex should be plotted and from which workspace when clicking `Plot Spectrum`.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`Elwin` tab
2. Load the data below
3. Click `Run` and wait
4. The workspace names `irs26176_graphite002_elwin_eq` and `irs26176_graphite002_elwin_eq2` should appear in the Output options combo box.
5. Try changing the spinbox next to the combobox. This should stay at zero for both workspaces as they both have only 1 spectrum.
6. Click `Plot Spectrum` in turn for each workspace. Make sure the workspace name is correct for the plot

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2690299/irs26176_graphite002_red.zip)

Fixes #24354 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-12-19 09:59 UTC, TTitcombe commented on qt/scientific_interfaces/Indirect/Elwin.cpp
> +void Elwin::setRunIsRunning(bool running) {
const all the things?

2018-12-19 10:00 UTC, TTitcombe commented on qt/scientific_interfaces/Indirect/Elwin.cpp
> +  auto groupWsAlg = AlgorithmManager::Instance().create("GroupWorkspaces");
what was the need for changing type to auto?

2018-12-19 10:12 UTC, TTitcombe reviewed
Works in testing as expected - names of graphs and legends reference the correct workspace, can't change the spectrum from 0 for the data provided.
However, the graphs have a window title xxxxx-1, which implies it's the first plot for that workspace. If you plot the same spectrum again, the titles change to Graph1, Graph2 etc. so the "-1" suffix is redundant, not sure if this was intentional or not.

Changes to docs are clear

Just have a couple of tiny questions about code, which may require small changes, before approving

2018-12-19 10:18 UTC, TTitcombe commented on qt/scientific_interfaces/Indirect/Elwin.cpp
> +void Elwin::setRunIsRunning(bool running) {
const bool &

2018-12-19 11:02 UTC, TTitcombe requested changes
bool to const bool where possible

2018-12-19 12:03 UTC, robertapplin commented
@TTitcombe It is intentional that you should be allowed to open multiple plots of the same spectra. I think the '-1' indicates the window number for that spectra. When a workspace has multiple spectra, the legend will display the workspace name and then '-Sp0' or '-Sp1', etc. So this will make it clear which spectra is being plotted. Because the output workspaces for the above only have one spectrum, the legend will just say the workspace name.

2018-12-20 08:48 UTC, TTitcombe approved these changes

2018-12-20 15:32 UTC, merged