Added missing tolerances for CompressEvents in AlignAndFocusPowderFromFiles
mantidproject/mantid pull request #24363
Opened 2018-12-18 23:17 UTC by marshallmcdonnell

**Description of work.**

Added the tolerances `CompressTolerance and `CompressWallClockTolerance` inputs from `AlignAndFocusPowderFromFiles` to the child algorithm calls to `CompressEvents` (int `AlignAndFocusPowderFromFiles`, not just the `AlignAndFocusPowder` algorithm) as the necessary `Tolerance` and `WallClockTolerance` arguments, respectively.

**To test:**

1) Set logging to `information` level.

2) Call `AlignAndFocusPowderFromFiles` **with at least two files to load** and `CompressTolerance` = 0. Will notice that `CompressEvents` is no longer called. 

3) Also, do with `CompressTolerance` > 0. and != 1e-5 and will see that `CompressEvents` called with the set value (not just the default).

4) Similarly,  test with the `CompressWallClockTolerance` argument set and see that its value is now set in `CompressEvents` as well.

Fixes *There is no associated issue.*

*This does not require release notes* because this only fixes internal issue in the algorithm with no new capabilities.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2018-12-19 13:20 UTC, peterfpeterson requested changes
You should add something in the release notes about this bugfix

2018-12-19 13:20 UTC, peterfpeterson commented on Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
> +            name_list = ['PreserveEvents', 'CompressTolerance', 'CompressWallClockTolerance']
This should also copy over `CompressStartTime`

2018-12-19 13:53 UTC, peterfpeterson submitted a review, later dismissed
LGTM

2018-12-20 16:10 UTC, peterfpeterson requested changes
Still need to pass `CompressStartTime` to `CompressEvents`

2018-12-20 19:43 UTC, peterfpeterson approved these changes

2018-12-21 09:33 UTC, soininen requested changes
I cannot find any unit tests for this algorithm. Would it be time to create some?

2018-12-21 12:22 UTC, soininen commented
If this needs to get merged in a timely manner, I am OK if you open an issue for tests and work on them later.

2018-12-21 13:03 UTC, marshallmcdonnell commented
@soininen Thank you! See issue #23888 for [AlignAndFocusPowder](http://docs.mantidproject.org/nightly/algorithms/AlignAndFocusPowder-v1.html) and #24386 for [AlignAndFocusPowderFromFiles](http://docs.mantidproject.org/nightly/algorithms/AlignAndFocusPowderFromFiles-v1.html).

2018-12-21 13:28 UTC, soininen approved these changes

2018-12-21 13:28 UTC, merged