Indirect Data Analysis - Undock mini plots
mantidproject/mantid pull request #24456
Opened 2019-01-10 09:07 UTC by robertapplin

**Description of work.**
This PR introduces the ability to undock the mini-plots seen on MSDFit, IqtFit, ConvFit and F(Q)Fit. This is a useful feature for the scientists using devices with small screens.

**To test:**
1. `Interfaces`->`Indirect`->`ConvFit` tab
2. Load the data below
3. Select a fit function (optional)
4. Click Run and wait (optional)
5. Double click the heading which says `Mini-plots` - the mini-plots should undock and can be resized.
6. Double click the heading again. The mini-plots should dock themselves back into their original position

The undocking feature should also work the same on MSDFit, IqtFit and F(Q)Fit.

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2744513/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2744514/irs26173_graphite002_res.zip)

Fixes #24448 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-14 11:55 UTC, mganeva reviewed
The Mini-plots can be undocked and resized as described. However, it is not possible to move the mini-plot window. To my opinion, this behavior should be changed. 

Tested on linux (ubuntu 18.04).

2019-01-14 13:08 UTC, mganeva requested changes
@robertapplin Could you add the possibility to move the mini-plot window?

2019-01-15 10:30 UTC, robertapplin commented
@mganeva This is odd, the mini-plots can already be moved when using windows. I have looked into this and it appears there is a qt bug where Dock widgets cannot be moved on Linux devices if the DockWidget is within a QLayout subclass. 
Using a QLayout object is unavoidable if we want a neat layout on our interfaces. Unfortunately I don't think there is a solution to this problem.

2019-01-16 11:05 UTC, mganeva submitted a review, later dismissed

2019-01-16 11:08 UTC, mganeva commented
@robertapplin I approve this PR since it is a bug in Qt. Do you know whether it is resolved for Qt5?
I afraid, that I will not be able to setup my Win10 VM to build mantid in a reasonable time.  I cannot test it in windows now.

2019-01-16 11:16 UTC, robertapplin commented
@mganeva I believe this is not resolved for Qt5 unfortunately

2019-01-23 10:52 UTC, mganeva commented
@robertapplin I've managed to build mantid on Win10. Indeed, one can move the undocked mini-plot on Windows, but not on linux. Qt forum says, that dock widgets are not designed to be put into QLayout.

What are your plans regarding this PR?

2019-01-23 11:06 UTC, robertapplin commented
@mganeva Regarding this PR, it is ready to be approved and merged - The resizing of the mini-plots while undocked on linux will hopefully mean it is still a useful feature (on linux)

2019-01-23 14:28 UTC, mganeva approved these changes
The code works as described. Mini-plots can be undocked and resized. Bug in Qt does not allow to move the mini-plot window on linux. Anyway, the feature is useful for small screens.

2019-01-24 13:54 UTC, merged