Indirect BayesQuasi - Prob workspace needs values for all 3 peaks
mantidproject/mantid pull request #24511
Opened 2019-01-15 15:45 UTC by robertapplin

**Description of work.**
BayesQuasi does a 3 peak fit but only gives the GUI output for 2. The parameter & fit workspaces (and the text file output) do have the 3 peak fit, but the probability workspace only has the 2 peak values. This workspace should have all three.

**To test:**
1.`Interfaces`->`Indirect`->`Bayes`->`Quasi` interface
2. Perform a fit

Check that the probability workspace contains values for all three peaks

Fixes #24510 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-15 19:18 UTC, SpencerHowells commented
@robertapplin the fit workspaces also need fit3 & diff3

2019-01-30 14:03 UTC, mantid-builder commented
@robertapplin it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2019-02-06 08:54 UTC, soininen requested changes
The additional histograms now appear in the output workspaces as promised in the description. Unit tests and release notes have been updated as well. The code looks generally good to me except for the text formatting refactoring, see the question below.

2019-02-06 08:54 UTC, soininen commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
> +        logger.information(' Erange : %f  to %f ' % (erange[0], erange[1]))
If doing this type of refactoring, why not go all the way to the recommended `format()`?

2019-02-06 14:59 UTC, soininen approved these changes

2019-02-07 15:55 UTC, merged