Get Correct Default Name for Summed Runs
mantidproject/mantid pull request #24518
Opened 2019-01-16 11:52 UTC by TTitcombe

**Description of work.**
Changed the way SANS' `AddRunsPresenter` calculates the default name for summed runs. This PR gets the correct number of leading 0s before the run number so the added file can be found by name just like any other run.

**Report to:** stephen.king@stfc.ac.uk

**To test:**
1. Interfaces -> SANS -> SANS v2
2. In the left hand tab bar, go to Sum runs
3. At the top of the page, enter comma separated run numbers e.g. 105476, 105476 and click Add
4. Notice the default name, it should have a number of leading 0s before the run number to make up to the correct instrument/facility number of digits
5. Click Sum
6. In mantid, click load and try to load using the default name WITHOUT the leading zeroes it added e.g. If I summed 105476, 105476, the default name would be LOQ00105476-add. In `Load` I would search for `LOQ105476-add`.
7. Mantid should be able to find the run
8. In sum runs, give one of the runs an instrument, e.g. 105476, LOQ105476. The default name should assume that you provided a full name so this will be used as is. In this example the default name will be LOQ105476-add.

Fixes #24491 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-24 15:56 UTC, Pasarus requested changes
A few things aren't particuarly performance minded but seem to have decent enough validation behind them. One things to note is that all python functions have an implicitly defined return None at the end of the function so if a function exits out with no return it actually is returning none therefore you needn't add it to the end of your functions but I won't make you rebuild your code for that small change. 

Besides that please attach user file and batch files.

2019-01-24 16:01 UTC, TTitcombe commented
> A few things aren't particuarly performance minded but seem to have decent enough validation behind them. One things to note is that all python functions have an implicitly defined return None at the end of the function so if a function exits out with no return it actually is returning none therefore you needn't add it to the end of your functions but I won't make you rebuild your code for that small change.
> 
> Besides that please attach user file and batch files.

Returning None explicitly is generally considered good practice, although in this case it's quite simple code so not very necessary.

Use this user file, batch file isn't required
[loq_user_file.txt](https://github.com/mantidproject/mantid/files/2792480/loq_user_file.txt)

2019-01-25 07:46 UTC, Pasarus commented
Having used the user file, mantid is unable to find the runs!
![image](https://user-images.githubusercontent.com/24723609/51732161-4573f300-2075-11e9-8f4c-5623bc187be8.png)

2019-01-30 09:49 UTC, Pasarus approved these changes
Works fine! Approved :+1:

2019-01-30 13:33 UTC, merged