Corrected import in errorreport.py
mantidproject/mantid pull request #24533
Opened 2019-01-17 13:22 UTC by Mantid-Matthew

**Description of work.**

In the python3 version of mantid the error report widget was failing to import a component and therefore not displaying when an unhandled exception was thrown. This PR updates the import statement so that the ui can be found correctly.

**To test:**
 * Run tests in python2 and python3 versions of mantid
 * In mantid ensure that usage reporting is turned on and restart mantid after doing so
 * Run the segfault algorithm and ensure error window comes up
 * In the script interpreter check that the following import statement works `from ErrorReporter.errorreport import CrashReportPage` This is checking that the import works from within mantid which is what is needed in the unhanded exception case.  

*There is no associated issue.*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-18 18:52 UTC, peterfpeterson requested changes
This would have been caught earlier if the following was the first import in `errorreport.py`
```python
from __future__ import (absolute_import, print_function)
```

2019-01-22 15:18 UTC, peterfpeterson approved these changes

2019-01-22 15:19 UTC, peterfpeterson commented
Unfortunately, you need to resolve the conflicts with the move from `qt4` to `qtpy` now.

2019-01-23 13:49 UTC, Mantid-Matthew commented
The updates to the errorreporter.py. Are no longer needed after the updates made in #24082 . The issues left over are fixed in #24566

2019-01-23 13:49 UTC, closed without merging