24437 rm line multi plot
mantidproject/mantid pull request #24567
Opened 2019-01-23 12:58 UTC by AnthonyLim23

The multiplotting now includes vertical lines, annotations and the ability to remove lines. 

**To test:**
Open the multi plotting interface (have to enable it first)
You will see some vertical lines and annotations
Click `remove line`
You should be able to remove everything excpet for the line and annotation marked as protected.

Fixes #24437. 

Does not need to be in the release notes. 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-01-29 11:40 UTC, Matthew-Andrew reviewed
This works for me in python2. When I tried the window on a python3 build however I get an error message saying `dictionary changed size during iteration`. When I try to open the window which then does not open.

2019-01-31 11:35 UTC, Mantid-Matthew commented on scripts/test/MultiPlotting/Subplot_test.py
> +
not sure whether this is a problem or not as flake8 is not run on test files but the python standard specifies a one line gap between functions in a class.

2019-01-31 18:15 UTC, Matthew-Andrew submitted a review, later dismissed
This looks good to me

2019-02-01 08:49 UTC, gvardany requested changes
I see some python files follow lower case + underscore naming scheme, some others camel case, or even camel case + underscore. I think it would be more coherent if we have only lowercase and underscores in file names of python scripts.

2019-02-06 11:24 UTC, Matthew-Andrew approved these changes

2019-02-06 13:44 UTC, gvardany reviewed
Thanks for renaming. Judging from the diff `scripts/MultiPlotting/subplot/subPlot.py` is not moved to `scripts/MultiPlotting/subplot/sub_plot.py`, but rather is deleted, and a new file is added. I think like this you are losing the history. Can you check what happened? For example, for `subplot_context` the move seems to be done properly.

2019-02-06 13:46 UTC, AnthonyLim23 commented
I think that I may have done a normal `mv` and not a `git mv`

2019-02-06 13:48 UTC, gvardany commented
That's what I thought, but actually in the diff of the last commit, it shows up correctly, but in the diff of the whole PR, it's not.

2019-02-06 16:19 UTC, AnthonyLim23 commented
huh strange. It should have a rather short history anyway.

2019-02-06 16:20 UTC, gvardany commented
Yes I think it's a detail anyhow, just to keep in mind for the future.

2019-02-06 16:21 UTC, gvardany approved these changes

2019-02-06 16:21 UTC, merged