Allow powerusers to change default editor content
mantidproject/mantid pull request #24580
Opened 2019-01-24 09:27 UTC by DTasev

**Description of work.**
This allows powerusers to change the default editor content that is loaded each time a new editor is made. Changes to the file will be reflected when a new editor is found (no need to restart Workbench)

**To test:**
- Open Workbench, this should create the `~/.mantid/default_editor_content.py` file. 
- Change the file, make a new editor (from `+`), it should now contain it

To consider: 
- I find this very useful for testing that requires me to load data, as I can have the script ready on startup without copy pasting. I want an opinion if other would find it useful.
- Is `~/.mantid/default_editor_content.py` the correct place for this file?
- If in the future the default content is changed, this PR might prevent this on already existing installation: should versioning be considered?

If this is found useful, future improvements are:
- Add options in context menu
  - Save current editor content as default, which will immediately replace the default with the current editor's content. 
  - Restore default editor content

Fixes #24565 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-11 14:03 UTC, mantid-builder commented
@DTasev it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2019-02-15 15:09 UTC, peterfpeterson requested changes
This is a good idea. I think you want to be more flexible on where the default contents live. Also, this should be added to the release notes.

2019-02-15 15:09 UTC, peterfpeterson commented on qt/python/mantidqt/widgets/codeeditor/multifileinterpreter.py
> +        self.default_content_filepath = osp.expanduser("~/.mantid/default_editor_content.py")
Shouldn't this use `mantid.kernel.ConfigService.getUserPropertiesDir()` so it is os independent?

2019-02-15 16:50 UTC, DTasev commented
I don't think this is very necessary to be added. Especially with #24500, which allows a similar functionality to be achieved, in a much nicer way

2019-02-15 16:50 UTC, closed without merging