Add uncertainties tag to NXcanSASAlgorithm
mantidproject/mantid pull request #24628
Opened 2019-01-29 09:38 UTC by TTitcombe

**Description of work.**
This PR moves file output from NXcanSAS algorithm inline with the standards as it now has an "uncertainties" tag. We currently keep the "uncertainty" tags to ensure new output is compatible with previous output.

**Report to:** stephen.king@stfc.ac.uk

**To test:**
To come

Fixes #24613 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-12 14:03 UTC, mantid-builder commented
@TTitcombe do you want to request a review on this PR?
<!-- {"problem_type": "unreviewed"} -->

2019-02-19 15:34 UTC, Matthew-Andrew approved these changes
Code looks good. I see both tags in the expected places. The file size is only marginally bigger between this and master as well.

2019-02-20 08:24 UTC, martyngigg requested changes
Is it possible to do this with a [HDF5 link](http://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/09_Groups.html) instead to save duplicate copies of the data at all?

2019-02-21 15:03 UTC, martyngigg approved these changes
I misunderstood what was happening here and thought we were adding copies of the data again but we're only adding attributes so this won't affect the size in a meaningful way even if the error data is larger.

2019-02-21 15:03 UTC, merged