Converter for powder diffraction real and reciprocal space functions
mantidproject/mantid pull request #24671
Opened 2019-01-31 17:58 UTC by AndreiSavici

**Description of work.**
Wrapper algorithms for PyStoG converter routines

**Report to:** [user name]/[nobody]. 

**To test:**
Run the scripts in the documentation for the two algorithms.

Fixes #24575 and fix #24575 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-01 21:44 UTC, marshallmcdonnell requested changes
Requested changes for the `SetSample` issues that will arise.

2019-02-04 14:41 UTC, marshallmcdonnell submitted a review, later dismissed

2019-02-04 14:43 UTC, marshallmcdonnell commented
Thanks for adding the `SetSampleMaterial` exception! I made some additional changes to both doc pages to make a note of this and to link to the `Materials` concept page for the scattering length terms.

2019-02-04 19:50 UTC, rosswhitfield requested changes
Can you add links to PyStoG from the docs so people can see or modify that code? Maybe use intersphinx to link to the exact functions used.

2019-02-04 21:52 UTC, rosswhitfield approved these changes

2019-02-05 06:14 UTC, merged