Mari definition update
mantidproject/mantid pull request #24684
Opened 2019-02-04 12:25 UTC by mducle

**Description of work.**

MARI has been upgraded with a new guide in 2017. This changes the instrument definition and parameters files to reflect the new instrument. The main changes are the position of the monitors used to calculate the energy.

The vanadium sample mass has changed but this is not very significant. Measurements indicate that the value in the parameter file can remain the same.

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #17943. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-05 15:46 UTC, OwenArnold submitted a review, later dismissed
Changes look reasonable. Builds passing. Approved.

2019-02-06 08:12 UTC, gvardany requested changes
Is the IDF generated by a script in the `mantidgeometry`? If so, has it also been updated correspondingly?

2019-02-06 08:12 UTC, gvardany commented on instrument/MARI_Definition.xml
> +                        last-modified="2016-11-02 15:50:00">
Is this not supposed to be the date of last modification of the file?
Also I think `valid-to` is optional here.

2019-02-06 08:12 UTC, gvardany commented on instrument/MARI_Definition_19900101_20160911.xml
> + name="MARI" valid-from   ="1900-01-31 23:59:59"
And `valid-from` must be optional here.

2019-02-06 08:12 UTC, gvardany commented on instrument/MARI_Parameters_19900101_20160911.xml
> +<parameter-file instrument = "MARI" valid-from = "2013-06-12T00:00:00">
Also I think it read nicer like this rather than 23:59:59 of the previous day.

2019-02-06 09:16 UTC, mducle commented
> Is the IDF generated by a script in the `mantidgeometry`? If so, has it also been updated correspondingly?

I don't know how the IDF was originally generated... but it hasn't been updated. 

I would really like the changes to the monitor positions put into Mantid ASAP though because it affects the reduction and we have users coming this week.

2019-02-06 09:57 UTC, mducle commented
IDFs seems to need both date from and date to fields else they fail the `APITest_ExperimentInfoTest`

2019-02-06 09:59 UTC, gvardany commented
Hmm, this does not match with the documentation, but anyhow, seems I was wrong that they are optional.

2019-02-07 18:30 UTC, gvardany approved these changes

2019-02-08 08:11 UTC, merged