Add embedded find/replace dialog to editor widget
mantidproject/mantid pull request #24731
Opened 2019-02-08 16:18 UTC by DTasev

This PR is waiting on #24700 to reuse some of the memory leaking common functionality.

**Description of work.**
Adds embedded find/replace dialog into the editor widget. To trigger press `Ctrl+F`.

Also fixes the editor widgets (and children) being leaked.

**To test:**
Press CTRL+F in the editor. Do a bunch of search/replaces. Try to check if all the options work correctly. Try some unicode symbols: `áéóúí`.

Fixes #24531 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-11 08:35 UTC, DTasev commented
Note to self: AssertionError: Todo after #24700 has been merged, to reuse the helper functions.

2019-02-12 11:11 UTC, martyngigg requested changes
This is really nice. I much prefer this to the dialog box from MantidPlot. It looks like it works entirely as I would expect :+1:

As we discussed offline there are a few cosmetic things to look into:
* [x] we need an item in the menu so that users know the shortcut
* [x] can we have next/previous types buttons instead of search backwards?
* [x] can we shrink the borders as whole bar seems quite visually imposing
* [x] replace/replace all buttons moved to bottom next to replace box
* [x] is it possible to prefil the search box if I have a word hightlighted? PyCharm does this and it saves the copy step

2019-02-13 14:09 UTC, DTasev commented
I have pushed up changes to address the comments. Note that I've updated the test instructions in the main post, most notably enter/shift+enter searches next/previous, escape closes the find/replace. The layout is a lot tighter, but I can't seem to find a way to stop the spacers from expanding when the window is made very wide.

2019-02-13 14:19 UTC, DTasev commented
I figured it out - replaced the horizontal spacer with a disabled flat button that _should_ be invisible. (it's above Replace All)
![image](https://user-images.githubusercontent.com/9135965/52717989-4d4ef500-2f9a-11e9-9736-83c0b92aad72.png)

There is still empty space there, above Replace All, but I am not sure what makes sense to go there, we don't have enough options for buttons.

2019-02-14 11:10 UTC, martyngigg commented
@DTasev It looks like MultiFileInterpreter test is failing

2019-02-14 11:13 UTC, DTasev commented
It should be fixed now

2019-02-14 13:54 UTC, martyngigg requested changes
The functionality seems to work for me with the exception of "match case", for example typing "IMPORT" into the search still matches "import".

I also have an issue on Ubuntu with words being cut off:
![screenshot from 2019-02-14 13-54-10](https://user-images.githubusercontent.com/733773/52790857-80a78780-305f-11e9-902d-b238e967e032.png)

I guess this is a theme problem with fixed button sizes?

2019-02-14 13:58 UTC, DTasev commented
> The functionality seems to work for me with the exception of "match case", for example typing "IMPORT" into the search still matches "import".

That might be a case of the combo box instantly replacing "IMPORT" back with "import" as the lower-case version was in the history and then the search is performed with lower-case again. This is the default behaviour of QComboBox, and it matches MantidPlot which is why I haven't changed it.

> I also have an issue on Ubuntu with words being cut off:
> ![screenshot from 2019-02-14 13-54-10](https://user-images.githubusercontent.com/733773/52790857-80a78780-305f-11e9-902d-b238e967e032.png)
> 
> I guess this is a theme problem with fixed button sizes?

Yeah, I will make the maximum widths more relaxed, and that should fix it

2019-02-14 15:01 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/plots/helperfunctionsTest.py
> -    @add_md_workspace_with_data()
This just removes a duplicate test.

2019-02-14 15:06 UTC, martyngigg submitted a review, later dismissed

2019-02-14 15:07 UTC, martyngigg commented
It looks like we still have some failing tests.

2019-02-15 08:14 UTC, DTasev commented
Tests are now passing!

2019-02-15 08:29 UTC, martyngigg approved these changes

2019-02-15 09:27 UTC, merged