basis vanadium wavelength ranges
mantidproject/mantid pull request #24810
Opened 2019-02-18 20:18 UTC by jmborr

**Description of work.**
- [x] introduced default wavelength ranges when integrating the vanadium signal
- [x] dictionary for new silicon 333 analyzers

**To test:**

Fixes #24809

This does not require release notes  because changes in the backend are not exposed to the user

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-19 21:37 UTC, sullivanbt requested changes
I think you need to add the new `parameter_file` and `instrument_definition_file` - `BASIS_silicon_333_Parameters.xml` and `BASIS_Definition_Si333.xml`.  Si333 also uses the Si111 mask - would it be better to create a separate mask?

2019-02-19 21:59 UTC, jmborr commented
@sullivanbt 
- I will add BASIS_silicon_333_Parameters.xml now
- IDF `BASIS_Definition.xml` works for all analyzers
- The mask for silicon 333 is the same as that for silicon 111 because it uses the same silicon crystals, but I will create a silicon 333 mask file which will be a soft link to the silicon 111 mask.

2019-02-20 13:24 UTC, sullivanbt approved these changes

2019-02-20 15:11 UTC, merged

2019-02-20 15:25 UTC, jmborr commented
@sullivanbt @peterfpeterson thanks!  👯