Pack six.py from pip on macOS
mantidproject/mantid pull request #24831
Opened 2019-02-20 08:51 UTC by gvardany

**Description of work.**

Packs `six.py` with the macOS bundle. The one shipped from the system has a too old version, which causes some import to fail, and MantidPlot fail to start up.

**Report to:** [ILL]/[Bjorn]. 

**To test:**

Download the .dmg from the mac build artefacts. Install on a clean (i.e. that does not have the build time dependencies for mantid) macOS machine. Make sure MantidPlot starts up normally.

Fixes #24816 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-20 09:57 UTC, martyngigg commented
Some builders have Homebrew Python configured and thus the ['pip_site_packages'](https://github.com/mantidproject/mantid/blob/master/MantidPlot/make_package.rb.in#L350) is wrong. For Homebrew it is `/usr/local/lib/python2.7/site-packages`. Can we update that so we check which exists and is being used?

We also have a slight maintenance headache at the moment as we have a near copy of this script at https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/make_package.rb.in to package the workbench so I think we'll need to make those changes there too. The mac packaging is something I would like to sort out properly this maintenance period.

2019-02-20 10:03 UTC, gvardany commented
I see, it would be great of course if we could agree on brew python vs system python, that could reduce some of the headache. Regarding the workbench, yes it also does not start, see issue #24817 .
So some stuff might need to be packed there as well.

2019-02-21 15:10 UTC, martyngigg requested changes
I've built this locally on a mac not using homebrew Python and `six` is packaged correctly in MantidPlot. We just need to update [workbench/make_package.rb.in](https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/make_package.rb.in#L292) too so it is packaged with the workbench on macOS.

2019-02-22 08:08 UTC, martyngigg approved these changes
This looks good. It is packaged into both the MantidPlot and Workbench bundles.

2019-02-22 10:45 UTC, martyngigg commented
@mantidproject/gatekeepers Could we get this merged so I can check it with #24832?

2019-02-22 11:47 UTC, merged

2019-02-22 11:56 UTC, martyngigg commented
Thanks!