Load current run in muon GUIs
mantidproject/mantid pull request #24852
Opened 2019-02-21 13:07 UTC by AnthonyLim23

The load current run option did not work in Muon Analysis for the CHRONUS instrument. This PR fixes that, in addition it adds the CHRONUS and ARGUS instruments to the new muon GUI.

**To test:**
- Go to https://github.com/mantidproject/mantid/blob/master/Framework/Properties/Mantid.properties.template#L23 and add `Muon/Muon_Analysis_2.py` to the list of interfaces
- Compile the code
- Open Muon Analysis and change the instrument to `CHRONUS`
- Click load current run and some data will be loaded
- Close Muon Analysis

- Open Muon Analysis 2
- Change the instrument to `CHRONUS` and click load current run
- In the ADS some new data will be added
- Change the instrument to `ARGUS` and click load current run
- In the ADS some new data will be added

Fixes #24837. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-25 13:08 UTC, mantid-roman requested changes
I have an error when I switch to ARGUS:
```
AttributeError: Attempting to set object of type <type 'NoneType'>, must be a Mantid Workspace type
```

2019-02-25 13:11 UTC, AnthonyLim23 commented
for which GUI? And did you have some data loaded before you switched (if so which)?

2019-02-25 13:12 UTC, mantid-roman commented
If I start with ARGUS and then switch to CHRONUS there is a different error:
```
IndexError: Too many runs (304) must be <100
```

2019-02-28 11:23 UTC, mantid-roman approved these changes

2019-02-28 11:40 UTC, merged