ILL powder few fixes
mantidproject/mantid pull request #24867
Opened 2019-02-22 10:36 UTC by gvardany

**Description of work.**

Fixes a couple of minor problems with ILL powder loader and reducer.

**Report to:** [ILL]/[Hansen].

**To test:**

Soon.

Fixes #24851 . 

*This does not require release notes since it is not yet in production use for D20*.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-01 14:55 UTC, soininen requested changes
Looks good to me. Just a few tiny issues below.

2019-03-01 14:55 UTC, soininen commented on Framework/DataHandling/test/LoadILLDiffractionTest.h
> +    const auto &indexOfFirstDet = detectorInfo.indexOf(1);
The `&` is unnecessary as `indexOf()` returns `size_t`.

2019-03-01 14:55 UTC, soininen commented on Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
> +      0.};           ///< the 2theta offset for D20 to account for dead pixels
The doxygen comment could be on the preceding line to get this formatted correctly.

2019-03-01 14:55 UTC, soininen commented on Framework/API/inc/MantidAPI/LogManager.h
> +  void addLogData(std::unique_ptr<Kernel::Property> p, bool overwrite = false) {
:+1:

2019-03-01 14:55 UTC, soininen commented on Framework/DataHandling/test/LoadILLDiffractionTest.h
> +    TS_ASSERT(position.X() < 0.);
`TS_ASSERT_LESS_THAN`?

2019-03-01 14:55 UTC, soininen commented on docs/source/release/v3.14.0/diffraction.rst
> +- :ref:`LoadILLDiffraction <algm-LoadILLDiffraction>` will now correctly resolve for the scan type and drive the detector to the offset corrected 2theta0 for D20 detector scans.
`:math:'2theta_0'`?

2019-03-04 11:02 UTC, soininen approved these changes

2019-03-04 14:49 UTC, NickDraper commented
Conflicts - A Haiku

```
To resolve conflicts
developer must merge
in the master branch
```

2019-03-05 06:46 UTC, soininen commented
The failed test seems unrelated.

2019-03-05 09:01 UTC, merged