AlignAndFocusPowderFromFiles absorption test
mantidproject/mantid pull request #24894
Opened 2019-02-26 20:09 UTC by peterfpeterson

This adds a test to verify that the absorption workspace, when supplied, is applied correctly.

**To test:**

Look over the new test and see that the builds pass.

*There is no associated issue.*

*This does not require release notes* because it is adding a system test to #24821.

**Do not merge before #24821.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-02-27 17:04 UTC, marshallmcdonnell requested changes
Overall, great addition for system tests! Few comments above need to be addressed.

2019-02-27 17:04 UTC, marshallmcdonnell commented on Testing/SystemTests/tests/analysis/AlignAndFocusPowderFromFilesTest.py
> +import timing
I got `no module found` for `timing`. Add as dependency or switch to different module?

2019-02-27 17:04 UTC, marshallmcdonnell commented on Testing/SystemTests/tests/analysis/AlignAndFocusPowderFromFilesTest.py
> +        xaxis = np.arange(0., float(num_wl_bins + 1)) * (2.20 - 0.05) / (num_wl_bins) + 0.05
Just to check, 2.20 is WavelengthMax? Should that be a variable for clarity?

2019-02-27 19:34 UTC, marshallmcdonnell approved these changes

2019-02-28 11:45 UTC, martyngigg commented
I'm just going to check that the new tests pass on Windows/macOS before saying yes.

2019-02-28 12:14 UTC, martyngigg commented
Tests pass on macOS.

2019-02-28 12:50 UTC, marshallmcdonnell commented
FYI, I test on Ubuntu 18.04 for the review

2019-02-28 13:00 UTC, martyngigg commented
Thanks for confirming @marshallmcdonnell. We've had a few tests go through recently that have broken on Windows/macOS so I just wanted to be doubly sure before proceeding, especially as this had a test that claimed it used to only work on RHEL 6!

2019-02-28 13:26 UTC, peterfpeterson commented
The `_skip_test` function was unused and deleted in this PR. It was a copy/paste mistake from `SNSPowderRedux` which this was based on.

2019-02-28 15:25 UTC, SamJenkins1 commented
Test seems to fail on windows

2019-02-28 15:35 UTC, martyngigg commented
@SamJenkins1 Can you provide some more information? Console output?

2019-03-05 10:19 UTC, SamJenkins1 commented
It appears it was running out of memory, martin thinks this was due to being on debug so this should be fine.

2019-03-05 10:54 UTC, merged