Indirect Diffraction - Manual Grouping Bug
mantidproject/mantid pull request #24982
Opened 2019-03-04 15:15 UTC by robertapplin

**Description of work.**
This PR fixes a bug where the wrong component is passed to the CreateGroupingWorkspace which means the relevant detector IDs couldn't be retrieved from the OSIRIS IPF when using manual grouping on Indirect Diffraction.

It also adds a bit of documentation to the Sum Files option in Indirect Data Reduction

**To test:**
1.`Interfaces`->`Indirect`->`Diffraction`
2. Enter the run numbers 137793-137796
3. Tick manual grouping and enter the number of groups to be 1.
4. Click `Run` and there should be no error.

Fixes #24974

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-06 14:14 UTC, SpencerHowells commented
@robertapplin Replacing with a fixed 0.1 may not be a good idea. It should depend on the y-values. Perhaps it should be something like 0.01*y_max.

2019-03-12 08:59 UTC, LowriJenkins requested changes
Other than a small check here it seems all good

2019-03-12 08:59 UTC, SamJenkins1 commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
> +    y_minimum = min(filter(lambda x: x > 0, workspace.readY(0)))
It doesn't make a huge difference but I personally find that a list comprehension would be more readable here. `y_minimum = min([x for x in workspace.readY(0) if x>0])`. up to you whether or not you want to here, there execution speed is similar enough to not matter, and the readability is a matter of opinion on this one. just wanted to check you were aware that list comprehension was an option

2019-03-12 08:59 UTC, SamJenkins1 commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
> +        y_spec_min = min(filter(lambda x: x > 0, workspace.readY(idx)))
same thing to consider as above

2019-03-12 09:14 UTC, LowriJenkins approved these changes

2019-03-13 07:45 UTC, soininen requested changes
`ISISIndirectDiffractionReduction` does not seem to have unit tests. Would it make sense to add some?

2019-03-13 10:28 UTC, soininen approved these changes

2019-03-14 06:48 UTC, merged