Run system test clean up functions when an exception is raised
mantidproject/mantid pull request #24990
Opened 2019-03-05 09:50 UTC by martyngigg

**Description of work.**

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-05 11:39 UTC, LowriJenkins submitted a review, later dismissed
Changes function as stated, code changes look good.

2019-03-05 17:31 UTC, peterfpeterson requested changes
You need a small change in the [SNAPRedux](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/SNAPRedux.py#L27-L43) system test. The last bit of loop should be:
```python
for direc in ['d_spacing', 'gsas', 'fullprof', 'nexus']:
    direc = os.path.join(savedir, direc)
    if os.path.exists(direc):
        if os.listdir(direc) == []:
            os.rmdir(direc)
```
This shouldn't be needed as none of these tests are run. They are skipped because of missing required files.

2019-03-05 21:01 UTC, martyngigg commented
Thanks, Pete!

2019-03-05 21:42 UTC, peterfpeterson submitted a review, later dismissed

2019-03-06 15:17 UTC, peterfpeterson commented
`Testing/SystemTests/tests/analysis/ISIS_WISHDiffractionFocussing.py` needs to have `_focused_workspace = list()` added in line 15, and the cleanup should be:
```python
    def cleanup(self):
        for ws in self._focused_workspaces:
            path = config.getString("defaultsave.directory")
            for filename in [ws + ".dat", ws + ".nxs"]:
                filename = os.path.join(path, filename)
                if os.path.exists(filename):
                    os.remove(filename)
```
It comes from the test failing outright and never creating that attribute.

2019-03-06 15:44 UTC, martyngigg commented
There are quite a few cleanup functions to fix so I'm dropping this back to 4.1

2019-03-21 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-04-09 14:03 UTC, mantid-builder commented
@martyngigg the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-04-23 14:03 UTC, mantid-builder commented
@martyngigg have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-04-29 15:50 UTC, martyngigg commented
I'm closing this for now to revisit it later.

2019-04-29 15:50 UTC, closed without merging