24785 ignore nexus instrument xml
mantidproject/mantid pull request #25077
Opened 2019-03-07 21:28 UTC by ricleal

**Description of work.**

Issue #24785

Create a `LoadNexusInstrumentXML` property in the `LoadEventNexus`.
If `LoadNexusInstrumentXML = True` (default) reads the nexus embedded instrument XML.
If `LoadNexusInstrumentXML = False` reads the local IDF.

**To test:**
Tests should pass.
However one can read an event Nexus file and click the option `LoadNexusInstrumentXML` and see if the local IDF was read. In Debug log level, after the Logs were read, this is clear.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-07 22:22 UTC, ricleal commented
@VickieLynch I just did the ignore NeXus instrument XML. I hope you haven't started it yet...

2019-03-08 15:53 UTC, VickieLynch submitted a review, later dismissed
This did work for the TOPAZ IDF which does not have a bank that is only for testing. I could add this bank to the IDF and see the data. This will need to be put in release notes when 4.1 is available.

2019-03-11 08:33 UTC, martyngigg requested changes
@ricleal The release notes for 4.1 should now be available. Could you add an entry about this?

2019-03-11 14:16 UTC, ricleal commented
@martyngigg Done!

2019-03-11 14:47 UTC, martyngigg commented
Thanks!

2019-03-11 15:24 UTC, martyngigg approved these changes

2019-03-11 16:20 UTC, martyngigg commented
Merging as the only change was a release note update after Vickie's original review.

2019-03-11 16:20 UTC, merged