Fixes to Kernel::Material
mantidproject/mantid pull request #25091
Opened 2019-03-08 20:08 UTC by peterfpeterson

It was discovered that `Material` and `NeutronAtom` weren't giving the same results when using a single atom. Also, comparing values for the null scatterer TiZr pointed out that not all the calculations were being done according to Sears. This was fixed, lots of consistency tests were added, and references to the exact equations implemented from literature are in the code. This way, if you find an error, you can get published!

**To test:**

Look that the tests are reasonable and that the code implements the equations they suggest they are.

Fixes #25047.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-11 12:29 UTC, soininen requested changes
A set of very welcome fixes to `Material` and the cross-section computations. I did not spot any obvious mistakes but below are a few comments about code quality and the like.

2019-03-11 12:29 UTC, soininen commented on Framework/Kernel/test/MaterialTest.h
> +    std::cout << "--->>> " << name << ": " << atom << std::endl;
Why the output in this and other tests below?

2019-03-11 12:29 UTC, soininen commented on Framework/Kernel/test/MaterialTest.h
> +    Material material(name, atom, 0.072); // TODO mass density is 7.90 g/cm3
What does the `TODO` mean?

2019-03-11 14:52 UTC, peterfpeterson commented on Framework/Kernel/src/Material.cpp
> +    length = std::sqrt(real * real + imag * imag);
I didn't know that was a thing

2019-03-11 14:55 UTC, peterfpeterson commented on Framework/Kernel/src/Material.cpp
> +    return 0.;
I don't recall why it was chosen to return zero for these cases. I think changing the behavior warrants a separate discussion in a bigger group.

2019-03-11 15:25 UTC, peterfpeterson commented on Framework/Kernel/src/Material.cpp
> +  return scatteringLength(cohScatterLengthReal(), cohScatterLengthImg());
`cohScatterLength` is in the table, where `cohScatterLengthSquared` isn't. The question is whether it is better to have `lengthSquared = b b*` or not. The values are different in the first place past the decimal.

2019-03-11 15:47 UTC, soininen commented on Framework/Kernel/src/Material.cpp
> +  return scatteringLength(cohScatterLengthReal(), cohScatterLengthImg());
I see. Lets keep it this way then.

2019-03-11 22:08 UTC, AndreiSavici approved these changes

2019-03-12 07:14 UTC, soininen approved these changes

2019-03-12 08:29 UTC, merged