Allow ShapeInfo to understand Hollow Cylinder Geometry
mantidproject/mantid pull request #25181
Opened 2019-03-14 17:01 UTC by aybamidele

**Description of work.**

**Report to:** [user name]/[nobody]. 

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-14 18:46 UTC, peterfpeterson commented
Is this intending on adding the explicit calculation to [`Rasterize`](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Rasterize.cpp) as well?

2019-03-19 15:40 UTC, aybamidele commented
@peterfpeterson Yes, it is, but not in this PR.

2019-03-19 15:44 UTC, martyngigg requested changes
This looks good and is a good first step to having full annular ring support. :+1: 

One minor thing that I think is worth adding is that in the other `set` functions such as `setCone` etc I think we should extend their unit tests to confirm that the inner and outer radius is set to `0` when they are called.

2019-03-19 15:50 UTC, aybamidele commented
Is it okay to do this in the second branch?

2019-03-19 15:53 UTC, martyngigg commented
Can we do it here as the work to define the functionality is here?

2019-03-20 10:25 UTC, martyngigg submitted a review, later dismissed
Changes look good now.

The build failure is the current problem with the RHEL 7 build and doctest failure and is unrelated to these changes.

2019-03-20 10:28 UTC, aybamidele commented
Yes, Dimitar just let me know. Thank you.

2019-03-20 14:33 UTC, DanNixon requested changes
A couple of small style comments.

2019-03-20 14:33 UTC, DanNixon commented on Framework/Geometry/test/ShapeInfoTest.h
> +    V3D centreBottomBase(0, 0, 0);
Could these test parameters be `constexpr`?

2019-03-20 14:33 UTC, DanNixon commented on Framework/Geometry/test/ShapeInfoTest.h
> +    double theight;
Could you use some more verbose variable names here?

e.g. just expanding `t` to `test`.

2019-03-25 09:04 UTC, DanNixon approved these changes

2019-03-25 11:17 UTC, merged