Indirect - Prevent loading of workspace with one data point on FQFit
mantidproject/mantid pull request #25228
Opened 2019-03-18 14:26 UTC by robertapplin

**Description of work.**
This PR prevents the user from loading a workspace with one data point. This prevents an error when clicking Run.

**To test:**
Repeat the steps seen in #25224 .

Fixes #25224

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-18 15:33 UTC, TTitcombe requested changes
When I go onto F(Q) Fit, I see the dialog box letting me know the workspace only has one data point, but afterwards the workspace at the top is still populated with "workspacename_Result". This signals to me that it has been loaded? Is it possible to depopulate this box to make it clearer there was an error loading?

2019-03-18 16:30 UTC, robertapplin commented
I see your point, however I don't think this would be Trivial to do. If the user attempts to click Run there is a message stating that a workspace hasn't been loaded, and there is no workspace plotted in the miniplots - so these indications might help the user (for now). Maybe this could be a change made after this release?

2019-03-19 08:15 UTC, TTitcombe commented
If it's not an easy change then I agree it's something that should be looked at next release

2019-03-19 08:15 UTC, TTitcombe submitted a review, later dismissed

2019-03-19 08:16 UTC, TTitcombe commented
This PR fixes the bug :+1: Docs updated appropriately, small efficient code changes.

2019-03-19 11:55 UTC, AnthonyLim23 commented
@TTitcombe could you have another look at this?

2019-03-19 13:23 UTC, TTitcombe approved these changes
Good fix to the bug of trying to plot workspaces with 1 data point

2019-03-19 15:26 UTC, merged