Update Windows build instructions for cmake 3.14
mantidproject/mantid pull request #25231
Opened 2019-03-18 15:05 UTC by martyngigg

**Description of work.**

Updates the instructions for building on Windows with CMake 3.14. The platform is no longer a part of the generator name and must be selected separately.

**To test:**

Review the text.

*There is no associated issue.*

*This does not require release notes* because **it is a developer docs change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-20 15:04 UTC, dtasev submitted a review, later dismissed
Looks good, instructions work, and the CMake project from 3.14 seems to be working & compiling well.

@martyngigg People upgrading from <3.14 will get an error about `googletest` being built with a different compiler (or something similar). Do you think we should add something about that in the notes? The fix for that is deleting `build/googletest-*`

Note: that happens only if you `Delete Cache` before regenerating the build

2019-03-21 09:44 UTC, DanNixon requested changes
Small typo.

2019-03-21 09:44 UTC, DanNixon commented on dev-docs/source/BuildingWithCMake.rst
> +  * Windows developers should choose ``Visual Studio 15 2017`` and in the _Optional platform for generator\_ box select ``x64``. If you see errors related the HDF5 then you have most likely selected
```suggestion
  * Windows developers should choose ``Visual Studio 15 2017`` and in the _Optional platform for generator\_ box select ``x64``. If you see errors related to HDF5 then you have most likely selected the wrong platform. 
```

2019-03-21 10:16 UTC, martyngigg commented
Thanks, Dan!

2019-03-21 10:42 UTC, DanNixon approved these changes

2019-03-21 12:22 UTC, merged