Clang-tidy modernize-loop-convert MantidPlot
mantidproject/mantid pull request #25273
Opened 2019-03-20 11:12 UTC by TTitcombe

**Description of work.**
This PR runs clang-tidy on MantidPlot and docs (+ one qt file has snuck in here) to use range-based for loops where possible

**To test:**
1. Code inspection
2. Tests pass

Note that if you search mantidplot code for `for \(.*\.begin\(\);.*\.end\(\);.*\)` (regex for an old for loop) you will find some instances which remain. There are some instances where clang-tidy has decided they should not be / it doesn't know how to change the loops to range-based. These stragglers should be manually assessed at a later date

Fixes partially #22183 

*This does not require release notes* because **internal code change**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-20 14:15 UTC, dtasev requested changes
Some comments about adding `const` in a bunch of places, and a few that can be improved further

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/Mantid/MantidUI.cpp
>    std::vector<std::string> sv;
`const auto& sv = Mantid::API::AlgorithmFactory::Instance().getKeys();` and remove the next line. Also `sv` can be renamed to `algorithmKeys` or `algorithmNames` I think

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/Mantid/MantidUI.cpp
>    QStringList sl;
Can this be reserved after `sv` is retrieved to avoid additional memory allocations?

`sl.reserve(sv.size());`

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/Mantid/MantidUI.cpp
> +  for (auto &i : curveSpecList) {
Change `auto &i` to `const auto &curveSpec`

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/MdPlottingCmapsProvider.cpp
> +  for (auto &it : info) {
Change to `const auto &fileInfo`

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/MdPlottingCmapsProvider.cpp
> +  for (auto &it : colorMapNamesSliceViewer) {
change to `const auto &colorMapName`

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/Table.cpp
> +    for (auto lines : sections) {
```suggestion
    for (const auto &lines : sections) {
```

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/Table.cpp
> +    for (auto &dataLine : dataLines) {
```suggestion
    for (const auto &dataLine : dataLines) {
```

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/TableStatistics.cpp
> +    for (auto lines : sections) {
```suggestion
    for (const auto &lines : sections) {
```

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/lib/3rdparty/qtcolorpicker/src/qtcolorpicker.cpp
> +  for (auto item : items) {
```suggestion
  for (auto *item : items) {
```

2019-03-20 14:15 UTC, DTasev commented on MantidPlot/src/lib/3rdparty/qtcolorpicker/src/qtcolorpicker.cpp
> +  for (auto item : items) {
```suggestion
  for (auto *item : items) {
```

2019-03-21 11:20 UTC, dtasev requested changes
A few more variables names to fix and this will be good to go

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (const auto &i : MATRIX)
Can `i` be renamed to `mat`?

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (const auto &i : EXCEL)
`i` should be renamed, but I'm not sure what to, maybe `document`?

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (const auto &i : FUNCTION)
rename `i` to `func`, `fun`, or `function

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (auto &i : MATRIX)
`i` to `mat`

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (auto &i : GRAPH)
`i` to `g` to match the other graph for loop

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (auto &i : EXCEL)
`i` to `document`, still not sure about the name

2019-03-21 11:20 UTC, DTasev commented on MantidPlot/src/origin/OPJFile.cpp
> +  for (auto &i : SPREADSHEET)
`i` to `spreadsheet` or `spread` to match name above

2019-03-21 11:20 UTC, DTasev commented on qt/widgets/common/src/AlgorithmHistoryWindow.cpp
> +  for (const auto &entrie : entries) {
`entrie` to `entry`

2019-03-21 11:20 UTC, DTasev commented on qt/widgets/common/src/AlgorithmHistoryWindow.cpp
> +  for (int unrollIndicie : unrollIndicies) {
`unrollIndicie` to `index`

2019-03-21 13:01 UTC, dtasev submitted a review, later dismissed
Looks good! 👍

2019-03-22 08:16 UTC, DanNixon requested changes

2019-03-22 08:16 UTC, DanNixon commented on MantidPlot/src/AxesDialog.cpp
> +  for (auto &axisItr : m_Axis_list) {
Can we remove "Itr" from these variable names given that it is no longer an iterator.

2019-03-22 08:16 UTC, DanNixon commented on MantidPlot/src/Mantid/FirstTimeSetup.cpp
> +  for (const auto &it : faclist) {
```suggestion
  for (const auto &facilityName : faclist) {
```

2019-03-22 08:53 UTC, DanNixon approved these changes

2019-03-26 10:38 UTC, TTitcombe commented
Closing as we are no longer actively developing MantidPlot code

2019-03-26 10:38 UTC, closed without merging

2019-03-26 10:43 UTC, DTasev commented
This PR is fully ready and reviewed though, I still think it should be merged, as the MantidPlot codebase will be there for a while, and this improves it a bit

2019-03-26 11:55 UTC, TTitcombe commented
> This PR is fully ready and reviewed though, I still think it should be merged, as the MantidPlot codebase will be there for a while, and this improves it a bit

@martyngigg

2019-03-26 11:57 UTC, martyngigg commented
Sorry that I didn't catch this before it was reviewed but I think any changes to those parts of the code do introduce risk and that part of the codebase is heavily untested so I'd rather not risk it and have to explain to users why we are tidying up code that we are going to throw away.