Fix cppcheck 1.87 warnings in PythonInterface
mantidproject/mantid pull request #25352
Opened 2019-03-25 09:21 UTC by soininen

Fix some `cppcheck` 1.87 warnings in the PythonInterface module. Some `unmatchedExpression` and `unreadVariable` warnings in the Python bindings will need to be dealt with later when `cppcheck` gets updated on the build servers.

**To test:**

Code review. Check that no `scope` declarations were accidentally removed from the Python bindings.

Progress towards #22912. 

*This does not require release notes* because this is an internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-01 14:39 UTC, TTitcombe submitted a review, later dismissed
Code changes look good

2019-04-01 15:13 UTC, DanNixon requested changes

2019-04-01 15:13 UTC, DanNixon commented on Framework/PythonInterface/mantid/api/src/Exports/ITableWorkspace.cpp
> +  for (int colIndex = 0; colIndex < numCols; colIndex++) {
I'd prefer keeping "column" un-abbreviated for the sake of clarity.

2019-04-01 15:13 UTC, DanNixon commented on Framework/PythonInterface/mantid/kernel/src/Exports/Material.cpp
> +  return std::accumulate(formula.cbegin(), formula.cend(), 0.,
:+1:

2019-04-08 08:09 UTC, DanNixon approved these changes

2019-04-08 16:14 UTC, merged