Formatting CMake files
mantidproject/mantid pull request #25354
Opened 2019-03-25 09:54 UTC by alicerussell1

**Description of work.**
This PR formats the CMake files to make them easier to read. This has been done using [cmake_format](https://github.com/cheshirekow/cmake_format). This is for the files in the framework from algorithms to indexing.

**To test:**
Read through and check it is easy to read and that no changes have been made that will effect the functionality of the file.

Fixes #25003 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-25 15:07 UTC, LowriJenkins requested changes
Mostly looks fine, a few comments that could do with removing that I've put suggestions up for, and one section that you should probably check about with martyn since it is commented out but its not just a file.

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/Geometry/CMakeLists.txt
> +#
```suggestion
```

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/HistogramData/CMakeLists.txt
> +#
```suggestion
```

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/HistogramData/CMakeLists.txt
> +#
```suggestion
```

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/ICat/CMakeLists.txt
> +#
```suggestion
```

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/ICat/CMakeLists.txt
> +#
```suggestion
```

2019-03-25 15:07 UTC, SamJenkins1 commented on Framework/Indexing/CMakeLists.txt
> +#
```suggestion
```

2019-03-27 15:07 UTC, alicerussell1 commented on Framework/GPUAlgorithms/CMakeLists.txt
> +# endforeach(f)
This file was removed by someone else in a different PR so this is no longer an issue

2019-03-27 16:31 UTC, LowriJenkins approved these changes

2019-03-28 06:48 UTC, merged