Formatted CMake files in framework Kernel to RemoteJobManagers
mantidproject/mantid pull request #25362
Opened 2019-03-25 11:55 UTC by alicerussell1

**Description of work.**
This PR formats the CMake files to make them easier to read. This has been done using [cmake_format](https://github.com/cheshirekow/cmake_format). This is for the files in the framework from Kernel to RemoteJobManagers.

**To test:**
Read through and check it is easy to read and that no changes have been made that will effect the functionality of the file.

Fixes #25003 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-03-27 14:14 UTC, LowriJenkins requested changes
a few changes here, but otherwise seems good

2019-03-27 14:38 UTC, LowriJenkins submitted a review, later dismissed

2019-03-27 14:40 UTC, LowriJenkins approved these changes

2019-03-27 19:55 UTC, merged

2019-03-28 08:26 UTC, martyngigg commented
@alicerussell1 It looks like we have some merge conflicts here too.