Remove GetEiMonDet versions 1 and 2
mantidproject/mantid pull request #25434
Opened 2019-03-28 15:34 UTC by soininen

Remove the deprecated versions 1 and 2 of `GetEiMonDet`.

**To test:**

Check no traces of versions 1 and 2 remain.

Fixes #25433. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-01 15:46 UTC, LowriJenkins requested changes
looks like all references to versions 1 and 2 are gone... wouldn't it be better to get rid of the version numbers now that there's only 1 version again, instead of using 3 despite there only being 1 version?

if not then I'll approve this, but I thought it bared mentioning.

2019-04-05 14:33 UTC, soininen commented
Like in software versioning I do not think it makes sense to revert the version number back to 1. This would be problematic for old data where the algorithm history would still show version 1.

2019-04-08 21:34 UTC, AndreiSavici commented
@SamJenkins1 We have several algorithms in Mantid that have only version 2 (at least the documentation is only for version 2): `LoadILLTOF-v2.rst`, `LoadISISNexus-v2.rst`, `FindEPP-v2.rst`, ...

2019-04-09 07:12 UTC, LowriJenkins approved these changes

2019-04-09 14:07 UTC, merged