ISISReflectometry GUI: Plotting
mantidproject/mantid pull request #25458
Opened 2019-04-02 09:56 UTC by Pasarus

**Description of work.**
The new restructure of the GUI does not have plotting functionality. As this is a major part of the Porting of the GUI to Workbench, I have added it ahead of porting it to workbench.

**To test:**
### First, set up some processed rows
- Open the `ISIS Reflectometry` interface, select `INTER`.
- From the Reflectometry menu, select Import table and choose `INTER_NR_test2.tbl` from the ISIS sample data.
- Click `Process` and when finished expand all groups. All rows should now be green.

### Test the first button ("plot runs")
- Select a single row within a group and then click plot runs. You get a single curve:
<img src="https://user-images.githubusercontent.com/12895056/55162331-82d12b80-515f-11e9-8dd0-3a49809f1bf9.png" width=200>

- Select two rows and click plot runs. You get two curves on one plot:
<img src="https://user-images.githubusercontent.com/12895056/55162520-f115ee00-515f-11e9-8dec-858213b44066.png" width=200>

- Select a group and click plot runs. You get all of the curves from the group on one plot:
<img src="https://user-images.githubusercontent.com/12895056/55162568-068b1800-5160-11e9-81f1-d1a1915ef2df.png" width=200>

- Select one row from the first group and two rows from the second group. You should get three curves:
<img src="https://user-images.githubusercontent.com/12895056/55162805-7ef1d900-5160-11e9-8a78-c1985b377c20.png" width=200>

- Select one row from the first group and the overall group for the second group. You should get three curves:
<img src="https://user-images.githubusercontent.com/12895056/55162881-a779d300-5160-11e9-8977-0c863f116e61.png" width=200>

### Test the second button ("plot group")
- Select a row or rows within a group and click plot group. Nothing should happen (ideally this should be disabled).

- Select a group and click plot group. You should get a single curve (for the stitched result):
<img src="https://user-images.githubusercontent.com/12895056/55162725-52d65800-5160-11e9-9c48-ebdda990ad04.png" width=200>

- Select two groups and click plot group. You should get two curves:
<img src="https://user-images.githubusercontent.com/12895056/55162761-65509180-5160-11e9-96d4-9085292fd215.png" width=200>

- Select one row from the first group and the overall group for the second group. The row should be ignored and one curve plotted for the second group:
<img src="https://user-images.githubusercontent.com/12895056/55162950-c7a99200-5160-11e9-8481-6873c3831ffc.png" width=200>

*Tests posted by @gemmaguest on the issue*

Fixes #25431 . 

*This does not need release notes as I believe it is an expected feature of the new GUI already*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-10 14:03 UTC, gemmaguest requested changes
I think there is a better approach than passing the notifications up through the views. Sorry I didn't think of this before! We could use an interface similar to `IMessageHandler`:
- Add an interface `IPlotter` with a pure virtual method `reflectometryPlot()` (for ease of testing and extendibility).
- Inherit this from your `Plotter` class (this could perhaps be split into 2 separate classes for the Qt4 and Qt5 stuff to avoid having repeated checks for the Qt version. What you have is probably fine for now, except that it might be easier to test if split up.)
- The `Plotter` class for Qt4 should have a pointer to the `IMainWindowView` rather than the `RunsTableView`. This already has a method `runPythonAlgorithm`. The other views then shouldn't need to know about the python stuff.
- Set up the `IPlotter` for the relevant version of Qt in `MainWindowView::initLayout`, and pass it to the `RunsTablePresenterFactory` and through to the `RunsTablePresenter`.
- The `RunsTablePresenter` should then just be able to call `IPlotter::reflectometryPlot()`.

What do you think?

Otherwise:
- code quality looks good and works well :+1:
- some minor comments in-line
- New unit tests should be added. Having an `IPlotter` interface you can mock should help when testing `RunsTablePresenter`, and to test the Qt4 `Plotter` you could use a `MockMainWindowView`

2019-04-11 09:35 UTC, Pasarus commented on qt/scientific_interfaces/ISISReflectometry/GUI/RunsTable/RunsTablePresenter.cpp
> +  m_view->jobs().clearSelection();
That was the behavior of the previous GUI, I could always remove this?

2019-04-11 14:08 UTC, Pasarus commented on qt/scientific_interfaces/ISISReflectometry/GUI/RunsTable/RunsTablePresenter.cpp
> +    if (workspaceName != "")
:+1:

2019-04-16 13:30 UTC, gemmaguest requested changes
Thanks for the changes - I think this is much easier to follow :+1:

Just some comments regarding minor things to tidy up - mainly include statements which I think have been left in accidentally, and some uses of pointers where I think references would do.

2019-04-16 13:30 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsView.cpp
> +#include "../Batch/BatchView.h"
Is this needed?

2019-04-16 13:30 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsView.h
> +  BatchView *m_batchView;
I don't think this is used any more? This and the forward declaration could be removed.

2019-04-16 13:46 UTC, Pasarus commented on qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchView.h
> +  void executePythonCode(const std::string &pythonCode);
Is this needed?

2019-04-16 13:46 UTC, Pasarus commented on qt/scientific_interfaces/ISISReflectometry/GUI/RunsTable/RunsTablePresenter.cpp
> +#include "GUI/Plotting/Plotter.h"
It should be IPlotter.h

2019-04-16 13:46 UTC, Pasarus commented on qt/scientific_interfaces/ISISReflectometry/Reduction/ReductionJobs.cpp
>  #include <iostream>
Remove iostream?

2019-04-16 13:46 UTC, Pasarus commented on qt/widgets/common/inc/MantidQtWidgets/Common/Batch/JobTreeView.h
> +  ~JobTreeView(){};
Nessercary?

2019-04-23 08:06 UTC, Pasarus commented
@gemmaguest I believe I have fixed all of the associated fixes/requests on this PR. Could you give it another review please?

2019-04-23 11:31 UTC, gemmaguest approved these changes
This all looks good now and all combinations of plots work :+1: :+1:

Some notes from testing:
- The .tbl file can't be imported in the restructured GUI yet so you have to enter the run numbers and angles separately.
- As noted in the test instructions, the differences in plots are not related to this PR (I get the same differences on the feature branch we're merging into). I'll look into that in a future PR. The main thing to test here is that the correct workspaces are being plotted, which they are.
- There is a crash when processing all groups which is also not related to this PR as I can reproduce it in the feature branch we're merging into. I'll look into that in a future PR.

2019-04-24 06:07 UTC, merged