Allow blocking of signals to the AlgorithmProgress
mantidproject/mantid pull request #25468
Opened 2019-04-03 11:30 UTC by DTasev

**Description of work.**
Allows blocking of all signals to the AlgorithmProgressPresenter. This stops the progress bar from updating. Use case is to prevent updates to the progress bar during ProjectRecovery, which uses a separate progress bar.

**To test:**
- Add blocking of signals before running project recovery.
- Run a recovery, progress bar should not update
- Allow signals at the end
- Progress bar should update as normal

Fixes #25324

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-03 15:48 UTC, alicerussell1 requested changes
The code looks good and works as intended. It has some failing tests and these need to be fixed.

2019-04-05 09:31 UTC, alicerussell1 approved these changes
This looks good, still works as intended and relevant tests now pass 👍 There is a remaining failed tests but this is unrelated.

2019-04-09 08:08 UTC, DTasev commented
Merged in master, that should fix the OSX Muon test with the change from https://github.com/mantidproject/mantid/pull/25344

2019-04-09 12:21 UTC, DTasev commented
I've just manually started ClangFormat as it was stuck scheduling from earlier

2019-04-09 14:34 UTC, merged