Add explicit calculations to rasterize for hollow cylinders
mantidproject/mantid pull request #25475
Opened 2019-04-05 09:11 UTC by aybamidele

**Description of work.**
I added explicit calculations for hollow cylinders to the rasterize module and included unit tests.

Refs #25149 
 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-06 11:50 UTC, peterfpeterson requested changes
Looks like a good addition that will help with absorption. Some very minor changes.

2019-04-06 11:50 UTC, peterfpeterson commented on Framework/Geometry/src/Rasterize.cpp
> +const V3D calculatePos(const double phi, const double R, const double z,
Maybe calling in `calculatePosInCylinder` would be clearer. I don't know if its necessary since it is only in this file.

2019-04-06 11:50 UTC, peterfpeterson commented on Framework/Geometry/src/Rasterize.cpp
> +  const auto x_prime = coords[0];
I think these should be `const auto &` to help the compiler in knowing that you just want friendlier names rather than copies of the data.

2019-04-08 12:28 UTC, aybamidele commented
It says MuonTest_MuonPairingAsymmetryTest failed. But I try to run it and all 19 tests pass. I'm not sure what could be the problem here.

2019-04-08 14:41 UTC, peterfpeterson submitted a review, later dismissed
Looks good to me. I like the clarity of moving some of the code out and appreciate renaming variables in nearby code.

2019-04-09 07:23 UTC, martyngigg commented
@aybamidele It looks like there are some compiler warnings on OSX. Could you also rebase with `master` to see if that fixes the IN4 system test failure?

2019-04-09 07:29 UTC, aybamidele commented
Yes, that is on my todo list

2019-04-09 13:15 UTC, peterfpeterson approved these changes

2019-04-09 14:55 UTC, merged