Refs #25542. Made GenerateEventsFilter work with all MatrixWorkspace.
mantidproject/mantid pull request #25543
Opened 2019-04-16 03:50 UTC by wdzhou

**Description of work.**

Enable GeneratesEventFilter to work with any MatrixWorkspace containing **run** and sample logs.

**To test:**

```
CreateWorkspace()
```

Fixes #25542. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-16 20:31 UTC, peterfpeterson requested changes
This is a good improvement to `GenerateEventsFilter`. A couple of small changes:
- Add release notes and/or update the algorithm's documentation. I think the example in the PR testing instructions would be really useful for users.
- The exceptions generated would benefit from greater clarity. I think having the workspace name and the fact that the `proton_charge` log is missing is useful in both (current error doesn't give the log's proper name). Then the extra "not an event workspace" or "is empty event workspace." Hopefully users never see the errors, but when they do they'll benefit from the clarity.

2019-04-17 17:51 UTC, wdzhou commented
@peterfpeterson all of your suggestion have been implemented.

2019-04-17 18:11 UTC, peterfpeterson requested changes
Some typos then it is good

2019-04-17 18:11 UTC, peterfpeterson commented on Framework/Algorithms/src/GenerateEventsFilter.cpp
> +            << " is not an Eventworkspace and does not have sample 'log "
```suggestion
            << " is not an Eventworkspace and does not have sample log "
```

2019-04-17 18:11 UTC, peterfpeterson commented on Framework/Algorithms/src/GenerateEventsFilter.cpp
> +               "proton_charge'."
```suggestion
               "'proton_charge'."
```

2019-04-17 18:11 UTC, peterfpeterson commented on Framework/Algorithms/src/GenerateEventsFilter.cpp
> +               "Therefore, o Unable to "
```suggestion
               "Therefore, unable to "
```

2019-04-17 22:51 UTC, wdzhou commented on Framework/Algorithms/src/GenerateEventsFilter.cpp
> +               "Therefore, o Unable to "
where did this 'o' come from?

2019-04-17 22:52 UTC, wdzhou commented on Framework/Algorithms/src/GenerateEventsFilter.cpp
> +               "proton_charge'."
' was in a bad place.

2019-04-18 14:29 UTC, peterfpeterson approved these changes

2019-04-22 15:19 UTC, merged