Flipping ratio correction
mantidproject/mantid pull request #25565
Opened 2019-04-18 17:36 UTC by AndreiSavici

**Description of work.**

This is a new algorithm to correct for flipping ratio. It multiplies MDEvents by  F/(F-1) and 1/(F-1). F can be a function of some log values

**To test:**
See documentation example. 

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-29 10:05 UTC, aybamidele commented
Could you point me to the documentation for this?

2019-04-29 17:09 UTC, AndreiSavici commented
https://inis.iaea.org/collection/NCLCollectionStore/_Public/16/076/16076003.pdf is the Scarpf paper (see page 87). The last formulas were scaled up, so the intensity is conserved. The link for the orther paper is in the help file. Let me know if you have issues retrieving it.

2019-05-09 14:01 UTC, peterfpeterson requested changes
Lots of changes in your inner loop.

2019-05-09 14:01 UTC, peterfpeterson commented on Framework/MDAlgorithms/src/FlippingRatioCorrectionMD.cpp
> +      for (; it != it_end; it++) {
Couldn't this be a range-based `for` loop?

2019-05-09 20:20 UTC, peterfpeterson approved these changes

2019-05-10 07:59 UTC, merged