Remove runs with bad proton charges from added runs
mantidproject/mantid pull request #25571
Opened 2019-04-23 10:33 UTC by TTitcombe

DRAFT as waiting to confirm this solution with the scientists
and waiting for PR #25562 to close

**Description of work.**
There is a bug which can cause SANS2D files to contain bad times in the proton charge logs (bad = the pulse occurred in the 1700s). While this has been fixed for new files being written, it can cause subtle bugs if these bad runs are included in added files.

This PR omits bad runs from added files, and warns the user that they should look into the proton charges. We believe this to be a safer option that running a script to predict a "good" proton charge time automatically, as incorrectly guessing this would be more damaging to the output data.

I've added a unit test, and filled in a unit test which was left empty. While I was digging around the old SANS code I also fixed a few code quality issues, as the volume of squiggly yellow lines made it difficult to read any code at all.

**Report to:** Sarah SANS2D

**To test:**
1. Interfaces -> SANS -> ISIS SANS
2. Ensure ISIS data archive is on
3. Load the attached user file in order to set your instrument to SANS2D
4. Click the sum runs tab (left)
5. In the top bar, enter 58090-58095 (this will add all runs between 58090 and 58095. The bad run is 58093)
6. Set your logger level to warning and click `Sum`. You should see a warning that run 58093 was omitted and that you should look at the proton logs if you want to use this data. The addition should continue

This will save a file to your default save directory, which you may want to delete afterwards.

*There is no associated issue.*

*This does not require release notes* because **fix to issue not encountered by users**

**Data:**
[user_file.txt](https://github.com/mantidproject/mantid/files/3107056/user_file.txt)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-06-07 14:03 UTC, mantid-builder commented
@TTitcombe have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-06-07 14:03 UTC, mantid-builder commented
@TTitcombe there are conflicts here, can you resolve them.
<!-- {"problem_type": "conflicting"} -->

2019-07-01 08:33 UTC, gvardany commented
@TTitcombe Is this still a draft?

2019-07-08 14:51 UTC, NickDraper requested changes
![image](https://user-images.githubusercontent.com/1017173/60819738-03a8b600-a198-11e9-8400-9443c9a69f6e.png)
 So I still see very negative dates

I added 58092-58094, save using the add within SANS and then reloaded with the Load alg.

2019-07-09 12:39 UTC, NickDraper requested changes

2019-07-09 12:39 UTC, NickDraper commented on scripts/SANS/SANSUtility.py
> +        first_log_time = pc.firstTime().toISO8601String()
So this would be better to create a time of 1990 and then compare the date times rather than convert to string and parse out the date.

2019-07-09 12:39 UTC, NickDraper commented on scripts/SANS/SANSUtility.py
> +        if int(first_log_time.split("-")[0]) < 1990:
I feel we need to run this as a loop to handle the situation where there is more than one bum value.

2019-07-15 11:07 UTC, NickDraper commented
So we are vloser, and almost there.  The file saves, and reloads and the unfiltered log looks ok.

But, if you have Status and Period filtering on the log, the graph comes out with a ridiculous range, and the stats for the log are wrong.

unfiltered
![image](https://user-images.githubusercontent.com/1017173/61211980-d78db780-a6f8-11e9-91e3-ff3f922b8033.png)


Status + period filtered
![image](https://user-images.githubusercontent.com/1017173/61212002-e3797980-a6f8-11e9-96e0-4e3a9b654a72.png)

Just status filtering is like none


So I suspect the issue is in the period log filtering
![image](https://user-images.githubusercontent.com/1017173/61212050-0c9a0a00-a6f9-11e9-8d84-cc8cba5a5829.png)

2019-07-17 12:24 UTC, Mantid-Matthew commented
Having looked into this more closely the bad values when filtering by periods come about because all of the period logs for the run are also corrupted and contain erroneous times. I'm therefore uncertain how to go about resolving this. Trying to correct all the corrupted logs from the workspace feels like it is beyond the scope of this issue which was specifically aimed at correcting an error when adding runs in overlay mode caused by the bad proton charge times. It is possible to filter all the TimeSeriesProperties from a run by the time of the first good proton charge using the code snippet below which seems sensible and corrects the issues seen above but probably needs double checking with scientists?

```
            for prop in run.getProperties():
                try:
                    prop.filterByTime(start, end)
                except AttributeError:
                    pass
```

I think there is probably a better global solution to how we deal with erroneous logs (likely by flagging them more clearly to the user, currently there is only a one line warning message when the file is loaded) but I'm not sure what is it at this stage.

2019-07-17 15:43 UTC, NickDraper commented
Could you talk to @martyngigg about this.  We create the period log from the icp_event (I think that is the name) log.  We could put some simple logic tests into the code that parses that log.

I'm keen to get some form of a fix in for this release for this so we don't crash when encountering this data.

2019-07-18 10:01 UTC, NickDraper submitted a review, later dismissed

2019-07-18 10:03 UTC, NickDraper commented
While imperfect this is good to go for this release and make the handling of these files functional.

2019-07-18 10:03 UTC, merged