Class_maker adding files incorrectly to some CMakeLists
mantidproject/mantid pull request #25581
Opened 2019-04-24 13:33 UTC by alicerussell1

**Description of work.**
This PR adds extra searches to the `class_maker` in `\buildconfig`  so it will find and add the file to the correct section in the `CMakeLists.txt` file if the section is formatted like this
```
set(
  INC_FILES
```

**To test:**
Add a new class using `class_maker.py` into the subproject `MDAlgorithms`. Check the `CMakeLists.txt` has updated correctly so that each file has been added to the correct list and not at the end. Check the files are still added to the correct locations.

Fixes ##25579

This does not require release notes because it is only used internally.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-04-24 16:11 UTC, dtasev requested changes
The functionality of this PR works well:
```
$ /buildconfig/class_maker.py MDAlgorithms TestClass25581
On branch pr/25581-merged
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Framework/MDAlgorithms/CMakeLists.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Framework/MDAlgorithms/inc/MantidMDAlgorithms/TestClass25581.h
	Framework/MDAlgorithms/src/TestClass25581.cpp
	Framework/MDAlgorithms/test/TestClass25581Test.h
```

However, `class_maker.py` seems to break the `cmake-format` formatting, as it adds a `\t ` (tab and whitespace) at the start of every line inside the `set` calls.

Do you think it's possible to change it to the 4 spaces that `cmake-format` uses, or should that be a different PR?

2019-04-25 08:52 UTC, alicerussell1 commented
Ah yes, I had not noticed that! I shall include it in this PR.

2019-04-25 09:16 UTC, dtasev approved these changes

2019-04-25 13:09 UTC, martyngigg commented on buildconfig/cmakelists_utils.py
> +        lines.append("    " + file)
Thank you for this! The tabs everywhere also irritated me :)

2019-04-25 13:09 UTC, merged