25576 move frequency domain analysis to workbench
mantidproject/mantid pull request #25593
Opened 2019-04-25 09:52 UTC by Mantid-Matthew

**Description of work.**

This moves the Frequency Domain Analysis Tab to the workbench.

**To test:**

In the workbench open the FDA GUI. It is in the Muon subsection of the interface list. Check that a few standard workflows work. If you need an explanation of how the GUI is supposed to work feel free to message me.

Fixes #25576

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-05-08 10:06 UTC, AnthonyLim23 commented
had a play and it seems to work. @Mantid-Matthew you have conflicts

2019-05-08 10:25 UTC, AnthonyLim23 commented
need to test:

1. Works in mantidplot
2. what happens if you open GUI, let it drop to the back and then 'reopen' the GUI

2019-05-08 10:47 UTC, AnthonyLim23 commented
it appears that browse does not work in workbench. I browse to a file and select it. Then it does not load

2019-05-10 15:02 UTC, AnthonyLim23 commented
conflicts and phase table presenter is failing on OSX

2019-05-15 16:19 UTC, AnthonyLim23 submitted a review, later dismissed
all works in workbench and mantidplot :shipit:

2019-05-16 08:01 UTC, martyngigg requested changes
Just a request for one small change to maintain future compatability.

2019-05-16 08:01 UTC, martyngigg commented on scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_view.py
> +        if PYQT4:
This check order looks good :+1:

2019-05-16 08:01 UTC, martyngigg commented on scripts/Muon/GUI/Common/load_run_widget/load_run_view.py
> +        # self.horizontal_layout.setMargin(0)
Can we remove the commented out code?

2019-05-16 08:01 UTC, martyngigg commented on scripts/Muon/GUI/MuonAnalysis/load_widget/load_widget_view.py
> +        # self.horizontal_layout.setMargin(0)
Commented out code?

2019-05-16 11:08 UTC, martyngigg approved these changes

2019-05-16 14:07 UTC, merged