10x faster Atom class
mantidproject/mantid pull request #25732
Opened 2019-05-17 22:52 UTC by quantumsteve

**Description of work.**

Using the proton number as an index leads to some substantial performance improvements.

I added two performance tests to show the difference

* test_z_performance: before: 0.246293s, after: 0.0214344s
* test_symbol_performance: before: 5.21779s, after: 0.310218s

Uses `tcb::span` suggested by @SimonHeybrock. Should that header be in a different place? 

**To test:**

* Code review
* I'd suggest running the performance tests with and without changes to `Atom.h` and Atom.cpp`

*There is no associated issue.*

I added a line to the release notes, though I suspect this is more about code smells than something observed by users.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-05-20 13:09 UTC, peterfpeterson commented
Should `span.hpp` be grabbed through an external project?

2019-05-20 15:21 UTC, quantumsteve commented
@peterfpeterson I moved span to an external project, which reduces the size of this PR.

2019-05-20 18:09 UTC, quantumsteve commented
`DOWNLOAD_NO_EXTRACT` wasn't available until CMake v3.6
https://github.com/Kitware/CMake/commit/1ba9b535478a2a73100a6b0e9bf01983b4774cb8

2019-05-22 12:43 UTC, peterfpeterson requested changes
A very minor change to the release notes and this is good to go. Once this gets merged, you should announce the availability of `tcb/span.h` on slack.

2019-05-22 12:43 UTC, peterfpeterson commented on docs/source/release/v4.1.0/framework.rst
> +- 10x performance improvement in calls to Mantid::PhysicalConstants::getAtom.
```suggestion
- 10x performance improvement in calls to ``Mantid::PhysicalConstants::getAtom``.
```

2019-05-22 14:38 UTC, peterfpeterson approved these changes

2019-05-22 14:52 UTC, merged