Disable version check2
mantidproject/mantid pull request #25752
Opened 2019-05-23 13:51 UTC by OwenArnold

WIP do not merge

2019-06-07 14:03 UTC, mantid-builder commented
@nvaytet do you have any comments on this PR?
<!-- {"problem_type": "review_requested"} -->

2019-06-20 08:22 UTC, nvaytet requested changes
Small thing: Strange: why was the `images/mantid_notebook_unstable.ico` file renamed?

Apart from that, all looks good.

2019-06-20 08:22 UTC, nvaytet commented on Framework/NexusGeometry/inc/MantidNexusGeometry/NexusGeometryParser.h
> +  virtual void error(const std::string &warning) = 0;
```suggestion
  virtual void error(const std::string &error) = 0;
```

2019-06-20 09:04 UTC, OwenArnold commented
> Small thing: Strange: why was the `images/mantid_notebook_unstable.ico` file renamed?
> 
> Apart from that, all looks good.

That was a problem in Master at the time. I'll remerge master.

2019-06-26 09:25 UTC, nvaytet approved these changes

2019-07-02 07:22 UTC, nvaytet commented
Hi Owen, a new warning has popped up with `clang` after you merged the `disable_version_check2` branch. Can you check what happened?

2019-07-18 14:03 UTC, mantid-builder commented
@OwenArnold the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-07-19 05:33 UTC, merged