GCC8 compiler warnings
mantidproject/mantid pull request #25751
Opened 2019-05-23 09:26 UTC by Pasarus

**Description of work.**
Recently I moved to an operating system using GCC8 to compile by default so I have removed a large portion of the warnings when compiling. With the exception of some warnings caused by `-Woverloaded-virtual` which at present seem incorrect, however, more investigation should be done before this is assumed.

**To test:**
- Code Review
- Assure tests pass

*There is no associated issue.*

*Internal change so no release notes*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-05-23 10:51 UTC, LowriJenkins requested changes
Just a few small changes, and I'll approve once the tests pass

2019-05-23 10:51 UTC, SamJenkins1 commented on Framework/Algorithms/src/RadiusSum.cpp
> + *  The function will raise exception (std::const invalid_argument &) if an
```suggestion
 *  The function will raise exception (std::invalid_argument) if an
```

2019-05-23 10:51 UTC, SamJenkins1 commented on Framework/Algorithms/src/RadiusSum.cpp
> + *  If the test fails, it will raise an exception (const invalid_argument &) to
```suggestion
 *  If the test fails, it will raise an exception (invalid_argument) to
```

2019-05-23 10:51 UTC, SamJenkins1 commented on Framework/LiveData/src/ISIS/DAE/isisds_command.cpp
> +  const auto commCommandSize = sizeof(comm.command);
if you move this up a line you can replace `malloc(sizeof(comm.command)+1)` with `malloc(commCommandSize+1)`

2019-05-28 11:54 UTC, LowriJenkins approved these changes

2019-05-28 20:31 UTC, merged