Switched to doing show data in one place
mantidproject/mantid pull request #25780
Opened 2019-05-29 12:28 UTC by Mantid-Matthew

**Description of work.**

This fixes an issue where-by the Muon GUI could crash when runs with different IDF's were loaded concurrently. 

**To test:**

Open the new Muon Analysis GUI, switch to the EMU instrument  and load run 90,000. Then try and load the run 812. You should get a succession of error boxes rather than a hard crash.

Fixes #25779 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-05-29 14:47 UTC, AnthonyLim23 commented
ubuntu qt5 failure :(

2019-05-30 07:38 UTC, Mantid-Matthew commented
This is a test of the old frequency domain analysis GUI which does not need to be ported to workbench so removed it from qt5 test list

2019-05-30 10:23 UTC, AnthonyLim23 approved these changes

2019-05-30 13:44 UTC, DanNixon requested changes
The failed tests were automatically restarted and passed indicating a potentially random failure. Can you revert the removal of the unit tests and see if this remains a problem.

2019-05-30 13:55 UTC, Mantid-Matthew commented
There seems to be an issue with the thread_model used in the Muon GUI's which causes occasional random failures when forced to run with Qt5. This seems to be causing occasional segfaults in tests which use it for threading. Having discussed it the best solution seems to be to harmonize the threading in workbench so that everything uses the threading implementation in mantidqt. I think doing so is beyond the scope of this PR however.

The tests removed from the qt5 list here are ones that are either not using any qt at all so do not need to be run twice using both qt4 and qt5 or correspond to old interfaces which are planned to be removed before being ported to workbench so also do not need to be tested against qt5.

2019-05-30 14:38 UTC, DanNixon approved these changes

2019-05-30 14:39 UTC, merged