Save Environment Algorithm
mantidproject/mantid pull request #25836
Opened 2019-06-03 13:00 UTC by SamJenkins1

**Description of work.**
Added algorithm `SaveSampleEnvironmentAndShape` to save out a binary .stl file containing the mesh of the entire shape of the environment and sample as a single mesh.
**To test:**
use .stl files in `ExternalData/Testing/Data/UnitTest/` along with `LoadSampleShape` and `LoadSampleEnvironment` to construct a sample (it must at least have a sample shape) then run `SaveSampleEnvironmentAndShape`, the .stl file created should be loadable in mantid using `LoadSampleShape` and should be able to be loaded in https://www.viewstl.com/. 

Attempting to save a non mesh based sample, e.g. one created using `CreateSampleShape` should fail.

The new tests should pass.

Fixes #25722

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-06-12 13:41 UTC, martyngigg requested changes
Looks generally nice. A few inline comments

2019-06-12 13:41 UTC, martyngigg commented on Framework/DataHandling/src/SaveSampleEnvironmentAndShape.cpp
> +  } catch (std::bad_cast &) {
Is there a specific place where `bad_cast` can be thrown? It is generally good practice to keep exception handlers as tight as possible to the code that can throw.

2019-06-12 13:41 UTC, martyngigg commented on Framework/DataHandling/src/SaveStl.cpp
> +namespace Mantid {
A newline here would help readability

2019-06-12 13:41 UTC, martyngigg commented on Framework/DataHandling/src/SaveStl.cpp
> +#include <boost/functional/hash.hpp>
Is this used anywhere?

2019-06-13 07:51 UTC, martyngigg requested changes
This is looking good. My final comment is that we could do with some doxygen comments for each of the methods to describe their arguments and purpose for future developers.

2019-06-13 07:51 UTC, martyngigg commented on Framework/DataHandling/src/SaveSampleEnvironmentAndShape.cpp
> +const Geometry::MeshObject &toMeshObject(const Geometry::IObject &object) {
This is a nice wrapper to display the intent. of the error catching :+1:

2019-06-13 07:51 UTC, martyngigg commented on Framework/DataHandling/src/SaveStl.cpp
> +/**
Should this comment be attached to the class in the header. It looks like it is not describing the method below?

2019-06-13 07:51 UTC, martyngigg commented on Framework/DataHandling/test/SaveSampleEnvironmentAndShapeTest.h
> +// Mantid Repository : https://github.com/mantidproject/mantid
Good set of tests!

2019-06-13 09:45 UTC, martyngigg approved these changes
One more final tidy up :)

2019-06-13 09:45 UTC, martyngigg commented on Framework/DataHandling/inc/MantidDataHandling/SaveStl.h
> +  /**
For doxygen to attach this to the correct class it need to go above the defintion:
```c++
   * Class to contain functionality for writing out STL files for
   * SaveShapeAndEnvironment. handles actual writing to file, creating the
   * header, and removing the scale applied when loading.
   *
   */
class DLLExport SaveStl {
```

2019-06-13 09:49 UTC, martyngigg requested changes
I meant to mark that request changes for the final comment fix

2019-06-13 09:56 UTC, martyngigg approved these changes
Good stuff :)

2019-06-17 07:32 UTC, DanNixon commented
How does this handle the fact the the sample and environment start out as separate meshes? IIRC an STL should only contain a single mesh so you'd have to combine them at some point.

2019-06-17 07:34 UTC, SamJenkins1 commented
it combines them

2019-06-17 07:42 UTC, DanNixon commented
I'm not convinced the way you are doing so produces a valid STL file. Although the STL format has been butchered enough most things will probably render it OK for visualisation purposes.

It should be said though there are numerous file formats that would have been much more appropriate here (e.g. OBJ which supports multiple meshes and mesh materials).

2019-06-17 07:51 UTC, SamJenkins1 commented
As far as I can tell the only real problem with the STL files produced by this is the lack of a set normal on each triangle, however as far as I've seen this has little actual affect on what can and can't load the file, and in fact is ignored by mantid.

while other files may be better in the long run, this was fairly quick to implement, making it useful for the testing needed for the current sample-corrections work, was easily testable as the files I had to load in were also STL, and should be fairly easy to extend for other file formats in future.

2019-06-17 07:52 UTC, merged

2019-06-17 07:55 UTC, DanNixon commented
> and should be fairly easy to extend for other file formats in future.

Yes, but we could have also just used an off the shelf library (e.g. Assimp) that can handle more formats that you'd ever need rather than needlessly reinventing the wheel. Doing so would have already reduced the time taken to get to where we are now.

2019-06-17 07:56 UTC, SamJenkins1 commented
hmm, when I looked into loading STL files in, I was unable to find a library usefull for what we wanted, I must admit I assumed the same would have been true for saving them without actually looking into it.

2019-06-17 08:03 UTC, DanNixon commented
Assimp will save and load both STL and OBJ (https://github.com/assimp/assimp#supported-file-formats). The only thing possibly missing we'd be interested in is saving OFF.

2019-06-17 08:04 UTC, SamJenkins1 commented
Yes,I looked it up and found that, its quite irritating that when I was looking into specifically loading STL files I saw no-mention of this library.