remove owning pointers
mantidproject/mantid pull request #25883
Opened 2019-06-12 12:05 UTC by SamJenkins1

**Description of work.**
Removed large number of owning pointers

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-06-18 13:11 UTC, TTitcombe requested changes
My first pass through the code. In generally changes look useful. I have questions about code which is repeated in a few places:
1. There are a few instances of `std::unique_ptr<T> var = std::unique_ptr<T>(p)` and `std::unique_ptr<T> var = std::make_unique`. We should use `auto` in these cases
2. There are quite a few files where you create a unique pointer and then immediately create a rawPointer using `get`. What is this pattern used for?

2019-06-18 13:11 UTC, TTitcombe commented on Framework/Kernel/test/FilteredTimeSeriesPropertyTest.h
> +    constexpr bool transferOwnership(true);
:+1:

2019-06-19 07:17 UTC, SamJenkins1 commented on Framework/API/src/WorkspaceFactory.cpp
> +      child.m_axes[i] = std::unique_ptr<Axis>(parent.m_axes[i]->clone(&child));
->clone returns a new pointer thats a deep copy of the original, thus we can create a seperate unique_ptr

2019-06-19 07:18 UTC, SamJenkins1 commented on Framework/Algorithms/inc/MantidAlgorithms/SofQW.h
> +  auto verticalAxisRaw = verticalAxis.get();
There are functions used below that do not take ownership, or in other similar cases must be called after the move is made, so the contained pointer is needed.

2019-06-19 07:19 UTC, SamJenkins1 commented on Framework/DataHandling/src/SaveISISNexus.cpp
> +  m_isisRaw.ioRAW(rawFile, true);
The pointer in question did not need to be a pointer, its ownership was never used, and it could never be null

2019-06-19 07:59 UTC, SamJenkins1 commented on Framework/API/inc/MantidAPI/MatrixWorkspace.h
> +  void pythonReplaceAxis(const std::size_t &axisIndex, Axis *newAxis);
There is a doxygen comment explaining this in the cpp

2019-06-19 08:59 UTC, TTitcombe submitted a review, later dismissed
Positive code change
Uses of raw pointers which remain seem appropriate

2019-06-19 16:33 UTC, martyngigg requested changes
This is a great tidy up. Just one thing that I think is worth cleaning up around the Python access function.

2019-06-19 16:33 UTC, martyngigg commented on Framework/API/src/MatrixWorkspace.cpp
> +void MatrixWorkspace::pythonReplaceAxis(const std::size_t &axisIndex,
This is exactly the correct thing to do but not quite in the right place. The [Python layer](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp) is able to contain these so called "proxy" functions as intermediaries without them needing to clutter up the C++ API.

2019-06-20 08:31 UTC, martyngigg commented on Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp
> + * Raw Pointer wrapper of replaceAxis to allow it to work with python
:+1:

2019-06-20 08:46 UTC, martyngigg approved these changes

2019-06-20 11:24 UTC, merged