fix master slave chopper dependency (no ticket)
mantidproject/mantid pull request #25995
Opened 2019-06-25 03:38 UTC by geishm-ansto

Fix a bug identified when instrument set to a new configuration.

NA

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-06-27 09:47 UTC, TTitcombe requested changes
@geishm-ansto The changes look sensible, however, would it be possible to add a test to `LoadPLNTest.h` to check that `gatePeriod` has been set as we would expect / that the bug has been fixed?

I'm not sure how difficult it would be to test that directly, but we could run `LoadPLN` on data with the same `FermiChopperFreq` but different `OverlapChopperFreq`, which would result in different `gatePeriod` and therefore different results?

2019-06-27 23:07 UTC, geishm-ansto commented
@TTitcombe Hi Tom, I added the gate period to the log and the unit test for the loader. It is useful for regression testing but the test does not cover the data that highlighted the problem. That was verified and documented in my local testing.

2019-06-28 07:02 UTC, TTitcombe approved these changes

2019-06-28 07:02 UTC, TTitcombe commented
Changes look good. Test case to capture regression

2019-06-28 08:41 UTC, merged