Indirect Sqw - Check Q and E are within the plot range
mantidproject/mantid pull request #26224
Opened 2019-07-05 15:38 UTC by robertapplin

Merge #25956 First
----------------------

**Description of work.**
This PR adds better validation checks for data when it is loaded in to the Data Reduction interface.

**To test:**
1. `Interfaces`->`Indirect`->`Data Reduction`->`Sqw` tab
2. Load data below
3. Change the Q Low value to be 0.2. (This is out of the acceptable range)
4. Click `Run`. A useful message should appear.

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3363322/irs26176_graphite002_red.zip)

Fixes #26209 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-09 08:28 UTC, LamarMoore requested changes
The solution seems to work but there is a change mentioned below which should fix the issue with the other platforms.

2019-07-09 08:29 UTC, LamarMoore commented on qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h
> +  return AnalysisDataService::Instance().retrieveWS<T>(workspaceName);
This needs to be fully qualified I think.

2019-07-09 08:58 UTC, LamarMoore commented on qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h
> +  return AnalysisDataService::Instance().retrieveWS<T>(workspaceName);
I applied the fix. @mantidproject/gatekeepers  will need to review this now.

2019-07-09 11:46 UTC, LamarMoore submitted a review, later dismissed

2019-07-09 12:03 UTC, NickDraper commented
@robertapplin Is this PR still "In Progress"?

2019-07-09 12:04 UTC, robertapplin commented
Yes, there are a couple additions that need to be made. These are nearly done and I'll remove the label soon

2019-07-10 09:14 UTC, LamarMoore commented
@robertapplin  There are semicolons at the end of function definitions in `IndirectDataValidationHelper.cpp` lines 107,127,149,88 which are causing the builds to fail.

2019-07-10 09:17 UTC, robertapplin commented
@LamarMoore Thanks, I'll fix this now

2019-07-10 14:12 UTC, robertapplin commented
I just need to finish writing the Unit tests for the IndirectDataValidationHelper, and then this will be ready to go.

2019-07-11 07:30 UTC, LamarMoore commented
@robertapplin Linux is not happy about your `MockDataSelector` being in an anonymous namespace.

2019-07-11 08:16 UTC, robertapplin commented
Thanks @LamarMoore , this should be fixed now.

2019-07-11 11:57 UTC, LamarMoore commented
@mantidproject/gatekeepers this is ready again.

2019-07-11 12:04 UTC, merged