Update to Muon interface release notes
mantidproject/mantid pull request #26236
Opened 2019-07-08 10:15 UTC by LolloB

Updated the release notes for the Muon interface.

**To test:**

Fixes #26114.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-08 13:35 UTC, Harrietbrown commented
What does deleting ``CreateSampleShape-v1.rst`` has to do with this PR?

2019-07-08 14:04 UTC, LolloB commented
> What does deleting `CreateSampleShape-v1.rst` has to do with this PR?

Nothing, I had deleted it as it does not compile on Ubuntu 18.04+ and forgotten to reintroduce it.

2019-07-08 15:46 UTC, AnthonyLim23 commented on docs/source/release/v4.1.0/muon.rst
> +* Muon Analysis v2 added to MantidPlot and workbench
```suggestion
* Muon Analysis v2 added to MantidPlot and workbench.
```

2019-07-08 15:46 UTC, AnthonyLim23 commented on docs/source/release/v4.1.0/muon.rst
> +* Elemental analysis interface added to workbench
```suggestion
* Elemental analysis interface added to workbench.
```

2019-07-08 16:26 UTC, AnthonyLim23 commented
can we have more details about the new muon analysis GUI and a link to its documentation. Please stress how it is designed to work better with multiple runs, be more intuitive and more stable. Add anything else you think is appropriate.

2019-07-09 10:11 UTC, Harrietbrown commented
Elemental Analysis itself really needs it's own documentation. I think that is what is implied in the issue.

2019-07-09 12:19 UTC, AnthonyLim23 commented
@Harrietbrown we have documentation on the elemental analysis GUI in a PR #26242

@NickDraper is this the sort of thing you had in mind?

2019-07-11 16:08 UTC, NickDraper requested changes
I'd like to see a screenshot added and a list of the best points about the new GUI, ideally why it is better than the old one, and what it lets people do.  All aimed at our users.

This is the culmination of about 1-5 - 2 man years of work, and this just does not do that credit.

2019-07-15 08:13 UTC, AnthonyLim23 commented
Could you also add the fit and results table link to the frequency domain docs.

2019-07-15 10:19 UTC, Harrietbrown reviewed
A few notes on capitalization, and make sure that documentation for the new FDA tabs are updated as well to say that they are used by FDA.

2019-07-15 10:19 UTC, Harrietbrown commented on docs/source/release/v4.1.0/muon.rst
> +* :ref:`Frequency Domain Analysis <Frequency_Domain_Analysis_2-ref>` GUI added to workbench.
Workbench is a proper noun and should be capitalized like you would MantidPlot

```suggestion
* :ref:`Frequency Domain Analysis <Frequency_Domain_Analysis_2-ref>` GUI added to Workbench.
```

2019-07-15 10:19 UTC, Harrietbrown commented on docs/source/release/v4.1.0/muon.rst
> +* :ref:`Muon ALC GUI <MuonALC-ref>` added to workbench.
```suggestion
* :ref:`Muon ALC GUI <MuonALC-ref>` added to Workbench.
```

2019-07-15 10:19 UTC, Harrietbrown commented on docs/source/release/v4.1.0/muon.rst
> +* :ref:`Muon Analysis v2 <MuonAnalysis_2-ref>` added to MantidPlot and workbench.
```suggestion
* :ref:`Muon Analysis v2 <MuonAnalysis_2-ref>` added to MantidPlot and Workbench.
```

2019-07-15 10:19 UTC, Harrietbrown commented on docs/source/release/v4.1.0/muon.rst
> +* :ref:`Elemental analysis <Muon_Elemental_Analysis-ref>` interface added to workbench.
```suggestion
* :ref:`Elemental analysis <Muon_Elemental_Analysis-ref>` interface added to Workbench.
```

2019-07-15 10:19 UTC, Harrietbrown commented on docs/source/interfaces/Frequency Domain Analysis.rst
> +* :ref:`Results Table Tab <muon_results_tab-ref>`
On the `muon_fitting_tab.rst` and `muon_results_tab.rst` documents add Frequency domain analysis to the "User By" section.

2019-07-15 10:33 UTC, Harrietbrown requested changes

2019-07-15 10:33 UTC, Harrietbrown commented on docs/source/interfaces/muon_results_tab.rst
>  :ref:`Muon Analysis <MuonAnalysis_2-ref>`
```suggestion
:ref:`Muon Analysis 2 <MuonAnalysis_2-ref>`
```

2019-07-15 10:47 UTC, Harrietbrown approved these changes
Very good. Well writen and the improvement section in particular is very positive.

2019-07-15 12:57 UTC, NickDraper approved these changes

2019-07-15 12:57 UTC, merged