workbench setting documentation
mantidproject/mantid pull request #26273
Opened 2019-07-10 10:44 UTC by Harrietbrown

Added documentation on the workbench settings
Added help button to workbench settings menu that opens help window.

**To test:**
1. build docs-html and docs-qthelp
1. open workbench
1. open file --> settings
1. click on the ? button
1. check that the help window opens on the Settings page and that the documentation is suitable.

Fixes #26135 

*This does not require release notes* because **It is an addition to documentation**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-11 14:47 UTC, ghost requested changes
Looks good, I've suggested changes for a few typos below. Also testing on Ubuntu the `?` button in the settings window looks a little too far over on the left-hand-side. A solution might be to add a left margin to its layout in qt-designer?
![image](https://user-images.githubusercontent.com/46960113/61060612-b5dbba00-a3f2-11e9-9442-8df69e2a62cd.png)

2019-07-15 07:35 UTC, Harrietbrown commented
That should fix the button near the margin, but we will have to check for different screen resolutions

2019-07-15 08:41 UTC, hsautessella commented
This all looks good to me now. The help button looks well positioned on my 1080p Ubuntu machine and 4k Windows one

2019-07-15 08:41 UTC, ghost approved these changes

2019-07-15 09:11 UTC, merged