Muon Analysis 2 - Fix load current run
mantidproject/mantid pull request #26286
Opened 2019-07-10 16:38 UTC by alicerussell1

**Description of work.**
This PR fixes the `Load current run` button in Muon Analysis 2. It should now find the newest run or give an error if it has not been found.

**To test:**
Open Muon Analysis 2 GUI
Click load current run
It should load a file called `.../data/auto_C.tmp` (the letter will vary depending on most recent run)
To check this is right open the old Muon Analysis GUI and load current run, it should be the same 

Fixes #26216

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-11 06:24 UTC, AnthonyLim23 commented on scripts/test/Muon/utilities/muon_file_utils_test.py
> +        file = StringIO(u"autoA")
could we have a different name for the variable as file is used for IO

2019-07-11 12:45 UTC, AnthonyLim23 commented
When it cannot find the run, instead of throwing an error and carrying I would like a message box telling the user it failed. See https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/message_box.py

2019-07-12 12:48 UTC, AnthonyLim23 requested changes
see above comment

2019-07-12 15:25 UTC, alicerussell1 commented
Currently it does give a message box when the error is raised and then stops (which looks the same as if I use the message box linked), do you want it to display it as a warning in a message box and then continue by loading `auto_A.tmp` as default as it was doing?

2019-07-12 15:33 UTC, AnthonyLim23 commented
when I forced it fail, I never got a warning box as it just loaded the default of A. It would be good to tell the user that is what we are doing so a warning box would be good.

2019-07-15 09:56 UTC, AnthonyLim23 approved these changes

2019-07-15 10:41 UTC, merged