Fixed FDA old bug that stopped phasequad
mantidproject/mantid pull request #26296
Opened 2019-07-11 12:39 UTC by AnthonyLim23

The phaseQuad option was not working in the old FDA GUI. 

**To test:**

Open Mantidplot
Open Muon Analysis (the original one not muon analysis 2)
load MUSR 62260
Open frequency domain analysis old
Change workspace to PhaseQuad
Click Calculate FFT
Mantid should not raises an error "MaskedDetectors"
The PhaseQuad workspace should be in the MUSR62260 group
Check that an FFT of the group also adds a workspace
Close the frequency GUI

In muon analysis load HIFI 84447
Open frequency domain analysis old
Change workspace to PhaseQuad
Click Calculate FFT
Mantid should not raises an error "MaskedDetectors"
The PhaseQuad workspace should be in the HIFI84447 group
Check that an FFT of the group also adds a workspace

Fixes #26270. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-11 12:47 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_model.py
> +            print(name, value)
```suggestion
```

2019-07-11 12:47 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_model.py
> +        cloned_workspace_CalMuon = mantid.CloneWorkspace(InputWorkspace=inputs["InputWorkspace"], OutputWorkspace="__tmp__")
```suggestion
        mantid.CloneWorkspace(InputWorkspace=inputs["InputWorkspace"], OutputWorkspace="__tmp__")
```

2019-07-11 12:48 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_model.py
> +        # falls over in here
```suggestion
```

2019-07-11 12:48 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_model.py
>          cropped_workspace_pre_phasequad = mantid.CropWorkspace(InputWorkspace=cloned_workspace,
```suggestion
        mantid.CropWorkspace(InputWorkspace=cloned_workspace,
```

2019-07-12 08:08 UTC, dtasev requested changes
Getting "OUTPUTWORKSPACE" not set error. Last of the output, including the error:

```
CropWorkspace started
Algorithm: CropWorkspace v1
Execution Date: 2019-07-12 08:05:25.037435000
Execution Duration: -1 seconds
UUID: 177c505a-4c30-4e47-b556-807300b5fa09
Parameters:
  Name: InputWorkspace, Value: __TMP0x7faaf835df60, Default?: No, Direction: Input
  Name: OutputWorkspace, Value: , Default?: Yes, Direction: Output
  Name: XMin, Value: 0.10000000000000001, Default?: No, Direction: Input
  Name: XMax, Value: 15, Default?: No, Direction: Input
  Name: StartWorkspaceIndex, Value: 0, Default?: Yes, Direction: Input
  Name: EndWorkspaceIndex, Value: 2147483647, Default?: Yes, Direction: Input
Property "OUTPUTWORKSPACE" is not set to a valid value: "Enter a name for the Output workspace".
Property "OUTPUTWORKSPACE" is not set to a valid value: "Enter a name for the Output workspace".
```

2019-07-12 09:40 UTC, AnthonyLim23 commented
could you send me instructions to try and reproduce it?

2019-07-12 13:40 UTC, DTasev commented
I did these steps:
Open Mantidplot
Open Muon Analysis (the original one not muon analysis 2)
load MUSR 62260
Open frequency domain analysis old
Change workspace to PhaseQuad
Click Calculate FFT

On `Calculate FFT` it shows the error above. Also happens with the HIFI instructions

2019-07-15 10:12 UTC, dtasev approved these changes
Flake8 is happy now, functionality works well - PhaseQuad workspaces are inside the WS groups, and no errors/warnings are shown

2019-07-15 10:45 UTC, merged