Indirect - Replace old output plotting widgets
mantidproject/mantid pull request #26377
Opened 2019-07-17 15:48 UTC by robertapplin

**Description of work.**
This PR replaces the old Indirect output plotting code with a refactored widget that can be used across many of the Indirect Interfaces.

**To test:**

Fixes #26029

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-26 15:58 UTC, BassoLorenzo submitted a review, later dismissed
Works as advertised, no problems were found.

2019-07-30 09:39 UTC, gemmaguest requested changes
Just one minor thing before I'm happy to merge

2019-07-30 09:39 UTC, gemmaguest commented on qt/scientific_interfaces/Indirect/ISISCalibration.cpp
> +      std::move(m_uiForm.ipoPlotOptions), this, PlotWidget::SpectraBin));
I don't think we want to transfer ownership of this to the presenter so this should probably be passed as a raw pointer (similar to uses of `m_uiForm->fitDataView`). Similarly for other uses.

2019-07-30 10:00 UTC, gemmaguest requested changes
Just spotted another use of `move` which looks unnecessary

2019-07-30 10:00 UTC, gemmaguest commented on qt/scientific_interfaces/Indirect/test/IndirectPlotOptionsModelTest.h
> +        std::make_unique<IndirectPlotOptionsModel>(std::move(m_plotter.get()));
I'm not sure the move is necessary here and I think it ends up being owned both locally and by the model? Would it be better to just create it as a raw pointer here if the model takes ownership?

2019-07-31 07:46 UTC, gemmaguest commented
@LolloB Could you quickly re-test this to make sure it still works after the recent changes? Then I'll merge it.

2019-08-01 08:37 UTC, BassoLorenzo approved these changes
Works well on MantidPlot and Workbench for Ubuntu 18.04

2019-08-01 08:38 UTC, gemmaguest approved these changes

2019-08-01 08:38 UTC, merged