Workbench: ISIS Reflectometry pause button is disabled on opening
mantidproject/mantid pull request #26445
Opened 2019-07-22 12:58 UTC by PhilColebrooke

**Description of work.**
The pause button in the ISIS Reflectometry interface is now disabled when the interface is first opened, and becomes enabled when processing is started.

**To test:**
1. Open Workbench -> Interfaces -> ISIS Reflectometry.
2. The pause button should be disabled.
3. Begin processing. Example numbers: Run number 13460 Angle 0.05, Run number 13463 Angle 0.05. (set instrument to INTER).
4. The pause button should become enabled. Try pausing and unpausing to ensure the button becomes enabled and disabled correctly.

Fixes #26394 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-22 13:51 UTC, Pasarus requested changes
Could you add a test to ensure that it is disabled on start?

2019-07-22 14:37 UTC, Pasarus submitted a review, later dismissed

2019-07-23 13:26 UTC, gemmaguest commented
I think it might be better to do this via the presenter so we can test it. I'll come over to chat about it.

2019-07-24 16:23 UTC, gemmaguest approved these changes
Thanks for the changes. Looks good now and behaves as expected :+1: :+1:. Happy to merge when tests pass.

The code has been written in a way to make testing easy but tests don't exist yet for the main window and it's beyond the scope of this PR to add them, so we agreed that this would be done later as part of #26025

2019-07-25 08:49 UTC, DanNixon commented on qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
> +  void reductionPaused() override;
@gemmaguest I know it's unrelated and low priority, but the naming of these functions imply they are getters (i.e. `reductionPaused()` would return a `bool` indicating if the reduction was paused).

A better name might be `notifyReductionPaused()`, etc.

2019-07-25 08:49 UTC, merged