JSON Geometry Parser for Nexus-style Geometry
mantidproject/mantid pull request #26491
Opened 2019-07-25 13:52 UTC by LamarMoore

**Description of work.**

This PR concerns the implementation of a geometry parser for the Nexus kafka stream. The geometry will be in JSON format having the nexus file structure  (and classes) superimposed. 

**To test:**

- Through code review
- Ensure unit tests are sensible and pass.
- Ensure performance test is passes and performance is acceptable.

Fixes #26213 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-07-26 07:08 UTC, matthew-d-jones requested changes
It looks like you are handling the "pixel_shape" case but not the "shape" case, where the geometry describes the entire instrument component. Let me know if there is not an example of that in the file I gave you.

I've also added some comments for minor improvements that could be made to the code.

2019-07-26 07:08 UTC, matthew-d-jones commented on Framework/TestHelpers/src/JSONGeometryParserTestHelper.cpp
> +    values.resize(size);
Casting `size`, could use `size_t` as function arg or static_cast here.

2019-07-26 07:08 UTC, matthew-d-jones commented on Framework/TestHelpers/src/JSONGeometryParserTestHelper.cpp
> +  if (values.size() > 0) {
`empty`

2019-07-26 14:00 UTC, OwenArnold requested changes

2019-08-01 14:28 UTC, LamarMoore commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  if (std::is_same<T, std::int64_t>::value)
We aren't at C++ 17 yet. Will look into the `enable_if`

2019-08-02 11:53 UTC, LamarMoore commented on Framework/TestHelpers/src/JSONGeometryParserTestHelper.cpp
> +    for (uint32_t i = 0; i < values.size(); ++i)
Can't. It breaks. I think the `operator[]` is resulting in the construction of an `Json::ArrayType`. When I take a reference to a `null` Json object and resize nothing happens. Might be a bug.

2019-08-02 14:19 UTC, OwenArnold commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  if (std::is_same<T, std::int64_t>::value)
No, only c++14, though Martyn et al are working on getting c++17 support.

2019-08-12 10:48 UTC, OwenArnold requested changes
Looking good. Few outstanding minorish changes IMHO.

2019-08-12 10:48 UTC, OwenArnold commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +    return false;
I'm not sure you should do it in this PR, but this seems like the information you might want to log. I changed `NexusGeometryParser` recently to allow logging via the `Kernel::Logger` maybe you could do the same thing here.

2019-08-12 10:48 UTC, OwenArnold commented on Framework/NexusGeometry/test/JSONGeometryParserTest.h
> +
Testing looks thorough 👍  for performance tests 👍  for so many destructive test cases

2019-08-12 10:48 UTC, OwenArnold commented on Framework/NexusGeometry/src/NexusGeometryParser.cpp
> +const H5G_obj_t DATASET_TYPE = static_cast<H5G_obj_t>(1);
These are unused?

2019-08-13 06:44 UTC, LamarMoore commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  Json::Value item;
`std::find_if` breaks things. Not sure why:
```cpp
  if(entry.empty())
      return Json::Value();
  
  auto item = std::find_if(
      entry.begin(), entry.end(), [&NXAttribute](const auto &child) {
        auto attributes = child[ATTRIBUTES];
        return (!attributes.isNull() &&
                 validateNXAttribute(attributes, NXAttribute));
      });
  return *item;
```

2019-08-13 06:49 UTC, LamarMoore commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +    throw std::invalid_argument("Could not find dependency in json provided.");
Not sure I understand the question.

2019-08-13 07:02 UTC, LamarMoore commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  if (children.isNull())
Check is necessary but there is a better way to do it.

2019-08-13 07:18 UTC, OwenArnold commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  Json::Value item;
```return *item``` won't be safe unless you can guarantee that the item will be found. `item` could be `entry.end()`

2019-08-13 09:44 UTC, LamarMoore commented on Framework/NexusGeometry/src/JSONGeometryParser.cpp
> +  Json::Value item;
In that case won't `*item` return an empty `Json::Value`?

2019-08-13 12:45 UTC, matthew-d-jones approved these changes
Looks good to me, I can't spot any issues with the parsing now. It should be easier to spot any problems once we can ingest the JSON via Kafka and check things look correct in the instrument view.

2019-08-13 12:53 UTC, OwenArnold approved these changes

2019-08-13 13:27 UTC, merged