Add tests for parsing search results to reflectometry GUI
mantidproject/mantid pull request #26517
Opened 2019-07-29 17:24 UTC by gemmaguest

This PR adds unit tests for constructing and parsing the search results for the ISIS Reflectometry GUI. It moves the code to do the parsing into the `SearchResult` class from the `RunsPresenter`.

**To test:**

Code review and ensure unit tests pass

Refs #26512

*This does not require release notes* because **it concerns testing only**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-01 10:44 UTC, NickDraper commented
This has moved around some GUI code so it needs some manual testing as well.  Please add some instructions into the to test section.

2019-08-01 10:47 UTC, NickDraper reviewed
Code review is good, just needs some manual testing as well

2019-08-01 10:57 UTC, gemmaguest commented
> This has moved around some GUI code so it needs some manual testing as well. Please add some instructions into the to test section.

@NickDraper I've added the instructions

2019-08-01 13:11 UTC, NickDraper commented
This all works fine

2019-08-01 13:11 UTC, NickDraper submitted a review, later dismissed

2019-08-01 21:07 UTC, quantumsteve requested changes
Can we avoid temporary strings or are there lifetime issues?

2019-08-01 21:07 UTC, quantumsteve commented on qt/scientific_interfaces/ISISReflectometry/GUI/Runs/SearchResult.cpp
> +
Should these 6 member function instead return `const std::string &`, which better matches the argument for ([QString::fromStdString]https://doc.qt.io/qt-5/qstring.html#fromStdString)?

2019-08-02 13:29 UTC, quantumsteve approved these changes

2019-08-02 13:29 UTC, merged