Add main window tests for reflectometry GUI
mantidproject/mantid pull request #26510
Opened 2019-07-29 11:23 UTC by gemmaguest

This PR adds missing unit tests for the MainWindowPresenter in the ISIS Reflectometry GUI.

It also includes a minor fix where there was a typo causing an incorrect notification function to be called. Fortunately this did not cause a bug because currently the two notification functions both end up calling the same underlying function to update the widget state.

**To test:**

Code review, and ensure unit tests pass

Fixes #26498 	

*This does not require release notes* because **it concerns unit testing only**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-06 07:55 UTC, dtasev requested changes
Just a small change on one of the includes.

Overall really good - I really like the style of moving expectations/assertions into functions, it makes the tests read like a little story! It's something I'll incorporate into my future unit tests too

2019-08-06 10:13 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowView.h
> +#include "GUI/Batch/IBatchPresenterFactory.h"
Ah, that is weird - thanks for that, would have taken me a while to work that one out!

2019-08-06 10:24 UTC, DTasev commented
Some merge conflicts have also appeared

2019-08-13 13:25 UTC, gemmaguest commented
@DTasev The conflicts are fixed and it's finally compiling - the move constructor and assignment operator also needed moving to the cpp file

2019-08-13 14:56 UTC, dtasev approved these changes
Tests finally compile and no merge conflicts! LGTM

2019-08-14 07:51 UTC, merged