Multi data set fitting in indirect data analysis GUI
mantidproject/mantid pull request #26524
Opened 2019-07-31 09:45 UTC by mantid-roman

**Description of work.**

Replaced the fit property browser in the indirect data analysis interface with the refactored FunctionBrowser supporting both single and multi data set fitting.

**To test:**

Fixes #22055

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-02 16:01 UTC, alicerussell1 requested changes
I've started going through some of the fitting files (mainly just looked at one tab so I could follow what was going on). They look good and what you've done makes sense. The one thing I did notice was large parts of code are commented out instead of removed, I assume this is because you were referring to it when doing other parts but now it probably needs to go as it will be confusing in future.

I've gone though: IndirectFitData.cpp , ConvFit.cpp, ConvFit.h, ConvFitDataPresenter.cpp, ConvFitDataPresenter.h, ConvFunctionModel.cpp, ConvFunctionModel.h, ConvFitDataTablePresenter.cpp, ConvFitDataTablePresenter.h, ConvFitModel.cpp, ConvFitModel.h

2019-08-05 09:14 UTC, robertapplin requested changes
I have looked through most of the files, and the changes look very good. Same as Alice, I noticed that large parts of the code are commented out. Are these to be removed, or are they yet to be re-implemented?

I had a few other minor comments below, however the changes made look very good.

2019-08-05 09:14 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/IqtFit.cpp
> +  // setSampleWSSuffices({"_iqt"});
I believe these can be removed completely

2019-08-05 09:14 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/JumpFitModel.cpp
> +std::pair<std::vector<std::string>, std::vector<IDAWorkspaceIndex>>
what is the difference between an `IDAWorkspaceIndex` and a `WorkspaceIndex`?

2019-08-06 06:48 UTC, AnthonyLim23 commented
When @robertapplin and @alicerussell1 are happy with the code I will test the non-indirect fitting

2019-08-13 07:07 UTC, AnthonyLim23 commented
@robertapplin could we have a chat about this PR later today?

2019-08-27 14:03 UTC, mantid-builder commented
@mantid-roman the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-08-29 07:54 UTC, AnthonyLim23 commented
file conflicts

2019-10-01 06:40 UTC, AnthonyLim23 commented
@Mantid-Matthew can we close this PR as we are splitting it up?

2019-10-18 14:03 UTC, mantid-builder commented
@mantid-roman there are conflicts here, can you resolve them.
<!-- {"problem_type": "conflicting"} -->

2019-10-18 14:03 UTC, mantid-builder commented
@mantid-roman the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2019-10-24 15:48 UTC, NickDraper commented
Removing the milestone as this is not ready, put it back if this is urgent for R4.2

2019-10-24 15:50 UTC, AnthonyLim23 commented
this has been split up by @Mantid-Matthew into smaller PR's so I am closing this

2019-11-05 08:24 UTC, closed without merging