Indirect Use new plotting widget
mantidproject/mantid pull request #26522
Opened 2019-07-30 12:59 UTC by robertapplin

**Description of work.**
This PR replaces the old plotting widgets seen on the Indirect interfaces. Instead, a new widget is used which is tested and will improve interface consistency.

**To test:**

Fixes #26511

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-05 14:08 UTC, BassoLorenzo submitted a review, later dismissed
Everything works as intended.

2019-08-06 08:46 UTC, BassoLorenzo submitted a review, later dismissed
The changes look good and everything works.

2019-08-07 10:08 UTC, robertapplin commented
@mantidproject/gatekeepers Please could we get this merged? It is holding up progress on two Indirect PRs

2019-08-07 10:54 UTC, gemmaguest requested changes
Looks good, just one use of `move` that looks like it shouldn't be there?

2019-08-07 10:54 UTC, gemmaguest commented on qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
> +      std::move(m_uiForm.ipoPlotOptions), this, PlotWidget::Spectra, "0");
Is the `std::move` required here?

2019-08-07 10:59 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
> +      std::move(m_uiForm.ipoPlotOptions), this, PlotWidget::Spectra, "0");
Good spot, it was accidental! 😃

2019-08-07 11:34 UTC, BassoLorenzo approved these changes
The interface works as intended

2019-08-07 12:31 UTC, gemmaguest approved these changes

2019-08-07 12:32 UTC, merged