Add a namespace for the ISISReflectometry GUI
mantidproject/mantid pull request #26548
Opened 2019-08-02 08:27 UTC by gemmaguest

This PR adds a namespace for the ISISReflectometry GUI. Recent changes mean the classes for this GUI now have short names, so this namespace will ensure we won't clash with other GUIs.

Refs #26535

**To test:**

- Code review and ensure tests till pass
- Check that the ISIS Reflectometry GUI still opens

*This does not require release notes* because **it concerns file tidying only**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-05 09:18 UTC, DTasev commented
Some merge conflicts have popped up

2019-08-05 10:08 UTC, dtasev requested changes
Changes look good, locally compiles and tests all pass. Some merge conflicts have popped up

2019-08-12 08:50 UTC, DTasev commented
Rebuilding Windows build as Git failed to pull the changes in [#31920](https://builds.mantidproject.org/job/pull_requests-windows/31920/console)

2019-08-12 09:34 UTC, DTasev commented
Windows passed but a merge conflict is now back 😲

2019-08-12 11:54 UTC, dtasev approved these changes
Moves Reflectometry files inside the `ISISReflectometry` namespace. :shipit:

2019-08-12 14:52 UTC, DanNixon commented on qt/scientific_interfaces/ISISReflectometry/Common/Clipboard.cpp
> +  if (!MantidQt::CustomInterfaces::ISISReflectometry::isGroupLocation(
You shouldn't need the `MantidQt::CustomInterfaces::ISISReflectometry::` here since it's already in that namespace.

2019-08-12 14:52 UTC, merged