Elemental Analysis color function now returns same color for same element
mantidproject/mantid pull request #26561
Opened 2019-08-05 13:00 UTC by LolloB

Changed function `get_color` to always returned the first unused colour in matplotlib default colour cycle.
If all are used then it will return the least used one.
Every plotted element is assigned a colour and always plotted with it. This prevents the same element from having two colours in different plots.

**To test:**
1. `Interface->Muon->Elemental Analysis`
2. Load a run (eg `2695`)
3. Plot multiple elements on multiple plots

Fixes #26431.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-05 14:28 UTC, dtasev requested changes
Really good change! I can see the enormous benefits of having the same color among all plots, it makes it much easier to follow. Just a few comments

2019-08-05 14:28 UTC, DTasev commented on scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
> +    # Return the first unused colour, if all used then restart from the beginning of the cycle
Could this be moved inside the function, and made into a [Python docstring](https://www.python.org/dev/peps/pep-0257/#id17)? Please also add a `:param element` in it that describes what that parameter is used for

2019-08-05 14:28 UTC, DTasev commented on scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
> +        occurrences = []
```suggestion
        occurrences = [self.used_colors.values().count('C{}'.format(i)) for i in range(self.num_colors)]
```
This seems clearer to be, but maybe I've done too much Python recently. If you choose to go this way this makes the 2 lines underneath unnecessary

2019-08-05 14:28 UTC, DTasev commented on scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
> +        color_index = min([int(col[1:]) for col in color_list])
```suggestion
        color_index = occurrences.index(min(occurrences))
```
I think this does the same, the `color_list` line can then be deleted

2019-08-05 16:18 UTC, AnthonyLim23 commented
could you either add a test here or merge this into the test PR and add them there?

2019-08-07 12:29 UTC, DTasev commented
I've made this dependent on #26446 as all of the test commits are from there and they shouldn't be merged before the test PR is in. When that's merged this will need a rebase

2019-08-07 16:52 UTC, AnthonyLim23 commented on scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
> +        if (not isinstance(element, str)) and (not isinstance(element, unicode)):
we can use a function again like the test PR

2019-08-12 08:49 UTC, dtasev approved these changes
Good addition! Works well and has tests

2019-08-12 09:25 UTC, merged