26582 overlay plots in tf asymmetry mode
mantidproject/mantid pull request #26583
Opened 2019-08-07 14:17 UTC by Mantid-Matthew

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-07 15:58 UTC, AnthonyLim23 commented on Framework/Muon/src/CalculateMuonAsymmetry.cpp
> +    extractSpectra->setProperty("WorkspaceIndex", 2);
```suggestion
    extractSpectra->setProperty("WorkspaceIndex", 1);
```

2019-08-07 15:59 UTC, AnthonyLim23 commented on Framework/Muon/src/CalculateMuonAsymmetry.cpp
> +    appendSpectra->setProperty("InputWorkspace2", unnormalisedFit);
a lot of this looks like it should be in a function

2019-08-07 17:24 UTC, AnthonyLim23 commented on Framework/Muon/src/CalculateMuonAsymmetry.cpp
> +    normWS->mutableY(0) = ws->y(0) / norms[j];
I think we should split off the workspace transform into its own function and we can call it twice. Then when we fix the missing constant we just need to edit one place.

2019-08-08 09:52 UTC, AnthonyLim23 requested changes
code looks good, need to test it

2019-08-08 09:52 UTC, AnthonyLim23 commented on Framework/Muon/src/CalculateMuonAsymmetry.cpp
> + * Adds a normalised fit asthe last spectra in the fitted workspace.
```suggestion
 * Adds a normalised fit as the last spectra in the fitted workspace.
```

2019-08-08 12:30 UTC, AnthonyLim23 submitted a review, later dismissed

2019-08-08 14:32 UTC, martyngigg commented
@AnthonyLim23 If you're happy with this still I can merge it once the builds pass.

2019-08-08 15:58 UTC, martyngigg approved these changes

2019-08-08 15:59 UTC, merged