Added tests for elemental analysis data file
mantidproject/mantid pull request #26638
Opened 2019-08-14 09:35 UTC by LolloB

Added tests to check that data file do not contain obviously wrong data (eg. negative mass) and are formatted correctly.
This includes:
 - having all peak types assigned to an element (see  #26430)
 - ensuring each element has an entry for `A`, `Z`, `Primary`, `Secondary`
 - ensuring at least one element has an entry for `Gammas`, `Electrons`

**To test:**

- Code review
- Check that the test pass with the default data file
- Modify the values of some peaks to negative ones, it should fail
- Add an entry for a non existing element, it should fail
- Remove `Pb->Electrons`, it should fail
- Remove one of `A`, `Z`, `Primary`, `Secondary` from any element, it should fail

Fixes #26593.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-28 14:03 UTC, mantid-builder commented
@LolloB it may be worth bringing this PR to attention for review.
<!-- {"problem_type": "unreviewed"} -->

2019-08-29 12:57 UTC, Harrietbrown requested changes
It all looks very good and the tests work fine. Just two small changes.

2019-08-29 12:57 UTC, Harrietbrown commented on scripts/test/Muon/elemental_analysis/peak_data_file_test.py
> +
There are a lot of unused import here, only import what you are using.

2019-08-29 12:57 UTC, Harrietbrown commented on scripts/test/Muon/elemental_analysis/peak_data_file_test.py
> +
It is good to have this in your tests so they can be ran independantly.

```suggestion


if __name__ == "__main__":
    unittest.main()

```

2019-08-29 13:57 UTC, Harrietbrown submitted a review, later dismissed
This works well, good job.

2019-08-29 18:42 UTC, martyngigg commented
@LolloB There are a few merge conflicts after merging #26432. Could you rebase, please?

2019-08-30 09:24 UTC, Harrietbrown approved these changes
Conflicts fixed, everything good.

2019-08-30 11:19 UTC, merged