Adding markers to workbench plots
mantidproject/mantid pull request #26666
Opened 2019-08-19 12:16 UTC by LolloB

**Description of work.**
This PR adds vertical and horizontal markers to the plots in Workbench.

**To test:**
Code review.

1. Open a plot in workbench
2. `right click->Markers->Horizontal/Vertical`, a green dashed line should appear with label `marker 0`
3. Add more markers, the names should increase progressively (i.e. `marker 0`, `marker 1` etc.)
4. Hover the cursor over one, the cursor should become an open hand
5. Click and drag, the cursor should become a closed hand. The label should disappear and the marker should move.
6. Release the marker, the label should appear again in the correct position
7. Pan/Zoom, the label should always be in the correct position
8. Hover the cursor over a marker and right click.
9. `marker 0->Edit`, an edit window will pop up
10. Adjust the position and change the name, the marker should move and the label should be updated
11. Right click again
12. `<name>->Delete`, marker and label should disappear
13. Now add a vertical and horizontal marker
14. Hover above the intersections and drag them. They should both move
15. Right click above the intersection. Now there should be 2 menu, one for each marker.

Fixes #26657.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-20 09:43 UTC, Harrietbrown commented
A couple of things I've found

1. On horizontal lines if the marker label is too long it trails off the side of the plot, the vertical marker doesn't have this issue, you should make it so that the marker text on the horizontal line is aligned right so it can't trail off.
1. The range that you can drag the vertical line is different to the range that the mouse changes. So you can hover over the vertical line with the open hand mouse button but not be able to drag and drop
1. Double clicking to open the editing window where two lines cross over opens both in sequence, not sure if that is the best way to handle it.
1. On the open hand cursor the pointer bit is in the centre, so it's not always clear where to position the mouse for the crossover point (I hope that makes sense).
1. If you change marker label into something with two separate words ("foo bar") it raises an error when it expects the second word to be convertible to an int.

2019-08-21 09:02 UTC, Mantid-Matthew commented
I've had a look at this and in general is working really well. I have a few minor comments though.
  * When I tried this in python3 I ran into a few errors, this seems to be the standard thing of dict.keys() returning an iterator not a list like it does in python2
  * We are trying to not offer options in menus e.c.t. unless they are strictly needed, is there a specific use case where the import export options are required to be on the menu?
  * There seems to be an odd interaction with the save to png option whereby all the markers even ones I had previously deleted were saved producing a plot like the below
![test2](https://user-images.githubusercontent.com/32058966/63418292-c4a68b00-c3fa-11e9-8226-caa9717aae32.png)

2019-08-21 09:09 UTC, Mantid-Matthew commented on qt/applications/workbench/workbench/plotting/figureinteraction.py
> +        self.valid_colors = {'blue': 'C0', 'orange': 'C1', 'green': 'C2', 'red': 'C3', 'purple': 'C4'}
Just as a code style thing could we define these as constants at the top of the file.

2019-08-21 09:35 UTC, Mantid-Matthew commented on qt/applications/workbench/workbench/plotting/figureinteraction.py
> +            action.setCheckable(True)
Out of curiosity why do we need to set the action as checkable here?

2019-08-21 09:40 UTC, Mantid-Matthew commented on qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
>          self._test_toggle_normalization(errorbars_on=False, plot_kwargs={'distribution': True})
Could we add some tests to do with adding and removing markers from the plot?

2019-08-21 09:43 UTC, Matthew-Andrew requested changes
In general looks really good and the new functionality works really nicely :+1: I've added a few comments above but in general great job.

2019-08-22 11:51 UTC, Matthew-Andrew submitted a review, later dismissed
I'm now happy with this. Seems to work really nicely good job :+1:

2019-08-22 20:10 UTC, martyngigg requested changes
This is a really great addition.

I only have one comment that I would prefer we address now. We have been trying to get better at ensuring that the method/function documentation exists and is up to date. Can we make sure that all of the new methods have documentation and that any methods/functions that have been changed have their docs updated?

2019-08-22 20:11 UTC, martyngigg commented
It also looks like we have a conflict now. Can we rebase with master?

2019-08-23 13:01 UTC, martyngigg commented
This looks good. Thanks. Just a documentation warning left.

2019-08-23 13:03 UTC, martyngigg commented on docs/source/workbench/plotwindow.rst
> +- set the axes' scales to linear or logarithmic.
The formatting here doesn't look quite right here as this is not formatted as a list. I think you just need a blank line between the line first line with the `-` and the previous line.

2019-08-23 15:30 UTC, martyngigg requested changes

2019-08-23 15:30 UTC, martyngigg commented on docs/source/workbench/plotwindow.rst
> -- set the axes' scales to linear or logarithmic.
Sorry to be picky. We need a single blank line above this line or the list is formatted as pre-formatted block (note the line down the left-hand side):
![Screenshot from 2019-08-23 16-22-53](https://user-images.githubusercontent.com/733773/63604277-3df0da00-c5c3-11e9-935c-53dc1a19e2fd.png)

2019-08-27 07:54 UTC, martyngigg approved these changes

2019-08-27 14:33 UTC, martyngigg commented
OSX failure is unrelated. Documentation warnings are fixed in #26712 after move to Ubuntu 18.04 on PR builds.

2019-08-27 14:33 UTC, merged