ReflectometryReductionOneAuto code tidied
mantidproject/mantid pull request #26707
Opened 2019-08-23 12:24 UTC by giovannidisiena

**Description of work.**
- `RebinParams` class simplified
- Replaced `catch (...)` with check to see if workspace exists
- Made west const consistent
- Refactored duplicated transmission run code in `validateInputs` into a function

**To test:**
Do a code review

Closes #26499 

*This does not require release notes as there is no change in functionality*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-09-06 14:03 UTC, mantid-builder commented
@giovannidisiena have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2019-09-26 16:12 UTC, gemmaguest requested changes
Code changes look good :+1: Just a minor suggestion for the new test. We should also do some manual testing as this PR makes changes to functional code. Could you have a think about what would be good to test based on the code that is touched? My first thought is to test with/without polarisation corrections - a good run for that is `44956` with angle `0.4` and transmission run `44937`.

2019-10-02 10:59 UTC, giovannidisiena commented
@gemmaguest I have update the workspace naming however I am not too sure about the functional testing, may be worth discussing later 🙂

2019-10-02 12:40 UTC, giovannidisiena commented
Tests pass for me locally on Windows however I get this on the Ubuntu VM... any idea as to why @gemmaguest?

![RROA3_test_fail](https://user-images.githubusercontent.com/22510773/66044691-0b1ef780-e51a-11e9-93fa-28856512768e.png)

2019-10-02 13:01 UTC, gemmaguest commented
> Tests pass for me locally on Windows however I get this on the Ubuntu VM... any idea as to why @gemmaguest?
> 
> ![RROA3_test_fail](https://user-images.githubusercontent.com/22510773/66044691-0b1ef780-e51a-11e9-93fa-28856512768e.png)

It may be that the processing instructions are for a spectrum that isn't a valid detector. Although if that's the case I'm surprised it works on Windows.

2019-10-15 10:25 UTC, gemmaguest requested changes
Just a couple more suggestions for simplifications

2019-10-15 10:25 UTC, gemmaguest commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
>      RebinParams(const double qMin, const bool qMinIsDefault, const double qMax,
You can simplify this further by removing the constructor - it isn't required if you use an initializer list when you create an instance (e.g. see [here](https://docs.microsoft.com/en-us/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=vs-2019)).

2019-10-15 10:25 UTC, gemmaguest commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
>      double m_qMin;
I think it's a more common convention to drop the `m_` prefix for public members - it makes it more readable when using them.

2019-10-22 15:07 UTC, gemmaguest submitted a review, later dismissed
Code changes look good and the interface still functions as expected - rebinning to specified Q values works as does slicing and polarization correction :+1:

2019-10-23 07:07 UTC, DanNixon requested changes
Looks good, just a couple of minor comments.

2019-10-23 07:07 UTC, DanNixon commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +  void getTransRun(std::map<std::string, std::string> &results,
```suggestion
  void getTransmissionRun(std::map<std::string, std::string> &results,
```

There is no real need to abbreviate this here.

2019-10-23 07:07 UTC, DanNixon commented on Framework/Algorithms/src/ReflectometryReductionOneAuto3.cpp
> +    auto transGroup =
```suggestion
    auto transmissionGroup =
```

2019-10-23 08:06 UTC, giovannidisiena commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +    bool hasQStep() const { return qStep.is_initialized(); }
Could you explain this for me please?

2019-10-23 08:09 UTC, DanNixon commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +    bool hasQStep() const { return qStep.is_initialized(); }
`boost::optional` (and `std::optional` for when we can use that) have `operator bool`. This allows conversion to `bool` when appropriate.

In the case of `optional` this returns if the optional has a value. The fact it is being returned from a function with a return type of `bool` indicates that `operator bool` should be used here.

2019-10-23 08:16 UTC, giovannidisiena commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +    bool hasQStep() const { return qStep.is_initialized(); }
Thank you!

2019-10-23 09:30 UTC, giovannidisiena commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +    bool hasQStep() const { return qStep.is_initialized(); }
@DanNixon now getting this error, any ideas?

`error: cannot convert ‘const boost::optional<double>’ to ‘bool’ in return`

2019-10-23 09:43 UTC, DanNixon commented on Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
> +    bool hasQStep() const { return qStep.is_initialized(); }
No idea. That should work. Just keep it as it was for now.

2019-10-23 11:56 UTC, DanNixon approved these changes

2019-10-23 11:56 UTC, merged

2019-10-23 11:57 UTC, DanNixon commented
@giovannidisiena Maybe you could try and teach people how to tidy commits in the manner you did for the last three in this PR.

I've been fighting a losing battle trying to get people to actually do this.