Updates on workbench markers
mantidproject/mantid pull request #26727
Opened 2019-08-29 13:06 UTC by LolloB

**Description of work.**
 - The name of the marker can no longer be left empty
 - The name of the markers cannot be duplicated
 - An option is added to make the name visible/invisible
 - An option is added to make the marker draggable or not
 - Label positions can be modified

**To test:**
1. Open a plot
2. Add a marker, try to name it "", an error should appear
3. Create a second marker and give it the same name as the first. An error should appear
4. Check option `Fix position`, the marker cannot be dragged (but the position can be changed from the edit window)
5. Uncheck `Display label`, the marker label should disappear
6. Change the marker name and check `Display label`. The new label should appear.
7. Change the label position. The label should move.

Fixes #26724, #26725

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-08-29 13:10 UTC, AnthonyLim23 commented on qt/applications/workbench/workbench/plotting/propertiesdialog.py
> +            raise RuntimeError("Marker names cannot be duplicated.\nAnother marker is named '{}'"
```suggestion
            raise RuntimeError("Marker names cannot be duplicated.\n Another marker is named '{}'"
```

2019-08-29 13:12 UTC, AnthonyLim23 commented on qt/applications/workbench/workbench/plotting/propertiesdialog.py
> +        self.markers = sorted(markers, key=lambda x: x.name)
can we have a better name then x?

2019-08-29 13:16 UTC, AnthonyLim23 commented on qt/python/mantidqt/plotting/markers.py
> +            y_pos = self.relative(self.marker.y, y_lower, y_upper) + self.label_y_pos
it took me a while, but is `self.label_y_pos` actually the offset from the y position?

2019-08-29 14:17 UTC, AnthonyLim23 commented
open a tiled plot (with at least two subplots), add markers to the top left subplot (this is fine). When you use the context menu on the another subplot the lines are added to the first subplot

2019-08-30 06:59 UTC, AnthonyLim23 commented
just had a look and it now adds to the correct subplot. However, I can edit any marker from any subplot. Even if that marker is not on the current subplot. Is this an intended feature?

2019-08-30 10:13 UTC, AnthonyLim23 submitted a review, later dismissed
:shipit:

2019-08-30 14:58 UTC, martyngigg requested changes

2019-08-30 14:58 UTC, martyngigg commented on qt/applications/workbench/workbench/plotting/propertiesdialog.py
> +    def __init__(self, filename, valid_style, valid_colors, used_names=[]):
It is not best practice to use [mutable objects as defaults](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) in Python. Can we follow the standard guidance as suggested on the guide and use `None`?

2019-09-02 17:02 UTC, AnthonyLim23 commented
@martyngigg are you happy with this?

2019-09-03 07:17 UTC, martyngigg commented
Sorry I missed that the update had happened. I'm happy now.

2019-09-03 07:17 UTC, martyngigg approved these changes

2019-09-03 07:17 UTC, merged