SaveNexusESS
mantidproject/mantid pull request #26734
Opened 2019-08-30 17:12 UTC by OwenArnold

Fixes #26557.

**WIP DO NOT MERGE THIS**

At this stage, just checking things will work cross-platform and where they won't or which instruments are problematic..

2019-09-10 10:13 UTC, DanNixon requested changes
Works as expected, detector positions and mappings are preserved over a save-load cycle.

2019-09-10 10:17 UTC, OwenArnold commented on Framework/NexusGeometry/src/NexusGeometrySave.cpp.orig
> +// Mantid Repository : https://github.com/mantidproject/mantid
Thanks removed now.

2019-09-10 10:32 UTC, DanNixon approved these changes

2019-09-11 07:12 UTC, OwenArnold commented
@mantidproject/gatekeepers would be good to get this merged asap.

2019-09-11 08:07 UTC, merged