S(Q, w) table checks
mantidproject/mantid pull request #26784
Opened 2019-09-11 13:44 UTC by ciaranightingale

**Description of work.**
https://docs.mantidproject.org/nightly/algorithms/SofQWNormalisedPolygon-v1.html#algm-sofqwnormalisedpolygon now has validateInputs function to check that the table is of the correct form (int, double, double), that the input workspace is of the correct type and that the table and workspace have the same number of detectors. 

**To test:**

The following script should create an invalid table and should be caught at the validate inputs stage. If we run the algorithm from the GUI then it would give the red star next to the table.
`import numpy as np

# Create Table to hold detector angular range
IRIS_PG_Det = CreateEmptyTableWorkspace()

# Calculate range for PG detectors on IRIS
no_det = int(51)
det_start = int(3)
detIDList = [i+det_start for i in range(no_det)]
angle_start = np.radians(25.)
angle_end = np.radians(160.)
angles = np.linspace(angle_start, angle_end, no_det+1, endpoint = True)
min = angles[:-1]
max = angles[1:]

# Add some columns, Recognized types are: int,float,double,bool,str,V3D,long64
IRIS_PG_Det.addColumn(type="int",name="Detector ID")
IRIS_PG_Det.addColumn(type="int",name="Min two theta")
IRIS_PG_Det.addColumn(type="double",name="Max two theta")

# Populate the columns for three detectors
for i,j in enumerate(detIDList):
    IRIS_PG_Det.addRow ([j, i, max[i] ] )`

Fixes #26637 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-09-13 06:57 UTC, AnthonyLim23 commented on Framework/Algorithms/test/SofQWNormalisedPolygonTest.h
> +   * @param types A vector of strings of the data types of the columns
would the name `dataType` be clearer?

2019-09-13 06:58 UTC, ciaranightingale commented on Framework/Algorithms/test/SofQWNormalisedPolygonTest.h
> +   * @param types A vector of strings of the data types of the columns
already done!

2019-09-17 15:22 UTC, AnthonyLim23 commented
@ciaranightingale you have left in the diff comments as part of your last commit.

2019-09-18 10:11 UTC, AnthonyLim23 submitted a review, later dismissed
:shipit: once builds pass

2019-09-18 11:42 UTC, AnthonyLim23 submitted a review, later dismissed
:shipit:

2019-09-18 13:06 UTC, DanNixon requested changes
Looks good :+1:, just a couple of comments.

2019-09-18 13:06 UTC, DanNixon commented on Framework/Algorithms/src/SofQWNormalisedPolygon.cpp
> +  if (tableWS) {
This block can be simplified slightly.

The `return` in the first `if` can be removed and the following `if`s converted to `else if`.

It only makes sense to assign `result["DetectorTwoThetaRanges"]` once.

2019-09-18 13:06 UTC, DanNixon commented on docs/source/release/v4.2.0/indirect_geometry.rst
> +- :ref:`SofQWNormalisedPolygon <algm-SofQWNormalisedPolygon>` now has a function to check the the input properties are valid.
Was this done? It still mentions "function".

Perhaps something like "... now checks input properties are valid"?

2019-09-19 16:20 UTC, AnthonyLim23 commented
the error messages have changed.

2019-09-23 07:02 UTC, AnthonyLim23 commented
@ciaranightingale you still need to push the changes

2019-09-24 12:05 UTC, DanNixon commented
Unless there is some actual change to be made can the last two commits please be removed. They simply add and remove a back quote.

2019-09-25 08:31 UTC, DanNixon requested changes

2019-09-25 08:31 UTC, DanNixon commented on docs/source/release/v4.2.0/indirect_geometry.rst
> +- :ref:`SofQWNormalisedPolygon <algm-SofQWNormalisedPolygon>`now checks input properties are valid.
```suggestion
- :ref:`SofQWNormalisedPolygon <algm-SofQWNormalisedPolygon>` now checks input properties are valid.
```

2019-09-25 11:57 UTC, DanNixon approved these changes

2019-09-25 11:57 UTC, merged