Add StretchedKT to fit functions
mantidproject/mantid pull request #26822
Opened 2019-09-18 15:00 UTC by hankwustfc

Description of work.

Add StretchedKT to Mantid fit functions.

To test:

1.Test if the documentation is added
2.Test if the fit function is working
3.Test the function with the unit test file

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-09-18 16:35 UTC, AnthonyLim23 commented
release notes will be #26827

2019-09-18 16:38 UTC, AnthonyLim23 commented on docs/source/fitting/fitfunctions/StretchedKT.rst
> +.. math:: A(t)=A_0\left(\frac13+\frac23\left(1-(\sigma t)^\beta\right)e^{-\frac{(\sigma t)^\beta}{\beta}}\right)
the `frac13` etc will not work

2019-10-07 14:18 UTC, NickDraper requested changes

2019-10-07 14:18 UTC, NickDraper commented on docs/source/fitting/fitfunctions/StretchedKT.rst
> +.. figure:: /images/StretchedKT.png
This should be replaced by a plot call

2019-10-08 09:22 UTC, NickDraper approved these changes

2019-10-08 09:22 UTC, NickDraper commented
code test and docs ok

2019-10-08 09:22 UTC, merged