Updated Function Browser and related files
mantidproject/mantid pull request #26865
Opened 2019-09-24 12:48 UTC by Mantid-Matthew

**Description of work.**

This is the changes from #26524 related to the core fitting framework and not the IndirectFitting GUI

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-09-25 12:02 UTC, alicerussell1 requested changes
This looks good, the interfaces that use the function browser all seem to still work the same as before. Just a couple of comments about the code

2019-09-25 12:24 UTC, Mantid-Matthew commented on qt/widgets/common/src/FunctionBrowser.cpp
> +      setLocalParameterValue(name, static_cast<int>(i),
I don't think there is no.

2019-09-26 10:13 UTC, Mantid-Matthew commented on qt/widgets/common/test/FunctionMultiDomainPresenterTest.h
> +  void setParameterConstraint(const QString &, const QString &) override {}
As this function does nothing in the mock adding names to the parameters leads to unused variable compiler warnings.

2019-09-26 10:14 UTC, Mantid-Matthew commented on qt/widgets/common/src/FunctionBrowser/FunctionBrowserUtils.cpp
> +      double d1 = boost::lexical_cast<double>(expr[0].str());
I don't think so no. I've added some tests and this seems to fulfill it's purpose with the assignment removed so have removed it.

2019-09-26 10:29 UTC, alicerussell1 commented on qt/widgets/common/test/FunctionMultiDomainPresenterTest.h
> +  void setParameterConstraint(const QString &, const QString &) override {}
Ah I hadn't realized it was part of the mock, would it give warnings if you put commented out names like `/*name*/`?

2019-10-03 15:46 UTC, alicerussell1 approved these changes
This looks good to me 👍

2019-10-04 07:33 UTC, merged