SaveAscii: add possibility to save the values of the spectrum axis
mantidproject/mantid pull request #26874
Opened 2019-09-25 12:52 UTC by gvardany

**Description of work.**
It was requested that SaveAscii write also the spectrum axis value.
Although it already offers something like that (the input called `SpectrumMetaData`), it is limited to few observables like Q, etc.
This PR adds a new flag (not to intervene with the one above), that makes it write the spectrum axis values no matter of the axis type. For the `BinEdgeAxis` it computes on-the-fly the bin centre value.

**To test:**
Soon.

Fixes #26862  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-01 12:49 UTC, NickDraper requested changes
Most of this is good, but if you save out the ascii file like this it cannot be loaded back in using LoadAscii.  Can I suggest you improve LoadAscii so it can load these files back in.

This is the error you get from LoadAscii

```
LoadAscii started
Failed to read as ASCII this file: 'C:/Users/rrc79113/Desktop/test.dat, error description: bad lexical cast: source type value could not be interpreted as target
Error in execution of algorithm LoadAscii:
Failed to recognize this file as an ASCII file, cannot continue.

```

2019-10-15 06:38 UTC, gvardany commented
Good point, I will take care of that.

2019-10-30 13:41 UTC, NickDraper approved these changes
This works fine now

```
SaveAscii started
SaveAscii successful, Duration 2.35 seconds
LoadAscii started
LoadAscii successful, Duration 18.25 seconds
```

2019-10-30 14:45 UTC, DanNixon approved these changes

2019-10-30 14:45 UTC, merged