CreateDetectorTable algorithm for Workbench
mantidproject/mantid pull request #26988
Opened 2019-10-09 16:03 UTC by PhilColebrooke

**Description of work.**
This PR adds a new algorithm called CreateDetectorTable which takes a workspace as input and outputs a table workspace containing detector information for the inputted workspace. This means that the ability to right-click a workspace and select "Show Detectors" is now possible in Workbench.

**To test:**
* In Workbench and MantidPlot, load a workspace, right-click it, and select "Show Detectors". Check that the table which displays in Workbench contains the same values as the one in MantidPlot.
* In the list of algorithms, there should now be one under Utility->Workspaces called CreateDetectorTable. Open the dialog and check the following things:
    * The WorkspaceIndices field accepts a comma-separated list of workspace indices and only the ones inputted are added to the output table workspace. If the field is left blank, all workspace indices from the workspace are used.
    * When the IncludeData checkbox is ticked, the output table workspace has two additional columns, "Data Value" and "Data Error" which show the first value from each spectrum.
    * The table workspace created by the algorithm has whatever name is inputted in the DetectorTableWorkspace field, or if no input is given, the name of the input workspace with "-Detectors" added.

Fixes #26867 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-10 16:08 UTC, SpencerHowells commented
@PhilColebrooke The MantidPlot version also shows Q values for IndirectInelastic. Does this do it?

2019-10-11 07:42 UTC, PhilColebrooke commented
> @PhilColebrooke The MantidPlot version also shows Q values for IndirectInelastic. Does this do it?

The code for getting all the values for the table is lifted from MantidPlot so it should yes.

2019-10-11 16:02 UTC, martyngigg requested changes
Good so far but can we add a `CreateDetectorTable` unit test too? This was missing from MantidPlot as the code was inside the GUI.

2019-10-11 16:02 UTC, martyngigg commented
I just spotted the "Not Ready" label. Sorry for the early review if you already had the tests in hand...

2019-10-15 11:42 UTC, DanNixon commented
Could I also request a performance test. The detector table is painfully slow to build for large instruments as it is.

2019-10-24 15:33 UTC, Harrietbrown requested changes
Can we have it so that the context drop down when right clicking on a workspace has Show Detectors greyed out is the workspace has no SpectrumInfo, as is it raises a runtime error when showing detectors on an invalid workspace in Workbench.

2019-10-25 08:40 UTC, PhilColebrooke commented
@Harrietbrown Now attempting ShowDetectors on an invalid workspace will output the error to the log and there is no runtime error. If multiple workspaces are selected, detector tables will be created for the valid ones.

2019-10-28 11:01 UTC, Harrietbrown submitted a review, later dismissed

2019-10-28 11:01 UTC, Harrietbrown commented
Good work, well done.

2019-10-28 11:53 UTC, DanNixon requested changes

2019-10-28 11:53 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +ITableWorkspace_sptr CreateDetectorTable::createDetectorTableWorkspace(
This could be a free function.

It is also rather complex, it is possible to split this into logical subdivisions?

2019-10-30 12:38 UTC, DanNixon requested changes

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +  std::string truncated{""};
```suggestion
  std::string truncated;
```

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +                             const bool &include_data, Logger &logger) {
```suggestion
                             const bool include_data, Logger &logger) {
```

No need to pass `bool` (or any other POD types) by const reference.

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +  bool isScanning = ws->detectorInfo().isScanning();
```suggestion
  const bool isScanning = ws->detectorInfo().isScanning();
```

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +createColumns(const bool &isScanning, const bool &include_data,
Can pass by value here.

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/src/CreateDetectorTable.cpp
> +                   const bool &isScanning, const bool &include_data,
```suggestion
                   const bool &isScanning, const bool &includeData,
```

Naming conventions.

2019-10-30 12:38 UTC, DanNixon commented on Framework/Algorithms/inc/MantidAlgorithms/CreateDetectorTable.h
> +class DLLExport CreateDetectorTable : public API::Algorithm {
```suggestion
class MANTID_ALGORITHMS_DLL CreateDetectorTable : public API::Algorithm {
```

2019-10-30 14:33 UTC, DanNixon approved these changes

2019-10-30 15:26 UTC, martyngigg approved these changes

2019-10-30 15:39 UTC, merged