Remove SANSConv.ToWavelength and SANSScale
mantidproject/mantid pull request #26989
Opened 2019-10-10 10:36 UTC by DavidFair

**Description of work.**
Removes SANS ConvertToWavelength and SANSScale as part of the work fixing workspace history

Run the system and unit tests as following
- ctest -R SANS
- systemtest -R SANS

Process some SANS data:
- Download the ISIS training data from the project site
- Open the ISIS SANS GUI
- Open the LOQ folder and select the Mask file as the user file
- Open the batch file and select the CSV
- Hit process all

Fixes #26955   . 

*This does not require release notes* because this is part of an epic #26960 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-16 15:17 UTC, cailafinn requested changes
System, unit, and functional tests pass. Just a few code and documentation comments.

2019-10-17 08:50 UTC, DavidFair commented on dev-docs/source/ISISSANSReductionBackend.rst
> +- :ref:`Divide <algm-Divide>` (by Sample Volume)
No it's just coincidence as this is the order of algorithms executed. In later PRs we also break the fact it's alphabetic by chance

2019-10-17 15:55 UTC, DavidFair commented
I'll put these back into alphabetical order with a fixup PR into this branch, as the various PRs will modify them out of order again (added into the epic #26960 )

2019-10-17 16:05 UTC, cailafinn approved these changes
Code looks good, unit and system tests still passing locally. Approved.

2019-10-18 08:01 UTC, merged