output transformation matrix
mantidproject/mantid pull request #27003
Opened 2019-10-10 20:34 UTC by AndreiSavici

**Description of work.**

Returned the transformation matrix from `SelectCellOfType` and `SelectCellWithForm`

**Report to:** Xiaoping

**To test:**
Set your default facility/instrument to SNS/TOPAZ, then run

```python
ws=LoadIsawPeaks("TOPAZ_3007.peaks")
FindUBUsingFFT(ws,MinD=8.0,MaxD=13.0)
r=SelectCellOfType(PeaksWorkspace=ws, CellType='Monoclinic', Centering='C', Apply=True)
print(r.TransformationMatrix)
```
It should output the same transformation matrix as you see in the mantid logs.

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-11 06:38 UTC, AndreiSavici commented
Unrelated failure

2019-10-11 13:48 UTC, peterfpeterson requested changes

2019-10-11 13:48 UTC, peterfpeterson commented on Framework/Crystal/src/SelectCellOfType.cpp
> +  this->setProperty("TransformationMatrix", T.getVector());
The algorithm docs would benefit from explaining what this is.

2019-10-15 14:41 UTC, peterfpeterson approved these changes

2019-10-15 20:09 UTC, merged