26871 adsorbtion for isis inelastic
mantidproject/mantid pull request #27011
Opened 2019-10-12 18:18 UTC by abuts

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-15 17:10 UTC, mducle requested changes
Mostly spelling mistakes but there are some bits of the logic I didn't get...

2019-10-15 17:10 UTC, mducle commented on scripts/test/AbsorptionShapesTest.py
> +        #np.testing.assert_almost_equal(corr_ranges,[97,0.4504,0.0009],4)
Should these commented out lines be removed? I guess they're using the "fast" algorithm? Why not uncomment them and let them run?

2019-10-15 17:10 UTC, mducle commented on scripts/test/AbsorptionShapesTest.py
> +        #np.testing.assert_almost_equal(corr_ranges,[97,0.2984,0.0002],4)
Should these commented out lines be removed?

2019-10-15 17:10 UTC, mducle commented on scripts/test/AbsorptionShapesTest.py
> +        #np.testing.assert_almost_equal(corr_ranges,[97,0.6420,0.3997],4)
Should these commented out lines be removed?

2019-10-15 17:37 UTC, abuts commented on Testing/SystemTests/tests/analysis/ISIS_LETReduction.py
> +            Change adsorption corrections parameters below to achieve best speed and
Done

2019-10-16 09:57 UTC, abuts commented
Good remarks, I hope all addressed in number of recent commits. -- Have problems in commentig one by one in my browser

2019-10-16 12:36 UTC, mducle commented on Testing/SystemTests/tests/analysis/ISIS_MERLINReduction.py
> +      #
Discussed with AB, and decided to keep additional stubs in each instrument reduction file as is for documentation purposes.

2019-10-16 12:40 UTC, mducle approved these changes
Looks good to me now!

2019-10-17 11:01 UTC, merged