refs #26774 updated Muon GUI's to usage report and deprecation of old
mantidproject/mantid pull request #27082
Opened 2019-10-24 09:35 UTC by AnthonyLim23

**Description of work.**
This PR adds usage reporting to Muon Analysis, Elemental Analysis and Frequency Domain Analysis

It also renames the original Muon GUI and Muon Analysis 2.

**To test:**

Open MantidPlot
Open Muon Analysis (old) - it should be the original GUI
Open Muon Analysis - it should be the new GUI
Fixes #26774. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-24 09:50 UTC, NickDraper commented on scripts/Muon/GUI/Common/usage_report.py
> +def register_GUI(name):
Minor point but the function name here does not pass the ronseal test
Perhaps ReportInterfaceStartup(name)

2019-10-24 09:50 UTC, NickDraper commented on scripts/Muon_Analysis.py
> +Name = "Muon_Analysis"
Does this mean that the usage reports will be mixed with the old UI from previous versions?

We want the GUI menu items to take over the name, but internally for usage reports, we might want to keep them separate

2019-10-24 10:13 UTC, NickDraper requested changes
In Mantidplot your olds are not consistent
![image](https://user-images.githubusercontent.com/1017173/67475996-18c62980-f64f-11e9-9598-d7eb94fb3512.png)

Reflectometry just uses "Reflectometry Old" without any brackets

2019-10-24 10:37 UTC, NickDraper requested changes

2019-10-24 10:37 UTC, NickDraper commented on qt/scientific_interfaces/Muon/MuonAnalysis.h
> +  static std::string name() { return "Muon Analysis old)"; }
Did you mean to get rid of both brackets?

2019-10-24 10:37 UTC, NickDraper commented on qt/scientific_interfaces/Muon/MuonAnalysis.cpp
> +  arn;
Pretty sure this deletion was a mistake

2019-10-24 11:07 UTC, NickDraper commented on qt/scientific_interfaces/Muon/MuonAnalysis.cpp
> +  arn;
arn?

2019-10-24 15:55 UTC, NickDraper submitted a review, later dismissed

2019-10-24 15:56 UTC, NickDraper commented
All looks good now, ready for merging once the builds pass

2019-10-24 15:56 UTC, NickDraper commented
Flake8 needs some love

2019-10-24 15:57 UTC, AnthonyLim23 commented on scripts/Muon/GUI/Common/usage_report.py
> +    UsageService.registerFeatureUsage("Interface", name, False)
```suggestion
    UsageService.registerFeatureUsage("Interface", name, False)

```

2019-10-25 09:36 UTC, NickDraper submitted a review, later dismissed
Reapproving after the warnings were resolved.

2019-10-25 11:21 UTC, DanNixon requested changes

2019-10-25 11:21 UTC, DanNixon commented on scripts/Muon/GUI/Common/usage_report.py
> +def ReportInterfaceStartup(name):
```suggestion
def report_interface_startup(name):
```

This follows Python naming conventions.

2019-10-25 11:40 UTC, AnthonyLim23 commented on scripts/Elemental_Analysis.py
> +from Muon.GUI.Common.usage_report import ReportInterfaceStartup
```suggestion
from Muon.GUI.Common.usage_report import report_interface_startup
```

2019-10-25 11:43 UTC, AnthonyLim23 commented on scripts/Frequency_Domain_Analysis.py
> +from Muon.GUI.Common.usage_report import ReportInterfaceStartup
```suggestion
from Muon.GUI.Common.usage_report import report_interface_startup
```

2019-10-25 11:43 UTC, AnthonyLim23 commented on scripts/Muon_Analysis.py
> +from Muon.GUI.Common.usage_report import ReportInterfaceStartup
```suggestion
from Muon.GUI.Common.usage_report import report_interface_startup
```

2019-10-25 16:17 UTC, NickDraper approved these changes
Good to go I think, The final change addressed Dan's concerns as well

2019-10-28 07:59 UTC, DanNixon approved these changes
RIP well formed commit history

2019-10-28 08:00 UTC, merged