Load current run in muon analysis
mantidproject/mantid pull request #27106
Opened 2019-10-25 14:09 UTC by AnthonyLim23

**Description of work.**
The load current run button in (new) muon analysis should work. 

**To test:**
Open muon analysis 2
Click load current run
Should load some data (for ISIS instruments)

No associated issue 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-10-28 09:19 UTC, giovannidisiena requested changes
Functional testing passed, minor nitpick then ready to be approved

2019-10-28 09:19 UTC, giovannidisiena commented on scripts/test/Muon/utilities/load_utils_test.py
> +        filename = 'PSI'+os.sep + 'run_1529_templs0.mon'
```suggestion
        filename = 'PSI'+ os.sep + 'run_1529_templs0.mon'
```

2019-10-30 09:59 UTC, AnthonyLim23 commented
@giovannidisiena I think that I have fixed your comment.

2019-10-30 10:41 UTC, giovannidisiena approved these changes
:shipit:

2019-10-30 13:13 UTC, DanNixon commented on scripts/test/Muon/utilities/load_utils_test.py
> +        filename = 'PSI'+ os.sep + 'run_1529_templs0.mon'
A cleaner alternative here would have been `os.path.join`.

2019-10-30 13:14 UTC, merged