Add error setting states as a known issue for SANS GUI
mantidproject/mantid pull request #27215
Opened 2019-10-31 16:51 UTC by DavidFair

**Description of work.**
Adds a note to the release notes about each time a user clicks process a
warning about error setting states being emitted. This cannot be fixed
in time for the release, as it involves changing how states are
generated within the SANS GUI

I'm working on this at the moment, however it has the potential to break more as SANS State is very intertwined. Therefore I'd like to put this caveat in now in case it doesn't make the release, and remove it later otherwise.

**To test:**
- Read the documentation
- Build

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-01 09:15 UTC, Matthew-Andrew requested changes
Could we remove the warning at the top of the rst file concerning sorting changes? Otherwise this looks good to me.

2019-11-05 11:55 UTC, Matthew-Andrew requested changes
Code changes look good and the double error is gone. A few side issues however:

- If a run is not found this error is not propagated up correctly, i.e. does not turn the row blue e.c.t.
- The progress bar at the bottom of the gui does not reset correctly
- Should post loading be indicated by green which could imply reduced?
- If you delete some rows during processing you get an unhandled exception.

2019-11-05 12:03 UTC, DavidFair commented
@Mantid-Matthew Does these comments refer to this PR or #27239 ?

2019-11-07 14:47 UTC, DavidFair commented
Closing this as #27239 resolves the issue described in these release notes

2019-11-07 14:47 UTC, closed without merging