Move file loading and processing async in SANS
mantidproject/mantid pull request #27239
Opened 2019-11-01 16:45 UTC by DavidFair

**Description of work.**
Move file finding to be synchronous as we need the result before
processing or loading data. Instead we now run the load or process
method async within the worker to avoid blocking the main thread

**To test:**
- Using the LOQ data set:
- Attempt to load or process a data set
- An error previously would appear and pressing ok and process again would work
- Now it should process first time
- Try various combo's with load and process selected/all

Fixes #27216 .

*This does not require release notes* because this issue was introduced and resolved before a release

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-05 11:29 UTC, Mantid-Matthew commented on scripts/SANS/sans/gui_logic/models/batch_process_runner.py
> +            self.row_processed_signal.emit(None)
Elsewhere this signal is emitted with 3 arguments. Will it work being emitted with one here?

2019-11-05 12:51 UTC, Matthew-Andrew requested changes
Code changes look good and the double error is gone. A few side issues however:

-  If a run is not found this error is not propagated up correctly, i.e. does not turn the row blue e.c.t.
-  The progress bar at the bottom of the gui does not reset correctly
-  Should post loading be indicated by green which could imply reduced?
-   If you delete some rows during processing you get an unhandled exception.

2019-11-05 13:43 UTC, DavidFair commented
- If a run is not found this error is not propagated up correctly, i.e. does not turn the row blue e.c.t.
This should fixed
- The progress bar at the bottom of the gui does not reset correctly
Fixed

- Should post loading be indicated by green which could imply reduced?
I'm tempted to leave this to user feedback, as if it causes confusion (green = processed rather than finished doing) we can change it
- If you delete some rows during processing you get an unhandled exception.
I'm going to defer this to the next release, as there are multiple ways to delete a row during processing, so just stopping the buttons working will not prevent this happening.

2019-11-05 16:27 UTC, Matthew-Andrew requested changes
Looks good overall the failing to find a file is now notified properly :+1: 

If I add some rows click process all and the add some more rows and click process all the progress bar behaves strangely however often reaching zero early or increasing in odd increments.

2019-11-06 18:12 UTC, DavidFair commented
Good spot on the progress bar, I've added a fix and a unit test for this

2019-11-07 12:52 UTC, Matthew-Andrew approved these changes
Works for me now :+1:

2019-11-07 14:47 UTC, merged