27248 fix plotting multiple single spectra workspaces
mantidproject/mantid pull request #27258
Opened 2019-11-05 11:06 UTC by Harrietbrown

This PR fixes a bug that caused an error to be raised when trying to plot multiple single spectra workspaces with different spectra indexs. This fix works by adding a check in the function to check if there are no common spectra before attempting to open the `SpectraSelectionDialog`, if there are no common spectra it instead overplots all selected workspaces.

This fix is a simple fix but in future after the release sprint `SpectraSelectionDialog` should be modified to handle these cases. however that will be more complex than would be appropriate to include this late into the release. I will make an issue for that against the next release.

**To test:**
1. open workbench
1. open `GEM63437_focussed.nxs` from the tutorial date, this contains a group workspace of foccused data with different spectra numbers.
1. select seveal workspaces
1. right click, plot
1. an overplot of all selected workspaces should be produced

Fixes #27248

*This does not require release notes* because It is a new bug introduced in this release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-05 11:30 UTC, alicerussell1 commented
There seem to be a number of commits that aren't relating to this PR, I think this can be fix by rebasing you branch onto `release-next`

2019-11-05 13:05 UTC, alicerussell1 requested changes
This looks good, and works well for workspace with one spectra. I do get the same error when try to plot workspaces with multiple spectra but no spectra in common. I'm not sure exactly what behaviour you'd expect there but it would be good to at least get a helpful error message.

2019-11-05 13:48 UTC, alicerussell1 requested changes

2019-11-05 14:03 UTC, alicerussell1 submitted a review, later dismissed
This looks good 👍

2019-11-05 17:21 UTC, martyngigg requested changes
Can we add some tests for both of the new behaviours?

2019-11-05 17:27 UTC, martyngigg commented on qt/python/mantidqt/dialogs/spectraselectorutils.py
> +    ws_spectra = [{ws.getSpectrum(i).getSpectrumNo() for i in range(ws.getNumberHistograms())} for ws in workspaces]
I think in the case where all workspaces have a single spectrum then it is correct to simply overplot them all. Could we avoid this potentially expensive loop in that scenario?

2019-11-06 13:58 UTC, martyngigg approved these changes
Thanks for the tests. This looks good now. :+1:

2019-11-06 14:59 UTC, merged