Muon AlC interface crashes
mantidproject/mantid pull request #27264
Opened 2019-11-05 14:31 UTC by StephenSmith25

**Description of work.**
The ALCLatestFileFinder expected the instrument name be case-consistent, e.g EMU, or emu. If it was supplied with a file with an upper case detector name, e.g EMU00066666 from //emu/data it would crash. The crash was due to querying an empty vector, which now has a return check, on the off chance the underlying directory changes (e.g wiped).

**To test:**
To replicate the original issue

    Set the default instrument to EMU, and turn off the data archive
    Add the //emu/data directory to user directories. 
    Interfaces->Muon->ALC
    Enter 66666
    Tick auto
    Press Load
    Should no longer crash (although this operation takes a long time as it loads a large amount of files in //emu/data )

Fixes #27221 . 
#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-11 09:19 UTC, Harrietbrown requested changes
Can you add some tests for this behaviour.

2019-11-11 10:28 UTC, NickDraper commented
You could create a separate issue to add the tests as long as that is prioritised after the release.

2019-11-12 12:52 UTC, StephenSmith25 commented
> Can you add some tests for this behaviour.

I've added two unittests, which should capture the behavior I've fixed.

2019-11-12 13:07 UTC, Harrietbrown approved these changes
Tests added to cover new functionality, all pass. good work, its good that we can get this in.

2019-11-12 13:27 UTC, DanNixon commented on qt/scientific_interfaces/Muon/ALCLatestFileFinder.cpp
> +    // and retry disable the auto button
It's not important to fix this now, but could this have been worded a bit better.

The behavior described in the error condition is particular unclear (e.g. it mentions a button but this is not a view or presenter).

2019-11-12 13:28 UTC, merged