Load other facilities.xml if one fails
mantidproject/mantid pull request #27283
Opened 2019-11-06 11:56 UTC by NickDraper

read the first commit descriiton

Look at the issue in #26830 for instructions

Fixes #26830

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-06 17:08 UTC, cailafinn requested changes
A couple of things about code comments and about the last message not being included if all of the files are corrupted/don't work.

2019-11-06 17:08 UTC, ConorMFinn commented on Framework/Kernel/src/ConfigService.cpp
> +            "able to start, Sorry.  Try reinstalling Mantid.");
Since this error seems to be swallowed by the error reporter, it may be worth explicitly sending this message to the log.

2019-11-07 11:42 UTC, cailafinn submitted a review, later dismissed
Code looks good and gives much more useful output. Approved.

2019-11-07 12:23 UTC, martyngigg requested changes
While we are changing this code, that we are unlikely to touch again for a while can we modernize things a bit? `emplace_back` over `push_back` with temporaries and `const` where we can to encourage its use elsewhere.

2019-11-07 12:23 UTC, martyngigg commented on Framework/Kernel/src/ConfigService.cpp
> +    std::string fileName = fileNames[attemptIndex];
```suggestion
    const auto& fileName = fileNames[attemptIndex];
```

2019-11-07 12:23 UTC, martyngigg commented on Framework/Kernel/src/ConfigService.cpp
> +      size_t n = pNL_facility->length();
```suggestion
      const size_t n = pNL_facility->length();
```

2019-11-07 12:23 UTC, martyngigg commented on Framework/Kernel/src/ConfigService.cpp
> +      Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
```suggestion
      const Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
```

2019-11-07 12:23 UTC, martyngigg commented on Framework/Kernel/src/ConfigService.cpp
> +        auto *elem = dynamic_cast<Poco::XML::Element *>(pNL_facility->item(i));
```suggestion
        const auto *elem = dynamic_cast<Poco::XML::Element *>(pNL_facility->item(i));
```

2019-11-07 12:23 UTC, martyngigg commented on Framework/Kernel/src/ConfigService.cpp
> +          m_facilities.push_back(new FacilityInfo(elem));
```suggestion
          m_facilities.emplace_back(new FacilityInfo(elem));
```

2019-11-07 16:04 UTC, martyngigg approved these changes
This looks good to me now.

2019-11-08 09:34 UTC, merged