Fix crash when setting max cores in properties lower than machine cores on Linux
mantidproject/mantid pull request #27343
Opened 2019-11-11 15:42 UTC by ConorMFinn

If the maximum number of cores mantid can use is set to be lower than the number of cores on the machine, certain algorithms would ignore this limit and run extra threads.

As a result, workspaces that were not created with this higher number of threads (created in the main thread) would cause a seg fault when the algorithm attempted to access an index of a vector that was out of range.

The root cause of the issue is that threads created separately from the main one do not keep the value set in the `mantid.user.properties` file for the max number of cores. Since this could cause issues in other areas, fixing this will be delayed until the next release. 

**To test:**

1. Interfaces -> Indirect -> Data Reduction -> ISIS Energy Transfer
2. Enter a valid run number (26184)
3. Click Run
4. S(Q, w) tab
5. Select the workspace just created
6. Click run
7. No crash should occur

Fixes #27158

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-11-12 10:51 UTC, DanNixon reviewed
I'm half tempted to put the additional thread count set into the macros in `MultiThreaded.h`. There could well be other scenarios this is affecting (possibly the issue I was looking at with Q1D).

2019-11-13 08:37 UTC, ConorMFinn commented
> I'm half tempted to put the additional thread count set into the macros in `MultiThreaded.h`. There could well be other scenarios this is affecting (possibly the issue I was looking at with Q1D).

The resetting of the thread to the config value? Should that be added as part of this PR?

2019-11-13 11:52 UTC, DanNixon commented
> > I'm half tempted to put the additional thread count set into the macros in `MultiThreaded.h`. There could well be other scenarios this is affecting (possibly the issue I was looking at with Q1D).
> 
> The resetting of the thread to the config value? Should that be added as part of this PR?

Yes, that is what I meant to suggest. In hindsight that was not clear.

2019-11-13 16:44 UTC, ConorMFinn commented
I keep getting build failures on mac and windows when working with the MultiThreaded macros. I've made an issue to do this as maintenance: #27375

2019-11-14 09:22 UTC, DanNixon requested changes
Happy with the fix given there is little time to much else.

2019-11-14 09:22 UTC, DanNixon commented on Framework/Algorithms/src/SofQWNormalisedPolygon.cpp
> +    */
Could you add a `#TODO` here with a link to the new issue you created.

2019-11-14 09:32 UTC, DanNixon approved these changes
:shipit:

2019-11-14 11:45 UTC, merged