Make Improvements to the Engineering Diffraction 2 GUI
mantidproject/mantid pull request #27519
Opened 2019-11-28 16:59 UTC by ConorMFinn

**Description of work.**
A few changes have been made to the code and functionality of the engineering diffraction GUI. 

-  Vanadium run files are also saved to the user directories.
- Focus outputs now include `.gss`, `.dat`, and `.nxs` files.
- The user is provided with more status information, such as when the GUI is searching for files.
- Similar plots for multiple banks are shown as tiled plots.
- Refactored current calibration into separate class.
- Added Documentation for focusing tab
- Made Ceria/Calib variables consistent, now using "`sample`"

**To test:**
1. Open Eng Diff GUI.
2. Click the calibrate button while the GUI is searching for files. 
2. Create a new calibration with "Plot Output" ticked (V: 307521 Sample: 305738)
3. Check similar Plots appear in the same figure. 
1. Check documentation is up to date. 
0. Go to the focus tab and focus a run (305761)
11. Check that all 3 file types have been generated. 

Fixes #27189 

*This does not require release notes* because **users have not had access to this GUI yet.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-12-09 13:17 UTC, Harrietbrown commented
When focussing i am getting an error `omp_set_num_threads should only be called in serial regions`.
Should that be comp_set_num_threads?

2019-12-09 15:33 UTC, Harrietbrown requested changes
I missed it before but along with the `omp_set_num_threads` error message there is also a `omp_set_dynamic should only be called in serial regions` message when focussing.

2019-12-09 15:33 UTC, Harrietbrown commented on scripts/Engineering/gui/engineering_diffraction/tabs/common/vanadium_corrections.py
> +    :param rb_number:
rb_number should have a summery

2019-12-09 15:33 UTC, Harrietbrown commented on scripts/Engineering/gui/engineering_diffraction/tabs/common/vanadium_corrections.py
>      :param vanadium_number: The number of the vanadium run.
rb_num should be added to the paramiter list. Also for consistency you should have rb_number or rb_num in both functions

2019-12-09 15:33 UTC, Harrietbrown commented on scripts/Engineering/gui/engineering_diffraction/tabs/focus/model.py
> +        Save a focused workspace to the file system. Saves a separate copies to a User directory if an rb number has
```suggestion
        Save a focused workspace to the file system. Saves separate copies to a User directory if an rb number has
```

2019-12-11 10:09 UTC, Harrietbrown submitted a review, later dismissed
Is the error message from `omp_set_num_threads` and `omp_set_dynamic` being handled in a different issue?

2019-12-11 10:48 UTC, ConorMFinn commented
> Is the error message from `omp_set_num_threads` and `omp_set_dynamic` being handled in a different issue?

Hm, I don't get that message locally. So I thought it was solved after the rebase. I'll look into it.

2019-12-11 11:02 UTC, Harrietbrown commented
did you get it when you were first running it?

2019-12-11 11:15 UTC, ConorMFinn commented
I can't be sure, I did the rebase before looking at the suggestions. It isn't currently happening when I do `test-pr` either. So I'm guessing it's a windows thing.

2019-12-11 11:18 UTC, Harrietbrown commented
I figured it would be if you hadn't noticed it before.

2019-12-12 10:45 UTC, ConorMFinn commented
> 
> 
> I figured it would be if you hadn't noticed it before.

This issue appears to be caused by the `SaveGSS` algorithm. I can remove that funcionality, or leave it in and accept the error appearing until that algorithm is fixed. What do you think is the best solution?

2019-12-12 10:49 UTC, Harrietbrown commented
In this case I would remove the functionality and put in a TODO, we don't want a bit error box that will mess up any other PRs you make untill you fix it. Best to fix it before it gets merged.

2019-12-12 11:21 UTC, ConorMFinn commented
> 
> 
> In this case I would remove the functionality and put in a TODO, we don't want a bit error box that will mess up any other PRs you make untill you fix it. Best to fix it before it gets merged.

Issue for this created at #27582

2019-12-16 15:16 UTC, Harrietbrown approved these changes
Good that the saveGSS has been sorted out. Good job.

2019-12-17 16:13 UTC, merged