Prevent units that are not suitable from being used in convertunits
mantidproject/mantid pull request #27547
Opened 2019-12-04 17:13 UTC by NickDraper

re #27458

**Description of work.**
Ensures that the target unit validator only lists "convertible units

**To test:**

Fixes #27458. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-12-12 09:26 UTC, DanielMurphy22 requested changes
Drop down menu for Convert Units works fine and the list of units on ConvertUnits.html in the docs is now correct. Just need to take them out of the ConvertUnitsUsingDetectorTable algorithm

2019-12-12 14:40 UTC, DanielMurphy22 submitted a review, later dismissed

2019-12-12 14:40 UTC, DanielMurphy22 commented
Looks good!

2019-12-12 14:57 UTC, DanNixon requested changes

2019-12-12 14:57 UTC, DanNixon commented on Framework/Kernel/inc/MantidKernel/UnitFactory.h
> +    for (auto unitKey : getKeys()) {
```suggestion
    for (const auto &unitKey : getKeys()) {
```

2019-12-12 14:57 UTC, DanNixon commented on Framework/Kernel/inc/MantidKernel/UnitFactory.h
> +      auto unit_sptr = create(unitKey);
```suggestion
      const auto unit_sptr = create(unitKey);
```

2019-12-27 14:03 UTC, mantid-builder commented
@NickDraper could you review the feedback left on this PR and make changes as appropriate
<!-- {"problem_type": "ignored_review"} -->

2020-01-06 12:56 UTC, merged

2020-01-06 12:59 UTC, DanNixon commented
Didn't realise we could merge our own unapproved PRs.

Top notch review process...

2020-01-06 14:23 UTC, NickDraper commented
On this one the only change was your two suggested changes

2020-01-06 14:28 UTC, DanNixon commented
And fixing the shit commit history.