Add normalize by bin width option for sliceviewer
mantidproject/mantid pull request #27560
Opened 2019-12-09 13:21 UTC by alicerussell1

**This PR cannot be merged until #27468**

**Description of work.**
This PR adds the option to normalize by bin width for matrix workspaces in slice viewer. In mantidplot this was done in the spectrum viewer by rebinning the data. This instead normalises the data by dividing it by the bin width.

**To test:**
See issue for detailed example.

Fixes #27359 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-12-10 11:14 UTC, Harrietbrown requested changes
The curves are able to be normalized by bin width and it all works as expected. Some minor changes. 

I have noticed that the range on the curves do not autoscale, because of this and the monitor curve being so much larger than any other, you need to manualy scale the plot to be able to see them. Is there an issue for this already?

2019-12-12 11:01 UTC, alicerussell1 commented
I've rebased this onto master as it included some of the commits from the earlier PR that has now been merged. For the autoscaling there is a tick box which if selected it should do the autoscaling and when you normalise it should change the scale.

2019-12-12 11:01 UTC, alicerussell1 commented on qt/applications/workbench/workbench/plotting/figureinteraction.py
> +        on the figure are either distributions or non-distributions
This has been changed in the earlier PR that this was based off so it should be correct now I've rebased it.

2019-12-12 11:01 UTC, alicerussell1 commented on qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
> +        model = SliceViewerModel(self.ws_MDE_3D)
They are two different workspaces but I intended to do them as separate tests so I've changed it

2019-12-13 10:27 UTC, Harrietbrown commented
It does change the scale when rebinning, the issue I was talking about rescaling the curves when moving the mouse over the colourplot like it does in sliceviewer in Mantidplot.

2019-12-17 10:22 UTC, Harrietbrown approved these changes
The issue with the curve not rescaling is unrelated to this PR so no reason to hold it back for that. Good work.

2019-12-17 14:53 UTC, merged