Upgrade hdf5 windows
mantidproject/mantid pull request #27570
Opened 2019-12-11 07:43 UTC by LamarMoore

**Description of work.**

Following an upgrade of `hdf5` for the windows platform [here](https://github.com/mantidproject/thirdparty-msvc2015/tree/upgrade-hdf5). The following changes were made to address compatibility issues with ESS nxs files.

**The changes to the thirdparty repo need to be merged before this PR is merged**

**To test:**

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-12-13 09:54 UTC, OwenArnold requested changes
Doesn't pinpoint issue, but a few changes suggested

2019-12-13 09:54 UTC, OwenArnold commented on Framework/DataHandling/src/LoadEventNexus.cpp
> +        } catch (std::runtime_error &) {
Why would this fail?

2019-12-13 09:54 UTC, OwenArnold commented on Framework/NexusGeometry/src/NexusGeometryParser.cpp
> +      tbb::parallel_sort(detectorIds.begin(), detectorIds.end());
Could probably use a comment about why you do this.

2019-12-13 09:54 UTC, OwenArnold commented on Framework/Types/src/Core/DateAndTime.cpp
>      DateAndTime::GPS_EPOCH(boost::gregorian::date(1990, 1, 1));
I know this wan't you, but I think the GPS_EPOCH above is wrong. GPS epoch 5th Jan 1980. Just a note, shouldn't really affect anything, but might cause confusion for future maintainers.

2019-12-13 09:54 UTC, OwenArnold commented on Framework/Kernel/inc/MantidKernel/NexusDescriptor.h
> +  static bool findAndOpenParentGroup(::NeXus::File &file,
The name of the function doesn't quite fit the description. Would imply opening the parent of some current with existing naming. `findAndOpenFirstChild`?

2019-12-20 17:01 UTC, martyngigg commented
While implementing the Python 3 builds for Windows I based my branch of just the HDF5 upgrade from the 3rd party. As far as I can tell the tests that fail here *do not* fail for me so I think the failing tests here are due to the other changes.

Could we possibly spin out the HDF5 upgrade only stuff to a separate PR?

2019-12-23 07:39 UTC, martyngigg commented
Just as a note. I've started doing to the Python 3 work and I based the changes off the HDF5 1.10 upgrade in 3rd party but **not** with these changes. The above tests seem to pass there so I don't think it is an issue with the HDF5 libraries. Would it be possible to spin out just the HDF5 upgrade to a separate PR?

2019-12-24 10:16 UTC, martyngigg commented
As discussed with Owen on Slack we decided that we should separate out the HDF5 upgrade and ESS compatibility changes as there are still issues with the latter. The HDF5 upgrade was merged in #27645 and #27646 now contains the other changes from this branch. The new branch is `ess-nexus-compat`.

Closing this as everything should now be on the aforementioned branch.

2019-12-24 10:17 UTC, closed without merging