Rename ALFView files and restructure
mantidproject/mantid pull request #27577
Opened 2019-12-11 16:28 UTC by AnthonyLim23

**Description of work.**
The file and varaible names for ALF view were not very good. This PR improves them, they now follow the coding standards. I have also moved the common functionality to a more readily available part of Mantid. 

**To test:**
Open Mantid
Go to custom interfaces -> Direct -> ALF view
An interface should apper
In the run box type `80511` and press enter
Wait a little while and an updated instrument should appear in the GUI
Go to the pick tab
Select the `tube` option
Change the subplot from the pick tab to integrate (right click)
Change the axis to `out of plane angle` (right click)
On the instrument view, right click above a bright spot and select `export tube`
A plot should appear on the far right of the GUI
You should be able to press the fit button and it will do a fit.

Fixes #26904. 

Does not need to be in release notes, this is a maintenance task, 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2019-12-18 16:03 UTC, cailafinn requested changes
Just a couple of missed things, passes functional tests.

2019-12-18 16:42 UTC, AnthonyLim23 commented on qt/scientific_interfaces/Direct/ALFCustomInstrumentModel.h
>  #ifndef MANTIDQT_CUSTOMINTERFACES_ALFVIEWMODEL_H_
```suggestion
#ifndef MANTIDQT_CUSTOMINTERFACES_ALFCUSTOMINSTRUMENTMODEL_H_
```

2019-12-18 16:43 UTC, AnthonyLim23 commented on qt/scientific_interfaces/Direct/ALFCustomInstrumentModel.h
>  #define MANTIDQT_CUSTOMINTERFACES_ALFVIEWMODEL_H_
```suggestion
#define MANTIDQT_CUSTOMINTERFACES_ALFCUSTOMINSTRUMENTMODEL_H_
```

2019-12-18 16:49 UTC, AnthonyLim23 commented on qt/widgets/instrumentview/CMakeLists.txt
> +					 MantidQtWidgetsPlotting
```suggestion
                     MantidQtWidgetsPlotting
```

2020-01-02 14:03 UTC, mantid-builder commented
have you had a chance to see why the build is failing?
<!-- {"problem_type": "failing"} -->

2020-01-06 14:25 UTC, cailafinn approved these changes
Looks good to me now. Code looks much better and the GUI still passes its functional tests. :+1:

2020-01-08 07:09 UTC, AnthonyLim23 commented
@mantidproject/gatekeepers could we please merge this PR?

2020-01-08 07:10 UTC, merged