Add options dialog to Reflectometry GUI [PART 1]
mantidproject/mantid pull request #27655
Opened 2020-01-06 10:51 UTC by giovannidisiena

**Description of work.**
This PR is **1** of **_**.

The options dialog model has been created and some work has been done to create a generic QSettings helper. This will affect the existing IndirectSettings and so someone should check that this still functions as expected.

**To test:**
Complete a code review, full manual testing instructions will follow when subsequent PRs are merged.

Partially resolves #26533

*This does not require release notes* because **they will be added in a subsequent PR**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-01-15 15:25 UTC, cailafinn requested changes
Looks good so far, just a couple of typos and comments.

2020-01-15 15:25 UTC, ConorMFinn commented on qt/widgets/common/inc/MantidQtWidgets/Common/QSettingsHelper.h
> +      settingTypeName = settings.value(settingName).toString().toStdString();
`settingTypeName` looks like it could be defined here, avoiding creating the string object if it does not end in `"/type"`

2020-01-15 15:25 UTC, ConorMFinn commented on qt/widgets/common/inc/MantidQtWidgets/Common/QSettingsHelper.h
> + *  as QVariant types are not properly encoded inini files
```suggestion
 *  as QVariant types are not properly encoded in ini files
```

2020-01-15 15:25 UTC, ConorMFinn commented on qt/widgets/common/inc/MantidQtWidgets/Common/QSettingsHelper.h
> +#endif /* MANTID_INDIRECTSETTINGSHELPER_H */
```suggestion
#endif /* MANTID_QSETTINGSHELPER_H */
```

2020-01-15 15:25 UTC, ConorMFinn commented on qt/scientific_interfaces/ISISReflectometry/GUI/Options/OptionsDialogModel.cpp
> +void OptionsDialogModel::loadSettings(std::map<std::string, bool> &boolOptions,
Personally, I'm not a fan of using out arguments like this. Though I understand the reasoning as you have two maps to work with.

2020-01-22 13:49 UTC, cailafinn submitted a review, later dismissed
This looks good to me now. Good work :+1:

2020-01-22 14:46 UTC, gemmaguest commented
Is it worth tagging this as Not Ready until the other PRs are merged?

2020-01-23 13:29 UTC, giovannidisiena commented
> This looks good to me now. Good work 👍

Thanks @ConorMFinn, merging #27656 dismissed your review so may be worth waiting until the end to have another once-over

2020-02-28 14:36 UTC, gemmaguest commented
@giovannidisiena Could you ensure that the full manual testing instructions are ready for when part 6 is merged?

2020-02-28 16:06 UTC, gemmaguest commented
This bug seems to have got back in: Batch is incorrectly marked as unsaved after processing a row (when state has changed but no content in the table has actually changed)

2020-03-02 08:58 UTC, giovannidisiena commented
> This bug seems to have got back in: Batch is incorrectly marked as unsaved after processing a row (when state has changed but no content in the table has actually changed)

Think it got back in via a rebase, should be gone now!

2020-03-12 11:03 UTC, giovannidisiena commented
Reminder: this PR will likely need to updating due to #28200, #28320, #28279 and #27061

2020-03-27 09:34 UTC, gemmaguest commented
@giovannidisiena Have you seen the conflicts on this? Is it ready, otherwise?

2020-03-27 11:13 UTC, giovannidisiena commented
@gemmaguest yes but for some reason not authorised to resolve them... and not quite, need to do a little but of updating as per the maintenance PRs above.

2020-04-20 13:23 UTC, giovannidisiena commented
@gemmaguest this is now up to date with the changes introduced by maintenance issues.

2020-04-21 17:28 UTC, gemmaguest requested changes
The reflectometry side of things now all looks good and everything is working as expected 🎉 

We should also test the Indirect interface(s) that use the settings helper. Do you know how/what to test here? I guess it is the `Interfaces->Indirect->Settings` dialog. Unfortunately if I change the settings and close and re-open this dialog it doesn't remember the changes, which looks like a regression.

2020-04-23 10:09 UTC, giovannidisiena commented
@gemmaguest I just tested this on `5.0` and it seems that if you re-open the settings dialog soon after closing then the settings are 'remembered', otherwise given an amount of time they will be reset. I introduced the first use of `QSettingsHelper` into the indirect code in this PR so it doesn't seem like a regression to me, maybe more an issue of the underlying code which is handling those settings once they are returned?

2020-04-23 10:15 UTC, giovannidisiena commented
@gemmaguest the other reason for this may the new format I used to save the settings due to .ini file encoding, which means that you probably need to clear the existing settings `plot-error-bars-external` and `restrict-input-by-name`...

2020-04-23 12:27 UTC, giovannidisiena commented
@gemmaguest sorry for the spam of ideas, to me it looks like this code is overriding any changes to the `restrict input data by name` option...

https://github.com/mantidproject/mantid/blob/87284a6b7b914d2fa2518a1492e80bda129dc4d1/qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp#L35-#L42

2020-04-23 12:30 UTC, giovannidisiena commented
@gemmaguest sorry for the spam of ideas, to me it looks like this code is overriding any changes to the `restrict input data by name` option:

https://github.com/mantidproject/mantid/blob/87284a6b7b914d2fa2518a1492e80bda129dc4d1/qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp#L34-#L42

2020-04-28 11:34 UTC, gemmaguest commented
> 
> 
> @gemmaguest sorry for the spam of ideas (and GH messing up), to me it looks like this code is overriding any changes to the `restrict input data by name` option:
> 
> [/qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp@`87284a6`#L34-#L42](https://github.com/mantidproject/mantid/blob/87284a6b7b914d2fa2518a1492e80bda129dc4d1/qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp#L34-#L42)

That's good to know - looks like there's also a minor bug with this default setting where this bit of code sets the default to true in the file when you open the dialog, but does not update the view so it remains unchecked... But if you then close and re-open the dialog then it is shown as checked as per the file...

However, testing with the other setting it works as I expect in master - whatever is in the file is reflected on the GUI when you open it. But I can't get it to work on this PR's branch, regardless of whether I remove the old format settings from the file or not. The new format setting is written correctly to the file, but when I re-open the dialog it does not pick it up. Playing around with the file contents, it looks like what is actually happening is that it is still reading from the old setting format even though it is writing to the new setting format??

2020-04-28 12:35 UTC, giovannidisiena commented
@gemmaguest that's strange, I'm not sure how/why it doesn't read from the new format if the old one is removed as the group name hasn't changed. In any case, this part is slightly outside the scope of this PR so could be left to someone who understands the .ini file/indirect interface better if they decide they want to use it...

2020-05-04 15:53 UTC, gemmaguest commented
The Indirect settings are working again :+1:

Could you add release notes? (They seem to have disappeared in the last force-push because they were in Muon for some reason!)

2020-05-11 08:57 UTC, gemmaguest approved these changes
Thanks for adding the release notes. This all looks good now :+1:

2020-05-12 15:19 UTC, merged