Fixes for reflectometry workflow algorithms history
mantidproject/mantid pull request #27697
Opened 2020-01-10 17:59 UTC by gemmaguest

**Description of work.**
To follow

**Report to:** Jos

**To test:**

To follow

Fixes #27633 

Release notes to follow

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-19 08:07 UTC, giovannidisiena requested changes
This looks good to me so far but there are a lot of changes here so might be worth having a second reviewer.

2020-02-19 16:22 UTC, gemmaguest commented on qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/ProcessingAlgorithm.h
> +                      QString const &blacklist = "", const int version = -1);
Normally I'd agree, but the `-1` is the convention used in the algorithms so this just passes it directly through.

2020-02-19 16:23 UTC, gemmaguest commented
I'm just going to rebase on master and update the release notes

2020-02-20 10:41 UTC, gemmaguest commented
> This looks good to me so far but there are a lot of changes here so might be worth having a second reviewer.

This doesn't touch any core components so I think the normal gatekeeper review should be fine. Note that the data processor code that has been changed is not currently used anyway! The PR does have the potential to break reflectometry scripts but scientists are aware of that and I will be pushing heavily for them to beta test it.

2020-02-20 15:57 UTC, gemmaguest commented
I'll take a look at the conflicts

2020-02-20 16:37 UTC, giovannidisiena commented
Having some problems with my archive so going to clear my assignment to allow someone else to do functional testing.

2020-02-21 09:10 UTC, gemmaguest commented
> Having some problems with my archive so going to clear my assignment to allow someone else to do functional testing.

@giovannidisiena The files in the ISIS sample data should be sufficient so you shouldn't need the archive?

2020-02-21 10:12 UTC, giovannidisiena approved these changes
All appears good to me :shipit:

2020-02-21 14:01 UTC, NickDraper commented
Final build failure was just network connectivity with the build slave

2020-02-21 14:02 UTC, merged