Removing vms_compat depdencey from LoadISISNexus
mantidproject/mantid pull request #27707
Opened 2020-01-14 11:50 UTC by StephenSmith25

**Description of work.**

To load the new Muon Nexus files (V2) the LoadISISNexus2 loader will be utilised. In order to use this loader, the dependence of the LoadISISNexus2 on the isis_vms_compat was removed in this PR. Primarily this PR extracts a number of functions into a set of helper functions and cleans up the LoadISISNexus2 code.

**Still left to do:**
Find an alternative location for gd_prtn_chrg and total_prtn_chrg
Some functions in the LoadISNexus2 class should be free functions

**To test:**

Fixes #27695 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-11 14:03 UTC, mantid-builder commented
@StephenSmith25 do you want to request a review on this PR?
<!-- {"problem_type": "unreviewed"} -->

2020-03-20 14:03 UTC, mantid-builder commented
@StephenSmith25 the build is failing, can you investigate.
<!-- {"problem_type": "failing"} -->

2020-05-06 14:05 UTC, NickDraper commented
@stephen, I've got two emu nxs_v2 files will these do for the muon tests?
- EMU00101521.nxs_v2
- EMU00103738.nxs_v2

2020-05-06 14:09 UTC, StephenSmith25 commented
> 
> 
> @StephenSmith25 , I've got two emu nxs_v2 files will these do for the muon tests?
> 
>     * EMU00101521.nxs_v2
> 
>     * EMU00103738.nxs_v2

Yeah, those should do, I've been testing it with EMU00103638.nxs_v2.

2020-05-06 15:24 UTC, NickDraper commented
Ok I ran a full ws comparison and it didn't quite match, we have some missing sample logs
![image](https://user-images.githubusercontent.com/1017173/81194315-6c2d1300-8fb4-11ea-88fe-da2a59061daf.png)


Missing:

dmp
dmp_freq
dmp_units
dur
dur_freq
dur_secs
dur_wanted
durunits
mon_sum1
mon_sum2
mon_sum3
run_header

Admittedly I'm not sure if any of these are important.

``` python 
wsRaw = mtd["LOQ49886"]
wsB4 = mtd["LoadISISBefore"]
raw_log_names = []
run = wsRaw.run()
for log in run.getLogData():
    raw_log_names.append(log.name)
    
    
b4_log_names = []
run = wsB4.run()
for log in run.getLogData():
    b4_log_names.append(log.name)

print("Missing:\n")
for name in b4_log_names:
    if name not in raw_log_names:
        print(name)
        
        
print("\nAdded:\n")
for name in raw_log_names:
    if name not in b4_log_names:
        print(name)
```

2020-05-06 15:38 UTC, StephenSmith25 commented
These variables were removed, as they were either available elsewhere, or deemed unnecessary. I think it discussed a while back (possibly January) and Martyn agreed at that time. These variables were chosen as I couldn’t see anything in Mantid that was using them and most seemed obscure.

2020-05-06 15:39 UTC, NickDraper requested changes
Trying to load Muon nxs_v2 files using the Load algorithm fails.  It is selecting the LoadMuonNexus algorithm as the loader.  You'll need to look at the confidence methods of LoadMuonNexus2 and LoadISISNexus, to make sure that LoadISISNexus wins for these files.
```
Error in execution of algorithm LoadMuonNexus:
Histogram: size mismatch of data.

Error in execution of algorithm Load:
Histogram: size mismatch of data.
```

We also need a nxs v2 file added to the LoadLotsOfFiles System test.


Otherwise really good, and I'm glad to see the back of the vms_compat block.

2020-05-06 15:50 UTC, StephenSmith25 commented
> 
> 
> Trying to load Muon nxs_v2 files using the Load algorithm fails. It is selecting the LoadMuonNexus algorithm as the loader. You'll need to look at the confidence methods of LoadMuonNexus2 and LoadISISNexus, to make sure that LoadISISNexus wins for these files.
> 
> ```
> Error in execution of algorithm LoadMuonNexus:
> Histogram: size mismatch of data.
> 
> Error in execution of algorithm Load:
> Histogram: size mismatch of data.
> ```
> 
> We also need a nxs v2 file added to the LoadLotsOfFiles System test

So currently this PR is the halfway point of loading the Muon v2 files and I've got another PR to put up which introduces a new algorithm to load the muon v2 files, which essentially calls LoadISISNexus (to do the bulk of the loading, which is made possible with these changes) and then does the Muon Specific stuff (e.g grouping, time zero) ontop. So might be best I address those issues in that PR.

2020-05-06 15:52 UTC, NickDraper commented
Ok can you add a reference to the issue for that then?

2020-05-06 16:05 UTC, NickDraper approved these changes
So the muon v2 files load into LoadISISNexus directly, is the Load issues and addition of a LoadLotsofFiles nxsV2 file happens in #27701 then this is good to go.

I'm really pleased to see us move on from the VMS days!

2020-05-06 16:06 UTC, NickDraper requested changes
One minor thing though as this alters some of our Loading algorithms we do need to mention this in the release notes.

2020-05-06 16:23 UTC, StephenSmith25 commented
> 
> 
> One minor thing though as this alters some of our Loading algorithms we do need to mention this in the release notes.

That’s true, I had forgot about this, I've pushed a documentation commit which I think is in the correct place, describing the change here.

2020-05-06 16:34 UTC, NickDraper requested changes
A couple of minor changes. Then we are good to go.

2020-05-06 16:34 UTC, NickDraper commented on docs/source/release/v5.1.0/framework.rst
> +The :ref:`LoadISISNexus <algm-LoadISISNexus>` algorithm has been modified to remove the VMS compatibility block.
```suggestion
The :ref:`LoadISISNexus <algm-LoadISISNexus>` algorithm has been modified to remove the need for the VMS compatibility block.
```

2020-05-06 16:34 UTC, NickDraper commented on docs/source/release/v5.1.0/framework.rst
> +dmp_freq, dmp_units dur, dur_freq, dur_secs, dur_wanted, durunits, mon_sum1, mon_sum2, mon_sum3, run_header.
```suggestion
dmp_freq, dmp_units dur, dur_freq, dur_secs, dur_wanted, durunits, mon_sum1, mon_sum2, mon_sum3, run_header (this is available in the workspace title).
```

2020-05-07 07:14 UTC, NickDraper approved these changes
All good to go, well done

2020-05-07 07:18 UTC, NickDraper requested changes
It looks like one of my sample logs tests has been merged into master that expects a certain number of sample logs, and the change here has caused the failure, you just need to adjust the number of logs expected.
```
======================================================================
FAIL: test_model_with_filtered_data (test_samplelogs_model.SampleLogsModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Jenkins/workspace/pull_requests-windows/qt/python/mantidqt/widgets/samplelogs/test/test_samplelogs_model.py", line 69, in test_model_with_filtered_data
    self.assertEqual(len(log_names), 152)
AssertionError: 140 != 152
```

2020-05-11 13:01 UTC, StephenSmith25 commented
> 
> 
> It looks like one of my sample logs tests has been merged into master that expects a certain number of sample logs, and the change here has caused the failure, you just need to adjust the number of logs expected.
> 
> ```
> ======================================================================
> FAIL: test_model_with_filtered_data (test_samplelogs_model.SampleLogsModelTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:/Jenkins/workspace/pull_requests-windows/qt/python/mantidqt/widgets/samplelogs/test/test_samplelogs_model.py", line 69, in test_model_with_filtered_data
>     self.assertEqual(len(log_names), 152)
> AssertionError: 140 != 152
> ```
I had to push two commits. The first fixed the failing tests, which was due to both the number of sample logs, but there was also a test failure due to trying to read "dur" out the logs. For that test I've replaced the call to "dur", to something else in the sample log hopefully that doesn't alter what the test was trying the "test". The second commit just removes an unused variable.

2020-05-11 14:12 UTC, NickDraper commented
Ah yes 'dur' was not important, just a log picked at random

2020-05-11 14:19 UTC, NickDraper approved these changes
Good to go, well done

2020-05-11 15:22 UTC, merged