Add Cropping Options to Eng Diff Calib Tab
mantidproject/mantid pull request #27714
Opened 2020-01-15 11:52 UTC by ConorMFinn

**Description of work.**
Cropping can now be done when creating a new calibration.
The GUI now allows for cropping by bank (1 or 2), or by specific spectrum numbers. 

**To test:**
1. Open Engineering Diffraction 2 GUI
2. Make sure that cropping options are greyed out when Load is selected.
3. Select Create New again
4. Check that the combo box selector appears when the cropping check box is selected 
5. Check selecting custom spectra reveals a Text entry
6. Check that only sane values can be entered and error messages make sense. 
7. Check that outputs are restricted by the cropping and have sane names. 

Fixes #26849 

*This does not require release notes* because **the GUI is not user ready.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-01-17 10:47 UTC, Harrietbrown requested changes
Is there any way you could add extra validation to the cropping values allowed. Is there any way to say what values are valid before running the calibration?

2020-01-17 10:47 UTC, Harrietbrown commented on scripts/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_presenter.py
> +    def on_combo_changed(self, index_or_string_i_dunno):  # TODO: Does this signal send and index or text?
This TODO should be sorted out in this PR

2020-01-17 14:46 UTC, ConorMFinn commented on scripts/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
> +            bank = "Cropped"
No, there isn't good spot.

2020-01-20 11:29 UTC, Harrietbrown requested changes
Good job tidying up those functions, I think it would be tricky to make it any tidyer.

2020-01-20 11:32 UTC, ConorMFinn commented on scripts/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
> +        def run_engg_calibrate(kwargs_to_pass):
This is my personal preference, but I like having the `**` operator refactored out of the main body of the function.

2020-01-20 11:33 UTC, ConorMFinn commented on scripts/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_presenter.py
> +            self.on_spectra_changed(self.view.get_custom_spectra_text())
Fixed now

2020-01-20 11:40 UTC, Harrietbrown commented on scripts/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
> +        def run_engg_calibrate(kwargs_to_pass):
Fair enough

2020-01-20 11:41 UTC, Harrietbrown commented
I am guessing that there isn't a way to premptivly validate the cropping range for a given input?

2020-01-20 16:49 UTC, ConorMFinn commented
> I am guessing that there isn't a way to premptivly validate the cropping range for a given input?

I haven't been able to do this, but it should be a little less picky now about ranges.

2020-01-21 11:55 UTC, Harrietbrown approved these changes
Good job. The cropping GUI is very simple to use and understand.

2020-01-23 08:18 UTC, merged