26881 add temp correction convsimfit
mantidproject/mantid pull request #27751
Opened 2020-01-21 14:31 UTC by Mantid-Matthew

**Description of work.**

This adds a temperature correction to the convolution fitting tab. 

**To test:**

Fixes #26881  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-06 12:49 UTC, AnthonyLim23 commented
@Mantid-Matthew is this ready for @Harrietbrown to review?

2020-02-06 13:24 UTC, Mantid-Matthew commented
This will be ready for re-review once #27880 is merged into master and this rebased.

2020-02-10 11:05 UTC, Mantid-Matthew commented
@Harrietbrown Now that #27880 has been merged this should be ready to review Thanks Mat

2020-02-10 16:32 UTC, Harrietbrown requested changes

2020-02-11 09:53 UTC, Harrietbrown commented
While not related to this issue spesificaly if the interface window is smaller (the default size on my pc) there will be a warning every time the fiting replots, this is done several times at the end of the fit. I don't know if this is worth it's own issue.

2020-02-11 10:04 UTC, Mantid-Matthew commented
I have noticed this as well and on windows the plotting in general looks ill-sized. I don't know whether this is a windowing issue or a matplotlib version thing but agree that it should have an issue opened for it.

2020-02-12 09:27 UTC, Mantid-Matthew commented on qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.cpp
> +// void ConvFunctionModel::checkProductFunction(IFunction_sptr fun) {}
Thanks that shouldn't be there have removed.

2020-02-12 10:20 UTC, Harrietbrown approved these changes
I have created an issue for the plotting errors found with a small gui #27914.
Beyond that the code looks good and runs without other errors. Good Job.

2020-02-12 16:04 UTC, martyngigg commented
Test failures are unrelated and fixed on master.

2020-02-12 16:04 UTC, merged