Updated mantidworkbench to send stacktrace
mantidproject/mantid pull request #27760
Opened 2020-01-22 16:01 UTC by Mantid-Matthew

**Description of work.**

This updates the error reporter in two ways
  * It removes the sending of recovery files as these were found to be not very useful.
  * It adds in the sending of a stacktrace in workbench in cases where one can be retrieved.

**To test:**
  * To test this properly you will need to get a local version of the error report server with this pull request built. https://github.com/mantidproject/errorreports/pull/15
  * You will also need to change the errorreports url in Mantid.properties.template to http://localhost:8082
  * There are two cases which need to be tested. 
       * Testing the catching of non-crashing errors can be done by trying to cancel a mantid build via a keyboard interrupt. 
       * To test the other case you need to add `raise RuntimeError("Error Message") before line 859 in mainwindow.py . This will then provoke an excetion on startip.

  * In both cases check that error-reports are received by the server with appropriate stack traces.

*There is no associated issue.*

*This does not require release notes* because this is a developer facing change

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-01-23 14:33 UTC, DanielMurphy22 commented
Code works as expected, just the one build failure

2020-01-23 14:35 UTC, DanielMurphy22 submitted a review, later dismissed

2020-01-23 15:23 UTC, martyngigg requested changes

2020-01-23 15:23 UTC, martyngigg commented on Framework/Kernel/inc/MantidKernel/ErrorReporter.h
>    /// recovery file path
Can we either update the comments or remove them for all of these member variables? The names are good so I think the comments are not really required.

2020-01-23 15:23 UTC, martyngigg commented on qt/applications/workbench/workbench/app/mainwindow.py
> +        print_file_path = os.path.join(ConfigService.getAppDataDirectory(), 'workbench_stacktrace.txt')
Couple of things:
* can we define the string `'workbench_stacktrace.txt'` using a named constant put at the top of the module with the others?
* we need to be careful with file handling as it's entirely possible to get an unexpected `OSError`. Can we wrap this in a `try...except` and also use `with open ...` so we don't need to worry about `.close()`

2020-01-23 15:23 UTC, martyngigg commented on scripts/ErrorReporter/error_report_presenter.py
> +            if os.path.isfile(traceback_file_path):
Similarly we need to make sure we handle errors around the os calls. Can we use `with` for opening the file and I think `open` and `os.rename` need an `OSError` catcher for safety?

2020-01-24 11:43 UTC, martyngigg submitted a review, later dismissed

2020-01-24 11:43 UTC, martyngigg commented on qt/applications/workbench/workbench/app/mainwindow.py
> +        try:
:+1:

2020-01-24 11:44 UTC, martyngigg commented
@Mantid-Matthew There are a couple of tests failing now. I expect because we have removed the recovery info.

2020-01-28 09:56 UTC, martyngigg commented
@Mantid-Matthew Would you have time to look at the failing tests here?

2020-01-29 08:21 UTC, martyngigg commented
@Mantid-Matthew Is there any issue with the Windows tests?

2020-01-29 08:29 UTC, Mantid-Matthew commented
No I was trying to build a windows package on another branch and lost track of which tab I was on.

2020-02-04 11:03 UTC, martyngigg approved these changes

2020-02-04 11:05 UTC, martyngigg commented
@mantidproject/gatekeepers Any chance we could get this merged to get it out to users? The stacktrace will be very useful for us figuring out what has happened.

The `Ubuntu Python 3` is now an orphaned status as we have removed that job since the default is now Python 3.

2020-02-04 11:34 UTC, merged