Fix crash in workbench when fitting in script editor
mantidproject/mantid pull request #27836
Opened 2020-01-31 10:48 UTC by alicerussell1

**Description of work.**
This fixes the crash when running a script with a fit in it in workbench. This was caused by the move to python 3, specifically a small change in `__hasattr__`, which meant the error was no longer being caught.

**To test:**
Run the following in workbench
```
ws = Load("MAR11060")
fitted = Fit("name=Gaussian", ws)
```
It should run successfully and not crash.

Fixes #27834 

*This does not require release notes* because **it was caused by the python migration during this sprint**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-01-31 14:30 UTC, PhilColebrooke requested changes
Mostly good. One small thing, is there any chance you could make it work?

2020-01-31 15:08 UTC, PhilColebrooke submitted a review, later dismissed
Good to go as long as the checks pass

2020-02-03 09:39 UTC, PhilColebrooke submitted a review, later dismissed
Still works

2020-02-03 14:42 UTC, gvardany commented on Framework/PythonInterface/mantid/fitfunctions.py
> +                raise AttributeError("Parameter not found")
Could you add the name of the parameter in the error message?

2020-02-05 09:32 UTC, gvardany commented
@PhilColebrooke Can you reapprove?

2020-02-05 09:37 UTC, PhilColebrooke approved these changes

2020-02-05 09:38 UTC, merged