Add plotting options to context menu for WorkspaceGroups
mantidproject/mantid pull request #27830
Opened 2020-01-30 11:50 UTC by PhilColebrooke

**Description of work.**
This PR makes it so that you can right-click a WorkspaceGroup and plot the workspaces it contains, like in MantidPlot.

**To test:**
1. Make a WorkspaceGroup and right-click it. There should now be plotting options.
2. Plotting this way should produce a plot with lines from each workspace in the group. If one of the workspaces can't be plotted, such as a TableWorkspace, a warning will appear in the log but the rest of the workspaces will still be plotted.
3. A WorkspaceGroup containing only non-plottable workspaces should not have the plotting options when right-clicked.

Fixes #27820 

No release notes because who cares

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-01-30 17:13 UTC, cailafinn requested changes
Show detector table on a workspace group containing only empty table workspaces causes an unhandled exception.

Other than that, just the one code comment.

2020-01-30 17:13 UTC, ConorMFinn commented on qt/python/mantidqt/dialogs/spectraselectordialog.py
> +                matrix_workspaces.append(ws)
This looks like it could just be `if isinstance: append; else: log warning`.

2020-01-31 09:04 UTC, cailafinn submitted a review, later dismissed
Code looks good and functions as described. Good work. :+1:

2020-02-03 09:15 UTC, NickDraper requested changes
```
No release notes because who cares
```

I have to say I disagree with this pretty unprofessional comment.
This is a user facing GUI change, that if you do not tell people about it will never be used.

2020-02-03 09:27 UTC, NickDraper commented
CLang format cancelled as the last build passed, and the final commit was release notes only and not complex.

Merged

2020-02-03 09:27 UTC, merged