Added some protection around loading config files in workbench
mantidproject/mantid pull request #27853
Opened 2020-02-03 17:12 UTC by NickDraper

**Description of work.**

Handles corrupt QObjects, and some of the sensitive fields in MessageDisplay, that HAVE to be boolean as they are passed to a C++ base class

**To test:**

1. Find your mantidworkbench.ini file (on windows it is in %appdata%\mantidproject)
1. Take a copy of your file so you can restore it after
1. Delete it
1. Start workbench, if it creates a new .ini file you know you re looking at the right file
1. Stop workbench and edit the new file. Paste in this corrupted version.
```
[General]
high_dpi_scaling=true

[project]
prompt_save_editor_modified=5.58
prompt_save_on_close=TrUe
prompt_on_deleting_workspace=flase

[Editors]
SessionTabs=@Variant(\0\0\0\x7f\0\0\0\xePyQt_PyObject\0\0\0\0\xf3\x63__builtin__\nset\np0\n((lp1\nVC:/Users/jsl28/Desktop/test_py23.py\np2\naVM:/doc/Summer student 2019/Doug internship work/Python/Degrader Calculator.py\np3\naVM:/doc/Summer student 2019/Doug internship work/Python/degrader_dictionary2.py\np4\natp5\nRp6\n.)
ZoomLevel=false

[MessageDisplay]
ShowFrameworkOutput=1e-8
ShowAllScriptOutput=Herbie_Goes_Bananas
ShowActiveScriptOutput=@Variant(\0\0\0\x7f\0\0\0\xePyQt_PyObject\0\0\0)
```
1. Start workbench
1. If it starts up - success

Fixes #26632. 

This does not require release notes*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-06 19:31 UTC, giovannidisiena requested changes
Code changes looks good, only one minor comment. I also get this output when starting workbench initially, no longer appearing on subsequent attempts:
```Could not load file:
  [Errno 2] No such file or directory: 'C:/Users/jsl28/Desktop/test_py23.py'
Could not load file:
  [Errno 2] No such file or directory: 'M:/doc/Summer student 2019/Doug internship work/Python/degrader_dictionary2.py'
Could not load file:
  [Errno 2] No such file or directory: 'M:/doc/Summer student 2019/Doug internship work/Python/Degrader Calculator.py'
```
however I assume this is to be expected. If that is the case then I'm happy to approve :+1:

2020-02-06 19:31 UTC, giovannidisiena commented on qt/python/mantidqt/widgets/messagedisplay.py
> +    def ReadSettingSafely(self,qsettings,key,default,type):
Should there be spaces between the commas and following arguments here?

2020-02-07 14:54 UTC, NickDraper commented
the missing files are reporting as expected, they are in the garbage file but not on your system

2020-02-07 15:36 UTC, giovannidisiena approved these changes

2020-02-10 07:25 UTC, merged