Workbench apply settings without relaunch
mantidproject/mantid pull request #27866
Opened 2020-02-04 15:35 UTC by NickDraper

**Description of work.**

The algorithms category and interface hiding should now apply as soon as the setting dialog is closed.
The button has also been changed to be close rather than "SaveSettings", as most of the settings were saved even if you clicked the X close button.

Also harmonised both the close and X close actions

**To test:**
1. open workbench
1. File->Settings
1. Fiddle with categories, both algorithms and interface hiding
1. check that the workbench toolboxes refresh when settings is closed.
1. try with both close and X close
1. Show invisible workspaces should also be immediate.

Fixes #27861. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-07 11:50 UTC, Harrietbrown requested changes
The settings take effect after closing the window. However closing the window is noticably slower even if no changes are made. If possible there should be a check to see if the setting have been changed before repopulating the algorithm widget and taskbar.

2020-02-07 11:50 UTC, Harrietbrown commented on qt/applications/workbench/workbench/widgets/settings/presenter.py
> +        Saes te mantid settings and updates updates te parent
I think this is what it is supposed to mean.

```suggestion
        Saves the mantid settings and updates updates the parent
```

2020-02-07 16:55 UTC, NickDraper commented
It's not really possible to check as most of the changes happen immediately, the dealy is from updating toolboxes in the workbench that might have been changed.

I'm not sure people fiddle in here often enough to be worried about a small change in closing speed

2020-02-07 16:56 UTC, NickDraper commented
Reopened as I only closed it by mistake

2020-02-10 11:33 UTC, Harrietbrown approved these changes
In that case it is probably not worth making a check for that. The actual functionality is all good and the jenkins failure is unrelated.

2020-02-12 16:12 UTC, merged