Add help button to add function dialog in fitting
mantidproject/mantid pull request #27916
Opened 2020-02-12 11:09 UTC by alicerussell1

**Do not merge until #27908 has been merged**

**Description of work.**
This PR adds a help button into the add function dialog in fitting. 
It also fixes a small bug where the fitting docs were never found as the url had changed from `fitfunctions/function_name` to `fitting/fitfunctions/function_name`

Report to: @AnthonyLim23 

**To test:**
Build the fitting docs
Open workbench, load a workspace and do a plot.
Click the fit button
Right-click on the plot and click any of the `add ...` options.
There should be a `?` button in the bottom left corner.
If you click it then it should show the help page for the fit function selected. If the function does not have documentation  then it should display the fit functions index page. 

Similarly Right-click on the property browser and click add function.
There should be a `?` in the bottom left corner which works the same as above

Add a function and right click on it in the function browser.
Click help and it should load the docs for that function if it exists

Fixes #27020 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-14 10:04 UTC, Harrietbrown requested changes

2020-02-17 11:30 UTC, alicerussell1 commented
I've made the change and rebased the branch as the earlier PR has been merged so it should be ready for another review

2020-02-17 12:55 UTC, Harrietbrown approved these changes
Everything looks good, the help menu comes up from the help context menu, and the add fit function browsers. It also is able to understand if a fit function is manualy typed in to the fitfunctionbrowser.
Good Job

2020-02-17 12:55 UTC, Harrietbrown commented
failing tests are unrelated

2020-02-18 08:54 UTC, merged