Reload data sets in Muon Analysis without crash
mantidproject/mantid pull request #27922
Opened 2020-02-12 15:13 UTC by giovannidisiena

**Description of work.**
This PR allows data sets to be reloaded within the Muon Analysis GUI (Workbench) without crashing Mantid while the Instrument View is open.

**To test:**
- Open Workbench
- Open Muon Analysis GUI
- Type in 62260 as the run number
- Show Instrument on the "EMU62260_raw_data MA" workspace
- Enter the Pick tab and click on some detectors
- Go back to the Muon Analysis GUI and use the <> buttons to move to the next run, and then back to 62260
- Should **not** crash

Fixes #27881 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-13 16:06 UTC, cailafinn requested changes
Having some trouble with functional testing due to increment button not working on Ubuntu. I do have a code comment though.

2020-02-14 07:35 UTC, giovannidisiena commented on qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
>    /// ADS notification handlers
Yes, it is to keep the member variable separate from the functions below.

2020-02-14 07:36 UTC, giovannidisiena commented
@ConorMFinn I am going to look into the increment button issue. As we discovered yesterday, it wasn't a problem for me initially (maybe an old master) but now it is.

2020-02-14 08:50 UTC, ConorMFinn commented on qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
>    /// ADS notification handlers
There is another member variable at Line 346. These should be together. Whether you move your new one down or the existing one up is down to you, but it should match the surrounding code.

2020-02-17 13:01 UTC, cailafinn approved these changes
This looks good to me now. Crash no longer occurs.

2020-02-18 08:46 UTC, merged