ILL SANS Absolute Scale
mantidproject/mantid pull request #27934
Opened 2020-02-13 14:57 UTC by gvardany

**Description of work.**
This PR makes it possible to do correct absolute normalisation even if the water and the sample runs are measured at different distances, and yet even if there is no flux measurement at the water distance.

**To test:**
Soon.

Fixes #27918 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-18 11:05 UTC, Harrietbrown requested changes
I am getting a failing system test `SANSILLAutoProcessTest.D33_AutoProcess_Test`

2020-02-18 12:23 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction.py
> +            Scales ws by the magic flux factor wrt the reference
There is no much magic at the end, I'll remove it :)

2020-02-18 12:48 UTC, gvardany commented
What is the failure exactly?

2020-02-18 12:50 UTC, Harrietbrown commented
```
SANSILLIntegration-[Error] Error in execution of algorithm SANSILLIntegration:
SANSILLIntegration-[Error] Index out of range
SANSILLIntegration-[Error]   at line 179 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLIntegration.py'
SANSILLAutoProcess-[Error] Error in execution of algorithm SANSILLAutoProcess:
SANSILLAutoProcess-[Error] Index out of range
SANSILLAutoProcess-[Error]   at line 179 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLIntegration.py'
SANSILLAutoProcess-[Error]   at line 299 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLAutoProcess.py'
SANSILLAutoProcess-[Error]   caused by line 461 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLAutoProcess.py'
SANSILLAutoProcess-[Error]   caused by line 1171 in 'c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py'
Traceback (most recent call last):
  File "C:\Users\wey38795\AppData\Local\Temp\tmpi2_zo3ge", line 24, in <module>
    systest.execute()
  File "C:\Users\wey38795\Documents\mantid_builds\Master\raw\mantid\Testing\SystemTests\lib\systemtests\systemtesting.py", line 225, in execute
    self.runTest()
  File "C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Testing/SystemTests/tests/analysis\SANSILLAutoProcessTest.py", line 101, in runTest
    SANSILLAutoProcess(
  File "c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py", line 1171, in algorithm_wrapper
    algm.execute()
RuntimeError: Index out of range
  at line 179 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLIntegration.py'
  at line 299 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLAutoProcess.py'
  caused by line 461 in 'C:/Users/wey38795/Documents/mantid_builds/Master/raw/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\SANSILLAutoProcess.py'
  caused by line 1171 in 'c:\users\wey38795\documents\mantid_builds\master\raw\mantid\framework\pythoninterface\mantid\simpleapi.py'
```

2020-02-18 16:32 UTC, gvardany commented
Does it go away if you wipe the IDF cache? It's `~/.mantid/instrument` on Unix, on Windows I think it's somewhere in APP DATA.

2020-02-19 08:48 UTC, Harrietbrown commented
OK that has gotten the tests passing.

2020-02-21 10:36 UTC, Harrietbrown approved these changes
All system tests are now passing on jenkins and localy and the code passes review.

Good job.

2020-02-21 12:01 UTC, merged