Change default grid to be off when creating menu for axis
mantidproject/mantid pull request #28117
Opened 2020-02-26 16:51 UTC by RichardWaiteSTFC

Set default of grid visibility to false when making menu that appears when user double clicks

To test:
Produce any 1D plot in workbench and double-click on an axis (the grid box is un-ticked) 

Fixes #28096

2020-02-27 10:27 UTC, DanielMurphy22 requested changes
flake8 failure is due to unused variable `ticks` on line 136.

Also, this is better, but if you plot, add gridlines (say with the toolbar button, and then double-click on an axis, it still defaults to the grid tickbox unticked. It should read (getattr) the currently set value, which log seems to do through this double-click on axis menu

2020-02-27 13:38 UTC, DanielMurphy22 requested changes
Are you able to add a Unit test for this?

2020-02-28 13:36 UTC, DanielMurphy22 approved these changes

2020-02-28 14:06 UTC, martyngigg commented
@RichardWaiteSTFC I'll fix this merge conflict manually when I merge it.

2020-02-28 14:17 UTC, merged