IndexProperty - Append bad index to out of range exception
mantidproject/mantid pull request #28120
Opened 2020-02-26 19:22 UTC by DavidFair

**Description of work.**
Previously, the at() access on the IndexProperty map would throw with an
invalid key message that didn't specify which key. This is useless for anyone who is using IndexProperty algorithms, such as MaskSpectra. 

With a range of specra (such as 500) you have to guess if the min / max or middle value(s) were bad.

Updates the IndexType to have a new method to convert to a string, this reduction in strict type safety could mean developers could abuse SpectrumIndex -> String conversions. However, it enables us to print a string representation of an index.

*I'm open to alternatives for ways to pack the value into an exception without exposing a string representation, however I personally can't think of one. So this is the best I can come up with.*

**Report to:** ISIS/Steve - Part of a larger issue I'm working on

**To test:**
- Run the following script
```
ws = CreateSampleWorkspace()
ws = MaskSpectra(ws, "SpectrumNumber", [900])
```
- Check it informs the user index 900 is incorrect

Fixes #28119 .

This does not require release notes because it's a small QOL fix not worth documenting

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-02-27 16:06 UTC, Harrietbrown requested changes
the solution has trouble when there are multiple invalid `SpecNums` or a mix of valid and invalid ones, try the test script with [400, 900], [140, 900], or "140-900" and try and get it working with them

2020-02-28 11:35 UTC, DavidFair commented
Thanks for noticing that, this should be fixed if you have a chance to re-review it

2020-02-28 14:22 UTC, Harrietbrown commented
so if you give it: 
`"100-250,300-900"` it gives `The following value is out of range: 201`, 
`"100,300-900"` it gives `The following value is out of range: 300`
but if you give it `"100-900"` it gives `The following maximum is out of range: 900`,

Having that option give the maximum out of range feels inconsistent.

2020-02-28 14:42 UTC, DavidFair commented
🤔 good point, in effect it's an implementation detail that it's the maximum in this case

I'll go through all the various branches (as we can select one of four ways to convert it) and bring them all to consistency

2020-02-28 14:54 UTC, DavidFair commented
All branches which directly test numbers will now get the same message, thanks for pointing that out

2020-02-28 16:44 UTC, Harrietbrown commented
I tested those three cases but there is no difference

2020-02-28 17:18 UTC, DavidFair commented
Sorry is that no difference between the outputs, or no difference since you reported it?
As all the examples (locally) produce the same output for me now 😕

2020-03-02 08:51 UTC, Harrietbrown commented
With the PR as is using `"100-900"` gives `The following value is out of range: 900` when for concistency it should be `201`

2020-03-03 10:00 UTC, DavidFair commented
Ah right, but from the spectrum translator we can't tell that since we effectively get a `min, max` value hence it states effectively that 900 > 200

We could do something fancy to work out the first invalid index, however ultimately it's the value 900 which was incorrect in the API call so that's what they want to look for?

2020-03-03 11:20 UTC, Harrietbrown commented
if `"100-250,300-900"`  can find `201` as the value out of bounds is it that much more complex to find `"100-900"` has the same?

2020-03-03 11:57 UTC, DavidFair commented
Unfortunately yes since

> 100-250,300-900

IndexProperty converts this into a vector with [100,250], [300, 900] as the ranges aren't contiguous

> 100-900

IndexProperty notices this is contiguous and replaces it with a SpectrumMin / SpectrumMax instead hence we don't have an interval in between

Both properties call an overloaded function on IndexType, which then calls into SpectrumNumberTranslator which does the checks. We could reverse the vector iterator so it checks max->min but then this would have the opposite problem (if the ws spectrum ends as 50 it will say 49 is out of range instead of 1).

I can't think of a more graceful fix without some significant API changes to SpectrumNumberTranslator, however I'm completely open to suggestions?

2020-03-03 12:52 UTC, Harrietbrown commented
You know more about how IndexProperty works, so if you think there is not a simple solution I will go with this for this release.

2020-03-03 13:05 UTC, DavidFair commented
Thanks, it is really useful discussion on how we should inform the users which spectra is wrong if we do need to come back to it
 
We should come back and address this when/if I (or another dev) has a user report that gets confused by the message from IndexProperty. However at least for SANS it's took several years for anyone run into a case where it was non-trivial to see which property was wrong

2020-03-03 13:06 UTC, Harrietbrown approved these changes
Running the script gives an error saying what SpectrumNumber input is invalid. one small problem is that is you give an input in the form of only a minimum and a maximum value it doesn't pick out the invalid value from the range it defines, but instead only the maximum value. But I do not think that is significant enough an issue to hold this back.

2020-03-03 13:23 UTC, merged