Fix unhandled exception when opening figure options on plot with empty legend
mantidproject/mantid pull request #28219
Opened 2020-03-04 10:51 UTC by PhilColebrooke

**Description of work.**
This PR adds a check so that the legend tab in the figure options is only shown if the plot has a legend *and* that legend has text, this prevents an unhandled exception from occurring.

**To test:**
```
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
ax.plot([0,1],[0,1])
ax.legend()
fig.show()
```
Open figure options.

Fixes #28198 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-03-04 11:20 UTC, cailafinn requested changes
The figure options now open, but clicking `Apply` or `Ok` in the figure options causes another unhandled exception to appear. 
```
Traceback (most recent call last):
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/presenter.py", line 72, in apply_properties_and_exit
    self.apply_properties()
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/presenter.py", line 68, in apply_properties
    tab.apply_properties()
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py", line 66, in apply_properties
    self.legend_props = LegendProperties.from_legend(ax.legend_)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/legend.py", line 71, in from_legend
    text = legend.get_texts()[0]
IndexError: list index out of range
```

2020-03-04 11:24 UTC, cailafinn requested changes
A quick code comment as well:

2020-03-04 11:24 UTC, ConorMFinn commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +        if legend and legend.get_texts():
I'm not sure the local variable is necessary. 
```suggestion
        if self.legend_ and self.legend_.get_texts():
```

2020-03-04 15:45 UTC, cailafinn submitted a review, later dismissed
Code looks good and fixes the described issue. Curves options error issue created at: #28230

2020-03-04 16:07 UTC, martyngigg reviewed
I'm a little nervous that we have to make changes to many key files. Does this only happen if you do a plot from a set of arrays from a script?

2020-03-04 16:10 UTC, martyngigg requested changes
I'm guessing we are also missing various tests across these areas for this? Can we add those?

2020-03-04 16:19 UTC, PhilColebrooke commented
The only times this issue can occur are:
- if you do a non-workspace plot from a script and call `ax.legend()` without providing any label(s).
- if you have any plot with a legend that does have labels and then for some reason use the figure options to remove every curve.

I believe that it was also an issue in 4.2 that went unnoticed, do you think it should be held off until the next release?

2020-03-04 16:23 UTC, martyngigg commented
Thanks. I think this is sufficiently niche that is safer to put it onto master. Can you change the milestone to 5.1S1 and base branch to master?

Would it be possible to add some tests too?

2020-03-04 16:24 UTC, PhilColebrooke commented
Will do

2020-04-15 09:55 UTC, martyngigg commented
@PhilColebrooke I just realised this was a bit stale so I rebased to fix up to merge conflicts and kick off the builds again just to check everything is still okay.

2020-04-15 19:22 UTC, martyngigg approved these changes

2020-04-15 19:22 UTC, martyngigg commented
Unrelated test failure

2020-04-15 19:24 UTC, merged