Change Algorithm State tracking
mantidproject/mantid pull request #28272
Opened 2020-03-06 13:40 UTC by NickDraper

**Description of work.**
Previously we had a collection of boolean values that tracked the state of an algorithm object:
1. IsInitialized
1. IsRunning
1. IsExecuted

This however cannot describe some situations, for example when an algorithm is errored.

This PR puts in two enums to describe the execution status, and the status of the result.

The boolean is methods are left in place, but report from the two enum states.

**NOT COMPLETE YET**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-03-20 16:22 UTC, cailafinn requested changes
Just a couple of things I noticed in the code review. Passes functional tests. :+1:

2020-03-23 09:54 UTC, cailafinn submitted a review, later dismissed
Progress Monitors working as expected in plot and workbench. Code looks good. I like this much more than the bool flags :+1:
Given the reach of the changes, this is probably worth testing on a few different setups. 

Tested on Ubuntu 18.04 | Local Release build.

2020-03-23 20:53 UTC, martyngigg requested changes

2020-03-23 20:53 UTC, martyngigg commented on Framework/API/inc/MantidAPI/Algorithm.h
> +  bool m_isExecuted;                            ///< Algorithm is executed flag
Do we need `m_isExecuted` now? I think this should be covered by `m_executionState`?

2020-03-24 17:25 UTC, martyngigg approved these changes

2020-03-24 17:26 UTC, merged