Fix Logger not being defined in plotfunctions and add check for there being valid workspaces to plot
mantidproject/mantid pull request #28349
Opened 2020-03-11 17:07 UTC by PhilColebrooke

**Description of work.**
The LOGGER definition in plotfunctions.py was removed which meant that if you attempted to plot a non-MatrixWorkspace, instead of a useful warning you would just get "name LOGGER is not defined". In fixing this I also discovered that if you attempted to plot a non-MatrixWorkspace, The warning would output but it would still attempt to make a plot so you'd get a different error afterwards.

**To test:**
Run this script:
```
ws = CreateSampleWorkspace()
table = CreateDetectorTable(ws)
plotSpectrum([table], [0])
```

You should get a warning in the log saying table is the wrong type and no plot should be created.

*There is no associated issue.*

No release notes because this wasn't a problem in the last release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-03-12 08:31 UTC, martyngigg requested changes
There is a slight issue here that the `plotfunctions.plot` was originally intended only for the GUI so logging that things are not compatible made sense. Now that we have them lower down and can access them from scripts through `plotSpectrum` I don't think they should log anymore but raise an exception and the GUI can handle catching it where relevant.

Changing this to raising an exception is more dangerous so I don't think we should do that for this release and given this raises an error on tables, just a different error, I don't think it is critical this goes in the release. Could you push this into 5.1S1 and then we can work on making it raises the errors more appropriately when given unexpected input?

2020-04-17 07:41 UTC, NickDraper commented
@martyngigg Any chance you could have another look at this today to see if it is ok now?

2020-04-17 08:10 UTC, martyngigg submitted a review, later dismissed

2020-04-17 08:11 UTC, martyngigg commented
@NickDraper Thanks for the reminder. I had missed there had been an update to it.

2020-04-17 08:13 UTC, martyngigg commented
Actually as this is a bit old I'd like to push it through the builds again. We've had a few issues where old PRs no longer function when merged with a current master recently.

2020-04-17 09:29 UTC, martyngigg approved these changes

2020-04-17 09:30 UTC, merged