Q binning for non zero gamma angle
mantidproject/mantid pull request #28427
Opened 2020-03-24 16:17 UTC by MathieuTillet

**Description of work.**
This PR changes the behavior of the q binning algorithm in SANSILLIntegration when the detector is not in front of the beam (gamma angle different from 0).
After some tries, binning from q_min to q_max with step (q_max - q_min)/pixels_by_row was determined a reasonable calculation (the original way of computing the binning cannot be extended over the whole range of the instrument).

**To test:**
`SANSILLAutoProcessTest` has been updated to take this change into account. Alternatively, one can use the files used for testing D16 to check the results' coherence.

Fixes #28425 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-04-21 15:01 UTC, gemmaguest requested changes
Looks good and the reduction still runs fine. Just one query.

2020-04-22 06:01 UTC, MathieuTillet commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
> +                            self.log().warning("Width of the instrument not found. Assuming 320 pixels.")
Fair point, I'll change that

2020-04-22 09:53 UTC, gemmaguest commented
Does this require release notes?

2020-04-23 11:55 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
> +                            self.log().warning("Width of the instrument not found. Assuming 320 pixels.")
Can you put the number of pixels in the instrument parameters file, and get from there?

2020-04-23 11:58 UTC, gvardany commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
> +                            self.log().warning("Width of the instrument not found. Assuming 320 pixels.")
I would also swap the order of ifs, other instruments are not expected to have gamme defined, so this makes sense only for D16.

2020-04-27 15:44 UTC, gemmaguest commented
> 
> 
> Does this require release notes?

@MathieuTillet @gvardany I'm happy to approve this, just wanted to check if it needs release notes?

2020-04-28 10:04 UTC, MathieuTillet commented
Very sorry about this delay. Here are both release notes and the changes requested by Gagik.

2020-04-29 12:23 UTC, gemmaguest approved these changes
Thanks for the changes. Still runs fine and the value is picked up from the params file or logs a warning if it's not there :+1:

2020-05-03 15:30 UTC, merged