Wb log keyoard movement
mantidproject/mantid pull request #28619
Opened 2020-04-29 13:50 UTC by NickDraper

**Description of work.**
Changed the sample logs view to update on selectionChanged rather than just clicked

**To test:**

1. in workbench load a file with some logs
1. Show Sample Logs
1. Check that you can both click on a log and also move between them with the cursor keys and the plot and stats update.
1. check that multiple selection still works.

refs #28569

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-04-30 15:00 UTC, PhilColebrooke requested changes
This works as intended 👍 Just some code comments

2020-04-30 15:51 UTC, NickDraper commented on qt/python/mantidqt/widgets/samplelogs/presenter.py
> +    def selectionChanged(self, selected, deselected):
I just learned that you don't have to match the arguments of a signal and slot in pyQt 😄

2020-04-30 15:51 UTC, NickDraper commented on qt/python/mantidqt/widgets/samplelogs/presenter.py
> +        """Update stats with selected log and replot the
done

2020-05-01 07:58 UTC, PhilColebrooke approved these changes
Looks good to me 😄

2020-05-03 15:33 UTC, merged