Speed up loading in workspace loading in the Muon Interface
mantidproject/mantid pull request #28627
Opened 2020-04-30 15:58 UTC by StephenSmith25

**Description of work.**
Issues with loading in the Muon interface have been noted previously, where it was found that the workspace history appears to be quite bloated. 

In this PR it was found that the MuonPreProcess and GroupWorkspaces algorithm were being run for each detector group, which feels quite unnecessary. This PR minimises the number of calls made to these algorithms, to improve the speed of loading and to make the workspace history appear more sensible.

This PR implements a context manager to stall the execution of the groping algorithm. This method was chosen as I didn't want to change the overall behaviour of the MuonWorkspaceWrapper show() method.

Comparing the workspace history before for MUSR62260 loaded in the GUI (**28 Algorithm calls**):

```
  LoadMuonNexus(Filename=r'\\isis.cclrc.ac.uk\inst$\ndxmusr\instrument\data\cycle_16_5\MUSR00062260.nxs', OutputWorkspace='MUSR00062260.nxs', DeadTimeTable='MUSR00062260.nxs_deadtime_table', DetectorGroupingTable='__notUsed')
    RenameWorkspace(InputWorkspace='MUSR00062260.nxs_deadtime_table', OutputWorkspace='MUSR62260_deadtime MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA', OutputWorkspace='MUSR62260 MA')
    RenameWorkspace(InputWorkspace='MUSR00062260.nxs', OutputWorkspace='MUSR62260_raw_data MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA', OutputWorkspace='MUSR62260 MA')
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingCounts(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; top; Counts; MA', GroupName='top', Grouping='17-24,49-56')
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingAsymmetry(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; top; Asymmetry; MA', OutputUnNormWorkspace='__MUSR62260; Group; top; Asymmetry; MA_unnorm', GroupName='top', Grouping='17-24,49-56', AsymmetryTimeMin=0.10000000000000001, AsymmetryTimeMax=32.293998718261719)
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingCounts(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; bkwd; Counts; MA', GroupName='bkwd', Grouping='25-32,41-48')
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingAsymmetry(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; bkwd; Asymmetry; MA', OutputUnNormWorkspace='__MUSR62260; Group; bkwd; Asymmetry; MA_unnorm', GroupName='bkwd', Grouping='25-32,41-48', AsymmetryTimeMin=0.10000000000000001, AsymmetryTimeMax=32.293998718261719)
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingCounts(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; bottom; Counts; MA', GroupName='bottom', Grouping='1-8,33-40')
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingAsymmetry(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; bottom; Asymmetry; MA', OutputUnNormWorkspace='__MUSR62260; Group; bottom; Asymmetry; MA_unnorm', GroupName='bottom', Grouping='1-8,33-40', AsymmetryTimeMin=0.10000000000000001, AsymmetryTimeMax=32.293998718261719)
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingCounts(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; fwd; Counts; MA', GroupName='fwd', Grouping='9-16,57-64')
    MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
    MuonGroupingAsymmetry(InputWorkspace='__pre_processed_data', OutputWorkspace='MUSR62260; Group; fwd; Asymmetry; MA', OutputUnNormWorkspace='__MUSR62260; Group; fwd; Asymmetry; MA_unnorm', GroupName='fwd', Grouping='9-16,57-64', AsymmetryTimeMin=0.10000000000000001, AsymmetryTimeMax=32.293998718261719)
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA,MUSR62260; Group; bkwd; Asymmetry; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA,MUSR62260; Group; bkwd; Asymmetry; MA,MUSR62260; Group; bottom; Counts; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA,MUSR62260; Group; bkwd; Asymmetry; MA,MUSR62260; Group; bottom; Counts; MA,MUSR62260; Group; bottom; Asymmetry; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA,MUSR62260; Group; bkwd; Asymmetry; MA,MUSR62260; Group; bottom; Counts; MA,MUSR62260; Group; bottom; Asymmetry; MA,MUSR62260; Group; fwd; Counts; MA', OutputWorkspace='MUSR62260 MA')
    GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA,MUSR62260; Group; top; Counts; MA,MUSR62260; Group; top; Asymmetry; MA,MUSR62260; Group; bkwd; Counts; MA,MUSR62260; Group; bkwd; Asymmetry; MA,MUSR62260; Group; bottom; Counts; MA,MUSR62260; Group; bottom; Asymmetry; MA,MUSR62260; Group; fwd; Counts; MA,MUSR62260; Group; fwd; Asymmetry; MA', OutputWorkspace='MUSR62260 MA')

```

And now (**14 Algorithm calls**)
```
LoadMuonNexus(Filename=r'\\isis.cclrc.ac.uk\inst$\ndxmusr\instrument\data\cycle_16_5\MUSR00062260.nxs', OutputWorkspace='MUSR00062260.nxs', DeadTimeTable='MUSR00062260.nxs_deadtime_table', DetectorGroupingTable='__notUsed')
RenameWorkspace(InputWorkspace='MUSR00062260.nxs_deadtime_table', OutputWorkspace='MUSR62260_deadtime MA')
RenameWorkspace(InputWorkspace='MUSR00062260.nxs', OutputWorkspace='MUSR62260_raw_data MA')
GroupWorkspaces(InputWorkspaces='MUSR62260_deadtime MA,MUSR62260_raw_data MA', OutputWorkspace='MUSR62260 MA')
MuonPreProcess(InputWorkspace='MUSR62260_raw_data MA', OutputWorkspace='__MUSR62260_pre_processed_data', TimeMin=0.10000000000000001, TimeOffset=0, DeadTimeTable='MUSR62260_deadtime MA')
MuonGroupingCounts(InputWorkspace='__MUSR62260_pre_processed_data', OutputWorkspace='MUSR62260; Group; top; Counts; MA', GroupName='top', Grouping='17-24,49-56')
MuonGroupingAsymmetry(InputWorkspace='__MUSR62260_pre_processed_data', OutputWorkspace='MUSR62260; Group; top; As [...]

2020-05-06 10:05 UTC, Harrietbrown requested changes
one question

2020-05-06 10:09 UTC, StephenSmith25 commented on scripts/Muon/GUI/Common/ADSHandler/muon_workspace_wrapper.py
> +                print(self.name, self._workspace_name, self.workspace)
Nope, completly forgot I put that there 🤦

2020-05-06 10:17 UTC, Harrietbrown submitted a review, later dismissed
Very clever soluton on the group workspace I expect ther may be other places where that helper will be useful. In this I got a significant speed up on load time, 8.4 seconds without the PR, 4.82s with the PR, so a good job all around.

2020-05-07 06:56 UTC, gvardany commented
Is this worth a release note?

2020-05-11 10:13 UTC, Harrietbrown approved these changes
Release notes look ok.

2020-05-11 15:24 UTC, merged