Crash when opening plot options on a sample logs plot
mantidproject/mantid pull request #28636
Opened 2020-05-04 09:10 UTC by NickDraper

**Description of work.**

Add protection from None being passed to C++

**To test:**

Fixes #27770

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-05-04 11:19 UTC, PhilColebrooke requested changes
The options can now be opened, but changing any of the options in the Curves tab produces this error:
```
Traceback (most recent call last):
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\presenter.py", line 66, in apply_properties
    tab.apply_properties()
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\presenter.py", line 71, in apply_properties
    self._replot_selected_curve(plot_kwargs)
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\presenter.py", line 129, in _replot_selected_curve
    new_curve = FigureErrorsManager.replot_curve(ax, curve, plot_kwargs)
  File "C:\Users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\figureerrorsmanager.py", line 118, in replot_curve
    new_curve = ax.replot_artist(curve, errorbars=True, **plot_kwargs)
  File "C:\Users\ilb25526\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 379, in replot_artist
    workspace_index = workspace.getIndexFromSpectrumNumber(spec_num)
Boost.Python.ArgumentError: Python argument types in
    None.getIndexFromSpectrumNumber(Workspace2D, NoneType)
did not match C++ signature:
    getIndexFromSpectrumNumber(class Mantid::API::MatrixWorkspace {lvalue} self, int spec_no)
```

2020-05-04 11:19 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +            if spec_num is not None:
Since this if-statement is the only thing inside the else it can be changed to `elif`.

2020-05-05 07:21 UTC, NickDraper commented
Fixing that requires some of the changes in #28639 I'll take this pr to draft and merge that in and close that PR.

2020-05-06 14:23 UTC, PhilColebrooke requested changes
If I open the plot options on a sample logs plot, change something in the Curves tab, click apply, then change something else and click apply again, I get this error:
```
Traceback (most recent call last):
  File "C:\Users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\figureerrorsmanager.py", line 119, in replot_curve
    new_curve = ax.replot_artist(curve, errorbars=True, **plot_kwargs)
  File "C:\Users\ilb25526\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 394, in replot_artist
    workspace, spec_num = self.get_artists_workspace_and_spec_num(artist)
  File "C:\Users\ilb25526\mantid\Framework\PythonInterface\mantid\plots\mantidaxes.py", line 200, in get_artists_workspace_and_spec_num
    raise ValueError("Artist: '{}' not tracked by axes.".format(artist))
ValueError: Artist: '[<matplotlib.lines.Line2D object at 0x00000155D8340130>]' not tracked by axes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\presenter.py", line 66, in apply_properties
    tab.apply_properties()
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\presenter.py", line 71, in apply_properties
    self._replot_selected_curve(plot_kwargs)
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\presenter.py", line 129, in _replot_selected_curve
    new_curve = FigureErrorsManager.replot_curve(ax, curve, plot_kwargs)
  File "C:\Users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\figureerrorsmanager.py", line 121, in replot_curve
    new_curve = cls._replot_mpl_curve(ax, curve, plot_kwargs)
  File "C:\Users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\figureerrorsmanager.py", line 136, in _replot_mpl_curve
    remove_curve_from_ax(curve)
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\plotconfigdialog\curvestabwidget\__init__.py", line 70, in remove_curve_from_ax
    curve.remove()
TypeError: remove() takes exactly one argument (0 given)
```

2020-05-06 14:23 UTC, PhilColebrooke commented on docs/source/release/v5.1.0/mantidworkbench.rst
> +- Plots extracted from "Show Sample Logs" by double clicking the plot can now be converted to a python script, just like other workbnehc plots.
```suggestion
- Plots extracted from "Show Sample Logs" by double clicking the plot can now be converted to a python script, just like other Workbench plots.
```

2020-05-19 11:35 UTC, PhilColebrooke requested changes
I'm still getting the error when I change a setting in the curves tab, click apply, then change something again and click apply.

I also get this error when I click the Fit button on a sample logs plot:
```
Traceback (most recent call last):
  File "C:\Users\ilb25526\mantid\qt\applications\workbench\workbench\plotting\figuremanager.py", line 356, in fit_toggle
    self.fit_browser.show()
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\fitpropertybrowser\fitpropertybrowser.py", line 143, in show
    self._add_spectra(allowed_spectra)
  File "C:\Users\ilb25526\mantid\qt\python\mantidqt\widgets\fitpropertybrowser\fitpropertybrowser.py", line 75, in _add_spectra
    self.addAllowedSpectra(name, spec_list)
TypeError: index 0 has type 'NoneType' but 'int' is expected
```

2020-05-20 12:27 UTC, NickDraper commented
Pated from slack:

> Phil I can't reproduce the crash on #28636 on my branch, are you sure you pulled in the changes?  Otherwise we need a call so I can see how you crash it.
> 
> 
> 
> 
> 
> 
> Phil Colebrooke:house_with_garden:  9:45 AM
> Call
> Call Ended
> Ended at 9:48 AM - Lasted 3 minutes
> 
> You both joined
> 
> Nick Draper  9:52 AM
> I can reproduce the fit button crash though, so thanks for that.
> :sunglasses:
> 1
> 
> 
> Phil Colebrooke:house_with_garden:  11:35 AM
> So I'm still seeing the error when I just check out your branch without merging master... :thinking_face:
> 
> Nick Draper  12:42 PM
> Could you give me the exact steps you follow to get an error for me to try to reproduce (edited) 
> 
> Phil Colebrooke:house_with_garden:  12:47 PM
> Basically the same as what you were doing on the call. I run the script in your PR to produce a sample logs plot, open the options, change something in the curves tab, click apply, changing something again, click apply
> 12:48
> Maybe we need to get a third person to try to see if there's something wrong with my setup
> 
> Nick Draper  12:48 PM
> what is the top commit message if you type git log?
> 
> Phil Colebrooke:house_with_garden:  12:53 PM
> "Ensure the graph is replotted with stored artist info"
> 
> Nick Draper  12:53 PM
> Hmm, that is the most recent commit.
> 12:54
> Let me solve the fit button issue, and then we will try to get someone else involved

2020-05-20 14:18 UTC, ConorMFinn commented
Fails for me too. The second applied change causes an error:

Note: This does not just happen when apply is clicked. Changing something, clicking okay, and then reopening the options and changing something else causes the same error.
```Traceback (most recent call last):
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plotting/figureerrorsmanager.py", line 119, in replot_curve
    new_curve = ax.replot_artist(curve, errorbars=True, **plot_kwargs)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 466, in replot_artist
    self.remove_artists_if(lambda art: art == artist)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 318, in remove_artists_if
    return self._remove_artists_if(unary_predicate)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 380, in _remove_artists_if
    is_empty = self._remove_artist_info_if(artist_info, unary_predicate)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 403, in _remove_artist_info_if
    is_empty_list = [workspace_artist.remove_if(self, unary_predicate) for workspace_artist in artist_info]
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 403, in <listcomp>
    is_empty_list = [workspace_artist.remove_if(self, unary_predicate) for workspace_artist in artist_info]
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 1491, in remove_if
    self._remove(axes, artists_to_remove)
  File "/home/conor/repos/mantid-review/Framework/PythonInterface/mantid/plots/mantidaxes.py", line 1499, in _remove
    artist.remove()
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 151, in remove
    self._remove_method(self)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1783, in <lambda>
    line._remove_method = lambda h: self.lines.remove(h)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/presenter.py", line 66, in apply_properties
    tab.apply_properties()
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py", line 70, in apply_properties
    self._replot_selected_curve(plot_kwargs)
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py", line 128, in _replot_selected_curve
    new_curve = FigureErrorsManager.replot_curve(ax, curve, plot_kwargs)
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plotting/figureerrorsmanager.py", line 121, in replot_curve
    new_curve = cls._replot_mpl_curve(ax, curve, plot_kwargs)
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plotting/figureerrorsmanager.py", line 136, in _replot_mpl_curve
    remove_curve_from_ax(curve)
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/plotconfigdialog/curvestabwidget/__init__.py", line 70, in remove_curve_from_ax
    curve.remove()
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 151, in remove
    self._remove_method(self)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1783, in <lambda>
    line._remove_method = lambda h: self.lines.remove(h)
ValueError: list.remove(x): x not in list```

2020-05-22 07:01 UTC, martyngigg commented
For independent verification I can also reproduce the error after clicking apply twice in the plot options. Does this help reproduce the problem:
![sample-logs-plot-options](https://user-images.githubusercontent.com/733773/82640054-d32c0800-9c01-11ea-91cc-91a9dcafcabc.gif)

I tried both checking out the branch and also doing `git test-pr 28636` so that it was merged with master and the result was the same.

2020-05-22 13:21 UTC, PhilColebrooke submitted a review, later dismissed
This works well now 👍 just got a couple of suggestions to tidy up the code

2020-05-22 13:21 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +        #check if it is a sample log plot
```suggestion
        # check if it is a sample log plot
```

2020-05-22 13:21 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +            #error bars never make sense for sample log plots
This comment is repeated further down where you set `errorbars` to false.
```suggestion
        if spec_num is None:
```

2020-05-22 13:21 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +            errorbars=False
```suggestion
            errorbars = False
```

2020-05-22 13:21 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +                new_artist = self.plot(workspace, **kwargs)[0]
You have the if and the else both doing the same thing
```suggestion
            new_artist = self.plot(workspace, **kwargs)[0]
```

2020-05-22 13:21 UTC, PhilColebrooke commented on Framework/PythonInterface/mantid/plots/mantidaxes.py
> +        :param log_name: string. The name of the plotted log, the
```suggestion
        :param log_name: string. The name of the plotted log
```

2020-05-22 13:21 UTC, PhilColebrooke commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratorlines.py
> +        kwargs.update({"LogName":"my_log","ExperimentInfo":0,"Filtered":True})
```suggestion
        kwargs.update({"LogName": "my_log", "ExperimentInfo": 0, "Filtered": True})
```

2020-05-27 10:02 UTC, alicerussell1 approved these changes
Looks good to me, works well 👍

2020-05-27 13:48 UTC, merged