New Settings and Images
mantidproject/mantid pull request #28656
Opened 2020-05-07 07:15 UTC by DanielMurphy22

**Description of work.**

**To test:**

Build Docs and check Settings.html makes sense and is formatted correctly:
- Are images the right size? Do sections of text line up with images?
- Does the link work correctly?
- Are explanations clear?

Fixes #27949

*This does not require release notes* because **documentation**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-05-07 16:24 UTC, cailafinn requested changes
Just a couple of *incredibly* minor nitpicks, otherwise builds correctly and looks good.

2020-05-07 16:24 UTC, ConorMFinn commented on docs/source/workbench/settings.rst
>  - Facility and default Instrument: These settings control the default settings used
```suggestion
- Facility and Default Instrument: These settings control the default settings used
```

2020-05-07 16:24 UTC, ConorMFinn commented on docs/source/workbench/settings.rst
> +- Choose which Algorithms categories to show in the Algorithm Toolbox.
```suggestion
- Choose which Algorithm categories to show in the Algorithm Toolbox.
```

2020-05-11 15:24 UTC, cailafinn approved these changes
Looks good to me now, nice work 👍

2020-05-12 08:56 UTC, merged