Support nonorthogonal axes on > 3D workspaces.
mantidproject/mantid pull request #28701
Opened 2020-05-19 07:11 UTC by martyngigg

**Description of work.**

**To test:**

See script in the related issue for generating a workspace to test this functionality.
* Try enabling nonorthogonal axes mode
* Ensure that when one of the dimensions selected is not Q then the nonorthogonal button is disabled and then switching back enables the button again.
* When nonorthogonal mode becomes available then the peaks/line viewer should become disabled.

Fixes #28698 

*This does not require release notes* because **nonorthogonal axes are new in this version**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-05-19 14:38 UTC, AndreiSavici requested changes
If I add to the script
```python
ConvertToMD(InputWorkspace='dgs',
            QDimensions='Q3D',
            Q3DFrames='HKL',
            QConversionScales='HKL',
            Uproj='1,1,0',
            Vproj='1,-1,0',
            Wproj='0,0,1',
            OutputWorkspace='md1')
```
then I expect that the angle between the axes to be 90 degrees. So it should take into account the W matrix. I've also found that MDNorm does not update the W matrix, so I will open an issue for myself on that.

2020-05-19 15:00 UTC, martyngigg commented
Thanks. I added code to take that into account. I'll find out why it's not working.

2020-05-19 15:11 UTC, martyngigg commented
@AndreiSavici Is this not correct? ![Screenshot from 2020-05-19 16-08-04](https://user-images.githubusercontent.com/733773/82343658-08aad880-99eb-11ea-9317-a4b46b88f52e.png)

2020-05-20 04:26 UTC, AndreiSavici commented
It is correct in this particular case. But the fact that the dimensions are not `[H,0,0]` and so on means that if I change either the x or y axis means that I will disable the non-orthogonal projections, and I cannot recover them any more.

2020-05-20 07:21 UTC, martyngigg commented
Thanks. I hadn't spotted that each dimension knew whether it was a Q dimension or not so my check was falling over - I've fixed this now. The angle looks okay now I think.

2020-05-20 17:02 UTC, AndreiSavici approved these changes
Thanks. Nice work. It behaves like expected

2020-05-21 16:02 UTC, merged