28514 sliceviewer title add ws name
mantidproject/mantid pull request #28762
Opened 2020-06-01 11:13 UTC by NickDraper

**Description of work.**

**To test:**
Files are in unit test data
``` python
Load(Filename='HET15869.raw', OutputWorkspace='HET15869_WS2D') # 2020-06-01T10:29:03.655998000 execCount: 1
Load(Filename='TOPAZ_3680_5_sec_MDEW.nxs', OutputWorkspace='TOPAZ_3680_5_sec_MDEW')
BinMD(InputWorkspace='TOPAZ_3680_5_sec_MDEW', AlignedDim0='Q_lab_x,-15.0,15.0,100', AlignedDim1='Q_lab_y,-15.0,15.0,100', AlignedDim2='Q_lab_z,-0.03500000000000121,0.0649999999999988,1', OutputWorkspace='An MDHisto Workspace')
```
1. Show the sliceviewer for each of the three workspace types.
1. For each, the window title should include the workspace name being plotted.

Fixes #28514

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-08 13:49 UTC, PhilColebrooke commented
Could you rebase onto master to resolve conflicts and make it so only the changes from this PR are shown?

2020-06-09 08:28 UTC, NickDraper commented
@PhilColebrooke Done

2020-06-09 09:25 UTC, PhilColebrooke requested changes
The window title now contains the workspace name, good stuff 👍

I noticed this line is still in the view file, I'm guessing it can be removed:
https://github.com/mantidproject/mantid/blob/b2b8f9b29a649d22311224f7ea16fb8ab08fd904/qt/python/mantidqt/widgets/sliceviewer/view.py#L468

Also does this need release notes?

2020-06-09 10:46 UTC, NickDraper commented
Removed that line, This does not need release notes on its own as there are others there already about improving the ui that cover this as well.

2020-06-09 14:42 UTC, PhilColebrooke approved these changes
⭐⭐⭐

2020-06-10 06:57 UTC, merged