Translate sample transmission calculator into workbench
mantidproject/mantid pull request #28782
Opened 2020-06-03 13:53 UTC by Harrietbrown

This PR adds the sample transmission calculator, originally only available in mantidplot, to workbench.

**To test:**

1. Build mantid and open `Interfaces->General->Sample Transmission Calculator`
2. Enter in some values for histogram bins and chemical cormula.
3. Click Calulate and check that the plot is updated with the correct output.
4. Try with invalid inputs and check that the validator allerts you that they are incorect.
1. Try in both single and multiple types for histogram and number and mass density.

Fixes #28691 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-04 13:08 UTC, StephenSmith25 requested changes
Looks good, function is very similar to the MantidPlot interface, just some minor comments.

Things I found from testing:
- This creates a new interface in MantidPlot as well, so there are two Sample transmission entries in MantidPlot now, one of which doesn't work.
- Sometimes the numbers on the plot axes are not formatted well, e.g try 
`Chemical: C - Low: 0, width: 1, High:5` 
For me the y axis looks a bit off - maybe need to fix the precision of the numbers.
- If you type something wrong in the chemical box it brings up a warning and sends the interface to the back, can be slightly annoying. 

- For me the help button doesn’t bring up the Qt help docs and instead opens a webpage.

2020-06-04 13:08 UTC, StephenSmith25 commented on scripts/SampleTransmissionCalculator/stc_presenter.py
> +        external_url = 'http://docs.mantidproject.org/nightly/interfaces/Sample Transmission Calculator.html'
This currently isn’t opening the Qt help pages for me. I'd be inclined to change this to use InterfaceManger directly, so something like
```
gui_name = 'Sample Transmission Calculator'
InterfaceManager().showCustomInterfaceHelp(gui_name)
```
should work.

2020-06-05 13:39 UTC, Harrietbrown commented on scripts/SampleTransmissionCalculator/stc_view.py
> +        getattr(self, 'histogram_err').setText('')
It was a holdover from using it in the `set_error_indicator` function, you're right it is fine just calling it on the attribute directly.

2020-06-09 13:30 UTC, Harrietbrown commented
- I have stoped the new gui from appearing in mantidplot.
- I don't have a validator for the chemical formula but I've had it attempt to run the algorithm and catch a runtime error.
- The issue with the plot problem is a result of have such a small difference between the transmission I'm not sure if the input values you have used are realistic enough to come up often.
- The help button should be fixed now.

2020-06-09 15:00 UTC, StephenSmith25 requested changes
I'm happy with this, thanks for all the changes, they've addressed all the issues I had. Just two small things left:

2020-06-15 11:41 UTC, martyngigg commented on scripts/test/sample_transmission_calculator/CMakeLists.txt
> +pyunittest_add_test(${CMAKE_CURRENT_SOURCE_DIR} python.scripts
Minor comment: Can we put `python.scripts.sampletransmissioncalculator` here? This string is used as the prefix in the test name that ctest uses. It makes running things with `ctest R` easier if they have a more identifiable prefix.

2020-06-16 12:41 UTC, StephenSmith25 reviewed
Looking good, just two minor comments and its good to go for me.

2020-06-16 12:41 UTC, StephenSmith25 commented on docs/source/release/v5.1.0/mantidworkbench.rst
> +- The Sample Transmission Calculator is now implemented in workbench.
This line appears twice.

2020-06-16 12:41 UTC, StephenSmith25 commented on scripts/test/sample_transmission_calculator/stc_view_test.py
> +    @unittest.skipIf(not hasattr(QHBoxLayout, 'replaceWidget'), 'Invalid qt version')
Given these are running in QT5 now we should be able to remove these `unittest.skipIf` statements now.

2020-06-17 08:56 UTC, StephenSmith25 reviewed
Good work, code looks good 👍 .

I just went for a last test and it appears to me that the multiple options doesn't behave exactly the same as the option in MantidPlot. For instance, the one in workbench will only accept three values, whereas MantidPlot accepts any odd number of values. Is this intentional?

2020-06-22 09:35 UTC, Harrietbrown commented
I'm not sure what you mean. Do you mean the input wavelength range? because trying on plot it is only accepting when 3 values are given

2020-06-22 09:45 UTC, StephenSmith25 commented
> I'm not sure what you mean. Do you mean the input wavelength range? because trying on plot it is only accepting when 3 values are given

Maybe I was wrong about this then, if so I'll approve. But this was changing the Input wavelength range type to `multiple`. In plot it was accepting any odd number of values, whereas in Workbench it was only accepting three values.

2020-06-22 10:15 UTC, Harrietbrown commented
Ok that change should handle it.

2020-06-24 08:10 UTC, StephenSmith25 approved these changes
Looks good to go 👍

2020-06-25 06:47 UTC, merged