Reset global variables in python scripts when running entire script
mantidproject/mantid pull request #28796
Opened 2020-06-05 13:16 UTC by Harrietbrown

**Description of work.**

This PR resets the global variable list in workbench python interpreter when running a whole script, this should not reset the variables if only running a partial script.

**Report to:** James Lord

**To test:**

1. Run the following python script
```
x=5
print(x)
```
2. remove the `x=5` line and highlight the print statment and run only that line. the x varable should still be kept.
3. Run the whole script without the `x=5` line, it should reset the varables so `x` will not be assigned.

Fixes #27185

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-08 09:46 UTC, NickDraper requested changes
The changes are good, and work fine, but would it be possible to add a test for this behaviour into test_interpreter.py?

2020-06-09 14:19 UTC, Harrietbrown commented
I've added a test for the functionality.

2020-06-10 09:52 UTC, NickDraper approved these changes
Great test added and works well, good to merge as soon as the builds are all happy.  Good work.

2020-06-10 11:25 UTC, martyngigg commented on qt/python/mantidqt/widgets/codeeditor/test/test_interpreter.py
> +        w = PythonFileInterpreter(content='x=\'this is a string\'\r\nprint(x)')
Nice test :+1:

2020-06-10 11:26 UTC, merged