Workbench sliceviewer: Dynamically rebin MDEventWorkspaces on zoom
mantidproject/mantid pull request #28832
Opened 2020-06-11 16:26 UTC by martyngigg

**Description of work.**

Adds dynamic rebinning to the sliceviewer. When the axes limits change on the view, if the workspace is an MDEventWorkspace, then the data is rebinned to the limits of the view rather than the full extent of the dimensions.

Zooming on scroll of the mouse wheel has also been enabled.

**To test:**

The following script can be used for a basic test of the functionality. It creates an `MDEventWorkspace`, fakes some data and creates some fake peaks.

Run the script and show the sliceviewer and play with the zooming:
* zoom with the magnifier tool and reset up to home - ensure the limits are as expected when drawing the zoom rectangle after the zooming completes
* zoom on scroll and check the data is as expected
* activate the peaks viewer and ensure the peak selection still zooms to the peak and when zooming in on the data the peaks stays where it should.
* check the non-orthogonal view works and vary the setub parameters to check

```python
mdws = CreateMDWorkspace(Dimensions=3,
                         Extents='-10,10,-10,10,-10,10',
                         Names='A,B,C',
                         Units='r.l.u.,r.l.u.,r.l.u.',
                         Frames='HKL,HKL,HKL')
expt_info = CreateSampleWorkspace()
mdws.addExperimentInfo(expt_info)
a, b, c = 1, 1, 1
alpha, beta, gamma = 90, 90, 90
SetUB(mdws, a, b, c, alpha, beta, gamma)
FakeMDEventData(InputWorkspace=mdws, PeakParams='500000,0,0,0,3')
run_number = 1
sxd_ws = LoadEmptyInstrument(InstrumentName='SXD')
AddSampleLog(sxd_ws, 'run_number', str(run_number), 'Number')
peak_ws = CreatePeaksWorkspace(InstrumentWorkspace=sxd_ws, NumberOfPeaks=0)
peak_ws.mutableRun().addProperty('run_number', run_number, True)
SetUB(peak_ws, a, b, c, alpha, beta, gamma)
# Add a new peak
AddPeakHKL(peak_ws, [2, 0, 0])
AddPeakHKL(peak_ws, [2, 1, 4])
# integrate to get a sphere with a background
peak_ws_sphere = IntegratePeaksMD(InputWorkspace=mdws,
                                  PeaksWorkspace=peak_ws, PeakRadius=0.2,
                                  BackgroundInnerRadius=0.7,
                                  BackgroundOuterRadius=0.9)

```

Also check that opening the viewer on the `mdws_svrebinned` actually shows the view for the original `mdws` but updates the window title to show this.

Pull request #28506 also has a script and data links to real examples. Test these too.

Fixes #28689
Fixes #28579 

*This does not require release notes* because **we'll update the sliceviewer release notes in one go before 5.1**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-12 11:06 UTC, NickDraper commented
One question with the zooming.  Would it be possible to make the right mouse click zoom out when on the zoom tool?  The instrument scientists mentioned this I remember.

2020-06-12 11:08 UTC, NickDraper commented
Can we drop the log level of the BinMD rebin commands, moving the mousewheel for zoom quickly overwhelms the log when set at the default notice level.

2020-06-12 11:19 UTC, NickDraper commented
Arguably unrelated, but found while testing this:
If you already have the PeakViewer Open and then click Non-Orthogonal Axes, it disables the Peaks Viewer button, but leaves the existing Peaks lists open and functional.

2020-06-12 11:24 UTC, NickDraper commented
When you scroll the mouse wheel, by say 4-5 clicks, The logs fill with 4-5 BinMD algorithms, but the screen image visibly updates only 2-3 times.  Is there a possible optimization perhaps to collect the mouse commands over a short window and then BinMD to that level?  Perhaps something for the future.

2020-06-12 11:30 UTC, NickDraper requested changes
Unhandled Exception:
Steps:
1. Show sliceviewer on mdws
1. Click lineplots on
1. click non orthogonal axes

```
BinMD-[Notice] BinMD successful, Duration 0.03 seconds
Python-[Error] Traceback (most recent call last):
  File "e:\mantid\code\qt\python\mantidqt\widgets\sliceviewer\view.py", line 321, in on_line_plots_toggle
    self.presenter.line_plots(state)
  File "e:\mantid\code\qt\python\mantidqt\widgets\sliceviewer\presenter.py", line 171, in line_plots
    self.view.data_view.remove_line_plots()
  File "e:\mantid\code\qt\python\mantidqt\widgets\sliceviewer\view.py", line 202, in remove_line_plots
    all_axes[2].remove()
IndexError: list index out of range
```

2020-06-12 12:20 UTC, NickDraper commented
Probably separate issue:
Plot options that do not apply to sliceviewer

sliceviewer title should be disabled, or retained
steps:
1.  Open the sliceviewer
1. click the cog icon and set a title, click ok
1. Title appears, but is removed again on any redraw such a zooming..

Warning from functionality that does not apply here:
Steps: 
1. Open sliceviewer
1. click the cog icon
1. Tick the `(Re-)Generate automatic legend`
1. click ok

`WARNING:matplotlib.legend:No handles with labels found to put in legend.`

We should prevent that option for the sliceviewer.

2020-06-12 12:22 UTC, NickDraper commented
More an observation:
1. With the pan button selected any click (left or right) without any dragging on the plot causes a BinMD call.

2020-06-12 12:25 UTC, NickDraper commented
Unexpected behaviour with mdws_rebinned:
1. plot mdws_rebinned in sliceviewer
1. use the pan tool, any attempt to move returns to the "home" position
1. use the zoom tool or mouse wheel, zooming does not happen you stay in the "home" position

2020-06-12 12:28 UTC, NickDraper commented
Losing the axis labels:
Steps:
1. show anything in sliceviewer
1. Show the line plots
1. remove the lineplots, by clicking the toolbar button again
1. The axes of the sliceviewer have lost their labels.
![image](https://user-images.githubusercontent.com/1017173/84502631-a3c46480-acb0-11ea-8e38-0ceaee12a005.png)
![image](https://user-images.githubusercontent.com/1017173/84502635-a921af00-acb0-11ea-81b4-7049ca1fcc9e.png)

2020-06-12 12:34 UTC, NickDraper commented
Zooming from a tight zoom on a moderate sized workspace is very slow.
steps:
1. Load MAR11060 and show in sliceviewer
1. Zoom in close to a small region
1. use the mouse wheel to zoom out.
1. I know the home button is fast but many people will just use the mouse, and in meetings many users did not know what the home button did, even after using workbench.

2020-06-12 12:45 UTC, NickDraper commented
This is really good, other than the issues I raised above I spent quite some time zooming in and out of data, and was really pleased with how everything seemed to work nicely together, even when I set it to Log Log axes.

2020-06-12 13:30 UTC, martyngigg commented
> One question with the zooming. Would it be possible to make the right mouse click zoom out when on the zoom tool? The instrument scientists mentioned this I remember.

This is probably fine. I don't think we are using right-click for anything else here. Agreed offline that it will zoom out like clicking "home".

> Can we drop the log level of the BinMD rebin commands on zooming, moving the mousewheel for zoom quickly overwhelms the log when set at the default notice level.

Yes I meant to do this. Thanks for the reminder.

> When you scroll the mouse wheel, by say 4-5 clicks, The logs fill with 4-5 BinMD algorithms, but the screen image visibly updates only 2-3 times. Is there a possible optimization perhaps to collect the mouse commands over a short window and then BinMD to that level? Perhaps something for the future.

I had thought about this, admittedly not very hard, and couldn't easily see away of say I know your done. Yes we could say if you get something within a small time window I suppose. It just seemed quite responsive even on my laptop so I left it using the simple solution. This is for MD workspaces though and MatrixWorkspaces have their own world of pain here.

I'll address the bugs that you found.

2020-06-15 15:15 UTC, martyngigg commented
I've fixed all of the bugs found with the exception of the peaksviewer one as I need to implement the peaks on the nonorthogonal view anyway.

I'll also create a separate issue to review the settings screen for the sliceviewer.

2020-06-16 13:26 UTC, NickDraper submitted a review, later dismissed
All good now, really nice to see this added.

2020-06-17 06:37 UTC, martyngigg commented
@NickDraper I've fixed the conflicts here but a quick retest might be good due after adding the read out table changes.

2020-06-17 08:26 UTC, martyngigg commented
Pascal has provided some feedback on the testing instance that I set up and I might as well address it here.
It concerns showing the slice viewer for an MDHistoWorkspace that still has a link to the original MDEvent. In this case we need to show the number of bin controls as we can always go back to the original workspace.

2020-06-22 07:29 UTC, martyngigg commented
I haven't heard anything further on this yet. @NickDraper Would you mind giving this a quick retest? The main addition is that the view will now show on an MDEventWorkspace if it is attached to an MDHistoWorkspace, with the window title updated to reflect this.

2020-06-24 08:35 UTC, NickDraper requested changes
So I mentioned the mouse over details box not updating on zoom, but I've found an uncaught exception as well

if you scroll the mouse when it is over the axes labels you get  (actually anywhere on the plot canvas that is not the plot)
```
Traceback (most recent call last):
  File "E:\mantid\code\external\src\ThirdParty\lib\python3.8\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "e:\mantid\code\qt\python\mantidqt\widgets\sliceviewer\zoom.py", line 49, in zoom_fun
    x_left = xdata - cur_xlim[0]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```


![image](https://user-images.githubusercontent.com/1017173/85522669-df8af280-b5fd-11ea-9efd-e4e666518bc1.png)

2020-06-24 09:39 UTC, martyngigg commented
Thanks, @NickDraper. I've fixed those 2 issues.

2020-06-24 10:01 UTC, NickDraper approved these changes
Excellent work, this is good to be merged now.

2020-06-25 06:45 UTC, merged