Add fitting capability to Eng Diff UI fittingn tab
mantidproject/mantid pull request #28895
Opened 2020-06-22 10:40 UTC by RichardWaiteSTFC

**Description of work.**
Adds the fit property browser to toolbar.
Allows for subtraction of background (so can fit all spectra in a single fit).
Can now load in data as d-spacing or TOF

**To test:**
(1) Perform calibration and focusing as per instructions in PR #28393  
(or download this file [Uploading ENGINX_305761_bank_1.zip…])
(2) Toggle the fit property browser using the `Fit' button on the toolbar.
(3) Add some functions and fit
(4) Play with background parameter (column 4 onwards in table) before and after the subtract background is set to True (it should update the background if set to True)
(5) Select a row for which subtract background is set to True and click the `Inspect Background' button - it should pop up an external figure which will also update as the parameters are changed.

Partially fixes #27780

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-26 15:19 UTC, cailafinn requested changes
Attempting to launch mantid results in this error. I think it may be to do with loading matplotlib before the backend is properly selected. 
```
Traceback (most recent call last):
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/app/start.py", line 192, in start
    exit_value = start_workbench(app, options)
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/app/start.py", line 127, in start_workbench
    main_window.setup()
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/app/mainwindow.py", line 163, in setup
    self.ipythonconsole = JupyterConsole(self)
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plugins/jupyterconsole.py", line 46, in __init__
    font_family=font.family(), font_size=font.pointSize())
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/jupyterconsole.py", line 60, in __init__
    shell.ex(startup_code)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2423, in ex
    exec(cmd, self.user_global_ns, self.user_ns)
  File "<string>", line 3, in <module>
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plotting/backend_workbench.py", line 28, in <module>
    from workbench.plotting.figuremanager import (QAppThreadCall, new_figure_manager as new_figure_manager_impl,
  File "/home/conor/repos/mantid-review/qt/applications/workbench/workbench/plotting/figuremanager.py", line 31, in <module>
    from mantidqt.widgets.fitpropertybrowser import FitPropertyBrowser
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/fitpropertybrowser/__init__.py", line 12, in <module>
    from .fitpropertybrowser import FitPropertyBrowserBase, FitPropertyBrowser
  File "/home/conor/repos/mantid-review/qt/python/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", line 16, in <module>
    import matplotlib.pyplot as plt
AttributeError: module 'matplotlib' has no attribute 'pyplot'
```

2020-06-30 15:35 UTC, RichardWaiteSTFC commented on scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_toolbar.py
> +                # action = self.addAction(get_icon(mdi_icon), text, getattr(self, callback))
good spot removed

2020-06-30 16:58 UTC, RichardWaiteSTFC commented on Framework/PythonInterface/plugins/algorithms/EnggEstimateFocussedBackground.py
> +            if nwindow < 3:
Not sure what you mean here. The xwindow has to be odd, greater than three and less than the number of of bins. I could combine these conditions as so?
```
if 3  <= nwindow < nbins:
	if not nwindow % 2:
		nwindow += 1
else
	# not effective due to edge effects of the convolution
	raise RuntimeError(f"The convolution window ({nwindow} points) must have at least three points but less than the length of the data ({nbins} points)")
'''

2020-07-01 08:56 UTC, ConorMFinn commented on Framework/PythonInterface/plugins/algorithms/EnggEstimateFocussedBackground.py
> +            if nwindow < 3:
So my reasoning was that `3` appears to be a magic number and is used in a couple of places to say there must be this many points. My thinking is that it should be moved to a variable like `MINIMUM_POINTS` or something so you can add a comment saying why it needs to be 3.

2020-07-17 14:48 UTC, cailafinn requested changes
Code is looking good to me now. Did notice during testing that repeadedly clicking the SubtractBG checkbox appears to be either applying or removing the subtraction multiple times. The resulting plot begins to look fairly warped after a few clicks.

2020-07-17 15:08 UTC, RichardWaiteSTFC commented
> Code is looking good to me now. Did notice during testing that repeadedly clicking the SubtractBG checkbox appears to be either applying or removing the subtraction multiple times. The resulting plot begins to look fairly warped after a few clicks.

Yep good spot. seems to be a bug that got introduced when I refactored to put stuff in model. For some reason the background subtraction box doesn't uncheck but it does trigger the background to be added back...I'm looking into it.

2020-07-22 08:46 UTC, cailafinn requested changes
Code looks good and the new fitting and background functionality works really well. 

Should've spotted this earlier, but could you add some release notes and add the new functionality to the Engineering Diffraction documentation?

2020-07-22 14:57 UTC, cailafinn approved these changes
Thanks for adding those docs. This looks good to me now. Awesome work 👍

2020-07-22 15:56 UTC, RichardWaiteSTFC commented
> Thanks for adding those docs. This looks good to me now. Awesome work 👍

Thanks for reviewing it - turned out to be a bit of a slog!

2020-07-24 13:43 UTC, merged