Update introduction to python documentation
mantidproject/mantid pull request #28923
Opened 2020-06-26 09:56 UTC by StephenSmith25

**Description of work.**

This PR makes a few adjustments to the introduction to python course, namely:

- Removes a reference to python 2, which is no longer relevant
- Updates the file handling to use the ``with`` statement.
- A small example of using a nametuple, as it is a useful collection due to the clarity of the contents it provides.

**To test:**
 - Build the documentation and check everything looks correct.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-06-30 07:50 UTC, Harrietbrown requested changes
just thins one thing and it will be good to go.

2020-06-30 07:50 UTC, Harrietbrown commented on docs/source/tutorials/introduction_to_python/working_with_files.rst
> +       file.close()
You don't need to close the file when using with.

2020-06-30 08:09 UTC, Harrietbrown commented on docs/source/tutorials/introduction_to_python/solutions_to_exercises.rst
>     #for i in range(1,21):
This should also be uncommented.

2020-07-02 14:39 UTC, StephenSmith25 commented on docs/source/tutorials/introduction_to_python/solutions_to_exercises.rst
>     #for i in range(1,21):
Ah yes missed this, thank you 👍

2020-07-07 14:12 UTC, Harrietbrown approved these changes
Good Job, the example code is correct as expected.

2020-07-09 10:04 UTC, merged