28809 python function signatures
mantidproject/mantid pull request #28953
Opened 2020-07-01 11:48 UTC by ConorMFinn

**Description of work.**
Replaces the generation of docstrings and algorithm function signatures with lazy versions. This essentially means that they are only generated when they are requested. The intention is to reduce the amount of time and memory spent initialising all the python algorithms at startup. 

Note: Due to the way that the code editor completion works, this currenly does not affect the time to boot the workbench. All of the information that would normally be generated lazily is accessed on startup. The intention is to investigate and implement changing this in a future PR. 

**To test:**
Workbench:
1. Boot workbench
2. In the code editor enter a python algorithm and an open bracket (such as `rebin(`)
3. Check that the correct signature appears.
4. Switch to the IPython Console
5. Perform step 2 again
6. Check that the signature and docstring are correct. 
7. Run `help(rebin)` or with some other algorithm and check the output makes sense. 

Python:
1. Start mantid python (`build/bin/mantidpython`)
2. `from mantid.simpleapi import *` (this should be quicker now, particularly on debug builds)
3. run `help(someAlgorithm)` and check the output is sane. 

Fixes #28809 

Contributes towards #28499 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-07-02 14:53 UTC, martyngigg requested changes
Just a few minor code comments to consider.

2020-07-02 14:53 UTC, martyngigg commented on Framework/PythonInterface/mantid/api/_workspaceops.py
> +    from mantid.simpleapi import LazyMethodSignature  # Import here to avoid circular depandancy.
Can we move the `LazyMethodSignature` & `LazyFunctionSignature` classes to `mantid.kernel.funcinspect` rather than having everything in `simpleapi`?

2020-07-02 14:53 UTC, martyngigg commented on Framework/PythonInterface/mantid/simpleapi.py
> +            # algm_object.initialize()
Can we remove the commented out code?

2020-07-02 14:53 UTC, martyngigg commented on Framework/PythonInterface/mantid/simpleapi.py
> +    # if input_prop not in algm_object:
Can we get rid of this too?

2020-07-02 14:53 UTC, martyngigg commented on Framework/PythonInterface/test/python/mantid/SimpleAPITest.py
> +        from mantid.simpleapi import rebin
Just out of interest. Is the import required for the test to pass now?

2020-07-13 10:32 UTC, martyngigg submitted a review, later dismissed
This looks really good now. I've tried both the IPython terminal and also the qtconsole and I've confirmed that the algorithms are not initialized on startup but when help or when function signatures are requested then they appear as before.

Good work.

2020-07-14 09:37 UTC, gemmaguest commented
@ConorMFinn There are conflicts

2020-07-15 10:42 UTC, martyngigg approved these changes

2020-07-16 10:37 UTC, merged