Remove reversible masking
mantidproject/mantid pull request #29004
Opened 2020-07-15 09:32 UTC by NickDraper

**Description of work.**
See #28776

**To test:**

TODO

Fixes #28776

TODO Release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-07-20 09:53 UTC, cailafinn requested changes
Changes make the masking algorithms much more intuitive. Just a couple of incredibly minor grammar nitpicks

2020-07-20 09:53 UTC, ConorMFinn commented on scripts/SANS/sans/algorithm_detail/mask_workspace.py
> +            # support MPI. Use a three step approach via a and  b instead.
```suggestion
            # support MPI. Use a two step approach via a and b instead.
```

2020-07-20 09:53 UTC, ConorMFinn commented on docs/source/release/v5.1.0/framework.rst
> +  ClearMaskedSpectra has been Removed as it no longer has a use,
```suggestion
  ClearMaskedSpectra has been removed as it no longer has a use,
```

2020-07-22 13:18 UTC, SimonHeybrock commented
Question: What about saved workspaces (prior this change) loaded back now. Do masked spectra get cleared? Should they?

2020-07-22 15:33 UTC, NickDraper commented
No we will not alter saved workspaces, I think this would be an unexpected change.  Just the algorithms will now clear the data as well as apply the mask flag.

2020-07-23 05:33 UTC, SimonHeybrock commented
> No we will not alter saved workspaces, I think this would be an unexpected change. Just the algorithms will now clear the data as well as apply the mask flag.

But then `ClearMaskedSpectra` should not be removed, otherwise users will not be able to clear that data?

2020-07-24 10:15 UTC, NickDraper commented
The only uses I have found in the code base have been immediate clearing of the data after using MaskInstrument.  So these will not cause a problem.  Are you aware of anyone actually saving uncleared data in files, or is this a theoretical problem?

2020-07-24 10:21 UTC, SimonHeybrock commented
I am not aware of anyone doing this, no.

2020-07-24 14:53 UTC, cailafinn approved these changes
Looks good to me now. This makes a lot more sense than the old workflow. Nice one 👍

2020-07-27 07:03 UTC, merged