DGSPlanner bug fixes
mantidproject/mantid pull request #29170
Opened 2020-08-11 16:31 UTC by AndreiSavici

**Description of work.**

Fixed issues in DGSPlanner interface

**To test:**
Start the DGSPlanner interface, preferably in workbench. In the UB section, start typing `-1` for one of the u or v vector components. It should not crash. 

Fixes #29164

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-08-12 09:46 UTC, DanielMurphy22 requested changes
The fix works well, and the coloring is great!

2020-08-12 09:46 UTC, DanielMurphy22 commented on scripts/DGSPlanner/InstrumentSetupWidget.py
> +                    val=val=int(value)
Should this line simply be:
```suggestion
                    val=int(value)
```

2020-08-12 12:35 UTC, peterfpeterson submitted a review, later dismissed
As advertised: doesn't crash.

2020-08-13 07:46 UTC, DanielMurphy22 approved these changes
Well done!

2020-08-13 08:19 UTC, merged