Remove TCMalloc on Windows
mantidproject/mantid pull request #29225
Opened 2020-08-25 15:12 UTC by MathieuTillet

**Description of work.**
Since the provided default allocator on windows is ok, there is no need for a custom allocator like TCMalloc on Windows (where it is not used anyhow), thus the block of code adding managing its inclusion is removed.
removed.

**To test:**
Check it still compiles on Windows.

WIP for #29054 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-08-25 16:23 UTC, martyngigg requested changes
Thanks for this, Mathieu.

The `TCMALLOC_LIBRARIES_LINKTIME` variable is also only used on Windows. Would you be able to remove this reference in all of the `CMakeLists.txt` files, as it is now not needed?

2020-08-26 06:06 UTC, MathieuTillet commented
I did it in a separate PR, #29202 .

2020-08-26 06:52 UTC, martyngigg commented
My apologies, I hadn't spotted the other PR. Thanks.

2020-08-26 06:52 UTC, martyngigg approved these changes

2020-08-26 07:25 UTC, merged