Python3 requires key instead of cmp keyword
mantidproject/mantid pull request #29431
Opened 2020-09-11 16:44 UTC by quantumsteve

**Description of work.**

In `sorted`, replace `cmp` keyword which removed from Python3. Given the complexity of the cmp function, [cmp_to_key](https://docs.python.org/3/library/functools.html#functools.cmp_to_key) was used to migrate to the new API while maintaining current functionality.

**Report to:** @mdoucet 

**To test:**

Execute the following:

```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

medium = 'air'
fpath = '/tmp/test.cfg'
db_list = range(179926, 179950)
    
first_run = 179926
last_run = 179935 #179949

LRDirectBeamSort(RunList=range(first_run,last_run+1), ComputeScalingFactors=True, 
    OrderDirectBeamsByRunNumber=False,
    SlitTolerance=0.06,
    IncidentMedium=medium, UseLowResCut=False, TOFSteps=200,
    ScalingFactorFile=fpath)
```

Fixes https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/15

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-09-14 20:13 UTC, peterfpeterson submitted a review, later dismissed
Looks good to me

2020-09-14 20:26 UTC, rosswhitfield requested changes
This should have tests. If it had tests this issue would have been fixed years ago.

2020-09-15 21:08 UTC, quantumsteve commented
@rosswhitfield @peterfpeterson Would you please review these changes?

2020-09-16 15:25 UTC, rosswhitfield approved these changes

2020-09-16 15:37 UTC, merged