Fix Y error labels in muon analysis results tables
mantidproject/mantid pull request #29434
Opened 2020-09-14 08:19 UTC by Harrietbrown

**Description of work.**

The output results table from Muon analysis should label the colombs with `Y0, Y1, Y2...` and `Y0_err, Y1_err, Y2_err...` for the values and errors respectivly. This pr links the two colombs so this label is propperly added to the errors.

**To test:**

1. Open Muon Analysis.
2. Load EMU20918.
3. Perform a fit.
4. Go to the results tab and output the results.
5. check that the colomns in the results table have the right labels linking values with their errors.

Fixes #29409 

*This does not require release notes* because it fixes a bug that was not in the previous release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-09-14 09:32 UTC, AnthonyLim23 commented
Functionality looks good. We do need to update the release notes and I think we should also update https://docs.mantidproject.org/nightly/concepts/TableWorkspaces.html to show the new functionality. What do you think @Harrietbrown ?

2020-09-14 09:33 UTC, AnthonyLim23 commented on scripts/Muon/GUI/Common/results_tab_widget/results_tab_model.py
> +                table.setLinkedYCol(table.columnCount()-1, table.columnCount()-2)
can we have something to explain why -1 and -2?

2020-09-14 14:08 UTC, AnthonyLim23 approved these changes, later dismissed
Documentation looks good and it works as expected.

2020-09-14 15:48 UTC, martyngigg requested changes

2020-09-14 15:48 UTC, martyngigg commented on Framework/PythonInterface/mantid/api/src/Exports/ITableWorkspace.cpp
> +           "set the data column associated with a given error column. ")
Nice spot that we were missing the set method exposed. Should this say **Get** here?

2020-09-14 15:48 UTC, martyngigg commented on Framework/PythonInterface/mantid/api/src/Exports/ITableWorkspace.cpp
> +           "set the data column associated with a given error column. ")
Could we capitalize the `Set` for consistency with the other methods?

2020-09-15 08:45 UTC, martyngigg approved these changes
Thanks for making those changes.

2020-09-15 08:45 UTC, martyngigg commented
Unrelated test failure.

2020-09-15 08:45 UTC, merged