Avoid hard crash in Indirect Energy Transfer load without TCP files
mantidproject/mantid pull request #29574
Opened 2020-09-23 14:43 UTC by clayton-tom

**Description of work.**
Add a check to avoid Energy Transfer from trying to access files from the ADS that haven't loaded correctly, letting it fail 'nicely' like the other tabs rather than hard crashing

**Report to:** Sanghamitra, Anthony

**To test:**
1. Turn off the data archive, download an IRIS .raw but NOT the three accompanying ICP files (e.g. IRIS00055127)
2. Interfaces -> Indirect -> Data reduction -> Energy transfer (default tab)
3. Input runs -> browse to the .raw and try to load it

Fixes #29554. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-09-23 15:25 UTC, AnthonyLim23 submitted a review, later dismissed
No longer crashes on a machine that use to. We will not put this in the release notes as it is a rare bug and more likely to confuse users.

Works on plot and workbench

2020-09-23 16:16 UTC, martyngigg requested changes

2020-09-23 16:16 UTC, martyngigg commented on qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
> +    return -1;
Should we not return the `defaultValue` in this case?

2020-09-24 13:38 UTC, martyngigg approved these changes

2020-09-24 13:39 UTC, merged