Add separate page for Sliceviewer releasen notes
mantidproject/mantid pull request #29591
Opened 2020-09-24 11:16 UTC by martyngigg

**Description of work.**

Adds a separate release notes page for the sliceviewer. It has had a significant number of new features that are worth highlighting on their own.

**To test:**

Build the docs and check they look okay with all of the images included.

Fixes #29506 

*This does not require release notes* because **it is release notes**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-09-24 16:49 UTC, DanielMurphy22 approved these changes
Really well done, pictures look great!
Easier to have this merged too before the other core stuff!

2020-09-24 17:00 UTC, DanielMurphy22 requested changes
Actually I should have pointed these out: http://developer.mantidproject.org/Standards/DocumentationGuideForDevs.html#how-to-define-titles-sections-etc
You should be able to batch commit now I've suggested the changes

2020-09-25 06:34 UTC, martyngigg commented on docs/source/release/v5.1.0/sliceviewer.rst
> +############
Thanks for the reminder of this and I wrote that page :facepalm:

2020-09-25 06:44 UTC, martyngigg commented
Thanks @DanielMurphy22. I've rebased and fixed the merge conflicts.

2020-09-25 08:48 UTC, DanielMurphy22 approved these changes
Images look great! Good to go.

2020-09-25 10:18 UTC, DavidFair commented
I didn't realise how many new things have gone into slice viewer, it's almost an entire release worth of features in a single area

2020-09-25 10:18 UTC, merged

2020-09-25 10:32 UTC, martyngigg commented
Yes I must admit I had to double check the last release too!