Change columns order and visibility in DrILL
mantidproject/mantid pull request #29595
Opened 2020-09-24 15:01 UTC by gui-co

**Description of work.**

**To test:**

Part of #29570 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-10-07 15:26 UTC, gvardany requested changes
There is a problem when changing the instrument or acquisition mode after having removed some columns. It seems it remembers the indices of the removed ones which are no longer relevant if you change the technique. Also could you add the add/remove actions to the edit menu as well? It could also be grouped like Edit->[Rows>[Add, Copy, Paste,...] , Columns>[Add/Remove] ]. Also please don't forget to add a section about these new features in the documentation.

2020-10-13 08:18 UTC, gui-co commented
The table is now reset when the instrument and/or acquisition mode is selected.

I added a new menu in the menu bar to hide/show columns. I also reorganized the menu by adding "rows" and "columns" submenus.

I added a note in DrILL's doc about the new features.

2020-10-14 09:59 UTC, gvardany commented
Thanks for the changes, it works well. Just a minor point, you can also put the Erase selected cells menu item under Cell(s) to be consistent with rows and columns. Also make clear in the docs that the order, the hidden and folded columns will be preserved when saving/loading a rundex file, whereas when changing the instrument and/or the acquisition mode it always starts fresh.

2020-10-14 15:30 UTC, gui-co commented
I added the 'Cell(s)' submenu for consistency.
I also clarified the doc concerning the saving and loading of visual settings.

2020-10-16 09:06 UTC, gvardany reviewed
There is still something confusing, when I switch to polarized for D17, the Run01, 10 and 11 columns show up at the end, but they are supposed to be in the beginning.

2020-10-16 09:26 UTC, gui-co commented
The visual settings (column order, collapsed columns, hidden columns) are now reset when the instrument and/or acquisition mode is changed.

2020-10-16 09:43 UTC, gvardany commented
The column order doesn't seem to be reset, try reordering and swapping between polarized and unpolarized reflectometries.

2020-10-16 12:00 UTC, gui-co commented
The column order was somehow kept in the table header. I now reset it each time the table is created.

2020-10-21 08:46 UTC, gvardany approved these changes
Works as described.

2020-10-21 12:15 UTC, merged