Refactor algorithms with simple api
mantidproject/mantid pull request #29662
Opened 2020-10-02 13:02 UTC by joseph-torsney

Refactored the algorithms mentioned in commits to use `mantid.simpleapi` instead of `self.createChildAlgorithm` 

**To test:**
Check they still work as expected (or not if the unit tests passing are satisfactory)

associated with #21008 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-02-08 10:45 UTC, darominski requested changes
It is nice to see the refactoring to more Python native use of algorithms. There are just a few things to add to avoid excessive number of workspaces ending up in the ADS, which was not the case in the previous solution. 
Other calls to algorithms in `EnggFitPeaks` could be refactored in the same way, namely: FindPeaks (L298), CreateWorkspace (L391), ConvertUnits (L401), CreateEmptyTableWorkspace(L460). In addition, the use of `mantid.` to refer to algorithms there as well as the other import of mantid.simpleapi as sapi throughout the code of `EnggFitPeaks`  could be harmonized at the same time.

2021-02-08 10:45 UTC, darominski commented on Framework/PythonInterface/plugins/algorithms/EnggFitPeaks.py
> +from mantid.simpleapi import *
In L13 in the new solution the simpleapi is already imported as mantid. Then, either the new import replaces the previous solution (I believe that'd be preferred ) and all references to simpleapi through mantid.algorithm_name should be refactored, or the new call to Fit should be done through mantid.fit.

2021-02-08 10:45 UTC, darominski commented on Framework/PythonInterface/plugins/algorithms/EnggFitPeaks.py
> +        return fit_output.OutputParameters, fit_output.OutputChi2overDoF
This does work nicely, however leaves `Fit` output workspaces in the ADS that were not there in the earlier solution. If this additional output was not intended, then perhaps the `Fit` algorithm should also have `StoreInADS=False` .

2021-02-08 10:45 UTC, darominski commented on Framework/PythonInterface/plugins/algorithms/EnggFitTOFFromPeaks.py
> +        )
This also leaves workspaces in the ADS, which is probably not intended. Adding` StoreInADS=False` should restore previous behaviour.

2021-02-08 10:45 UTC, darominski commented on Framework/PythonInterface/plugins/algorithms/EnggFitTOFFromPeaks.py
> +        )
And this call also leaves workspaces in the ADS, which is probably(?) not intended. Adding` StoreInADS=False` should restore previous behaviour.

2021-04-20 13:44 UTC, joseph-torsney commented
You're right, I didn't intend the new calls to store things in the ADS, thanks for catching that!

2021-04-26 16:43 UTC, DavidFair commented
As this is a maintenance piece which has risk for little gain this close to release, I'm going to move the milestone to 6.2 if that's okay?

2021-06-08 19:37 UTC, darominski approved these changes
Apologies for such a delay in the approval. I somehow missed a notification for the commits with resolved build issues. Looks good now!

2021-06-09 12:33 UTC, DavidFair approved these changes
Looking at the PR dates it took a while, though nobodies fault but this is finally getting merge
I think it's a good improvement to readability and it helps a lot with clearer error messages whilst developing :+1:

2021-06-09 12:33 UTC, merged