Show correct attribute values in Indirect Data Analysis FunctionBrowser
mantidproject/mantid pull request #29810
Opened 2020-10-23 16:13 UTC by StephenSmith25

**Description of work.**
This PR ensures that the correct value of function attributes is shown in the function browser used in Indirect and Muon Analysis. With regards to the attached issue this ensures that the correct Q value is shown in the function browser in the ConvFit tab of IDA. The work is split up as follows:

[ ] - Show the correct value of the attribute in the browser 
[ ] - Allow users to set attributes within the browser (ensuring the stored model is appropriately updated)
[ ] - Unit tests

**To test:**
TODO

Fixes #28529 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-11-04 14:25 UTC, Harrietbrown requested changes

2020-11-04 15:33 UTC, StephenSmith25 commented on qt/widgets/common/src/FunctionMultiDomainPresenter.cpp
> +  void apply(double &d) const override {
Annoyingly these override a base class method so they cannot be templated. I’ll have a look at doing something different, as it is just writing the same line over and over again.. Doesn’t seem great.

2020-11-05 09:12 UTC, Harrietbrown commented on qt/widgets/common/src/FunctionMultiDomainPresenter.cpp
> +  void apply(double &d) const override {
how much work would it be to change the base class method? do the other implementations of it have any differences that would stop them from being templated?

2020-11-05 11:01 UTC, StephenSmith25 commented on qt/widgets/common/src/FunctionMultiDomainPresenter.cpp
> +  void apply(double &d) const override {
Latest commit should remove some boilerplate and allow lambda expression to be used. For our use case this means we can simple pass in a single lambda, without having to define that `struct` at the top of the .cpp file.

2020-11-11 10:11 UTC, Harrietbrown approved these changes
The Q values are corectly set and remembers when chaged in the browser. Good Job

2020-11-11 16:19 UTC, merged