IDA Convfit get lorentzian width from ipf
mantidproject/mantid pull request #29932
Opened 2020-11-11 09:28 UTC by Harrietbrown

**Description of work.**

This PR makes it so that the Convfit tab in the indirct data analysis gui can get it's initial guess paramiters for it's lorenzian from the resolution IPF when it is loaded. 
Also as part of finding a solution to this I have also added a propper overload for IFunction getError and SetError by paramiter name instead of just index.

**To test:**

1. get data from #24664 
1. Open workbench
2. Open Indirect->Data Analysis
3. Go to Convfit
4. In the function browser add a lorenzian
5. Load a sample resolution pair
6. The function browser shoud have it's FWHM changed to 0.0175, the rage markers on the plor should have been updated to reflect this.
7. change to multiple input and do the same with indevidual spectra and combinations of different workspaces.

Fixes #29254 

The changes to convfit has release notes, but the overload for getError and setError are internal only and do not require them.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-11-12 14:24 UTC, robertapplin commented
This has merge conflicts @Harrietbrown

2020-11-12 14:32 UTC, robertapplin commented
I am getting a `Vector subscript out of range` error when I load in this data and select 1 Lorentzian:
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/5531221/irs26173_graphite002_res.zip)

2020-11-13 14:18 UTC, Harrietbrown commented
I'm not able to recreate a `Vector subscript out of range` error on my end, could you give some more specific instructions

2020-11-16 13:31 UTC, robertapplin requested changes

2020-11-16 13:31 UTC, robertapplin commented on qt/widgets/common/src/FunctionModel.cpp
> +          if (comp->hasParameter("resolution")) {
Might we need to check that `comp` exists before we check `hasParameter`?

2020-11-16 13:33 UTC, robertapplin commented on qt/widgets/common/src/FunctionModel.cpp
> +          if (comp->hasParameter("resolution")) {
Nevermind, it looks like this will work fine.

2020-11-16 13:34 UTC, robertapplin approved these changes, later dismissed

2020-11-16 14:17 UTC, robertapplin submitted a review, later dismissed
Looks good 👍

2020-11-19 08:29 UTC, martyngigg requested changes
A nice addition to the function layer to mirror the access by name for the paramters.

Are there any further tests that could be added around CompositeFunction, ParamFunction to test the new behaviour?

2020-11-19 08:29 UTC, martyngigg commented on qt/widgets/common/src/FunctionModel.cpp
> +        const auto ws =
I'm finding this a little difficult to parse due to the heavy nesting. Could we maybe extract out another method
```cpp
setResolutionFromWorkspace(const MatrixWorkspace & workspace)
```

that could be called as

```cpp
setResolutionFromWorkspace(AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>(wsName));
```
?

2020-11-19 08:29 UTC, martyngigg commented on qt/widgets/common/src/FunctionModel.cpp
> +        if (analyser.size() > 0) {
With the new extracted method we could do an early return with
```cpp
if(analyser.empty())
  return
```
to further reduce the indentation and improve readability?

2020-11-19 16:56 UTC, martyngigg approved these changes
Thanks for adding those tests.

2020-11-20 11:10 UTC, martyngigg commented
Unrelated test failure.

2020-11-20 11:10 UTC, merged