Add Alpha (Balance Parameter) To ALC Interface
mantidproject/mantid pull request #29942
Opened 2020-11-11 16:38 UTC by Matt-Cumber

**Merge #29847  first**

**Description of work.**
Added new option to ALC interface to set alpha value

**To test:**
1. Open ALC
2. Load some single period data and check alpha is available
3. Load some multi period data and check alpha is not available

Fixes #29798 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-12-03 10:50 UTC, AnthonyLim23 commented on docs/source/interfaces/Muon ALC.rst
> +  forward and backward groups. *Alpha* is the balanace parameter and is only available
```suggestion
  forward and backward groups. **Alpha** is the balance parameter and is only available 
```

2020-12-03 17:11 UTC, AnthonyLim23 requested changes

2020-12-03 17:12 UTC, AnthonyLim23 commented
GUI works well

2020-12-09 14:26 UTC, AnthonyLim23 submitted a review, later dismissed

2020-12-15 10:41 UTC, DavidFair approved these changes, later dismissed
I've resolved the merge conflict in the docs for you, and I'm happy to :shipit: once the CI finishes (to make sure I haven't botched the docs somehow)

2020-12-15 11:21 UTC, DavidFair approved these changes
3rd time lucky on getting this merged before another merge conflict develops....

2020-12-16 17:51 UTC, AnthonyLim23 commented
@DavidFair could you please merge this before we get another conflict?

2020-12-17 06:53 UTC, merged