Fix environment injection in mantidpython
mantidproject/mantid pull request #29963
Opened 2020-11-13 22:01 UTC by peterfpeterson

There was an error in how it was done in #29944 which broke mantidpython on fedora. This fixes that issue.

**To test:**

`mantidworkbench` and `mantidpython` should both launch.

*There is no associated issue.*

*This does not require release notes* because it only affects Fedora.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-11-14 01:01 UTC, KedoKudo submitted a review, later dismissed
This branch is built and tested (running `mantidworkbench` and `mantidpython`) on Fedora 33 with latest libs.
Both `mantidworkbench` and `mantidpython` launches without any issues.

2020-11-16 15:25 UTC, rosswhitfield requested changes

2020-11-16 15:25 UTC, rosswhitfield commented on buildconfig/CMake/LinuxPackageScripts.cmake
> +  if ("${UNIX_DIST}" MATCHES "^Fedora")
The `if` and `else` are doing the same thing. I don't think that is what you were aiming for?

2020-11-16 18:26 UTC, KedoKudo approved these changes
Tested again on Fedora33 and both Workbench and mantidpython launches without any issue.
It seems like the duplicated entry has no impact on the actual functionality of the launch script.

2020-11-16 18:27 UTC, merged