Changed bin edges to points
mantidproject/mantid pull request #30042
Opened 2020-11-23 07:39 UTC by SilkeSchomann

Fixes [#23792](https://github.com/mantidproject/mantid/issues/23792)

When removing the exponential in RemoveExpDecay and EstimateMuonAsymmetryFromCounts use point data instead of bin edges for the x values.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-12-03 10:27 UTC, DannyHindson commented
@SilkeSchomann - I've just picked up this PR to review. We normally put a "**To test:**" section in the PR description. Would you mind adding this in? In some cases there genuinely isn't much to test in addition to the automated tests so in that case I normally just write "code review only" or similar. I think in this case it's probably just a case of running one of the two algorithms you mention in the description

2020-12-03 11:25 UTC, DannyHindson requested changes
I noticed that the unit test for RemoveExpDecay didn't need a change (RemoveExpDecayTest.h) despite the underlying algorithm changing. I had a closer look at why and the unit test always creates workspaces that use points rather than bin edges. I think it would be useful to add an extra test that runs on a workspace with bin edges. I think you can do that by adding a new boolean parameter called usePoints or similar to the createWorkspace function in RemoveExpDecayTest.h. If you create the X vector with one more entry in it than the Y vector the call to the CreateWorkspace algorithm will create a workspace using bin edges.

I've also a couple of detail level comments against the individual units.

2020-12-03 11:25 UTC, DannyHindson commented on Framework/Muon/src/RemoveExpDecay.cpp
> +  const auto xPointRawData = histogram.points().rawData();
Sorry these two points are a bit pedantic...
- Please could you change this line so it reads the x points off the result object. The code used to read the bin edges from result and the Y and E values are also read off result so seems more consistent
- Also the Points class returned by points() already supports indexing using [i] so no need for the .rawData() bit on the end. Probably makes sense to rename the variable to xPoints or similar as part of this

2020-12-03 11:26 UTC, DannyHindson requested changes

2020-12-03 11:26 UTC, DannyHindson commented on Framework/Muon/src/MuonAsymmetryHelper.cpp
> +  const auto xPointRawData = histogram.points().rawData();
See comments against RemoveExpDecay.cpp - please can you make same changes here

2020-12-03 15:22 UTC, DannyHindson requested changes

2020-12-03 15:22 UTC, DannyHindson commented on Framework/Muon/test/RemoveExpDecayTest.h
> +    X.emplace_back(0.0);
Thanks for making the changes. All looks good apart from one little thing related to these extra x values. 
I think this code is currently adding both of the extra x values on the front of the first histogram. Also it assumes nspec is always equal to 2 ie always two histograms. I think you should move a single X.emplace_back(0.0) statement down to in between lines 40 and 41 and then that will work better. You might have to adjust the test values lower down as well where you check the x values at index 10, 19 etc are what you expect.

2020-12-03 18:32 UTC, DannyHindson requested changes
This looks good now. Please can you add a line into the Muon.rst release note in docs\source\release?

2020-12-03 18:56 UTC, SilkeSchomann commented
The release note is already updated (https://github.com/mantidproject/mantid/pull/30101)

2020-12-04 07:37 UTC, DannyHindson commented
> The release note is already updated (#30101)

OK. I don't think there's much benefit in separating the release note change into a separate pull request. Please can you make the change under this PR and close #30101? I think Jenkins will spot it is a docs change only and won't run all the jobs. I see the RHEL7 job has failed because of a problem with one of the agents so will restart that now

2020-12-04 09:28 UTC, DannyHindson approved these changes
Thanks for making the changes. Looks good to me

2020-12-04 12:14 UTC, DavidFair approved these changes
I had to double check that we weren't making an expensive copy with `const auto xPoints = result.points()` but looking at the implementation someone has already wrapped it in a light-weight container, so we don't need to worry about it which is a nice bonus

LGTM lets :shipit:

2020-12-04 12:14 UTC, merged