Adopt lead pressure calculation algorithm
mantidproject/mantid pull request #30083
Opened 2020-11-27 16:00 UTC by clayton-tom

**Description of work.**
Onboard a new algorithm from Chris Ridley and add some unit tests. The purpose of this algorithm is to take the dSpacing of the 111 bragg peak and the temperature, and calculate the sample pressure using an equation of state. It can also, if supplied with a target pressure, try a range of dSpacing values to see which corresponds to the target pressure for the input temperature.

**Report to:** Chris Ridley

**To test:**
1. Run the algorithm with a range of different values of dSpacing and temperature in the valid ranges to ensure sensible answers are returned
2. Run the algorithm with input values out of range to ensure the input validation catches it

Fixes #30049 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2020-11-30 08:51 UTC, samtygier-stfc commented
I think you could avoid the loop and do the whole thing in numpy. It would loose the optimisation of trimming down to candidates below TOL, and mean that the whole array of 10k values is held in memory. But I suspect it would be faster. Something like: 

```
test_dspacing = np.arange(2, 2.95, 0.0001)
pressure = calculate_pressure(test_dspacing, temp)
diff = abs(pressure - p_target)
i = np.argmin(diff)
diff, found_d = diff[i], test_dspacing[i]

if diff < TOL:
	if use_input_target:
	...
```

2020-11-30 10:47 UTC, clayton-tom commented
> I think you could avoid the loop and do the whole thing in numpy. It would loose the optimisation of trimming down to candidates below TOL, and mean that the whole array of 10k values is held in memory. But I suspect it would be faster. Something like:
> 
> ```
> test_dspacing = np.arange(2, 2.95, 0.0001)
> pressure = calculate_pressure(test_dspacing, temp)
> diff = abs(pressure - p_target)
> i = np.argmin(diff)
> diff, found_d = diff[i], test_dspacing[i]
> 
> if diff < TOL:
> 	if use_input_target:
> 	...
> ```

@samtygier-stfc thanks for your comment, I've given it a go and it's certainly faster (~0.02 vs ~0.09 seconds to run exec for same inputs), and I think there probably aren't many mantid users who will struggle with the ~29000 ndarray values so will go ahead with this

2020-11-30 11:35 UTC, samtygier-stfc requested changes
Code looks good. Test case and example work. Probably someone else should check that the answers are sensible.

Would it be normal for the table workspace to be returned as an output? For example so I could do

`lead_calc = LeadPressureCalc(dSpacing=2.85, T=312, TargetPressure=0.0043)`

2020-11-30 11:35 UTC, samtygier-stfc commented on Framework/PythonInterface/test/python/plugins/algorithms/LeadPressureCalcTest.py
> +class MyTestCase(unittest.TestCase):
Should this be called `LeadPressureCalcTest`

2020-11-30 17:23 UTC, samtygier-stfc approved these changes

2020-11-30 17:24 UTC, samtygier-stfc commented
Looks good to me.

2020-12-08 11:26 UTC, merged

2020-12-08 14:10 UTC, DannyHindson commented
@clayton-tom - well done on completing this Tom. Please can you check the nightly build succeeds tonight and assuming it does, can you email Chris and ask him to have a look?