Add more default plot settings to workbench
mantidproject/mantid pull request #30121
Opened 2020-12-08 09:45 UTC by joseph-torsney

This PR adds more default plot settings to workbench:
- Axes spine width
- Whether grid is turned on
- Enable/disable ticks on each side of the plot
- Enable/disable tick labels on each side of the plot
- Set width, length, and direction for major and minor ticks

**To test:**
- Ensure enabling/disabling all of the settings above work correctly.
- Are the changes to the gui clear and easy to use in your opinion? 
- Should we add some of these settings to the plot config? For example, a tiled plot with ticks and labels on all sides can look a bit messy!
![image](https://user-images.githubusercontent.com/68589504/101467209-ef8f5800-3939-11eb-9bed-9f9258d4c581.png)

Fixes #29739 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-01-06 16:30 UTC, Harrietbrown requested changes
I think this wiould benefit from a button to restore the dafault plot settings to factory default.

2021-01-06 16:30 UTC, Harrietbrown commented on docs/source/concepts/PropertiesFile.rst
> +|``plots.ticks.major.direction``  |The default direction of the major ticks                          |``In``, ``Out``      |
both this and the minor ticks can also be ``InOut``

2021-01-08 10:24 UTC, martyngigg commented
@Harrietbrown We're keen to getting the settings changes in and have created a new issue for resetting to defaults.

@joseph-torsney Could you address the point that Harriet made in the docs about the ticks can also have the `InOut` option and then we are good to go.

2021-01-08 13:33 UTC, martyngigg commented
Unrelated test failures and minor docs correction after first review.

2021-01-08 13:33 UTC, merged