Fix interface squishing in Indirect Corrections interface
mantidproject/mantid pull request #30264
Opened 2021-01-06 13:42 UTC by Harrietbrown

**Description of work.**

This commit adds a scroll bar to the tabs in the indirect corrections interface to prevent squishing in smaller screens.

**To test:**

1. open Indirect Corrections check that the layout of all parts of each tab are clear.
2. change screen resolution and make sure that the interface can still be used in the resolution without being squished.

Fixes #30221

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-01-07 13:25 UTC, Pasarus requested changes
Generally it looks fine however, this run button on most tabs looks a little weird, could you fix it? 
![image](https://user-images.githubusercontent.com/24723609/103897659-cb1acd00-50eb-11eb-813c-b8662e67e002.png)

2021-01-07 17:10 UTC, Pasarus requested changes
Sorry I didn't see this sooner:
the 2 middle tabs at the bottom have a dodgy button that isn't large enough unfortunately
![image](https://user-images.githubusercontent.com/24723609/103921964-08428780-510b-11eb-8112-7f4b8a4a6136.png)

That should be the last thing to fix before I can approve this!

2021-01-08 11:44 UTC, clayton-tom approved these changes
Buttons no longer squish and the interfaces scale well, nice work 👍

2021-01-08 13:25 UTC, martyngigg commented
Unrelated build failure that is fixed by #30293

2021-01-08 13:25 UTC, merged