Allow multiple goniometers to be stored in the Run object
mantidproject/mantid pull request #30543
Opened 2021-01-29 21:33 UTC by rosswhitfield

**Description of work.**

This is mainly useful for constant wavelength instruments that do motor scans.

**To test:**

Both of these datasets are included int he unit test data.

```python
ws = LoadMD('HB3A_data.nxs')
SetGoniometer(ws, Axis0='omega,0,1,0,-1', Axis1='chi,0,0,1,-1', Axis2='phi,0,1,0,-1', Average=False)
r = ws.getExperimentInfo(0).run()
for i in range(r.getNumGoniometers()):
    print(i,r.getGoniometerByIndex(i).getEulerAngles('YZY'))
```

```python
ws = LoadILLDiffraction(Filename='ILL/D20/000017.nxs')
SetGoniometer(ws, Axis0='omega.position,0,1,0,1', Average=False)
for i in range(ws.run().getNumGoniometers()):
    print(f'{i} omega = {ws.run().getGoniometerByIndex(i).getEulerAngles("YZY")[0]:.1f}')
```

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-02-02 19:50 UTC, peterfpeterson requested changes
This looks overall good. The only change is a minor one on the exception being thrown. Please throw `std::out_of_range` rather than `std::invalid_argument` for the various things that take an index.

2021-02-02 19:50 UTC, peterfpeterson commented on Framework/API/src/Run.cpp
> +    throw std::invalid_argument(
This would be better as a `std::out_of_range` like [`std::vector::at`](https://en.cppreference.com/w/cpp/container/vector/at)

2021-02-02 20:13 UTC, peterfpeterson submitted a review, later dismissed

2021-02-03 15:15 UTC, rosswhitfield commented on Framework/API/inc/MantidAPI/Run.h
> +  void setGoniometer(const Geometry::Goniometer &goniometer);
Yeah, sure. I can change this to `setGoniometers`?

2021-02-03 17:49 UTC, jmborr commented on Framework/API/inc/MantidAPI/Run.h
> +  void setGoniometer(const Geometry::Goniometer &goniometer);
that be preferable

2021-02-03 18:09 UTC, peterfpeterson approved these changes

2021-02-03 19:17 UTC, merged

2021-02-16 11:05 UTC, DannyHindson commented
@rosswhitfield - I noticed this PR yesterday and it got me thinking about a change we've been asked to make but haven't got around to yet. Have you ever been asked to support multiple UB matrices in a single workspace? The WISH team here at ISIS have asked us to do this in order to support a situation where there are multiple crystallites in a singe sample. Although not the same thing functionally as what you've done here it sounded like technically speaking it could be a similar kind of change.

2021-02-16 13:52 UTC, rosswhitfield commented
@DannyHindson Yes, I believe that is something both TOPAZ and Corelli have requested.

That is unrelated to this as this is to help support reactor instruments that do things like omega scans but it is a similar change. Adding the ability to store multiple UB's is easy, it's making correct use of them that will be the challenge.

2021-02-16 14:13 UTC, rosswhitfield commented
This is not currently a priority for us but it has been a very old request, see #12116