Improve incremental builds of Qt .ui files
mantidproject/mantid pull request #30553
Opened 2021-02-01 16:49 UTC by DannyHindson

**Description of work.**

All the ui\_\*.h files are deleted from the build directory prior to the start of a non-clean build on Jenkins to ensure that no stale
ui_*.h files are left behind in the scenario where a .ui file has been deleted

For Windows builds this was triggering a lot of recompilation in targets using Qt

To avoid this the ui\_\*.h deletion has been moved in cmake where it can be made more targeted ie the list of actual ui_*.h files
can be compared to the ones that should be present and only the extras removed

As part of this I've removed the ui_*.h deletion from the linux build script as well because the cmake rule will apply there. Unclear whether the original problem affected linux builds though - the incremental build process may not have been affected as much by this

**To test:**

Create a dummy ui_*.h file in one of the target specific subdirectories in the build directory eg in C:\mantid\build\qt\widgets\common\qt5

It doesn't matter what the content of the file is. Also the file name shouldn't equal the stem of an of the .ui files for this target

Run cmake and check that the dummy ui_*.h file has been deleted

The changes to the build scripts should be validated by the fact that the jobs have run successfully on this PR

Fixes #30469.

*This does not require release notes* because **it has no functional impact, it's just a technical change to the build process**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-02-05 13:45 UTC, Pasarus requested changes
It mostly works well, I have a question though, should it be working if there are no CMake changes? for example when I build a new target and no CMake changes have occured it does not remove the bogus ui_*.h files, is it possible this could cause an issue?

2021-02-05 14:26 UTC, DannyHindson commented
> It mostly works well, I have a question though, should it be working if there are no CMake changes? for example when I build a new target and no CMake changes have occured it does not remove the bogus ui_*.h files, is it possible this could cause an issue?

Let me have a think about that. The place this is supposed to take effect is on Jenkins - because I'm relocating some logic that lived in buildscript.bat. So it won't kick in locally in Visual Studio if there are no cmake changes. Not sure if cmake always runs on Jenkins though when it does a Windows build

2021-02-05 15:58 UTC, DannyHindson commented
I just checked out your question about cmake running. There is an explicit command in both buildscript.bat and buildscript to run cmake before the build starts so I think it does always run on Jenkins eg
```
call cmake.exe -G "%CM_GENERATOR%" -A %CM_ARCH% -DCMAKE_SYSTEM_VERSION=%SDK_VERS% -DCONSOLE=OFF -DENABLE_CPACK=ON -DENABLE_MANTIDPLOT=OFF -DMAKE_VATES=OFF -DParaView_DIR= -DMANTID_DATA_STORE=!MANTID_DATA_STORE! -DUSE_PRECOMPILED_HEADERS=ON %PACKAGE_OPTS% ..
```
So the behaviour is the same as before this PR ie no deletion of ui_*.h happens on local machines but it does on Jenkins

2021-02-05 16:34 UTC, Pasarus approved these changes
If this is what we want then I am more than happy to approve :+1:

2021-02-08 12:06 UTC, martyngigg commented
> I just checked out your question about cmake running. There is an explicit command in both buildscript.bat and buildscript to run cmake before the build starts so I think it does always run on Jenkins eg
> 
> ```
> call cmake.exe -G "%CM_GENERATOR%" -A %CM_ARCH% -DCMAKE_SYSTEM_VERSION=%SDK_VERS% -DCONSOLE=OFF -DENABLE_CPACK=ON -DENABLE_MANTIDPLOT=OFF -DMAKE_VATES=OFF -DParaView_DIR= -DMANTID_DATA_STORE=!MANTID_DATA_STORE! -DUSE_PRECOMPILED_HEADERS=ON %PACKAGE_OPTS% ..
> ```
> 
> So the behaviour is the same as before this PR ie no deletion of ui_*.h happens on local machines but it does on Jenkins

I think this is okay as I can't imagine trying to add rules to VS to get it to delete things from its own ruleset would work out so well. At least now we can just tell developers to run cmake whereas before we would have had to get them to remove the files by hand.

2021-02-08 12:06 UTC, merged