Move issue template to new GitHub system
mantidproject/mantid pull request #30744
Opened 2021-02-22 17:07 UTC by martyngigg

GitHub now allows defining several templates.
This adds a template for an empty issue and a bug report.

2021-02-24 16:10 UTC, DanielMurphy22 requested changes
I added this to my repo to see how it works (I don't know if you can create issues [here](https://github.com/DanielMurphy22/SmokeTests/issues)).

Overall it's really good to have a change and happy to discuss the different comments I've made!

2021-02-24 16:10 UTC, DanielMurphy22 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +4. See error
Is the idea with all of these descriptions that the person creating the issue is slowed down to think of a good way to explain it? If we don't want to force people to delete all these descriptions, then we could use `<!--` to set these as hidden comments, which might be nice here!

2021-02-24 16:10 UTC, DanielMurphy22 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable/possible, add screenshots to help explain your problem.
I assume this is to inspire some creativity! You could also mention adding a GIF of the issue (like from ScreenToGIF) if appropriate!

2021-02-24 16:10 UTC, DanielMurphy22 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable/possible, add screenshots to help explain your problem.
e.g. https://github.com/mantidproject/mantid/issues/28306#issuecomment-696756489

2021-04-26 16:45 UTC, DavidFair commented
I'm going to clear the release milestone, as this can go in independent of a release. Feel free to give me a shout if you disagree

2021-07-20 10:17 UTC, martyngigg commented
These can be seen live by clicking new at https://github.com/martyngigg/sandbox/issues.

2021-07-20 10:43 UTC, DanielMurphy22 approved these changes
Looks really good to me! Particularly like the link to the forum!

2021-07-20 13:32 UTC, DavidFair commented
I like the fact we can automatically categorise things too, i.e. bugs :+1:

2021-07-20 13:32 UTC, merged