Improved FileFinder Search Speed
mantidproject/mantid pull request #30746
Opened 2021-02-22 17:25 UTC by Matt-Cumber

**Description of work.**
When searching for multiple runs, added a check to see if the file exists using the current run number and the previous path and extension. This provides a great speed benefit particularly if the runs are stored on the archive in one directory, which is the most common use case, by limiting calls made to the web api.

**To test:**
I have been using this script for testing. But you should see overall improvements when loading runs in interfaces as well
```
# Worst case every file in different directory 
archive_search_10_dirs = "70993, 72589, 74374, 76366, 78873, 83480, 86490, 88127, 91955, 95162" 

# Baseline
ten_archive_files = "70993-71003" 

# Some cases interfaces would like to load in hundreds of runs and were limited by long search times
one_hundred_archive_files = "70993-71093" 
two_hundred_archive_files = "70993-71193" 

# I have also been testing local files but you will need to set this up yourself

n_times = 3 # how many times to run the search
average = 0

for i in range(1, n_times+1):
    start = time.time()
    runs = FileFinder.findRuns(hintstr=one_hundred_archive_files) # Add in what you are searching for here as the parameter hinstr
    end = time.time()
    print("Elapsed time {}: {} seconds".format(i, end-start))
    average += end-start

print("Average time: {}".format(average/n_times))
```

Fixes #30408 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-02-23 14:18 UTC, martyngigg requested changes
I like this improvement as it uses a fact that is true much of the time for facility directories where runs are typically next to each other. Offline you showed some timings you had done. Could you include them in the PR description for future reference?

Just a couple of inline code comments to address too.

2021-02-23 14:18 UTC, martyngigg commented on Framework/API/src/FileFinder.cpp
> +      std::string previous_path{""};
For strings the default constructor will give an empty string so we can collapse this to:
```c++
std::string previousPath, previousExt;
```
Note that I've switched to camelCase to be consistent with the coding standards.

2021-02-23 14:18 UTC, martyngigg commented on Framework/API/src/FileFinder.cpp
> +          previous_ext = "." + Poco::Path(path).getExtension();
I think the Poco::Path constructor is a little expensive so it's probably worth a separate variable for that first.

2021-02-23 14:18 UTC, martyngigg commented on docs/source/release/v6.1.0/framework.rst
> +- :ref:`FileFinder <mantid.api.FileFinderImpl>` has been modified to improve search times in some cases.
Can we be a little more explicit in the *some* cases? Perhaps just say in the case of searching for multiple runs for the same instrument?

2021-02-23 14:19 UTC, martyngigg commented
@gvardany Might this help with the issues in #29881 or is that more generally an issue for multiple files and not just runs?

2021-02-23 14:39 UTC, gvardany commented
This seems indeed very similar. I will try with my script on this branch to see if it helps. It is just that my concern was finding via MultipleFileProperty, but eventually this must rely on the same FileFinder anyhow.

2021-02-23 14:46 UTC, martyngigg commented
> This seems indeed very similar. I will try with my script on this branch to see if it helps. It is just that my concern was finding via MultipleFileProperty, but eventually this must rely on the same FileFinder anyhow.

Yes I hope so. If not we should probably try and have these things converge.

2021-02-23 15:09 UTC, martyngigg commented on Framework/API/src/FileFinder.cpp
> +          }
If we have caught an error here perhaps we should clear the previous path and extensions as they likely causes issues if the next one is okay it'll cache again anyway?

2021-02-23 15:09 UTC, martyngigg commented on Framework/API/src/FileFinder.cpp
> +            const Poco::File file(previousPath + p1.first + run + previousExt);
Can we not duplicate `previousPath + p1.first + run + previousExt` below? From a readability point of you I need to double take to check that they are the same.

I think `Poco::File` has a string method?

2021-02-23 16:56 UTC, martyngigg approved these changes
I think this is an excellent improvement and is ready to go now.

2021-02-24 07:25 UTC, merged

2021-02-24 09:56 UTC, gvardany commented
Unfortunately this didn't improve my observations on our archive (https://github.com/mantidproject/mantid/issues/29881).
Here is what I got before and after the merge of this PR.
3rd and 4th entries are when setting the same value to the same property, those are faster due to caching of its previous value in multiple file property.
Still I have hard time interpreting these timings.
I'm puzzled that even with caching the resolved paths it takes around 60sec.
This means that it is probably the time spent just checking if the files exists w/o any finding.
I'm also confused why for the first time setting with absolute paths takes longer than with numors.
I had a draft attempt https://github.com/mantidproject/mantid/tree/multiplefiles_samedirectory based on the assumption that in one go all the numors must be in the same directory, but that didn't seem to change the picture either.

```
Master (after merge)
--------------------
Absolute paths took: 126.40826392173767
Numors took: 94.69144296646118
Absolute paths took: 62.48769807815552
Numors took: 61.87765407562256

Master (before merge)
---------------------
Absolute paths took: 122.73527884483337
Numors took: 101.9387719631195
Absolute paths took: 61.36741924285889
Numors took: 61.29860305786133
```