Improved interface help interaction
mantidproject/mantid pull request #30786
Opened 2021-02-26 17:56 UTC by peterfpeterson

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-02-27 02:29 UTC, AndreiSavici requested changes, later dismissed
Will need to also check all interfaces, to make sure there are no missing pages. PyChop needs to have the 'direct' section

2021-02-27 02:29 UTC, AndreiSavici commented on qt/python/mantidqt/gui_helper.py
> +        mantidqt.interfacemanager.InterfaceManager().showCustomInterfaceHelp(mantidplot_name, section)
This line will always fail. Try
`mantidqt.interfacemanager.InterfaceManager().showCustomInterfaceHelp('/'.join([mantidplot_name, section]))` instead, or you need to pass the parameters down the chain

2021-03-05 03:19 UTC, AndreiSavici commented
@martyngigg Can you get some people at ISIS going through all interfaces, see if they can open the correct help page?

2021-03-11 08:28 UTC, martyngigg approved these changes
The ISIS interfaces have been checked and all of them open the correct help page when clicked.

2021-03-11 15:11 UTC, merged