Workspace calculator widget
mantidproject/mantid pull request #30852
Opened 2021-03-09 15:09 UTC by darominski

**Description of work.**

This PR implements a new widget: workspace calculator. This new widget allows to perform binary operations, currently 4 arithmetic operations and weighted mean, as well as simultaneously scaling of the two provided workspaces by an arbitrary floating number (except for 0).

Still to do: 
1. Add validation of the input parameters,
2. Add mocking and testing.

**To test:**

Perform available binary operations using all kind of workspaces, for example using the workspaces created by the following script:
```
lhs1 = CreateSingleValuedWorkspace(DataValue=1)
rhs1 = CreateSingleValuedWorkspace(DataValue=2)

ws1 = CreateSampleWorkspace()
ws2 = CreateSampleWorkspace()
ws3 = CreateSampleWorkspace()
ws4 = CreateSampleWorkspace()

lhs2 = ws1.clone()
rhs2 = ws2.clone()

lhs3 = GroupWorkspaces([ws1, ws2])
rhs3 = GroupWorkspaces([ws3, ws4])

S=range(0,100);
ERR=range(0,100);
# create Histo workspace
ws5 = CreateMDHistoWorkspace(Dimensionality=2,Extents='-3,3,-10,10',SignalInput=S,ErrorInput=ERR,\
                           NumberOfBins='10,10',Names='Dim1,Dim2',Units='MomentumTransfer,EnergyTransfer')
ws6 = CreateMDHistoWorkspace(Dimensionality=2,Extents='-3,3,-10,10',SignalInput=S,ErrorInput=ERR,\
                           NumberOfBins='10,10',Names='Dim1,Dim2',Units='MomentumTransfer,EnergyTransfer')

lhs4 = ws5.clone()
rhs4 = ws6.clone()

lhs5 = GroupWorkspaces([ws5, ws6])
rhs5 = lhs5.clone()
```

Fixes #30827. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-06-09 10:29 UTC, DannyHindson requested changes
I've had a look through this and I've got two general comments:
1) the default location of the new widget is in the middle pane next to the Editor and IPython widgets. In this position, the widget contains a lot of blank space:
![image](https://user-images.githubusercontent.com/56295817/121337252-40e1c980-c914-11eb-8a17-eebe15360250.png)
I wonder if it would be better to locate it by default in the left hand column on its own row beneath the Workspaces widget:
![image](https://user-images.githubusercontent.com/56295817/121337341-55be5d00-c914-11eb-866c-d0cd9e037b32.png)
Any thoughts? This would make it more visible but the user can always disable if they don't want it there. I guess you would perhaps need to do something to make the workspace dropdowns a bit wider to support this eg move the Go button so it's below the inputs rather than to the rhs

2) If I do an operation on matrix_group_lhs and matrix_group_rhs I see some temporary workspaces left over at the end:

![image](https://user-images.githubusercontent.com/56295817/121337739-c1a0c580-c914-11eb-9822-467232b50d15.png)

The names of the workspaces in the output group also seem quite long\technical

2021-06-09 10:29 UTC, DannyHindson commented on docs/source/workbench/workspacecalculator.rst
> +the latter over a mixted input consisting of :ref:`WorkspaceGroup`
typo in mixted - mixed

2021-06-09 10:29 UTC, DannyHindson commented on qt/applications/workbench/workbench/plugins/workspacecalculatorwidget.py
> +# Copyright &copy; 2017 ISIS Rutherford Appleton Laboratory UKRI,
Please can you put 2021 in this header

2021-06-09 10:29 UTC, DannyHindson commented on qt/applications/workbench/workbench/plugins/workspacecalculatorwidget.py
> +        return "Calculator"
Although it's a bit more verbose, I think it might be more clear to new users if this was "Workspace Calculator"

2021-06-09 10:29 UTC, DannyHindson commented
Also please can you resolve the merge conflict in the rst file

2021-06-15 15:17 UTC, DannyHindson reviewed
Thanks for making the changes. The layout looks good now - I see the new widget below the Editor, IPython widgets as you described. Also the workspace names in groups look good.

Just one remaining question - the items in the workspace selector for lhs and rhs aren't sorted alphabetically whereas they are in the main workspace area. Is it possible to change this? Not sure if this is a switch you have available or whether this requires a change to the workspace selector widget. No problem if that's not possible

2021-06-15 15:59 UTC, darominski commented
> Thanks for making the changes. The layout looks good now - I see the new widget below the Editor, IPython widgets as you described. Also the workspace names in groups look good.
> 
> Just one remaining question - the items in the workspace selector for lhs and rhs aren't sorted alphabetically whereas they are in the main workspace area. Is it possible to change this? Not sure if this is a switch you have available or whether this requires a change to the workspace selector widget. No problem if that's not possible

Thank you for you comment. I also see this is as an inconvenience, and I am not sure why the `WorkspaceSelector` here behaves differently than in interfaces or auto-generated dialogs. Also, during testing, I found that when the lhs or rhs `WorkspaceSelector` s are filled when the workbench is closed, it causes a segmentation fault. The last 20 lines of the stack trace of the issue are the following: 
```
#0  0x00007fffdd5c2cbf in QGuiApplication::font() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007fffdd67a3a1 in QFont::QFont() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007fffdd6a9b0d in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007fffdd6c2ee6 in QTextLine::layout_helper(int) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007fffdd6c4915 in QTextLayout::endLayout() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007fffd0b16e64 in QWidgetLineControl::redoTextLayout() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fffd0b17048 in QWidgetLineControl::updateDisplayText(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fffd0b19eba in QWidgetLineControl::finishChange(int, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007fffd0b1a2f0 in QWidgetLineControl::internalSetText(QString const&, int, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fffd0b1194c in QLineEdit::setText(QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007fffd0ad9282 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fffd0adbd79 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fffdfcb8555 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fffdfc24b9e in QAbstractItemModel::rowsRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fffdfc2c19b in QAbstractItemModel::endRemoveRows() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fffdd9411de in QStandardItemModel::removeRows(int, int, QModelIndex const&) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007fffd0ad68f8 in QComboBox::clear() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fffcc9f0511 in MantidQt::MantidWidgets::WorkspaceSelector::handleClearEvent(Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::ClearNotification> const&) (this=0x3b39260)
    at /users/arominski/project/mantid/qt/widgets/common/src/WorkspaceSelector.cpp:183
#18 0x00007fffcc9f228e in Poco::NObserver<MantidQt::MantidWidgets::WorkspaceSelector, Mantid::Kernel::DataService<Mantid::API::Workspace>::ClearNotification>::notify(Poco::Notification*) const (this=0x3b18eb0, pNf=0x39eb7c0) at /usr/include/Poco/NObserver.h:86
#19 0x00007ffff348f18b in Poco::NotificationCenter::postNotification(Poco::AutoPtr<Poco::Notification>) () at /usr/lib/libPocoFoundation.so.50
#20 0x00007fffe8a5bc97 in Mantid::Kernel::DataService<Mantid::API::Workspace>::clear() (this=0x269f3f0) at /users/arominski/project/mantid/Framework/Kernel/inc/MantidKernel/DataService.h:340
 
```

I am going to investigate why clearing a `WorkspaceSelector` during closing the workbench causes this issue, but so far I have no logical explanation.

2021-06-15 17:18 UTC, DannyHindson commented
I don't think the other UIs that use a workspace selector sort the workspaces perfectly either. They sort the workspaces that are present when they are opened but any workspaces created after they are opened don't get sorted properly. Here's the workspace selector on the Indirect, Corrections UI. I created the "aaaa" workspace after the UI was opened:

![image](https://user-images.githubusercontent.com/56295817/122095642-8bc47b00-ce05-11eb-9415-50565bfd3f6a.png)

The sorting might be fixed by adding a call to model()->sort(0) to WorkspaceSelector::handleAddEvent immediately after addItem

2021-06-16 09:54 UTC, darominski commented
> I don't think the other UIs that use a workspace selector sort the workspaces perfectly either. They sort the workspaces that are present when they are opened but any workspaces created after they are opened don't get sorted properly. Here's the workspace selector on the Indirect, Corrections UI. I created the "aaaa" workspace after the UI was opened:
> 
> ![image](https://user-images.githubusercontent.com/56295817/122095642-8bc47b00-ce05-11eb-9415-50565bfd3f6a.png)
> 
> The sorting might be fixed by adding a call to model()->sort(0) to WorkspaceSelector::handleAddEvent immediately after addItem

Thank you, that indeed works well and allows for sorting of the `WorkspaceSelector` contents. I added a few extra calls to make sure renaming workspaces and refreshing does not break the sorting. To avoid warnings, a number of additional types had to be registered via `qRegisterMetaType` in _common.sip.

Also, I found an issue with setting validity flags when a workspace was renamed but the text was still filled in the `WorkspaceSelector`. The invalid input asterisk was not set in that case. The visibility of those asterisks is now set whenever the 'Go' button is pressed.

I also found the origin of the segmentation fault, it was in (too) late closing of the `WorkspaceSelector`, which must've been called after the QApplication of the workbench was already deleted. The solution includes an explicit forwarding of the close event to the `WorkspaceCalculator` widget.

2021-06-16 14:42 UTC, DannyHindson requested changes
I've just retested and the workspace selectors are now sorted and the seg fault on closing workbench no longer happens.
If I rename a workspace then the workspace selectors in the calculator don't get resorted and the renamed item just stays in its original place - but I'm fine with this. It's a minor point.
Please can you add a line to the release notes for the workspace calculator? I saw you'd added a line for the sort order change to the workspace selector but not one for the main change.

2021-06-17 09:23 UTC, DannyHindson approved these changes, later dismissed

2021-06-22 12:49 UTC, DannyHindson commented
@darominski - just noticed this PR has some merge conflicts so please can you resolve them so it can get merged?

2021-06-22 13:08 UTC, martyngigg commented
I've set auto merge enabled so that when the conflicts are resolved it will merge when the builds pass

2021-06-22 15:20 UTC, darominski commented
> @darominski - just noticed this PR has some merge conflicts so please can you resolve them so it can get merged?

Unfortunately, the fix dismissed the review. Could you re-approve?

2021-06-22 15:25 UTC, DannyHindson approved these changes

2021-06-22 15:25 UTC, merged