patch for HB2A concerning data save in GSAS format
mantidproject/mantid pull request #30853
Opened 2021-03-09 15:31 UTC by Kvieta1990

**Description of work.**

The autoreduction script for HB2A is using `SaveGSSCW` to save GSAS formatted data whereas the `HB2AReduce` script was using `SaveGSS` to save GSAS formatted data. Current pull request is to change `HB2AReduce` algorithm to be consistent with autoreduction workflow in terms of saving GSAS formatted data.

**To test:**

Launch `HB2AReduce` algorithm and put in an example run as shown below,

![hsvnmHAg](https://user-images.githubusercontent.com/2872152/110495184-43891480-80c2-11eb-9616-36203d05c1fe.png)

Check the output to see whether it is following the same format as data saved from autoreduction, as given below,

[autoreduction.zip](https://github.com/mantidproject/mantid/files/6109594/autoreduction.zip)

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-03-09 15:55 UTC, peterfpeterson requested changes
Minor requests:
* Add a comment above each of the two tests in `test_saving_files` to aid future developers to see that they are running the same thing with slightly different parameters
* Change the code-block for HB2AReduce to be a link. The release note below it gives an example
* Mention SaveGSSCW in the release note

2021-03-09 18:26 UTC, peterfpeterson approved these changes

2021-03-19 15:18 UTC, Kvieta1990 commented
New test data added and `HB2AReduceTest.py` script updated accordingly. Could you please merging the pull request? Thank you so much! @peterfpeterson

2021-03-22 14:25 UTC, peterfpeterson requested changes

2021-03-22 14:25 UTC, peterfpeterson commented on Framework/PythonInterface/plugins/algorithms/HB2AReduce.py
> +                    Filename=f"{outputbase}.{_outputext}",
```suggestion
                    OutputFilename=f"{outputbase}.{_outputext}",
```

2021-03-22 14:33 UTC, peterfpeterson approved these changes

2021-03-23 12:33 UTC, merged