Create new multiple scattering algorithm based on Muscat
mantidproject/mantid pull request #31078
Opened 2021-04-07 16:53 UTC by DannyHindson

**Description of work.**

New algorithm to calculate multiple scattering corrections. Based on Fortran code supplied by Spencer Howells, which in turn in based on original Discus code from M Johnson

**To test:**

Fixes #28937.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-04-16 14:39 UTC, Pasarus commented
I get some GCC warnings on compile could you fix these:
```
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp: In member function ‘virtual void Mantid::Algorithms::Muscat::exec()’:
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:212:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < nScatters; i++) {
                    ~~^~~~~~~~~~~
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:328:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < outputWSs.size(); i++) {
                    ~~^~~~~~~~~~~~~~~~~~
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:335:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < outputWSs.size(); i++) {
                    ~~^~~~~~~~~~~~~~~~~~
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp: In member function ‘double Mantid::Algorithms::Muscat::simulatePaths(int, size_t, const Mantid::API::Sample&, const Mantid::Geometry::Instrument&, Mantid::Kernel::PseudoRandomNumberGenerator&, Mantid::API::MatrixWorkspace_sptr, Mantid::API::MatrixWorkspace_sptr, double, Mantid::Kernel::V3D, bool)’:
/home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:460:56: warning: conversion to ‘double’ from ‘long unsigned int’ may alter its value [-Wconversion]
   sumOfWeights = sumOfWeights / pow(sumOfQSS / (nPaths * (nScatters - 1)), nScatters - 1);
```

2021-04-19 06:14 UTC, DannyHindson commented
> I get some GCC warnings on compile could you fix these:
> 
> ```
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp: In member function ‘virtual void Mantid::Algorithms::Muscat::exec()’:
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:212:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (auto i = 0; i < nScatters; i++) {
>                     ~~^~~~~~~~~~~
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:328:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (auto i = 0; i < outputWSs.size(); i++) {
>                     ~~^~~~~~~~~~~~~~~~~~
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:335:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (auto i = 0; i < outputWSs.size(); i++) {
>                     ~~^~~~~~~~~~~~~~~~~~
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp: In member function ‘double Mantid::Algorithms::Muscat::simulatePaths(int, size_t, const Mantid::API::Sample&, const Mantid::Geometry::Instrument&, Mantid::Kernel::PseudoRandomNumberGenerator&, Mantid::API::MatrixWorkspace_sptr, Mantid::API::MatrixWorkspace_sptr, double, Mantid::Kernel::V3D, bool)’:
> /home/sam/mantid/Framework/Algorithms/src/Muscat.cpp:460:56: warning: conversion to ‘double’ from ‘long unsigned int’ may alter its value [-Wconversion]
>    sumOfWeights = sumOfWeights / pow(sumOfQSS / (nPaths * (nScatters - 1)), nScatters - 1);
> ```

That's strange - these were also raised by Jenkins and the final commit on this PR should have fixed those: 5d698aa638d72dadffe8cbdc250f0e6bb1761008

2021-04-22 10:30 UTC, Pasarus requested changes
Fully functional, just need to look into if a few variables could be const or passed by reference, should be good to go quite quickly before the code freeze!

2021-04-22 10:56 UTC, DannyHindson commented on Framework/Algorithms/src/Muscat.cpp
> +        total = simulatePaths(nSingleScatterEvents, 1, sample, *instrument, rng, sigmaSSWS, SQWS, kinc, detPos, true);
Yes not sure what I was thinking here. Perhaps the code was more complicated at some point in the past

2021-04-22 11:03 UTC, DannyHindson commented on Framework/Algorithms/src/Muscat.cpp
> +    auto t = generateInitialTrack(shape, frame, sourcePos, rng);
This one can't be const because the subsequent call to interceptSurface modifies the Track object t

2021-04-22 13:11 UTC, Pasarus commented on Framework/Algorithms/src/Muscat.cpp
> +    auto t = generateInitialTrack(shape, frame, sourcePos, rng);
Ah ok good spot!

2021-04-22 13:29 UTC, Pasarus submitted a review, later dismissed

2021-04-23 15:12 UTC, Pasarus approved these changes

2021-04-23 16:11 UTC, merged