Fix position of new widgets when upgrading workbench versions
mantidproject/mantid pull request #31194
Opened 2021-04-22 11:57 UTC by joseph-torsney

Workbench v6.1.0 adds a memory bar widget. If there is an existing `.ini` file from a previous version of workbench, the mainwindow state from this old version will be restored. Since the old state does not include the new widget, it gets plonked on its own in a new column (see #31177). 

This PR adds a version number to the state of the mainwindow. When restoring the state, if the version numbers mismatch, the state will not be applied and the default layout will remain. 

When applying a layout saved by the user on an old version, accessible from `View > User Layouts`, in most cases the memory bar widget will appear in its own column as before. This has been mentioned in the release notes.

**To test:**
1. Checkout to a commit before the memory bar widget was added to master, e.g. `git checkout e0c3d704~1`
2. Launch workbench and modify the layout, then close workbench.
3. `git test-pr <this>`
4. Launch workbench, the memory widget should appear in the correct place.

Fixes #31177

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-04-22 16:30 UTC, thomashampson requested changes
This does solve the immediate issue, but I think we can improve it to display a message to the user if they load a saved user layout that doesn't include the memory widget, rather than relying on them reading the release notes.

2021-04-23 13:49 UTC, thomashampson commented on qt/applications/workbench/workbench/app/mainwindow.py
> +        if success:
no need for the local variable

2021-04-23 13:49 UTC, thomashampson commented on qt/applications/workbench/workbench/app/mainwindow.py
> +            if success:
same as above, can just have:
```suggestion
            if self.restoreState(state, version):
```

2021-04-23 16:01 UTC, Pasarus approved these changes

2021-04-23 16:02 UTC, thomashampson approved these changes

2021-04-23 16:09 UTC, martyngigg commented
Nice work everyone on catching and fixing this.

2021-04-23 16:53 UTC, merged