Keep Fit Results In Muon Analysis When New Data Is Loaded
mantidproject/mantid pull request #31356
Opened 2021-05-05 13:12 UTC by Matt-Cumber

**Description of work.**

**To test:**
Open Muon Analysis
Load a run (e.g. MUSR62260)
Go to the fitting tab and fit any function (e.g. Linear background) and press fit (doesn't need to be a good fit)
Go to the results tab and verify the fit workspace is present
Go back to Fitting tab
Step to the next run by clicking the arrow next to run number
Once the data has loaded click fit once again and do this for several runs
Now go to the results tab
The results tab should include the results from all the fits you performed not just the last one
On the fitting tab click undo fits
On the results tab the table should now be empty

Fixes #31298 

*This does not require release notes* because **this is a bug from this release not present in the previous release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-05 15:03 UTC, robertapplin requested changes
Thanks for this fix, just a few comments that might need some changing. When you do a fit and then change an instrument, all of the fits should be removed, but this doesn't happen at the moment. I think this can be fixed quite easily here https://github.com/mantidproject/mantid/blob/c4a8230fec10d95155c302fd3cf25c28e8012183/scripts/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_presenter.py#L51

2021-05-06 11:41 UTC, robertapplin approved these changes
Good stuff, thanks for fixing this

2021-05-07 16:32 UTC, DavidFair commented on Testing/SystemTests/tests/qt/PythonInterfacesStartupTest.py
> -            exec(open(os.path.join(self._interface_directory, interface_script)).read())
This has a real code smell to it, as were effectively echoing concatenated code into an exec. Is there no way we can call `.close()` in some sort of Qt hook when the window is closing, or am I misunderstanding what it's doing?

2021-05-10 09:39 UTC, DavidFair approved these changes
On discussion it would be best for Rob to jointly tackle this: However, as he is on leave currently, this PR fixes a problem in the release and it's only a code smell rather than a problem lets :shipit:

2021-05-10 09:39 UTC, merged