removal of inelastic background from empty instrumnnt
mantidproject/mantid pull request #31396
Opened 2021-05-08 14:48 UTC by abuts

**Description of work.**
The changes to the script give the possibility to remove empty background from the data runs. See the ticket #31327 for the description of the task

**To test:**

Well, I believe, there are unit tests for every operation. If system tests for isis direct reduction are passing, the changes will make no harm. 
The scientific validation will be performed by ISIS Excitation group. 

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-10 07:07 UTC, mducle requested changes
Couple of comments, but the main thing is that we need separate background workspaces for each of the `'sample_run'`, `'wb_run'` and `'monovan_run'`.

I haven't tried running the code yet - just trying to read the code, so some of the other comments might be wrong... but some of the logic in this code is a bit convoluted.

2021-05-10 08:32 UTC, abuts commented on scripts/Inelastic/Direct/RunDescriptor.py
> +        ebg_ws  =  ebg_ws*(ws_current/ebg_current)
normalization will occurs later -- the workspace after diagnostics is not normalized

2021-05-10 13:01 UTC, Harrietbrown requested changes
Could you correct these spellings.

2021-05-10 13:01 UTC, Harrietbrown commented on scripts/test/RunDescriptorTest.py
> +        # Verify situation if sampe workspace is in event mode and
```suggestion
        # Verify situation if sample workspace is in event mode and
```

2021-05-10 13:01 UTC, Harrietbrown commented on scripts/test/RunDescriptorTest.py
> +        # and background loaded as hisograms with monitors included
```suggestion
        # and background loaded as a histogram with monitors included
```

2021-05-10 13:05 UTC, Harrietbrown approved these changes
This is ok to be merged pending jenkins tests passing. Good Job.

2021-05-10 13:24 UTC, mducle approved these changes
Looks good to me now... Thanks!

2021-05-10 15:33 UTC, merged

2021-05-10 15:34 UTC, martyngigg commented
I've just realised that this I merged this to `master` without first checking where it was intended to go. There is no milestone set so is it okay that this will **not** be in 6.1?

2021-05-10 15:58 UTC, mducle commented
@martyngigg yes I think it's ok to go into `master` not `6.1`. We're still in the process of testing it and if it's in nightly it would be easier for the instrument scientists to test it.

2021-05-10 17:58 UTC, abuts commented
yes, Nightly would be ok

2021-05-11 08:33 UTC, abuts commented
we will update production scripts in the normal way as we always did when Mantid acceptance cycle was too long