Update MSlice.py
mantidproject/mantid pull request #31405
Opened 2021-05-10 15:03 UTC by SilkeSchomann

This change allows starting the installed version of MSlice standalone without problems (before it just crashed).

**To test:**

Try to run this file. MSlice should start without Mantid running in the background.

_There is no associated issue._ 

_This does not require release notes as this is fixing an internal issue_

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-10 17:06 UTC, DavidFair approved these changes
Got this working on Linux with the following (for future reference):

```
PYTHONPATH=<build_dir>/scripts/ExternalInterfaces/mslice/src/mslice:$PYTHONPATH python3 <source_dir>/scripts/MSlice.py
```
This worked fine for me. Interestingly trying to use `bin/mantidpython scripts/MSlice.py` works up to a point then chokes because of multiple interactive terminals. However that's out of scope for this work so lets :shipit:

2021-05-11 07:28 UTC, martyngigg requested changes
This is a nice addition.

I was wondering if we could add a documentation page for MSlice in https://github.com/mantidproject/mantid/tree/master/docs/source/interfaces/direct. I think it could mostly just link to the separate mslice docs but it could also include the instructions for how to start it as a standalone application?

2021-05-27 11:14 UTC, martyngigg commented
I hadn't spotted this was still open. I'll merge this. @SilkeSchomann For the next release, as the online docs will soon point at nightly from master anyway, could you add a docs page for mslice at https://github.com/mantidproject/mantid/tree/master/docs/source/interfaces/direct that gives these instructions on starting standalone but also links to the mslice documentation?

2021-05-27 11:14 UTC, martyngigg approved these changes

2021-05-27 11:14 UTC, merged