Add a Sliceviewer page to the user documentation
mantidproject/mantid pull request #31474
Opened 2021-05-14 15:01 UTC by martyngigg

**Description of work.**

The Sliceviewer documentation was still on the wiki. This creates a page for the new Sliceviewer under the workbench directory in the docs and changes all of the references internally to this page.

**To test:**

* Build the docs
* Review the new page

*There is no associated issue.*

*This does not require release notes* because **it is not a new feature**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-17 08:46 UTC, RichardWaiteSTFC commented
Should this have the milestone 6.1?

2021-05-17 12:16 UTC, RichardWaiteSTFC requested changes
Looks good, informative screenshots and all the links to the sliceviewer docs work. Just one thing I would add about to the cursor information widget.

2021-05-20 11:23 UTC, martyngigg commented on docs/source/workbench/sliceviewer.rst
> +regarding a given pixel as the mouse cursor moves of the image. The new table
Good call. I've just updated the page.

2021-05-25 09:12 UTC, martyngigg commented
@RichardWaiteSTFC I don't suppose you'd have time to review this today?

2021-05-25 09:14 UTC, RichardWaiteSTFC commented
> @RichardWaiteSTFC I don't suppose you'd have time to review this today?

@martyngigg Will do, sorry I forgot about this!

2021-05-25 15:43 UTC, RichardWaiteSTFC commented on docs/source/workbench/sliceviewer.rst
> +crystal (so-called non-orthogonal view) will be now be visible:
Such a minor nit-pick, but I don't think this is technically true. If a workspace fulfils your criteria (i.e. has HKL units and a UB present)  but the angles are set to 90 (within some tolerance?) then the button is not enabled (as you would expect!). However I believe the meaning is clear and I think this should PR should be merged before smoke testing so I am approving (I'm just sorry I didn't pick up on it before).

2021-05-25 15:43 UTC, RichardWaiteSTFC approved these changes

2021-05-26 09:38 UTC, merged

2021-05-26 17:23 UTC, rosswhitfield commented
@martyngigg Which data set did you use to generate the figures for the peaks overlay part of the sliceviewer page. I would like to update the page as part of #31282

2021-05-27 10:21 UTC, martyngigg commented
@rosswhitfield I used the SXD23767 data from the [training data](http://sourceforge.net/projects/mantid/files/Sample%20Data/TrainingCourseData.zip/download) and this script

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
peaksws = Load('peaks_qLab.nxs')
FindUBUsingFFT(PeaksWorkspace='peaksws', MinD=0.8, MaxD=10)
IndexPeaks(peaksws, Tolerance=0.05)
CopySample(InputWorkspace='peaksws', OutputWorkspace='SXD23767',
           CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)

mdws = ConvertToDiffractionMDWorkspace(SXD23767,
                                       OutputDimensions='HKL',
                                       OneEventPerBin=False,
                                       LorentzCorrection=True)
                                    
IntegratePeaksMD(
    InputWorkspace=mdws,
    PeaksWorkspace=peaksws,
    PeakRadius=0.5,
    BackgroundInnerRadius=1.1,
    BackgroundOuterRadius=1.4,
    OutputWorkspace='peaksws_sphere_withbkgd')

peaksws_sphere_withbkgd = mtd['peaksws_sphere_withbkgd']
while peaksws_sphere_withbkgd.getNumberPeaks() > 25:
    DeleteTableRows(peaksws_sphere_withbkgd, Rows=peaksws_sphere_withbkgd.getNumberPeaks() - 1)
```

I think I must have played a bit to remote some peaks so there weren't so many found.

2021-05-27 11:33 UTC, rosswhitfield commented
Thank you!