Enable T0 and sample position calibration in SCDCalibratePanels
mantidproject/mantid pull request #31513
Opened 2021-05-18 18:22 UTC by KedoKudo

**Description of work.**

- Original Gitlab User Story: [SCD316](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/316)
- This is into `master`

**To test:**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-19 14:57 UTC, jmborr commented
@KedoKudo For this part of your workbench test:
```python
SCDCalibratePanels(
        PeakWorkspace="pws",
        a=silicon.a,
        b=silicon.b,
        c=silicon.c,
        alpha=silicon.alpha,
        beta=silicon.beta,
        gamma=silicon.gamma,
        CalibrateL1=True,
        CalibrateBanks=False,
        CalibrateT0=True,
        TuneSamplePosition=True,
        OutputWorkspace="testCaliTable",
        XmlFilename="test.xml",
    )
```
can you define namedtuple `silicon`?

2021-05-19 14:59 UTC, KedoKudo commented
> @KedoKudo For this part of your workbench test:
> 
> ```python
> SCDCalibratePanels(
>         PeakWorkspace="pws",
>         a=silicon.a,
>         b=silicon.b,
>         c=silicon.c,
>         alpha=silicon.alpha,
>         beta=silicon.beta,
>         gamma=silicon.gamma,
>         CalibrateL1=True,
>         CalibrateBanks=False,
>         CalibrateT0=True,
>         TuneSamplePosition=True,
>         OutputWorkspace="testCaliTable",
>         XmlFilename="test.xml",
>     )
> ```
> 
> can you define namedtuple `silicon`?

Sorry about the confusion, should have updated the function call to use natrolite.
The testing script in the description is not updated.

2021-05-19 19:35 UTC, jmborr commented
I don't understand the output I'm getting. I moved both the moderator and the sample position like this:
```python
CloneWorkspace(InputWorkspace='pws', OutputWorkspace='clone')

MoveInstrumentComponent(
    Workspace='clone',
    ComponentName='moderator',
    X=0, Y=0, Z=-0.01,
    RelativePosition=True,
)


MoveInstrumentComponent(
    Workspace='clone',
    ComponentName='sample-position',
    X=0.002, Y=-0.003, Z=0,
    RelativePosition=True,
)


SCDCalibratePanels(
        PeakWorkspace="clone",
        a=natrolite.a,
        b=natrolite.b,
        c=natrolite.c,
        alpha=natrolite.alpha,
        beta=natrolite.beta,
        gamma=natrolite.gamma,
        CalibrateL1=True,
        CalibrateBanks=False,
        CalibrateT0=True,
        TuneSamplePosition=True,
        OutputWorkspace="testCaliTable",
        XmlFilename="/tmp/test.xml",
    )
```
And the log output seems to indicate that the sample position is calibrated _twice_

> ** Calibrating L1 (moderator) as requested
> -- Fit L1 results using 11076 peaks:
>     dL1: 0.010362 
>     L1 18.01 -> 17.9996 
>     dT0 = -0.154085 
>     dSamplePos = (-0.00199842,0.00300038,7.27082e-07)
>     chi2/DOF = 2.45087e-06
> ** Tunning sample position as requested
> -- Tune SamplePos = (0,0,0) is below tolerance (1e-06), zero it
> -- Tune SamplePos results using 11076 peaks:
>   deltaSamplePos = (0,0,0)
>   chi2/DOF = 2.45072e-06
> -- Generate calibration table
> Generate a TableWorkspace to store calibration results.
> finished generating tables
> Generating xml tree 
> 	Saving parameter file as /tmp/test.xml
> Saving DetCal file in SCDCalibrate2.DetCal

Is this supposed to happen?

2021-05-19 19:50 UTC, KedoKudo commented
> I don't understand the output I'm getting. I moved both the moderator and the sample position like this:
> 
> ```python
> CloneWorkspace(InputWorkspace='pws', OutputWorkspace='clone')
> 
> MoveInstrumentComponent(
>     Workspace='clone',
>     ComponentName='moderator',
>     X=0, Y=0, Z=-0.01,
>     RelativePosition=True,
> )
> 
> 
> MoveInstrumentComponent(
>     Workspace='clone',
>     ComponentName='sample-position',
>     X=0.002, Y=-0.003, Z=0,
>     RelativePosition=True,
> )
> 
> 
> SCDCalibratePanels(
>         PeakWorkspace="clone",
>         a=natrolite.a,
>         b=natrolite.b,
>         c=natrolite.c,
>         alpha=natrolite.alpha,
>         beta=natrolite.beta,
>         gamma=natrolite.gamma,
>         CalibrateL1=True,
>         CalibrateBanks=False,
>         CalibrateT0=True,
>         TuneSamplePosition=True,
>         OutputWorkspace="testCaliTable",
>         XmlFilename="/tmp/test.xml",
>     )
> ```
> 
> And the log output seems to indicate that the sample position is calibrated _twice_
> 
> > ** Calibrating L1 (moderator) as requested
> > -- Fit L1 results using 11076 peaks:
> > dL1: 0.010362
> > L1 18.01 -> 17.9996
> > dT0 = -0.154085
> > dSamplePos = (-0.00199842,0.00300038,7.27082e-07)
> > chi2/DOF = 2.45087e-06
> > ** Tunning sample position as requested
> > -- Tune SamplePos = (0,0,0) is below tolerance (1e-06), zero it
> > -- Tune SamplePos results using 11076 peaks:
> > deltaSamplePos = (0,0,0)
> > chi2/DOF = 2.45072e-06
> > -- Generate calibration table
> > Generate a TableWorkspace to store calibration results.
> > finished generating tables
> > Generating xml tree
> > Saving parameter file as /tmp/test.xml
> > Saving DetCal file in SCDCalibrate2.DetCal
> 
> Is this supposed to happen?

TL;DR; Yes

Longer version:
L1, T0 and sample position are dependent on each other, therefore it is better to have the optimizer optimize them together instead of one at a time (something I noticed while working on this user story).
So the first log is the one doing the heavy lifting as it finds the answer, and the second one is more of a sanity check that the sample position found along with L1 is already good enough.

2021-05-19 20:45 UTC, jmborr commented
Well, if this threw me into confusion then it's highly likely other users will be also confused with looking at the log messages.  You may want to rephrase a bit the log output so that what the log states is consistent with what the algorithm does.

also, what are the units of `dT0`? I see `dT0 = -0.154085` but is this micro-seconds?

2021-05-19 21:24 UTC, KedoKudo commented
> Well, if this threw me into confusion then it's highly likely other users will be also confused with looking at the log messages. You may want to rephrase a bit the log output so that what the log states is consistent with what the algorithm does.
> 
> also, what are the units of `dT0`? I see `dT0 = -0.154085` but is this micro-seconds?

yes, dT0 is in micro seconds.

2021-05-19 22:14 UTC, jmborr commented
> > Well, if this threw me into confusion then it's highly likely other users will be also confused with looking at the log messages. You may want to rephrase a bit the log output so that what the log states is consistent with what the algorithm does.
> > also, what are the units of `dT0`? I see `dT0 = -0.154085` but is this micro-seconds?
> 
> yes, dT0 is in micro seconds.

Could you write the units after the number, in the log message?

2021-05-19 22:15 UTC, jmborr commented
If I change the values in the `T0` column of the `pws` `PeaksWorkspace`, will `SCDCalibratePanels` pick these values or will it just use with the wavelength and ignore the `T0` values? I'm trying to figure out a way to test for `T0`

2021-05-19 23:10 UTC, KedoKudo commented
> > > Well, if this threw me into confusion then it's highly likely other users will be also confused with looking at the log messages. You may want to rephrase a bit the log output so that what the log states is consistent with what the algorithm does.
> > > also, what are the units of `dT0`? I see `dT0 = -0.154085` but is this micro-seconds?
> > 
> > 
> > yes, dT0 is in micro seconds.
> 
> Could you write the units after the number, in the log message?

I will add the unit in the log message.

2021-05-19 23:11 UTC, KedoKudo commented
> If I change the values in the `T0` column of the `pws` `PeaksWorkspace`, will `SCDCalibratePanels` pick these values or will it just use with the wavelength and ignore the `T0` values? I'm trying to figure out a way to test for `T0`

T0 is not a property of peaks, so you will have to update the wavelength of all peaks to get what you want.

2021-05-19 23:33 UTC, jmborr commented
> T0 is not a property of peaks, so you will have to update the wavelength of all peaks to get what you want.

I forgot `T0` is calculated, not stored.  
If I'm not mistaken (can you verify?), I could change the wavelength according to this simple formula:  
<img src="https://render.githubusercontent.com/render/math?math=\lambda' = \lambda \frac{TOF}{TOF %2B T_0}">

2021-05-19 23:39 UTC, KedoKudo commented
> > T0 is not a property of peaks, so you will have to update the wavelength of all peaks to get what you want.
> 
> I forgot `T0` is calculated, not stored.
> If I'm not mistaken (can you verify?), I could change the wavelength according to this simple formula:
> ![](https://render.githubusercontent.com/render/math?math=\lambda' = \lambda \frac{TOF}{TOF %2B T_0})

It might be easier to just copy what [`LoadIsawDetcal`](https://github.com/mantidproject/mantid/blob/20aa5d47c871facd2fde76ff414b19872dd66101/Framework/DataHandling/src/LoadIsawDetCal.cpp#L214) did: using `ChangeBinOffset` to set T0.

2021-05-20 00:55 UTC, KedoKudo commented
> > It might be easier to just copy what [`LoadIsawDetcal`](https://github.com/mantidproject/mantid/blob/20aa5d47c871facd2fde76ff414b19872dd66101/Framework/DataHandling/src/LoadIsawDetCal.cpp#L214) did: using `ChangeBinOffset` to set T0.
> 
> This should work with an EventsWorkspace containing diffraction data but as far as I can tell, your workbench script invokes `CreatePeaksWorkspace` which instantiates some peak objects without using any events or TOF histograms. Thus, there are no events of histograms to shift. The output of `CreateSimulationWorkspace` (workspace `csw`) is only used to fetch the instrument geometry, if I'm correct.
> 
> I see there are no test to verify that `T0` spits the correct shift when the diffraction data is shifted. I tried including this function in your script workbench script and then calibrate _only_ `T0`:
> 
> ```python
> CloneWorkspace(InputWorkspace='pws', OutputWorkspace='clone')
> 
> def shift_by_t0(input_workspace, t0):
>     r"""
>     @brief Shift the TOF of all peaks by T0
>     @details The contents of the following column can be changed: 'Wavelength'.
>     Other columns ('TOF', 'Energy', 'DSpacing') are read-only.
>     @param t0: shift in TOF, in micro-seconds
>     """
>     w = mtd[str(input_workspace)]
>     tofs = w.column('TOF')
>     waves = w.column('Wavelength')
>     for i in range(w.rowCount()):
>         new_wave = waves[i] * (tofs[i] + t0) / tofs[i]
>         w.setCell('Wavelength', i, new_wave)
> 
> shift_by_t0('clone', 90)
> 
> SCDCalibratePanels(
>         PeakWorkspace="clone",
>         a=natrolite.a,
>         b=natrolite.b,
>         c=natrolite.c,
>         alpha=natrolite.alpha,
>         beta=natrolite.beta,
>         gamma=natrolite.gamma,
>         CalibrateL1=False,#True,
>         CalibrateBanks=False,
>         CalibrateT0=True,
>         TuneSamplePosition=Fals, #True,
>         OutputWorkspace="testCaliTable",
>         XmlFilename="/tmp/test.xml",
>     )
> ```
> 
> I find that no matter what the value of `t0` I used (I used 30, 60, 90) I always obtain `dT0 = -9.9996`. The exception is `t0=0`, for which I get `dT0 = -0.0495253`. All this means either my shifting function is not correcting shifting TOF (I changed the wavelength but maybe I also have to change Qlab and Qsample) or the calibration of `T0` is incorrect.

dT0 is calculated based on Qlab, therefore updating QLab is necessary.
Otherwise SCDCalibratePanels2 cannot see the effect of T0.

2021-05-24 12:56 UTC, jmborr requested changes
> dT0 is calculated based on Qlab, therefore updating QLab is necessary.
> Otherwise SCDCalibratePanels2 cannot see the effect of T0.  
I have rescaled `QLab` and `QSample`  but still get the same `dT0`, irrespective of the `T0` shift.
```python
def shift_by_t0(input_workspace, t0):
    r"""
    @brief Shift the TOF of all peaks by T0
    @details The contents of the following column can be changed: 'Wavelength'.
    Other columns ('TOF', 'Energy', 'DSpacing') are read-only.
    @param t0: shift in TOF, in micro-seconds
    """
    w = mtd[str(input_workspace)]
    tofs = w.column('TOF')
    waves = w.column('Wavelength')
    qlabs = w.column('QLab')
    qsamples = w.column('QSample')
    for i in range(w.rowCount()):
        new_wave = waves[i] * (tofs[i] + t0) / tofs[i]
        w.setCell('Wavelength', i, new_wave)
        w.setCell('QLab', i, qlabs[i] * (waves[i] / new_wave))
        w.setCell('QSample', i, qsamples[i] * (waves[i] / new_wave))
```

2021-05-24 13:02 UTC, KedoKudo commented on Framework/API/src/FileFinder.cpp
> +          path = findRun(instrSName + *h, exts, useExtsOnly);
This is not part of the calibration task.
Somehow Github thinks it is :man_shrugging:

2021-05-24 13:05 UTC, KedoKudo commented on Framework/Crystal/src/SCDCalibratePanels2.cpp
> +  //  The general workflow of calibration is
Actually I did add recommendations in the documentation page that user should consider calibrate L1, T0 and sample position together if possible.
Given that different instrument will have their instrument specific needs (and this calibration alg is not restricted for one instrument), I don't really think we can provide a definitive workflow that everybody can follow.

2021-05-24 13:36 UTC, jmborr commented on Framework/Crystal/src/SCDCalibratePanels2.cpp
> +  //  The general workflow of calibration is
I thought this was the workflow that was implemented in the code, which is why I was advocating to be included in the documentation. My bad.

2021-05-24 13:38 UTC, zjmorgan commented
@jmborr Here is a Python script to adjust the TZERO offset of a peaks workspace.

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from mantid.kernel import V3D

pws = LoadNexus(Filename='/SNS/TOPAZ/shared/stories/calibration/topaz_test_data.nxs', OutputWorkspace='pws')
LoadIsawUB('pws', '/SNS/TOPAZ/IPTS-24887/shared/2021A/scolecite_100K/use_Eng/SC100K_Monoclinic_C.mat')

DetID = []
TOF = []

N = mtd['pws'].getNumberPeaks()
for i in range(N):
    TOF.append(mtd['pws'].row(i)['TOF'])
    DetID.append(mtd['pws'].row(i)['DetID'])

LoadEmptyInstrument(InstrumentName='TOPAZ', OutputWorkspace='TOPAZ')
CreatePeaksWorkspace(InstrumentWorkspace='topaz', OutputWorkspace='cws', NumberOfPeaks=0)

h = 6.62607004e-34
mn = 1.674927471e-27
 
c = h/mn

L1 = mtd['cws'].getInstrument().getComponentByName('moderator').getPos().norm()

TZERO = 1.0

for i in range(N):
    det = mtd['cws'].getInstrument().getDetector(DetID[i]).getPos()
    L2 = det.norm()
    lamda = c*(TOF[i]+TZERO)/(L1+L2)*1e+4
    Q = V3D(-det.X()/L2*2*np.pi/lamda,-det.Y()/L2*2*np.pi/lamda,(1-det.Z()/L2)*2*np.pi/lamda)
    mtd['cws'].addPeak(mtd['cws'].createPeak(Q))
    mtd['cws'].getPeak(i).setGoniometerMatrix(mtd['pws'].getPeak(i).getGoniometerMatrix())
    mtd['cws'].getPeak(i).setRunNumber(mtd['pws'].getPeak(i).getRunNumber())
    mtd['cws'].getPeak(i).setIntHKL(mtd['pws'].getPeak(i).getIntHKL())
    HKL = mtd['pws'].getPeak(i).getHKL()
    mtd['cws'].getPeak(i).setHKL(HKL[0],HKL[1],HKL[2])
```

2021-05-24 17:22 UTC, jmborr commented
> @jmborr Here is a Python script to adjust the TZERO offset of a peaks workspace.  

@zjmorgan  Are these peaks from Natrolite or some other sample. Below's the call to `SCDCalibratePanels` I'm using but it assumes the sample's Natrolite 
```python
    SCDCalibratePanels(
            PeakWorkspace="cws",
            a=natrolite.a,
            b=natrolite.b,
            c=natrolite.c,
            alpha=natrolite.alpha,
            beta=natrolite.beta,
            gamma=natrolite.gamma,
            CalibrateL1=False,#True,
            CalibrateBanks=False,
            CalibrateT0=True,
            ToleranceT0=0.01,
            SearchRadiusT0=TZERO * 2,
            TuneSamplePosition=False, #True,
            OutputWorkspace="testCaliTable",
            XmlFilename="/tmp/test.xml",
        )
```
And this is what I get for the correction `dT0`:

| input T0  (micro-s) | dT0 (micro-s)  |
|---:|---:|
| 1  |  |
| 10  |   |
|  100 | -9.99606  |

2021-05-24 17:25 UTC, zjmorgan commented
@jmborr My mistake. This data is for scolecite a slightly different crystal.
```python
def convert(dictionary):
    return namedtuple('GenericDict', dictionary.keys())(**dictionary)

import os
directory = os.path.dirname(os.path.realpath(__file__))

lc_scolecite = {
    "a": 6.51201,  # A
    "b": 18.95454,  # A
    "c": 9.57822,  # A
    "alpha": 90,  # deg
    "beta": 108.9211 ,  # deg
    "gamma": 90,  # deg
}

scolecite = convert(lc_scolecite)
```

2021-05-24 17:26 UTC, KedoKudo commented
> @jmborr My mistake. This data is for scolecite a slightly different crystal.
> 
> ```python
> def convert(dictionary):
>     return namedtuple('GenericDict', dictionary.keys())(**dictionary)
> 
> import os
> directory = os.path.dirname(os.path.realpath(__file__))
> 
> lc_scolecite = {
>     "a": 6.51201,  # A
>     "b": 18.95454,  # A
>     "c": 9.57822,  # A
>     "alpha": 90,  # deg
>     "beta": 108.9211 ,  # deg
>     "gamma": 90,  # deg
> }
> 
> scolecite = convert(lc_scolecite)
> ```

I think the c here is the incorrect one, here are the one from the corresponding user story
```
lc_scolecite = {
    "a": 6.51201,  # A
    "b": 18.95454,  # A
    "c": 9.75822,  # A
    "alpha": 90,  # deg
    "beta": 108.9211 ,  # deg
    "gamma": 90,  # deg
}

scolecite = convert(lc_scolecite)
```

2021-05-24 17:29 UTC, zjmorgan commented
> I think the c here is the incorrect one, here are the one from the corresponding user story [SCD316](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/316)

That is true, however, the synthetic data is still generated with the incorrect data with `c=9.57`.

2021-05-24 19:42 UTC, jmborr commented
@KedoKudo @zjmorgan  The final test

```python
######################################
# Perturb the source, sample, and T0
######################################
CloneWorkspace(InputWorkspace='pws', OutputWorkspace='clone')
MoveInstrumentComponent(
    Workspace='clone',
    ComponentName='moderator',
    X=0, Y=0, Z=-0.01,
    RelativePosition=True,
)
MoveInstrumentComponent(
    Workspace='clone',
    ComponentName='sample-position',
    X=0.002, Y=-0.003, Z=-0.003,
    RelativePosition=True,
)
shift_by_t0('clone', 42.0)
SCDCalibratePanels(
        PeakWorkspace="clone",
        a=natrolite.a,
        b=natrolite.b,
        c=natrolite.c,
        alpha=natrolite.alpha,
        beta=natrolite.beta,
        gamma=natrolite.gamma,
        CalibrateL1=True,
        ToleranceL1=0.0001,
        SearchRadiusL1=0.1,
        CalibrateBanks=False,
        CalibrateT0=True,
        ToleranceT0=0.01,
        SearchRadiusT0=100.0,
        TuneSamplePosition=True,
        ToleranceSamplePos=0.0001,
        SearchRadiusSamplePos=0.01,
        OutputWorkspace="testCaliTable",
        XmlFilename="/tmp/test.xml",
    )
```

results in the following adjustments:

```shell
** Calibrating L1 (moderator) as requested
-- Fit L1 results using 11076 peaks:
    dL1: 0.010362 
    L1 18.01 -> 17.9996 
    dT0 = -42.1541 
    dSamplePos = (-0.00199842,0.00300038,0.00300073)
    chi2/DOF = 2.45087e-06
** Tunning sample position as requested
-- Tune SamplePos = (0,0,0) is below tolerance (0.0001), zero it
-- Tune SamplePos results using 11076 peaks:
  deltaSamplePos = (0,0,0)
  chi2/DOF = 2.45072e-06
```

I believe they are pretty good. `L1` differs by 0.3mm and `T0` by 0.1 micro-second.
This PR is ready to be approved, unless any of you have objections to make.

2021-05-24 21:34 UTC, jmborr commented
> That is true, however, the synthetic data is still generated with the incorrect data with `c=9.57`.

If I use this value for `c`, then the calibration becomes worse!

| input T0  (micro-s) | dT0 (micro-s)  |
|---:|---:|
| 1  | -1.99975 |
| 10  | -19.9971  |
|  100 | -127.774  |

I'm going to stick with the workbench script at the top, because it creates everything from scratch. This script shows that the calibration algorithm is working

2021-05-24 21:35 UTC, jmborr approved these changes

2021-05-25 12:37 UTC, merged