Add new diagnostic plot scripts for SCDCalibratePanels2 output
mantidproject/mantid pull request #31533
Opened 2021-05-20 15:44 UTC by KedoKudo

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-05-20 21:43 UTC, zjmorgan commented
Getting `AttributeError: 'Figure' object has no attribute 'add_gridspec'` when trying to run the example. I wonder if this is a Matplotlib version problem?

2021-05-20 22:01 UTC, KedoKudo commented
> Getting `AttributeError: 'Figure' object has no attribute 'add_gridspec'` when trying to run the example. I wonder if this is a Matplotlib version problem?

I believe it is a version issue.  You might need to update your matplotlib version or switch back to legacy format, which does not use the grid layout.

2021-05-20 22:04 UTC, zjmorgan reviewed
> > Getting `AttributeError: 'Figure' object has no attribute 'add_gridspec'` when trying to run the example. I wonder if this is a Matplotlib version problem?
> 
> I believe it is a version issue. You might need to update your matplotlib version or switch back to legacy format, which does not use the grid layout.

That latter works!

2021-05-20 22:13 UTC, KedoKudo commented on scripts/SCD_Reduction/SCDCalibratePanels2Diagnostics.py
> +        hkl = np.array(pk.getHKL())
okay, I will make the change.

2021-05-21 12:30 UTC, zjmorgan commented
Code looks good and provides similar diagnostics to ISAW. Changing this to `IntHKL` should satisfy all requirements.

2021-05-21 12:32 UTC, zjmorgan requested changes
Change 'getHKL' to 'getIntHKL' to compare the integer indices.

2021-05-21 12:45 UTC, zjmorgan approved these changes

2021-05-21 18:48 UTC, merged