changed the label for the output ws of cc
mantidproject/mantid pull request #31578
Opened 2021-05-25 15:58 UTC by walshmm

**Description of work.**
PR addresses [this defect](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/275)

- [x] `Framework/Algorithms/src/CorelliCrossCorrelate.cpp ` modified
- [x] `Framework/Algorithms/src/CrossCorrelate.cpp ` modified
- [ ] pr against `ornl-next`

Companion to PR ____ 

**To test:**

Launch Mantid workbench and run the following script from the UI:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

#Create a workspace with 2 spectra with five bins of width 0.5
ws = CreateSampleWorkspace(BankPixelWidth=1, XUnit='dSpacing', XMax=5, BinWidth=0.25)
ws = ScaleX(InputWorkspace='ws', Factor=0.5, Operation='Add', IndexMin=1, IndexMax=1)
# Run algorithm  CrossCorrelate
OutputWorkspace = CrossCorrelate(InputWorkspace='ws', WorkspaceIndexMax=1, XMin=2, XMax=4)

# Show workspaces
print("AutoCorrelation {}".format(OutputWorkspace.readY(0)))
print("CrossCorrelation {}".format(OutputWorkspace.readY(1)))
```
Then right click OutputWorkspace and generate a spectrum plot from 1-4, confirming that the units are no longer d-spacing but rather something more accurate. (Bins of Shift)

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-06-04 18:21 UTC, rosswhitfield requested changes
The issue with this change is that the output of `CrossCorrelate` is usually fed into `GetDetectorOffsets` which [checks that the input workspace is in d-spacing](https://github.com/mantidproject/mantid/blob/b465e0128bf3b58c7c31f4d50f28dca9901e6316/Framework/Algorithms/src/GetDetectorOffsets.cpp#L36). The validation in `GetDetectorOffsets` sould be expanded to check for either d-spacing or these new units.

2021-06-04 19:39 UTC, wdzhou commented
> The issue with this change is that the output of `CrossCorrelate` is usually fed into `GetDetectorOffsets` which [checks that the input workspace is in d-spacing](https://github.com/mantidproject/mantid/blob/b465e0128bf3b58c7c31f4d50f28dca9901e6316/Framework/Algorithms/src/GetDetectorOffsets.cpp#L36). The validation in `GetDetectorOffsets` sould be expanded to check for either d-spacing or these new units.

In fact, the workspace as the output of `CrossCorrelate` shall not have unit as dSpacing at all.  The previous implementation is not correct and causes many confusion.

2021-06-04 19:44 UTC, rosswhitfield commented
> > The issue with this change is that the output of `CrossCorrelate` is usually fed into `GetDetectorOffsets` which [checks that the input workspace is in d-spacing](https://github.com/mantidproject/mantid/blob/b465e0128bf3b58c7c31f4d50f28dca9901e6316/Framework/Algorithms/src/GetDetectorOffsets.cpp#L36). The validation in `GetDetectorOffsets` sould be expanded to check for either d-spacing or these new units.
> 
> In fact, the workspace as the output of `CrossCorrelate` shall not have unit as dSpacing at all. The previous implementation is not correct and causes many confusion.

Yes, that is what this PR is fixing. But in fixing that `GetDetectorOffsets` now won't accept the output of CrossCorrelate as input.

2021-06-09 14:12 UTC, rosswhitfield approved these changes

2021-06-11 09:46 UTC, DavidFair approved these changes

2021-06-11 09:46 UTC, merged