return signed offset from alg GetDetectorOffsets
mantidproject/mantid pull request #31701
Opened 2021-06-02 21:09 UTC by stonecoldhughes

**Description of work.**

Add "signed" mode to GetDetectorOffsets. Update documentation. Still in progress.

**To test:**

> cd build/bin;
> ./AlgorithmsTest GetDetectorOffsetsTest

Fixes https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/263
 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-06-04 20:11 UTC, rosswhitfield requested changes

2021-06-04 20:11 UTC, rosswhitfield commented on docs/source/algorithms/GetDetectorOffsets-v1.rst
> +:math:`offset = peak_center*-1`
This isn't rendering correctly
![2021-06-04-160824_266x42_scrot](https://user-images.githubusercontent.com/5595210/120857360-217f2100-c54f-11eb-92d4-6678b8e770b3.png)

2021-06-04 20:11 UTC, rosswhitfield commented on docs/source/algorithms/GetDetectorOffsets-v1.rst
> +:math:`offset = -1*peakCentre*step/(dreference+PeakCentre*step)`
You probably don't need to include the `-1*`, just do `-peakCentre*...`. Same for the other equations.

2021-06-04 20:11 UTC, rosswhitfield commented on Framework/Algorithms/src/GetDetectorOffsets.cpp
> +  if (mode == offset_mode::signed_offset) {
Can you add a test for this new mode https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/test/GetDetectorOffsetsTest.h

2021-06-09 13:31 UTC, rosswhitfield approved these changes

2021-06-10 13:07 UTC, stonecoldhughes commented
@mantidproject/gatekeepers this is ready for merge! Thanks

2021-06-10 15:14 UTC, merged