Implement PolarizationAngleCorrectionMD (master)
mantidproject/mantid pull request #31702
Opened 2021-06-03 00:19 UTC by wdzhou

**Description of work.**

PolarizationAngleCorrectionMD

**To test:**

Fixes #31679. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-06-07 21:48 UTC, AndreiSavici requested changes
Works as expected, but need simple changes as described.

2021-06-07 21:48 UTC, AndreiSavici commented on docs/source/algorithms/PolarizationAngleCorrectionMD-v1.rst
> +**Example - Run Applied Detailed Balance**
Wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +   * @brief Apply detailed balance to event workspace
Wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +    // apply detailed balance and convert to MD for event workspace 2
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +    // apply detailed balance and convert to MD for event workspace 1
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +   * @brief Test apply detailed balance to 1 run
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +   * @brief Calculate detailed balance, convert to MD and merge as the old way
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/src/PolarizationAngleCorrectionMD.cpp
> + * @brief Apply detailed balance to each MDEvent in MDEventWorkspace
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/src/PolarizationAngleCorrectionMD.cpp
> +      "The output MDEventWorkspace with detailed balance applied");
no detailed balance

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/inc/MantidMDAlgorithms/PolarizationAngleCorrectionMD.h
> +  /// Apply detailed balance to each MDEvent
wrong comment

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +    // Calculate detailed balance for the single MDEventWorkspace
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +    // Calculate detailed balance for the single MDEventWorkspace
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +   * @brief Test applying detailed balance to 2 merged runs in Q_sample
wrong name

2021-06-07 21:48 UTC, AndreiSavici commented on Framework/MDAlgorithms/test/PolarizationAngleCorrectionMDTest.h
> +   * @brief Calculate detailed balance, convert to MD and merge as the old way
wrong name

2021-06-08 14:49 UTC, wdzhou commented on Framework/MDAlgorithms/src/PolarizationAngleCorrectionMD.cpp
> +                  "An in-plane polarization angle PAP_APA​, between -180 and 180 degrees");
copy & paste error

2021-06-08 20:23 UTC, AndreiSavici approved these changes

2021-06-10 15:20 UTC, merged