Add help button to sliceviewer
mantidproject/mantid pull request #31782
Opened 2021-06-15 08:10 UTC by joseph-torsney

Adds a help button to the sliceviewer

**To test:**

1. Open sliceviewer
2. Click the help button in the bottom left
3. Check that it opens the correct page in the mantid docs

Fixes #31262. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-07-16 12:37 UTC, RichardWaiteSTFC commented
I get a missing link - but presumably I need to build docs?
I did have one question though - is it possible to get rid of extraneous spacers/dividers?
![image](https://user-images.githubusercontent.com/55979119/125948711-a91f3e03-517b-4d4f-8bec-54389eee3a67.png)

2021-07-16 13:28 UTC, RichardWaiteSTFC commented
Built the `docs-html` OK, but when I build `docs-qthelp` i get the following error in VS
```
Error	MSB6006	"cmd.exe" exited with code -1.	docs-qthelp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	231
```
And the help page is still not working (although the link looks OK to me)

2021-08-20 12:00 UTC, thomashampson commented
I rebuilt the Windows job and built the package to test the button and can confirm it works as expected.

2021-08-20 13:22 UTC, thomashampson requested changes

2021-08-20 13:22 UTC, thomashampson commented on docs/source/release/v6.2.0/mantidworkbench.rst
> +- Improved cross-platform theming by using the same icon on all platforms for closing editor tabs.
This change was reverted, so the line shouldn't be here.

2021-08-20 14:38 UTC, thomashampson approved these changes

2021-08-20 16:53 UTC, AnthonyLim23 commented
@mantidproject/gatekeepers could we please get this merged?

2021-08-20 16:55 UTC, merged