Rename Indexes in IDA
mantidproject/mantid pull request #31865
Opened 2021-06-23 10:53 UTC by Harrietbrown

**Description of work.**

This PR renames the Indexes in IDA to be more clear in what they are. Primarily it reanames TableDatasetIndex to WorkspaceID indicating that the index was used to locate a workspace within a list of workspaces, as opposed to WorkspaceIndex which locates a spectra within a Workspace.

**To test:**

This should not change anty functionality. so long as it builds and tests pass it whould be fine. But open the interface and make sure there are no crashes when running.

Fixes #29207

*This does not require release notes* because **it is not a change to functionality.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-07-07 11:19 UTC, robertapplin requested changes
Your changes look good. I noticed a couple of things when testing IDA but I think they are unrelated:
- The `RangeSelectors` cannot be moved past 1 even when the data goes beyond 1. They can also be moved to -1 even when data stops at zero. I think this should be restricted by setting the bounds of the range selectors whenever new data with a different x range is loaded.

- When you load in two spectra (one each from two different workspaces), add a function and do a fit, switching between the datasets doesn't update the `FunctionBrowser` function

2021-07-07 11:19 UTC, robertapplin commented on qt/widgets/common/inc/MantidQtWidgets/Common/FitDomain.h
> +  FitDomain(std::string const &workspaceName, WorkspaceIndex SpectraIndex, double startX, double endX);
Can we leave this as `workspaceIndex`? This area of code only refers to a workspaceIndex and never spectraIndex so changing this variable name reduces naming consistency here

2021-07-07 11:19 UTC, robertapplin commented on qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorPresenter.h
> +                     std::vector<WorkspaceIndex> const &spectraIndices);
Can we leave this as `workspaceIndices` too as this will also reduce variable naming consistency in this file

2021-07-07 11:19 UTC, robertapplin commented on qt/widgets/common/inc/MantidQtWidgets/Common/IndexTypes.h
>  // Used to index data by workspace
Can we improve this comment to give a better description of `WorkspaceID`?

2021-07-07 11:25 UTC, robertapplin commented
Just spotted a large number of warnings in the visual studio debug console too
```
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQObject::connect: No such slot MantidQt::CustomInterfaces::IDA::FqFitDataPresenter::updateActiveDataIndex()
QLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQLayout: Attempting to add QLayout "" to MantidQt::CustomInterfaces::IDA::FitStatusWidget "", which already has a layoutQObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisElwinTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisMSDFitTab::tableExcludeChanged(const std::string &, WorkspaceID, WorkspaceIndex)
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisMSDFitTab::runAsPythonScript(const QString &, bool)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisMSDFitTab::respondToSelectedFitDataChanged(WorkspaceID)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisMSDFitTab::respondToNoFitDataSelected()
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisMSDFitTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtFitTab::tableExcludeChanged(const std::string &, WorkspaceID, WorkspaceIndex)
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtFitTab::runAsPythonScript(const QString &, bool)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtFitTab::respondToSelectedFitDataChanged(WorkspaceID)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtFitTab::respondToNoFitDataSelected()
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisIqtFitTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisConvFitTab::tableExcludeChanged(const std::string &, WorkspaceID, WorkspaceIndex)
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisConvFitTab::runAsPythonScript(const QString &, bool)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisConvFitTab::respondToSelectedFitDataChanged(WorkspaceID)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisConvFitTab::respondToNoFitDataSelected()
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisConvFitTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisFqFitTab::tableExcludeChanged(const std::string &, WorkspaceID, WorkspaceIndex)
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisFqFitTab::runAsPythonScript(const QString &, bool)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisFqFitTab::respondToSelectedFitDataChanged(WorkspaceID)
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisFqFitTab::respondToNoFitDataSelected()
QObject::connect: No such signal MantidQt::CustomInterfaces::IDA::IndirectDataAnalysisFqFitTab::runAsPythonScript(const QString &, bool)
QObject::connect:  (receiver name: 'IndirectDataAnalysis')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectAddWorkspaceDialog::addData()
QObject::connect:  (sender name:   'pbAdd')
QObject::connect:  (receiver name: 'IndirectAddWorkspaceDialog')
QObject::connect: No such slot MantidQt::CustomInterfaces::IDA::IndirectAddWorkspaceDialog::closeDialog()
QObject::connect:  (sender name:   'pbClose')
QObject::connect:  (receiver name: 'IndirectAddWorkspaceDialog')
```

2021-07-07 12:39 UTC, Harrietbrown commented on qt/scientific_interfaces/Indirect/FqFitDataPresenter.cpp
> +auto &ads_instance = Mantid::API::AnalysisDataService::Instance();
Must have missed their removal in a rebase

2021-07-07 12:58 UTC, Harrietbrown commented
>> When you load in two spectra (one each from two different workspaces), add a function and do a fit, switching between the datasets doesn't update the FunctionBrowser function

I'm not getting that

2021-07-08 16:39 UTC, robertapplin approved these changes
Thanks for those changes, it looks good to go

2021-07-13 08:05 UTC, Harrietbrown commented
could a @mantidproject/gatekeepers have a look at this.

2021-07-13 09:03 UTC, merged