Muon quickedit gets its initial values from context
mantidproject/mantid pull request #31931
Opened 2021-06-30 11:28 UTC by AnthonyLim23

**Description of work.**
When the quickedit is created, it will now get the initial values from the context. Making it easier to change the default settings in the future. 

**To test:**
Open frequency domain analysis
Load some data
Use the quick edit and make sure it behaves as expected
Do a transform 
Use the quick edit and make sure it behaves as expected

There is no associated issue.

In the release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-06-30 11:32 UTC, robertapplin requested changes
Looks good, can you add a test for this?

2021-07-01 15:45 UTC, robertapplin commented
Tests are failing @AnthonyLim23

2021-07-01 15:47 UTC, AnthonyLim23 commented on scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
> +        self.context.update_ylim_all(ylime)
```suggestion
        self.context.update_ylim_all(ylims)
```

2021-07-02 09:20 UTC, AnthonyLim23 commented on scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
> +        self.options.set_autoscale.assert_called_once_with(state)
```suggestion
        self.options.set_autoscale.assert_called_with(state)
```

2021-07-02 09:20 UTC, AnthonyLim23 commented on scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
> +        self.options.set_errors.assert_called_once_with(state)
```suggestion
        self.options.set_errors.assert_called_with(state)
```

2021-07-02 09:20 UTC, AnthonyLim23 commented on scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
> +        self.options.set_plot_x_range.assert_called_once_with(xlims)
```suggestion
        self.options.set_plot_x_range.assert_called_with(xlims)
```

2021-07-02 09:20 UTC, AnthonyLim23 commented on scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
> +        self.options.set_plot_y_range.assert_called_once_with(ylims)
```suggestion
        self.options.set_plot_y_range.assert_called_with(ylims)
```

2021-07-02 15:28 UTC, robertapplin approved these changes
Looks good to go

2021-07-05 08:34 UTC, merged