IntegrateEllipsoid now use separate integrators for Bragg peaks and satellite peaks
mantidproject/mantid pull request #32007
Opened 2021-07-12 18:13 UTC by KedoKudo

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-07-13 19:34 UTC, jmborr commented
@KedoKudo I think the documentation of `IntegrateEllipsoid` should contain a paragraph explaining the case when you want to differentiate between main and satellite peaks, and the case when you don't want that (for instance, you may have no _a priori_ knowledge of the modulation vectors). You could use parts of the workbench test script to showcase the two "execution modes". There's no need for the inserted code to become a doctests, thought, just to show how the two modes are called by the algorithm

2021-07-13 19:48 UTC, KedoKudo commented
> @KedoKudo I think the documentation of `IntegrateEllipsoid` should contain a paragraph explaining the case when you want to differentiate between main and satellite peaks, and the case when you don't want that (for instance, you may have no _a priori_ knowledge of the modulation vectors). You could use parts of the workbench test script to showcase the two "execution modes". There's no need for the inserted code to become a doctests, thought, just to show how the two modes are called by the algorithm

somehow my `git rebase` excluded the documentation updates :sweat: 

Now the PR should contain the updated documentation with examples.

2021-07-13 20:11 UTC, jmborr commented
I ran your workbench script and I'm a bit confused. The reported intensities for the satellite peak are as follows:
```bash
peak 1:
  NO satellite:   MNP = [0,0,-1], intensity = 17.00000000100127
  WITH satellite: MNP = [0,0,-1], intensity = 13.000000000500636
```
So the satellite peak is assigned more intensity when interpreted as a main peak. However, if I look at the various geometrical boundaries in the two scenarios:
```python
# Treat the satellite peak as a main peak
IntegrateEllipsoids(...RegionRadius=0.055, PeakSize=0.0425,
                    BackgroundInnerSize=0.043,  BackgroundOuterSize=0.055...)
# Tread the peak as satellite
IntegrateEllipsoids(...SatelliteRegionRadius=0.1,  SatellitePeakSize=0.08,
                    SatelliteBackgroundInnerSize=0.081, SatelliteBackgroundOuterSize=0.1...)
```
looks like the scenario that considers the satellite as a main Bragg peak  assigns a smaller Q-volume (0.0425) than the scenario that explicitly considers the peak as a satellite (0.08). Thus, I was expecting a smaller intensity in the first scenario since there should be less events to be collected because of the smaller Q-volume. Could the disparity be caused by the subtraction of the different backgrounds?

2021-07-13 20:19 UTC, KedoKudo commented
> I ran your workbench script and I'm a bit confused. The reported intensities for the satellite peak are as follows:
> 
> ```shell
> peak 1:
>   NO satellite:   MNP = [0,0,-1], intensity = 17.00000000100127
>   WITH satellite: MNP = [0,0,-1], intensity = 13.000000000500636
> ```
> 
> So the satellite peak is assigned more intensity when interpreted as a main peak. However, if I look at the various geometrical boundaries in the two scenarios:
> 
> ```python
> # Treat the satellite peak as a main peak
> IntegrateEllipsoids(...RegionRadius=0.055, PeakSize=0.0425,
>                     BackgroundInnerSize=0.043,  BackgroundOuterSize=0.055...)
> # Tread the peak as satellite
> IntegrateEllipsoids(...SatelliteRegionRadius=0.1,  SatellitePeakSize=0.08,
>                     SatelliteBackgroundInnerSize=0.081, SatelliteBackgroundOuterSize=0.1...)
> ```
> 
> looks like the scenario that considers the satellite as a main Bragg peak assigns a smaller Q-volume (0.0425) than the scenario that explicitly considers the peak as a satellite (0.08). Thus, I was expecting a smaller intensity in the first scenario since there should be less events to be collected because of the smaller Q-volume. Could the disparity be caused by the subtraction of the different backgrounds?

Yes, the instrument scientists would like the satellite peaks and Bragg peaks use completely different integration parameters, which includes how background is estimated.

2021-07-13 20:53 UTC, jmborr requested changes
Very very minor requests

2021-07-13 21:04 UTC, KedoKudo commented on docs/source/release/v6.2.0/diffraction.rst
> +- New script for doing calibration by groups, :ref:`PowderDiffractionCalibration <calibration_tofpd_group_calibration-ref>`
It is under the improvements in the release note

2021-07-13 21:05 UTC, KedoKudo commented on Framework/MDAlgorithms/test/IntegrateEllipsoidsTest.h
> +    TS_ASSERT_THROWS_NOTHING(loadalg->setPropertyValue("Filename", "TOPAZ_36079_crop.nxs"));
the testing data has already been cropped (thanks to @ckendrick), so the overall testing time is very short.

2021-07-14 17:28 UTC, jmborr requested changes
Just two minuscule typos. Slack me after you submit the corrections

2021-07-14 17:28 UTC, jmborr commented on docs/source/algorithms/IntegrateEllipsoids-v1.rst
> +the integrator used for staellite peaks are different from the one used for
typo in "staellite"

2021-07-14 17:28 UTC, jmborr commented on docs/source/algorithms/IntegrateEllipsoids-v1.rst
> +**Example - IntegrateEllipsoids with staellite peaks:**
typo in "staellite"

2021-07-14 19:35 UTC, jmborr approved these changes

2021-07-14 19:35 UTC, merged