Sequential Fitting in Muon FDA interface
mantidproject/mantid pull request #32038
Opened 2021-07-16 15:52 UTC by robertapplin

**Description of work.**
This PR adds a Sequential Fitting tab to the FDA interface. It is one of the WIMDA replacement requirements.

**To do**
- [ ] Subscribe the sequential tab notifiers to the other tabs
- [ ] Make the sequential tab compliant with the `BasicFittingModel` and not just `TFAsymmetryFittingModel`
- [ ] Release notes
- [ ] Update tests

**To test:**

Fixes #32036

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-07-20 09:38 UTC, robertapplin commented
I have created an issue to add an option for selecting the FFT imaginary and real parts separately #32050 . I'll do this in a separate PR once this is merged

2021-07-22 08:00 UTC, sf1919 requested changes
I have tested the changes and apart from a problem with FFT (which will be picked up separately in #32050 ) it functions well.

I have also reviewed the code. I have some queries about specific bits of code which would be great if you could respond to. However my biggest concern is with regards testing. You have added a huge amount of code to the basic fitting model and general fitting model but I cannot see any tests for any of the new code. Is there a reason for not testing it? 

Finally - there seems to be a bit of overlap between basic and general fitting models. Can you explain why we have these separate models? What is their role?

2021-07-26 09:20 UTC, robertapplin commented on scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_model.py
> +        single_function = functions[row_index - 1].clone() if not use_initial_values and row_index >= 1 else \
When we do a sequential fit, we pass on the end parameters of the previous fit to be the initial parameters of the next fit, so I believe this is what is going on here

2021-07-26 09:22 UTC, robertapplin commented on scripts/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_model.py
> +
Having the same name allows the Sequential fitting tab to work with a `BasicFittingModel`, a `GeneralFittingModel` or a `TFAsymmetryFittingModel`, so this is intentional

2021-07-26 09:24 UTC, robertapplin commented on scripts/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model.py
> +    def get_all_fit_function_parameter_values_for(self, fit_function: IFunction) -> list:
The 'for' refers to the parameter passed into the function. So its saying get all fit function parameter values for the provided fit function. I think this is a fairly common convention used to name functions

2021-07-26 09:59 UTC, robertapplin commented on scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py
A lot of this PR has been moving code from the TFAsymmetryModel to the General and Basic Model, so a lot of tests already exist here:
https://github.com/mantidproject/mantid/blob/9783748b9b35cb1d1f1ac24d26e6edc43d7e3fc8/scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py#L543

The private functions starting with `_` tend not to be tested directly, and are instead tested indirectly through public methods. https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods

I've added some tests for `validate_sequential_fit` as this was not tested, thanks for spotting that

2021-07-26 12:18 UTC, sf1919 commented on scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py
If the code has moved from TFAsymmetryModel should the tests move too? Sorry - just making absolutely sure!

2021-07-29 09:58 UTC, robertapplin commented on scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py
Yes I think some of the tests should probably move, I will try sort that out later today

2021-07-30 08:38 UTC, robertapplin commented
@sf1919 Thanks, this should be ready for another look. I did a rebase so only the last commit is new

2021-08-02 09:48 UTC, sf1919 approved these changes, later dismissed
Thanks for moving those tests - makes a lot more sense now.

I'm happy with the changes made and can confirm it's all still working. I have come across an issue with the Fitting tab but having checked v6.1 and a recent Nightly the erorr has crept in as part of a different PR so will raise a separate issue ticket for it.

All in all a good piece of work.

2021-08-04 10:53 UTC, gemmaguest commented
@robertapplin There are conflicts

2021-08-04 11:18 UTC, robertapplin commented
Thanks @gemmaguest its fixed now

2021-08-04 14:06 UTC, sf1919 approved these changes
Resolving merge conflict removed approval so am re-approving. Previous comments still stand and a quick test proves rebasing hasn't affected functionality.

2021-08-05 09:17 UTC, merged