WorkspaceCalculator: connection control of WorkspaceSelectors
mantidproject/mantid pull request #32076
Opened 2021-07-26 14:29 UTC by darominski

**Description of work.**

It has been found that relatively rapid changes in the ADS contents can cause hard crash coming from the `WorkspaceSelector` present in `WorkspaceCalculator` workbench plugin. The proposed solution disconnects observers of these `WorkspaceSelector` to the ADS by default and when the `WorkspaceCalculator` widget is hidden. The connection to the ADS is established only when WorkspaceSelector comes into focus, using an overloaded `focusInEvent` and a new signal: `focussed`. This already fixes the found hard crash. 

The `WorkspaceSelectors` are disconnected in the following cases:
- By default, when the widget is created,
- When the widget is hidden,
- After 'Go' button is pressed.

When one of the `WorkspaceSelectors` went into focus but was not disconnected, it can still cause an issue reported in #32032 . A `focusOutEvent` emitted when `WorkspaceSelector` goes out of focus cancels user's selection, so cannot be dependent upon. Also, a `focusOutEvent` on the widget is not properly triggered even then `focusPolicy` is set (e.g. to 'ClickFocus'), and neither does the `leaveEvent` cannot be used reliably as it triggers too often for a small widget such as `WorkspaceCalculator`. 

**To test:**

Run the following script:

```
from mantid.simpleapi import *
ws_list = []

for i in range(50000):
    print(i)
    name = "ws" + str(i)
    CreateSingleValuedWorkspace(OutputWorkspace=name, DataValue=0)
    ws_list.append(name)
    if i % 10 == 0:     
        DeleteWorkspaces(WorkspaceList=ws_list)
        ws_list.clear()
```

There should be no crashes when the `WorkspaceCalculator` widget is hidden, has not been interacted with, or has been interacted with but the 'Go' button was pressed. 

Fixes #32032 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-08-13 07:25 UTC, gvardany commented
@darominski I think there is some misunderstanding. What I meant is that we should add a switch to the `WorkspaceSelector` whether to observe the ADS. The host GUI should decide if that makes sense or not. We should not completely remove that, as it is used in many places and might be expected to work as is elsewhere.

2021-08-13 07:31 UTC, darominski commented
> @darominski I think there is some misunderstanding. What I meant is that we should add a switch to the `WorkspaceSelector` whether to observe the ADS. The host GUI should decide if that makes sense or not. We should not completely remove that, as it is used in many places and might be expected to work as is elsewhere.

I believe there was indeed a misunderstanding, especially as of commit f7418ad, this feature was present in the `WorkspaceSelector`, with the addition of functions that would connect and disconnect the observers. Then, the observer's status could be managed by the hosting GUI, in this case the `WorkspaceCalculator`. There, the logic was to disconnect them after a specified idle time, and in other cases when the interaction with `WorkspaceSelector` could be assumed to be finished. In this case, I am going to revert back to commit f7418ad and we can discuss the logic of deciding when the observers are disconnected.

2021-08-16 14:37 UTC, gvardany commented
That idle time is exactly what I'm worried about, many things can happen during that. Ideally, we should disconnect immediately, once a choice is made in the selector. Clicking on it again can query the ADS again.

2021-08-19 12:11 UTC, gvardany commented
I removed the disconnect on timeout, and cabled it to `activated` signal instead. Also made the event handlers in `WorkspaceSelector` synchronized. This is ready for another review.

2021-08-24 13:11 UTC, robertapplin requested changes
I can confirm that there is no crash for cases 1, 2 and 3. I also couldn't cause a crash for cases 4 and 5 - are we still looking for solutions to these? If so, is this PR still ready to go in without solutions to cases 4 and 5?

The code changes also look good, I just had one very minor suggestion

2021-08-24 13:11 UTC, robertapplin commented on qt/widgets/common/src/WorkspaceSelector.cpp
> +bool WorkspaceSelector::isConnected() { return m_connected; }
can this method be `const`?

2021-08-24 13:11 UTC, robertapplin commented on docs/source/release/v6.2.0/mantidworkbench.rst
> +- ADS signal handlers are made synchronized in `WorkspaceSelector`. This reduces the probability of hard crash when interacting with the widget while a script manipulating a large number of workspace
I think this should be 'ADS signal handlers are now synchronized in the `WorkspaceSelector`'

2021-08-24 13:31 UTC, gvardany commented
Thanks for taking a look at this. Yes, I think this should not wait for the 4 and 5. Those are rare scenarios that can be investigated another time. Are you on release or debug build? Debug build doesn't crash as it is slow, so the race condition doesn't occur. It might also depend on the machine; if it is not so powerful, again the creation of workspace might take longer than the widget's reaction.

2021-08-24 14:02 UTC, robertapplin commented
> Thanks for taking a look at this. Yes, I think this should not wait for the 4 and 5. Those are rare scenarios that can be investigated another time. Are you on release or debug build? Debug build doesn't crash as it is slow, so the race condition doesn't occur. It might also depend on the machine; if it is not so powerful, again the creation of workspace might take longer than the widget's reaction.

Ah ok, I was in debug mode but just tried with release and I can see the crash for case 4 and 5. But there is no crash for 1, 2, 3 👍

2021-08-24 14:03 UTC, robertapplin approved these changes
This is a difficult issue to fix but I think this is a good solution. I am also happy for edge cases 4 and 5 to be fixed at a later date

2021-08-25 11:01 UTC, martyngigg commented
Do we have an issue recorded for looking into the edge cases?

2021-08-25 11:01 UTC, martyngigg approved these changes

2021-08-25 11:01 UTC, merged

2021-08-25 11:09 UTC, martyngigg commented
One thing that could help track down 4/5 atleast as a starting point could be a `RelWithDebInfo` build and then in a shell before you start workbench activate core dump files:
```sh
build_dir> ulimit -c unlimited
build_dir> PYTHONPATH=$PWD/bin python3 bin/workbench
```
Make the crash happen and when it does it should produce a file called `core` in the `build_dir`. Open this with gdb:
```sh
build_dir> gdb /usr/bin/python3 core
```
and it should give the location of the segfault. This avoids needing to have the debugger running with the program which can slow it down and mean the bug is not produced.

2021-08-25 11:37 UTC, gvardany commented
Just opened the follow-up issue https://github.com/mantidproject/mantid/issues/32308.