32093 max ent groups
mantidproject/mantid pull request #32104
Opened 2021-07-29 10:45 UTC by AnthonyLim23

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-07-30 16:57 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> -        final_options = self.load.getGroupedWorkspaceNames()
check it call load and runs

2021-07-30 16:58 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        # if phase table is outputed
check ifs

2021-07-30 16:58 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        if self.use_groups and self.get_num_groups ==0:
check ifs

2021-07-30 16:58 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +    def _create_group_table(self):
test this

2021-07-30 16:58 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        run = self.view.get_run
check gives correct args

2021-07-30 16:58 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        phase_table_list = []
check inc/ex groups correctly

2021-08-02 10:34 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        phase_table_list = []
check if

2021-08-05 09:39 UTC, Pasarus requested changes, later dismissed
Whilst testing this PR I fail at the line:

`For the phase table row, there will only be one option "None"` , where MUSR6226_raw_data FD; etc is present when it shouldn't be.
After attempting to continue in case it was an issue, I get the following error:
![image](https://user-images.githubusercontent.com/24723609/128321464-8a84939b-f78b-4eeb-b141-36c408f8e9b4.png)

2021-08-05 09:50 UTC, AnthonyLim23 commented
Sorry, I dont understand the steps you have taken to get there.

If you dont select the "output phase table" you will only ever be able to do the "None" option

2021-08-06 10:18 UTC, AnthonyLim23 commented
unrelated failure

2021-08-06 13:34 UTC, AnthonyLim23 commented on scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
> +        print("moo", groups)
```suggestion
```

2021-08-06 13:51 UTC, Matt-Cumber requested changes
Co-add doesn't play nice.
Load HIFI84447-8 and tick co add
Go to transform tab
Change FFT to maxent (FFT works with co-add might be worth a look)
Click calculate
Crash (but can continue)

2021-08-06 15:00 UTC, Matt-Cumber approved these changes
Looks good. Test failure is unrelated

2021-08-09 10:17 UTC, merged

2021-08-09 10:18 UTC, DannyHindson commented
RHEL7 failure was due to unreliable test so have merged this without waiting for that to pass