Add option to show/hide legend in plot context menu
mantidproject/mantid pull request #32112
Opened 2021-07-30 11:16 UTC by joseph-torsney

Adds option to show/hide legend in plot context menu so that it is quicker to do this!

**To test:**
1. Open a plot on a workspace.
2. Right click on the axes `Legend > Show/hide legend`
3. Test that this hides the legend, then test that doing it again shows the legend.

Additionally, check that when a plot is made with no legend you can still show it via `Legend > Show/hide legend`. For example on the plot generated by this script:
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt

ws = CreateSampleWorkspace()
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
ax.plot(ws, specNum=1)
fig.show()

```

Fixes #29679. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-08-04 15:02 UTC, thomashampson requested changes
Nice addition of functionality. I think a small tweak would improve it.

2021-08-04 15:02 UTC, thomashampson commented on qt/applications/workbench/workbench/plotting/figureinteraction.py
> +        menu.addMenu(legend_menu)
If you did this, you might as well pass the legend handle to the `_toggle_legend_and_redraw()` function rather than the axes.

2021-08-05 15:23 UTC, joseph-torsney commented on qt/applications/workbench/workbench/plotting/figureinteraction.py
> +        menu.addMenu(legend_menu)
I don't think passing the legend handle to the `_toggle_legend_and_redraw()` will work because if there is no legend, we want to call `ax.legend()`

2021-08-05 16:02 UTC, thomashampson approved these changes
Looking good

2021-08-09 11:03 UTC, merged

2021-08-09 11:03 UTC, DannyHindson commented
Merging despite RHEL7 failure because failure originates from unreliable test + I don't believe these changes will impact any system tests