Fix a gcc 11 error
mantidproject/mantid pull request #32190
Opened 2021-08-11 08:32 UTC by StephenSmith25

**Description of work.**
Conda build uses gcc 11 on Linux, this produces an error while building mantid due to a missing definition of std::size_t. 

**To test:**
Builds pass

*There is no associated issue.*

*This does not require release notes* because its a developer change

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-08-11 09:56 UTC, Pasarus requested changes
Would it be possible to ensure GCC 11 in our linux builds from now on? I was thinking just adding it to our development environment, as we already ship 9.3.

2021-08-11 10:34 UTC, StephenSmith25 commented
Do we need to jump straight to 11? It feels like anything great than >9 would be sufficient for the time being?

2021-08-11 10:54 UTC, Pasarus commented
My reasoning for this, is because we are going to need this for Conda build anyway, so why not just move forward now? This way any regressions will be caught by our master Conda builds.

2021-08-11 11:07 UTC, martyngigg commented
> My reasoning for this, is because we are going to need this for Conda build anyway, so why not just move forward now? This way any regressions will be caught by our master Conda builds. @martyngigg what do you think?

Are we not better waiting until conda-forge moves: https://conda-forge.org/docs/user/announcements.html. I can't see anything mentioning gcc 11. I'd be suprised if they moved to a minimum version only a month after release. I don't think we want to move too far ahead of the community for standard builds. Nothing wrong with experimental builds for newer versions in the future though.

2021-08-11 11:08 UTC, StephenSmith25 commented
I probably should have given more info. Conda forge pins the compilers to gcc 9, its just locally if you're building it and leave it unpinned the {cxx-compiler} metapackage will fetch gcc-11, which didn't work due to this small issue. I don't feel theres any rush to adopt gcc 11 as Its likely only me that's going to be using it now anyway..

2021-08-11 15:13 UTC, StephenSmith25 commented
Pin what, the conda build? In the end we'll be matching conda forge's pinning (which is pinned to a major version rather than a minor). If a developer wants to use a different compilers I don't see why we'd stop that.

2021-08-11 15:30 UTC, Pasarus commented
My reasoning is largely because it removes a potential issue a developer would come across when compiling and checking bugs. Say someone comes a long and something behaves differently in their Conda build to what we ship, it's problematic, I don't think it's necessarily a good idea to run different compiler versions for different parts of our flow, e.g. CI, deployment, and development environment.

2021-08-11 15:56 UTC, StephenSmith25 commented
I can see you're point, but what issues are we avoiding? We already use 3 compilers (MSVC/CLANG/GCC) in the project and we get consistent behaviour throughout (barring some floating point difference) because they all implement the C++ standard. I don't foresee Mantid behaving differently because I'm using gcc 10.3 instead of 9.3. There may be some new warnings or errors, but these mostly point out issues that we should probably fix, e.g in this case we hadn't told it where size_t was defined, maybe it was using the C type rather than the c++ type in cstddef.



Is it really common practice to specify the exact compiler version somebody can use in your project? Especially down to a minor version, for example why wouldn't we use GCC 9.4?

2021-08-12 07:28 UTC, martyngigg commented
> My reasoning is largely because it removes a potential issue a developer would come across when compiling and checking bugs. Say someone comes a long and something behaves differently in their Conda build to what we ship, it's problematic, I don't think it's necessarily a good idea to run different compiler versions for different parts of our flow, e.g. CI, deployment, and development environment.



> I can see your point, but what issues are we avoiding? We already use 3 compilers (MSVC/CLANG/GCC) in the project and we get consistent behaviour throughout (barring some floating point difference) because they all implement the C++ standard. I don't foresee Mantid behaving differently because I'm using gcc 10.3 instead of 9.3. There may be some new warnings or errors, but these mostly point out issues that we should probably fix, e.g in this case we hadn't told it where size_t was defined, maybe it was using the C type rather than the c++ type in cstddef.
> 
> Is it really common practice to specify the exact compiler version somebody can use in your project? Especially down to a minor version, for example why wouldn't we use GCC 9.4?

I think you both raise valid points here. We want the flexibility to try out new compilers easily. On Linux in the past we have been pinned by the distribution so have not really needed to think about it. I do agree that a level of consistency for a "standard" setup is useful though and for a couple of reasons:
  - new starters: we want the entry process to be smooth and that's best done by basically matching what we know works (and by works I do mean does not produce warnings/errors).
  - known good setup: if I end up using the latest compiler but conda-forge is pinned a couple of versions back then might we not have issues that say some new features are available in gcc 11 but not 9 then we will find out too late?

Is there a way we can have a compromise so that as "standard" 2 developers would get the same version but we can support some experimental opt-in where a developer understands they are on the edge?

2021-08-12 07:29 UTC, martyngigg commented
I think this is a useful conversation but could we also get this PR marked as approved as our discussion doesn't impact that the fix is good.

2021-08-12 07:29 UTC, Pasarus approved these changes

2021-08-12 10:09 UTC, merged