32079 mantidqt separate package
mantidproject/mantid pull request #32193
Opened 2021-08-11 12:08 UTC by StephenSmith25

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-14 14:36 UTC, DavidFair commented
@StephenSmith25 Is this PR still active?
If so, could you resolve the merge conflicts and I'll look to get this in rather than it lingering around

2021-09-14 14:39 UTC, StephenSmith25 commented
Yep still active

2021-09-15 15:44 UTC, DavidFair requested changes
Some high level readability improvements

We also need to add `conda-build` to the mantid-developer conda env too

I'm still building away on OSX with the various recipes...

2021-09-15 15:44 UTC, DavidFair commented on CMakeLists.txt
> +option(ENABLE_MANTIDPLOT "Enable Qt4-based gui & components" OFF)
We should nuke references to MantidPlot/Qt4 elements at this point as we see them

2021-09-15 15:44 UTC, DavidFair commented on CMakeLists.txt
> +if(ENABLE_WORKBENCH OR MANTID_QT_LIB STREQUAL "BUILD")
Could we move anything related to a QtBuild into it's own CMake file?

That way our top level CMakelists.txt reads something like:
```
if(ENABLE_WORKBENCH OR MANTID_QT_LIB STREQUAL "BUILD")
   add_file(buildconfig/CMake/MantidQtTargets.cmake)
```

But if it's too much work we can leave it for the future

2021-09-15 15:44 UTC, DavidFair commented on buildconfig/CMake/Bootstrap.cmake
> +if (MANTID_FRAMEWORK_LIB STREQUAL "BUILD")
Could we do this check once and use an internal var instead:

```
if(MANTID_FRAMEWORK_LIB STREQUAL "BUILD")
   set(MANTID_FRAMEWORK_LIB_BUILD ON)
endif()


// Some other file
if (${MANTID_FRAMEWORK_LIB_BUILD})
   // Do something
endif
```

2021-09-15 15:44 UTC, DavidFair commented on buildconfig/CMake/CommonSetup.cmake
> +if (MANTID_FRAMEWORK_LIB STREQUAL "BUILD")
Ditto about splitting this into it's own Framework_Lib cmake file (if it's trivial)

2021-09-24 13:05 UTC, DavidFair approved these changes
LGTM, we can tidy up the other minor bits as we go, but I'd like to get this big change in

I've re-tested with:
mantid-framework: Linux, OSX, Windows
mantid-qt: Windows
mantid-workbench: Windows

2021-10-01 08:19 UTC, merged