Fit to raw checkbox now works as intended
mantidproject/mantid pull request #32191
Opened 2021-08-11 08:35 UTC by tolu28-coder

**Description of work.**
This pull request fixes the isssue with the fit to raw checkbox in muon guis unchecking when no rebinned  workspaces are present.

**To test:**
1. Open muon analysis gui
2. load current run
3.  Try unchecking fit to raw checkbox this should give a warning 
4. Trying to uncheck the fit to raw checkbox again should give a warning no matter how many time you try when no rebined data is present.

Fixes #32187. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-08-11 09:24 UTC, AnthonyLim23 commented
I just looked on master and it works as expected for all runs, except the current run. I think we should be investigating why it doesn't work for that run instead of applying a sticking plaster.

2021-08-11 09:35 UTC, tolu28-coder commented
The issue still occurs on other runs i try what dataset are you using

2021-08-11 09:41 UTC, AnthonyLim23 commented
I using MUSR on master, 62260 is fine and so is the one before the current run

2021-08-11 10:01 UTC, tolu28-coder commented
The issue still occurs for me no matter what run i use

2021-08-11 10:05 UTC, AnthonyLim23 commented
Then I think you may have a bad build. 
![image](https://user-images.githubusercontent.com/25006392/129010826-2640bb0a-6255-431e-aaa1-0d68c7aa5637.png)

2021-08-11 10:10 UTC, tolu28-coder commented
> Then I think you may have a bad build.
> ![image](https://user-images.githubusercontent.com/25006392/129010826-2640bb0a-6255-431e-aaa1-0d68c7aa5637.png)

Did you try unchecking checkbox twice

2021-08-18 08:04 UTC, robertapplin requested changes
I can confirm that this is a good fix to the problem you found, I have just one small suggestion

2021-08-18 08:04 UTC, robertapplin commented on scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_function_options_view.py
> +from qtpy import QtCore
Can you move this above the `QWidget` import, and also only import `Qt` as this is all we need from `QtCore`
```suggestion
from qtpy.QtCore import Qt
from qtpy.QtWidgets import QWidget
```

2021-08-18 08:49 UTC, robertapplin commented
I can replicate this bug for all runs

I think `setChecked` doesn't update the `Qt.CheckState` and only makes a visual change to the check box, hence why it was not previously working with the `QCheckbox::stateChanged` signal

2021-08-18 10:04 UTC, robertapplin commented
It looks like something has gone wrong with the merge

2021-08-18 10:04 UTC, robertapplin requested changes

2021-08-18 10:04 UTC, robertapplin commented on scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_function_options_view.py
> +from qtpy.QtCore import Qt
Thanks for changing this, can you also put this import above the `qtpy.QtWidgets` import?

2021-08-18 10:05 UTC, tolu28-coder commented
I was able to fix it by resetting branch and rebasing on master

2021-08-18 12:24 UTC, robertapplin approved these changes, later dismissed

2021-08-19 09:31 UTC, robertapplin approved these changes

2021-08-19 13:02 UTC, merged