Muon analysis raw plot speed
mantidproject/mantid pull request #32419
Opened 2021-09-08 14:13 UTC by AnthonyLim23

**Description of work.**

The loading speed of muon analysis was slower than previous version as it was creating 16 tiled plots.

I will send an unstable build to some users to test.

**To test:**

Open muon analysis
Load some data
The load speed should be faster than without this PR

Fixes #32379

*This does not require release notes* because it fixes a speed issue of a new feature.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-08 14:14 UTC, AnthonyLim23 commented on scripts/Muon/GUI/Common/plot_widget/raw_pane/raw_pane_presenter.py
> +        #self.handle_data_updated(autoscale,hold_on)
```suggestion
```

2021-09-10 10:21 UTC, Harrietbrown submitted a review, later dismissed
With this PR I estimate an approximate 20% (3-4 seconds) speed up in loading. This is great although the load time is still noticeable. A good start for speeding up the interface.

2021-09-10 12:57 UTC, AnthonyLim23 commented
Im going to push some more changes as David has found some related speed ups

2021-09-10 15:11 UTC, DavidFair commented
> Im going to push some more changes as David has found some related speed ups

I'm going to mark this as a draft and dismiss the review then until the work is done

Also could we test the functionality beyond load times, especially around plotting as we may have unintentional breakage from this too

2021-09-10 15:19 UTC, AnthonyLim23 commented
after discussion with users, the decision is to disable it from a user's point of view

2021-09-10 15:37 UTC, AnthonyLim23 commented
@Harrietbrown could you please have another look?

2021-09-14 15:34 UTC, Harrietbrown requested changes
This is a massive improvement, loading is up to 4 times faster with these changes. but can you remove the commented lines? unless they are being kept there to be used in a latter PR?

2021-09-14 15:37 UTC, AnthonyLim23 commented
Its commented out so we can add it back in easily after the release

2021-09-15 08:18 UTC, Harrietbrown approved these changes
This massively speeds up the loading in Muon analysis and FDA. Good job.

2021-09-15 13:06 UTC, AnthonyLim23 commented
@mantidproject/gatekeepers could we get this merged please? It is blocking another piece of work

2021-09-15 13:52 UTC, merged