Deprecate CalibrateRectangularDetectors
mantidproject/mantid pull request #32430
Opened 2021-09-08 21:59 UTC by wdzhou

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-09 15:47 UTC, peterfpeterson requested changes
Minor change then this looks good to go

2021-09-09 15:47 UTC, peterfpeterson commented on docs/source/release/v6.3.0/diffraction.rst
> +- CalibrateRectangularDetectors is deprecated.
Please link to the algorithm

2021-09-10 14:59 UTC, peterfpeterson approved these changes

2021-09-10 15:14 UTC, DavidFair requested changes
Could we leave the system test in until we remove this?
Whilst it's deprecated I'm concerned about any regressions from unrelated changes, on the off-chance someone is running this

2021-09-11 12:43 UTC, wdzhou commented
The purpose of this PR is to deprecate `CalibrateRectangularDetector` because (1) `PDCalibration` has replaced it for years and (2) the algorithm underneath has inconsistent behavior in Ubuntu 20.04.

2021-09-13 10:26 UTC, DavidFair commented
> @DavidFair The purpose of this PR is to deprecate `CalibrateRectangularDetector` because (1) `PDCalibration` has replaced it for years and (2) the algorithm underneath has inconsistent behavior in Ubuntu 20.04.

So the hitch for me is deprecate != remove
Whilst it's in Mantid and callable we should have a test to make sure we don't break it (even if nobody is likely calling it) especially if it's already there for free.

If we're 100% sure absolutely nobody uses it in any way shape or form lets skip straight to removal rather than letting it rot

2021-09-16 03:01 UTC, wdzhou commented
Task was changed.  Replace by #32500

2021-09-16 03:01 UTC, closed without merging