Handle RHEL using cmake3 instead of cmake in cppcheck
mantidproject/mantid pull request #32460
Opened 2021-09-09 18:39 UTC by DavidFair

**Description of work.**
This explicitly checks which instance we have instead of hard coding. This was failing some cppcheck builds on our new RHEL builders

**To test:**
- Grab the latest docker image for CentOS (as this matches the build servers):
- `docker run -it mantidproject/mantid-development-centos7`
- Clone mantid and cd into source directory
- Run the script as follows (note the env var is required)
`WORKSPACE=$(pwd) buildconfig/jenkins/cppcheck.sh`
- Ensure CMake starts and it starts the cppcheck step, you don't need to wait for this to complete
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-10 15:52 UTC, martyngigg requested changes
The cmake3 commands work as expected but following the merge of #32458 it now needs a compiler capable of understanding C++17 so I think we need the [`SCL_ENABLE`](https://github.com/mantidproject/mantid/blob/2959feaa5b70ffac308ad106258bc8539d169f95/buildconfig/Jenkins/buildscript#L134) stuff from the buildscript too or cmake configure fails saying it doesn't understand C++17.

2021-09-10 16:58 UTC, DavidFair commented
Good shout, I completely forgot the we use SCL as it worked first time (by chance) :+1:

2021-09-23 10:36 UTC, martyngigg reviewed
I'm afraid this still isn't quite there. I get:

```sh
[abc@ndw2185 mantid_src]$ WORKSPACE=$PWD buildconfig/Jenkins/cppcheck.sh
++ dirname buildconfig/Jenkins/cppcheck.sh
+ SCRIPT_DIR=buildconfig/Jenkins
+ ALLOWED_ERRORS_COUNT=1095
+ [[ '' == *pull_requests* ]]
+ '[' -d /mantid_src/build ']'
+ cd /mantid_src/build
+ find -name cppcheck.xml -delete
++ command -v scl
+ '[' /usr/bin/scl ']'
+ CMAKE_EXE=cmake3
+ SCL_ENABLE='scl enable devtoolset-7'
+ CMAKE_INVOKE='scl enable devtoolset-7 cmake3'
+ scl enable devtoolset-7 cmake3 --version
Unable to open /etc/scl/conf/cmake3!
```

I think `scl` is a little annoying in that you have to quote the whole invocation, including arguments, as one string.

2021-09-23 12:53 UTC, DavidFair commented
Sorry about that, try giving that a go as it works locally for me (though I didn't wait for cppcheck to fully finish as it takes ~1.5 hours locally)

2021-09-23 14:46 UTC, martyngigg commented
> Sorry about that, try giving that a go as it works locally for me (though I didn't wait for cppcheck to fully finish as it takes ~1.5 hours locally)

No problem. It fell over pretty quickly for me in my clean docker container so I didn't need to wait too long - I don't blame you for not waiting that long!

2021-09-23 14:52 UTC, martyngigg approved these changes
Looks great now! Thanks.

2021-09-24 07:14 UTC, merged