Enable /bigobj on MSVC by default
mantidproject/mantid pull request #32648
Opened 2021-09-28 12:03 UTC by DavidFair

**Description of work.**
This enables the bigobj flag for targets where the number of sections in
an obj file exceeds 2^16 for ISISReflectometryTest targets causing the build to fail on MSVC debug. 
This is because the underlying target pulls in Qt and MantidQtWidgetsCommon
pushing us just over the threshold.

This is enabled by Microsoft by default for UWP apps (so has first party
support). The drawback is linkers pre-2005 cannot read from these
objects, something that will not affect us:
https://stackoverflow.com/a/15110915

**To test:**
- Build MantidScientificInterfacesISISReflectometryTestQt5 on MSVC Debug mode

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-30 11:26 UTC, martyngigg requested changes

2021-09-30 11:26 UTC, martyngigg commented on buildconfig/CMake/MSVCSetup.cmake
> +  /MP /W3 /bigobj \
I had a feeling that this already existed in a couple of places. Could we remove this now it is included globally: https://github.com/mantidproject/mantid/search?q=bigobj

2021-10-01 14:43 UTC, martyngigg approved these changes, later dismissed
Thanks for cleaning up those old targets.

2021-10-01 14:44 UTC, martyngigg commented
`cppcheck` seems broken though!

2021-10-01 15:05 UTC, DavidFair commented
I've rebased onto the latest main :crossed_fingers:

2021-10-01 15:31 UTC, martyngigg approved these changes, later dismissed

2021-10-22 08:05 UTC, martyngigg approved these changes
Looks good to me now.

2021-11-02 11:10 UTC, merged