Initial cull of master term in relation to git
mantidproject/mantid pull request #32683
Opened 2021-09-30 15:52 UTC by martyngigg

**Description of work.**

Replaces key occurrences of master with main in dev-docs and buildscript. Note that this is not everything in the codebase just important buildscripts and dev-docs so that developers see up-to-date information.

Other occurrences will be dealt with separately.

**To test:**

* Review 

*There is no associated issue.*

*This does not require release notes* because **it is an internal change.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-09-30 18:15 UTC, peterfpeterson approved these changes, later dismissed
I appreciate the couple of formatting additions hiding in here

2021-10-01 10:35 UTC, DavidFair commented on dev-docs/source/BuildingWithCMake.rst
> +For a "how is it used version" of this guide, look at the scripts used on the builservers for `windows <https://github.com/mantidproject/mantid/blob/main//buildconfig/Jenkins/buildscript.bat>`_ or `l
Looks like this one has slipped through

2021-10-01 10:35 UTC, DavidFair commented on dev-docs/source/DataFilesForTesting.rst
> +- `.../Testing/Data/ <https://github.com/mantidproject/mantid/tree/main//Testing/Data>`__
Some double `//` have slipped in here

2021-10-01 10:37 UTC, DavidFair commented on dev-docs/source/WritingPerformanceTests.rst
> +Mantid <http://builds.mantidproject.org/job/main/_performancetests2/>`__.
This has an extra slash in the job name now

2021-10-01 10:37 UTC, DavidFair requested changes
Some minor replacement mistakes, otherwise looks good

2021-10-01 14:30 UTC, DavidFair approved these changes
LGTM thanks for doing those, lets :shipit:

2021-10-01 15:56 UTC, merged