Allow Setting of Read Only Columns on table workspaces.
mantidproject/mantid pull request #32712
Opened 2021-10-05 15:49 UTC by ConorMFinn

**Description of work.**
Added the ability to use scripts to set columns in table workspaces to be read only when opened in the mantid viewer. 

**To test:**
1. This script covers most of the new functionality:
```
ws = CreateEmptyTableWorkspace()

ws.addReadOnlyColumn("int", "what")
ws.addColumn("str", "huh")
ws.addColumn("int", "eh")

ws.addRow([0, "aaa", 2])
ws.addRow([1, "bbb", 3])

ws.setCell(0, 0, 10)

ws.setColumnReadOnly("huh", True)
```
2. Check that only the `eh` column is editable in the workspace viewer. 

Fixes #20662 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-10-14 09:49 UTC, StephenSmith25 reviewed
Looks good, functions as described. Just two small comments.

2021-10-18 08:17 UTC, StephenSmith25 submitted a review, later dismissed

2021-10-18 09:33 UTC, DavidFair requested changes
Some minor points, mainly missing test(s) to make sure trying to write to a read-only column works correctly especially from Python

2021-10-19 13:14 UTC, DavidFair approved these changes
LGTM thanks :+1:

2021-10-19 13:14 UTC, merged