Rework CONDA_BUILD CMake build variable and add some more CMake docs
mantidproject/mantid pull request #32764
Opened 2021-10-13 13:24 UTC by StephenSmith25

**Description of work.**
The use of the CONDA_BUILD cmake variable has become a little jumbled. In one case its invoked as we are building in a conda environment, in the other case because we are using conda build to create a mantid package. Two situations which can suitably be described by a CONDA_BUILD variable, but are in fact two DISTINCT use cases..

This PR clarifies their use cases.

**To test:**
The builds and tests should pass. 
The docs should make sense

Fixes #32761 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-10-20 14:05 UTC, cailafinn reviewed
Builds well and is much more clear now. Just a quick question about the docs:

2021-11-01 16:41 UTC, ConorMFinn requested changes
Just one tiny nitpick and a quick question

2021-11-01 16:41 UTC, ConorMFinn commented on dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
> +CMake conda variables
This is the worst kind of nitpick, and I apologise
```suggestion
CMake Conda Variables
```

2021-11-01 16:41 UTC, ConorMFinn commented on dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
> +The CONDA_BUILD parameter is used to customise our installation, which is required when we are using the conda-build tool to build and package Mantid.
It may be mentioned in this doc already, but is it worth mentioning here how these variables can be checked or changed, like in the old doc?

2021-11-02 11:19 UTC, ConorMFinn approved these changes
LGTM! Nice 👍🏻

2021-11-03 09:00 UTC, merged