Muon feature flag tests
mantidproject/mantid pull request #32779
Opened 2021-10-15 10:39 UTC by AnthonyLim23

**Description of work.**

We needed to add some tests  for the muon feature flags in PR #32572 
**To test:**

Check that the tests pass

Do some plots in the frequency domain GUI (look at #32572 for how to add the raw and model plots) and check it works.

Fixes #32632. 

This is not in the release notes as it does not change the user experience. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-10-18 10:52 UTC, sf1919 requested changes
Trying to follow the Superconducting copper test specified in #32572 but can't fit the final Gaussian. I can add the Gaussian to the Model Fitting Tab but when I click Fit I get the following error and no line is drawn.

![Screenshot (53)](https://user-images.githubusercontent.com/55837273/137717442-35575e0f-5e2d-4d76-ada2-081fbc46a005.png)
 
 Is this a bug introduced by this PR?

2021-10-19 16:07 UTC, AnthonyLim23 commented
That error is because the x range in the tab (0 to 15) does not match the data (50 to 120) and is captured in issue https://github.com/mantidproject/mantid/issues/32795

2021-10-20 07:30 UTC, sf1919 requested changes

2021-10-21 09:53 UTC, sf1919 approved these changes
I am happy with the changes that have been made. I have re-run the tests and they all work so am happy to approve these tests.

2021-10-26 09:55 UTC, merged