Fix bug in WANDPowderReduction that resulted in zeroed output
mantidproject/mantid pull request #32853
Opened 2021-10-25 18:21 UTC by rosswhitfield

**Description of work.**

There was an issues if you had identical x-values after `Transpose` going to `ResampleX` where the output is just `0`. This groups spectra with the same "x-values" before `Transpose`.

**To test:**

Previously running this code would results in empty output for the `2nd` workspace.

```
LoadWAND(IPTS=23858, RunNumbers=558129, ApplyMask=True, Grouping='2x2', OutputWorkspace='vana')
LoadWAND(IPTS=27692, RunNumbers=558130, ApplyMask=True, Grouping='2x2', OutputWorkspace='1st')
LoadWAND(IPTS=27692, RunNumbers=558131, ApplyMask=True, Grouping='2x2', OutputWorkspace='2nd')

reduced = WANDPowderReduction(InputWorkspace='1st, 2nd', CalibrationWorkspace='vana', NumberBins=1500 , Target='Theta')
```

Fixes [PD359](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/359)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-10-26 15:26 UTC, peterfpeterson submitted a review, later dismissed
Looks good to me. The new test appears to demonstrate the bug.

2021-10-27 14:03 UTC, DavidFair requested changes
LGTM, just one issue with leaking workspaces from the test in the ADS

2021-10-27 16:02 UTC, DavidFair approved these changes

2021-10-27 18:26 UTC, jmborr approved these changes
The workbench test works as expected.
I just have a minor question, so I mark this as approved

2021-10-28 10:38 UTC, merged