Update clang-format hook
mantidproject/mantid pull request #32923
Opened 2021-11-08 15:55 UTC by Pasarus

**Description of work.**
Changed the pre-commit hook for clang-format we are running, so it can handle python or python3 being called for the hook which provides support across all OSs

**To test:**
Run pre-commit on CentOS7/RHEL7 and on Windows both in a conda env and not

*There is no associated issue.*

*This does not require release notes* because **It is developer facing**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-11-08 17:24 UTC, ConorMFinn approved these changes, later dismissed
Runs properly on Windows, Ubuntu 18, and CentOS 7 (in a docker container)

2021-11-09 09:06 UTC, thomashampson requested changes
It works now, but only if I switch off python in `Settings > Manage app exclusion aliases` in the Windows settings. Can that be added to the dev docs?

2021-11-09 09:10 UTC, thomashampson approved these changes

2021-11-09 14:43 UTC, merged

2021-11-09 14:43 UTC, DavidFair commented
Failure unrelated