refs #32950 load now produces the history of the loader called
mantidproject/mantid pull request #33001
Opened 2021-11-17 14:24 UTC by AnthonyLim23

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-11-19 13:28 UTC, martyngigg requested changes
Code wise this seems like the right thing but I've tried it in workbench and I seem to get an extra property on the generated history that I think is an output property (`TimeZeroList`)? I don't think that was here before? I've included a screenshot:

![Screenshot 2021-11-19 at 13 23 10](https://user-images.githubusercontent.com/733773/142630061-d6a1a433-1adf-44c8-b105-704cd1872630.png)

2021-11-19 15:13 UTC, AnthonyLim23 commented on Framework/API/test/ScriptBuilderTest.h
> +  void test_Build_Load_Uses_Args_From_Correct_Load() {
yes, you are right.  I will just need to work out how to handle the file path changing between OS's

2021-11-19 15:14 UTC, AnthonyLim23 commented
> Code wise this seems like the right thing but I've tried it in workbench and I seem to get an extra property on the generated history that I think is an output property (`TimeZeroList`)? I don't think that was here before? I've included a screenshot:
> 
> ![Screenshot 2021-11-19 at 13 23 10](https://user-images.githubusercontent.com/733773/142630061-d6a1a433-1adf-44c8-b105-704cd1872630.png)

TimeZeroList should have present before. It is used for working out the time zero shifts (each detector could have a unique value).

2021-11-22 10:28 UTC, martyngigg commented
Thanks for updating the test.

Looking at the loader I can see `TimeZeroList` is an [output property](https://github.com/mantidproject/mantid/blob/442f0c7f0b5a046cfce5b3bd5525de4162323a7c/Framework/DataHandling/src/LoadMuonNexus.cpp#L95) so I don't think it should be in the generated script?

2021-11-22 12:01 UTC, AnthonyLim23 commented
I think we use it later on in the history. It should be replaced at some point by a table.

2021-11-22 17:06 UTC, martyngigg approved these changes
Ah I see this happens with `LoadMuonNexus` also. That means this essentially works as it did before so I'll approve it.

2021-11-23 14:15 UTC, merged