Fix ADS observer behaviour on Fitting tab in Engineering Diffraction UI
mantidproject/mantid pull request #33004
Opened 2021-11-17 17:35 UTC by DannyHindson

**Description of work.**

The fitting tab creates ~3 workspaces when you load a workspace:
a) the focussed workspace the user has loaded
b) a derived workspace that has background subtracted
c) a log group workspace

If the user renamed or deleted any of these the UI would often crash or log a nasty looking error message. The ADS observer behaviour has been reworked to sort this out. This relies on a new class called WorkspaceContainer that links together the a) and b) workspaces in the list above

As part of this I noticed that the serial and sequential fit weren't taking into account the Subtract BG checkbox which indicates whether a) or b) is active for each loaded workspace. So I've fixed this bug also.

**To test:**

Open up the Engineering Diffraction interface
Go to the Fitting Tab
Load the file in the attached zip file

Fixes #32837.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-11-23 15:37 UTC, DanielMurphy22 requested changes
My manual test of the interface went really well, renaming and deleting works as expected. My code review only produced a question and an annoying nitpick (sorry!)

2021-11-23 15:37 UTC, DanielMurphy22 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/calibration_info.py
> +            logger.error("Unable to loading calibration file " + filepath + ". Error: " + str(e))
```suggestion
            logger.error("Unable to load calibration file " + filepath + ". Error: " + str(e))
```
Sorry to nitpick

2021-11-23 15:37 UTC, DanielMurphy22 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
> -            obj_dic["background_params"] = data_widget.model.get_bg_params()
Why is it fine to remove this background_params entry, also on line 72 of this file?

2021-11-23 18:06 UTC, DannyHindson commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/calibration_info.py
> +            logger.error("Unable to loading calibration file " + filepath + ". Error: " + str(e))
No problem!

2021-11-24 11:24 UTC, DanielMurphy22 approved these changes
Works really well! Thanks for your answer!

2021-11-24 13:25 UTC, merged