Algorithm history uses load version for "Load"
mantidproject/mantid pull request #33078
Opened 2021-11-29 16:34 UTC by AnthonyLim23

**Description of work.**
After loading some data sets into Mantid and trying to generate a history (either by specifically asking for it or project recovery) an error message would appear in the log `Could not create a fresh version of Load version 1`. This was caused by the algorithm creation using the wrong version (it was the version of Load being called and not of the actual loader).
-->

**To test:**

Open Mantid
Load `SXD23767`
Get the history - no warnings should appear in the log
Paste the history into a script
Clear the ADS
Run the script (to check it works)

Fixes #33076 . 

This does not require release notes because its a bug that I added a couple of weeks ago.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-11-29 16:51 UTC, martyngigg requested changes

2021-11-29 16:51 UTC, martyngigg commented on Framework/API/src/ScriptBuilder.cpp
> +      int version = atoi(algHistory.getPropertyValue("LoaderVersion").c_str());
Can we use the [C++ version](https://en.cppreference.com/w/cpp/string/basic_string/stol) of this instead as it just accepts a `std::string`:
```
const int version = std::stoi(algHistory.getPropertyValue("LoaderVersion"))
```

2021-11-29 16:51 UTC, martyngigg commented on Framework/API/test/ScriptBuilderTest.h
> +  void test_Build_Load_Uses_Correct_version() {
Thanks for adding a test 👍🏻

2021-11-29 16:58 UTC, AnthonyLim23 commented on Framework/API/src/ScriptBuilder.cpp
> +      int version = std::stoi(algHistory.getPropertyValue("LoaderVersion").c_str());
```suggestion
      int version = std::stoi(algHistory.getPropertyValue("LoaderVersion"));
```

2021-11-30 11:35 UTC, martyngigg approved these changes
This looks good now. Confirmed that the error message no longer appears when creating the script from that has a loader where version 1 does not exist.

2021-11-30 15:08 UTC, merged