Preserve indent when commenting
mantidproject/mantid pull request #33077
Opened 2021-11-29 15:08 UTC by RichardWaiteSTFC

**Description of work.**

Preserve indent when commenting with `ctrl-/` to give mantid same behaviour as PyCharm.

To-Do
- Release notes

**To test:**
(1) Copy this into the script editor
```
for ii in range(2):
    print(ii)
print(10*ii)
```
(2) Comment lines with `ctrl-/` - it should produce this
```
# for ii in range(2):
    # print(ii)
# print(10*ii)
```
(3) Uncomment the lines and check the formatting is correct
(4) Play around with adding trailing whitespace etc.

Fixes #33069 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-11-29 17:44 UTC, thomashampson requested changes

2021-11-29 17:47 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_codecommenter.py
> +                          "# do_something_else()"]
Thanks, actually I'd not realised PyCharm behaved like that - but I will aim for that now!

2021-11-30 08:51 UTC, RichardWaiteSTFC commented on docs/source/release/v6.3.0/mantidworkbench.rst
> +- Commenting code int he editor using 'ctrl+/' will preserve indenting (i.e. `# ` will be inserted at the position of the first non-whitespace character in the line).
Thanks, fixed this!

2021-11-30 08:53 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_codecommenter.py
> +                          "# do_something_else()"]
I think actually (I didn't realise this) but PyCharm uses the least indented line to determine the indentation of the comment - e.g. commenting this
```
    lines[i] = lines[i][:istart] + '# ' + lines[i][istart:]
return lines
```
gives this
```
#     lines[i] = lines[i][:istart] + '# ' + lines[i][istart:]
# return lines
```
So I now loop over all lines to determine the position of the first non-whitespace char with the minimum indent in the selection

2021-11-30 11:24 UTC, thomashampson approved these changes
This is a nice improvement to the way code is commented out when using the shortcut key, and works well for all the things I've tested (seems to be consistent with PyCharm's behaviour).

2021-11-30 15:06 UTC, merged