Select between field and freq in FDA
mantidproject/mantid pull request #33119
Opened 2021-12-10 17:43 UTC by AnthonyLim23

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-12-14 12:02 UTC, Harrietbrown commented
one of your testing steps says 
>> Tick `reconstruct` in the table

does this mean `output reconstructed data`? I don;t see a `reconstruct` option

2021-12-14 12:58 UTC, AnthonyLim23 commented
> one of your testing steps says
> 
> > > Tick `reconstruct` in the table
> 
> does this mean `output reconstructed data`? I don;t see a `reconstruct` option

yes it does

2021-12-14 13:51 UTC, AnthonyLim23 commented on docs/source/release/v6.3.0/muon.rst
> +- Can now select the unit for the frequency spectra (MHz or Gauss), by picking either `Frequency` or `Field` respectfully.
```suggestion
- Can now select the unit for the frequency spectra (MHz or Gauss), by picking either `Frequency` or `Field` respectfully.

```

2021-12-14 15:05 UTC, Harrietbrown requested changes

2021-12-15 08:47 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/frequency_context.py
> +            return [0.0, 30.0]
if you do a maxent and an FFT it is then possible on the (sequential tab) to plot them both together. So I have opted to use the larger of the 2 ranges as the default value.

2021-12-15 08:56 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/test/Muon/CMakeLists.txt
> +    plot_fit_panes/plot_freq_fit_pane_presenter_test.py
```suggestion
    plot_widget/plot_freq_fit_pane_presenter_test.py
```

2021-12-15 16:01 UTC, Harrietbrown approved these changes
With all tests now passing this is ok to go ahead. Good job

2021-12-15 16:52 UTC, merged