added fit wizard to muon feature flags
mantidproject/mantid pull request #33115
Opened 2021-12-09 11:07 UTC by AnthonyLim23

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-12-14 16:01 UTC, robertapplin requested changes
Looks good, I haven't tested it yet but will hopefully do that tomorrow.

2021-12-15 08:50 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/features/add_fitting.py
> +# Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
```suggestion
# Copyright &copy; 2021 ISIS Rutherford Appleton Laboratory UKRI,
```

2021-12-15 08:51 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/features/add_fitting.py
> +FITWIZARD = "fit_wizard"
I have gone for fit wizard, as that feels like a more user friendly name. There is some intuition that a "wizard" makes the thing (in this case fits) easier.

2021-12-15 08:52 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_tab_widget/fitting_tab_widget.py
> +        self.fitting_tab_view.show_fit_script_generator()
```suggestion
        """
        Show the fit script generator in the fitting interface
        """
        self.fitting_tab_view.show_fit_script_generator()
```

2021-12-15 08:53 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py
> +        self.fit_controls.show_fit_script_generator()
```suggestion
        """
        Show the fit script generator in the fitting interface
        """
        self.fit_controls.show_fit_script_generator()
```

2021-12-15 08:53 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_controls_view.py
> +    def show_fit_script_generator(self):
```suggestion
    def show_fit_script_generator(self) -> None:
```

2021-12-15 14:50 UTC, robertapplin commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/features/add_fitting.py
> +FITWIZARD = "fit_wizard"
To me its hard to understand what a 'fit wizard' does, whereas with 'fit script generator' I find it is much clearer what its purpose is

2021-12-15 14:50 UTC, robertapplin commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_controls_view.py
> +        self.fit_generator_button.show()
Can you add a function comment here too

2021-12-15 17:14 UTC, robertapplin approved these changes
Ready to be shipped

2021-12-16 17:26 UTC, merged