Split Activation Fit function into two seperate functions
mantidproject/mantid pull request #33130
Opened 2021-12-15 10:15 UTC by sf1919

**Description of work.**
Split the Activation Fitting function for Muons into two separate functions, one for Kelvin and one for meV.

**To test:**

TBC

Fixes #33090. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-12-16 16:21 UTC, SilkeSchomann approved these changes, later dismissed
Code looks good and the ActivationK Fitting function works as expected.

2021-12-16 18:05 UTC, DavidFair requested changes
I'm happy with the code, but we need to be sure that this is not a breaking change in any way.

Does 6.2 have Activation as a function? Since `FitScriptGenerator` will have potentially created scripts with this in now

2021-12-17 07:53 UTC, sf1919 commented on Framework/CurveFitting/inc/MantidCurveFitting/Functions/ActivationK.h
> +class MANTID_CURVEFITTING_DLL ActivationK : public BackgroundFunction {
I'd be very surprised if it broke any exisiting scripts etc. Activation Fitting function was only added a few weeks ago (#32899) and as far as I'm aware only one user has tried to use it. These changes are as a result of their feedback (#33090).

2021-12-17 12:01 UTC, SilkeSchomann approved these changes
Approved again after recent changes.

2021-12-17 16:16 UTC, DavidFair approved these changes

2021-12-17 16:16 UTC, merged