Bug fix to get correct x values in SaveNexus when spec indices
mantidproject/mantid pull request #33153
Opened 2021-12-17 13:27 UTC by RichardWaiteSTFC

**Description of work.**
Thanks @DannyHindson for this fix - on-line fix that corrects the spectrum index from which the x-values of a spectrum are retrieved. This applies to SaveNExus-like algorithms that have ragged x binns and for which the user supplies specific spectrum indices to save. 

**To test:**
Follow instructions in original issue #33152 - check loaded spectra match up with the original workspace.

Fixes #33152 and #33129

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2021-12-20 16:59 UTC, robertapplin commented
Please could you send me the data used in the issue @RichardWaiteSTFC ?

2021-12-20 17:00 UTC, robertapplin commented
The code changes look good, I just need to do some functional testing and then I'll approve this

2021-12-21 08:45 UTC, RichardWaiteSTFC commented
@robertapplin - the data in the issue #33152 are just simulated, you only need to run the script to test (script even makes the plot).

2021-12-21 10:14 UTC, robertapplin commented
> @robertapplin - the data in the issue #33152 are just simulated, you only need to run the script to test (script even makes the plot).

Ah yes sorry, I didn't realise the script was saving the data before loading it back in again

2021-12-21 10:47 UTC, robertapplin approved these changes, later dismissed
The code changes look good, and the bug is fixed 👍

2021-12-21 17:39 UTC, martyngigg requested changes

2021-12-21 17:39 UTC, martyngigg commented on Framework/Nexus/src/NexusFileIO.cpp
> +      NXputslab(fileID, localworkspace->x(spec[i]).rawData().data(), start, asize);
Can I be slightly annoying and ask that we rename this `spec` variable? I was looking over the code and I got confused whether this contains spectrum numbers or workspace indices. I checked `SaveNexusProcessed` and it passes through [`indices`](https://github.com/mantidproject/mantid/blob/d529618f2eed7c53a7c1b90bd0afb349437c514e/Framework/DataHandling/src/SaveNexusProcessed.cpp#L305). I think renaming this variable would help the readability of the code a lot and we may as well do it while while we are changing it.

2021-12-22 11:18 UTC, martyngigg approved these changes
Thanks for making that change. I think it helps reading and understanding that code

2021-12-22 12:19 UTC, merged