Fix various ISIS SANS clipboard bugs
mantidproject/mantid pull request #33290
Opened 2022-01-12 15:06 UTC by DavidFair

**Description of work.**
- Fixes all the edge cases found in #33195 
- Port (copy and paste) the existing implementation into the table model and surround it in tests

See commits for more details

**To test:**
- Download the ISIS Sample Data
- Locate the `loqdemo` folder in the sample data
- Open the ISIS SANS interface
- Click batch file, load the CSV
- Click the row with name `first_row` and shift click select down to `second_row`, click copy
- Click off the rows (so none is selected), click paste and check the order copied correctly
- Do the same steps again, but this time selecting `second_row` first, then `first_row`
- Check the pasted order is goes first->second again
- Try breaking copy / cut paste various different ways 

Fixes #33286 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-01-13 17:01 UTC, RichardWaiteSTFC requested changes
Looks like another edge case is needed when pasting multiple rows to an empty row when only trailing empty rows exist below?
![image](https://user-images.githubusercontent.com/55979119/149375103-accf4f92-e8db-4ef4-afe3-f8125e50e09b.png)

2022-01-14 16:42 UTC, DavidFair commented
On discussion me and Richard agreed to push this to 6.4, as it borderlines a new feature
The current feature (whilst clunky) does not cause crashes / problems so we agreed to play it safe

2022-01-14 16:43 UTC, RichardWaiteSTFC submitted a review, later dismissed
This looks good, behaves like other spreadsheet software which I find quite intuitive. Test coverage looks good for many edge cases.

2022-01-17 08:29 UTC, martyngigg requested changes

2022-01-17 08:29 UTC, martyngigg commented on docs/source/release/v6.3.0/33286_sans.rst
> +Bugfixes
If we're targeting this at 6.4 can we move the release notes to the 6.4 section?

2022-02-01 14:14 UTC, RichardWaiteSTFC commented
@DavidFair - sorry forgot about this. Do I need to test it again, or did you just change the release notes in your force push?

2022-02-02 10:18 UTC, DavidFair commented
It was a rebase from release-next to main so I could shift the release notes into 6.4
This should be identical code-wise to before

2022-02-03 09:21 UTC, RichardWaiteSTFC commented
> @DavidFair - just thought I'd try this for peace of mind. Looks like it's functioning correctly but is very slow, it hangs for ~5s when pasting. Probably this is my computer and there's no reason your code is slowing it down, I was wondering whether you could check?

Ah the slow down appears to only occur when I have my default instrument set as WISH as opposed to LOQ. I seem to recall this produced an error, I no longer see this but the slow down is reproducible.

2022-02-03 10:06 UTC, DavidFair commented
> > @DavidFair - just thought I'd try this for peace of mind. Looks like it's functioning correctly but is very slow, it hangs for ~5s when pasting. Probably this is my computer and there's no reason your code is slowing it down, I was wondering whether you could check?
> 
> Ah the slow down appears to only occur when I have my default instrument set as WISH as opposed to LOQ. I seem to recall this produced an error, I no longer see this but the slow down is reproducible.

This is because the table opens the associated .nxs file to get the instrument name. Unfortunately it does the `n` times for `n` rows because of a long-standing bug (I can't find the issue # at the moment)

2022-02-03 10:08 UTC, RichardWaiteSTFC approved these changes
> > Ah the slow down appears to only occur when I have my default instrument set as WISH as opposed to LOQ. I seem to recall this produced an error, I no longer see this but the slow down is reproducible.
> 
> This is because the table opens the associated .nxs file to get the instrument name. Unfortunately it does the `n` times for `n` rows because of a long-standing bug (I can't find the issue # at the moment)

OK I'll approve!

2022-02-03 14:23 UTC, martyngigg approved these changes

2022-02-03 14:23 UTC, merged