Handle OSError exceptions when trying to remove recovery checkpoints
mantidproject/mantid pull request #33335
Opened 2022-01-17 17:53 UTC by martyngigg

**Description of work.**

We now trap errors that would have caused the error reporter to be raised. A user can do nothing about
the errors and recovery cleans up after itself in future runs so the risk is minimal. See the commit messages
for more details.

**To test:**

[project recovery manual tests](https://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html)

Fixes #32065 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-01-18 11:29 UTC, DanielMurphy22 requested changes
Just one small code comment I want to check. Manual testing of Project Recovery worked fine.

2022-01-18 12:58 UTC, martyngigg commented on qt/applications/workbench/workbench/projectrecovery/projectrecovery.py
> +    def _remove_directory_and_directory_trees(self, directory: str, *, ignore_errors: bool = False):
Yeah it's a nice feature that I especially like for flag-like options like this were just putting `True` is potential confusing.

2022-01-18 13:00 UTC, martyngigg commented on qt/applications/workbench/workbench/app/mainwindow.py
> +                self.project_recovery.remove_current_pid_folder()
Ah yes thank you! That's the whole error in the first place! 🤦🏻

2022-01-18 13:37 UTC, martyngigg commented on qt/applications/workbench/workbench/app/mainwindow.py
> +                self.project_recovery.remove_current_pid_folder()
That should be fixed now.

2022-01-18 14:17 UTC, martyngigg commented on qt/applications/workbench/workbench/app/mainwindow.py
> +                self.project_recovery.remove_current_pid_folder()
I fixed it and then my push failed. It should be good now.

2022-01-19 09:22 UTC, DanielMurphy22 approved these changes
Looks good to me! Hopefully this will prevent the problem users have been facing!

2022-01-20 11:22 UTC, DavidFair approved these changes
:crossed_fingers: hopefully this resolves this for good

2022-01-20 11:23 UTC, merged