Update accepted file types in Indirect Corrections documentaton
mantidproject/mantid pull request #33433
Opened 2022-02-02 15:34 UTC by Harrietbrown

**Description of work.**
This PR updates the Indirect corrections documentation list of allowed files or workspaces.

**Report to:** @SpencerHowells

**To test:**

Check documentation

Fixes #33429

*This does not require release notes* because It is a simple change to documentation

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-02-03 10:50 UTC, ConorMFinn requested changes
Nice, just a couple of tiny nitpicks

2022-02-03 10:50 UTC, ConorMFinn commented on docs/source/interfaces/indirect/Indirect Corrections.rst
> +  Either a reduced file (_red.nxs) or workspace (_red), an S(Q,\omega) file (_sqw.nxs) or workspace (_sqw) or an ELF file (_elf.nxs) or workspace (_elf) that represents the sample.
Are the `\omega` sections meant to be appearing as symbols?

May need to be:
```
    :math:`S(Q,\omega)`
```

2022-02-03 10:50 UTC, ConorMFinn commented on docs/source/interfaces/indirect/Indirect Corrections.rst
> +  Either a reduced file (_red.nxs) or workspace (_red), an S(Q,\omega) file (_sqw.nxs) or workspace (_sqw) or an ELF file (_elf.nxs) or workspace (_elf) that represents the container.
Super nitpicky, I know, but could we have another comma here to separate out the list?
```suggestion
  Either a reduced file (_red.nxs) or workspace (_red), an S(Q,\omega) file (_sqw.nxs) or workspace (_sqw), or an ELF file (_elf.nxs) or workspace (_elf) that represents the container.
```

2022-02-07 12:23 UTC, cailafinn approved these changes
Looks good to me now 👍

2022-02-08 13:50 UTC, DavidFair approved these changes

2022-02-08 13:50 UTC, merged