Update NOMAD geometry
mantidproject/mantid pull request #33469
Opened 2022-02-04 20:34 UTC by ckendrick

**Description of work.**

Updates the NOMAD geometry based on the new survey positions.

**To test:**

Verify the instrument geometry is correct.

Refer to Gitlab task [PD412](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/412)

Version into `ornl-next`: 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-02-04 21:35 UTC, peterfpeterson requested changes
The release notes should be in `diffraction.rst`

2022-02-04 21:35 UTC, peterfpeterson commented on docs/source/algorithms/CalculateDIFC-v1.rst
> +  DIFC of pixel 100 is 1274
Makes sense that this value has changed.

2022-02-07 18:11 UTC, peterfpeterson approved these changes

2022-02-08 13:50 UTC, DavidFair approved these changes

2022-02-08 13:50 UTC, merged