Show a tooltip on hovering over the instrument viewer
mantidproject/mantid pull request #33568
Opened 2022-02-16 13:49 UTC by MathieuTillet

**Description of work.**
At the request of some scientists at ILL, when hovering over the instrument in the instrument viewer, a tool tip showing basic information about the pixel appears. It is mostly useful and meant for rectangular detectors.

This tool tip only shows the detector name - which in rectangular detectors contains all relevant info about its position - and the integrated counts.

This feature is of course optional and can be activated via the settings menu.

**To test:**
- Load a file with a rectangular detector - for example `ExternalData/Testing/Data/UnitTest/ILL/D22B/046600.nxs`
- Open the instrument viewer.
- In the `Display settings` menu, check `Tooltip`
- Hover over the instrument and check the tool tip is there.

Closes #33567 .

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-02-28 09:42 UTC, ConorMFinn requested changes
Works well, code-wise just a tiny note on the release note. Also noticed that if the view type is switched, e.g. from full 3D to any of the others, the checkbox in Display Settings remains ticked but no tooltip appears.

2022-02-28 09:42 UTC, ConorMFinn commented on docs/source/release/v6.4.0/mantidworkbench.rst
> +- Nex option in the instrument viewer to see basic detector data in a tooltip when hovering.
```suggestion
- New option in the instrument viewer to see basic detector data in a tooltip when hovering.
```

2022-03-03 12:30 UTC, MathieuTillet commented
Thanks for catching that, I should work well now!

2022-03-04 12:06 UTC, ConorMFinn approved these changes
Looks good to me now, nice work 👍

2022-03-07 11:53 UTC, DavidFair approved these changes
LGTM and makes a big difference to the UX not having to move your eyes back and forth to see the same information

2022-03-07 11:53 UTC, merged