Support for SANSv2 autoprocess in DrILL
mantidproject/mantid pull request #33697
Opened 2022-03-24 15:48 UTC by gui-co

**Description of work.**

**To test:**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-03-28 15:12 UTC, darominski requested changes
This looks generally good. I have some comments and questions, and these are dispersed throughout the code. I am still to test the consistency due to issue with masks.

The lack of masks fortunately revealed an issue in the `validateInputs` of the `SANSILLMultiProcess`: in L392, the `RuntimeError` `re` should be assigned to `issues` dictionary as a string.

2022-03-29 07:26 UTC, gui-co commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/model/DrillExportModel.py
>          Args:
Done.

2022-03-29 07:26 UTC, gui-co commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/model/DrillExportModel.py
>          Args:
Done.

2022-03-29 08:59 UTC, gui-co commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/model/DrillTask.py
> +                self._onFinished(1, "")
When the return value of the algorithm is `false`, the observer already logged the error message.

2022-03-29 09:04 UTC, darominski approved these changes
Thank you for the changes, LGTM. The provided test works as advertised, and the output is exactly the same in both cases. However, there are some warnings with saving the output after DrILL processing, with `SaveCanSAS1D`, the units are not compatible with all outputs of the group to be saved, but that's perhaps beyond the scope of this PR.

2022-03-29 09:06 UTC, gui-co commented
Thanks, I will create a separate PR concerning the error handling in `SANSILLMultiProcess`.

2022-04-04 10:16 UTC, merged