Results table observer for muons
mantidproject/mantid pull request #33763
Opened 2022-04-13 09:09 UTC by AnthonyLim23

**Description of work.**

Users wanted to be able to change the values in a results table and for the values to automatically be updated in the GUI. 

**To test:**

Before opening Mantid turn on the model analysis and plotting (option 2) feature flag as described in https://github.com/mantidproject/mantid/pull/33712

Open mantid
Open muon analysis
Load MUSR 62260
Go to the fitting tab and add a function (doesnt matter which)
Go to sequential fitting tab and press fit all
Go to the results table tab
Select run number in the top table, then click the "output results" button 
Change the table name to "run" and press "output results"
Change the table name to "new" and press "output results"
Go to the model fitting tab
Notice that the plot is just bunch of markers in a vertical line
Open the "new" table from the ADS
Change one of the run numbers to 62249
Notice that the plot updates
Deleting "run" from the ADS will update the results table combo box so it will only contain "new" and "ResultsTable"

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-04-13 12:00 UTC, AnthonyLim23 commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/muon_context.py
> +        if isinstance(workspace, TableWorkspace):
```suggestion
        elif isinstance(workspace, TableWorkspace):
```

2022-04-14 15:44 UTC, AnthonyLim23 commented
@Harrietbrown could you please keep an eye on this while I am away?

2022-04-19 14:11 UTC, SilkeSchomann requested changes
It does work as expected but it looks as if a comment in the code needs to be cleaned up.

2022-04-19 15:13 UTC, Harrietbrown commented on qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/results_context.py
> +                                             self.replaced) # need to add unsubscribe to a close method in the widget
Anthony did mention a issue with subscribers not being removed, that was a seperate problem so this comment was likly intended as a TODO. I've removed the comment.

2022-04-26 07:01 UTC, SilkeSchomann approved these changes
Happy to approve this now after the changes.

2022-04-26 07:24 UTC, merged