Fix crash when group workspace is validated by ReflectometryBackgroundSubtraction
mantidproject/mantid pull request #33800
Opened 2022-04-28 13:25 UTC by ConorMFinn

**Description of work.**
When validating inputs the conversion of the index property to an index
set was causing unhandled exceptions that could crash mantid if run and
would interfere with the doc tests if not. This adds a catch for that
behaviour and also warns the user that they may not use a group
workspace for this algorithm (in the dialogue anyway, running from a script automatically converts group workspaces to re-run the algorithm for each member, so gets around the issue. This should probably be remedied at some point to have consistent behaviour, but is outside the scope of this PR and certainly not this close to release).

**To test:**

1. Put an empty group workspace in the ADS:
```
from mantid import api
groupws = api.WorkspaceGroup()
mtd['group'] = groupws
```
2. Open the ReflectometryBackgroundSubtraction dialogue 
3. It should open cleanly
4. Hit run with the group selected as the input workspace
5. The InputWorkspace property should be highlighted with an error

Fixes #33627 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-04-28 16:19 UTC, robertapplin requested changes
This works as described and the code looks good. Is it possible to add a test for this?

2022-04-28 16:19 UTC, robertapplin commented on Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp
> +  } catch (std::runtime_error &e) {
I think this can be const
```suggestion
  } catch (const std::runtime_error &e) {
```

2022-04-28 16:43 UTC, ConorMFinn commented
> Is it possible to add a test for this?

As it was to do with the algorithm dialog, I didn't think it was. But after some more thought it is possible to do some kind of testing for it at least

2022-04-29 07:36 UTC, robertapplin approved these changes
Thanks for adding a test, looks good to me

2022-04-29 12:33 UTC, merged