Tidy and Revise v6.4 Reflectometry Release Notes
mantidproject/mantid pull request #33985
Opened 2022-05-26 09:39 UTC by ConorMFinn

**Description of work.**
Rewording and reformatting of the release notes for reflectometry ready for the 6.4 release. 

**To test:**
1. Delete `docs/doctrees` from your build. 
1. Build the docs and check they look right & there are no warnings. 
2. Grammar, spelling, and formatting checked. 
3. Links etc. 

*There is no associated issue.*

*This does not require release notes* because **this would get very recursive if there were.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-05-31 10:24 UTC, sf1919 requested changes

2022-05-31 10:24 UTC, sf1919 commented on docs/source/release/v6.4.0/reflectometry.rst
> +- Removed the "primary fraction correction" from the :ref:`LRAutoReduction <algm-LRAutoReduction>` algorithm, as this correction is no longer in use.
```suggestion
- Removed the ``primary fraction correction`` from the :ref:`LRAutoReduction <algm-LRAutoReduction>` algorithm, as this correction is no longer in use.
```

2022-05-31 10:24 UTC, sf1919 commented on docs/source/release/v6.4.0/reflectometry.rst
> +- The Instrument Selector tooltips have been updated to clarify that any changes made using these combo-boxes will apply across all of mantid.
```suggestion
- The Instrument Selector tooltips have been updated to clarify that any changes made using these combo-boxes will apply across all of Mantid.
```

2022-05-31 10:24 UTC, sf1919 commented on docs/source/release/v6.4.0/reflectometry.rst
> +- **On the ISIS Reflectometry interface's** :ref:`Experiment Settings tab <refl_exp_instrument_settings>`, **you can now specify default experiment settings on a per-sample basis as well as a per-ang
```suggestion
- **On the ISIS Reflectometry interface's** :ref:`Experiment Settings tab <refl_exp_instrument_settings>`, **you can now specify default experiment settings on a per-sample basis as well as a per-angle basis. The new** ``Title`` **field in the lookup table allows you to specify a regular expression. Any runs with a title that match this expression will use those settings by default.**
```

2022-05-31 10:24 UTC, sf1919 commented on docs/source/release/v6.4.0/reflectometry.rst
> +- Workbench will no longer crash if :ref:`ReflectometryBackgroundSubtraction <algm-ReflectometryBackgroundSubtraction>` is run from the Algorithm Dialog with a group workspace as the input.
Not sure about this one but think Group Workspace should probably be capitalised. 

```suggestion
- Workbench will no longer crash if :ref:`ReflectometryBackgroundSubtraction <algm-ReflectometryBackgroundSubtraction>` is run from the Algorithm Dialog with a Group Workspace as the input.
```

2022-06-01 07:31 UTC, sf1919 approved these changes, later dismissed
I'm very happy with the changes. All the links work, it reads well. It's good to go.

2022-06-01 07:59 UTC, martyngigg commented
I think the base branch here should be `release-next`?

2022-06-01 10:02 UTC, martyngigg commented
No additional changes have appeared from the branch switch the original review is still valid. I'll approve and merge.

2022-06-01 10:03 UTC, martyngigg approved these changes

2022-06-01 10:03 UTC, merged