Add Sliceviewer link to Workbench Docs
mantidproject/mantid pull request #33994
Opened 2022-05-30 10:28 UTC by ConorMFinn

**Description of work.**
While looking for the sliceviewer docs I noticed that the only links to them appear to come from the release notes. This just adds a link to the list of workbench features, and also does some tidying to make the list look consistent. 

**To test:**
1. Delete doc-trees
2. Build the docs
3. Check links work and grammar is good. 

*There is no associated issue.*

*This does not require release notes* because **it only concerns documentation.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-06-01 13:57 UTC, martyngigg commented
Yep `release-next` is good 👍🏻

2022-06-06 08:56 UTC, sf1919 requested changes

2022-06-06 08:56 UTC, sf1919 commented on docs/source/workbench/index.rst
> +    * :ref:`Plotting <plotting>`: Describes how mantid workspaces have been integrated with the matplotlib framework and
```suggestion
    * :ref:`Plotting <plotting>`: Describes how Mantid workspaces have been integrated with the matplotlib framework and
```

2022-06-09 10:17 UTC, sf1919 approved these changes
Thanks for making the small change.

Looks good to go.

2022-06-09 10:18 UTC, merged