Fixing colorbar
mantidproject/mantid pull request #34214
Opened 2022-07-15 22:57 UTC by zjmorgan

**Description of work.**

Fixing an annoying bug that causes sliceviewer to throw an exception when using log-scale and there are empty slices with invalid data

**To test:**

Run this script.

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

signal = np.linspace(0,1,1000)
error = np.sqrt(signal)

signal -= 0.5

signal[signal>0.25] = np.nan

ws = CreateMDHistoWorkspace(Dimensionality=3,
                            Extents='-3,3,-10,10,-5,5',
                            SignalInput=signal,
                            ErrorInput=error,
                            NumberOfBins='10,10,10',
                            Names='Dim1,Dim2,Dim3',
                            Units='Uni1,Uni2,Uni3')
```

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-07-18 15:38 UTC, robertapplin commented
Thanks for fixing this. I've tried to select `Log` scaling but its disabled for me, did you mean `SymmetryLog10`?

2022-07-18 15:54 UTC, zjmorgan commented
> Thanks for fixing this. I've tried to select `Log` scaling but its disabled for me, did you mean `SymmetryLog10`?

I forgot to mention that you first have to slice to all positive values before switching to log scale. See this screenshot:
![image](https://user-images.githubusercontent.com/13754794/179551987-244f4de2-7469-4038-8de1-9e15b3d2bcca.png)

2022-07-19 11:51 UTC, robertapplin requested changes
Looks good, it fixes an exception seen in v6.4. Please could you add a release note to this location? https://github.com/mantidproject/mantid/tree/main/docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes

See the file in [this folder](https://github.com/mantidproject/mantid/tree/main/docs/source/release/v6.5.0/Indirect/Bugfixes) for an example (the filename is the PR number that fixes the issue)

2022-07-21 08:44 UTC, robertapplin approved these changes
Looks good to me 👍

2022-07-21 12:43 UTC, merged