Validate Sample and Corrections provided in ApplyAbsorptionCorrections
mantidproject/mantid pull request #34229
Opened 2022-07-22 15:21 UTC by sf1919

**Description of work.**
When testing the ApplyAbsorptionCorrections tab during smoke testing Mantid would close if both Sample and Corrections were not provided. Looking at the other tabs there is validation in place to prevent 'Run' from working and provides the user with an explanation if nothing has been uploaded. This PR provides validation for the Apply Absorption Corrections tab in line with the other Indirect Corrections tabs.

**To test:**
1. Go to `Indirection->Corrections` GUI
2. Select the `Apply Absorption Corrections` tab
3. Scroll down and press `Run`. You should get a pop up explaining no data was uploaded .

Fixes #34117

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-07-25 12:26 UTC, darominski requested changes
This PR fixes the linked issue, and Mantid does not undergo a hard crash when either the `Sample` or `Corrections` are not provided in the Apply Absorption Corrections tab of the Indirect Interface, so that's great.

Unfortunately, I run into a hard crash during testing with the data available in `Testing/Data/UnitTest`, e.g. `irs26176_graphite002_red.nxs`. When this file is used as a sample in the Calculate Paalman Pings tab to create an absorption workspace, and then both the sample and corrections are used as intended: everything executes properly, and if one of the inputs is missing, the fix from this PR works properly. The issue is if a name of one of the properties does not refer to an existing workspace, e.g. is misspelled (in the following example, the last character of the name is missing). Then a hard crash follows with the following message: `what(): Unable to find Data Object type with name 'iris26176_graphite002_FlatPlate_PP_Correction': data service  search object iris26176_graphite002_FlatPlate_PP_Correction`.

Could you include in this PR a fix to catch such an exception and display a proper error message to the user?

2022-07-26 09:57 UTC, sf1919 commented
@darominski I'm having difficulty recreating the issue you're having. My attempts have resulted in a pop up that explains it is unable to find the file. There is no hard crash. Could you walk me through what you did?

2022-07-26 13:57 UTC, darominski commented
Absolutely, these are all my steps:
1. In the workbench, I make sure that ISIS is the facility and IRIS is the instrument.
2. I open the Indirect/Corrections interface.
3. In the second tab, `Calculate Paalman Pings`, I choose the Sample property by browsing to an IRIS test file, e.g. `ExternalData/Testing/Data/UnitTest/irs26176_graphite002_red.nxs`. Then, I add modify the Sample Thickness, so it's not 0, let's say `0.1` cm, and set the Chemical Formula to `C`, and press `Run` button. A number of workspaces should be created, including the correction one called `irs26176_graphite002_FlatPlate_PP_Corrections_ass`.
4. I change the tab to the last one: `Apply Absorption Corrections`, change the selection from `File` to `Workspace`, and select the only suggested option for each of `Sample` and `Corrections` property. When I press the `Run` button, everything executes properly. 
5. However, if after selecting a proper workspace for either the `Sample` or `Corrections` I modify the text to one that does not point to a workspace that exists in the ADS, and then press Run, the execution stops with an uncaught exception reported previously.

I can consistently reproduce it this way on my Ubuntu 18.04. Let me know if it works differently on your side.

2022-07-27 08:05 UTC, darominski commented
Thank you for your last commit, it indeed fixed the reported issue.

Unfortunately, and apologies for being such a pain of a reviewer, I managed to crash it again in a slightly different way but I believe a related one:
1. Follow steps 1 to 3 from my previous comment, but this time save the corrections workspace with a name that the `FileFinder` for Corrections property in the `Apply Absorption Corrections` tab can recognize it (`*_Corrections.nxs` seems to be the way)
2. Pick the Sample property either from a file or already loaded workspace, and select Corrections property by browsing to the freshly saved file.
3. Try to Run. Mantid should abruptly close with no error message.

I believe this is coming from the `Corrections` file containing only the `ass` contribution. If the container parameters are defined  for the absorption correction calculation, and thus created workspace group (with 4 absorption contributions) is saved and subsequently loaded, everything executes as expected.

2022-07-27 08:23 UTC, sf1919 commented
@darominski I think perhaps this should be raised as a new issue rather than continuing to expand on this PR. Whilst it is another loading issue for Apply Absorption Corrections it isn't the original issue which was trying to run it without any files/workspaces loaded at all.

2022-07-27 08:43 UTC, darominski approved these changes
In that case, the original issue has been fixed, and the solution looks good to me.  A separate issue should  be created for the remaining crash. Thanks!

2022-07-27 15:28 UTC, merged