Improve ILL loaders documentation
mantidproject/mantid pull request #34227
Opened 2022-07-22 14:28 UTC by darominski

The ILL team has received a number of complaints from new users regarding the documentation of dedicated loaders. It was found lacking in terms pointing the user whether a specialised or a general loader should be used to load a number of files, and sometimes the documentation seemed incomplete or confusing.  This PR aims to fix the following issues:

- [ ] Add references to Load and `LoadAndMerge` algorithms to ILL's specialised loaders
- [ ] Clear out any inconsistencies and incomplete descriptions of specialised loaders' behaviour

ILL specialised loaders include: `LoadILLDiffraction`, `LoadILLSANS`, `LoadILLIndirect2`, `LoadILLReflectometry`, `LoadILLTOF2`, `LoadILLPolarizedDiffraction`.  

**To test:**
1. Documentation clarity and formatting

Fixes #34226. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-26 15:47 UTC, jhaigh0 requested changes
This is still listed as a draft but feels as if its in its final version.

Good changes which read well and the inclusion of links is nice. Just a couple very small formatting / typo changes.

2022-10-26 15:47 UTC, jhaigh0 commented on docs/source/algorithms/LoadILLReflectometry-v1.rst
> +If the **BraggAngle** property is not specified, then the sample angle metadata position (`SAN`)` is going to be used instead.
```suggestion
If the **BraggAngle** property is not specified, then the sample angle metadata position (`SAN`) is going to be used instead.
```

Tiny typo

2022-10-26 15:47 UTC, jhaigh0 commented on docs/source/algorithms/LoadILLIndirect-v2.rst
>  The `LoadDetectors` allows to choose which data to load for IN16B: those acquired by the spectrometer,
```suggestion
The **LoadDetectors** option allows to choose which data to load for IN16B: those acquired by the spectrometer,
```

To make refferencing this function parameter in-line with the change made to ``LoadILLTOF-v2``

2023-08-03 13:31 UTC, perenon commented
Hi @jhaigh0.

This PR is really old and is now totally outdated. Do you agree if I delete it and come back later with a fresh and updated new one ?

2023-08-03 14:38 UTC, closed without merging