Fix excessive text elision workbench data view
mantidproject/mantid pull request #34260
Opened 2022-08-04 09:03 UTC by martyngigg

**Description of work.**

This work addresses the issues with excessive text elision in the matrixworkspace data view after upgrading to Qt 5.12. See the screenshot in the linked issue for a comparison where the old version is on Qt 5.9.

It is not clear that this is a bug in Qt, just a change in behaviour. Here we introduce a delegate to control the amount of elision of the string that occurs.

**To test:**

* Open workbench
* Load any data file
* 

Fixes #34101

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-08-15 11:15 UTC, sf1919 requested changes
I have checked the functionality and it works well under all circumstances (including line shading). Happy with the majority of the code - just one or two minor changes requested.

2022-08-15 11:15 UTC, sf1919 commented on qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/delegate.py
> +# Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
```suggestion
# Copyright &copy; 2022 ISIS Rutherford Appleton Laboratory UKRI,
```

2022-08-15 11:15 UTC, sf1919 commented on qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_delegate.py
> +# Copyright &copy; 2019 ISIS Rutherford Appleton Laboratory UKRI,
```suggestion
# Copyright &copy; 2022 ISIS Rutherford Appleton Laboratory UKRI,
```

2022-08-16 07:41 UTC, martyngigg commented
Thanks for picking up those typos. They should be fixed now.

2022-08-16 09:16 UTC, sf1919 approved these changes

2022-08-18 08:31 UTC, merged