Skip Sum Banks Algo for Linear detector
mantidproject/mantid pull request #34271
Opened 2022-08-08 16:12 UTC by robertapplin

**Description of work.**

**To test:**

Fixes #34270

*This does not require release notes* because **the Refl Preview tab is still in development**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-08-08 16:13 UTC, robertapplin commented on qt/scientific_interfaces/ISISReflectometry/Reduction/Detector.cpp
> +  return detectorState != Mantid::Geometry::Instrument::ContainsState::Full;
Maybe add a comment to this function to explain why we are doing this

2022-08-25 15:39 UTC, gemmaguest requested changes
There seems to be a bug when you have a background ROI set and click the Apply button, then there is an additional `0-1` that appears in the lookup table along with the background ROI you specified

2022-08-25 15:49 UTC, gemmaguest reviewed
Code changes look good :+1:. Just one minor tidying suggestion but it's not essential. I'm not sure why the background ROI is now broken - it's ok on `main` though so seems to be caused by this PR

2022-08-25 15:49 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/Common/Detector.cpp
> +namespace MantidQt {
This could use short notation for namespaces i.e. `namespace MantidQt::CustomInterfaces::ISISReflectometry`

2022-08-25 15:49 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/Common/Detector.h
> +namespace MantidQt {
Again, short notation for namespaces

2022-08-25 15:50 UTC, gemmaguest commented
> > There seems to be a bug when you have a background ROI set and click the Apply button, then there is an additional `0-1` that appears in the lookup table along with the background ROI you specified
> 
> I think this bug is in main too. Its been recorded in issue #34220 (3rd from bottom)

Ah ok, ignore my last message then! In that case I think it's not worth doing the tidying fix and I'm happy to approve this

2022-08-25 15:56 UTC, gemmaguest approved these changes
Really good changes - this makes the functionality of the Preview tab much more useful because it can now be used for all of our existing reflectometry instruments, not just the prototype 2D detector. Nice encapsulation of the calls to `Instrument` and some useful tests added, because we might change the way this is implemented in a future PR. Great work :+1: :+1:

2022-08-26 07:19 UTC, merged