Prevent Mantid crash when fitting Gaussian peaks for a CrystalFieldFunction
mantidproject/mantid pull request #34283
Opened 2022-08-11 12:52 UTC by SilkeSchomann

**Description of work.**

Added check for height ties based on sigma for Gaussian peaks within a CrystalFieldFunction to void IFunction::sortTies(). In this case the tie is not sorted but still applied as usual for its respective peak function. The sortTies function does not differentiate between ties applied to individual peaks separately and ties that can potentially influence each other. This caused Mantid crashes for multisite CrystalField objects with Gaussian peaks as Gaussian peaks automatically have a tie based on sigma for its height.

**To test:**

Run the script from the original issue [34245](https://github.com/mantidproject/mantid/issues/34245) and check it works.

Fixes #34245 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-08-12 08:44 UTC, MialLewis approved these changes, later dismissed
Script that previously crashed mantid runs with a successful fit, code looks good.

I note that several `Numeric derivatives should be used when non-constant ties defined.` warnings are output during the fit (at least on `RelWithDebug` mode, probably a non-issue.

2022-08-16 10:39 UTC, martyngigg requested changes

2022-08-16 10:39 UTC, martyngigg commented on Framework/API/src/IFunction.cpp
> +    if (this->name() == "CrystalFieldFunction" && tie->ownerFunction()->name() == "Gaussian" &&
Could I ask if there would be a different way to solve this that doesn't required quite detailed knowledge of the function/tie specifics in the base class?

Maybe an `bool IFunction::ignoreTie(const Tie&)` that a function could override that by default returned `false`?

2022-08-17 15:09 UTC, martyngigg requested changes
Thanks for these changes. It's good that functions can now decide this for themselves.

Would it be possible to add a test for `IFunction::sortTies` to check those that are expected to be ignored are ignored?

2022-08-24 14:51 UTC, SilkeSchomann commented
> 

The result of sortTies is not accessible. I've added tests for ignoreTie instead and a Python test that would have caught the initial problem.

2022-08-31 09:41 UTC, martyngigg approved these changes

2022-08-31 09:41 UTC, merged