Update PythonNotebook documentation
mantidproject/mantid pull request #34406
Opened 2022-09-16 15:36 UTC by DanielMurphy22

**Description of work.**

So far just updated the documentation.

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-09-28 14:34 UTC, DanielMurphy22 commented
should consider how to preserve the custom memory allocation from jemalloc on Linux, currently part of mantidpython

2022-10-14 14:18 UTC, robertapplin requested changes
Nice clean changes! I have a few suggestions and questions about the removal of rpm/deb files

2022-10-18 09:53 UTC, martyngigg commented on buildconfig/CMake/Packaging/rpm/scripts/rpm_post_install.sh.in
> -#!/bin/sh
It is now yes as we no longer support RHEL 7

2022-10-18 09:53 UTC, martyngigg commented on Testing/SystemTests/scripts/mantidinstaller.py
> -class NSISInstaller(MantidInstaller):
Yep this is fine too as they are not being used.

2022-10-18 09:55 UTC, martyngigg commented on buildconfig/CMake/Packaging/AddPythonPath.py.in
>          if not directory.endswith(os.sep):
Is this file used anywhere? I notice it as a lot of Python 2.7 code in it too.

2022-10-18 14:25 UTC, robertapplin commented
All tests complete and code is looking much cleaner, so nice work! I just need to build the system tests on Windows and OSX using the build_packages_from_branch pipeline, once the release is out the door

2022-10-28 13:21 UTC, DanielMurphy22 commented
> I just need to build the system tests on Windows and OSX using the build_packages_from_branch pipeline, once the release is out the door

After build package from branch 100 and 101 failed due to a problem on main which is now fixed, I've merged with current main and re-run the build with package jobs as 113 and 114 https://builds.mantidproject.org/job/build_packages_from_branch/

2022-11-01 09:22 UTC, robertapplin approved these changes
Good work with this! The vast majority of references to mantidpython are now removed, and some unneeded scripts have also been removed.

The system tests are passing on windows, OSX and linux :+1:

2022-11-02 16:57 UTC, merged