Minor additions to IntegratePeakSkew
mantidproject/mantid pull request #34429
Opened 2022-09-21 16:03 UTC by RichardWaiteSTFC

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-17 11:42 UTC, DannyHindson commented
@RichardWaiteSTFC - is this ready for review now?

2022-10-17 12:01 UTC, RichardWaiteSTFC commented
> @RichardWaiteSTFC - is this ready for review now?

Thanks for checking, just got one more small change to go!

2022-10-19 09:13 UTC, DannyHindson requested changes
Looks good. Just a few minor things in the detail comments. Also:
- perhaps it's worth adding another couple of peaks to the SXD docs usage example so that the new TOF resolution plot has more than one point?
- there's a .gitkeep file in the file list. Please can you remove?
- as a general rule we should only add new algorithm parameters at the end of the list but since this algorithm is very new\in evaluation I think it's fine here to add them in the middle to keep the grouping sensible
- Just for completeness I'll note here that there's also a change to make Lorentz correction optional that's not in the PR description but that looks fine

2022-10-19 09:18 UTC, RichardWaiteSTFC commented on docs/source/algorithms/IntegratePeaksSkew-v1.rst
> +          (Right)
I could put it where I discuss the resolution (i.e. step 1) near the top?

2022-10-19 09:21 UTC, DannyHindson commented on docs/source/algorithms/IntegratePeaksSkew-v1.rst
> +          (Right)
Would that interrupt the flow of the step by step description a bit? Depends on how big it is and how it looks. Also fine just to leave it where it is and just mention the new plot in the text under the "Plotting" heading

2022-10-19 09:21 UTC, RichardWaiteSTFC commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
>                               doc="dTheta resolution (estimated from width at forward scattering minus "
Yes it's radians, I will clarify the docstring and in the plot

2022-10-19 09:22 UTC, DannyHindson commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
> +        self.declareProperty(name="ScaleThetaWidthByWavelength", defaultValue=False, direction=Direction.Input,
Yes sure. Just to check the algorithm still completes successfully with this set to True

2022-10-19 09:22 UTC, RichardWaiteSTFC commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
> +            estimated_dth = np.sqrt(slope)
Yes good catch they should indeed be inside the `if` on the next line!

2022-10-19 09:56 UTC, RichardWaiteSTFC commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
> +            ax[1].set_title(rf"$d\theta$={estimated_dth:.2E}" + "\n$dT_{bk}/T_{bk}$" + f"={estimated_dt0_over_t0:.2E}")
I was debating with myself whether to have the input `ThetaWidth` in degrees instead, that way the units on the plot can be consistent and the number might be a bit more meaningful to the user?

2022-10-19 17:14 UTC, DannyHindson approved these changes
Thanks for the changes. All looks good now

2022-10-20 07:28 UTC, merged