CCache on windows
mantidproject/mantid pull request #34494
Opened 2022-10-10 08:30 UTC by robertapplin

**Description of work.**
This PR ensures ccache is configured on windows when building with Ninja. It should hopefully mean far quicker build speeds when modifying certain files.

**To test:**
1. Update your environment to make sure ccache is installed. You can do `mamba env update -f mantid-developer-win.yml --prune`
1. Starting with an empty build folder, create a ninja build by `cmake --preset=win-ninja` from the source directory, and `ninja` from the build directory.
2. Change a commonly used header file like `Instrument.h`
3. Do ninja again in the build directory, and it should build fairly quickly
4. Check your `AppData/Roaming` directory for a `ccache` folder, to check that caching is being done

Part of #34490

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-13 10:19 UTC, DanielMurphy22 approved these changes, later dismissed
Very good! Makes a real difference to rebuild time!

2022-10-14 08:48 UTC, DanielMurphy22 commented on buildconfig/CMake/WindowsSetup.cmake
> +  endif()
```suggestion
  # for a single-config generator like Ninja, aim to use CCache and Debug on Clion. The Zi flag is not supported by 
  CCache so we need to use Z7 to allow debugging.
  if(CCACHE_FOUND)
    set(_language_flags "/Z7 /Ob0 /Od /RTC1")
  else()  # For multi-config generators like MSVC, Ccache is not used, so Zi flag can be used for debugging
    set(_language_flags "/Zi /Ob0 /Od /RTC1")
  endif()
```

Feel free to adjust!

2022-10-14 10:00 UTC, DanielMurphy22 approved these changes, later dismissed
Much happier!

2022-10-17 07:44 UTC, martyngigg requested changes
This looks great.

Just one minor thing with an `if` and I think it's good to go.

2022-10-17 07:44 UTC, martyngigg commented on buildconfig/CMake/WindowsSetup.cmake
> +  if(CCACHE_FOUND)
As we have the `USE_CCACHE` option too I think we need to check that?

```suggestion
  if(USE_CCACHE AND CCACHE_FOUND)
```

as if cmake was run first with `USE_CCACHE=ON` but then run again with ``USE_CCACHE=OFF` ccache was still found but the developer no longer wants it to be used.

2022-10-17 08:48 UTC, martyngigg approved these changes

2022-10-17 10:29 UTC, merged