Add CLion instructions for windows
mantidproject/mantid pull request #34500
Opened 2022-10-13 10:56 UTC by robertapplin

**Description of work.**
This PR adds a new developer documentation page for setting up CLion on Linux and Windows. It moves previously existing Linux documentation to this page, and expands on the instructions to help set it up on a Windows environment.

**To test:**
Build the dev docs target and make sure the links on the documentation work.

Read through the documentation and try set up CLion on windows to make sure it makes sense

Part of #34490 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-18 13:51 UTC, sf1919 commented on dev-docs/source/CLion.rst
> +- On Linux, set your Build type to be ``Debug``. On Windows, set your build type to be ``DebugWithRelRuntime``
Could we add a note that if the option isn't available you just type it in?

2022-10-18 13:58 UTC, robertapplin commented
Set the Debugger to be Bundled LLDB for windows

2022-10-19 14:06 UTC, sf1919 commented on dev-docs/source/CLion.rst
> +- Set the executable to be the ``python.exe`` in your conda installation, e.g. ``/path/to/mambaforge/envs/mantid-developer/bin/python.exe``
In windows the `python.exe` file is not in the bin folder but the level above that.

2022-10-19 15:01 UTC, robertapplin commented
Thanks @sf1919 . I have done some re-formatting to hopefully make it easier to read as well, so it might be worth build the `dev-docs-html` target again and having a look

2022-10-21 14:25 UTC, sf1919 requested changes
Just a couple of spelling errors. Otherwise the formatting looks really good in terms of indicating the different methods for Linux and Windows.

2022-10-21 14:25 UTC, sf1919 commented on dev-docs/source/CLion.rst
> +The first time you build from CLion, you will most likely need to launch it from a terminal or command line to make sure you have access to all the relevent tools.
```suggestion
The first time you build from CLion, you will most likely need to launch it from a terminal or command line to make sure you have access to all the relevant tools.
```

2022-10-21 14:25 UTC, sf1919 commented on dev-docs/source/CLion.rst
> +- To build a specific target, select it in the configurations drop-down menu and click the hammar icon next to it.
```suggestion
- To build a specific target, select it in the configurations drop-down menu and click the hammer icon next to it.
```

2022-10-24 08:29 UTC, sf1919 approved these changes
Thanks for making the final minor changes. It looks good and the instructions work.

2022-10-25 10:17 UTC, merged