Added button to hide plot in the plot toolbar
mantidproject/mantid pull request #34614
Opened 2022-10-24 16:20 UTC by jhaigh0

**Description of work.**

Added button to hide plot in the plot toolbar.

**To test:**

- Load data and open a plot
- Click the new hide plot button (eye icon) and check that the plot is hidden
- Go to the plots tab and checked the plot is showing as hidden (grey eye)
- Click the show plot button in the plots tab and check that the plot reappears

Fixes #34050

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-28 12:32 UTC, DanielMurphy22 requested changes
Well done, functionally testing this, the new toolbar button syncs up well with the plot selector widget (plots toolbox). 

I think it would be good to add a few tests to this. There could be a unit test in test_toolbar that checks simply that the hide state of the window does get set when the toolbar button is clicked ( This test should fail if I change newline 360 `self.window.hide()` to `pass`).

Then it would be quite nice if we can have a test to check that calling hide by clicking the toolbar button in the plot is reflected in the plotselector widget. This will probably mean creating a genuine PlotSelector widget object rather than mocking. Also this is arguably an integration test between the plotselector and the plotting.toolbar so should probably join other integration tests in the SystemTests.  

One final note beyond this PR, is we should change the PlotToolbar.png here: https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/06_formatting_plots.html#plot-toolbar This image is a screenshot from this powerpoint file in the documents repo: https://github.com/mantidproject/documents/blob/main/Images/Images_for_Docs/formatting_plots.pptx

2022-10-31 11:50 UTC, jhaigh0 commented
@DanielMurphy22 
I've added a test to test that when the button is pressed the window is hidden. As for integrating with the plot selector, the plot selector is update by it's model's `notify()` method which interacts with the global figure manager. A plot's viasability updating is already tested [here](https://github.com/mantidproject/mantid/blob/af039a025bbf9d3ce19207eac1ecc5f7b5ecb[…]/workbench/widgets/plotselector/test/test_plotselector_model.py](https://github.com/mantidproject/mantid/blob/af039a025bbf9d3ce19207eac1ecc5f7b5ecb461/qt/applications/workbench/workbench/widgets/plotselector/test/test_plotselector_model.py#L72)).

2022-10-31 14:47 UTC, DanielMurphy22 requested changes
Just a small thing. And thanks for looking into the integration test. I'm happy to accept that how both the toolbar and plots toolbox talk to the figuremanager is already tested.

2022-10-31 14:53 UTC, jhaigh0 commented on qt/applications/workbench/workbench/plotting/test/test_toolbar.py
> +        fig_manager.toolbar.hide_plot()
Thanks for spotting that one 👍

2022-11-01 10:02 UTC, DanielMurphy22 approved these changes
Good job! Really clean code change and the new button works seamlessly with the plots tab.

2022-11-01 15:55 UTC, merged