Add Logbook Export Functionality to the Search Runs Widget
mantidproject/mantid pull request #34622
Opened 2022-10-26 16:56 UTC by ConorMFinn

**Description of work.**
Adds a button to the Search Runs widget on the Refl gui that allows the user to export the content of the table out to a `.csv` file that can be loaded into a spreadsheet program.

Scientists were using this widget as a logbook rather than an external one, so having something they can save out and take away has been highly requested. 

**To test:**
*NOTE: The implementation of this makes use of the `QFileDialog`, which has [some interesting fights with Jetbrains IDE's](https://stackoverflow.com/questions/57646908/pyqt5-qfiledialog-is-not-returning-correct-paths-in-ubuntu) when launched from there and causing messed up paths. To see a representative example of the code working, launch workbench from a terminal. 

1. Load an experiment (ID: 1120015 Cycle: 11_3 is my usual testing go-to)
2. Type some details into the Comment and exclude columns
3. Hit enter after editing (this bit is important, and a limit of the QTableView, the changes don't get picked up otherwise)
4. Click the export button
5. Think up a name and a place for your logbook
6. Hit enter
7. Check the contents of the CSV is as expected and the correct file extension was applied to the file.  

Fixes #33468 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-10-27 15:40 UTC, gemmaguest requested changes
Nice code and some good tests added :+1: :+1:. Just a couple of minor suggestions plus a slight design adjustment to work around Qt not being MVP (it's a lengthy explanation, but should be a simple change!)

2022-10-27 15:41 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/GUI/Runs/IRunsView.h
> +  virtual std::string getLogbookCSV() const = 0;
Might be worth having a chat about this anyway in case we can simplify any of it!

2022-11-02 15:06 UTC, gemmaguest requested changes
Thanks for the changes - looks good :+1:. Could we also add some tests for the new functions in QtCatalogSearcher and RunsPresenter? I think the test suites should already be set up with the relevant mocks for the searcher and message handler, so hopefully these are straightforward to add?

2022-11-02 15:06 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsPresenter.h
> +#include <fstream>
Could this be in the .cpp file?

2022-11-02 15:06 UTC, gemmaguest commented on qt/scientific_interfaces/ISISReflectometry/test/Runs/MockRunsView.h
> +  MOCK_CONST_METHOD0(getSearchResultsCSV, std::string());
I think this can be removed now?

2022-11-03 09:25 UTC, ConorMFinn commented
> Thanks for the changes - looks good 👍. Could we also add some tests for the new functions in QtCatalogSearcher and RunsPresenter? I think the test suites should already be set up with the relevant mocks for the searcher and message handler, so hopefully these are straightforward to add?

I wasn't actually done working on the changes yet, just pushing so I didn't lose anything if my machine died

2022-11-03 15:28 UTC, gemmaguest requested changes
Code changes look good and some nice tests added :+1:

Just one thing I've noticed during functional testing - if I cancel the file browser dialog, it saves the results anyway to a `.csv` file in the directory I ran mantid from.

2022-11-03 16:14 UTC, gemmaguest approved these changes
Thanks for the final fix. This all looks good now :+1:. Happy to merge when tests pass :shipit:

2022-11-03 16:35 UTC, ConorMFinn commented
#33415

2022-11-08 09:40 UTC, gemmaguest commented
@mantidproject/gatekeepers Could we get this merged? I'd like to get it into nightly for a user to test

2022-11-08 09:48 UTC, merged