Use Conda for pre-commit checks
mantidproject/mantid pull request #34742
Opened 2022-11-16 16:11 UTC by martyngigg

**Description of work.**

The `pre-commit` job recently starting hitting this error:

```sh
An unexpected error has occurred: CalledProcessError: command: ('/home/abc/.cache/pre-commit/repoyrc1wg3z/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/abc/.cache/pre-commit/repoyrc1wg3z
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/abc/.cache/pre-commit/repoyrc1wg3z/py_env-python3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/abc/.cache/pre-commit/repoyrc1wg3z/setup.py'"'"'; __file__='"'"'/home/abc/.cache/pre-commit/repoyrc1wg3z/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u6t1x1pm
           cwd: /home/abc/.cache/pre-commit/repoyrc1wg3z/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/abc/.cache/pre-commit/repoyrc1wg3z/setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
    WARNING: Discarding file:///home/abc/.cache/pre-commit/repoyrc1wg3z. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It now requires a minimum of Python 3.7 so we will need to use Conda to run the check. This adds a script to do that.

**To test:**

* Checking [testing job passed](https://builds.mantidproject.org/job/testing-pre-commit-script/15/)

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2022-11-22 08:53 UTC, sf1919 approved these changes, later dismissed
Test instance passed no problems and pretty quickly.

Reviewing the code it's great to have the comments in to explain the changes.

Happy to approve.

2022-11-22 17:22 UTC, thomashampson requested changes

2022-11-22 17:22 UTC, thomashampson commented on buildconfig/Jenkins/Conda/publish-to-github
> +mamba install gh
```suggestion
mamba install gh -y
```

2022-11-22 17:22 UTC, thomashampson commented on buildconfig/Jenkins/Conda/download-and-install-mambaforge
>  #   3. CLEAN_BUILD: whether or not to force mambaforge to be removed before attempting to install it again
```suggestion
#   2. CLEAN_BUILD: whether or not to force mambaforge to be removed before attempting to install it again
```

2022-11-24 15:08 UTC, thomashampson approved these changes

2022-11-24 15:12 UTC, merged