Dns powder tof maintenance
mantidproject/mantid pull request #34834
Opened 2022-12-07 15:50 UTC by koshchii

**Description of work.**

This PR improves functionality of the Powder TOF mode of the DNS Reduction GUI. In particular: 

- The drop-down combo box in the upper left corner of the "Data" tab is replaced by two separate "Sample Data" and "Standard Data" buttons
- As soon as the path for standard data is specified by the user in the "Standard Files Directory" field of the "Paths" tab, the standard data are loaded and selected for reduction by default
- The obsolete "Read All" button is removed from the interface
- Documentation is re-structured and updated

**To test:**

- Download test data: [TOF_Powder_Vanadium.zip](https://github.com/mantidproject/mantid/files/8629427/TOF_Powder_Vanadium.zip)
- Open the reduction GUI [Interfaces->Direct->DNS Reduction]
- Browse to the directory where the test data are located using the "Paths" tab of the GUI
- Switch to the "Data" tab. The expected default behavior is: 
  - Sample test data are loaded and available for selection in "Sample Data" view.
  - Standard test data are loaded and selected for reduction in "Standard Data" view. Switch to the "Standard Data" to make sure that the default setting works.  
- Open the "Options" tab to select options for data reduction 
- Reduce the data and generate a data reduction script using the "Script Generator" tab
- Visualize results using the "Plotting" tab
- Make sure that the updated documentation is consistent with the implemented modifications

Fixes #34828. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-02-27 17:06 UTC, DannyHindson requested changes
I've tested this and built the docs and just a few minor points, generally works well:

1) The "Sample Data" button is not clickable in some parts of its surface for me (I'm running on Windows in case it's relevant). It's only clickable close the lower and right hand edge. Some of the button appears to be hidden by the invisible DNSFileSelectorWatcher widget (because if I don't create this the button is fine and will accept clicks anywhere). You can fix this by adding a call to `self.watcher.lower()` in file_selector_widget.py

2) The help menu inside the user interface didn't work for me. Perhaps the path in the `_help_button_clicked` function in main_view.py needs updating?

3) If I go straight to the Data tab without doing anything on the Path tab I see both sets of filter options on the right hand side (Filter by Scan and Filter By Standard Data Type). Should this just show one or the other? Not a big problem because once you load some data on the Path tab you the Data tab initially shows the Sample Data and only the Filter By Scan filters.

One other minor point that pre-dates this PR - the Data Directory edit box on the Paths tab shows a red asterisk even after a valid directory has been entered. Should this be hidden once you've entered a valid path? Not important to address this in this PR

2023-03-07 16:56 UTC, koshchii commented
> I've tested this and built the docs and just a few minor points, generally works well:
> 
>     1. The "Sample Data" button is not clickable in some parts of its surface for me (I'm running on Windows in case it's relevant). It's only clickable close the lower and right hand edge. Some of the button appears to be hidden by the invisible DNSFileSelectorWatcher widget (because if I don't create the watcher widget, the button is fine and will accept clicks anywhere). You can fix this by adding a call to `self.watcher.lower()` in file_selector_widget.py
> 
>     2. The help menu inside the user interface didn't work for me. Perhaps the path in the `_help_button_clicked` function in main_view.py needs updating?
> 
>     3. If I go straight to the Data tab without doing anything on the Paths tab I see both sets of filter options on the right hand side (Filter by Scan and Filter By Standard Data Type). Should this just show one or the other? Not a big problem because once you load some data on the Path tab you the Data tab initially shows the Sample Data and only the Filter By Scan filters.
> 
> 
> One other minor point that pre-dates this PR - the Data Directory edit box on the Paths tab shows a red asterisk even after a valid directory has been entered. Should this be hidden once you've entered a valid path? Not important to address this in this PR

Thank you very much for the review and nice suggestions! The new commits address the points you mentioned

2023-03-08 09:07 UTC, DannyHindson requested changes
Thanks for the changes. It all looks good now. Please can you add a release note .rst file in `docs\source\release\v6.7.0\Direct_Geometry` directory containing a ~1 line description of the changes?

2023-03-08 13:47 UTC, DannyHindson approved these changes

2023-03-21 14:04 UTC, merged