Update ALFView interface documentation
mantidproject/mantid pull request #34902
Opened 2023-01-05 16:40 UTC by robertapplin

**Description of work.**
This PR updates the interface documentation for ALFView, and adds release notes for recent feature changes made to the GUI.

**To test:**
Build `docs-html`
Open the ALFView documentation page and read it. Make sure it makes sense/all links work/all images are displayed
Read the release notes

Fixes #34824

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-01-12 17:05 UTC, DanielMurphy22 commented on docs/source/interfaces/direct/ALFView.rst
> +.. image::  ../../images/ALFView_Interface.png
```suggestion
.. image::  ../../images/ALFView_Interface.PNG
```

2023-01-12 17:06 UTC, DanielMurphy22 requested changes
This PR should be merged tomorrow before code freeze! I wanted to approve, especially as the testing docs can be improved after testing, but the image in the main docs page should have capitals .PNG 

I'm off tomorrow so please get someone else to approve and merge!

2023-01-12 17:08 UTC, DanielMurphy22 approved these changes, later dismissed
Quick change!

2023-01-13 08:58 UTC, martyngigg approved these changes

2023-01-13 13:22 UTC, martyngigg commented
Unrelated test failures on documentation updates.

2023-01-13 13:23 UTC, merged