TimeROI object in python
mantidproject/mantid pull request #34901
Opened 2023-01-04 21:54 UTC by peterfpeterson

This exposes the new `mantid.kernel.TimeROI` object to python which will be used for implementing the new design for filtering events and logs #34794. 

**NOTE** do not merge before #34894 because it contains all of those changes as well.

**To test:**

```sh
ninja all
python -m pydoc mantid.kernel.TimeROI
```
see that there are docs for the exposed methods.

*There is no associated issue.*

*This does not require release notes* because it is not connected to anything user facing yet. Future PRs will add release notes.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-01-10 16:38 UTC, jmborr submitted a review, later dismissed
I think this baby's good to go :baby:

2023-01-10 19:48 UTC, AndreiSavici requested changes, later dismissed
There is no python unit test for the TimeROI object

2023-01-10 20:58 UTC, peterfpeterson commented
The `TimeROI` can't be created in python. The test suggested in the PR details is the only way until more functionality exists.

2023-01-11 18:53 UTC, AndreiSavici approved these changes

2023-01-11 18:54 UTC, merged