Update the dev docs for obtaining a fit benchmark
mantidproject/mantid pull request #34910
Opened 2023-01-09 11:29 UTC by robertapplin

**Description of work.**
This PR updates the documentation on how to obtain a benchmark of fit minimizers in Mantid using the FitBenchmarking package.

**To test:**
Read through and test that the instructions work

*There is no associated issue.*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-01-27 12:04 UTC, jhaigh0 commented
Would be good to have a little more detail around this
```
PYTHONPATH=/path/to/build/bin/<config> fitbenchmarking -o fitting_options.ini -p examples/benchmark_problems/Muon
```
i.e that the path is to your Mantid build, maybe just give an example path. I also feel it could be moved down to the 'Running a benchmark' section, since the instruction already says to follow the instructions in that section.

Only other thing is "Download the examples folder from..." lead me to think there would be a download link to the folder somewhere and not that I'd have to clone the repo. So some rewording there might be good.

2023-02-08 14:07 UTC, jhaigh0 reviewed
Seems good now, easy to read. :+1:

The only question I have is if the docs should make reference to 'MantidWorkbench' rather than just 'Mantid'?

2023-02-08 14:44 UTC, robertapplin commented
> The only question I have is if the docs should make reference to 'MantidWorkbench' rather than just 'Mantid'?

Thats a good question. I think 'Mantid' makes more sense because a lot of our CurveFitting and Algorithms are in the Mantid Framework. And I think this is separate to 'MantidWorkbench' which refers more to the GUI, which uses the Framework. Mantid fitting can be used separately from the GUI in a python script.

2023-02-08 14:47 UTC, jhaigh0 requested changes

2023-02-08 14:47 UTC, jhaigh0 commented on dev-docs/source/ObtainingABenchmarkForMantidFitting.rst
> +1. Download and install the desired version of Mantid from the `releases page <https://github.com/mantidproject/mantid/releases>`_. Note its installation path, hereby denoted as ``[INSTALL_PATH]``.
```suggestion
1. Download and install the desired version of MantidWorkbench from the `releases page <https://github.com/mantidproject/mantid/releases>`_. Note its installation path, hereby denoted as ``[INSTALL_PATH]``.
```
Maybe just this to change then?

2023-02-08 14:56 UTC, jhaigh0 approved these changes

2023-02-08 19:15 UTC, merged