Fix Rendering Error
mantidproject/mantid pull request #35013
Opened 2023-01-18 16:57 UTC by ConorMFinn

**Description of work.**
Pinned qt on conda to a slightly earlier patch to avoid the rendering issues seen in the instrument viewer, alf, and refl guis. 

**To test:**
1. Update your conda environment from the supplied mantid dev `.yaml`
2. Launch workbench
3. Open the refl GUI & instrument viewer and flick through the tabs. 
4. Check that the rendering is working as it should. 

Fixes #34964 

*This does not require release notes* because **it concerns our conda management.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-01-19 09:37 UTC, martyngigg commented
@ConorMFinn Thanks for this. Could you change the `base` branch to `release-next`?

2023-01-19 09:38 UTC, martyngigg requested changes

2023-01-19 09:38 UTC, martyngigg commented on conda/recipes/conda_build_config.yaml
> +  - 5.15.4
As we pinned to a patch level could we add a comment here too?

2023-01-19 12:28 UTC, martyngigg approved these changes
This looks great to me. Installing the test package uploaded to Anaconda results in qt-main 5.15.4 and not .6 being installed.

I noticed an issue if you just try an in-place upgrade an existing package and it *won't* downgrade Qt but we primarily need to fix the case of installing from scratch and this fixes that.

2023-01-19 15:02 UTC, martyngigg commented
@mantidproject/gatekeepers Please can we merge this for this evening. The test failure on Windows is not related to these changes.

2023-01-19 16:10 UTC, merged

2023-01-20 14:49 UTC, DanielMurphy22 commented
Just as a note, pinning back to this minor version also helps to fix 2 other bugs: https://github.com/mantidproject/mantid/issues/35046 https://github.com/mantidproject/mantid/issues/35029