Fix HKL cursor info for 4D MD workspaces
mantidproject/mantid pull request #35044
Opened 2023-01-20 13:36 UTC by robertapplin

**Description of work.**
This PR fixes a bug in the SliceViewer when viewing 4D data. The HKL values are now correctly printed in the cursor info widget even when another dimension exists. The dimensions can now be in any order and it should still work e.g. any of EHKL, HEKL, HKEL, HKLE.

**To test:**
Follow the instructions in the attached issue.
You can also try swapping the order of the dimensions and check it is still working.

Fixes #34986

*This does not require release notes* because **the bug was not present in the previous release**

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-01-24 09:08 UTC, RichardWaiteSTFC commented
@MialLewis can you test it for the following workspace `ws_slice` which has axes that are a mix of h,k,l
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-3,3,-3,3,-3,3',
                   Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                   Frames='HKL,HKL,HKL',
                   SplitInto='2', SplitThreshold='10')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
BinMD(InputWorkspace=ws, AxisAligned=False,
    BasisVector0='[00L],r.l.u.,0,0,1',
    BasisVector1='[HH0],r.l.u.,1,1,0',
    BasisVector2='[-HH0],r.l.u.,-1,1,0',
    OutputExtents='-4,4,-4,4,-0.25,0.25',
    OutputBins='101,101,1', OutputWorkspace='ws_slice', NormalizeBasisVectors=False)
```
And perhaps similar 4D workspaces with non-Q dimensions included? Cheers!
Alternatively I'm happy to test this PR - whatever you prefer!

2023-01-24 09:10 UTC, MialLewis commented
> @MialLewis can you test it for the following workspace `ws_slice` which has axes that are a mix of h,k,l
> 
> ```
> ws = CreateMDWorkspace(Dimensions='3', Extents='-3,3,-3,3,-3,3',
>                    Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
>                    Frames='HKL,HKL,HKL',
>                    SplitInto='2', SplitThreshold='10')
> expt_info = CreateSampleWorkspace()
> ws.addExperimentInfo(expt_info)
> SetUB(ws, 1,1,2,90,90,120)
> BinMD(InputWorkspace=ws, AxisAligned=False,
>     BasisVector0='[00L],r.l.u.,0,0,1',
>     BasisVector1='[HH0],r.l.u.,1,1,0',
>     BasisVector2='[-HH0],r.l.u.,-1,1,0',
>     OutputExtents='-4,4,-4,4,-0.25,0.25',
>     OutputBins='101,101,1', OutputWorkspace='ws_slice', NormalizeBasisVectors=False)
> ```
> 
> And perhaps similar 4D workspaces with non-Q dimensions included? Cheers! Alternatively I'm happy to test this PR - whatever you prefer!

yep, I'm happy to do it, I've pretty much finished testing and about to approve

2023-01-24 09:56 UTC, gemmaguest commented
@robertapplin Should this be going into `release-next` instead of `main`?

2023-01-24 09:57 UTC, robertapplin commented
> @robertapplin Should this be going into `release-next` instead of `main`?

Yes, thank you!

2023-01-24 10:37 UTC, MialLewis commented
As discussed, if you run the following script, `H` should be equal to `K`. `L` also appears to be tracking the third slice point.

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws_4D = CreateMDWorkspace(Dimensions=4, Extents=[-1, 1, -1, 1, -1, 1, -1, 1], Names="E,H,K,L",
                              Frames='General Frame,HKL,HKL,HKL', Units='meV,r.l.u.,r.l.u.,r.l.u.')
expt_info_4D = CreateSampleWorkspace()
ws_4D.addExperimentInfo(expt_info_4D)
SetUB(ws_4D, 1, 1, 2, 90, 90, 120)
BinMD(InputWorkspace=ws_4D, AxisAligned=False,
    BasisVector0='[00L],r.l.u.,0,0,0,1',
    BasisVector1='[HH0],r.l.u.,0,1,1,0',
    BasisVector2='[-HH0],r.l.u.,0,-1,1,0',
    BasisVector3='[E],r.l.u.,1,0,0,0',
    OutputExtents='-1,1,-4,4,-4,4,-0.25,0.25',
    OutputBins='100,100,100,100', OutputWorkspace='ws_slice', NormalizeBasisVectors=False)
```

2023-01-25 15:31 UTC, RichardWaiteSTFC requested changes
I think this is very close and actually works as expected for the workspaces tested because now you get the full point (HKL and any non_Q dimension positions) from a combination of the slicepoints and `xdim` & `ydim` however I think there is still a bug here.
In the screenshot (using the workspace @MialLewis posted) - the `zdim` passed to the `argsort` seems to be for a non-Q axis (it should be 2). Possibly because of a problem in `get_dim_indices` which @DannyHindson may have also talked to you about?
![image](https://user-images.githubusercontent.com/55979119/214605284-6c15a291-f823-477c-8b12-21332fb4ca89.png)

2023-01-25 15:31 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +        zdim = next(i for i, v in enumerate(slice_point) if v is not None and i in qdims)
Not sure this is working as expected - this assumes there is only one Q-dim with a slicepoint (see screenshot). 
`xdim` and `ydim` may be non-Q dimensions as well - but I think that's handled OK...

2023-01-25 15:31 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +        hkl_point = tuple(full_point[q_i] for q_i in qdims)
I think this is not the HKL but actually the point in the sliceviewer projection coordinates (see screenshot)

2023-01-25 15:31 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +        h_i, k_i, l_i = np.argsort([xdim, ydim, zdim])
Again, `h_i` etc. correspond to the index of the `proj_matrix` column correpsonding to the index of the elements in `hkl_point` - perhaps `icol_x` etc. would be better names?

2023-01-25 15:38 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +        qdims = np.array([ws.getDimension(i).getMDFrame().isQ() for i in range(ndims)])
Minor point, but as the `qdims` is something constant about the workspace we should probably store this as an attribute as we use it again when determining the HKL and maybe have some private methods to e.g. `get_index_nonQ_dims` etc. - what do you think?

2023-01-25 16:00 UTC, RichardWaiteSTFC commented
Ah I think I see the problem - we no longer need the argsort (added to solve out-of range error) - the order of the elements in `hkl_point` (as discussed not actually HKL) are in the order of the workspace basis vectors (and columns in `proj_matrix`).

2023-01-26 14:26 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dimensionwidget.py
> +        return dims_i[self.qflags]
minor but could this be simplified to 
`return np.where(self.qflags)[0]`

2023-01-27 09:30 UTC, robertapplin commented
@RichardWaiteSTFC I have created a separate issue to deal with the second bug https://github.com/mantidproject/mantid/issues/35095 . Hopefully dealing with them separately will make things a bit easier

2023-01-27 11:34 UTC, RichardWaiteSTFC requested changes
Looks good, thanks for splitting up the issue - this is a good fix to get in for the release and a good addition to the tests. If you could perhaps just rename one variable then I'll approve (sorry very nit-picking of me)!

2023-01-27 11:34 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +        hkl_projection = tuple(full_point[q_i] for q_i in qdims_i)
Really minor but I think `hkl_projection` is not a good name, perhaps  `q_xyz`? Recall this is the Q vector in the frame of the sliceviewer axes.

2023-01-27 11:34 UTC, RichardWaiteSTFC commented on qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
> +    def get_hkl_from_full_point(self, full_point: List[float], qdims_i: List[int]):
As discussed offline, the `qdims_i` are actually a property that can be determined from the workspace and so I think ultimately belongs in the model (not retrieved from the data view dimension widget and passed via the presenter) - but I'm happy for that to be addressed in #35095

2023-01-27 12:10 UTC, RichardWaiteSTFC approved these changes
Great job!

2023-01-27 17:05 UTC, merged