Update WSL developer documentation to refer to X Server use
mantidproject/mantid pull request #35111
Opened 2023-01-30 12:04 UTC by MialLewis

**Description of work.**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-02-02 13:43 UTC, robertapplin requested changes
Looks good, just had a few minor comments and a question

2023-02-02 13:43 UTC, robertapplin commented on dev-docs/source/WindowsSubsystemForLinux.rst
> +WSL does not currently support GUIs. In order to display a GUI from an application running in WSL you will therefore need to use an XServer. Failure to do so will result in a crash upon launching `wo
```suggestion
WSL does not currently support GUIs. In order to display a GUI from an application running in WSL you will need to use an XServer. Failure to do so will result in a crash upon launching `workbench`.
```

2023-02-02 13:43 UTC, robertapplin commented on dev-docs/source/WindowsSubsystemForLinux.rst
> +1. Download a compatible XServer onto the host Windows machine. `MobaXterm <https://mobaxterm.mobatek.net/>`_ is recommended and has been confirmed to work with Mantid workbench.
```suggestion
1. Download a compatible XServer onto the host Windows machine. `MobaXterm <https://mobaxterm.mobatek.net/>`_ is recommended and has been confirmed to work with Mantid Workbench.
```

2023-02-02 13:43 UTC, robertapplin commented on dev-docs/source/WindowsSubsystemForLinux.rst
> +  4. Echo the `DISPLAY` variable, you should see the value `<host machine IP Address>:0.0`.
Would it be useful to say that they can check the IP address here matches the `IPv4 address` displayed when you run `ipconfig` in your terminal? Just as an extra check

2023-02-02 17:54 UTC, MialLewis commented
> Looks good, just had a few minor comments and a question

Thanks for the feedback, I've actioned all of the comments.

2023-02-03 08:52 UTC, robertapplin approved these changes
Thanks for the changes, looks good! The test failures are unrelated

2023-02-03 13:49 UTC, martyngigg commented
Unrelated status check failure.

2023-02-03 13:50 UTC, merged