Only publish from a single Jenkins pipeline by default
mantidproject/mantid pull request #35121
Opened 2023-01-31 17:21 UTC by thomashampson

**Description of work.**
Allow multiple nightly pipelines (e.g. `release-next` and `main`) to be run simultaneously with only one being published. A global variable called `BRANCH_TO_PUBLISH` has been added to the Jenkins system configuration that will determine which branch to publish by default (currently set to `release-next`). Once this has been merged we can re-enable the main nightly pipeline.

**To test:**
I temporarily changed the `BRANCH_TO_PUBLISH` Jenkins global variable to the name of the branch in this pull request and started a test pipeline run on this branch. You can see that if you click "build with parameters" the "publish packages" option is ticked:
https://builds.mantidproject.org/job/tom-test-pipeline-with-branch_to_publish/
After changing `BRANCH_TO_PUBLISH` to `release-next` and running this pipeline job on this branch, you can see that the "publish packages" option is not ticked:
https://builds.mantidproject.org/job/tom-test-pipeline/

Fixes #34849

*This does not require release notes* because **it is a change to our build pipeline**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-02-02 13:35 UTC, robertapplin requested changes
The changes look good and seems to work judging by the test pipelines. Just wanted to ask whether we need to add documentation about `BRANCH_TO_PUBLISH`? For instance is this a variable we need to change when running through the Release Checklist?

2023-02-06 15:00 UTC, robertapplin submitted a review, later dismissed
Thanks for the doc update, looks good 👍

2023-02-08 19:20 UTC, peterfpeterson commented
Please click the "Ready for review" button

2023-02-10 15:21 UTC, robertapplin approved these changes

2023-02-13 09:38 UTC, merged