Add ISIS Reflectometry GUI Preview Tab manual testing instructions
mantidproject/mantid pull request #35131
Opened 2023-02-01 15:02 UTC by rbauststfc

**Description of work.**

Adds manual testing instructions for the new preview tab in the ISIS Reflectometry GUI. We're using test data from the unit tests at the moment - the reason for this is explained on the linked issue and it shouldn't be necessary long-term.

**To test:**

Check that the new instructions make sense.

Fixes #34967. 

*This does not require release notes* because **it is an update to documentation.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-02-07 12:07 UTC, ConorMFinn requested changes
Reads well and tests almost all the functionality I can think of, just a few suggestions:

2023-02-10 15:21 UTC, rbauststfc commented on dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
> +- Type `INTER45455` into the `Run` input. Set the `Angle` to `1` and click `Load`. The instrument view plot should display the data. If the plot remains blank then check that you have added the path
Ah, thanks, I'll correct that - I'm not sure why I didn't spot it from the existing text!

2023-02-10 15:22 UTC, rbauststfc commented on dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
> +- Type `INTER45455` into the `Run` input. Set the `Angle` to `1` and click `Load`. The instrument view plot should display the data. If the plot remains blank then check that you have added the path
It's been re-named in the unit test data, so this should work OK.

2023-02-10 15:24 UTC, rbauststfc commented on dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
> +- Click the rectangle-select button above the plot and draw a region onto the instrument view. The selected detector segments should be summed and the result plotted on the second (slice viewer) plot
Yes, good idea. I've just checked the deleting and I found that I could use the delete key for both the instrument viewer and slice viewer. I had to be quite careful that the region was definitely selected, though. Are you still having this problem?

2023-02-13 10:28 UTC, ConorMFinn commented on dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
> +- Click the rectangle-select button above the plot and draw a region onto the instrument view. The selected detector segments should be summed and the result plotted on the second (slice viewer) plot
https://github.com/mantidproject/mantid/pull/35131/files/02c0666414d92f6ee5926f44bd8801eccc825531..ceeab53a9a73f9c4a93b9a2db4907f0b6021bcda#r1102894614

2023-02-13 10:32 UTC, rbauststfc commented on dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
> +- Click the rectangle-select button above the plot and draw a region onto the instrument view. The selected detector segments should be summed and the result plotted on the second (slice viewer) plot
Ah, thanks for double checking. I'll add it to the list on issue #34220 as something we need to look into.

2023-02-13 10:41 UTC, ConorMFinn approved these changes
Looks good to me, good to get these added in 👍

2023-02-16 09:26 UTC, merged