Added the ability read the notes from ISIS nexus files
mantidproject/mantid pull request #35171
Opened 2023-02-06 10:54 UTC by AnthonyLim23

**Description of work.**
The muon group wanted to be able to read the notes from a nxs file. Turns out that it a field in all ISIS nxs files. I have updated the main reader to handle this. 

**To test:**

Load files from different instruments. The below script is a nice way to check things (EMU and IRIS have comments)

```
files = ['EMU115363.nxs_v2', 'POLREF00004699.nxs', 'IRIS56944.nxs']

for file in files:
    ws = LoadISISNexus(file)
    if "POL" in file:
        # returns a group
        ws = ws[0]
    print("file: ", file)
    print("comment: ", ws.getComment())
    print()
```

Fixes #34908 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-02-06 11:57 UTC, AnthonyLim23 commented on Framework/DataHandling/test/LoadISISNexusTest.h
> +    load.setPropertyValue("Filename", "EMU000102347.nxs_v2");
```suggestion
    load.setPropertyValue("Filename", "EMU00102347.nxs_v2");
```

2023-02-09 12:07 UTC, gemmaguest commented
Note to whoever merges this that it would be good to do a squash and merge because we will need to cherry-pick the fix onto another branch.

2023-02-09 12:09 UTC, ConorMFinn requested changes
Works well, just a quick comment on the release notes

2023-02-13 09:40 UTC, ConorMFinn approved these changes
Looks good to me now!

2023-02-13 17:50 UTC, merged