Make plots resize with windows better
mantidproject/mantid pull request #35195
Opened 2023-02-10 10:42 UTC by jhaigh0

**Description of work.**

This PR fixes a bug where plot axes labels could be hidden outside the window boundaries after resizing. It also aims to make all plot types resize in a more predictable and nicer way. 

An important part of this was giving plots a tight layout; this has resulted in warnings being printed to the console when a window is resized to be very small. Since these warnings are annoying, I tried to filter them out, but couldn't find a solution that worked. However, you have to shrink the plot to an unusable size to make them appear, so I think it is okay overall.

**To test:**

To test these changes, it will be useful to have another version of Mantid open to see the differences.

 - Load `164199.nxs` (from the training course data)
 - Right-clicking on the loaded workspace, plot a....
 	- [ ] Spectrum
 	- [ ] Spectrum with errors
 	- [ ] Spectrum range tiled plot
 	- [ ] Spectrum range waterfall plot
 	- [ ] Super Plot
 	- [ ] Super Plot with errors
 	- [ ] Colorfill
 	- [ ] Surface
 	- [ ] Wireframe
 	- [ ] Contour
 - And for each of these resize the window to a few different **reasonable** sizes and check that
	1. No figure objects are colliding
	2. No parts of the figure are being hidden outside the window boundaries
	3. Moving the legend and editing axes names and ranges doesn't break anything
 - Now load `164198.nxs` and `164200.nxs`
 - Group the three workspaces together (highlight all and click Group)
 - Right-clicking on the new group, plot all the different types of plots again and make the same checks

Finally, test with a some other graphing scenarios that you think might be challenging.

Fixes #35014

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-03-03 15:51 UTC, sf1919 requested changes
This works very well and it's useful that when the labels etc are cut off you do get an error message - `Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations.`

I've asked for a couple of changes to the comments just to make them clearer.

Should this have test(s)?

2023-03-03 15:51 UTC, sf1919 commented on Framework/PythonInterface/mantid/plots/plotfunctions.py
> +            # Stop legend messing with the tight layout
```suggestion
            # Stop legend interfering with the tight layout
```

2023-03-03 15:51 UTC, sf1919 commented on Framework/PythonInterface/mantid/plots/plotfunctions.py
> +        # Keeping the colour bar in the GridSpec rather than alongside it means it behaves much nicer
Could this be reworded slightly? It seems a bit subjective and not clear what behaviour it is actually doing.

2023-03-07 16:28 UTC, jhaigh0 commented
Yes, I reckon I could've put a test in for the creating subplots colour bar change; I'll add that.

2023-03-10 09:24 UTC, sf1919 approved these changes
Thank you for putting the tests in. I think they're a good addition and should hopefully catch anything like this in future. 

This one is now good to go.

2023-03-10 15:11 UTC, merged