Tidy up pearl output files naming and save directories
mantidproject/mantid pull request #35334
Opened 2023-03-02 17:06 UTC by RichardWaiteSTFC

**Description of work.**

Tidy up pearl output files naming and save directories
**To test:**

Fixes #30883 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-03-07 14:30 UTC, DannyHindson requested changes

2023-03-07 14:30 UTC, DannyHindson commented on scripts/Diffraction/isis_powder/pearl.py
> +        }
This Pearl-specific function override of `_generate_out_file_paths` copies all of the code from the equivalent function in abstract_inst.py but I think the only changes are L119-121. The `dat_files_directory` variable is also renamed higher up but that's not important. Please could you create a new function in abstract_inst.py called `_get_output_formats()` or similar that generates the output_formats dictionary
and then have an overridden version of `_get_output_formats` in this unit that does the Pearl-specific behaviour (subfolders)? You can then remove the Pearl specific version of `_generate_out_file_paths` I think

2023-03-16 17:32 UTC, DannyHindson submitted a review, later dismissed
Looks good thanks

2023-03-17 07:53 UTC, DannyHindson commented
Just noticed that the release note is in the single crystal folder for this PR. If you have a minute today please could you move to `docs\source\release\v6.7.0\Diffraction\Powder`

2023-03-17 09:18 UTC, RichardWaiteSTFC commented
> Just noticed that the release note is in the single crystal folder for this PR. If you have a minute today please could you move to `docs\source\release\v6.7.0\Diffraction\Powder`

Good spot thanks! I was on auto-pilot!

2023-03-17 09:26 UTC, DannyHindson commented
Is the old release note still there in the Single Crystal folder?

2023-03-17 09:28 UTC, RichardWaiteSTFC commented
> Is the old release note still there in the Single Crystal folder?

Not since my force-push, sorry!

2023-03-17 10:54 UTC, DannyHindson approved these changes

2023-04-20 11:03 UTC, merged