Refactoring assert raises in python algorithm tests part 5
mantidproject/mantid pull request #35330
Opened 2023-03-02 13:08 UTC by jhaigh0

**Description of work.**

Fifth part of the work to remove the blanket use of `assertRaises` when testing algorithm input validation in favour of `assertRaisesRegex`. This way we can expect a certain exception rather than accepting any possible `RuntimeException` which could be an unrelated bug (there were a few found during in the tests from this pr).

Main issue is #34570

**To test:**

 - All tests should pass (handled by Jenkins)
 - Code review

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-03-14 13:53 UTC, robertapplin requested changes
The code looks good. I had one minor code style suggestion, and spotted a couple of typos in some of the exceptions

2023-03-14 13:53 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TotScatCalculateSelfScattering.py
> +                raise ValueError("SampleTemperature must be provided")
```suggestion
        if placzek_order == 2:
            if not sample_temp:
                raise ValueError("SampleTemperature must be provided")
            placzek_kwargs.update({"SampleTemperature": sample_temp})
```

2023-03-14 13:53 UTC, robertapplin commented on Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/MSDFitTest.py
> +            "SpecMin must be less then SpecMax",
```suggestion
            "SpecMin must be less than SpecMax",
```
I think there is a typo in this exception

2023-03-14 13:53 UTC, robertapplin commented on Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/MSDFitTest.py
> +            "XStart must be less then XEnd",
```suggestion
            "XStart must be less than XEnd",
```
same here

2023-03-14 14:23 UTC, jhaigh0 commented
> The code looks good. I had one minor code style suggestion, and spotted a couple of typos in some of the exceptions

Will need to change those strings where they are raised too.

2023-03-15 08:48 UTC, robertapplin approved these changes
Thanks for the changes, looks good 👍

2023-03-15 15:58 UTC, merged