Improve sample shape plotting performance
mantidproject/mantid pull request #35369
Opened 2023-03-16 08:09 UTC by DannyHindson

**Description of work.**

Speed up performance of the plotting of the sample shape and container in cases where shapes are complex. This has been achieved by reducing the number of calls to getMesh

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-03-16 16:49 UTC, jhaigh0 requested changes
Nice change to localise those `getMesh()` calls. Also took around 30 seconds or so to show the shape for me, I would be a nice if there was a progress indicator for that I think (not in this pr though).

Just some minor code review comments.

2023-03-16 16:49 UTC, jhaigh0 commented on qt/python/mantidqt/mantidqt/plotting/sample_shape.py
> +    if mesh is not None:
I think `if mesh` is equivalent to `if mesh is not None` but okay if you just want to be explicit about it 👍

2023-03-16 16:49 UTC, jhaigh0 commented on qt/python/mantidqt/mantidqt/plotting/test/test_sample_shape.py
> +        self.assertTrue(sample_shape.get_valid_sample_mesh_from_workspace(workspace) is not None)
You could use `self.assertIsNotNone()` for these if you like.

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIsNotNone

2023-03-16 16:49 UTC, jhaigh0 commented on qt/python/mantidqt/mantidqt/plotting/test/test_sample_shape.py
> +        self.assertFalse(sample_shape.get_valid_container_mesh_from_workspace(workspace))
`self.assertIsNone()` would be more readable in these cases.

2023-03-17 08:40 UTC, DannyHindson commented
I decided in the end that it was a bit rubbish that the view still takes 30-40 seconds to load. So I've just pushed a change that properly speeds this up by reducing the number of calls to getMesh even further. Each shape should now just be retrieved once with a single call to getMesh. For me it now takes about 10 seconds.

2023-03-17 09:15 UTC, jhaigh0 reviewed
New changes work great, even quicker than before ⚡. I had a spinny wheel cursor this time when it was loading which is good enough feedback now the time to load is much smaller.

I've added one reformatting suggestion to get rid of the raw loop from `create_plot` but other than that all seems good. Much better to pass the meshes about rather than creating them in every function.

2023-03-17 09:34 UTC, jhaigh0 approved these changes

2023-03-17 09:53 UTC, jhaigh0 requested changes
Ah, Almost forgot.... I think this should have a release note since the users should notice the difference.

2023-03-17 10:29 UTC, jhaigh0 approved these changes

2023-03-21 13:52 UTC, merged