Fixed crash in indirect data analysis
mantidproject/mantid pull request #35429
Opened 2023-04-03 13:43 UTC by AnthonyLim23

This fixes a bug that caused the indirect data analysis interfaces to crash when multiple cells were selected, such that the total number of selected cells exceeded the number of rows.

I have not included a unit test because it involves significant amounts of Qt. Since the function takes a `QModelIndexList` we would need to create `QModelIndex`'s. However, these need a `QAbstractModel`. Which in turn needs several virtual functions. 

**To test:**
Open indirect -> data analysis
Go to the conv fit tab (any tab will work if you have data)
Click Add Workspace
Select some data for the workspace and resolution
For workspace indices, just load (any) 6 spectra

Select the `Resolution` cells for two of the spectra (just 2 cells will be highlighted)
Click Remove, those 2 rows should be gone (check by looking at the WS index)

Highlight the `Resolution` and `WS Index` cells for 3 spectra (6 highlighted cells in total)
Click Remove - this used to crash
One row should be left (the one you did not highlight)

Fixes #35427 

In release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

2023-04-14 15:52 UTC, MialLewis approved these changes, later dismissed
Code looks good, bug is fixed. I'll take your word that a unit test would be a disproportionate amount of work!

2023-04-20 10:53 UTC, thomashampson requested changes

2023-04-20 10:53 UTC, thomashampson commented on qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.h
> +  std::map<int, QModelIndex> getUniqueIndices(const QModelIndexList &selectedIndices);
Function can be private if it's not accessed by the test class any more.

2023-04-25 10:29 UTC, thomashampson approved these changes

2023-04-25 11:52 UTC, merged