Change pystog to be a conda dependency
mantidproject/mantid pull request #35673
Opened 2023-06-12 13:20 UTC by peterfpeterson

Since there is now a noarch [conda package for pystog](https://anaconda.org/neutrons/pystog) change from the external dependency to that package.

**To test:**

The unit test for `PDConvertReciprocalSpace` should continue to pass.

*There is no associated issue.*

*This does not require release notes* because it changes how a dependency is installed and has no other effect.

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-06-12 14:36 UTC, Kvieta1990 submitted a review, later dismissed

2023-06-19 14:33 UTC, thomashampson requested changes

2023-06-19 14:33 UTC, thomashampson commented on conda/recipes/mantid/meta.yaml
> +    - pystog {{ pystog }}
Since this adds to our conda recipe, can we test that the packaging still works with this change?

2023-07-20 13:42 UTC, sf1919 commented
Given the outcome of the TWG meeting does this PR need updating or closing?

2023-08-24 11:24 UTC, thomashampson approved these changes

2023-08-24 12:40 UTC, merged