Add missing algorithm history tracking to UnGroupWorkspace
mantidproject/mantid pull request #35865
Opened 2023-07-31 14:42 UTC by jhaigh0

**Description of work**

Fixes a bug where workspaces which belonged to a group that was passed to `UnGroupWorkspace`, did not include the algorithm in their history.

The reason why is that when passing on algorithm history, the Algorithm base class searches for algorithm properties which are outputs and can cast to a workspace. `UnGroupWorkspace` simply removes the group workspace passed to it (releasing the child workspaces in doing so) so doesn't need an 'output' property, meaning the history is never passed on.

**Summary of work**
The simplest way has involved moving the second `fillHistory` declaration from private to protected. I don't see this as being dangerous to do anyway, just disrupts the 'correctness' a little.
Also added in a test.

**To test:**

Run this script
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws1 = CreateSampleWorkspace()
ws2 = CreateSampleWorkspace()
group_ws = GroupWorkspaces(InputWorkspaces="ws1,ws2")
UnGroupWorkspace(group_ws)
```
Right click `ws1` and click `Show History`; `UnGroupWorkspace` should be the last algorithm on there with correct input worksapce listed.
Check again for `ws2`.

Fixes #34255

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-08-14 12:48 UTC, robertapplin requested changes
Nice find and thanks for adding a test. I have a few suggestions but looks good overall

2023-08-14 12:48 UTC, robertapplin commented on Framework/Algorithms/test/UnGroupWorkspaceTest.h
> +    return found;
I think we can use a c++ std library algorithm here
```suggestion
    auto iter = std::find_if (wsHistories.cbegin(), wsHistories.cend(), [](auto const &algHistory){ return algHistory->name() == "UnGroupWorkspace";});
    return iter != wsHistories.cend();
```

2023-08-14 12:48 UTC, robertapplin commented on Framework/Algorithms/test/UnGroupWorkspaceTest.h
> +  bool isAlgorithmInHistory(const Mantid::API::Workspace_sptr ws) {
```suggestion
  bool isAlgorithmInHistory(const Mantid::API::Workspace_sptr &ws) {
```

2023-08-16 14:05 UTC, robertapplin commented on Framework/Algorithms/src/UnGroupWorkspace.cpp
> +  fillHistory(outputWorkspaces);
Is it possible to just do this?
```suggestion
  fillHistory(wsGrpSptr->getAllItems());
```

2023-08-16 14:10 UTC, jhaigh0 commented on Framework/Algorithms/src/UnGroupWorkspace.cpp
> +  fillHistory(outputWorkspaces);
yes 🙃 clearly did that when tired

2023-08-21 08:54 UTC, robertapplin approved these changes
Thanks for the changes, happy to approve

2023-08-21 16:40 UTC, merged