Adapt PowderreduceP2d to usage with SNAP data
mantidproject/mantid pull request #35872
Opened 2023-08-01 14:20 UTC by YannickMeinerzhagen

**Description of work**
The Workflow algorithm PowderreduceP2d has been modified for several reasons.
1. As the algorithm AlignDetectors was deprecated, it was replaced with the algorithm ApplyDiffCal.
2. A small Bug for the ResetNegatives2D function was fixed. 
3. The algorithm was modified to be applicable to data collected at the instrument SNAP at SNS.
4. The possibility to use a vanadium background file was added.
5. Binning parameters have been adjusted to removal of the parameter center wavelength

**Purpose of work**
The algorithm PowderReduceP2d was developed for the creation of multidimensional neutron time of flight datasets. These datasets are necessary for the new multidimensional Rietveld refinement method that is being developed for the diffractometer POWTEX to be build at FRM-II in Garching. For more information on the multidimensional Rietveld refinement look at:

https://doi.org/10.1107/S1600576723002819

https://doi.org/10.1107/S1600576717005398

https://doi.org/10.1107/S1600576715016520

As the instrument POWTEX is not build up yet, we are testing the reduction and refinement process with data from different instruments. The extension to other instruments is interesting for others as well, as the method can be applied to all TOF instruments with large area detectors.

**Summary of work**
1. The algorithm was replaced as was recommended.
2. The resetting of negative values to a set value was done by creating a new workspace. Not setting the attribute distribution to True resulted in an error, so that was added to the function.
3. The SNAP instrument uses a different calibration method than was used before (detcal files instead of cal files), which made a different calibration routine necessary.
4. The instrument POWGEN has started using background measurements for the vanadium correction, so this has been added as an optional functionality. 
5. The parameter center wavelength was removed because it was unnecessary. The binning parameters now have to be defined as a list of firstBin, binwidth, lastBin.

**Further detail of work**
3. To reduce data collected at the instrument SNAP it was first necessary to implement the usage of detcal files for the calibration of the detectors. Depending on the fileextension (cal or detcal) the code automatically follows the corresponding calibration path. To make the usage of masking files easier, the missing option to use xml files via the loadMask algorithm has been implemented.

**To do:**

- [ ] Check if test function for this algorithm still works
- [ ] If necessary, adapt testing data
- [ ] Check .rst file for any changes necessary
- [ ] If necessary, make changes to flow chart
- [ ] Add release notes
- [ ] Add labels fitting to the Pull request

**To test:**
Example for testing can be found in the test function associated with this algorithm. If available, POWGEN or SNAP data should generally work but some fiddling with initial parameters might be necessary.

*There is no associated issue.*

At this moment the base of this PR is main, if this is not correct please let me know. Any information on applicable labels will be much appreciated.

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-08-22 11:11 UTC, robertapplin requested changes
Just had a quick look through. I won't be able to do a full review, so thought I'd just look through the code. I spotted a couple of misaligned indentations - apologies for how picky this is! Apart from that, the code looks good

2023-08-22 11:11 UTC, robertapplin commented on docs/source/diagrams/PowderReduceP2D_ProcessCanRun.dot
>      edgebinning     [label="Is edgebinning specified?"]
```suggestion
    $decision_style
    maskFile        [label="Is masking file specified?"]
    detcal          [label="Is calibration file of type detcal?"]
    detcal2         [label="Is calibration file of type detcal?"]
    detcal3         [label="Is calibration file of type detcal?"]
    edgebinning     [label="Is edgebinning specified?"]
```

2023-08-22 11:11 UTC, robertapplin commented on docs/source/diagrams/PowderReduceP2D_ProcessCanRun.dot
> +  LoadDetcal                    -> FindDetectorsPar
```suggestion
  detcal                    -> FindDetectorsPar  [label="No"]
  LoadDetcal                -> FindDetectorsPar
```

2023-08-22 11:11 UTC, robertapplin commented on docs/source/diagrams/PowderReduceP2D_ProcessVanadiumRun.dot
>      edgebinning     [label="Is edgebinning specified?"]
```suggestion
    maskFile        [label="Is masking file specified?"]
    detcal          [label="Is calibration file of type detcal?"]
    detcal2         [label="Is calibration file of type detcal?"]
    detcal3         [label="Is calibration file of type detcal?"]
    edgebinning     [label="Is edgebinning specified?"]
```

2023-08-22 11:11 UTC, robertapplin commented on docs/source/diagrams/PowderReduceP2D_ProcessVanadiumRun.dot
> +  LoadDetcal                    -> FindDetectorsPar
```suggestion
  detcal                    -> FindDetectorsPar  [label="No"]
  LoadDetcal                -> FindDetectorsPar
```

2023-08-22 11:11 UTC, robertapplin commented on docs/source/release/v6.8.0/Diffraction/Powder/New_features/35872.rst
> +-:ref:`PowderReduceP2D <algm-PowderReduceP2D>` has been adapted to work with SNAP measuring data
```suggestion
- :ref:`PowderReduceP2D <algm-PowderReduceP2D>` has been adapted to work with SNAP measuring data.
```

2023-08-23 07:41 UTC, YannickMeinerzhagen commented
Thanks a lot for your input. I dont mind picky stuff, it has to be done and will only quicken the following review :)

2023-08-23 08:43 UTC, MialLewis commented
Hi Yannick, You're currently occupying all 8 of our linux builders with builds triggered as a result of your pushes to your remote branch associate with this PR. I don't suppose you could fix your PR locally before pushing? Let me know if you have any queries regarding how to do this.

2023-08-23 09:26 UTC, YannickMeinerzhagen commented
I'm sorry, didn't realise that would happen when I just accept the change requests here! I will do changes locally next time, thanks for letting me know.

2023-08-23 09:34 UTC, MialLewis commented
No worries, I think if you click `Add suggestion to batch` you can commit all the recommended changes as one commit, which will only trigger one build.

2023-09-01 08:36 UTC, robertapplin approved these changes
Thanks for the changes. The code looks good and it works as explained 👍

2023-09-01 11:29 UTC, gemmaguest commented
> I'm sorry, didn't realise that would happen when I just accept the change requests here! I will do changes locally next time, thanks for letting me know.

@YannickMeinerzhagen You can also temporarily close a PR if you want to push to it without kicking off the builds - just re-open it again when you want to run the builds. I haven't tried applying suggested changes when it's closed but I imagine it should still work.

2023-09-04 15:01 UTC, merged