Update EngDiff UI manual testing instructions
mantidproject/mantid pull request #36025
Opened 2023-09-07 14:01 UTC by RichardWaiteSTFC

**Description of work**

**Purpose of work**

**Summary of work**

**Further detail of work**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-09-08 14:23 UTC, thomashampson commented
let's keep this going into `main` rather than `release-next`. Dev docs are always published from `main` anyway.

2023-10-04 14:59 UTC, warunawickramasingha commented on dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
> +1. Load in a run - the `Subtract BG` box should be checked in the UI table by default. This should generate a workspace with suffix `_bgsug` and the data should look like the background is flat and r
There is a typo, it should be _bgsu**b**

2023-10-04 14:59 UTC, warunawickramasingha commented on dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
> +2. Click the `Load` button. A row should be added to the UI table for each focused run.There should be a grouped workspace with the suffix `_logs_Fitting` in the ADS with tables corresponding to each
I think this description of 'run_info' is needed be moved earlier

2023-10-05 15:20 UTC, warunawickramasingha commented on dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
There is a discrepancy in the files generated at Test 1 - Focus - Step 6. The test specify as 

> `ENGINX_305761_307521_all_banks.gss` and `ENGINX_305761_307521_all_banks.abc` (i.e. two ASCII files per run - each file contains all the spectra for a focused run).

Whereas the real files generated are like 

> ENGINX_305761_307521_all_banks_dSpacing.gss, ENGINX_305761_307521_bank_2_dSpacing.gss,  ENGINX_305761_307521_all_banks_TOF.gss and ENGINX_305761_307521_bank_2_TOF.gss

> ENGINX_305761_307521_all_banks_dSpacing.abc, ENGINX_305761_307521_all_banks_TOF.abc, ENGINX_305761_307521_bank_2_dSpacing.abc, and ENGINX_305761_307521_bank_2_TOF.abc

2023-10-05 15:29 UTC, warunawickramasingha commented on dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
>  9. Set the ``Region of Interest`` to ``Texture (20 spec)`` - there should be 20 spectra per run (5 tiled plot windows, 4 spectra per window).
9. Set the ``Region of Interest`` to ``Texture (20 spec)`` **and  Click 'Calibrate'**?

2023-11-02 11:51 UTC, warunawickramasingha requested changes
As I have commented above, there is a typo and a discrepancy in the files generated at Test 1 - Focus - Step 6.

2024-01-12 14:41 UTC, warunawickramasingha commented
> As I have commented above, there is a typo and a discrepancy in the files generated at Test 1 - Focus - Step 6.

In addition, I noticed a few places where the screenshots of the Engdiff interface looks outdated as below

1. The screenshot does not have the GSAS-II tab: https://docs.mantidproject.org/nightly/interfaces/diffraction/Engineering%20Diffraction.html#parameters
https://docs.mantidproject.org/nightly/interfaces/diffraction/Engineering%20Diffraction.html#id1
https://docs.mantidproject.org/nightly/interfaces/diffraction/Engineering%20Diffraction.html#id2
2. The toolbar in the plot section does not contain the buttons up to date.
https://docs.mantidproject.org/nightly/interfaces/diffraction/Engineering%20Diffraction.html#id2

2024-04-12 15:09 UTC, warunawickramasingha approved these changes
Thanks for the changes and both the docs and dev-docs targets locally compiled successfully and looks up-to-date with the attached images. 
Happy to approve!

2024-04-15 07:46 UTC, merged