Initial diffraction release notes for v6.8
mantidproject/mantid pull request #36157
Opened 2023-09-21 14:00 UTC by RichardWaiteSTFC

**Description of work**

Initial diffraction release notes for v6.8

**To test:**
(1) Build docs
(2) Check links and formatting in html

*There is no associated issue.*

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-09-21 14:45 UTC, sf1919 commented
This needs to be on release-next

2023-09-22 15:23 UTC, ConorMFinn requested changes
A few small issues/questions

2023-09-22 15:23 UTC, ConorMFinn commented on docs/source/release/v6.8.0/diffraction.rst
> +- Raise an error in POLARIS (ISIS) powder reduction script if user tries to creta a vanadium workspace without correcting for absorption and multiple scattering.
```suggestion
- Raise an error in POLARIS (ISIS) powder reduction script if user tries to create a vanadium workspace without correcting for absorption and multiple scattering.
```

2023-09-22 15:23 UTC, ConorMFinn commented on docs/source/release/v6.8.0/diffraction.rst
> +- Raise errors in absolute normalisation due to lack of sample/vanadium shape and material in ISIS powder reduction
This reads a bit strangely
```suggestion
- When performing an ISIS powder reduction, errors are raised in absolute normalisation when sample/vanadium shape and material are not provided.
```

2023-09-22 15:23 UTC, ConorMFinn commented on docs/source/release/v6.8.0/diffraction.rst
> +- Added new SNAPRed menu item for Diffraction interfaces
```suggestion
- Added new ``SNAPRed`` menu item for Diffraction interfaces
```

2023-09-22 15:23 UTC, ConorMFinn commented on docs/source/release/v6.8.0/diffraction.rst
> +- New algorithm to load gaussian cube files for volumetric data into a 3D :ref:`MDHistoWorkspace <MDHistoWorkspace>`
Can we have a link to this new algorithm's docs?

2023-09-25 10:48 UTC, ConorMFinn approved these changes

2023-09-25 12:41 UTC, merged