Add pre-commit hook to check release note bullet point stlye
mantidproject/mantid pull request #36202
Opened 2023-10-03 11:05 UTC by jhaigh0

**Description of work**

Add a pre-

**Purpose of work**

**Summary of work**

**Further detail of work**

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-10-11 14:15 UTC, robertapplin approved these changes, later dismissed
This works really well, and will prevent a lot of problems when building our release notes with sphinx. This will mean fewer nightly failures due to sphinx warnings, thanks!

2023-10-13 10:40 UTC, ConorMFinn requested changes, later dismissed
I'm not overly familiar with how pre-commit works, but is there a reason a new repo was created for this and rather than using https://github.com/mantidproject/pre-commit-hooks that's already in the organisation?

2023-10-17 02:08 UTC, peterfpeterson commented on .pre-commit-config.yaml
> +  - repo: https://github.com/jhaigh0/mantid-pre-commit
Shouldn't the hook be in https://github.com/mantidproject/pre-commit-hooks.git ?

2023-10-17 02:17 UTC, peterfpeterson commented
I only got through fixing issues in the dev-docs site, but #36288 might flag this issue in a more robust way.

2023-10-24 13:32 UTC, jhaigh0 commented
I have added a PR to the mantid project pre commit hooks repo. So once that is through I can update this PR to use that instead.

https://github.com/mantidproject/pre-commit-hooks/pull/10

2023-10-25 13:06 UTC, ConorMFinn commented
- https://github.com/mantidproject/pre-commit-hooks/pull/10 is now merged, so this is ready for another look @robertapplin

2023-10-26 13:42 UTC, peterfpeterson approved these changes

2023-10-26 13:42 UTC, merged