Make user docs for ISIS single-crystal diffraction reduction
mantidproject/mantid pull request #36210
Opened 2023-10-04 08:12 UTC by RichardWaiteSTFC

**Description of work**

Make user docs for ISIS single-crystal diffraction reduction

**To test:**

Fixes #xxxx. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-12-07 13:08 UTC, warunawickramasingha requested changes
I executed all the code blocks in the docs and found out a few locations with some errors which I have commented as above.

2023-12-07 13:08 UTC, warunawickramasingha commented on docs/source/techniques/ISIS_SingleCrystalDiffraction_Workflow.rst
> +                           ReflectionCondition='Body centred')
I am getting this error at this line

`File "<unknown>", line 33
    ModVector1="0.5,0,0", ModVector2="0,0.5,0", ModVector3="0,0,0.5",
    ^
SyntaxError: invalid syntax`

2023-12-07 13:10 UTC, RichardWaiteSTFC commented on docs/source/techniques/ISIS_SingleCrystalDiffraction_Workflow.rst
> +  detcal_path = sxd.calibrate_sxd_panels(wsname, pk_wsname, save_dir, tol=0.2)
Thanks, will do both of the above!

2023-12-07 13:11 UTC, RichardWaiteSTFC commented on docs/source/techniques/ISIS_SingleCrystalDiffraction_Workflow.rst
> +        skew_args = {**skew_args, 'OutputFile': path.join(save_dir, f"{run}_{peak_type.value}_int.pdf")}
Thanks yes it should be `PEAK_TYPE.FOUND`

2023-12-08 17:23 UTC, warunawickramasingha approved these changes
Thank you for the updates and I am happy to approve!

2023-12-11 08:49 UTC, merged