Fix for plot script unhiding other plots
mantidproject/mantid pull request #36310
Opened 2023-10-23 15:43 UTC by jclarkeSTFC

### Description of work
The script generated by a plot window ends with a call to `plt.show()`, but `show()` causes all hidden plots to be unhidden. This was changed from calling `fig.show()` in #28699 because the `matplotlib` online documentation usually uses `plt.show()`. There's an explanation [here](https://stackoverflow.com/a/51570439) about the difference (assuming the random person who wrote that answer is correct).

Fixes #34978. 

### To test:
See #34978 for how to reproduce. Maybe trying a few different plot types and their generated scripts would be good. I tried a few different ones and they seemed okay.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-11-07 13:04 UTC, adriazalvarez commented
I think is the best solution to the problem described in #34978. But as noted by James, fixing it in this way on the workbench backend will make things worse for people using the script externally, as fig.show() does not execute its own event loop. 
https://github.com/matplotlib/matplotlib/blob/325fcbbc3e626052ceb8672e80b51abd6a05f94b/lib/matplotlib/figure.py#L2641

I have tried to open an script using this solution on a jupyter notebook, and it works only because the notebook executes plt.show() by default on each cell. (on pycharm for example it does not work). 

We could add a commented 'plt.show()'  in the line next to fig.show() with a  warning to the users of the issue. Otherwise is a use case scenario, if most people will execute the script withing the workbench, then the changes are fine. 

Since this is a draft, I guess is better if somebody with more authority than me comment on it.

2024-01-10 16:08 UTC, jclarkeSTFC commented
Probably best to leave it as it is for now, can always come back to this later.

2024-03-20 13:49 UTC, jclarkeSTFC commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
> +        # User plt.show() if running the script outside of Workbench
```suggestion
        # Use plt.show() if running the script outside of Workbench
```

2024-03-20 13:49 UTC, jclarkeSTFC commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
> +    "# User plt.show() if running the script outside of Workbench\n"
```suggestion
    "# Use plt.show() if running the script outside of Workbench\n"
```

2024-03-20 13:50 UTC, warunawickramasingha commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
> +        # User plt.show() if running the script outside of Workbench
I guess there is a typo in the comment where `User` need to be `Use`. Unfortunately that change requires update to unit tests as well.

2024-03-20 13:50 UTC, jclarkeSTFC commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
> +    "# User plt.show() if running the script outside of Workbench\n"
```suggestion
    "# Use plt.show() if running the script outside of Workbench\n"
```

2024-03-20 13:51 UTC, jclarkeSTFC commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
> +    "# User plt.show() if running the script outside of Workbench\n"
```suggestion
    "# Use plt.show() if running the script outside of Workbench\n"
```

2024-03-20 14:30 UTC, warunawickramasingha requested changes

2024-03-20 14:30 UTC, warunawickramasingha commented on qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
> +    cmds.append("# User plt.show() if running the script outside of Workbench")
```suggestion
    cmds.append("# Use plt.show() if running the script outside of Workbench")
```

2024-03-21 13:29 UTC, warunawickramasingha approved these changes
Happy to approve and the fix is working fine.

2024-03-21 13:43 UTC, merged