Moving Data Analysis GUI interface files to inelastic folder.
mantidproject/mantid pull request #36364
Opened 2023-11-03 12:30 UTC by adriazalvarez

### Description of work
A new qt library / test library for the inelastic interface category has been created.
 A new inelastic subdirectory has been created,  and the data analysis interface files and test files have been moved 
to the new category.
#### Summary of work

Part of #35665 . 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-11-03 14:04 UTC, robertapplin requested changes
Code changes look good and the hard part (creating a qt library) is done!

I've just realised how many Data Analysis files there are. We also need to moves these and their related test files:

- [ ] `IFQFitObserver`
- [ ] `IndirectDockWidgetArea`
- [ ] `IndirectFitPlotModel`
- [ ] `IndirectFitPlotView`
- [ ] `IndirectFitPropertyBrowser`
- [ ] `ConvFitModel`
- [ ] `FQFitConstants`
- [ ] `FitStatusWidget`
- [ ] `FunctionTemplateBrowser`
- [ ] `IDAFunctionParameterEstimation`
- [ ] `IIndirectFittingModel`
- [ ] `IIndirectFitDataView`
- [ ] `IIndirectFitOutput`
- [ ] `IIndirectFitOutputOptionsModel`
- [ ] `IIndirectFitOutputOptionsView`
- [ ] `IIndirectFitPlotView`
- [ ] `IIndirectFitPlotModel`
- [ ] `IIndirectFitPlotPresenter`
- [ ] `IIndirectFittingModel`
- [ ] `IndirectEditResultsDialog`
- [ ] `IndirectFitData`
- [ ] `IndirectFitDataModel`
- [ ] `IndirectFitDataPresenter`
- [ ] `IndirectFitDataView`
- [ ] `IndirectFitOutput`
- [ ] `IndirectFitOutputOptionsPresenter`
- [ ] `IndirectFitTab`
- [ ] `IndirectSpectrumSelector`
- [ ] `ParameterEstimation`

2023-11-06 16:06 UTC, adriazalvarez commented
I have added the remaining files in the last commit. 
Sorry for the huge file dump. It was very entangled with data analysis and data manipulation, 
so I have decided to merge this issue with #36323 . This last commit makes part of that. 
(at the end there were data manipulation classes calling data analysis classes). Additionally, I had to move the indirect function browser folder to inelastic folder to resolve dependencies in data analysis.
Finally I also moved the test.

2023-11-06 16:30 UTC, robertapplin requested changes
This new file organisation is much better, thanks! Can you rename the `IndirectFunctionBrowser` folder to `FunctionBrowser`, and move it into the Analysis folder?

2023-11-06 16:30 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/CMakeLists.txt
>      IndirectFitPreviewPlot.ui
I think we want to move this to the Inelastic/Analysis folder

2023-11-06 16:30 UTC, robertapplin commented on qt/scientific_interfaces/Inelastic/Analysis/IndirectFitPlotView.h
> +class MANTIDQT_INELASTIC_DLL SplitterHandle : public QSplitterHandle {
I think we probably don't need the export macro on this class

2023-11-06 16:30 UTC, robertapplin commented on qt/scientific_interfaces/Inelastic/Analysis/IndirectFitPlotView.h
> +class MANTIDQT_INELASTIC_DLL Splitter : public QSplitter {
And same with this class?

2023-11-06 16:30 UTC, robertapplin commented on qt/scientific_interfaces/Inelastic/Analysis/IndirectFitPropertyBrowser.h
> +class MANTIDQT_INELASTIC_DLL FitStatusWidget;
These are just forward declarations and so will not need the export macro
https://stackoverflow.com/questions/4757565/what-are-forward-declarations-in-c

2023-11-06 16:34 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/IndirectFitDataModel.h
>  */
I think you might have missed removing this file from the Indirect folder? It is already in the Inelastic/Analysis folder

2023-11-07 15:44 UTC, robertapplin approved these changes
Thanks for all your hard work on this. This is a really good first step for organising the files in Indirect/Inelastic. It lowers the entry threshold for new starters, and also should make it easier for us to spot commonly used functionality that can be shared across interfaces in the future

2023-11-07 16:15 UTC, merged