Fixes Crash in ApplyAbsorptionCorrections if Corrections file incomplete
mantidproject/mantid pull request #36391
Opened 2023-11-09 18:28 UTC by adriazalvarez

### Description of work
Fixes a bug that crashes the workbench abruptly when trying to apply a correction in the Corrections interface. 

#### Summary of work

For reproducing this issue: 

1. In the workbench, make sure that ISIS is the facility and IRIS is the instrument.
2. Open the ```Indirect->Corrections``` interface.
3. In the second tab, `Calculate Paalman Pings`, choose the Sample property by browsing to an IRIS test file, e.g. `ExternalData/Testing/Data/UnitTest/irs26176_graphite002_red.nxs`. Then, modify the Sample Thickness so it's not 0,  e.g. `0.1` cm, and set the Chemical Formula to `C`. 
4. Press `Run` button. A number of workspaces should be created, including the correction one called `irs26176_graphite002_FlatPlate_PP_Corrections_ass`.
5. Save the corrections workspace with a name that the `FileFinder` for Corrections property in the `Apply Absorption Corrections` tab can recognize it (`*_Corrections.nxs` seems to be the way)
6. Pick the Sample property either from a file or already loaded workspace, and select Corrections property by browsing to the freshly saved file.
7. Try to Run. Mantid should abruptly close with no error message.

     The issue was caused when creating a correction workspace group with only one workspace (like the  ``A,ss`` contribution). If that workspace is saved as a nexus file, the SaveNexus algorithm detects that the workspace group has only one member and saves it as a single workspace instead of as a group. If that workspace is loaded again, and the apply corrections algorithm tried to load, the '_Corrections' key will lead the prompt to select the workspace, but as it is not a group, it retrieves a null pointer for the validator.
     Now, the validator function checks that corrections is a group before processing it. The warning dialog catches the error and prompts the user to change it to a group. 

     While this PR solves the issue of crashing, the default behaviour for saving a corrections group with only one member should be to store it as a group. As that makes part of meddling with SaveNexus algorithm, or perhaps invoking a transform algorithm within the apply corrections interface, it may be best to open a new issue to change that behaviour when saving corrections. 

Fixes #34232 . 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-11-10 10:18 UTC, SpencerHowells commented
@adriazalvarez As the author of all these programs I have a few comments.
1 Tab 2 is about 10 yrs old & has never given this problem. Applying using the existing ws works. Has the reading algorithm been changed recently. Tab 3 also crashes. we have the same problem in other interfaces.
2 We are planning to upgrade and move the interface. During this we will remove tab 2 because tab 3 is a superior version.

2023-11-10 10:39 UTC, adriazalvarez commented
Hi @SpencerHowells , Thanks for your comments. 
Sorry if I have missed something, I'm not entirely familiar with the code revision history of this interface.
I'm not sure what could cause the crash on tabs 2 or 3. I'm trying in the current stable version of Mantid and the issue is quite reproducible on the apply corrections tab.

2023-11-10 11:11 UTC, SpencerHowells commented
@adriazalvarez I think it's a problem with the Load algorithm. To test I did a Load file command. It created a ws using the name of the group not that of the ws in the group.

2023-11-10 16:20 UTC, adriazalvarez commented
I'll investigate.
________________________________
From: SpencerHowells ***@***.***>
Sent: Friday, November 10, 2023 11:11 AM
To: mantidproject/mantid ***@***.***>
Cc: Diaz Alvarez, Adrian (STFC,RAL,ISIS) ***@***.***>; Mention ***@***.***>
Subject: Re: [mantidproject/mantid] Fixes Crash in ApplyAbsorptionCorrections if Corrections file incomplete (PR #36391)


@adriazalvarez<https://github.com/adriazalvarez> I think it's a problem with the Load algorithm. To test I did a Load file command. It created a ws using the name of the group not that of the ws in the group.

—
Reply to this email directly, view it on GitHub<https://github.com/mantidproject/mantid/pull/36391#issuecomment-1805529911>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCZ6OE7R3SSK5EQR7QVCP4DYDYDWXAVCNFSM6AAAAAA7FAIOZOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBVGUZDSOJRGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-13 14:36 UTC, SpencerHowells commented
@adriazalvarez In my last comment I should have been clearer in that it ctreates a single ws (not group) with change of name.

2023-11-14 15:57 UTC, robertapplin requested changes
Good stuff, the crash no longer happens, and there is a warning message that describes the problem! Just need to add a release note to this PR then I'll be happy to approve

2023-11-15 09:11 UTC, robertapplin approved these changes
Nice clean changes 👍  The other bug mentioned by Spencer is recorded separately in #36410

2023-11-15 11:00 UTC, merged