Unsquish widgets on the Indirect/Inelastic GUI's
mantidproject/mantid pull request #36445
Opened 2023-11-21 16:00 UTC by robertapplin

### Description of work

Fixes #36382

### To test:

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2023-11-29 16:56 UTC, MohamedAlmaki reviewed
Thanks for the changes, I've noticed this problem for a while. 

There is a problem in some tabs where the fields get squashed when you decrease the height of the tab, for example:
![image](https://github.com/mantidproject/mantid/assets/44416400/b1c00afa-e5da-4a33-b6f4-0dfe72f20ac9)

2023-11-30 10:53 UTC, robertapplin commented
> Thanks for the changes, I've noticed this problem for a while.
> 
> There is a problem in some tabs where the fields get squashed when you decrease the height of the tab

Good spot, this should be fixed in the latest commit

2023-11-30 17:43 UTC, MohamedAlmaki commented
Unassinging myself because I will be on leave until the next month

2023-12-06 17:08 UTC, cailafinn requested changes
Looks good, just typos in the release notes.

2023-12-06 17:08 UTC, cailafinn commented on docs/source/release/v6.9.0/Inelastic/Bugfixes/36382.rst
> +- A bug where the ``Run`` and ``Ouput Options`` appeared squished on Inelastic interfaces has been fixed.
```suggestion
- A bug where the ``Run`` and ``Output Options`` appeared squished on Inelastic interfaces has been fixed.
```

2023-12-11 13:27 UTC, cailafinn approved these changes
Looks good to me. Tested on macOS with a Retina Screen (~2k).

2023-12-11 14:13 UTC, merged