Abins: support frozen atoms in GAUSSIAN calculations
mantidproject/mantid pull request #36741
Opened 2024-01-25 16:43 UTC by ajjackson

### Description of work

#### Summary of work
Allow Abins to import GAUSSIAN data with frozen atoms. This currently breaks an assumption in the parser and results in an IndexError.

#### Purpose of work

Researchers may choose to freeze the positions of some atoms when calculating the vibrational spectrum with GAUSSIAN. This speed up the calculation and may enable study of larger systems or unstable conformations. AbINS already supports similar data from VASP ("selective dynamics") but currently the equivalent output from GAUSSIAN creates puzzling IndexErrors.

*There is no associated issue.*

**Report to:** Sanghamitra Mukhopadhyay

#### Further detail of work
Currently the parser reads the (full) atomic structure in one part of the file and notes the number of atoms. Later it reads the displacement information, but the number of rows may be smaller than expected as frozen atoms are omitted.

Instead, we now use the indices from the displacement data to filter down to the "active" atoms. For the incoherent inelastic scattering spectrum calculation in Abins, it is a valid
approach to simply pretend the frozen atoms don't exist and perform the rest of the calculation without them. For coherent scattering this approach will be invalid, and when explicit coherent scattering is added to Abins in future we may need to identify such cases and either warn or refuse to run them.

### To test:

The first commit on this branch adds a test that reproduces the error; subsequent commits should fix the test and add support for such files.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-01-29 10:19 UTC, ajjackson commented
Looks good, we are getting the expected failure in CI before implementing the fix:

```
ERROR: test_gaussian_5 (AbinsLoadGAUSSIANTest.AbinsLoadGAUSSIANTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/Abins/AbinsLoadGAUSSIANTest.py", line 57, in test_gaussian_5
    self.check(name=self._gaussian_system5, loader=abins.input.GAUSSIANLoader)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/tester.py", line 192, in check
    data = self._read_ab_initio(loader=loader, filename=name, extension=extension, **loader_kwargs)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/tester.py", line 227, in _read_ab_initio
    data = self._get_reader_data(ab_initio_reader)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/tester.py", line 240, in _get_reader_data
    abins_type_data = ab_initio_reader.read_vibrational_or_phonon_data()
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/gaussianloader.py", line 55, in read_vibrational_or_phonon_data
    self._read_modes(file_obj=gaussian_file, data=data)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/gaussianloader.py", line 126, in _read_modes
    self._read_atomic_disp_block(file_obj=file_obj, disp=atomic_disp)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/abins/input/gaussianloader.py", line 186, in _read_atomic_disp_block
    disp[self._num_read_freq + f, num_atom, 0] = complex(float(l[2 + 3 * f]), 0)
IndexError: index 21 is out of bounds for axis 0 with size 21

----------------------------------------------------------------------
Ran 5 tests in 1.723s

FAILED (errors=1)
```

Note that this is an IndexError related to processing the data; it is not (yet!) complaining about the lack of output reference data.

2024-01-29 13:33 UTC, ajjackson commented
Fix is implemented, test failure expected due to missing reference data.

2024-01-29 15:06 UTC, ajjackson commented
Note that a "shortcut" path is currently commented out from `_remove_frozen_atoms`. This is a sanity check: if the function works as expected, tests should pass without the shortcut. I will then activate this code: hopefully the tests will still pass, and the code will run a tiny bit faster for large systems.

```python
    @staticmethod
    def _remove_frozen_atoms(*, active_atoms: List[int], data: dict) -> None:
        """Modify data in-place, removing atoms that are missing from active_atoms and re-indexing"""

        # Do nothing if there are no frozen atoms
        # if len(active_atoms) == len(data["atoms"]):
        #     return None

        ...
```

2024-02-29 14:59 UTC, robertapplin requested changes

2024-02-29 14:59 UTC, robertapplin commented on docs/source/release/v6.10.0/Framework/Algorithms/36741.rst
I think this release note is causing some of the PR check failures because it needs to be in one of the subfolders, either Bugfixes or NewFeatures

2024-03-05 10:31 UTC, robertapplin approved these changes
The code changes are clean, and I am satisfied the added tests have covered the new use case 👍

2024-03-05 10:54 UTC, merged