Add check if sample details exists before applying absorption correction in diffraction script
mantidproject/mantid pull request #36809
Opened 2024-02-05 15:32 UTC by MohamedAlmaki

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-02-27 15:41 UTC, warunawickramasingha commented
I followed the same steps on a Windows machine and at step 2, I am getting an Attribute error rather than a Value error like below. 

![image](https://github.com/mantidproject/mantid/assets/142818102/58550148-7ffb-40be-869f-eef0bb28227d)

2024-06-11 09:12 UTC, warunawickramasingha requested changes
Can you please check the test failure whether they are related? Thanks!

2024-06-13 12:34 UTC, sf1919 commented
@warunawickramasingha this should be ready to review again - the last test failures were not associated with this PR and have been fixed.

2024-06-13 15:17 UTC, warunawickramasingha approved these changes
Thanks for the changes. Code looks nice and I ran the scripts provided for testing and it worked exactly as described.

Happy to approve!

2024-06-13 15:28 UTC, merged