Cleanup SANS release notes
mantidproject/mantid pull request #36828
Opened 2024-02-07 16:06 UTC by backmari

### Description of work

This PR does some cleanup for the SANS release notes so they are ready for the release of Mantid v6.9.

### To test:

Read through the SANS release notes to make sure they make sense/no typos.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-02-12 11:53 UTC, robertapplin requested changes
Thanks for the changes, looks really good - only had a few picky suggestions! @rbauststfc @cailafinn @jclarkeSTFC is there anything you want  to highlight with an image in these release notes?

2024-02-12 11:53 UTC, robertapplin commented on docs/source/release/v6.9.0/sans.rst
>    :ref:`ISIS SANS GUI <ISIS_Sans_interface_contents>`
```suggestion
  :ref:`ISIS SANS GUI <ISIS_Sans_interface_contents>`.
```

2024-02-12 11:53 UTC, robertapplin commented on docs/source/release/v6.9.0/sans.rst
>    location in the ISIS SANS GUI.
Do you think we should link to the ISIS SANS GUI here?

2024-02-12 12:37 UTC, cailafinn commented
> Thanks for the changes, looks really good - only had a few picky suggestions! @rbauststfc @cailafinn @jclarkeSTFC is there anything you want to highlight with an image in these release notes?

Improvements to the beam centre finder:
![image](https://github.com/mantidproject/mantid/assets/47181718/49b65b16-09e0-43ea-98d3-06cb7718e854)

CanSAS1D now disabled when 2D reduction is selected:

![image](https://github.com/mantidproject/mantid/assets/47181718/af0e8c2d-1d39-4d14-b015-0d5a35c148d1)

2024-02-13 09:07 UTC, robertapplin approved these changes
Looks good, the links are working and the images are clear 👍

2024-02-13 09:10 UTC, merged