Create MultiFunctionTemplateView and MultiFunctionTemplatePresenter
mantidproject/mantid pull request #36962
Opened 2024-03-04 16:34 UTC by robertapplin

### Description of work
This PR creates two generic classes, `MultiFunctionTemplateView` and `MultiFunctionTemplatePresenter`, that can replace the `ConvFunctionTemplateView` and `ConvTemplatePresenter`.

The future plan is to use these two classes for the IqtTab instead of `IqtFunctionTemplateView` and `IqtTemplatePresenter`. This will make it easier to change the StretchedExp checkbox in this tab to a combobox.

Before I can do this, I need to create a `MultiFunctionTemplateModel` as outlined in this next issue #36964

Fixes #36928

### To test:
Code review

Follow the testing instructions here
https://developer.mantidproject.org/Testing/Inelastic/DataAnalysisTests.html

*This does not require release notes* because **there are no functional changes**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-03-11 13:23 UTC, cailafinn requested changes
Just a couple of code comments/questions. Functionally works really well.

2024-03-11 13:23 UTC, cailafinn commented on qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/MultiFunctionTemplateView.cpp
> +  }
Could this just be a `std::for_each`?

2024-03-11 14:23 UTC, robertapplin commented on qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/IqtFunctionModel.cpp
> +}
Yes, this is to override an existing pure virtual function. This is likely to change in the next upcoming PR which will refactor a lot of the model code

2024-03-12 14:48 UTC, cailafinn approved these changes
Found an issue while testing but it's not related to this, so I'm happy to approve. 

Unrelated (it's on main) crash when loading invalid data:
1. Produce an Iqt workspace from `Data Manipulation` but use the `irs26176_graphite002_red` file in both boxes
2. Load the Iqt workspace into the `Data Analysis` GUI
3. Change the number of exponentials to 1
4. Crash.

2024-03-12 15:26 UTC, robertapplin commented
> Found an issue while testing but it's not related to this, so I'm happy to approve.
> 
> Unrelated (it's on main) crash when loading invalid data:
> 
> 1. Produce an Iqt workspace from `Data Manipulation` but use the `irs26176_graphite002_red` file in both boxes
> 2. Load the Iqt workspace into the `Data Analysis` GUI
> 3. Change the number of exponentials to 1
> 4. Crash.

Thanks for finding this! I have opened an issue here #37004

2024-03-12 16:44 UTC, merged