Add new integration algorithm for single-crystal Bragg peaks
mantidproject/mantid pull request #37103
Opened 2024-04-02 17:42 UTC by RichardWaiteSTFC

### Description of work
Add new integration algorithm for single-crystal Bragg peaks adapted and extended from an algorithm in SXD2001 [1].
It uses scipy.minimize to fit peaks in adjacent pixels until the I/sigma ratio drop below some threshold - not scipy.minimize is used because mantid fitting currently does not perform well for this type of function - in principle it should be straightforward to use the mantid fitting at a later date.

[1] Gutmann, M. J. (2005). SXD2001. ISIS Facility, Rutherford Appleton Laboratory, Oxfordshire, England.

Fixes #33629

**Report to:** Matthias Gutmann (SXD)

### To test:

(1) Run this script (maybe delete a few rows/peaks from the table if it takes too long)
```
Load(Filename='/archive/ndxsxd/Instrument/data/cycle_10_3/SXD23767.raw', OutputWorkspace='SXD23767')
FindSXPeaksConvolve(InputWorkspace='SXD23767', PeaksWorkspace='peaks_out', GetNBinsFromBackToBackParams=True, ThresholdIoverSigma=20)
IntegratePeaks1DProfile(InputWorkspace='SXD23767', PeaksWorkspace='peaks_out', OutputWorkspace='peaks_int_poisson', GetNBinsFromBackToBackParams=True, NFWHM=6, CostFunction='Poisson', FixPeakParameters='A', FractionalChangeDSpacing=0.02, OutputFile='/mnt/babylon/Public/RWaite/SXD23767_1D_profile_poisson.pdf')
IntegratePeaks1DProfile(InputWorkspace='SXD23767', PeaksWorkspace='peaks_out', OutputWorkspace='peaks_int', GetNBinsFromBackToBackParams=True, NFWHM=6, CostFunction='RSq', FixPeakParameters='A', FractionalChangeDSpacing=0.02, OutputFile='/mnt/babylon/Public/RWaite/SXD23767_1D_profile_Rsq.pdf')
```
(2) Check the output pdf (it should have a couple of plots per peak)
![image](https://github.com/mantidproject/mantid/assets/55979119/cfa93b0c-37d5-41db-b9d6-c0362557623e)

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-04-19 15:40 UTC, robertapplin requested changes
Looks good, still need to test. Spotted a few typos but other than that the code is neatly divided into functions where possible :)

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/mantid/api/src/Exports/IPeakFunction.cpp
> +      .def("setCentre", &IPeakFunction::setCentre, arg("self"), "Sets setCentre of the peak function.");
```suggestion
      .def("setCentre", &IPeakFunction::setCentre, arg("self"), "Sets the centre of the peak function.");
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
> +                    istart = -iy_start  # chop of ii elements at the begnining of the kernel along this dimension
```suggestion
                    istart = -iy_start  # chop of ii elements at the beginning of the kernel along this dimension
```

2024-04-19 15:40 UTC, robertapplin commented on docs/source/algorithms/IntegratePeaks1DProfile-v1.rst
> +The algorithm proceeds by fitting a ``PEakFunction`` and ``BackgroundFunction`` to the TOF spectrum of individual
```suggestion
The algorithm proceeds by fitting a ``PeakFunction`` and ``BackgroundFunction`` to the TOF spectrum of individual
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            doc="The output PeaksWorkspace will be a copy of the input PeaksWorkspace with the" " integrated intensities.",
```suggestion
            doc="The output PeaksWorkspace will be a copy of the input PeaksWorkspace with the integrated intensities.",
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            doc="Peak parameters to fix in the fits (reccommend fixing A for back-to-back exponential based functions).",
```suggestion
            doc="Peak parameters to fix in the fits (recommend fixing A for back-to-back exponential based functions).",
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            doc="Background funtion to fit.",
```suggestion
            doc="Background function to fit.",
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            "which the integrated intensity is a parameter. If Summation then the error will be the quadratue "
```suggestion
            "which the integrated intensity is a parameter. If Summation then the error will be the quadrature "
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            "IoverSigmaThreshold",
This is picky, would it be better to capitalise the O so it uses camel case?

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            alg.setProperty(prop, value)
I think this can be simplified
```suggestion
        alg.setProperties(kwargs)
```

2024-04-19 15:40 UTC, robertapplin commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +        self.ifix_final = None
Would there be any benefit adding type hints to these member variables?

2024-05-01 08:34 UTC, RichardWaiteSTFC commented on Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
> +            alg.setProperty(prop, value)
Thanks - I didn't know about this!

2024-05-01 10:26 UTC, robertapplin approved these changes
Thanks for the changes! Code looks good and is working as expected according to the test instructions. Happy to approve!
![image](https://github.com/mantidproject/mantid/assets/40830825/55cd504f-8096-447d-9c96-5a542ef9dac6)

2024-05-01 14:30 UTC, merged