Catch invalid argument instead of run time error for getEFixed
mantidproject/mantid pull request #37101
Opened 2024-04-02 15:43 UTC by SilkeSchomann

### Description of work

#### Summary of work

Fixes #[36988](https://github.com/mantidproject/mantid/issues/36988)

**Report to:** @mducle 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-04-03 14:53 UTC, adriazalvarez requested changes
Tested with LET data. It is possible to create a detector table with no crashes. 
I would suggest that perhaps it should be good to add a unit test against this exception (invalid argument)?

2024-04-04 15:29 UTC, adriazalvarez approved these changes, later dismissed
Thanks for the changes!

2024-04-05 06:02 UTC, thomashampson requested changes

2024-04-05 06:02 UTC, thomashampson commented on Framework/Algorithms/test/CreateDetectorTableTest.h
> +    TS_ASSERT_THROWS_ANYTHING(inputWS->getEFixed(detector));
I don't think this is testing your bug fix, it would still pass without the code changes.

2024-04-05 14:43 UTC, adriazalvarez approved these changes
Thanks for fixing the test. I think it should be good now.

2024-04-09 13:31 UTC, thomashampson approved these changes
Fixes a bug reported by user.

2024-04-09 13:31 UTC, merged