Refactor Inelastic QENS FitTab
mantidproject/mantid pull request #37193
Opened 2024-04-22 08:12 UTC by robertapplin

### Description of work
This PR does some refactoring of the FitTab of Inelastic QENS Fitting interface. It reduces the amount of code in this FitTab by removing unused code, and moving some of the code to more testable locations, such as the FittingModel of some of the Presenters.

Part of #36390

### To test:

*This does not require release notes* because **it is an internal change**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-04-29 09:42 UTC, adriazalvarez requested changes
Thanks for this neat refactoring. 
I have added couple of comments. 
Additionally, I have found that when `Run` button is pressed from any of the QENS tab with a fit function selected, an empty warning dialog appears: 
![image](https://github.com/mantidproject/mantid/assets/146007827/37ebc167-03a2-4d89-891e-f41b49082520)
Can you check if you get the same?

2024-04-29 09:42 UTC, adriazalvarez commented on qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.cpp
> +  QList<FunctionModelDataset> datasets;
Does not have to be in this PR. But `FunctionModelDataset` class could be refactored with  std strings.

2024-04-29 09:42 UTC, adriazalvarez commented on qt/scientific_interfaces/Inelastic/QENSFitting/FitDataView.cpp
> +    : QTabWidget(parent), m_uiForm(new Ui::FitDataView), m_tabName(tabName) {
Perhaps we can use some `QWidget` properties (like `windowTitle`) to store the tab name instead of a private member?

2024-04-29 11:27 UTC, robertapplin commented
Thanks for spotting that weird warning, not sure how I missed it!

2024-04-30 06:55 UTC, adriazalvarez commented
Thanks for the changes. It looks good to me.

2024-04-30 06:55 UTC, adriazalvarez approved these changes

2024-04-30 07:46 UTC, merged