Support saving a multi-dataset ORSO file from the ISIS Reflectometry GUI
mantidproject/mantid pull request #37268
Opened 2024-05-03 12:07 UTC by rbauststfc

### Description of work

#### Summary of work

Description and testing instructions to be added

Fixes #36396. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-05-07 12:18 UTC, cailafinn requested changes
Functionally, this works really well. Followed the instructions (with the Sample Data refl files as I didn't seem to have access to the Journal during testing). All working well, files were saved into the correct locations with the right prefixes and suffixes. Automatic saving worked well. Correct checkboxes disabled when settings adjusted. 

Built the docs, all looking good formatting and grammar-wise. 

Just have a few code notes. As discussed, as the functionality is good, happy for certain elements to be fixed in a maintenance issue to avoid delay. The build warning probably does need to be fixed though as Jenkins will start reporting those as failures soon.

2024-05-07 12:18 UTC, cailafinn commented on docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
> +|                               | ``Additional columns (includes Q resolution`` option |
```suggestion
|                               | ``Additional columns (includes Q resolution)`` option|
```
Missing a bracket here

2024-05-07 13:06 UTC, rbauststfc commented on qt/scientific_interfaces/ISISReflectometry/GUI/Save/AsciiSaver.cpp
> +    saveToSingleFile(workspaceNames, saveDirectory, logParameters, fileFormat);
Thanks for this thought - on this one, would you be happy if I left it as it is? I'm a fan of returning early in situations where you've checked a condition and then there's no point continuing with the purpose of the method at all if that condition doesn't hold. When you're checking a condition to see if you should achieve the method's purpose in one way or another, though, then I personally prefer an if/else, as I find it clearer when reading to understand the intention of the code. I think my preference would be that there's flexibility on code style for this particular type of case, if that works for you.

2024-05-07 13:09 UTC, rbauststfc commented on qt/scientific_interfaces/ISISReflectometry/GUI/Save/AsciiSaver.cpp
> +  const auto ws = workspace(workspaceNames.front());
Agree, this is definitely maintenance as there's quite a bit of legacy code in here. I'll open an issue.

2024-05-07 16:22 UTC, cailafinn approved these changes
Functionally working well for the sample data. Produces multi-workspaces properly when auto-saving. 
Code all looking good to me now. East const/const west issue moved to maintenance. 
Docs looking good when built.

2024-05-07 18:22 UTC, sf1919 commented
@mantidproject/gatekeepers Checked the warnings and they are all unrelated to this PR so please go ahead and gatekeep.

2024-05-08 07:32 UTC, rbauststfc commented
@mantidproject/gatekeepers it would be great if this one could be picked up by a gatekeeper, as it's blocking another piece of work that I'd like to put through review in time for code-freeze. Thanks!

2024-05-08 07:58 UTC, merged