WIP: refactor Abins, replace SData with Euphonic data structures
mantidproject/mantid pull request #37350
Opened 2024-05-13 13:57 UTC by ajjackson

### Description of work

#### Summary of work
Remove `abins.sdata.SData`, use classes from `euphonic.spectra` instead

#### Purpose of work
Abins currently manages collections of simulated spectra with an "SData" class. This assumes that the data will be structured in a tree with heirarchy atom -> quantum-order. This is not flexible enough to deal with coherent scattering, which might not be decomposable by atom.

Euphonic is an existing dependency and uses Spectrum1D, Spectrum2D and Spectrum1DCollection classes to manage spectra including arbitrary metadata. Effectively this is a flat table structure, amenable to "query" or "pipeline" workflows. This seems to be an appropriate tool, so here we extend that to add the missing Spectrum2DCollection and work towards using those natively in Abins.

#### Further detail of work
- [ ] Add a method to SData to produce an equivalent SpectrumNDCollection object
- [ ] Update abins to use these objects for all "output" management (i.e. summing relevant subsets and creating workspaces)
- [ ] Update abins to simulate data directly into a SpectrumNDCollection object
- [ ] Delete SData class and related unit tests
- [ ] Move patches and extensions to Euphonic classes upstream into a new euphonic release
- [ ] Remove Euphonic subclasses from mantid, update Euphonic dependency version

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-06-17 14:34 UTC, ajjackson commented
This initially led to some severe performance regressions, due to the relatively high overhead of iterating over a Euphonic Spectrum1DCollection/Spectrum2DCollection object, which performs unit conversions while spawning new objects. Some efficiency tweaks can be made to the Euphonic objects, but mostly we can recover the performance by iterating in other ways (over the metadata and underlying arrays).

In addition, we can start to introduce `multiprocessing`-based parallelism, which plays nicely with loops over "flat" tables.

2024-06-21 15:37 UTC, ajjackson commented
Very strange test failure there: something is going wrong with the Pychop call inside a multiprocessing starmap, but only for OSX and Windows. I wonder if there is some OS-dependent namespace hackery that runs into issues because both abins and Pychop have an Instrument class 🤔

2024-08-21 13:52 UTC, sf1919 commented
Apologies... wrong PR

2025-01-16 16:19 UTC, sf1919 commented
@ajjackson is this PR still one to be worked on?

2025-01-16 16:37 UTC, ajjackson commented
Yes it is still in progress. Effort moved upstream to Euphonic for a bit and will be back here shortly (with many deleted lines of code.)

2025-01-28 16:15 UTC, ajjackson commented
Oof, that was a big rebase

2025-03-12 11:35 UTC, ajjackson commented
Hurrah, we now have a substantial net reduction in lines-of-code 🎉

2025-05-14 16:38 UTC, ajjackson commented
I have done a few large benchmark calculations now:
- for this paper we ran Abins on supercells of ~1500 atoms https://arxiv.org/abs/2504.19352 ; this branch and `main` each took around 90 mins for calculations
- in a separate benchmark using some NaCl force constants from the Euphonic training set (i.e. a small unit cell) with a large q-space sampling  of ~97,000 q-points, both branches took 6.4 min to run

So I am confident that there is not a significant negative performance impact. (There _is_ certainly scope to improve the performance in those cases by better use of parallelism, though!)

2025-05-20 09:21 UTC, ajjackson commented
I'm sorry that this diff is a bit tricky to navigate. The github view does rather too much interweaving of blocks! I'll try to break down what is going on file-by-file to help with review.

At a high level: Abins calculates many individual contributions to the inelastic phonon scattering, by atom and by quantum order. These have been stored in a class "SData" which is essentially a nested dict. However the design of the dict was insufficiently flexible to support future functionality: it assumes that we can always organise the contributions by Atom and by individual quantum orders, and that no other divisions will be worth keeping track of. Already an "SDataByAngle" collection was added to the scheme, complicating things.

Here we replace that with data structures that are already maintained and tested in Euphonic: Spectrum1DCollection and Spectrum2DCollection, which are collections of Spectrum1D and Spectrum2D. These are "flat" collections which allow contributions to be managed with arbitrary metadata of the form `dict[str, str|int]`. There is no longer a special organisation for angles: this is just another bit of metadata in the "table". But there is a stricter separation of 1D vs 2D into separate classes: SData uses the same class for either an one must figure out which is being used from the data shape or presence of q bins.

Unlike Abins, which works in Angstrom and wavenumber internally, Euphonic uses the package Pint to attach units to data and facilitate conversion between them. So wherever we see a Quantity, this represents a scalar or numpy array with associated unit. They can be created with the Quantity() constructor or by multiplying with a unit produced by `ureg`.

The most significant changes in the PR are:
- Entirely remove the existing SData class from *sdata.py*
- Create/rework a few functions in *sdata.py* that provide Abins-specific functionality to the Euphonic classes
- Rework the various iterations and construction of data in *spowdersemiempiricalcalculator.py* (the actual intensity calculation), *abinsalgorithm.py* (a common base class to Abins and Abins2D algorithms), and the *Abins.py*, *Abins2D.py* and *abins2.py* algorithm implementations.
- By flattening the iteration it became simpler to implement parallelism; this is implemented for broadening and autoconvolution stages.

The good news is that (I think) the new iteration schemes look a bit nicer.

File-by-file notes:
- Abins.py/Abins2D.py/abins2.py
  - `sdata` is renamed to `spectra` to allude to underlying type
- **Abins2BasicTest.py**
  - Restrict the number of quantum orders in test calculations; these were running slowly and it was inconsistent with the Abins-v1 tests
- conda_build_config.yaml
  - Bump the required Euphonic version to get support for Spectrum2DCollection and improvements to all spectra
- abinsalgorithm.py
  - **clean up some logic for early exit**
  - Rework get_masses_table to use new data structure
  - Rework create_workspaces to use new data structure
- **instrument.py, pychop.py**
  - factor out Pychop-fitting step so that it can be triggered from outside the `calculate_sigma` step. This is to support the parallel broadening implementation.
- parameters.py
  - the existing `threads=4` parameter was not actually used anywhere, and is not a particularly good default. Instead, define a chunk size and detect available CPUs automatically.
- sdata.py
  - remove SData, SDataByAngle
  - replace missing functionality with functions operating on Spectrum objects
- spowdersemiempiricalcalculator
  - use spectrum classes instead of SData
  - simplify case where fewer quantum orders are requested than previous calculation: just load all of them! When workspaces are constructed we will only build/fill them for the requested orders.
  - implement parallel broadening with multiprocessing

The test suite has been changed as little as possible to be confident that the results are unaffected. This means that the reference data is still in a format related to the old data types, and converted on the fly to something that can be compared more directly. When the dust has settled, the tests could be cleaned up a bit by converting the relevant data to Euphonic JSON formats.

In **bold** I have highlighted a few of the changes that are not strongly coupled to the spectrum work. If it helps I could cherry-pick these into a separate PR which can be quickly reviewed and slightly reduce the main diff?

2025-05-20 10:16 UTC, sf1919 commented
The failing test looks suspicisouly similar to the pydantic failure - #39131

2025-05-20 10:26 UTC, ajjackson commented
The new pin was just merged so I'll try a rebase.

2025-05-20 14:09 UTC, ajjackson commented
Here is a PR with the self-contained changes, if that helps tidy up the diff! https://github.com/mantidproject/mantid/pull/39343

2025-06-05 09:21 UTC, adriazalvarez requested changes
Thanks for this change.  It seems the euphonic data structures blend very well with abins, as stripping most of `sdata` makes the code base more easy to read. 
All tests are passing, I have only a few small comments.

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/abinsalgorithm.py
> +        """Iterate over spectrum metadata as though all data were in line_data"""
Interesting way of dict comprehending, but (at least me) haven't seen this often, and since it is manipulating metadata from euphonic, could this comment elaborate slightly more ?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/sdata.py
> +def check_thresholds(
A `:param` for items seems to be missing in the docstring here

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/sdata.py
> +    spectra._z_data[:, mask] = float("nan")
Do you know why is this ? 
Could something like `spectra.z_data.magnitude[:,mask] = float("nan")` work?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/sdata.py
> +    fundamentals = atom_spectra[0]._y_data
maybe related to previous question, but it is possible to not call here the protected data? (same goes for the unit)

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/sdata.py
> +    for order in range(highest_initial_order, max_order):
Is it guaranteed max_order > highest_initial_order ? Does it need some validation?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/spowdersemiempiricalcalculator.py
> +            one_angle_spectra.metadata["angle"] = str(angle)
Does this cast to str needs any formatting?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/spowdersemiempiricalcalculator.py
>          Calculate 1-D S(q,w) using geometry-constrained energy-q relationships
we could still comment on the return type here ?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/spowdersemiempiricalcalculator.py
>          if len(q2.shape) == 1:
There are few checks of 1D/2D dimensionality in SPowderEmpiricalCalculator, could we make `is2d` a data attribute to do this at once and use it where is needed? (maybe is unnecesary, you don't need to change this if you don't feel strongly about it)

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/spowdersemiempiricalcalculator.py
> +            with Pool(n_threads) as p:
Are we expecting this to hang at some point ? Do we need error handling ?

2025-06-05 09:21 UTC, adriazalvarez commented on scripts/abins/spowdersemiempiricalcalculator.py
> +                    x_data=(self._q_bins * ureg("1/angstrom")),
I think at the beginning of the class the units are defined ? 
(q_unit, freq_unit, s_unit), could we use those in here?
Or Maybe is better to define the units in the parameters or constant files ?

2025-06-05 09:24 UTC, adriazalvarez commented
Other comment, not related to this PR. I think the euphonic docs don't have an entry for `Spectrum2DCollection`, it's easy to guess what it does, but maybe for completion you may consider adding it at some point.

2025-06-05 09:40 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +        """Iterate over spectrum metadata as though all data were in line_data"""
Will take a look, it may be that an equivalent function exists in euphonic now anyway.

This part:
```python
            for key in metadata.keys()
            - {
                "line_data",
            }
```

is an example of `black` formatting obscuring the meaning!

`for key in (metadata.keys() - {"line_data",})`

makes it clearer what we are really iterating over: a difference of sets.

2025-06-05 10:13 UTC, ajjackson commented
Thanks @adriazalvarez for many good suggestions, I'll start working through them.

2025-06-06 10:18 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +        """Iterate over spectrum metadata as though all data were in line_data"""
Yes, this is now upstream as a method on SpectrumCollections so we can just delete it 😄

2025-06-06 11:19 UTC, ajjackson commented on scripts/abins/sdata.py
> +    spectra._z_data[:, mask] = float("nan")
I think this was fixed upstream and can be avoided now.

2025-06-06 11:20 UTC, ajjackson commented on scripts/abins/sdata.py
> +    fundamentals = atom_spectra[0]._y_data
I have reworked this method to take Spectrum collections instead of lists of individual spectrum. This lets us use some nice public methods for everything.

2025-06-06 12:50 UTC, ajjackson commented on scripts/abins/sdata.py
> +    for order in range(highest_initial_order, max_order):
It can only be done by setting abins.parameters.autoconvolution.max_order to 1. That would be a very silly thing to do, but let's add validation so that the function scope is clearer.

2025-06-06 13:05 UTC, ajjackson commented on scripts/abins/spowdersemiempiricalcalculator.py
> +            one_angle_spectra.metadata["angle"] = str(angle)
These strings are not really user-facing and it is important that different angles do not collide to the same key; so they should use the highest possible precision. It looks like python defaults to the appropriate 16 digits for `float`, but wouldn't hurt to force it.

(Here's a fun little test: the result isn't always the same because the number can end in zeros.)
```
In [24]: print(f"Random number: {(x := random.random())}")
Random number: 0.7511003656171013

In [25]: for precision in range(10, 18):
    ...:     print(precision, x == float(f"{{:.{precision}}}".format(x)))
    ...:
10 False
11 False
12 False
13 False
14 False
15 False
16 True
17 True
```

2025-06-06 13:48 UTC, ajjackson commented on scripts/abins/spowdersemiempiricalcalculator.py
> +            with Pool(n_threads) as p:
What scenario do you have in mind? A timeout in case of process communication error? I don't know how reliably we can predict how long this operation should take, maybe with a bit of testing that can be done.

2025-06-06 13:48 UTC, ajjackson commented on scripts/abins/spowdersemiempiricalcalculator.py
>          if len(q2.shape) == 1:
Good idea!

2025-06-06 13:56 UTC, ajjackson commented on scripts/abins/spowdersemiempiricalcalculator.py
> +                    x_data=(self._q_bins * ureg("1/angstrom")),
Good catch! For now it doesn't make much difference as this is the only implementation in Abins that matters. It could make sense to centralise in abins.constants later. I'd be reluctant to define them in abins.parameters as this invites more fiddling and it's not guaranteed all the conversions will be done correctly. (In Euphonic they would be...)

2025-06-06 13:58 UTC, ajjackson commented
> Other comment, not related to this PR. I think the euphonic docs don't have an entry for `Spectrum2DCollection`, it's easy to guess what it does, but maybe for completion you may consider adding it at some point.

Cheers, opening a Euphonic Issue for this https://github.com/pace-neutrons/Euphonic/issues/413

2025-06-10 08:10 UTC, adriazalvarez approved these changes, later dismissed
Thanks for the changes.

2025-06-10 08:27 UTC, ajjackson commented
Thanks for review, hope it wasn't too painful relative to size!

2025-06-16 15:10 UTC, cailafinn requested changes
Looking very good, just have a couple of questions before merge.

2025-06-16 15:10 UTC, cailafinn commented on scripts/abins/abinsalgorithm.py
> +        from abins.constants import ONE_DIMENSIONAL_INSTRUMENTS
Is there a reason for this only being imported at this point, rather than at the top of the file? Especially given some of the abins constants are already imported. There's a few of these throughout the changes, so just want to confirm.

2025-06-16 15:10 UTC, cailafinn commented on scripts/test/Abins/AbinsSDataTest.py
> -    def test_sdba_from_sdata_series_bad_inputs(self):
Just want to check, there seems to be a lot of tests removed. Are the cases they covered handled by other tests?

2025-06-16 15:15 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +        from abins.constants import ONE_DIMENSIONAL_INSTRUMENTS
No technical reason, just subjective tidiness which may have changed between iterations of refactoring! I could move it to the top if you like.

2025-06-16 15:18 UTC, ajjackson commented on scripts/test/Abins/AbinsSDataTest.py
> -    def test_sdba_from_sdata_series_bad_inputs(self):
They test classes which no longer exist in Mantid. The functionality was replaced by classes from Euphonic, which has 97% code coverage. (That doesn't mean things can't slip through, but it's a good start!)

2025-06-16 16:10 UTC, cailafinn commented on scripts/abins/abinsalgorithm.py
> +        from abins.constants import ONE_DIMENSIONAL_INSTRUMENTS
That's the standard for almost all the files in `mantid`, so that would be preferable. It just means any import errors get caught as early as possible

2025-06-16 16:11 UTC, cailafinn commented on scripts/test/Abins/AbinsSDataTest.py
> -    def test_sdba_from_sdata_series_bad_inputs(self):
Great, thanks!

2025-06-17 10:03 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +        from abins.constants import ONE_DIMENSIONAL_INSTRUMENTS
Ok, I have moved all the imports in abinsalgorithm.py to top-level.

In the process I noticed the sanity-check of cpu_count() seemed to be a bit broken and cleaned it up.

2025-06-17 14:17 UTC, cailafinn reviewed
Great, looks good to me now. Just wanted to check if this has any user-facing behaviour changes? If so, could we have a release note?

2025-06-17 14:21 UTC, ajjackson commented
It's not supposed to, unless they are importing things from the scripts directory and fiddling with advanced parameters. The performance profile will have slightly changed but I benchmarked this and it doesn't seem to be noticeable at this point.

Perhaps it is worth writing that there was a big refactor of the internal library for AbINS, as it could _in theory_ impact users who do clever things with external scripts that hook into AbINS. Most likely, I am the only one of those 😅

2025-06-17 14:30 UTC, cailafinn approved these changes

2025-06-17 14:31 UTC, merged