Fix OpenGL segmentation fault on Linux
mantidproject/mantid pull request #37437
Opened 2024-05-30 10:52 UTC by jclarkeSTFC

When drawing some instruments in full 3d (with OpenGL), putting all the draw commands for the instrument in one big list seems to cause a segmentation fault on certain versions of Linux, including the version used on IDAaaS. This changes `InstrumentRenderer` to draw each component of the instrument using a separate list.

#### Summary of work

- Draw each instrument component in a separate display list.
- Add a method that will give you the OpenGL version string (someone will thank me in the future).
- Split the picking and non-picking display lists into named member variables instead of using two indices.

Fixes #36220 

### To test:
See #36220, or what caused the original segmentation fault for me was to view full 3D for MAR11001 (on Rocky 8 IDAaaS and Ubuntu). Other instruments and files will need checking as well.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-05-30 15:15 UTC, jhaigh0 requested changes
One small thing.
I find it not so easy to ready, but I reckon that's mostly just because its complex in nature. I wonder if some comments explaining how it works would be helpful? I'll let other reviewers chime in, I don't mind either way.

2024-05-30 16:41 UTC, RichardWaiteSTFC commented
Tested this on MARI > Excitations Single Crystal (no GPU) and found no crash (started from terminal with `mantidworkbench`)

2024-06-04 13:27 UTC, jhaigh0 requested changes
A few minor suggestions, mostly to do with the older code, but looking pretty much there

2024-06-04 13:27 UTC, jhaigh0 commented on qt/widgets/instrumentview/src/InstrumentRendererClassic.cpp
> +  }
I know this has been copied from the old code so don't worry with fixing it now, but there's got to be a better way to do this 🙃 I think the component info class should have a way of retrieving the max index

2024-06-04 13:27 UTC, jhaigh0 commented on qt/widgets/instrumentview/src/InstrumentRendererMultiList.cpp
> +  }
There might be a simpler way to initialise these vectors
```
std::vector<T> myVector(length, repeatingElementOfTypeT);
```

2024-06-04 13:27 UTC, jhaigh0 commented on qt/widgets/instrumentview/src/InstrumentRendererMultiList.cpp
> +    return;
```suggestion
  if (std::none_of(visibleComps.cbegin(), visibleComps.cend()))
    return;
```

2024-06-04 13:27 UTC, jhaigh0 commented on qt/widgets/instrumentview/src/InstrumentRendererMultiList.cpp
> +  auto &useDisplayList = picking ? m_usePickingDisplayList : m_useNonPickingDisplayList;
Feels as if maybe these bools could be simplified? is it always either `m_usePickingDisplayList` or `m_useNonPickingDisplayList`? In that case could they be one bool? I might be misunderstanding.

2024-06-05 10:35 UTC, jhaigh0 approved these changes
We've had a test in IDAaaS now that they've added the config option to the local properties. Prevents the crash as intended.

2024-06-05 13:43 UTC, merged