37041 scrolling on plot when cursor is above legend will grab the legend
mantidproject/mantid pull request #37473
Opened 2024-06-05 10:39 UTC by yusufjimoh

### Description of work
The default behaviour in Matplotlib is that the legend gets grabbed 
when the cursor is over it during a plot scroll event.
To fix this issue, I set the legend's draggability to false during scrolling 
and re-enable it once the scrolling ends.

Fixes: #37041 

### To test:

### To test:
1. Create a plot
2. scroll the plot to zoom in/out, 
3. scroll when the cursor is above the legend
4. the cursor doesn't grab the legend

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-06-05 11:04 UTC, GuiMacielPereira requested changes
The commit history looks this confusing because it was cherry-picked from an older PR with merge conflicts.

Other than that I checked:

- Fix works as expected, `scroll_event` does not pick up legend anymore 
- Fix works on both MantidAxes and normal Matplotlib axes
- If legend draggable is `False`, `scroll_event` does not change it
- Unit test passing, also checked that it fails if a change is made in the code

The final thing to do is replace the current file for the release notes with the correct PR number `37473.rst` and add the line: `- Legend in plots is no longer accidentally picked up by a mouse scroll`

2024-06-12 10:44 UTC, jhaigh0 approved these changes
Looks like this is all good to go, happy to approve since Gui is away.
The only edge case I can see is if you pick up and move the legend and _then_ start scrolling, it will drop the legend. But I think that's fine.

2024-06-12 10:46 UTC, jhaigh0 commented
Only other thing to say is that if there is an issue related to the pr (#37041 for this one) then you should name your release note after that issue, its easier that way so you don't have to first make a PR. 
Its also fine to name it after the pr since the numbers are unique from each other, so don't worry about changing it.

2024-06-12 11:32 UTC, yusufjimoh commented
Okay Noted.

2024-06-17 07:55 UTC, GuiMacielPereira approved these changes
I am happy to approve as well, the final thing I would say for the **gatekeeper is to squash these commits**, because they were cherry-picked from another branch and as it is they are confusing to read.

2024-06-17 08:27 UTC, merged