Add instructions for fixing a merge conflict between protected branches
mantidproject/mantid pull request #37608
Opened 2024-06-25 11:27 UTC by robertapplin

### Description of work
This PR adds instructions for gatekeepers when fixing a merge conflict between protected branches (e.g. between `main` and `release-next`. The key is to make sure a PR is created to resolve the conflict, rather than pushing straight to `main`.

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-07-19 11:41 UTC, thomashampson requested changes
Instructions seem correct and are easy to follow. There is just a formatting issue caused by some missing code-block directives.

2024-07-19 11:41 UTC, thomashampson commented on dev-docs/source/Gatekeeping.rst
> +    origin  https://github.com/<username>/mantid.git (push)
Missing code-block directive
```suggestion
.. code-block:: bash

    $ git remote -v
    mantid  https://github.com/mantidproject/mantid.git (fetch)
    mantid  https://github.com/mantidproject/mantid.git (push)
    origin  https://github.com/<username>/mantid.git (fetch)
    origin  https://github.com/<username>/mantid.git (push)
```

2024-07-19 11:41 UTC, thomashampson commented on dev-docs/source/Gatekeeping.rst
> +    origin  https://github.com/mantidproject/mantid.git (push)
Missing code-block directive
```suggestion
.. code-block:: bash

    $ git remote -v
    origin  https://github.com/mantidproject/mantid.git (fetch)
    origin  https://github.com/mantidproject/mantid.git (push)
```

2024-07-19 14:49 UTC, thomashampson approved these changes
Clear instructions for resolving merge conflicts when e.g. merging release-next into main. I like the suggestion of using a PR rather than pushing directly to main.

2024-07-22 06:46 UTC, SilkeSchomann commented
> Clear instructions for resolving merge conflicts when e.g. merging release-next into main. I like the suggestion of using a PR rather than pushing directly to main.

Me too :-)

2024-07-22 06:51 UTC, merged