Move common Indirect/Inelastic widgets into new MantidQtWidgetsSpectroscopy library
mantidproject/mantid pull request #37664
Opened 2024-07-16 10:57 UTC by robertapplin

### Description of work

#### Summary of work

Fixes #37591

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-07-16 14:44 UTC, robertapplin commented
Building a windows conda package here:
https://builds.mantidproject.org/job/build_packages_from_branch/

2024-07-18 15:01 UTC, adriazalvarez requested changes
I have done a fresh build and installed through conda. It builts without errors and loads from conda without any warning. 
All interfaces are present, I have tested most of the tabs and everything seems to be working correctly. This must have been quite an strenuous effort on moving files, but it looks much better organized and we avoid problems we've had before with the overlap of mixed libraries between inelastic/indirect. 
I have spotted a problem with the corrections interface, and opened an issue: #37674 .

I'm almost certain that the issue is not related to this PR, but I'd like to ask you to double check that you get the same problem, then I'll approve gladly.

2024-07-19 07:47 UTC, robertapplin commented
> I'm almost certain that the issue is not related to this PR, but I'd like to ask you to double check that you get the same problem, then I'll approve gladly.

Thanks for finding this - yes I also get this, and I think fixing it separately is a good idea

2024-07-19 07:52 UTC, adriazalvarez approved these changes

2024-07-22 07:49 UTC, merged