Added Deprecation policy to Mantid documentation
mantidproject/mantid pull request #37718
Opened 2024-07-30 16:22 UTC by sf1919

- Added a new deprecation policy page to the user documentation. The draft policy was written at Mantid Developer Meeting 2023 and reviewed by Technical Working Group in July 2024.
- added a link to the page from the main user documentation index

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-07-31 12:31 UTC, peterfpeterson reviewed
Looking at the [governance](https://github.com/mantidproject/governance/) document, maybe we change "facilities" to "Mantid Steering Committee" (with link). Similar to deprecating unused algorithms, we should give a final approval to the steering committee. This is consistent with what we've been doing this last round.

2024-07-31 13:45 UTC, sf1919 commented on docs/source/deprecation.rst
> +- Algorithms that have not been used for 3 years or more. We will use Usage Data to determine this. For more information
See revised lines 27-28 below

2024-07-31 15:37 UTC, peterfpeterson approved these changes, later dismissed

2024-08-01 08:17 UTC, robertapplin requested changes

2024-08-01 08:17 UTC, robertapplin commented on docs/source/deprecation.rst
> +- Other Features covered by Usage Data that have not need used for 3 or more years
```suggestion
- Other Features covered by Usage Data that have not beed used for 3 or more years
```

2024-08-01 08:17 UTC, robertapplin commented on docs/source/deprecation.rst
> +make it clear that we are not longer supporting (i.e. no longer developing) the previous version(s). Although previous
```suggestion
make it clear that we are no longer supporting (i.e. no longer developing) the previous version(s). Although previous
```

2024-08-01 08:17 UTC, robertapplin commented on docs/source/deprecation.rst
> +versions will still be available and safe to use users will be encouraged to use more recent versions.
```suggestion
versions will still be available and safe to use, users will be encouraged to use more recent versions.
```

2024-08-05 09:27 UTC, sf1919 commented
I have updated the PR to take into account @robertapplin suggestions. I have also added a little bit about best practice for deprecating multiple algorithms/features as separate PRs.

@peterfpeterson Can you review again?

2024-08-05 12:37 UTC, peterfpeterson approved these changes

2024-08-07 08:02 UTC, robertapplin approved these changes

2024-08-07 08:02 UTC, merged