Inelastic Settings option to turn off Load Workspace History
mantidproject/mantid pull request #37751
Opened 2024-08-06 10:41 UTC by adriazalvarez

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-08-08 09:02 UTC, robertapplin requested changes
This is a really useful new feature, thanks for the implementation! Just spotted a few potential typos in the code

2024-08-08 12:34 UTC, robertapplin commented
This is working really well - loading on the QENS Fitting interface in particular is much faster when not loading history. I have tested on all Indirect/Inelastic interfaces and it is working as expected. Just one place where it may not be working is on the Indirect Simulations interface->MolDyn tab for the Resolution input. Do you see this too?

2024-08-09 07:39 UTC, adriazalvarez commented
You are right, the simulations interface was missing. Thanks for catching that up. I have added it now.

2024-08-09 08:00 UTC, robertapplin commented on qt/scientific_interfaces/Indirect/Simulation/SimulationTab.h
> +  virtual void setLoadHistory(bool doLoadHistory){UNUSED_ARG(doLoadHistory)};
```suggestion
  virtual void setLoadHistory(bool doLoadHistory) { UNUSED_ARG(doLoadHistory); }
```

2024-08-09 13:05 UTC, robertapplin approved these changes
This is a really nice addition to the Indirect/Inelastic settings. If users are finding it slow to load data into one of our interfaces, they now have the option to untick the "Load Workspace History" option. In some cases (such as on QENS Fitting), the time it takes to load certain datasets with this option is much reduced!

2024-08-14 08:22 UTC, rbauststfc commented
Just a quick question before merging this in, I didn't notice many changes/additions to tests in this PR. Are we happy that it's not possible/useful to add any more test coverage, for example where we have added new methods to a presenter (I know we can't do it for additions to the views)?

2024-08-14 11:19 UTC, adriazalvarez commented
Thanks for your suggestions. 
I don't think I can add much more test cases on the settings presenter regarding this setting.
The implementation of the settings is done on QObjects on interfaces which are not tested at this moment. 
If you agree, I think we can move forward with the merge.

2024-08-14 12:01 UTC, merged