Fix the calibration diagnostics plot issue
mantidproject/mantid pull request #37791
Opened 2024-08-12 19:41 UTC by Kvieta1990

### Description of work

#### Summary of work

With the calibration diagnostics tool, we are supposed to be able to generate a 2D plot showing the difference between the calibrated and engineering calibration constant, and also the masks will be shown as well.

However, seems that the new version of Mantid is killing the capability complaining something about the solid angle extraction from the instrument. Here we are fixing the issue by changing the way of extracting the solid angle.

### To test:

Use the following script,

```python
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

LoadDiffCal(
    InstrumentName="NOM",
    Filename="/SNS/snfs1/instruments/NOM/shared/CALIBRATION/autoreduce/NOMAD_196808_2023-08-14_shifter.h5"
)

fig, ax = diagnostics.difc_plot2d("_cal", instr_ws="_group",
                                  mask="_mask", vrange=(0, 5))
```

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-08-13 18:23 UTC, peterfpeterson requested changes
There are some mixed usage of detector id and workspace index that is, at minimum, confusing. Doing
```python
det = NOM_instr.getDetector(1000)
print(det.getID()
```
will point out the issue. I don't know if it matters for this particular case, but better variable names would help

Separate from this PR, somehow a bug got into place and we aren't exercising the python API for things quite correctly. The following seems like it should work
```python
samplePos = NOM_instr.spectrumInfo().samplePosition()
det = NOM_instr.getDetector(1000)
print(det.solidAngle(samplePos))
print(det.getTwoTheta(samplePos)) # bad position, but error is about function signature
```
It seems like this PR is working around these issues and we should create a defect for the python binding.

2024-08-13 18:23 UTC, peterfpeterson commented on scripts/Calibration/tofpd/diagnostics.py
> +        maximum_solid_angle = max(maximum_solid_angle, det_tmp.readY(det_id)[0])
The variable `det_id` here is actually a workspace index. It would add clarity to rename the variable.

2024-08-13 19:03 UTC, Kvieta1990 commented on scripts/Calibration/tofpd/diagnostics.py
> +    LoadEmptyInstrument(InstrumentName=instr_name, OutputWorkspace=f"{instr_name}_instr")
I guess my problem is how to get `instr_ws` into the `SolidAngle` algorithm... I tried to used it as the input workspace but it complains something like,

```
Error in execution of algorithm SolidAngle:
SpecialWorkspace2D must have 'spectra' of length 1 only.
```

2024-08-13 19:39 UTC, Kvieta1990 commented on scripts/Calibration/tofpd/diagnostics.py
> +    LoadEmptyInstrument(InstrumentName=instr_name, OutputWorkspace=f"{instr_name}_instr")
addressed

2024-08-13 19:48 UTC, peterfpeterson approved these changes

2024-08-14 09:19 UTC, merged

2024-08-14 09:23 UTC, sf1919 commented
I have added the milestone to this now but please can you all remember that PRs going into `main` need a milestone to ensure they are listed within the correct release.