add FilterByTime functionality
mantidproject/mantid pull request #37816
Opened 2024-08-16 17:31 UTC by KyleQianliMa

### Description of work
This PR adds the function of "FilterbyTime to the LoadEventAsWorkspace2D function by introducing two optional input fields: "FilterByTimeStart" and "FilterByTimeStop". If both are left empty, it will by default not apply any filter. If either start or stop is entered, it will filter from start time till end or start till end time. 

The functionality is implemented by introducing "BankPulseTime" and "PulseIndexer". Once "FilterByTimeStart" and/or "FilterByTimeStop" are introduced, a TimeROI is created from BankPulseTime, then this TimeROI is used to extract event_index using PulseIndexer, then a for loop is used to loop through the filtered event_index to generate "Y" of workspace.

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-08-16 18:32 UTC, jmborr requested changes
in the pull request description, can you write a manual test I can run in the workbench?

2024-08-16 18:43 UTC, KyleQianliMa commented
> in the pull request description, can you write a manual test I can run in the workbench?
I wrote that in the wrong place and it got commented out. Should I also write something that can be directly exectued from commandline of workbench?

2024-08-16 18:49 UTC, jmborr commented
> > in the pull request description, can you write a manual test I can run in the workbench?
> > I wrote that in the wrong place and it got commented out. Should I also write something that can be directly exectued from commandline of workbench?

Yes, a few python statements that I could execute in the workbench would be best

2024-08-19 15:09 UTC, KyleQianliMa commented
I've created something like this:
ws1 = LoadEventAsWorkspace2D(Filename = "BSS_11841_event.nxs", OutputWorkspace = "outputWS",
                        FilterByTimeStart = 0.0, FilterByTimeStop = 5.0, 
                        XCenter = 1.54, XWidth = 0.1,
                        Units = "Wavelength"
)

ws2 = LoadEventNexus(Filename = "BSS_11841_event.nxs", OutputWorkspace ="outputWS2",
                FilterByTimeStart = "0.0", FilterByTimeStop = "5.0")

ws3 = Integration(InputWorkspace = "outputWS2", RangeLower = 0.0, OutputWorkspace = "outputWS3")

The data of ws1 and ws3 is the same. But CompareWorkspace returns False because their X-axis is different. In the c++ code, setting x-axis can be achieved by:
    // set the expected X-axis
    outputWS3->getAxis(0)->setUnit("Wavelength");
    const auto xBins = {1.463, 1.617};
    const auto histX = Mantid::Kernel::make_cow<Mantid::HistogramData::HistogramX>(xBins);
    for (size_t i = 0; i < outputWS3->getNumberHistograms(); i++)
      outputWS3->setSharedX(i, histX);
But I don't know how to generate histX with python.

2024-08-19 17:39 UTC, jmborr reviewed
This script pass
```
from mantid.simpleapi import HFIRSANS2Wavelength, LoadEventAsWorkspace2D, LoadEventNexus
filename="/HFIR/CG3/IPTS-23782/nexus/CG3_4829.nxs.h5"

LoadEventNexus(
    Filename=filename,
    OutputWorkspace="CG3_4829_1",
    FilterByTimeStart=60,
    FilterByTimeStop=120
)
HFIRSANS2Wavelength(InputWorkspace="CG3_4829_1",  OutputWorkspace="CG3_4829_1")


LoadEventAsWorkspace2D(
    Filename=filename,
    OutputWorkspace="CG3_4829_2",
    FilterByTimeStart=60,
    FilterByTimeStop=120
)

# Accept if workspaces differ by one count, but no more
CompareWorkspaces(Workspace1="CG3_4829_1", Workspace2="CG3_4829_2", Tolerance=1)
```
The rest looks :ok_hand: 
@KyleQianliMa  You still need to fix the conda build. Have you already tried?

2024-08-19 19:54 UTC, peterfpeterson commented on Framework/DataHandling/src/BankPulseTimes.cpp
> +  } catch (std::exception &e) {
```suggestion
  } catch (const std::exception &) {
```
should fix that pesky windows compiler warning

2024-08-21 12:46 UTC, jmborr submitted a review, later dismissed

2024-08-21 20:14 UTC, KyleQianliMa commented
@jmborr Could you re-run the tests using CG3_4829.nxs.h5 file? It seems like all the check passed somehow. Previously some tests mysteriously failed, so I rebased the repo and pushed again. That caused some problem while I resolve merge conflict. I believe now everything should be ok.

2024-08-22 13:59 UTC, jmborr approved these changes

2024-08-22 14:05 UTC, merged