Compression options for AlignAndFocusPowderFromFiles
mantidproject/mantid pull request #37831
Opened 2024-08-19 18:18 UTC by dmitry-ganyushin

[6060: Add load w/ compression parameters to AlignAndFocusPowderFromFiles](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/6060)
### Description of work
Added an additional parameter  AlignAndFocusPowderFromFiles to determine whether its call to LoadEventNexus should enable compressing events during load. The parameter is called "MinSizeCompressOnLoad" which is a floating point number of Gbytes. 
.

2024-08-19 19:40 UTC, peterfpeterson requested changes
This missed the mark. The request was "AlignAndFocusPowderFromFiles needs additional parameter(s) to determine whether its call to LoadEventNexus should enable compressing events during load." When it is determined that the file should be compressed on load, the parameters `CompressTolerance` and `CompressBinningMode` need to be supplied to `LoadEventNexus`. The `__compressEvents()` method is called by the `__accummlate()` method which is run after a chunk is processed. These methods should not be modified.

This is also missing release notes.

2024-08-20 18:26 UTC, peterfpeterson commented on Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
> +            loader.setPropertyValue("CompressTolerance", str(self.kwargs["CompressTolerance"]))
```suggestion
            loader.setProperty("CompressTolerance", float(self.kwargs["CompressTolerance"]))
```

2024-08-20 20:47 UTC, dmitry-ganyushin commented on Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
> +            loader.setPropertyValue("CompressTolerance", str(self.kwargs["CompressTolerance"]))
Modified as suggested

2024-08-21 19:27 UTC, peterfpeterson approved these changes
I tried this in three modes:
* without the `CompressTolerance` parameter - did not compress on load
* with the `CompressTolerance` > filesize - did not compress on load
* with the `CompressTolerance` < filesize - did compress on load

2024-08-21 19:41 UTC, merged