Add tests for IqtPresenter tab
mantidproject/mantid pull request #37901
Opened 2024-09-02 12:32 UTC by adriazalvarez

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-05 09:41 UTC, warunawickramasingha requested changes

2024-09-16 14:52 UTC, adriazalvarez commented on qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.h
>    virtual void setSelectedSpectrum(int spectrum);
You are right, I haven't seen the use for these functions to be virtual. I have made them non-virtual now.

2024-09-17 10:53 UTC, warunawickramasingha commented on qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
Thanks for the changes. 
I just noticed that ``virtual`` keyword is missing from DataProcessor class's ``~DataProcessor() = default;`` that is being extended here. If you could make a note of it and add it to this PR or to any later PR, I think it would be better. Otherwise I am happy with the PR.

2024-09-18 07:30 UTC, adriazalvarez commented on qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
Thanks. I have overriden it from the interface class, so no need to add the virtual keyword.

2024-09-18 08:46 UTC, warunawickramasingha commented on qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
Thanks for making changes.

But I don't think just adding the `override` keyword to `~DataProcessor()` will make it a `virtual`. Since `ElwinPresenter` is further extending `DataProcessor` I think the ideal destructor for `DataProcessor` class needs to be either 
`virtual ~DataProcessor() override = default;` or 
`virtual ~DataProcessor() = default;` 
to guarantee that the `ElwinPresenter` object will be properly deleted at the end. 

Please correct me otherwise.

Thanks!

2024-09-18 09:09 UTC, adriazalvarez commented on qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
I think the override keyword makes the function virtual. So it becomes redundant to add the virtual. 
https://en.cppreference.com/w/cpp/language/override

2024-09-18 11:53 UTC, warunawickramasingha commented on qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
Thanks for noting this! I tried out an example and it seems to be working as you have mentioned.

2024-09-18 11:53 UTC, warunawickramasingha approved these changes
Thanks for the changes and happy to approve!

2024-09-19 07:11 UTC, merged