Implement CompressEvents method without sorting events
mantidproject/mantid pull request #37900
Opened 2024-09-02 05:16 UTC by rosswhitfield

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-03 19:12 UTC, peterfpeterson reviewed
The main question is whether the conversion of fine histogram bin has the correct check as to whether to convert it to a weighted event

2024-09-03 19:12 UTC, peterfpeterson commented on Framework/DataObjects/src/EventList.cpp
> +    if (tolerance < 0) {
Should we make these 3 a `struct` since they appear together in a couple of places?

2024-09-03 19:12 UTC, peterfpeterson commented on docs/source/algorithms/CompressEvents-v1.rst
> +This method will not be used if the events are already sorted as that
It is wise to ignore this option

2024-09-04 00:07 UTC, rosswhitfield commented on Framework/DataObjects/src/EventList.cpp
> +    if (weights > 0)
:facepalm:

2024-09-04 16:32 UTC, peterfpeterson approved these changes
On my machine, for the linear case, I get 2.6s for `SortEvents=False` and 10.4s for `SortEvents=True`

2024-09-04 19:19 UTC, peterfpeterson requested changes
Something is strange. Looking more closely at the results.

2024-09-04 20:42 UTC, peterfpeterson commented
Comparing things more closely, I discovered there are some differences between SortEvents=True/False. For SNS the DAS-clock is 0.1us so setting a tolerance of 0.05us gets below numerical issues, however (`SortEvents=False` has to be first to not sort the input workspace)
```python
filename='/path/to/SNAP_57514.nxs.h5'
wksp='SNAP_57514'

LoadEventNexus(Filename=filename, OutputWorkspace=wksp)
SumSpectra(InputWorkspace=wksp, OutputWorkspace=wksp)
CompressEvents(InputWorkspace=wksp, OutputWorkspace=wksp+'_linear_1F', Tolerance=.05, 
               BinningMode="Linear", SortFirst=False)
CompressEvents(InputWorkspace=wksp, OutputWorkspace=wksp+'_linear_1T', Tolerance=.05, 
               BinningMode="Linear", SortFirst=True)

tofs_F = mtd[wksp+'_linear_1F'].getSpectrum(0).getTofs()
tofs_T = mtd[wksp+'_linear_1T'].getSpectrum(0).getTofs()
wght_F = mtd[wksp+'_linear_1F'].getSpectrum(0).getWeights()
wght_T = mtd[wksp+'_linear_1T'].getSpectrum(0).getWeights()

print('*'*30, len(tofs_F), len(tofs_T))
for i in range(25): # len(tofs_F)):
    if tofs_F[i] != tofs_T[i]:
        print(f'{i:4d} *** {tofs_F[i]:6.3f} {tofs_T[i]:6.3f} *** {wght_F[i]:6.0f} {wght_T[i]:6.0f}')
print('*'*30)
```
The time-of-flight created for the events are off by 0.025 between cases. The fix to this would be to keep track of the time-of-flight in a way similar to the sorted case.

2024-09-05 15:21 UTC, peterfpeterson approved these changes
Thanks for the hard work in getting this put together. It works well.

2024-09-06 14:38 UTC, merged