Add single source of truth for absolute and relative differences to `Mantid::Kernel::FloatingPointComparison`
mantidproject/mantid pull request #37931
Opened 2024-09-06 18:20 UTC by rboston628

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-06 18:26 UTC, peterfpeterson commented on Framework/Kernel/src/FloatingPointComparison.cpp
> + * false otherwise.  False if either is NaN
```suggestion
 * false otherwise.  False if either (but not both) is NaN
```

2024-09-16 19:39 UTC, rboston628 commented on Framework/Kernel/src/FloatingPointComparison.cpp
> +    T const denom = static_cast<T>(0.5 * (std::abs(x) + std::abs(y)));
It does lead to different values.  I'm pretty convinced that the average of the absolute values is the correct norm to use.  I am following what is used, for instance, in [`TableColumn,h`](https://github.com/mantidproject/mantid/blob/420cb84178daf00d05a8a97c37eb81201f5feed8/Framework/DataObjects/inc/MantidDataObjects/TableColumn.h#L235).  It's also safer.

2024-09-16 19:52 UTC, rboston628 commented on Framework/Kernel/src/FloatingPointComparison.cpp
> +    T const denom = static_cast<T>(0.5 * (std::abs(x) + std::abs(y)));
Another option is using the max of the absolute values.  That is what is used in python's [`math.isclose()`](https://docs.python.org/3/library/math.html#math.isclose).  In the case of a positive and negative, the max and average absolute value will remain similar, while the absolute value of the average could be zero.

E.g. `x=-2`, `y=3`.
method | rel. diff. 
:---:|:---:
`max(\|x\|,\|y\|)` | 5/3 = 2.66
`avg(\|x\|, \|y\|)` | 5/2.5 = 2
`\|avg(x, y)\|` | 5/1 = 5

E.g. `x=-10`, `y=10`.
method | rel. diff. 
:---:|:---:
`max(\|x\|,\|y\|)` | 20/10 = 2
`avg(\|x\|, \|y\|)` | 20/10 = 2
`\|avg(x, y)\|` | 20/0 = `+inf`

I'm willing to try the max instead, but that might change some expected behavior

2024-09-16 20:01 UTC, rboston628 commented
> I [kicked off](https://builds.mantidproject.org/job/build_packages_from_branch/890/) a `build_packages_from_branch` job as requested. I think I selected the correct options to just run the build and test and not the package bit.

For some reason it passed on Linux and Windows, but [failed on Mac](https://builds.mantidproject.org/job/build_packages_from_branch/890/execution/node/164/log/?consoleFull).  Going to investigate now.

2024-09-16 20:34 UTC, peterfpeterson commented on Framework/Kernel/src/FloatingPointComparison.cpp
> +    T const denom = static_cast<T>(0.5 * (std::abs(x) + std::abs(y)));
I feel sufficiently schooled.

2024-09-16 20:34 UTC, peterfpeterson approved these changes

2024-09-17 09:55 UTC, jclarkeSTFC requested changes
The changes look good, I had a go at the 3D view to see if I could spot any weird polygon behaviour, but looked okay. I just had a couple of points:
- Were you thinking of putting these methods in the Python API? If not, then I think the release note isn't needed. 
- I'm not suggesting that you go back and change this now, but I don't think it's a good idea for existing files to have their `const` style changed when they are edited. Because otherwise the next person will come along, do something in this class and feel that they can change them all back again because they prefer the other way.

2024-09-17 12:37 UTC, peterfpeterson commented
@jclarkeSTFC I generically agree with you on release notes, but this is a functionality that we'd like to get more developers using. The release notes can be for them too.

When we move to a newer clang-format (>=14), east const vs west const becomes a configuration option.

2024-09-17 12:40 UTC, jclarkeSTFC approved these changes

2024-09-17 13:34 UTC, merged