Handle uncaught error in CompositeFunction::removeTie when tyring to unfix a tied parameter
mantidproject/mantid pull request #37958
Opened 2024-09-11 10:03 UTC by MohamedAlmaki

### Description of work

#### Summary of work

Fixes #xxxx. 

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-11 15:06 UTC, warunawickramasingha requested changes
I have followed the steps given in https://github.com/mantidproject/mantid/issues/37940.

But I am still observing a crash at the same step due to a runtime exception raised from [here](https://github.com/mantidproject/mantid/blob/main/Framework/API/src/IFunction.cpp#L184). Please check. Thanks

2024-09-12 09:20 UTC, sf1919 commented
@MohamedAlmaki  - I think this has been affected by our changes to pre-commit. Have a look at the summary for the approval in the PR to see if you can identify what needs updating in your PR - https://github.com/mantidproject/mantid/pull/37960#pullrequestreview-2298555084

2024-09-12 10:37 UTC, warunawickramasingha commented
Thanks for the changes, and no crash observed this time. I'll approve once the CI is green.

2024-09-12 13:30 UTC, sf1919 commented
@warunawickramasingha CI is green

2024-09-12 14:36 UTC, warunawickramasingha approved these changes
Happy to approve this!

2024-09-12 14:36 UTC, merged