Update MVP tutorial documentation
mantidproject/mantid pull request #37953
Opened 2024-09-10 15:53 UTC by robertapplin

### Description of work
This PR updates some of the MVP tutorial documentation to use some coding best practises in the examples, and also adds MVP best practises and an explanation why they are useful.

It also simplifies some of the examples by removing the use of the QMainWindow. Instead it is useful to just use a plain QWidget because it simplifies code, but also it means the QWidget you design can be used standalone OR in embedded within a wider interface. (QMainWindow is less flexible as it cannot be embedded in a wider interface).

Part of #37830
Still need to update the MVPDesign document separately

**To do**
- [ ] Only made it up to the Mocking doc page so far

### To test:

*This does not require release notes* because **it is an internal documentation change**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-17 13:30 UTC, adriazalvarez requested changes
I have followed the tutorial in order, trying to reproduce all the examples. 
Thanks for updating the docs and modernizing the code. 
Everything works as intended, but I have spotted some typos here and there.
I only have a general comment, but could be something I'm ignoring, or some limitation of osx: On following the exercise, there is frequently the need to import functions by calling `from qtpy.QtCore.Qt import XXX`. I haven't been able to make this work for me, and I needed to import `from qtpy.QtCore import Qt` and then call the relevant functions from Qt on the code. Do you know what could be wrong?

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/AddLineEdit.rst
Missing QLineEdit import

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/AddSpinBox.rst
Missing QSpinBox import

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Tables.rst
In this example, the QTableWidget and QTableWidgetItem imports are not specified

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Layouts.rst
>  So far we have used the vertical layout (``QtWidgets.QVBoxLayout``) and we
I think up to this point the only used layout was a GridLayout. 
Is it possible to either change the layout of the previous examples to QVBox or specify here that so far we have used the Grid Layout?

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Layouts.rst
> +        self._button.clicked.connect(self.btn_click)
The function callback here should be `self._button_clicked`

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/PresenterExerciseSolution.rst
> +    class View(QWidget):
In the solution to this exercise, the `subscribe_presenter` function is missing on the view

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/PresenterExerciseSolution.rst
> +    view.show()
```suggestion
if __name__ == "__main__" :
    app = _get_qapplication_instance()
    view = View()
    presenter = Presenter(view)
    view.show()
```

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Mocking.rst
In the code snippet of this file, the function to assert has been renamed to `get_value` previously, so the code should be updated on the test case. (`self.view.get_value` instead of `self.view.getValue`).
Maybe for completion also `self.view.btn_click` should be renamed to `self.view._button_clicked`, as it has been changed before too.

Also, in the solution to the mocking exercise (file not changed in this pr), all the getters functions have been renamed to camel case previously but not in the mocking exercise (getValue, getColour, getPhase..)

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/ModelExerciseSolution.rst
In this exercise solution, the model and the view are missing the List import. 
`from typing import List`

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Matplotlib.rst
> +        def add_data(self, xvalues: ndarray, yvalues: ndarray, visible: bool, colour: str, marker: str) -> None:
This function is probably better renamed as plot_data? I say because it doesn't add data, just clears the axes and plots new one.

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Matplotlib.rst
It could be said here to name the python file `plot_view.py`

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/CompleteGUIcode/model_colour.py
On the `CompleteGui.rst` file there is still an entry for `model_colour.py` on the index

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/CompleteGUIcode/plot_view.py
> +    def addData(self, xvalues: ndarray, yvalues: ndarray, visible: bool, colour: str, marker: str) -> None:
this function needs to be renamed `add_data` (or `plot_data` if you accept my previous suggestion)

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/CalculatorExample/Calculator.py
following previous conventions, should it be better to rename Model, View, Presenter files as model.py, view.py and presenter.py on the calculator?

2024-09-17 13:30 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/CalculatorExample/View.py
> +    def show_display(self, show: bool) -> None:
This function behaviour is reversed on arguments pass on the presenter(or the name should be hide_display). It does the opposite of its intended function.

2024-09-17 15:45 UTC, robertapplin commented
Thanks for reviewing this! I've made all the changes, let me know if I've missed anything accidentally

2024-09-18 07:49 UTC, adriazalvarez requested changes
Thanks for the quick response! 
I think I have spotted another typo, but it looks good.

2024-09-18 07:49 UTC, adriazalvarez commented on dev-docs/source/MVPTutorial/Mocking.rst
In this file there is a `test_doSomething`, the test is calling `getValue` instead of `get_value`

2024-09-18 12:33 UTC, adriazalvarez approved these changes
Thanks for all the changes. It's quite a nice tutorial!

2024-09-19 06:51 UTC, merged