Fix ENGINX data cache search on IDAaaS
mantidproject/mantid pull request #38027
Opened 2024-09-19 10:09 UTC by GuiMacielPereira

### Description of work
From the issue described in https://github.com/mantidproject/mantid/issues/37398, the ENGINX files were still not being found in the data cache because part of the path was still using `ENGIN-X` instead of `ENGINX`.

#### Summary of work
I changed a few lines of code that ensure that when the shortname of the instrument is used (`ENGINX`) to find the index file, the path is also constructed consistently with this, and uses the shortname version.

Access ENGINX files easily on IDAaaS from the data cache.
Fixes #37398 . 

#### Further detail of work

### To test:
Load ENGINX files on IDAaaS with the debug log enabled and check that the data cache is used.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-09-26 15:57 UTC, jhaigh0 approved these changes, later dismissed
Load is now looking in the correct place. With Gui's build I got this permission denied error upon trying to load the data.
![image](https://github.com/user-attachments/assets/316e5bc4-920a-4e7c-99be-fd2f8a5bbc10)
This shows that Load was searching in the correct place `/data/instrument/ENGINX`

2024-09-26 16:23 UTC, cailafinn reviewed
Code and the newly added test look good. 

Does this need a release note before merging? If I'm reading the history right this would have been a problem in 6.10.

2024-09-27 09:38 UTC, cailafinn requested changes
Just noticed a typo in the release notes.

2024-09-27 09:39 UTC, cailafinn requested changes

2024-09-27 09:39 UTC, cailafinn commented on docs/source/release/v6.11.0/Framework/Data_Objects/Bugfixes/38027.rst
> +- Loading `ENGIN-X` data on IDAaaS from the insttrument data cache no longer throws a path not found error.
```suggestion
- Loading ``ENGIN-X`` data on IDAaaS from the instrument data cache no longer throws a "path not found" error.
```

2024-09-27 11:23 UTC, cailafinn approved these changes

2024-09-27 12:18 UTC, merged