Remove direct calls to presenter from cut viewer view
mantidproject/mantid pull request #38197
Opened 2024-10-15 16:38 UTC by RichardWaiteSTFC

### Description of work

Remove direct calls to presenter from cut viewer view for MVP training.
This is blocked by #38101(which must be merged first)

Fixes #38102

### To test:

(1) Follow manual testing instructions 
https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#cutviewer-tool

*This does not require release notes* because **internal change, users shouldn't notice difference**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-10-15 16:41 UTC, RichardWaiteSTFC commented
Want to add co-authors to commits, but won't do this until review so as not to rerun CI

2024-10-22 08:34 UTC, robertapplin commented
I think this needs rebasing on main now that the prior PR has been merged. When its rebased I will review!

2025-01-06 08:58 UTC, robertapplin requested changes
The code looks good, and I can confirm the CutViewerView is not communicating directly with the SliceViewer(Presenter). There has been some nice renaming too of some variables, such as `extents` to `extents_in_plane`, which has helped with code readability and understanding

I have one small suggestion which could also be an improvement to the existing code

2025-01-09 09:13 UTC, robertapplin approved these changes
Thanks for the changes, looks good to go!

2025-01-09 09:49 UTC, merged