Add `value` attribute to python binding of `Property` base class
mantidproject/mantid pull request #38206
Opened 2024-10-17 13:53 UTC by rboston628

### Description of work

#### Summary of work

Within the python binding, added a `value` attribute to the generic `Property` type.  This will have the same behavior as `valueAsStr`.

#### Purpose of work

Most `Property`s in mantid inherit from `PropertyWithValue` and have a `.value` attribute.

However, some inherit from `Property` directly and don't have this attribute.  Since users might look for it, this was programmed to just return the same as `.valueAsStr` for the generic base `Property` type.

This came up within the context of PR #38177, which adds an `EnumeratedStringProperty` without a python binding.  When the property is retrieved from an algorithm, it has type `Property`, and hence has no `.value` attribute.  This PR will make sure that `.value` still works.

#### Further detail of work

Change was two lines:
``` c++
.add_property("value", &Property::value, &Property::setValue,
                    "The value of the property. For a generic property, equivalent to valueAsStr.")
```

### To test:

This should be basically inaccessible from the python API.  There is no way to create a generic `Property` object from within python.  

This would only even come up in the situation of a class inheriting directly from `Property`, without its own python binding,  The only property that meets this description is `MatrixProperty`, but that is not used inside any algorithm.  I tried testing in a few ways, but couldn't get anything to come up.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-10-17 18:58 UTC, dmitry-ganyushin approved these changes

2024-10-17 21:39 UTC, peterfpeterson requested changes
Please add a unit test in python that shows this works. Maybe with float property and string property. 

This also needs release notes.

2024-10-18 15:09 UTC, peterfpeterson commented
The tests could be added to https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/test/python/mantid/kernel/PropertyWithValueTest.py

2024-10-22 15:48 UTC, rboston628 commented
There is no way to add a test of this in this PR, and it is being added into PR #38177

2024-10-22 15:48 UTC, closed without merging