Add new pearl focus mode allowing user to specify which transverse detector modules to focus
mantidproject/mantid pull request #38344
Opened 2024-11-01 14:44 UTC by RichardWaiteSTFC

### Description of work

New focus mode "trans_subset" added to the PEARL reduction routines which allows user to specify specific modules to include in the transverse bank focussing using the parameter `trans_mod_nums`. The module numbers in the range 1-9 can be specified using the same string syntax as run-numbers - e.g. `trans_mod_nums="1-3,5"` corresponds to focussing modules 1,2,3 and 5.

Fixes #38340

**Report to:** Nick Funnell (PEARL, ISIS)

### To test:

To-Do

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-11-15 12:04 UTC, robertapplin requested changes

2024-11-15 12:04 UTC, robertapplin commented on scripts/Diffraction/isis_powder/pearl.py
> +
Using the "return early" pattern in this function might help with readability, although I know this is subjective so feel free to ignore this comment! https://medium.com/swlh/return-early-pattern-3d18a41bba8

2024-11-15 13:07 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPearlTest.py
> +
Yep sorry just cut/copied that function from inside a test to outside - should have made it an f-string (which I agree are more readable)

2024-11-21 11:11 UTC, robertapplin approved these changes
Thanks for the changes! The code looks good and I've followed the instructions and it works as expected. A test and release note has been added 👍

2024-11-22 11:11 UTC, merged