38254 Introducing PeakShapeDetectorBin peak shape
mantidproject/mantid pull request #38433
Opened 2024-11-21 12:36 UTC by warunawickramasingha

### Description of work
A new peak shape `PeakShapeDetectorBin` was introduced to save the shape of each peak including the detector IDs and limits of either `TOF` or `dSpacing`. This shape can be used for

- Overlap detection post integration (peaks could be excluded or flagged as combined)
- Two-step integration - re-integrate weak peaks using strong peak dimensions
- Eventual visualisation on instrument view (i.e. show bounding box of peak)

Fixes #38254. 

#### Further detail of work

### To test:
1. Code review
2. Unit tests should pass in python and c++
3. `PeakShapeDetectorBin` should be visible to python and can be inspected with below code snippet
```
from mantid.dataobjects import PeakShapeDetectorBin
from mantid.kernel import SpecialCoordinateSystem
detBinList = [(101, 27.0, 100.0), (202, 3000.0, 5000.0)]
shape = PeakShapeDetectorBin(detBinList, SpecialCoordinateSystem.NONE, "ParentAlgoName", 1)
print(shape.toJSON())
print(shape.algorithmName())
print(shape.algorithmVersion())
print(shape.shapeName())
```

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-11-27 16:03 UTC, GuiMacielPereira requested changes
The code looks good and the unit tests are comprehensive. The script provided for testing runs without issue.
I have only a few requests and I noticed that the `==` is not quite working?
When I run
```
from mantid.dataobjects import PeakShapeDetectorBin
from mantid.kernel import SpecialCoordinateSystem
detBinList = [(101, 27.0, 100.0), (202, 3000.0, 5000.0)]
shape1 = PeakShapeDetectorBin(detBinList, SpecialCoordinateSystem.NONE, "ParentAlgoName", 1)
shape2 = PeakShapeDetectorBin(detBinList, SpecialCoordinateSystem.NONE, "ParentAlgoName", 1)
print(shape1==shape2)
```
It prints `False`, but from the code it looks like the intention is to print `True`?
Unless I misunderstood in which case you can ignore this.

2024-12-03 16:00 UTC, warunawickramasingha commented
> The code looks good and the unit tests are comprehensive. The script provided for testing runs without issue. I have only a few requests and I noticed that the `==` is not quite working? When I run
> 
> ```
> from mantid.dataobjects import PeakShapeDetectorBin
> from mantid.kernel import SpecialCoordinateSystem
> detBinList = [(101, 27.0, 100.0), (202, 3000.0, 5000.0)]
> shape1 = PeakShapeDetectorBin(detBinList, SpecialCoordinateSystem.NONE, "ParentAlgoName", 1)
> shape2 = PeakShapeDetectorBin(detBinList, SpecialCoordinateSystem.NONE, "ParentAlgoName", 1)
> print(shape1==shape2)
> ```
> 
> It prints `False`, but from the code it looks like the intention is to print `True`? Unless I misunderstood in which case you can ignore this.

Thanks for the detailed review @GuiMacielPereira ! 
The above observation was because the `operator==` was not exposed to python's `__eq__` method. 

The same behaviour can be observed in the existing peak shapes such as `PeakShapeEllipsoid`, `PeakShapeSpherical` from python. You could try that by 

```
from mantid.dataobjects import PeakShapeSpherical, PeakShapeEllipsoid
sphere1 = PeakShapeSpherical(0.5)
sphere2 = PeakShapeSpherical(0.5)
print(sphere1 == sphere2)  # <-- False

ellipse1 = PeakShapeEllipsoid([V3D(1, 0, 0), V3D(0, 1, 0), V3D(0, 0, 1)], [0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9])
ellipse2 = PeakShapeEllipsoid([V3D(1, 0, 0), V3D(0, 1, 0), V3D(0, 0, 1)], [0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9])
print(ellipse1 == ellipse2) # <-- False
```
However I have fixed this for `PeakShapeDetectorBin` and would now output `True` in your example.

2024-12-05 11:30 UTC, GuiMacielPereira requested changes
Thank you for your explanation, I think we should keep `__eq__` doing the same thing as the other classes. If you change it back and the tests pass, I'll be happy to aprove.
Apologies for my oversight

2024-12-05 11:30 UTC, GuiMacielPereira commented on Framework/PythonInterface/mantid/dataobjects/src/Exports/PeakShapeDetectorBin.cpp
> -      .def("__eq__", &PeakShapeDetectorBin::operator==, arg("self"), arg("other"));
I see, maybe it's best to keep it as it was before? I hadn't realised that the other Peak shapes had the same behaviour, so I think they should all be consistent with each other.

2024-12-09 14:02 UTC, GuiMacielPereira approved these changes
All good, thanks for changing the equality back!

2024-12-11 13:57 UTC, merged