Abins: improve handling of isotopic cross-sections
mantidproject/mantid pull request #38448
Opened 2024-11-26 13:19 UTC by ajjackson

### Description of work
#### Summary of work

- [x] introduce unit test that error should be raised for Zn65
- [x] modify code to raise ValueError in such cases
- [x] introduce unit test that Zn_30_65.39 should be identified as isotopic mixture
- [x] modify code to detect when standard mass is used

#### Purpose of work

__Primary issue__:
Unstable isotopes such as Zn65 currently give a NaN cross-section. We should ensure that unsupported isotopes give a noisy error instead.

__Secondary issue__:
We are seeing Zn65 because data with mass 65.39 is being inappropriately rounded to this exotic isotope, rather than identified as being the standard isotopic mixture. Such cases should be detected more robustly.

Fixes #37735 

**Report to:** Jeff Armstrong

#### Further detail of work

### To test:
The changes are covered by unit tests and system tests

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2024-11-26 17:05 UTC, ajjackson commented
Currently Abins identifies if the mass is a standard isotopic mixture by comparing against `Atom(symbol=symbol).mass` with a threshold of 0.01.

In the case of zinc, the standard mass has been revised by a difference of more than 0.01, so CASTEP writes mass values that are not detected by Abins as being the standard.

A more robust workflow could look at which is _nearest_ between the standard mass and another known isotope.

I have found a quirk the `Atom` API though:

```
In [44]: Atom(symbol="Zn").mass
Out[44]: 65.409

In [45]: Atom(symbol="Zn", a_number=82).mass
Out[45]: 81.95484

In [46]: Atom(symbol="Zn", a_number=83).mass
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[46], line 1
----> 1 Atom(symbol="Zn", a_number=83).mass

RuntimeError: Failed to find an atom with symbol=Zn and a=83

In [47]: Atom(symbol="Zn", a_number=20).mass
Out[47]: 53.99295
```

Mass values that are too high raise an error, but masses that are too _low_ do not!

2024-11-28 12:31 UTC, ajjackson commented
For an example of a really nasty case that requires some logic to get through:

- Mantid's `Atom.cpp` defines a standard I53 with mass 126.904470 and, among many others, an isotope 127I53 with abundance 100% and mass 126.904468
- The mass assigned to "standard" iodine by CASTEP is 126.903999; presumably these codebases are using reference data from different years.

To resolve this, we
- check if the requested mass is closer to the Mantid reference mass of 127I53 or I53;
- in this case the 127I53 mass is actually closer so we assume this could be what they wanted.
- Then we check if data is available; the coherent scattering length is NaN so it is not.
- Because we are within 0.01 of the standard mass, we assume this was the original intent, raise a warning, and use the I53 data.

2024-11-29 11:13 UTC, ajjackson commented
The docs failure might be connected to 
> 17:04:07 release/v6.12.0/indirect_geometry:3: WARNING: Bullet list ends without a blank line; unexpected unindent. [docutils]

but I'm not sure what to do about that. The pre-commit hooks will not let me append another newline to the release note!

2024-12-10 11:57 UTC, ajjackson commented
Thanks @robertapplin for figuring out the docs formatting 🎉

2025-01-03 11:27 UTC, adriazalvarez requested changes
The changes are sensible and adding the atominfo dataclass handles better edge cases and also simplifies the code in some parts. Additionally, test cases are added. 
I have very small comments but otherwise looks fine to me.

2025-01-03 11:27 UTC, adriazalvarez commented on scripts/abins/abinsalgorithm.py
> +@dataclasses.dataclass
Does this dataclass belong in this file? What do you think of moving it to a separate file?

2025-01-03 11:27 UTC, adriazalvarez commented on scripts/abins/abinsalgorithm.py
> +        if abs(nearest_isotope.mass - standard_mix.mass) < 1e-12:
Could we move the epsilon to be a constant? I know is very unlikely this number has to be changed, but to make the code look more homogeneous.

2025-01-03 11:27 UTC, adriazalvarez commented on scripts/abins/abinsalgorithm.py
> +            logger.warning(f"Standard mass {standard_mix.mass} is close enough, will " f"use data for this isotope mixture.")
```suggestion
            logger.warning(f"Standard mass {standard_mix.mass} is close enough, will use data for this isotope mixture.")
```
I think the precommit is modifying this string to be in a single line.

2025-01-06 10:06 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +@dataclasses.dataclass
No strong opinion. It is used in two files, but abins2 is always going to import from abinsalgorithm so there is no danger of circular references. (If anything the danger increases by introducing a new module.)

I'm happy to move it if you think it will be tidier.

2025-01-06 10:16 UTC, ajjackson commented on scripts/abins/abinsalgorithm.py
> +            logger.warning(f"Standard mass {standard_mix.mass} is close enough, will " f"use data for this isotope mixture.")
140 characters is so wiiiiiiide

2025-01-06 12:22 UTC, adriazalvarez commented on scripts/abins/abinsalgorithm.py
> +@dataclasses.dataclass
Design wise is fine, I was more thinking that in abins library every filename sort of contains a class with the same name as the file. If the atoms info is an independent entity, probably it would be stylistically more clean to have it in a separate file.

2025-01-06 20:32 UTC, adriazalvarez approved these changes
Thanks for addressing my comments.

2025-01-07 08:14 UTC, merged