Added section for testing ADS interactions to MSlice manual testing doc
mantidproject/mantid pull request #38513
Opened 2024-12-16 10:04 UTC by SilkeSchomann

### Description of work

Recently, an ADS observer was added to MSlice. This allows to monitor changes to the ADS and reacting accordingly. This new functionality should be covered by manual tests, so I have updated the manual testing instructions for MSlice.

Fixes #38491.

#### Further detail of work

### To test:

Read the new instructions and check grammar and spelling. 

For following the test instructions the MSlice version in Mantid needs to be updated to the latest MSlice nightly version.

*This does not require release notes* because **it is a change of the developer documentation and not user facing.**

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2025-01-08 16:50 UTC, GuiMacielPereira requested changes
I've followed the instructions and everything is working correctly.

However, I noticed that if I go to the`MD Histo` tab, and save a workspace to mantid, and then click `delete` inside the `MD Histo` tab, then Mantid does crash.
Could you try to replicate this issue?

2025-01-09 10:50 UTC, SilkeSchomann commented
> I've followed the instructions and everything is working correctly.
> 
> However, I noticed that if I go to the`MD Histo` tab, and save a workspace to mantid, and then click `delete` inside the `MD Histo` tab, then Mantid does crash. Could you try to replicate this issue?

Yes, I can reproduce the issue and have opened a GitHub issue for MSlice for this: https://github.com/mantidproject/mslice/issues/1044

The test instructions itself are ok, though.

2025-01-10 08:47 UTC, SilkeSchomann commented
> > I've followed the instructions and everything is working correctly.
> > However, I noticed that if I go to the`MD Histo` tab, and save a workspace to mantid, and then click `delete` inside the `MD Histo` tab, then Mantid does crash. Could you try to replicate this issue?
> 
> Yes, I can reproduce the issue and have opened a GitHub issue for MSlice for this: [mantidproject/mslice#1044](https://github.com/mantidproject/mslice/issues/1044)
> 
> The test instructions itself are ok, though.

There is a PR for MSlice that fixes the crash: https://github.com/mantidproject/mslice/pull/1045

2025-01-10 09:46 UTC, GuiMacielPereira approved these changes, later dismissed
Sounds good, happy to approve :+1:

2025-01-10 10:44 UTC, thomashampson commented on dev-docs/source/Testing/Direct/MSliceTestGuide.rst
> +#. Now click ``Clear`` in the Workspaces window in Mantid and check that all workspace in the ``2D`` and ``MD Histo`` tabs in MSlice are deleted as well
```suggestion
#. Now click ``Clear`` in the Workspaces window in Mantid and check that all workspaces in the ``2D`` and ``MD Histo`` tabs in MSlice are deleted as well
```

2025-01-10 10:44 UTC, thomashampson approved these changes

2025-01-10 10:48 UTC, SilkeSchomann commented
@thomashampson Thanks for fixing this!

2025-01-10 11:54 UTC, merged