Refactor WildesTest to reduce Code Duplication
mantidproject/mantid pull request #38529
Opened 2024-12-18 16:58 UTC by yusufjimoh

### Description of work
Refactor WildesTest to reduce Code Duplication

#### Summary of work
- created helper functions to reduce code duplication in PolarizationCorrectionWildesTest

Fixes #38326 

### To test:
Test should pass

This does not require release notes because it involves code refactoring and improvements

2025-01-10 14:51 UTC, adriazalvarez requested changes
Test are working well and I think is a good step into a better organized test file. I appreciate the effort you have done with these refactoring as it is a complex test suite. 
I have some suggestions that I think could improve this refactoring, but please feel free to discuss if you don't agree.

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
>      BinEdges edges{0.3, 0.6, 0.9, 1.2};
Throughout all the test, ```nBins```, ``edges`` and ```yVal``` have the same value. I think it could be a good opportunity to move them as global constants for the file to save some lines. if a future test needs to add different parameters for the test histogram, it can always create local values.

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  }
```suggestion
  void addWorkspacesToService(const std::vector<std::string> &wsNames, const std::vector<MatrixWorkspace_sptr> &wsList) {
    for (size_t i = 0; i < wsNames.size(); ++i) {
      AnalysisDataService::Instance().addOrReplace(wsNames[i], wsList[i]);
    }
  }
```
I don't think in any test you want to add less workspaces than the ones you pass on within the vector, so the ```numWorkspaces`` parameter can be omitted.

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  }
```suggestion
  void prepareAndRegisterWorkspaces(std::vector<std::string> &wsNames,
                                    const std::vector<Mantid::API::MatrixWorkspace_sptr> &wsList, const size_t nHist) {

    for (size_t i = 0; i < wsNames.size(); ++i) {
      for (size_t j = 0; j < nHist; ++j) {
        wsList[i]->mutableY(j) *= static_cast<double>(i + 1);
        wsList[i]->mutableE(j) *= static_cast<double>(i + 1);
      }
    }
  }
```
To keep the tests more modular, I would extract the ```addWorkspacesToService``` function out of here and put it back after the call to this function in the test. I would also rename this function to something like ```setWorkspacesTestData``` or something on that line.

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  void validateNumberOfEntries(const WorkspaceGroup_sptr workspaceGroup, const size_t expectedEntries) {
```suggestion
  void validateNumberOfEntries(const WorkspaceGroup_sptr &workspaceGroup, const size_t expectedEntries) {
```

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  }
You don't need this function if you are using an optional parameter (see the comment on ```createWorkspaceList```)
```suggestion

```

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  std::vector<MatrixWorkspace_sptr> createWorkspaceList(const std::optional<Counts> counts, const size_t numClones) {
```suggestion
  std::vector<MatrixWorkspace_sptr> createWorkspaceList(size_t numClones, const std::optional<Counts>& counts = std::nullopt ) {
```
Using this function signature allows you to call ```createWorkspaceList``` from the test using only the ```numClones``` parameter, and avoid using the other ```createWorkspaceList``` function.

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +    AnalysisDataService::Instance().addOrReplace(wsNames.back(), wsList.back());
```suggestion
```
Again, I would extract this call out of this function, and also you can call it with the new helper function you have: 
```addWorkspacesToService(wsNames, wsList);```

2025-01-10 14:51 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  MatrixWorkspace_sptr createWorkspace(const Counts &counts) { return createWorkspace(2, std::nullopt, counts); }
```suggestion
  MatrixWorkspace_sptr createWorkspace(size_t nHist = 2, std::optional<Counts>& counts = std::nullopt,  std::optional<BinEdges>& edges = std::nullopt) {
    if (!edges) {
      edges = BinEdges{0.3, 0.6, 0.9, 1.2};
    }

    const auto yVal = 2.3;
    if (!counts) {
      counts = Counts{yVal, 4.2 * (yVal), yVal};
    }

    return create<Workspace2D>(nHist, Histogram(*edges, *counts));
  }

```
I would keep only one definition of this function and reverse the parameters count and edge in the function signature. I think you call it in a few places using only the count parameter, but you need to pass a number anyway to create a workspaces and it may not be always numHist =2 ,  so better pass it when you call the function.

2025-01-14 13:17 UTC, adriazalvarez requested changes
Thanks for the changes. I have some more suggestions.

2025-01-14 13:17 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
>          wsList[i]->mutableE(j) *= static_cast<double>(i + 1);
```suggestion
  void setWorkspacesTestData( const std::vector<Mantid::API::MatrixWorkspace_sptr> &wsList) {

    for (size_t i = 0; i < wsList.size(); ++i) {
      for (size_t j = 0; j < wsList[i]->getNumberHistograms(); ++j) {
        wsList[i]->mutableY(j) *= static_cast<double>(i + 1);
        wsList[i]->mutableE(j) *= static_cast<double>(i + 1);
```
I think you can get away with only passing the `wsList` here and in another prepare workspace function.

2025-01-14 13:17 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
>                                              const size_t nHist) {
Since you only modify a workspace,  you can pass here only that workspace ,like so:
```
 void setupWorkspacesForIdealCasesTwoInput(const Mantid::API::MatrixWorkspace_sptr& ws) {
    
    for (size_t i = 0; i < ws->getNumberHistograms(); ++i) {
      ws->mutableY(i) *= 2.;
      ws->mutableE(i) *= 2.;
    }
  }
```

2025-01-14 13:17 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  static constexpr size_t nBins{3};
```suggestion
  double m_yVal{2.3};
  BinEdges m_edges{0.3, 0.6, 0.9, 1.2};
  size_t m_nBins{3};
```
I would consider adding these as global constants for the file. But if you prefer to keep them as private fields, is better to add the prefix `m_` to the name. As in `m_yVal`, `m_edges`, `m_nBins`. Also, consider adding ```nHist```  because is it mostly always 2. Additionally, if some tests changes the value of `yVal` if would fail other tests, so you would have to override the `setup` function of the tests suites and initialize correctly the values for each test. So maybe simpler to move them as global constants?

2025-01-14 13:17 UTC, adriazalvarez commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
>      Counts counts{yVal, yVal, yVal};
```suggestion
    Counts counts(3, yVal);
```
When the value is repeated, you can initialize the counts using this constructor.

2025-01-14 20:59 UTC, yusufjimoh commented on Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
> +  static constexpr size_t nBins{3};
Thanks for the suggestion, I have added the variables as global constants

2025-01-15 10:15 UTC, adriazalvarez requested changes

2025-01-15 11:52 UTC, yusufjimoh commented
@adriazalvarez Thanks for the suggestions, I have changed the global constant variables to uppercase, along with the other suggested changes

2025-01-15 15:02 UTC, adriazalvarez approved these changes
Thanks for the latest changes. Test are passing, the test suite is better organized, and there are some helper functions that reduce redundant lines and will help on adding new tests if necessary.

2025-01-15 15:31 UTC, merged