37795 change polaris pdf norm
mantidproject/mantid pull request #38535
Opened 2024-12-20 12:03 UTC by andy-bridger

### Description of work

#### Summary of work
As per issue https://github.com/mantidproject/mantid/issues/37795 added an option for the vanadium normalisation to be done either using relative or absolute normalisation.

Fixes #37795.

#### Further detail of work
This is done by addition of a new mode "pdf_norm". In order to accommodate this some additional alterations were required to the enum class and the test files. An additional test was added to check the absolute normalisation.

### To test:

Run the ISISPowder_PolarisTest.py tests. There should now be 18. The new tests FocusTestNoAbsorptionWithRelativeNormalisation and FocusTestNoAbsorptionWithAbsoluteNormalisation have replaced FocusTestNoAbsorption.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2025-01-08 15:29 UTC, RichardWaiteSTFC requested changes
Thanks for this, just a minor thing and a request to tidy up a function which you didn't write (but seeing as you are in the file anyway).
Also would it be possible to get a release note for this - we will want users to be aware of it (to that end we will also contact POLARIS scientists when it's merged)!

2025-01-08 15:29 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
Looks like these functions are also in `FocusTestNoAbsorptionWithRelativeNormalisation` - would it be possible to define them as helper functions once outside the test classes so they don't have to be duplicated?

2025-01-08 15:29 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +    required_run_numbers = ["98531", "98532", "98533", "98534"]  # create_van : PDF mode  # File to focus (Si)
I'm OK to have an additional file, but is there a reason why you couldn't use `98533` and just have a different reference file?

2025-01-08 15:29 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> -        van_normalisation_method="Relative",
It's worth clarifying that the old reference file for `FocusTestNoAbsorption` is now used in the test `FocusTestNoAbsorptionWithRelativeNormalisation` - despite the fact that before this change the default `van_normalisation_method="Absolute"` when `mode="PDF"` (now it is "Relative")  - this is because the default vanadium normalisation was previously overwritten as a kwarg passed to `focus` here

2025-01-08 15:29 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> -            van_normalisation_method="Relative",
Was there any need to remove these?
Also since you're making changes in this part of the file...
It looks like this function could be tidied up, something like (not tested no warranty included!):
```
focus_kwargs = {}
if paalman_pings:
        inst_object._inst_settings.empty_can_subtraction_method = "PaalmanPings"  # the default is Simple
        inst_object._inst_settings.paalman_pings_events_per_point = 1
else:
    focus_kwargs["sample_empty_scale"] = sample_empty_scale
return inst_object.focus(
            run_number=run_number,
            input_mode="Summed",
            do_van_normalisation=True,
            do_absorb_corrections=True,
            sample_empty=sample_empty,
            multiple_scattering=False,
            **focus_kwargs)
```
The point is to make it clear how  `paalman_pings` variable affects the arguments passed to `focus`. You could include all the kwargs in the `focus_kwargs` dict if you like. What do you think?

2025-01-09 10:05 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> -        van_normalisation_method="Relative",
Sorry, no code change required! I think this comment on github is enough - just might be something that could confuse the eagle-eyed gatekeepers! In future probably worth adding this sort of thing to the PR description.

2025-01-09 10:11 UTC, andy-bridger commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> -            van_normalisation_method="Relative",
Re: Removal - I think I did that because it should be taken care of by the `setup_inst_object("PDF", with_container=True)` above and I didn't want to encourage further confusion by having it changeable from two places within the function. The whole passing of the argument normalisation is a bit confusing.

Re: Change - I like it, I think it is better with only having the additional kwarg in a dictionary, as most of the information is visible directly within the function call?

2025-01-09 10:15 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> -            van_normalisation_method="Relative",
RE: Removal - I see and I agree!
RE: Change - yep happy to keep just the one additional kwarg as I have above - thanks!

2025-01-10 12:59 UTC, andy-bridger commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +    required_run_numbers = ["98531", "98532", "98533", "98534"]  # create_van : PDF mode  # File to focus (Si)
Short answer is probably no, I'm sure there is a way that could've been done. I just tried to keep it consistent and it seemed that the old test took 98532 and ran the normalisation then compared it to 98533, so I figured we could run a different normalisation and compare it to 98534.

2025-01-10 13:05 UTC, andy-bridger commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
I've done this - I wasn't sure what variable to use for the passed class objects as `self` seemed inappropriate for a general helper function - so I called it `test`.

2025-01-10 13:06 UTC, andy-bridger commented
I think all those comments have now been addressed?

2025-01-10 13:34 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
Sorry I just meant the two functions `generate_error_message` and `assert_output_file_exists` being moved to external helper functions - but I now see the latter requires the `test` object.

It is annoying with systems test that each test is it's own class, I have not seen the test class being passed in this way before but it works!

It might be overkill, put one possible solution is to define a new base class with these methods like so 

class focus_system_test_helper(systemtesting.MantidSystemTest): 
  def _assert_output_file_exists(directory, filename):
        test.assertTrue(os.path.isfile(os.path.join(directory, filename)), msg=generate_error_message(filename, directory))
    
  def _assert_focus_output_files(ws_num):
        user_output = os.path.join(output_dir, "17_1", "Test")
        assert_output_file_exists(user_output, f"POLARIS{ws_num}.nxs")
        assert_output_file_exists(user_output, f"POLARIS{ws_num}.gsas")
        output_dat_dir = os.path.join(user_output, "dat_files")
        for bankno in range(1, 6):
            assert_output_file_exists(output_dat_dir, f"POL{ws_num}-b_{bankno}-TOF.dat")
            assert_output_file_exists(output_dat_dir, f"POL{ws_num}-b_{bankno}-d.dat")

# outside class
def _generate_error_message(expected_file, output_dir):
      return f"Unable to find {expected_file} in {output_dir}.\nContents={os.listdir(output_dir)}"
```

Then define the individual classes like so
```
class FocusTestNoAbsorptionWithAbsoluteNormalisation(focus_system_test_helper):
```

I'm pretty sure the test suite won't try to run the new base class, if you have time feel free to give it a go, otherwise happy to approve!

2025-01-10 13:50 UTC, RichardWaiteSTFC requested changes
One more thing that I should have thought about before sorry!
Can we update the Polaris reduction docs here?
https://github.com/mantidproject/mantid/blob/f81538d597c2dbc8e2e87a74b918235596262835/docs/source/techniques/ISISPowder-Polaris-v1.rst?plain=1#L361

2025-01-10 13:50 UTC, RichardWaiteSTFC commented on docs/source/release/v6.12.0/Diffraction/Powder/New_features/38535.rst
> +-  Now added an option for the vanadium normalisation for Polaris to be done either using relative (`pdf`) or absolute normalisation (`pdf_norm`). This manifests as the ability to set `mode : pdf` or
How about something like this that includes the link to the POLARIS docs?
```suggestion
-  Renamed parameter ``mode="pdf_norm"`` to :ref:`ISIS POLARIS powder reduction<isis-powder-diffraction-polaris-ref>` for when the chopper is off/stationary with a default ``van_normalisation_method="absolute"``. The existing  ``mode="pdf"`` now has a default  ``van_normalisation_method="relative"`` (was previously ``"relative"``).
```
I think linking to the docs means we can ditch the stuff about how the user can change the setting (helpful though that was).
What do you think?

2025-01-10 15:18 UTC, andy-bridger commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
It seems it does try and run the helper class, I guess because in inherits from `systemtesting.MantidSystemTest`. I can get around it by putting it within another class which doesn't inherit. This work around allows more of the repeated code to be moved to the helper but is perhaps a bit hackier? I've added it as a commit, but let me know and we can roll back to the previous format

2025-01-10 15:22 UTC, RichardWaiteSTFC commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
Oh dear sorry! That does seem to be a bit hacky - one could also set the base class test to be skipped by  overloading the skipTests method and returning True - but then this would be recorded as a skipped test!
If it's OK with you let's roll back and stick with what you had!

2025-01-13 09:52 UTC, andy-bridger commented on Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
> +        def generate_error_message(expected_file, output_dir):
Yeh, I saw that as an option but also didn't like the fact it would come up as a skipped test. Should be reverted now

2025-01-13 17:06 UTC, RichardWaiteSTFC approved these changes
Looks good thanks for the changes!

2025-01-14 09:47 UTC, RichardWaiteSTFC requested changes
Actually if you get chance could you clean up the commit history? Specifically instead of adding another separate commit to revert the previous one,  could you do `git rebase -i HEAD~4` and remove the commit(s) 
a4f39ff355a71d29f78b755d1393e84f388b586e
e0697c5b04d93f2b12112df2dccd160c4173811f

There may be another way in git, but that's what I use! It's good practice to keep it clean (I know it's my fault for suggesting changes that don't pan out!)

2025-01-14 10:06 UTC, RichardWaiteSTFC commented
> Sure, I did have a think about it before reverting and came to the conclusion that I wanted to have it in the commit history in case we changed our minds again (to still have the code accessible), but if you're happy for it to go, I am too

Thanks, if you could go ahead that'd be great. 
Btw, I see the logic in wanting to keep a record of the change in case you need it later, in that instance you can always make a new branch at HEAD before doing changes to commit history on this PR branch if you want to.

2025-01-14 16:13 UTC, RichardWaiteSTFC approved these changes
Nice work, thanks for this!

2025-01-15 10:35 UTC, merged