H5Util read 1d slices of data
mantidproject/mantid pull request #38546
Opened 2024-12-27 18:26 UTC by peterfpeterson

### Description of work

#### Summary of work

Refs #38332

#### Further detail of work

### To test:

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2025-01-06 14:55 UTC, robertapplin commented
This might not be possible, or ideal, but just thought I would float this idea with you:

Would it be possible to remove the old `readArray1DCoerce` function with two parameter arguments, and just have the one `readArray1DCoerce` function with 4 arguments (and 2 of them being optional)? It could look something like this, and might make the code simpler/less repeated code:

```c++
template <typename NumT>
void readArray1DCoerce(const H5::DataSet &dataset, std::vector<NumT> &output, const size_t length = nullptr,
                       const size_t offset = 0u) {
  DataSpace filespace = dataset.getSpace();

  if (length == nullptr) {
    length = static_cast<size_t>(filespace.getSelectNpoints());
  }

  // set extent and offset in DataSpace
  hsize_t rankedoffset[1] = {static_cast<hsize_t>(offset)};
  hsize_t rankedextent[1] = {static_cast<hsize_t>(length)};
  filespace.selectHyperslab(H5S_SELECT_SET, rankedextent, rankedoffset);

  // size of thing being read out
  DataSpace memspace(1, rankedextent);

  const DataType dataType = dataset.getDataType();
  if (getType<NumT>() == dataType) { // no conversion necessary
    output.resize(length);
    dataset.read(output.data(), dataType, memspace, filespace);
  } else if (PredType::NATIVE_INT32 == dataType) {
    convertingRead<int32_t>(dataset, dataType, output, memspace, filespace);
  } else if (PredType::NATIVE_UINT32 == dataType) {
    convertingRead<uint32_t>(dataset, dataType, output, memspace, filespace);
  } else if (PredType::NATIVE_INT64 == dataType) {
    convertingRead<int64_t>(dataset, dataType, output, memspace, filespace);
  } else if (PredType::NATIVE_UINT64 == dataType) {
    convertingRead<uint64_t>(dataset, dataType, output, memspace, filespace);
  } else if (PredType::NATIVE_FLOAT == dataType) {
    convertingRead<float>(dataset, dataType, output, memspace, filespace);
  } else if (PredType::NATIVE_DOUBLE == dataType) {
    convertingRead<double>(dataset, dataType, output, memspace, filespace);
  } else {
    // not a supported type
    throw DataTypeIException();
  }
}
```
 Perhaps this is not ideal, let me know!

2025-01-08 17:10 UTC, dmitry-ganyushin requested changes

2025-01-08 17:28 UTC, peterfpeterson commented on Framework/Nexus/src/H5Util.cpp
> +    convertingRead<int32_t>(dataset, dataType, output, memspace, filespace);
The compiler interprets that time from the actual `output` vector from the signature
```cpp
void convertingRead(const DataSet &dataset, const DataType &dataType, std::vector<OutputNumT> &output,
                    const DataSpace &memspace, const DataSpace &filespace)
```
The type in the dataset needs to be given explicitly to the compiler.

2025-01-08 17:58 UTC, dmitry-ganyushin approved these changes
Looks good.

2025-01-08 18:19 UTC, merged