added and propagated FullBinsOnly flag
mantidproject/mantid pull request #38550
Opened 2024-12-30 17:44 UTC by walshmm

### Description of work

#### Summary of work

This simply adds the FullBinsOnly parameter to RebinRagged and passes it to the appropriate functions in RebinRagged.

This change was motivated by differences observed in the outputs of the application SNAPRed, and the algorithm SNAPReduce.
It was determined that the binning had actually produced artifacts at the end of the spectra, which is most notable in how the normalization is handled.  This artifact is able to be removed via the FullBinsOnly param.

*There is no associated issue.*

### To test:

Open RebinRagged in the Workbench. Observe the new param has been exposed.
Refer to [FullBinsOnly test](https://github.com/mantidproject/mantid/blob/865df3c9f8ff86a9be717bf45595b273feca25e7/Framework/Algorithms/test/RebinTest.h#L503C2-L508C4) for how to confirm this pass through was effective for RebinRagged. 

while not a 1-1 copy of the unit test, you can still observe that this param is being passed by running the following script in workbench:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

xExpected = [0.5, 2.5, 4.5, 6.5]
yExpected = [3, 8.0]
params = "2.0"

def Create1DWorkspace(size):
    xData = []
    yData = []
    j = .5
    for i in range(0, size+1):
        xData.append(j)
        yData.append((i+1)*2)
        j = .75 + j
    yData.pop()
    ws = CreateWorkspace(xData, yData)
    return ws

inputWs = Create1DWorkspace(10)

RebinRagged(InputWorkspace=inputWs, OutputWorkspace="NotFullBinsOnly", Delta=2.0, PreserveEvents=True, FullBinsOnly=False)

RebinRagged(InputWorkspace=inputWs, OutputWorkspace="FullBinsOnly", Delta=2.0, PreserveEvents=True, FullBinsOnly=True)
```

You will see a difference if you just "View Data", one has an additional x value.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

2025-01-03 08:47 UTC, sf1919 commented
I think the doc tests are failing because the release note is missing a `-` at the beginning. See https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html#how-to-write-a-release-note for more details.

2025-01-13 16:26 UTC, yusufjimoh requested changes
Thank you for incorporating the FullBinsOnly property into the algorithm. I have reviewed the code, and everything appears to be in good order. The unit tests passed successfully, and I have tested it using both the scripts and the GUI, confirming that there are no breaking changes. The release note provided is also sufficient.

I believe we may need to update the documentation for the RebinnedRagged Algorithm to reflect these recent changes.

2025-01-14 09:04 UTC, yusufjimoh commented
@walshmm Thanks for your response, referencing the docs will be fine. We can also update the sample code in the documentation to reflect the usage of the new property.

2025-01-14 17:07 UTC, walshmm commented
@yusufjimoh I have added an additional code block and explanation to the doc page.

2025-01-15 11:48 UTC, yusufjimoh approved these changes
Thank you for updating the pull request with code and explanations on when and how to use the FullBinsOnly property. happy to approve the pull request

2025-01-15 14:29 UTC, merged